var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.polyfill=function(a,b,c,f){if(b){c=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var h=a[f];h in c||(c[h]={});c=c[h]}a=a[a.length-1];f=c[a];b=b(f);b!=f&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(a){return a instanceof h?a:new h(function(b,g){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var f=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){f(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var g=a[b];a[b]=null;try{g()}catch(k){this.asyncThrow_(k)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var h=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(g){b.reject(g)}};h.prototype.createResolveAndReject_=function(){function a(a){return function(e){g||(g=!0,a.call(b,e))}}var b=this,g=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};h.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof h)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};h.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(g){this.reject_(g);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};h.prototype.reject_=function(a){this.settle_(2,a)};h.prototype.fulfill_=function(a){this.settle_(1,a)};h.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};h.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)d.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var d=new b;h.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};h.prototype.settleSameAsThenable_=function(a,b){var g=this.createResolveAndReject_();try{a.call(b,g.resolve,g.reject)}catch(k){g.reject(k)}};h.prototype.then=function(a,b){function g(a,b){return"function"==typeof a?function(b){try{k(a(b))}catch(t){e(t)}}:b}var k,e,c=new h(function(a,b){k=a;e=b});this.callWhenSettled_(g(a,k),g(b,e));return c};
h.prototype.catch=function(a){return this.then(void 0,a)};h.prototype.callWhenSettled_=function(a,b){function g(){switch(k.state_){case 1:a(k.result_);break;case 2:b(k.result_);break;default:throw Error("Unexpected state: "+k.state_);}}var k=this;null==this.onSettledCallbacks_?d.asyncExecute(g):this.onSettledCallbacks_.push(g)};h.resolve=c;h.reject=function(a){return new h(function(b,g){g(a)})};h.race=function(a){return new h(function(b,g){for(var k=$jscomp.makeIterator(a),e=k.next();!e.done;e=k.next())c(e.value).callWhenSettled_(b,
g)})};h.all=function(a){var b=$jscomp.makeIterator(a),g=b.next();return g.done?c([]):new h(function(a,e){function k(b){return function(e){d[b]=e;f--;0==f&&a(d)}}var d=[],f=0;do d.push(void 0),f++,c(g.value).callWhenSettled_(k(d.length-1),e),g=b.next();while(!g.done)})};return h},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(c||"")+"_"+b++,c)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var c=a.next();$jscomp.generator.ensureIteratorResultIsObject_(c);if(c.done)this.yieldResult=c.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(c.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var f=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(f);if(!f.done)return this.context_.stop_(),f;var h=f.value}catch(d){return this.context_.yieldAllIterator_=null,this.context_.throw_(d),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,h);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(b){return a.next(b)}function c(b){return a.throw(b)}return new Promise(function(f,h){function d(a){a.done?f(a.value):Promise.resolve(a.value).then(b,c).then(d,h)}d(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var f=a.length,h=0;h<f;h++){var d=a[h];if(b.call(c,d,h,a))return{i:h,v:d}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");
$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,f={next:function(){if(c<a.length){var h=c++;return{value:b(h,a[h]),done:!1}}f.next=function(){return{done:!0,value:void 0}};return f.next()}};f[Symbol.iterator]=function(){return f};return f};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
$jscomp.checkEs6ConformanceViaProxy=function(){try{var a={},b=Object.create(new $jscomp.global.Proxy(a,{get:function(c,f,h){return c==a&&"q"==f&&h==b}}));return!0===b.q}catch(c){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
$jscomp.polyfill("WeakMap",function(a){function b(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),d=Object.seal({}),e=new a([[b,2],[d,3]]);if(2!=e.get(b)||3!=e.get(d))return!1;e.delete(b);e.set(d,4);return!e.has(b)&&4==e.get(d)}catch(v){return!1}}function c(){}function f(a){if(!$jscomp.owns(a,d)){var b=new c;$jscomp.defineProperty(a,d,{value:b})}}function h(a){var b=Object[a];b&&(Object[a]=function(a){if(a instanceof c)return a;f(a);return b(a)})}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&
$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;var d="$jscomp_hidden_"+Math.random();h("freeze");h("preventExtensions");h("seal");var p=0,l=function(a){this.id_=(p+=Math.random()+1).toString();if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};l.prototype.set=function(a,b){f(a);if(!$jscomp.owns(a,d))throw Error("WeakMap key fail: "+a);a[d][this.id_]=b;return this};l.prototype.get=function(a){return $jscomp.owns(a,d)?a[d][this.id_]:void 0};l.prototype.has=
function(a){return $jscomp.owns(a,d)&&$jscomp.owns(a[d],this.id_)};l.prototype.delete=function(a){return $jscomp.owns(a,d)&&$jscomp.owns(a[d],this.id_)?delete a[d][this.id_]:!1};return l},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(a){function b(){if($jscomp.ASSUME_NO_NATIVE_MAP||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),d=new a($jscomp.makeIterator([[b,"s"]]));if("s"!=d.get(b)||1!=d.size||d.get({x:4})||d.set({x:4},"t")!=d||2!=d.size)return!1;var e=d.entries(),c=e.next();if(c.done||c.value[0]!=b||"s"!=c.value[1])return!1;c=e.next();return c.done||4!=c.value[0].x||"t"!=c.value[1]||!e.next().done?!1:!0}catch(x){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;$jscomp.initSymbolIterator();var c=new WeakMap,f=function(a){this.data_={};this.head_=p();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};f.prototype.set=function(a,b){a=0===a?0:a;var e=h(this,a);e.list||(e.list=this.data_[e.id]=[]);e.entry?e.entry.value=b:(e.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,
value:b},e.list.push(e.entry),this.head_.previous.next=e.entry,this.head_.previous=e.entry,this.size++);return this};f.prototype.delete=function(a){a=h(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};f.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=p();this.size=0};f.prototype.has=function(a){return!!h(this,a).entry};
f.prototype.get=function(a){return(a=h(this,a).entry)&&a.value};f.prototype.entries=function(){return d(this,function(a){return[a.key,a.value]})};f.prototype.keys=function(){return d(this,function(a){return a.key})};f.prototype.values=function(){return d(this,function(a){return a.value})};f.prototype.forEach=function(a,b){for(var e=this.entries(),d;!(d=e.next()).done;)d=d.value,a.call(b,d[1],d[0],this)};f.prototype[Symbol.iterator]=f.prototype.entries;var h=function(a,b){var e=b&&typeof b;"object"==
e||"function"==e?c.has(b)?e=c.get(b):(e=""+ ++l,c.set(b,e)):e="p_"+b;var d=a.data_[e];if(d&&$jscomp.owns(a.data_,e))for(a=0;a<d.length;a++){var f=d[a];if(b!==b&&f.key!==f.key||b===f.key)return{id:e,list:d,index:a,entry:f}}return{id:e,list:d,index:-1,entry:void 0}},d=function(a,b){var e=a.head_;return $jscomp.iteratorPrototype(function(){if(e){for(;e.head!=a.head_;)e=e.previous;for(;e.next!=e.head;)return e=e.next,{done:!1,value:b(e)};e=null}return{done:!0,value:void 0}})},p=function(){var a={};return a.previous=
a.next=a.head=a},l=0;return f},"es6","es3");
$jscomp.polyfill("Set",function(a){function b(){if($jscomp.ASSUME_NO_NATIVE_SET||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),c=new a($jscomp.makeIterator([b]));if(!c.has(b)||1!=c.size||c.add(b)!=c||1!=c.size||c.add({x:4})!=c||2!=c.size)return!1;var d=c.entries(),p=d.next();if(p.done||p.value[0]!=b||p.value[1]!=b)return!1;p=d.next();return p.done||p.value[0]==b||4!=p.value[0].x||p.value[1]!=p.value[0]?!1:d.next().done}catch(l){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;$jscomp.initSymbolIterator();var c=function(a){this.map_=new Map;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)this.add(b.value)}this.size=this.map_.size};c.prototype.add=function(a){a=0===a?0:a;this.map_.set(a,a);this.size=this.map_.size;return this};c.prototype.delete=function(a){a=this.map_.delete(a);this.size=this.map_.size;return a};c.prototype.clear=function(){this.map_.clear();
this.size=0};c.prototype.has=function(a){return this.map_.has(a)};c.prototype.entries=function(){return this.map_.entries()};c.prototype.values=function(){return this.map_.values()};c.prototype.keys=c.prototype.values;c.prototype[Symbol.iterator]=c.prototype.values;c.prototype.forEach=function(a,b){var d=this;this.map_.forEach(function(c){return a.call(b,c,c,d)})};return c},"es6","es3");
$jscomp.polyfill("Object.values",function(a){return a?a:function(a){var b=[],f;for(f in a)$jscomp.owns(a,f)&&b.push(a[f]);return b}},"es8","es3");$jscomp.polyfill("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,c){var b=this;b instanceof String&&(b=String(b));var h=b.length;c=c||0;for(0>c&&(c=Math.max(c+h,0));c<h;c++){var d=b[c];if(d===a||Object.is(d,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,c){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,c||0)}},"es6","es3");
(function(a){(a.SafeWeb=a.SafeWeb||{}).constants={SHASTA_URL:"https://ratings-wrs.symantec.com",SHASTA_LOOKUP_PATH:"brief",DEFAULT_FULL_REPORT_URL:"https://safeweb.norton.com/report/show",HTTP_PROTOCOL:"http",HTTPS_PROTOCOL:"https",HTTPS_GET_METHOD:"GET",HTTPS_POST_METHOD:"POST",PII_SUBMISSION_TIMEOUT:2E3,SCAM_INSIGHT_BLOCK_PAGE_PATH:"content/ui/scam-insight-block-page.html",BLOCK_PAGE_PATH:"content/ui/blockedPage.html",SYMC_USER_AGENT:"X-Symc-User-Agent",WRS_HEADER_VALUES:{XBP_SAFEWEB:"xBP/SafeWeb",
XBP_SAFEWEB_YAHOO:"xBP/SafeWeb_Yahoo",XBP_SAFEWEB_YAHOO_ADVT:"xBP/SafeWeb_Yahoo_Advt"},ROOT_NODE:{TAG_NAME:"symantec",VERSION_ATTR:"v",CACHE_POSITIVE_ATTR:"cacheP",CACHE_NEGATIVE_ATTR:"cacheN"},PII_FLAGS:{EXIT_SITE:0,CONTINUE_TO_SITE:1,SUPPRESSED_DUE_TO_SILENTMODE:2,SUPPRESSED_DUE_TO_HTTPS:4},PII_SUBMISSION_STATUS:{SUCCESS:"Success",FAILURE:"Fail"},SITE_NODE:{TAG_NAME:"site",CANONICAL_SITE_ID_ATTR:"id",COMBINED_RATING_ATTR:"r",SECURITY_RATING_ATTR:"sr",BUSINESS_RATING_ATTR:"br",CACHE_ATTR:"cache",
PII_ENABLE_ATTR:"piien",PII_POLICY_HTTPS:"piipolhttps",PII_POLICY_ID:"piipolid",PII_POLICY_FIELD_TYPE:"piipolft"},WRS_RATINGS:{UNKNOWN_SITE:"u",BAD_SITE:"b",WARNING_SITE:"w",GOOD_SITE:"g",NORTON_SECURE_SITE:"r",PII_NOT_ENABLED:"n",PII_ENABLED:"y",PII_SILENCE:"s"},ANNOYANCE_FACTORS_KEYS:{PUAPP:!0,HRDUN:!0,JOKE:!0,MLAPP:!0,TRCKW:!0,TPSQT:!0,PPCNA:!0,HACK:!0,SPAM:!0,SWBPL:!0},PII_FACTORS_KEYS:{PIIAGE:"age",PIIPOP:"pop"},PII_POLICY_HTTPS_KEYS:{DONTCARE:"dc",HTTPS:"h"},IDENTITY_THREATS_KEYS:{MLWR:!0,MBCHG:!0,
RMTA:!0,PHISH:!0,BDOOR:!0,ISTLR:!0,DIAL:!0,DLDR:!0,SPWR:!0},SHOPPING_RISKS_KEYS:{CTFGS:!0,RCGS:!0,REPLC:!0},COMPUTER_THREATS_KEYS:{COHD:!0,ADWR:!0,VIRUS:!0,WORM:!0,SRISK:!0,BREXP:!0,MLWR:!0,MBCHG:!0,HEUR:!0,ELTMS:!0,TRJN:!0},SITE_FACT_NODE:{TAG_NAME:"d",REPORTED_BY_KEY:"reported_by",SRC_KEY:"src",ID_KEY:"id"},SITE_FACT_IDS:{PRIVACY_POLICY_APPROVED:"privacy policy approved",NETWORK_SCANNING_SERVICE:"network scanning service",SSL_CA_NAME:"ssl CA name",AUTHORIZED_RESELLER:"Authorized Reseller",CERTIFIED_BUSINESS:"certified business",
VERISIGN_TRUSTED:"VRTRU",VERISIGN_SSL:"VRSSL"},SITE_FACT_SOURCES:{SRC_BUYSAFE:"BUYSAFE",SRC_VERISIGN:"Verisign",SRC_MARK_MONITOR:"MARKMONITOR"},ATTRIBUTE_COUNT:"cnt",CACHE_LIMIT:1E3,RATING_TYPE:{WCID_HEURISTICS:1,WCID_CHECK_URL:2,SAFEWEB:3,SCAM_INSIGHT:4},MESSAGES:{WAX_FIELDS_FOUND:"45E6BAD1-9F79-4E16-BA3A-1F77AA21EAC9",PROCESS_PAGE_FOR_SCAM_FIELDS:"FEDA41BC-73DC-4F99-A2CF-B5589CF2D0F8",TOP_FRAME_UNLOADED:"E5C199FF-A74B-414F-803C-4C7030C0E573",CAN_ANALYZE_FOR_SCAM:"6E6CDFB7-4CF6-4C73-B998-6CA3432DDC07"},
IS_SCAM_INSIGHT_ENABLED:!0,performanceReporter:{COMPONENT:{SCAM_INSIGHT:"scam_insight"},TYPE:{INIT:"init",PII_PROTO_SUBMISSION:"_piiProtoSubmission",CALCULATE_SCAM_RATING:"_calculateScamInsightRating",HANDLE_PII_RATING:"_handlePIIEnabledRating",SET_WRS_RESPONSE:"setWrsResponse",HANDLE_MESSAGE:"_handleMessage",HANDLE_MESSAGE_CALLBACK:"_handleScamPageFoundCallback",HANDLE_CACHE_RESPONSE:"_handleCacheResponse",SEND_PII_SUBMISSION:"sendPIISubmission",COLLECT_PII_FIELDS:"_collectPIIFields",TOP_FRAME_UNLOADED:"topFrameUnloaded",
ADD_MUTATION_OBSERVER:"_addBodyMutationObserver",FIELD_FOUND_CALLBACK:"handleFieldsFoundCallback",WAX_CONTROLLER_INITIALIZE:"scamInsightWaxControllerInitialize",CAN_ANALYZE_HANDLER_RESPONSE:"canAnalyzeForScamHandlerResponse",RUN_WAX_ANALYSIS:"_runWaxAnalysis"}},SCAM_INSIGHT_RESULT:{UNTESTED:0,SUSPICIOUS_PAGE:1,SUSPICIOUS_NO_BLOCK_PAGE:2,NOT_SUSPICIOUS_PAGE:3},SCAM_INSIGHT_RATING_KEY:"scamRating",SCAM_ANALYSIS_STATE:{PENDING:0,ANALYZE:1},YAHOO_DOMAIN:"yahoo.com",HSPART_KEY:"hspart",HSPART_VALUE:"symantec"}})(executionContext);
(function(a){a.SafeWeb.telemetryWrapper=function(a,c){var b={},h=a.utils.isString,d=a.telemetryConstants;b.TELEMETRY_CATEGORY={SCAM_INSIGHT:"Scam_Insight"};b.actionType={PROTO:{PII_SUBMISSION:"PII_Submission"}};b.sendPIISubmissionStatusEvent=function(a){if(!h(a))return null;b.send(b.TELEMETRY_CATEGORY.SCAM_INSIGHT,b.actionType.PROTO.PII_SUBMISSION,a)};b.send=function(b,c,g){if(!h(b)||!h(c)||!h(g))return null;var k={};k[d.parameters.HIT_TYPE]=d.HIT_TYPE.EVENT;k[d.parameters.CATEGORY]=b;k[d.parameters.ACTION]=
c;k[d.parameters.LABEL]=g;(a.telemetry||a.telemetryProxy).send(k)};return b}(a.SymBfw,a.SafeWeb)})(executionContext);
(function(a){a.SafeWeb.Rating=function(a){var b=a.utils.isNil,f=a.utils.isArray,h=SafeWeb.constants,d=a.utils,p=a.localizer,l=a.utils.isInteger,g=a.utils.isString,k=SafeWeb.constants,e=function(d){if(b(d))throw Error("Input dictionary cannot be null");var c=e.ratingSchema,g;for(g in c){var k=c[g],f=d[g];if(b(f)){if(k.isRequired)throw Error("Cannot find value for key "+g+" in the input dictionary.");if(b(k.defaultValue))throw Error("Default value has not been supplied in the Schema.");this[g]=k.defaultValue}else{k=
k.typeChecker;if(!1===k(f))throw Error("Input value for key "+g+" does not match schema.");this[g]=f}}this.id=a.utils.createNewGuid()};e._checkPIISchema=function(a){return g(a.piiEnable)?k.WRS_RATINGS.PII_ENABLED!==a.piiEnable&&k.WRS_RATINGS.PII_SILENCE!==a.piiEnable?!0:g(a.piiPolHttps)&&g(a.piiPolID)&&f(a.piiFieldType)&&l(a.age)&&l(a.pop)?!0:!1:!1};e.ratingSchema={computerThreats:{isRequired:!1,typeChecker:d.isInteger,defaultValue:0},annoyanceFactors:{isRequired:!1,typeChecker:d.isInteger,defaultValue:0},
identityThreats:{isRequired:!1,typeChecker:d.isInteger,defaultValue:0},shoppingRisks:{isRequired:!1,typeChecker:d.isInteger,defaultValue:0},phishingThreats:{isRequired:!1,typeChecker:d.isInteger,defaultValue:0},siteRating:{isRequired:!0,typeChecker:d.isInteger},fullURL:{isRequired:!0,typeChecker:d.isString},normalizedURL:{isRequired:!0,typeChecker:d.isString},cacheTime:{isRequired:!1,typeChecker:d.isInteger,defaultValue:0},piiAttributes:{isRequired:!1,typeChecker:e._checkPIISchema,defaultValue:{piiEnable:k.WRS_RATINGS.PII_NOT_ENABLED}},
scamRating:{isRequired:!1,typeChecker:d.isInteger,defaultValue:h.SCAM_INSIGHT_RESULT.UNTESTED}};e.prototype.getComputerThreats=function(){return this.computerThreats};e.prototype.getAnnoyanceFactors=function(){return this.annoyanceFactors};e.prototype.getIdentityThreats=function(){return this.identityThreats};e.prototype.getShoppingRisks=function(){return this.shoppingRisks};e.prototype.getPhishingThreats=function(){return this.phishingThreats};e.prototype.getFullReportURL=function(){return h.DEFAULT_FULL_REPORT_URL+
"?url="+this.getFullURL()+"&ulang="+p.getLocale()};e.prototype.getSiteRating=function(){return this.siteRating};e.prototype.getFullURL=function(){return this.fullURL};e.prototype.getNormalizedURL=function(){return this.normalizedURL};e.prototype.getID=function(){return this.id};e.prototype.getCacheTime=function(){return this.cacheTime};e.prototype.getPIIEnValue=function(){return this.piiAttributes.piiEnable};e.prototype.getPIIPolID=function(){return b(this.piiAttributes.piiPolID)?null:this.piiAttributes.piiPolID};
e.prototype.getPIIHTTPS=function(){return b(this.piiAttributes.piiPolHttps)?null:this.piiAttributes.piiPolHttps};e.prototype.getPIIFieldType=function(){return b(this.piiAttributes.piiFieldType)?[]:this.piiAttributes.piiFieldType};e.prototype.getPIIAge=function(){return b(this.piiAttributes.age)?0:this.piiAttributes.age};e.prototype.getPIIPop=function(){return b(this.piiAttributes.pop)?0:this.piiAttributes.pop};e.prototype.getScamRating=function(){return this.scamRating};e.prototype.serialize=function(){return JSON.stringify(this)};
e.SITE_RATING={SW_INVALID_STATE:0,SW_TRUSTED_STATE:1,SW_NEUTRAL_STATE:2,SW_KNOWN_PHISHING_STATE:3,SW_SUSPECTED_PHISHING_STATE:4,SW_KNOWN_MALICIOUS_STATE:5,SW_CAUTION_MALICIOUS_STATE:6,SW_NORTON_CERTIFIED:7,SW_TRUSTED_TRANSACTION_STATE:8,SW_UNTRUSTED_TRANSACTION_STATE:9,SW_PAGE_BAD_UNTRUSTED_TRANSACTION_STATE:10,SW_DISABLED_STATE:11,SW_UNLICENSED_STATE:12,SW_ERROR_STATE:13,SW_PENDING_STATE:14,SW_MAX_STATE:15};return e}(a.SymBfw)})(executionContext);
(function(a){a.SafeWeb.WrsParser=function(a){var b=a.utils.isNil,f=a.utils.isntNil,h=a.utils.isEmptyObject,d=SafeWeb.constants,p=a.logger,l=SafeWeb.Rating;a=function(){this._rootDict={cacheP:600,cacheN:600}};a.prototype.parseWRSResponse=function(a,d){if(b(a))return null;if(b(d))throw Error("URL Array cannot be null.");a=$(a);a=this.parseRootNode(a);return b(a)?null:this.parseSiteInformation(a,d)};a.prototype.parseSiteInformation=function(a,c){a=a.find(d.SITE_NODE.TAG_NAME);var e=a.length;if(0===e)return null;
if(c.length!==e)return p.error("Lengths of input URL Array("+c.length+") and Shasta results("+e+") do not match."),null;for(var k=[],g=0;g<e;g++){var f=a[g],r=f.attributes,t=r.length,n={},u=!1,m={};n.fullURL=c[g];var w=0;for(w=0;w<t;w++){var q=r.item(w);switch(q.nodeName){case d.SITE_NODE.CANONICAL_SITE_ID_ATTR:n.normalizedURL=q.value;break;case d.SITE_NODE.COMBINED_RATING_ATTR:n.combinedRating=q.value;break;case d.SITE_NODE.SECURITY_RATING_ATTR:n.securityRating=q.value;u=!0;break;case d.SITE_NODE.BUSINESS_RATING_ATTR:n.shoppingRating=
q.value;break;case d.SITE_NODE.CACHE_ATTR:n.cacheTime=Number(q.value);break;case d.SITE_NODE.PII_ENABLE_ATTR:m.piiEnable=q.value;break;case d.SITE_NODE.PII_POLICY_HTTPS:m.piiPolHttps=q.value;break;case d.SITE_NODE.PII_POLICY_ID:m.piiPolID=q.value;break;case d.SITE_NODE.PII_POLICY_FIELD_TYPE:q=q.value,"*"===q?m.piiFieldType=["*"]:(q=q.split(",").map(Number),m.piiFieldType=q.filter(function(a){return!isNaN(a)}))}}n.piiAttributes=m;h(n.piiAttributes)&&(n.piiAttributes.piiEnable=d.WRS_RATINGS.PII_NOT_ENABLED);
b(n.normalizedURL)&&(n.normalizedURL="");b(n.combinedRating)&&(n.combinedRating=d.WRS_RATINGS.UNKNOWN_SITE);b(n.securityRating)&&(n.securityRating=d.WRS_RATINGS.UNKNOWN_SITE);b(n.shoppingRating)&&(n.shoppingRating=d.WRS_RATINGS.UNKNOWN_SITE);b(n.cacheTime)&&(n.cacheTime=!1===u?this._rootDict.cacheN:this._rootDict.cacheP);n.siteRating=this.getSiteRating(n.securityRating,n.shoppingRating);this.parseSiteAttributes($(f),n);f=new l(n);k.push(f)}return k};a.prototype.parseSiteAttributes=function(a,c){a=
a.children();for(var e=a.length,g=0,k=0,h=0,l=0,p=0;p<e;p++){var n=a.get(p),u=n.nodeName;n=n.attributes;f(d.ANNOYANCE_FACTORS_KEYS[u])&&(k+=Number(n[d.ATTRIBUTE_COUNT].value));f(d.IDENTITY_THREATS_KEYS[u])&&(h+=Number(n[d.ATTRIBUTE_COUNT].value));f(d.SHOPPING_RISKS_KEYS[u])&&(l+=Number(n[d.ATTRIBUTE_COUNT].value));f(d.COMPUTER_THREATS_KEYS[u])&&(g+=Number(n[d.ATTRIBUTE_COUNT].value));f(d.PII_FACTORS_KEYS[u])&&(b(c.piiAttributes)&&(c.piiAttributes={}),c.piiAttributes[d.PII_FACTORS_KEYS[u]]=Number(n[d.PII_FACTORS_KEYS[u]].value))}c.computerThreats=
g;c.annoyanceFactors=k;c.identityThreats=h;c.shoppingRisks=l};a.prototype.getSiteRating=function(a,b){if(a===d.WRS_RATINGS.NORTON_SECURE_SITE)return l.SITE_RATING.SW_NORTON_CERTIFIED;if(a===d.WRS_RATINGS.GOOD_SITE){if(b===d.WRS_RATINGS.GOOD_SITE)return l.SITE_RATING.SW_TRUSTED_TRANSACTION_STATE;if(b===d.WRS_RATINGS.UNKNOWN_SITE)return l.SITE_RATING.SW_TRUSTED_STATE}return a===d.WRS_RATINGS.BAD_SITE?b===d.WRS_RATINGS.BAD_SITE?l.SITE_RATING.SW_PAGE_BAD_UNTRUSTED_TRANSACTION_STATE:l.SITE_RATING.SW_KNOWN_MALICIOUS_STATE:
b===d.WRS_RATINGS.WARNING_SITE||b===d.WRS_RATINGS.BAD_SITE?l.SITE_RATING.SW_UNTRUSTED_TRANSACTION_STATE:a===d.WRS_RATINGS.WARNING_SITE?l.SITE_RATING.SW_CAUTION_MALICIOUS_STATE:l.SITE_RATING.SW_NEUTRAL_STATE};a.prototype.parseRootNode=function(a){a=a.find(d.ROOT_NODE.TAG_NAME);if(0===a.length)return null;for(var b=a[0].attributes,e=b.length,c=0;c<e;c++){var f=b.item(c);switch(f.nodeName){case d.ROOT_NODE.VERSION_ATTR:this._rootDict[d.ROOT_NODE.VERSION_ATTR]=f.value;break;case d.ROOT_NODE.CACHE_POSITIVE_ATTR:this._rootDict[d.ROOT_NODE.CACHE_POSITIVE_ATTR]=
Number(f.value);break;case d.ROOT_NODE.CACHE_NEGATIVE_ATTR:this._rootDict[d.ROOT_NODE.CACHE_NEGATIVE_ATTR]=Number(f.value)}}return a};return a}(a.SymBfw)})(executionContext);
(function(a){a.SafeWeb.connection=function(a){var b={},f=a.utils.isNil,h=a.utils.isntNil,d=a.utils.isFunction,p=a.utils.isArray,l=SafeWeb.constants,g=SafeWeb.WrsParser;b.getResultForURL=function(a,e){if(f(a))throw Error("URL cannot be null");if(!1===d(e))throw Error("Shasta Connection callback cannot be null");var c=encodeURIComponent(SafeWeb.cache.safeURL(a));c=l.SHASTA_URL+"/"+l.SHASTA_LOOKUP_PATH+"?url="+c;var k=b.constructHeader({senderURL:a,methodType:l.HTTPS_GET_METHOD});b.shastaConnection(c,
l.HTTPS_GET_METHOD,function(b){var d=b.target.status,c=b.target.responseXML;if(200===d){var f=(new g).parseWRSResponse(c,[a]);SafeWeb.cache.addRatingsToCache(f);setTimeout(function(){e(d,f)},1)}else setTimeout(function(){e(d,b)},1)},k)};b.constructHeader=function(a){var b={};if(h(a))switch(a.methodType){case l.HTTPS_GET_METHOD:b[l.SYMC_USER_AGENT]=l.WRS_HEADER_VALUES.XBP_SAFEWEB;break;case l.HTTPS_POST_METHOD:if(h(a.senderURL)){var d=new URI(a.senderURL),c=d.domain();d=d.query(!0);h(d)&&c===l.YAHOO_DOMAIN&&
d[l.HSPART_KEY]===l.HSPART_VALUE&&(f(a.bAdvtFlag)?b[l.SYMC_USER_AGENT]=l.WRS_HEADER_VALUES.XBP_SAFEWEB_YAHOO:b[l.SYMC_USER_AGENT]=l.WRS_HEADER_VALUES.XBP_SAFEWEB_YAHOO_ADVT)}break;default:b[l.SYMC_USER_AGENT]=l.WRS_HEADER_VALUES.XBP_SAFEWEB}return b};b.getResultsForURLs=function(a,e,c){if(!1===p(a))throw Error("URL Array cannot be null");if(0===a.length)throw Error("URL Array length cannot be null");if(!1===d(e))throw Error("Shasta Connection callback cannot be null");if(f(c))throw Error("Payload cannot null");
var h=l.SHASTA_URL+"/"+l.SHASTA_LOOKUP_PATH,k="",r;for(r in a)k+=a[r]+"\r\n";c.methodType=l.HTTPS_POST_METHOD;c=b.constructHeader(c);b.shastaConnection(h,l.HTTPS_POST_METHOD,function(b){var d=b.target.status,c=b.target.responseXML;if(200===d){var f=(new g).parseWRSResponse(c,a);SafeWeb.cache.addRatingsToCache(f);setTimeout(function(){e(d,f)},1)}else setTimeout(function(){e(d,b)},1)},c,k)};b.shastaConnection=function(a,b,c,g,l){if(f(a))throw Error("API URL cannot be null");if(f(b))throw Error("HTTP Method cannot be null");
if(!1===d(c))throw Error("Shasta Callback cannot be null");var e=new XMLHttpRequest;e.open(b,a,!0);e.addEventListener("load",function(a){c(a)});e.addEventListener("error",function(a){c(a)});h(g)&&Object.keys(g).forEach(function(a,b){e.setRequestHeader(a,g[a])});e.send(l)};return b}(a.SymBfw)})(executionContext);
(function(a){a=a.SafeWeb.ScamInsightPII=a.SafeWeb.ScamInsightPII||{};var b=dcodeIO.ProtoBuf.newBuilder({})["import"]({"package":"PIIFeatureTelem",options:{optimize_for:"LITE_RUNTIME"},messages:[{name:"ScamInsight_PII_Submission_List",fields:[{rule:"optional",type:"uint32",name:"Version",id:1,options:{"default":1}},{rule:"optional",type:"bytes",name:"Enterprise_GUID",id:2},{rule:"optional",type:"bytes",name:"Machine_GUID",id:3},{rule:"optional",type:"bytes",name:"Machine_CAT",id:4},{rule:"optional",
type:"string",name:"ProductName",id:5,options:{"default":""}},{rule:"optional",type:"string",name:"ProductVersion",id:6,options:{"default":""}},{rule:"repeated",type:"Submission_Type",name:"Submission",id:7}],messages:[{name:"Submission_Type",fields:[{rule:"optional",type:"int64",name:"UTCTime",id:1},{rule:"optional",type:"sint32",name:"LocalTZUTCOffset",id:2},{rule:"optional",type:"string",name:"Site_URL",id:3},{rule:"optional",type:"string",name:"Referrer_URL",id:4},{rule:"optional",type:"string",
name:"FormAction_URL",id:5},{rule:"optional",type:"string",name:"PII_PolicyID",id:6},{rule:"repeated",type:"uint32",name:"Form_Fields",id:7},{rule:"optional",type:"uint32",name:"PII_Flags",id:8}]}]}],enums:[{name:"ScamInsight_PII_FlagValues",values:[{name:"SCAMINSIGHT_PII_CONTINUED_TO_PAGE",id:1},{name:"SCAMINSIGHT_PII_SUPPRESSEDDUETOSILENTMODE",id:2},{name:"SCAMINSIGHT_PII_SUPPRESSEDDUETOHTTPS",id:4}]}]}).build();a.proto=b})(executionContext);
(function(a){a.SafeWeb.piiprotoutils=function(a){var b={},f=SafeWeb.ScamInsightPII.proto.PIIFeatureTelem.ScamInsight_PII_Submission_List,h=f.Submission_Type,d=a.utils.isNil,p=a.utils.isArray,l=a.utils.isEmptyObject,g=a.utils.isString,k=a.utils.urlWithoutQueryParameters,e="1.0.0",v=function(){this.piiSubmissionItem={UNIX_TIME:null,OFFSET_TIME:null,SITE_URL:null,REFERRER_URL:null,FORM_ACTION_URL:null,PII_POLICYID:null,FORM_FIELDS:null,PII_FLAGS:null}};v.prototype.setSubmissionTime=function(){var a=
new Date;this.piiSubmissionItem.UNIX_TIME=a.getTime();this.piiSubmissionItem.OFFSET_TIME=a.getTimezoneOffset()};v.prototype.setSiteUrl=function(a){a=k(a);a=encodeURIComponent(a);this.piiSubmissionItem.SITE_URL=a};v.prototype.isValidPIISubmissionData=function(){return d(this.piiSubmissionItem.UNIX_TIME)||d(this.piiSubmissionItem.OFFSET_TIME)||l(this.piiSubmissionItem.SITE_URL)||!g(this.piiSubmissionItem.SITE_URL)||l(this.piiSubmissionItem.PII_POLICYID)||!g(this.piiSubmissionItem.PII_POLICYID)||!p(this.piiSubmissionItem.FORM_FIELDS)||
d(this.piiSubmissionItem.PII_FLAGS)?!1:!0};b._fillPIIItem=function(a,b){l(a.piiSubmissionItem.REFERRER_URL)||b.setReferrerURL(encodeURIComponent(a.piiSubmissionItem.REFERRER_URL));l(a.piiSubmissionItem.FORM_ACTION_URL)||b.setFormActionURL(encodeURIComponent(a.piiSubmissionItem.FORM_ACTION_URL));var e=dcodeIO.Long.fromNumber(a.piiSubmissionItem.UNIX_TIME);b.setUTCTime(e);b.setLocalTZUTCOffset(a.piiSubmissionItem.OFFSET_TIME);b.setSiteURL(a.piiSubmissionItem.SITE_URL);b.setPIIPolicyID(a.piiSubmissionItem.PII_POLICYID);
b.setFormFields(a.piiSubmissionItem.FORM_FIELDS);b.setPIIFlags(a.piiSubmissionItem.PII_FLAGS)};b.setPIIProductVersion=function(a){if(!g(a))throw Error("Invalid string");e=a};b._createPIIList=function(a){var d=new f,c=new h;d.setVersion(1);d.setProductName("NSSS");d.setProductVersion(e);b._fillPIIItem(a,c);d.setSubmission(c);return d};b.submitShastaPII=function(a){var e,c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){if(1==f.nextAddress){if(!(a instanceof v))throw Error("Invalid PII Object");
if(!a.isValidPIISubmissionData())throw Error("Invalid PII Submission Data");e=b._createPIIList(a);if(d(e))throw Error("PII Creation Failed");c=e.toArrayBuffer();if(d(c))throw Error("Invalid Serialized Message");return f.yield(b._sendPIIDataToShasta(c),2)}return f.return(f.yieldResult)})};b._sendPIIDataToShasta=function(b){var e,d,c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){if(1==f.nextAddress)return e={"Content-Type":"application/x-protobuf"},d={method:"POST",headers:e,body:b},
f.setCatchFinallyBlocks(2),f.yield(fetch("https://shasta-clt.symantec.com/incident-pii/1",d),4);if(2!=f.nextAddress){c=f.yieldResult;if(c.status!==a.constants.httpStatusCodes.OK)throw Error("PII Submission Failed");return f.return()}f.enterCatchBlock();throw Error("PII Submission Failed");})};b.getPIISUbmissionObj=function(){return new v};return b}(a.SymBfw)})(executionContext);
(function(a){a.SafeWeb.cache=function(b){var c=b.utils.isNil,f=b.utils.isntNil,h=b.utils.isEmptyObject,d=b.logger,p=SafeWeb.constants,l=SafeWeb.connection,g={_normalizedURLToRatingsMap:{},_cachedURLs:0,safeURL:function(a){a=new URI(a);return a.protocol()+"://"+a.hostname()+a.pathname()},addRatingsToCache:function(a){if(c(a)||0===a.length)throw Error("Ratings array cannot be null or empty");var b=function(a,b){setTimeout(function(){g.removeRatingFromCache(a)},b)},f;for(f in a){if(g._cachedURLs>=p.CACHE_LIMIT)break;
var h=a[f];if(!c(h)){var l=h.getCacheTime();if(0!==l){var k=h.getNormalizedURL(),t=null;c(k)||0===k.length?(t=g.safeURL(h.getFullURL()),d.error("Normalized URL cannot not be null or empty:"+t)):(c(g._normalizedURLToRatingsMap[k])?g._cachedURLs++:t=g.safeURL(h.getFullURL()),g._normalizedURLToRatingsMap[k]=h,b(k,1E3*l))}}}},removeRatingFromCache:function(a){if(c(a))throw Error("Normalized URL cannot be null");delete g._normalizedURLToRatingsMap[a];g._cachedURLs--},getRatingForURL:function(a,b){var d=
g.ratingForCachedURL(a);f(d)?setTimeout(function(){b(d)},1):l.getResultForURL(a,function(a,d){var e=200===a?d[0]:null;setTimeout(function(){b(e)},1)})},ratingForCachedURL:function(b){if(h(g._normalizedURLToRatingsMap))return null;var d=new URI(b);do{var c=d.hostname(),l=d.domain();var k=d.segment();var p=d.pathname(),t=k.length,n=0;do{k=c+p;k=g._normalizedURLToRatingsMap[k];if(f(k))break;p=p.slice(0,p.lastIndexOf("/"));n++}while(n<t);if(!f(k)){if(!0===d.is("IP")&&(k=g._normalizedURLToRatingsMap[c],
f(k)))break;c=d.subdomain();if(f(c)&&0<c.length){p=c.split(".").length;t=0;do{k=c+"."+l;k=g._normalizedURLToRatingsMap[k];if(f(k))break;c=c.slice(c.indexOf(".")+1,c.length);t++}while(t<p);if(f(k))break}k=l;k=g._normalizedURLToRatingsMap[k]}}while(0);d=null;f(k)&&(d=JSON.parse(JSON.stringify(k)),d.fullURL=b,d=new a.SafeWeb.Rating(d));return d},getRatingsForURLs:function(a,b,d){var e=[];e.length=a.length;var h={},k=[],p;for(p in a){var n=a[p];if(c(n))e[p]=null;else{var u=g.ratingForCachedURL(n);f(u)?
e[p]=u:(h[k.length]=p,k.push(n))}}0===k.length?setTimeout(function(){b(e)},1):l.getResultsForURLs(k,function(a,d){if(200===a)for(var c in d)e[h[c]]=d[c];setTimeout(function(){b(e)},1)},d)},updateCacheRatingsForUrl:function(a){if(!c(a)){var b=a.getNormalizedURL();c(b)||0===b.length?d.log("Normalized url for this newRating is null, dont proceed further to alter in this case"):f(g._normalizedURLToRatingsMap[b])&&(g._normalizedURLToRatingsMap[b]=a)}}};return g}(a.SymBfw)})(executionContext);
(function(a){a.SafeWeb.manager=function(a){var b=SafeWeb.cache,f=a.utils.isNil,h=a.utils.isFunction,d={getRatingForURL:function(a,c){if(f(a))throw Error("URL array cannot be null or empty.");if(!1===h(c))throw Error("Callback function cannot be null.");!1===d.validateURL(a)?setTimeout(function(){c(null)},1):b.getRatingForURL(a,c)},getRatingsForURLs:function(a,c,g){if(f(a)||0===a.length)throw Error("URL array cannot be null or empty.");if(!1===h(c))throw Error("Callback function cannot be null.");
for(var k in a)!1===d.validateURL(a[k])&&(a[k]=null);b.getRatingsForURLs(a,c,g)},validateURL:function(a){if(f(a))return!1;var b=new URI(a);a=b.protocol();b=b.hostname();return 0===a.length||0===b.length?!1:"http"===a||"https"===a?!0:!1}};return d}(a.SymBfw)})(executionContext);
(function(a){a.SafeWeb.scamInsightUtility=function(a,c){var b=a.utils.urlWithoutQueryParameters,h=a.utils.isEmptyObject,d={};d._viewAnywayCache=new Set;d.addToViewAnywayCache=function(a){h(a)||(a=b(a),d._viewAnywayCache.has(a)||(d._viewAnywayCache.add(a),setTimeout(d._removeFromViewCache,18E5,a)))};d._removeFromViewCache=function(b){a.logger.debug("Removing from view cache : "+b);d._viewAnywayCache.delete(b)};d.isURLInViewAnywayCache=function(a){if(h(a))return!1;a=b(a);return d._viewAnywayCache.has(a)};
return d}(a.SymBfw,a.SafeWeb)})(executionContext);
(function(a){a.SafeWeb.scamInsightMgr=function(a,c){var b=a.extensionAdapter,h=a.utils.isEmptyObject,d=a.utils.isNil,p=a.utils.isntNil,l=a.utils.isArray,g=a.utils.isInteger,k=a.utils.isString,e=c.constants,v=a.telemetrySettings,x=c.piiprotoutils,y=a.utils.urlProtocol,r=a.logger,t=a.utils.isFunction,n=a.performanceReporterFactory,u=c.piiprotoutils,m={initialize:function(){if(e.IS_SCAM_INSIGHT_ENABLED){var a=e.performanceReporter.TYPE.INIT+":"+Date.now();n.reportStartForComponent(e.performanceReporter.COMPONENT.SCAM_INSIGHT,
a);m._processedTabFields=new Map;m._PIISubmissionInfo=new Map;m._scamPageFoundCallback=null;b.addMessageListener(m._handleMessage);b.addTabRemovedEventListener(m._handleTabClose);n.reportStopForComponent(e.performanceReporter.COMPONENT.SCAM_INSIGHT,a)}},registerEventCallback:function(a){if(!t(a))throw Error("Invalid Callback function");m._scamPageFoundCallback=a},setVersion:function(a){if(!k(a))throw Error("Invalid string");u.setPIIProductVersion(a)},_getSITabInfo:function(a){var b=m._processedTabFields.get(a);
d(b)&&(b=new Map,b.set("waxFieldsInfo",new Set),b.set("wrsScamResponse",{}),b.set("matchedFields",new Set),b.set("piiSubmissionTimer",0),b.set("piiFlag",0),b.set("piiSubmitted",!1),b.set("scamInsightBlockPageHandled",!1),m._processedTabFields.set(a,b));return b},_collectPIIFields:function(a,b){if(g(a)&&l(b)&&!(0>=b.length)){var d=e.performanceReporter.TYPE.COLLECT_PII_FIELDS+":"+Date.now();n.reportStartForComponent(e.performanceReporter.COMPONENT.SCAM_INSIGHT,d);var c=m._getSITabInfo(a),f=c.get("waxFieldsInfo"),
q=f.size;b.every(function(a){return f.add(a)});var h=f.size;m._processedTabFields.set(a,c);r.debug("Received WAX fields for tabID : "+a+" arrPIIFields : "+b);r.debug("Processed Tab fields map after wax update : "+a);r.debug(m._processedTabFields.get(a));h>q&&m._calculateScamInsightRating(a);n.reportStopForComponent(e.performanceReporter.COMPONENT.SCAM_INSIGHT,d)}},_getMatchedFields:function(a,b){return d(b)||0===b.size||d(a)||0===a.size?new Set:a.has("*")?b:new Set([].concat($jscomp.arrayFromIterable(a)).filter(function(a){return b.has(a)}))},
_piiProtoSubmission:function(a,b,f){if(!v.isTelemetryEnabled())return null;var g=x.getPIISUbmissionObj();if(h(g)||d(f)||0===f.size)return null;var q=e.performanceReporter.TYPE.PII_PROTO_SUBMISSION+":"+Date.now();n.reportStartForComponent(e.performanceReporter.COMPONENT.SCAM_INSIGHT,q);var k=a.getFullURL();a=a.getPIIPolID();g.setSiteUrl(k);g.setSubmissionTime();g.piiSubmissionItem.PII_FLAGS=b;g.piiSubmissionItem.PII_POLICYID=a;g.piiSubmissionItem.FORM_FIELDS=[].concat($jscomp.arrayFromIterable(f));
x.submitShastaPII(g).then(function(a){r.debug("Protobuf submission successful");c.telemetryWrapper.sendPIISubmissionStatusEvent(e.PII_SUBMISSION_STATUS.SUCCESS)}).catch(function(a){r.debug("Protobuf submission failed - "+a);c.telemetryWrapper.sendPIISubmissionStatusEvent(e.PII_SUBMISSION_STATUS.FAILURE)});n.reportStopForComponent(e.performanceReporter.COMPONENT.SCAM_INSIGHT,q)},getBlockPageData:function(a){if(!g(a))return null;var b=m._PIISubmissionInfo.get(a);if(d(b))return null;var c={},f=b.get("wrsScamResponse");
b.get("piiSubmitted")||(m.sendPIISubmission(e.PII_FLAGS.EXIT_SITE,a),b.set("piiSubmitted",!0),m._PIISubmissionInfo.set(a,b));c.url=f.getFullURL();c.ageScore=f.getPIIAge();c.prevalenceScore=f.getPIIPop();return c},sendPIISubmission:function(a,b){if(!g(b)||!g(a)||-1===Object.values(e.PII_FLAGS).indexOf(a))return null;var c=m._PIISubmissionInfo.get(b);if(d(c))return null;b=e.performanceReporter.TYPE.SEND_PII_SUBMISSION+":"+Date.now();n.reportStartForComponent(e.performanceReporter.COMPONENT.SCAM_INSIGHT,
b);var f=c.get("wrsScamResponse");c=c.get("matchedFields");m._piiProtoSubmission(f,a,c);n.reportStopForComponent(e.performanceReporter.COMPONENT.SCAM_INSIGHT,b)},_sendPIISubmissionSilentRating:function(a){if(!g(a))return null;var b=m._processedTabFields.get(a);if(d(b))return null;var c=b.get("wrsScamResponse"),e=b.get("matchedFields"),f=b.get("piiFlag");m._piiProtoSubmission(c,f,e);b.set("piiSubmitted",!0);m._processedTabFields.set(a,b)},_sendPIISubmissionSilentRatingOnTabClose:function(a){if(!g(a))return null;
var b=m._processedTabFields.get(a);if(d(b))return null;if(!b.get("piiSubmitted")){a=b.get("wrsScamResponse");var c=b.get("piiFlag"),e=b.get("matchedFields");b=b.get("piiSubmissionTimer");m._piiProtoSubmission(a,c,e);clearTimeout(b)}},_calculateScamInsightRating:function(a){if(!g(a))return null;var b=m._processedTabFields.get(a);if(d(b))return null;var c=b.get("waxFieldsInfo"),f=b.get("wrsScamResponse");if(d(c)||0===c.size||h(f))return null;c=[e.SCAM_INSIGHT_RESULT.SUSPICIOUS_PAGE,e.SCAM_INSIGHT_RESULT.SUSPICIOUS_NO_BLOCK_PAGE];
var k=f.getScamRating();if(d(k))throw Error("ScamInsight rating cannot be null");var l=e.performanceReporter.TYPE.CALCULATE_SCAM_RATING+":"+Date.now();n.reportStartForComponent(e.performanceReporter.COMPONENT.SCAM_INSIGHT,l);if(c.includes(k))m._handleCacheResponse(a,f),r.debug("Handled scam rating from cache for tabId : "+a);else{switch(f.getPIIEnValue()){case e.WRS_RATINGS.PII_ENABLED:case e.WRS_RATINGS.PII_SILENCE:m._handlePIIEnabledRating(a,b)}n.reportStopForComponent(e.performanceReporter.COMPONENT.SCAM_INSIGHT,
l)}},_handlePIIEnabledRating:function(a,b){var c=e.performanceReporter.TYPE.HANDLE_PII_RATING+":"+Date.now();n.reportStartForComponent(e.performanceReporter.COMPONENT.SCAM_INSIGHT,c);var f=b.get("waxFieldsInfo"),g=b.get("wrsScamResponse"),h=g.getPIIEnValue(),k=new Set(g.getPIIFieldType());if(d(k)||0===k.size)return null;f=m._getMatchedFields(k,f);if(d(f)||0===f.size)return m._updateCachedScamRating(g,e.SCAM_INSIGHT_RESULT.NOT_SUSPICIOUS_PAGE),null;b.set("matchedFields",f);m._processedTabFields.set(a,
b);r.debug("Processed Tab fields map after matched fields update : "+a);r.debug(m._processedTabFields.get(a));f=g.getPIIHTTPS();d(f)&&(f=e.PII_POLICY_HTTPS_KEYS.DONTCARE);var l=g.getFullURL();k=y(l);d(k)&&(k=e.HTTP_PROTOCOL);h===e.WRS_RATINGS.PII_ENABLED&&f===e.PII_POLICY_HTTPS_KEYS.DONTCARE||h===e.WRS_RATINGS.PII_ENABLED&&f===e.PII_POLICY_HTTPS_KEYS.HTTPS&&k===e.HTTP_PROTOCOL?(m._handleScamPageFoundCallback(a,l),m._updateCachedScamRating(g,e.SCAM_INSIGHT_RESULT.SUSPICIOUS_PAGE)):(l=0,h===e.WRS_RATINGS.PII_ENABLED&&
f===e.PII_POLICY_HTTPS_KEYS.HTTPS&&k===e.HTTPS_PROTOCOL&&(l=e.PII_FLAGS.SUPPRESSED_DUE_TO_HTTPS),h===e.WRS_RATINGS.PII_SILENCE&&(l=e.PII_FLAGS.SUPPRESSED_DUE_TO_SILENTMODE),b.get("piiSubmissionTimer")||(h=setTimeout(m._sendPIISubmissionSilentRating,e.PII_SUBMISSION_TIMEOUT,a),b.set("piiFlag",l),b.set("piiSubmissionTimer",h),m._processedTabFields.set(a,b)),m._updateCachedScamRating(g,e.SCAM_INSIGHT_RESULT.SUSPICIOUS_NO_BLOCK_PAGE));n.reportStopForComponent(e.performanceReporter.COMPONENT.SCAM_INSIGHT,
c)},setWrsResponse:function(a,c){var f=e.performanceReporter.TYPE.SET_WRS_RESPONSE+":"+Date.now();n.reportStartForComponent(e.performanceReporter.COMPONENT.SCAM_INSIGHT,f);if(!d(a)&&!h(c)){r.debug("WRS response set. TabId : "+a+" url : "+c.fullURL);var g=m._getSITabInfo(a);g.set("wrsScamResponse",c);c=c.getPIIEnValue();c!==e.WRS_RATINGS.PII_ENABLED&&c!==e.WRS_RATINGS.PII_SILENCE||b.getTab(a,function(a){b.sendMessageToTab(a,{id:e.MESSAGES.PROCESS_PAGE_FOR_SCAM_FIELDS,state:e.SCAM_ANALYSIS_STATE.ANALYZE})});
m._processedTabFields.set(a,g);m._calculateScamInsightRating(a);n.reportStopForComponent(e.performanceReporter.COMPONENT.SCAM_INSIGHT,f)}},deletePIISubmissionInfo:function(a){if(!g(a))return null;var b=m._PIISubmissionInfo.get(a);if(d(b))return null;m._PIISubmissionInfo.delete(a)},_handleTabClose:function(a){if(!g(a))return null;m.deletePIISubmissionInfo(a)},_handleMessage:function(a,c,f){if(!d(a)&&!d(a.id))switch(f=b.getTabID(f),a.id){case e.MESSAGES.WAX_FIELDS_FOUND:if(d(a.data))break;c=a.data;
if(0>=c.length)break;m._collectPIIFields(f,c);break;case e.MESSAGES.TOP_FRAME_UNLOADED:c=e.performanceReporter.TYPE.TOP_FRAME_UNLOADED+":"+Date.now();n.reportStartForComponent(e.performanceReporter.COMPONENT.SCAM_INSIGHT,c);a=m._processedTabFields.get(f);if(d(a))break;a.get("piiSubmissionTimer")&&m._sendPIISubmissionSilentRatingOnTabClose(f);m._processedTabFields.delete(f);n.reportStopForComponent(e.performanceReporter.COMPONENT.SCAM_INSIGHT,c);break;case e.MESSAGES.CAN_ANALYZE_FOR_SCAM:f=m._processedTabFields.get(f),
d(f)||(f=f.get("wrsScamResponse"),d(f)||(f=f.getPIIEnValue(),f!==e.WRS_RATINGS.PII_ENABLED&&f!==e.WRS_RATINGS.PII_SILENCE||c(e.SCAM_ANALYSIS_STATE.ANALYZE)))}},_handleScamPageFoundCallback:function(a,b){if(g(a)&&!c.scamInsightUtility.isURLInViewAnywayCache(b)&&(b=m._processedTabFields.get(a),!d(b))){var e=b.get("scamInsightBlockPageHandled");if(!p(e)||!0!==e){e=b.get("matchedFields");var f=b.get("wrsScamResponse");r.debug("Scam Page detected : ");r.debug(b);m._scamPageFoundCallback(a);var h=new Map;
h.set("wrsScamResponse",f);h.set("matchedFields",e);h.set("piiSubmitted",!1);m._PIISubmissionInfo.set(a,h);b.set("scamInsightBlockPageHandled",!0);m._processedTabFields.set(a,b)}}},_handleCacheResponse:function(a,b){g(a)&&!d(b)&&b.getScamRating()===e.SCAM_INSIGHT_RESULT.SUSPICIOUS_PAGE&&t(m._scamPageFoundCallback)&&m._handleScamPageFoundCallback(a,b.getFullURL())},_updateCachedScamRating:function(a,b){!d(a)&&g(b)&&(a=c.cache.ratingForCachedURL(a.getFullURL()),d(a)||a.getScamRating()===b||(a[e.SCAM_INSIGHT_RATING_KEY]=
b,c.cache.updateCacheRatingsForUrl(a)))}};m.initialize();return m}(a.SymBfw,a.SafeWeb)})(executionContext);
