var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(e){var b=0;return function(){return b<e.length?{done:!1,value:e[b++]}:{done:!0}}};$jscomp.arrayIterator=function(e){return{next:$jscomp.arrayIteratorImpl(e)}};$jscomp.makeIterator=function(e){var b="undefined"!=typeof Symbol&&Symbol.iterator&&e[Symbol.iterator];return b?b.call(e):$jscomp.arrayIterator(e)};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(e,b,a){e!=Array.prototype&&e!=Object.prototype&&(e[b]=a.value)};$jscomp.getGlobal=function(e){return"undefined"!=typeof window&&window===e?e:"undefined"!=typeof global&&null!=global?global:e};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(e,b){this.$jscomp$symbol$id_=e;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function e(a){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(a||"")+"_"+b++,a)}var b=0;return e}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var e=$jscomp.global.Symbol.iterator;e||(e=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[e]&&$jscomp.defineProperty(Array.prototype,e,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var e=$jscomp.global.Symbol.asyncIterator;e||(e=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(e){$jscomp.initSymbolIterator();e={next:e};e[$jscomp.global.Symbol.iterator]=function(){return this};return e};
$jscomp.iteratorFromArray=function(e,b){$jscomp.initSymbolIterator();e instanceof String&&(e+="");var a=0,f={next:function(){if(a<e.length){var d=a++;return{value:b(d,e[d]),done:!1}}f.next=function(){return{done:!0,value:void 0}};return f.next()}};f[Symbol.iterator]=function(){return f};return f};
$jscomp.polyfill=function(e,b,a,f){if(b){a=$jscomp.global;e=e.split(".");for(f=0;f<e.length-1;f++){var d=e[f];d in a||(a[d]={});a=a[d]}e=e[e.length-1];f=a[e];b=b(f);b!=f&&null!=b&&$jscomp.defineProperty(a,e,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.keys",function(e){return e?e:function(){return $jscomp.iteratorFromArray(this,function(b){return b})}},"es6","es3");$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(e){function b(){this.batch_=null}function a(a){return a instanceof d?a:new d(function(c,m){c(a)})}if(e&&!$jscomp.FORCE_POLYFILL_PROMISE)return e;b.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var c=this;this.asyncExecuteFunction(function(){c.executeBatch_()})}this.batch_.push(a)};var f=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){f(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var c=0;c<a.length;++c){var g=a[c];a[c]=null;try{g()}catch(h){this.asyncThrow_(h)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var d=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var c=this.createResolveAndReject_();try{a(c.resolve,c.reject)}catch(g){c.reject(g)}};d.prototype.createResolveAndReject_=function(){function a(a){return function(m){g||(g=!0,a.call(c,m))}}var c=this,g=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};d.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof d)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var c=null!=a;break a;case "function":c=!0;break a;default:c=!1}c?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};d.prototype.resolveToNonPromiseObj_=function(a){var c=void 0;try{c=a.then}catch(g){this.reject_(g);return}"function"==typeof c?
this.settleSameAsThenable_(c,a):this.fulfill_(a)};d.prototype.reject_=function(a){this.settle_(2,a)};d.prototype.fulfill_=function(a){this.settle_(1,a)};d.prototype.settle_=function(a,c){if(0!=this.state_)throw Error("Cannot settle("+a+", "+c+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=c;this.executeOnSettledCallbacks_()};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)c.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var c=new b;d.prototype.settleSameAsPromise_=function(a){var c=this.createResolveAndReject_();a.callWhenSettled_(c.resolve,c.reject)};d.prototype.settleSameAsThenable_=function(a,c){var g=this.createResolveAndReject_();try{a.call(c,g.resolve,g.reject)}catch(h){g.reject(h)}};d.prototype.then=function(a,c){function g(a,c){return"function"==typeof a?function(n){try{b(a(n))}catch(v){m(v)}}:c}var b,m,f=new d(function(a,c){b=a;m=c});this.callWhenSettled_(g(a,b),g(c,m));return f};
d.prototype.catch=function(a){return this.then(void 0,a)};d.prototype.callWhenSettled_=function(a,d){function g(){switch(b.state_){case 1:a(b.result_);break;case 2:d(b.result_);break;default:throw Error("Unexpected state: "+b.state_);}}var b=this;null==this.onSettledCallbacks_?c.asyncExecute(g):this.onSettledCallbacks_.push(g)};d.resolve=a;d.reject=function(a){return new d(function(c,g){g(a)})};d.race=function(c){return new d(function(b,g){for(var d=$jscomp.makeIterator(c),m=d.next();!m.done;m=d.next())a(m.value).callWhenSettled_(b,
g)})};d.all=function(c){var b=$jscomp.makeIterator(c),g=b.next();return g.done?a([]):new d(function(c,d){function m(a){return function(g){n[a]=g;h--;0==h&&c(n)}}var n=[],h=0;do n.push(void 0),h++,a(g.value).callWhenSettled_(m(n.length-1),d),g=b.next();while(!g.done)})};return d},"es6","es3");$jscomp.polyfill("Object.is",function(e){return e?e:function(b,a){return b===a?0!==b||1/b===1/a:b!==b&&a!==a}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(e){return e?e:function(b,a){var f=this;f instanceof String&&(f=String(f));var d=f.length;a=a||0;for(0>a&&(a=Math.max(a+d,0));a<d;a++){var c=f[a];if(c===b||Object.is(c,b))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(e,b,a){if(null==e)throw new TypeError("The 'this' value for String.prototype."+a+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+a+" must not be a regular expression");return e+""};$jscomp.polyfill("String.prototype.includes",function(e){return e?e:function(b,a){return-1!==$jscomp.checkStringArgs(this,b,"includes").indexOf(b,a||0)}},"es6","es3");
$jscomp.owns=function(e,b){return Object.prototype.hasOwnProperty.call(e,b)};$jscomp.assign="function"==typeof Object.assign?Object.assign:function(e,b){for(var a=1;a<arguments.length;a++){var f=arguments[a];if(f)for(var d in f)$jscomp.owns(f,d)&&(e[d]=f[d])}return e};$jscomp.polyfill("Object.assign",function(e){return e||$jscomp.assign},"es6","es3");(function(e){(e.SymBfw=e.SymBfw||{}).globals={BROWSER:"Chrome",PRODUCT_GUID:"DC6B1B05-C7B2-43EB-81E3-CBD3896553C2"}})(this);
(function(e){(e.SymBfw=e.SymBfw||{}).logger=function(b){return{debug:function(a){},log:function(a){},error:function(a){console.error(a);var f=b.telemetryWrapper;f.send(f.componentType.LOGGER,f.actionType.ERROR,a)},warn:function(a){console.warn(a);var f=b.telemetryWrapper;f.send(f.componentType.LOGGER,f.actionType.WARN,a)},info:function(a){console.info(a)}}}(e.SymBfw)})(this);
(function(e){e=e.SymBfw;var b={httpStatusCodes:{},localizer:{DEFAULT_MESSAGES_DICTIONARY:"strings",GET_LOCALIZED_STRING:"44F4D54E-AB86-454C-A494-DE3AD87E72F9",GET_LOCALIZED_STRINGS:"0D1C5EEF-749F-4EEB-AD6D-F9C26018EE91",GET_ALL_LOCALIZED_STRINGS:"33445b60-9a88-4d99-829f-564704b2a960",GET_LOCALIZED_STRING_FROM_DICTIONARY:"D15C0B4C-DC1B-403F-A3C8-8BB42137B325",GET_LOCALIZED_STRINGS_FROM_DICTIONARY:"88313974-C371-4A8D-9196-0A2CE43C8327",GET_LOCALIZED_STRING_WITH_FORMAT:"F3D7C8CE-B1A9-425A-AD24-4120C592AF86",
GET_LOCALIZED_STRING_WITH_FORMAT_FROM_DICTIONARY:"9066F4CC-31A4-45F5-A07A-81DDC38E5F99",GET_CURRENT_LANGUAGE_DIRECTION:"C30B2719-DD82-41EC-E93A-8A602444F90A",GET_LOCALIZED_STRINGS_WITH_FORMAT:"E225C9A6-209A-4702-8E48-3B6EFBF67E26"},clipboard:{messages:{CLEAR_CLIPBOARD:"aa232db5-1dba-473a-ab4b-e9c378b7978b"},DEFAULT_TIMEOUT:6E4}};b.httpStatusCodes.OK=200;b.httpStatusCodes.PARTIAL_CONTENT=206;b.httpStatusCodes.CREATED=201;b.httpStatusCodes.NO_CONTENT=204;b.httpStatusCodes.INCORRECT_URI=302;b.httpStatusCodes.NOT_MODIFIED=
304;b.httpStatusCodes.BAD_REQUEST=400;b.httpStatusCodes.UNAUTHORIZED=401;b.httpStatusCodes.INVALID_SCHEMA=403;b.httpStatusCodes.NOT_FOUND=404;b.httpStatusCodes.HEADER_ERROR=406;b.httpStatusCodes.GONE=410;b.httpStatusCodes.ENTITY_TOO_LARGE=413;b.httpStatusCodes.DATASTORE_RATE_LIMITED=429;b.httpStatusCodes.RATE_LIMITING=503;b.httpStatusCodes.SERVER_ERROR=500;b.DEFAULT_FETCH_TIMEOUT=6E4;b.CERT_COMMON_NAME="CN";b.telemetry={TELEMETRY_ENABLED:"293E0764-AF48-4C52-B675-0161A7B6BECE",TELEMETRY_OPT_OUT_SHOWN:"FE795012-44D6-491D-A8A1-E83633892C9D",
BFW_TELEMETRY_SETTINGS_CONTAINER:"233D07C0-6318-4BCE-A36A-82DFB19F3B2A",USER_RESPONDED_IN_OPT_OUT_PAGE:"8157BC1F-5ED8-4373-A18D-8CD8E0263752",LAST_OFFER_DATE:"9EA53F0C-7F18-44A5-8138-C11F27D66FC1"};b.os={WINDOWS:"Windows",MAC:"Mac",UNKNOWN:"Unknown"};b.CDN_FILE_DOWNLOADER={ENCRYPTION_METHOD:"RS256",SUPPORTED_PROTOCOL:"https",SUPPORTED_FILEFORMATS:["json"],RESPONSE_STATUS:{UNSUCCESSFUL_RESPONSE:"Error in fetching the file with status code",FILE_TAMPERED:"CDN file has been tampered",PUBLIC_KEY_NOT_VERIFIED:"Public key verification has failed",
INVALID_PARAMETERS:"Invalid paramaters"},CERT_ISSUER_NAME:"CERT_ISSUER_NAME",CERT_ISSUED:"CERT_ISSUED"};b.uiConstants={NOTIFICATION:{IFRAME_ID:"symc-notification-popup",HTML:"content/ui/notification.html",STYLE:"content/ui/content-page.css",STACK_COUNT:1,DEFAULT_TIMEOUT:1E4,HEIGHT:160,WIDTH:460,TYPE:{QUESTION:0,TIMED:1},BUTTON:{DEFAULT:0,SECONDARY:1},MESSAGES:{DEFAULT_MESSAGE:"8DB8FE17-6F5E-485E-81EE-1112762F48E4",DEFAULT_BUTTON_PRESSED:"209CBB4D-6D6B-46F4-9EA7-303181937BF6",SECONDARY_LINK_PRESSED:"8881560D-E8A2-41FA-A81D-A90D41311D0D",
THIRD_BUTTON_PRESSED:"196F06EB-956E-44EE-A60D-F4741C5CF4D3",NOTIFICATION_CLOSED:"EA7414A5-667F-4459-BAC2-38464F3330A3",NOTIFICATION_QUEUE_MESSAGE:"A88CCFCD-B98D-4607-B780-79A1CF7ADFAD",NOTIFICATIONS_SHOWN:"57C094C2-F0F0-44C2-9BBF-9E147135FB50",UI_INIT:"EE5B61D6-3A55-4ABB-B304-02BDAD9698FE",UI_INIT_PROXY:"0FABE0DB-1C87-475B-D89E-F4EC0EE963DE",HIDE_NOTIFICATIONS:"8211780F-93EC-4E37-8933-E60CB6052E84"}},CONTENT_PAGE_STYLE_ID:"symc-content-stylesheet"};b.performanceReporter={MESSAGES:{REPORT_START:"2379B4CB-E725-4818-8FCC-A9372EABBF45",
REPORT_END:"1F62DD4E-56AD-4528-9A69-BFE9EC135B9F",GET_PERFORMANCE_REPORTER:"2306DE62-ACA8-40AE-9909-517474C1120B"}};b.utils={IP:"ip"};b.NAVIGATION_COMPLETE="complete";b.STORE_URLS={Chrome:"https://chrome.google.com/webstore/",Firefox:"https://addons.mozilla.org/",Safari:"https://safari-extensions.apple.com/",Edge:"https://www.microsoft.com/[a-zA-Z]+[-]?[a-zA-Z]*/(p|store)/"};b.BROWSER_TYPE={CHROME:"Chrome",FIREFOX:"Firefox",EDGE:"Edge",SAFARI:"Safari"};e.constants=b})(this);
(function(e){e.SymBfw.utils=function(b){var a={},f=b.constants;a.createNewGuid=function(){var a=(new Date).getTime();return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(c){var b=(a+16*Math.random())%16|0;a=Math.floor(a/16);return("x"==c?b:b&7|8).toString(16)})};a.stringUTF16LEToByteArray=function(a){if(!1===this.isString(a))throw Error("Input string cannot be null or is not a string");for(var c=[],b=0;b<a.length;++b){var g=a.charCodeAt(b),d=(g&65280)>>8;c.push(g&255);c.push(d)}return c};
a.arrayBufferToStringUTF16LE=function(a){if(this.isNil(a))return null;a instanceof ArrayBuffer&&(a=new Uint8Array(a));for(var c=[],b=0;b<a.byteLength;b++)c.push(a[b]);return this.byteArrayToStringUTF16LE(c)};a.byteArrayToStringUTF16LE=function(a){if(!1===this.isArray(a))throw Error("Byte array cannot be null or is not an array");if(2>a.length)throw Error("Byte array needs to contain at least two bytes");if(0!==a.length%2)throw Error("Byte array needs to contain even number of bytes");for(var c="",
b=0;b<a.length-1;b+=2){var g=a[b];if(255<g)throw Error("Encoding error: Input contains element larger than a byte.");g&=255;var d=a[b+1];if(255<d)throw Error("Encoding error: Input contains element larger than a byte.");d=d<<8&65280;c+=String.fromCharCode(g+d)}return c};a.downloadFileFromUrl=function(a){var c=document.createElement("iframe");c.style.display="none";c.src=a;c.width="1";c.height="1";c.frameborder="0";document.body.appendChild(c);setTimeout(function(){document.body.removeChild(c)},5E3)};
a.obfuscatePassword=function(a,d){if(!1===this.isString(a))throw Error("password  cannot be null and has to be a string");if(!1===this.isString(d))throw Error("obfuscationKey  cannot be null and has to be a string");a=new Uint8Array(b.utils.stringUTF16LEToByteArray(a));d=new Uint8Array(b.utils.stringUTF16LEToByteArray(d));d=b.utils._obfuscateData(a,d);return d=b.utils.arrayBufferToStringUTF16LE(d)};a._obfuscateData=function(c,b){if(a.isNil(c)||a.isNil(b))return null;c instanceof ArrayBuffer&&(c=new Uint8Array(c));
b instanceof ArrayBuffer&&(b=new Uint8Array(b));for(var d=c.byteLength,g=new Uint8Array(d),h=0;h<d;h++)g[h]=c[h]^b[h%d];return g};a.getOSType=function(){var a=f.os.UNKNOWN;-1!=navigator.appVersion.toLowerCase().indexOf("win")?a=f.os.WINDOWS:-1!=navigator.appVersion.toLowerCase().indexOf("mac")&&(a=f.os.MAC);return a};a.isNil=function(a){return"undefined"===typeof a||null===a?!0:!1};a.isntNil=function(a){return"undefined"!==typeof a&&null!==a?!0:!1};a.isEmptyObject=function(c){return a.isNil(c)||0===
Object.keys(c).length?!0:!1};a.objectHas=function(c,b){return a.isObject(c)&&a.isString(b)?Object.prototype.hasOwnProperty.call(c,b):!1};a.isString=function(c){return a.isntNil(c)&&"string"===typeof c?!0:!1};a.isFunction=function(c){return a.isntNil(c)&&"function"===typeof c?!0:!1};a.isArray=function(a){return Array.isArray(a)};a.isObject=function(c){return a.isntNil(c)&&"object"===typeof c&&c.constructor===Object?!0:!1};a.isBoolean=function(c){return a.isntNil(c)&&"boolean"===typeof c?!0:!1};var d=
{ac:{com:!0,gov:!0,mil:!0,net:!0,org:!0,edu:!0},ad:{nom:!0},ae:{ac:!0,co:!0,gov:!0,mil:!0,name:!0,net:!0,org:!0,pro:!0,sch:!0},af:{com:!0,edu:!0,gov:!0,net:!0,org:!0},ai:{off:!0,com:!0,net:!0,org:!0},al:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0,uniti:!0,tirana:!0,soros:!0,upt:!0,inima:!0},an:{com:!0,net:!0,org:!0,edu:!0},ag:{com:!0,org:!0,net:!0,co:!0,nom:!0},ao:{co:!0,ed:!0,gv:!0,it:!0,og:!0,pb:!0},ar:{com:!0,edu:!0,gob:!0,gov:!0,"int":!0,mil:!0,net:!0,org:!0,tur:!0},arpa:{e164:!0,"in-addr":!0,
iris:!0,ip6:!0,uri:!0,urn:!0},at:{ac:!0,co:!0,gv:!0,or:!0,priv:!0},au:{asn:!0,com:!0,net:!0,id:!0,org:!0,csiro:!0,oz:!0,info:!0,conf:!0,act:!0,nsw:!0,nt:!0,qld:!0,sa:!0,tas:!0,vic:!0,wa:!0},aw:{com:!0},az:{com:!0,net:!0,"int":!0,gov:!0,biz:!0,org:!0,edu:!0,mil:!0,pp:!0,name:!0,info:!0},ba:{co:!0,com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0,rs:!0,unbi:!0,unmo:!0,unsa:!0,untz:!0,unze:!0},bb:{biz:!0,co:!0,com:!0,edu:!0,gov:!0,info:!0,net:!0,org:!0,store:!0,tv:!0},bd:{com:!0,edu:!0,net:!0,gov:!0,org:!0,
mil:!0},be:{ac:!0},bf:{gov:!0},bh:{biz:!0,cc:!0,com:!0,edu:!0,gov:!0,info:!0,net:!0,org:!0},bm:{com:!0,edu:!0,org:!0,gov:!0,net:!0},bn:{com:!0,edu:!0,gov:!0,net:!0,org:!0},bo:{com:!0,edu:!0,gob:!0,gov:!0,"int":!0,mil:!0,net:!0,org:!0,tv:!0},br:{adm:!0,adv:!0,agr:!0,am:!0,arq:!0,art:!0,ato:!0,b:!0,bio:!0,blog:!0,bmd:!0,cim:!0,cng:!0,cnt:!0,com:!0,coop:!0,ecn:!0,edu:!0,eng:!0,esp:!0,etc:!0,eti:!0,far:!0,flog:!0,fm:!0,fnd:!0,fot:!0,fst:!0,g12:!0,ggf:!0,gov:!0,imb:!0,ind:!0,inf:!0,jor:!0,jus:!0,lel:!0,
mat:!0,med:!0,mil:!0,mus:!0,net:!0,nom:!0,not:!0,ntr:!0,odo:!0,org:!0,ppg:!0,pro:!0,psc:!0,psi:!0,qsl:!0,rec:!0,slg:!0,srv:!0,tmp:!0,trd:!0,tur:!0,tv:!0,vet:!0,vlog:!0,wiki:!0,zlg:!0},bs:{com:!0,edu:!0,gov:!0,net:!0,org:!0},bt:{com:!0,edu:!0,gov:!0,net:!0,org:!0},bw:{co:!0,org:!0},by:{gov:!0,mil:!0},bz:{du:!0,et:!0,om:!0,ov:!0,rg:!0},ca:{ab:!0,bc:!0,mb:!0,nb:!0,nf:!0,nl:!0,ns:!0,nt:!0,nu:!0,on:!0,pe:!0,qc:!0,sk:!0,yk:!0},cc:{co:!0},ck:{biz:!0,co:!0,edu:!0,gen:!0,gov:!0,info:!0,net:!0,org:!0},cn:{ac:!0,
ah:!0,bj:!0,com:!0,cq:!0,edu:!0,fj:!0,gd:!0,gov:!0,gs:!0,gx:!0,gz:!0,ha:!0,hb:!0,he:!0,hi:!0,hl:!0,hn:!0,jl:!0,js:!0,jx:!0,ln:!0,mil:!0,net:!0,nm:!0,nx:!0,org:!0,qh:!0,sc:!0,sd:!0,sh:!0,sn:!0,sx:!0,tj:!0,tw:!0,xj:!0,xz:!0,yn:!0,zj:!0},co:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,nom:!0,org:!0},cr:{ac:!0,c:!0,co:!0,ed:!0,fi:!0,go:!0,or:!0,sa:!0},cx:{gov:!0},cy:{ac:!0,biz:!0,com:!0,ekloges:!0,gov:!0,ltd:!0,name:!0,net:!0,org:!0,parliament:!0,press:!0,pro:!0,tm:!0},cu:{com:!0,edu:!0,org:!0,net:!0,gov:!0,inf:!0},
dm:{com:!0,net:!0,org:!0,edu:!0,gov:!0},"do":{art:!0,com:!0,edu:!0,gob:!0,gov:!0,mil:!0,net:!0,org:!0,sld:!0,web:!0},dz:{art:!0,asso:!0,com:!0,edu:!0,gov:!0,net:!0,org:!0,pol:!0},ec:{com:!0,edu:!0,fin:!0,gov:!0,info:!0,med:!0,mil:!0,net:!0,org:!0,pro:!0},ee:{com:!0,org:!0,fie:!0,pri:!0},eg:{com:!0,edu:!0,eun:!0,gov:!0,mil:!0,name:!0,net:!0,org:!0,sci:!0},er:{com:!0,edu:!0,gov:!0,ind:!0,mil:!0,net:!0,org:!0,rochest:!0,w:!0},es:{com:!0,edu:!0,gob:!0,nom:!0,org:!0},et:{biz:!0,com:!0,edu:!0,gov:!0,info:!0,
name:!0,net:!0,org:!0},fi:{aland:!0},fj:{ac:!0,biz:!0,com:!0,info:!0,mil:!0,name:!0,net:!0,org:!0,pro:!0},fk:{ac:!0,co:!0,gov:!0,net:!0,nom:!0,org:!0},fr:{asso:!0,com:!0,f:!0,gouv:!0,nom:!0,prd:!0,presse:!0,tm:!0},ge:{com:!0,edu:!0,gov:!0,org:!0,mil:!0,net:!0,pvt:!0},gg:{co:!0,net:!0,org:!0},gh:{com:!0,edu:!0,gov:!0,mil:!0,org:!0},gi:{com:!0,ltd:!0,gov:!0,mod:!0,edu:!0,org:!0},gn:{ac:!0,com:!0,gov:!0,net:!0,org:!0},gp:{com:!0,net:!0,edu:!0,asso:!0,org:!0},gr:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0},
gt:{com:!0,edu:!0,gob:!0,ind:!0,mil:!0,net:!0,org:!0},gu:{com:!0,edu:!0,gov:!0,net:!0,org:!0},hk:{com:!0,edu:!0,gov:!0,idv:!0,net:!0,org:!0},ht:{com:!0,net:!0,firm:!0,shop:!0,info:!0,pro:!0,adult:!0,org:!0,art:!0,pol:!0,rel:!0,asso:!0,perso:!0,coop:!0,med:!0,edu:!0,gouv:!0},hu:{2E3:!0,agrar:!0,bolt:!0,casino:!0,city:!0,co:!0,erotica:!0,erotika:!0,film:!0,forum:!0,games:!0,hotel:!0,info:!0,ingatlan:!0,jogasz:!0,konyvelo:!0,lakas:!0,media:!0,news:!0,org:!0,priv:!0,reklam:!0,sex:!0,shop:!0,sport:!0,
suli:!0,szex:!0,tm:!0,tozsde:!0,utazas:!0,video:!0},id:{ac:!0,co:!0,go:!0,mil:!0,net:!0,or:!0,sch:!0,web:!0},il:{ac:!0,co:!0,gov:!0,idf:!0,k12:!0,muni:!0,net:!0,org:!0},im:{co:!0,"ltd.co":!0,"plc.co":!0,net:!0,gov:!0,org:!0,nic:!0,ac:!0},"in":{ac:!0,co:!0,edu:!0,ernet:!0,firm:!0,gen:!0,gov:!0,i:!0,ind:!0,mil:!0,net:!0,nic:!0,org:!0,res:!0},iq:{com:!0,edu:!0,gov:!0,i:!0,mil:!0,net:!0,org:!0},ir:{ac:!0,co:!0,dnssec:!0,gov:!0,i:!0,id:!0,net:!0,org:!0,sch:!0},it:{edu:!0,gov:!0},je:{co:!0,net:!0,org:!0},
jo:{com:!0,edu:!0,gov:!0,mil:!0,name:!0,net:!0,org:!0,sch:!0},jp:{ac:!0,ad:!0,co:!0,ed:!0,go:!0,gr:!0,lg:!0,ne:!0,or:!0},ke:{ac:!0,co:!0,go:!0,info:!0,me:!0,mobi:!0,ne:!0,or:!0,sc:!0},kh:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0,per:!0},ki:{biz:!0,com:!0,de:!0,edu:!0,gov:!0,info:!0,mob:!0,net:!0,org:!0,tel:!0},km:{asso:!0,com:!0,coop:!0,edu:!0,gouv:!0,k:!0,medecin:!0,mil:!0,nom:!0,notaires:!0,pharmaciens:!0,presse:!0,tm:!0,veterinaire:!0},kn:{edu:!0,gov:!0,net:!0,org:!0},kr:{ac:!0,busan:!0,chungbuk:!0,
chungnam:!0,co:!0,daegu:!0,daejeon:!0,es:!0,gangwon:!0,go:!0,gwangju:!0,gyeongbuk:!0,gyeonggi:!0,gyeongnam:!0,hs:!0,incheon:!0,jeju:!0,jeonbuk:!0,jeonnam:!0,k:!0,kg:!0,mil:!0,ms:!0,ne:!0,or:!0,pe:!0,re:!0,sc:!0,seoul:!0,ulsan:!0},kw:{com:!0,edu:!0,gov:!0,net:!0,org:!0},ky:{com:!0,edu:!0,gov:!0,net:!0,org:!0},kz:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0},lb:{com:!0,edu:!0,gov:!0,net:!0,org:!0},lc:{com:!0,org:!0,edu:!0,gov:!0},li:{com:!0,net:!0,org:!0,gov:!0},lk:{assn:!0,com:!0,edu:!0,gov:!0,grp:!0,
hotel:!0,"int":!0,ltd:!0,net:!0,ngo:!0,org:!0,sch:!0,soc:!0,web:!0},lr:{com:!0,edu:!0,gov:!0,net:!0,org:!0},ls:{org:!0,co:!0},lt:{gov:!0,mil:!0},lu:{gov:!0,mil:!0,org:!0,net:!0},lv:{asn:!0,com:!0,conf:!0,edu:!0,gov:!0,id:!0,mil:!0,net:!0,org:!0},ly:{com:!0,edu:!0,gov:!0,id:!0,med:!0,net:!0,org:!0,plc:!0,sch:!0},ma:{ac:!0,co:!0,gov:!0,m:!0,net:!0,org:!0,press:!0},mc:{asso:!0,tm:!0},me:{ac:!0,co:!0,edu:!0,gov:!0,its:!0,net:!0,org:!0,priv:!0},mg:{com:!0,edu:!0,gov:!0,mil:!0,nom:!0,org:!0,prd:!0,tm:!0},
mk:{com:!0,edu:!0,gov:!0,inf:!0,name:!0,net:!0,org:!0,pro:!0},ml:{com:!0,edu:!0,gov:!0,net:!0,org:!0,presse:!0},mn:{edu:!0,gov:!0,org:!0},mo:{com:!0,edu:!0,gov:!0,net:!0,org:!0},mt:{com:!0,edu:!0,gov:!0,net:!0,org:!0},mv:{aero:!0,biz:!0,com:!0,coop:!0,edu:!0,gov:!0,info:!0,"int":!0,mil:!0,museum:!0,name:!0,net:!0,org:!0,pro:!0},mw:{ac:!0,co:!0,com:!0,coop:!0,edu:!0,gov:!0,"int":!0,museum:!0,net:!0,org:!0},mx:{com:!0,edu:!0,gob:!0,net:!0,org:!0},my:{com:!0,edu:!0,gov:!0,mil:!0,name:!0,net:!0,org:!0,
sch:!0},nf:{arts:!0,com:!0,firm:!0,info:!0,net:!0,other:!0,per:!0,rec:!0,store:!0,web:!0},ng:{biz:!0,com:!0,edu:!0,gov:!0,mil:!0,mobi:!0,name:!0,net:!0,org:!0,sch:!0},ni:{ac:!0,co:!0,com:!0,edu:!0,gob:!0,mil:!0,net:!0,nom:!0,org:!0},no:{mil:!0,stat:!0,kommune:!0,herad:!0,priv:!0,vgs:!0,fhs:!0,museum:!0,fylkesbibl:!0,folkebibl:!0,idrett:!0},np:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0},nr:{biz:!0,com:!0,edu:!0,gov:!0,info:!0,net:!0,org:!0},om:{ac:!0,biz:!0,co:!0,com:!0,edu:!0,gov:!0,med:!0,mil:!0,
museum:!0,net:!0,org:!0,pro:!0,sch:!0},pe:{com:!0,edu:!0,gob:!0,mil:!0,net:!0,nom:!0,org:!0,sld:!0},pf:{com:!0,org:!0,edu:!0},pg:{"com.pg":!0,net:!0},ph:{com:!0,edu:!0,gov:!0,i:!0,mil:!0,net:!0,ngo:!0,org:!0},pk:{biz:!0,com:!0,edu:!0,fam:!0,gob:!0,gok:!0,gon:!0,gop:!0,gos:!0,gov:!0,net:!0,org:!0,web:!0},pl:{art:!0,bialystok:!0,biz:!0,com:!0,edu:!0,gda:!0,gdansk:!0,gorzow:!0,gov:!0,info:!0,katowice:!0,krakow:!0,lodz:!0,lublin:!0,mil:!0,net:!0,ngo:!0,olsztyn:!0,org:!0,poznan:!0,pwr:!0,radom:!0,slupsk:!0,
szczecin:!0,torun:!0,warszawa:!0,waw:!0,wroc:!0,wroclaw:!0,zgora:!0},pr:{ac:!0,biz:!0,com:!0,edu:!0,est:!0,gov:!0,info:!0,isla:!0,name:!0,net:!0,org:!0,pro:!0,prof:!0},pro:{law:!0,med:!0,cpa:!0},ps:{com:!0,edu:!0,gov:!0,net:!0,org:!0,plo:!0,sec:!0},pt:{com:!0,edu:!0,gov:!0,"int":!0,net:!0,nome:!0,org:!0,publ:!0},pw:{belau:!0,co:!0,ed:!0,go:!0,ne:!0,or:!0},ro:{arts:!0,com:!0,firm:!0,info:!0,nom:!0,nt:!0,org:!0,rec:!0,store:!0,tm:!0,www:!0},rs:{ac:!0,co:!0,edu:!0,gov:!0,"in":!0,org:!0},sb:{com:!0,edu:!0,
gov:!0,net:!0,org:!0},sc:{com:!0,edu:!0,gov:!0,net:!0,org:!0},sh:{co:!0,com:!0,edu:!0,gov:!0,net:!0,nom:!0,org:!0},sl:{com:!0,edu:!0,gov:!0,net:!0,org:!0},st:{co:!0,com:!0,consulado:!0,edu:!0,embaixada:!0,gov:!0,mil:!0,net:!0,org:!0,principe:!0,saotome:!0,store:!0},sv:{com:!0,edu:!0,gob:!0,org:!0,red:!0},sz:{ac:!0,co:!0,org:!0},tr:{av:!0,bbs:!0,bel:!0,biz:!0,com:!0,dr:!0,edu:!0,gen:!0,gov:!0,info:!0,k12:!0,name:!0,net:!0,org:!0,pol:!0,tel:!0,tsk:!0,tv:!0,web:!0},tt:{aero:!0,biz:!0,cat:!0,co:!0,com:!0,
coop:!0,edu:!0,gov:!0,info:!0,"int":!0,jobs:!0,mil:!0,mobi:!0,museum:!0,name:!0,net:!0,org:!0,pro:!0,tel:!0,travel:!0},tw:{club:!0,com:!0,ebiz:!0,edu:!0,game:!0,gov:!0,idv:!0,mil:!0,net:!0,org:!0},mu:{ac:!0,co:!0,com:!0,gov:!0,net:!0,or:!0,org:!0},mz:{ac:!0,co:!0,edu:!0,gov:!0,org:!0},na:{co:!0,com:!0},nz:{ac:!0,co:!0,cri:!0,geek:!0,gen:!0,govt:!0,health:!0,iwi:!0,maori:!0,mil:!0,net:!0,org:!0,parliament:!0,school:!0},pa:{abo:!0,ac:!0,com:!0,edu:!0,gob:!0,ing:!0,med:!0,net:!0,nom:!0,org:!0,sld:!0},
py:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0},qa:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0},re:{asso:!0,com:!0,nom:!0},ru:{ac:!0,adygeya:!0,altai:!0,amur:!0,arkhangelsk:!0,astrakhan:!0,bashkiria:!0,belgorod:!0,bir:!0,bryansk:!0,buryatia:!0,cbg:!0,chel:!0,chelyabinsk:!0,chita:!0,chukotka:!0,chuvashia:!0,com:!0,dagestan:!0,"e-burg":!0,edu:!0,gov:!0,grozny:!0,"int":!0,irkutsk:!0,ivanovo:!0,izhevsk:!0,jar:!0,"joshkar-ola":!0,kalmykia:!0,kaluga:!0,kamchatka:!0,karelia:!0,kazan:!0,kchr:!0,kemerovo:!0,
khabarovsk:!0,khakassia:!0,khv:!0,kirov:!0,koenig:!0,komi:!0,kostroma:!0,kranoyarsk:!0,kuban:!0,kurgan:!0,kursk:!0,lipetsk:!0,magadan:!0,mari:!0,"mari-el":!0,marine:!0,mil:!0,mordovia:!0,mosreg:!0,msk:!0,murmansk:!0,nalchik:!0,net:!0,nnov:!0,nov:!0,novosibirsk:!0,nsk:!0,omsk:!0,orenburg:!0,org:!0,oryol:!0,penza:!0,perm:!0,pp:!0,pskov:!0,ptz:!0,rnd:!0,ryazan:!0,sakhalin:!0,samara:!0,saratov:!0,simbirsk:!0,smolensk:!0,spb:!0,stavropol:!0,stv:!0,surgut:!0,tambov:!0,tatarstan:!0,tom:!0,tomsk:!0,tsaritsyn:!0,
tsk:!0,tula:!0,tuva:!0,tver:!0,tyumen:!0,udm:!0,udmurtia:!0,"ulan-ude":!0,vladikavkaz:!0,vladimir:!0,vladivostok:!0,volgograd:!0,vologda:!0,voronezh:!0,vrn:!0,vyatka:!0,yakutia:!0,yamal:!0,yekaterinburg:!0,"yuzhno-sakhalinsk":!0},rw:{ac:!0,co:!0,com:!0,edu:!0,gouv:!0,gov:!0,"int":!0,mil:!0,net:!0},sa:{com:!0,edu:!0,gov:!0,med:!0,net:!0,org:!0,pub:!0,sch:!0},sd:{com:!0,edu:!0,gov:!0,info:!0,med:!0,net:!0,org:!0,tv:!0},se:{a:!0,ac:!0,b:!0,bd:!0,c:!0,d:!0,e:!0,f:!0,g:!0,h:!0,i:!0,k:!0,l:!0,m:!0,n:!0,
o:!0,org:!0,p:!0,parti:!0,pp:!0,press:!0,r:!0,s:!0,t:!0,tm:!0,u:!0,w:!0,x:!0,y:!0,z:!0},sg:{com:!0,edu:!0,gov:!0,idn:!0,net:!0,org:!0,per:!0},sn:{art:!0,com:!0,edu:!0,gouv:!0,org:!0,perso:!0,univ:!0},sy:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,news:!0,org:!0},th:{ac:!0,co:!0,go:!0,"in":!0,mi:!0,net:!0,or:!0},tj:{ac:!0,biz:!0,co:!0,com:!0,edu:!0,go:!0,gov:!0,info:!0,"int":!0,mil:!0,name:!0,net:!0,nic:!0,org:!0,test:!0,web:!0},tn:{agrinet:!0,com:!0,defense:!0,edunet:!0,ens:!0,fin:!0,gov:!0,ind:!0,info:!0,
intl:!0,mincom:!0,nat:!0,net:!0,org:!0,perso:!0,rnrt:!0,rns:!0,rnu:!0,tourism:!0},tz:{ac:!0,co:!0,go:!0,ne:!0,or:!0},ua:{biz:!0,cherkassy:!0,chernigov:!0,chernovtsy:!0,ck:!0,cn:!0,co:!0,com:!0,crimea:!0,cv:!0,dn:!0,dnepropetrovsk:!0,donetsk:!0,dp:!0,edu:!0,gov:!0,"if":!0,"in":!0,"ivano-frankivsk":!0,kh:!0,kharkov:!0,kherson:!0,khmelnitskiy:!0,kiev:!0,kirovograd:!0,km:!0,kr:!0,ks:!0,kv:!0,lg:!0,lugansk:!0,lutsk:!0,lviv:!0,me:!0,mk:!0,net:!0,nikolaev:!0,od:!0,odessa:!0,org:!0,pl:!0,poltava:!0,pp:!0,
rovno:!0,rv:!0,sebastopol:!0,sumy:!0,te:!0,ternopil:!0,uzhgorod:!0,vinnica:!0,vn:!0,zaporizhzhe:!0,zhitomir:!0,zp:!0,zt:!0},ug:{ac:!0,co:!0,go:!0,ne:!0,or:!0,org:!0,sc:!0},uk:{ac:!0,bl:!0,"british-library":!0,co:!0,cym:!0,gov:!0,govt:!0,icnet:!0,jet:!0,lea:!0,ltd:!0,me:!0,mil:!0,mod:!0,"national-library-scotland":!0,nel:!0,net:!0,nhs:!0,nic:!0,nls:!0,org:!0,orgn:!0,parliament:!0,plc:!0,police:!0,sch:!0,scot:!0,soc:!0},us:{dni:!0,fed:!0,isa:!0,kids:!0,nsn:!0},uy:{com:!0,edu:!0,gub:!0,mil:!0,net:!0,
org:!0},ve:{co:!0,com:!0,edu:!0,gob:!0,info:!0,mil:!0,net:!0,org:!0,web:!0},vi:{co:!0,com:!0,k12:!0,net:!0,org:!0},vn:{ac:!0,biz:!0,com:!0,edu:!0,gov:!0,health:!0,info:!0,"int":!0,name:!0,net:!0,org:!0,pro:!0},ye:{co:!0,com:!0,gov:!0,ltd:!0,me:!0,net:!0,org:!0,plc:!0},yu:{ac:!0,co:!0,edu:!0,gov:!0,org:!0},za:{ac:!0,agric:!0,alt:!0,bourse:!0,city:!0,co:!0,cybernet:!0,db:!0,edu:!0,gov:!0,grondar:!0,iaccess:!0,imt:!0,inca:!0,landesign:!0,law:!0,mil:!0,net:!0,ngo:!0,nis:!0,nom:!0,olivetti:!0,org:!0,pix:!0,
school:!0,tm:!0,web:!0},zm:{ac:!0,co:!0,com:!0,edu:!0,gov:!0,net:!0,org:!0,sch:!0}};a.getSLD=function(c){if(a.isNil(c))return null;var b=c.split("."),f=b.length-2;if(0>f)return null;c=b[f];b=b[f+1];f=d[b];return a.isNil(f)||a.isNil(f[c])?null:c+"."+b};a.depthOfTLDorSLD=function(c){if(a.isNil(c))return null;c=a.getSLD(c);return a.isntNil(c)?2:1};a.isInteger=function(c){return a.isNil(c)?!1:"number"===typeof c&&isFinite(c)&&Math.floor(c)===c};a.isSuccessCode=function(c){return a.isNil(c)?!1:c===f.httpStatusCodes.OK||
c===f.httpStatusCodes.PARTIAL_CONTENT||c===f.httpStatusCodes.CREATED||c===f.httpStatusCodes.NO_CONTENT?!0:!1};a.safeFetch=function(a,b,d){b=void 0===b?{}:b;d=void 0===d?f.DEFAULT_FETCH_TIMEOUT:d;return new Promise(function(c,f){var g=setTimeout(function(){f(Error("Request timed out "+a))},d);fetch(a,b).then(function(a){clearTimeout(g);c(a)}).catch(function(a){clearTimeout(g);f(a)})})};a.isSuccessCodeLocalFile=function(c){return a.isInteger(c)?"Safari"===b.globals.BROWSER&&0===c||c===f.httpStatusCodes.OK?
!0:!1:!1};a.urlWithoutQueryParameters=function(c,b){a.isNil(b)&&(b=!0);if(a.isNil(c))return null;var d=new URI(c),g=d.protocol();if(a.isNil(g)||""===g||"http"!==g&&"https"!==g)g="http",d=new URI(g+"://"+c);c=d.hostname();d=d.path();if(a.isNil(d)||"/"===d)d="";return b?g+"://"+c+d:c+d};a.baseURL=function(c){return a.isNil(c)?null:(new URI(c)).hostname()};a.pathName=function(c){return a.isNil(c)?null:(new URI(c)).pathname()};a.urlProtocol=function(c){if(a.isNil(c))return null;c=(new URI(c)).protocol();
return""===c?null:c};a.getUrlTLD=function(c){if(a.isNil(c))return null;c=(new URI(c)).tld();return""===c?null:c};a.getCompanyDomain=function(c){if(a.isNil(c))return null;var b=(new URI(c)).hostname();c=a.getUrlTLD(c);return""===b?null:a.isntNil(c)&&0<b.indexOf(c)?(b=b.substring(0,b.lastIndexOf(c)-1).split("."),b[b.length-1]):b};a.getDomain=function(c){if(a.isNil(c))return null;c=(new URI(c)).domain();return""===c?null:c};a.isUrlAnIp=function(c){return a.isNil(c)?null:(new URI(c)).is(f.utils.IP)};
a.getFileNameExtension=function(c){if(!a.isString(c))return null;c=(new URI(c)).suffix();return""===c?null:c};a.appendToObject=function(c,b){if(a.isNil(c)||a.isNil(b))throw Error("invalid arguments to appendToObject");Object.keys(b).forEach(function(a){c[a]=b[a]})};a.createCustomHTMLEvent=function(a,b){if(!1===this.isString(a))throw Error("Event name cannot be null and has to be a string");a=new CustomEvent(a,{detail:b});window.dispatchEvent(a)};a.isTopLevelWindow=function(){return"Edge"===b.globals.BROWSER?
window.top.location==window.self.location?!0:!1:window.top==window.self?!0:!1};a.getActiveElement=function(){return document.activeElement};a.verifyJson=function(a,b,d,g){try{var c=forge.md.sha256.create();c.update(JSON.stringify(a));var f=c.digest().toHex(),m=KEYUTIL.getKey(d);if(!0===KJUR.jws.JWS.verify(b,m,g)){var n=b64utoutf8(b.split(".")[1]);return KJUR.jws.JWS.readSafeJSONString(n).hash===f}return!1}catch(q){return!1}};a.isNewVersionUpdated=function(a,b){b=b.split(".");a=a.split(".");var c=
b[1]!==a[1];return b[0]!==a[0]||c?!0:!1};a.isStorePageURL=function(c){return a.isString(c)?"Edge"===b.globals.BROWSER?(new RegExp(f.STORE_URLS[b.globals.BROWSER])).test(c):-1===c.indexOf(f.STORE_URLS[b.globals.BROWSER])?!1:!0:!1};a.upperCaseFirstLetter=function(b){return a.isString(b)?b.charAt(0).toUpperCase()+b.slice(1):b};a.setTimeout=function(b){return new Promise(function(d,c){return a.isInteger(b)?window.setTimeout(d,b):c(Error("Delay must be an integer"))})};a.getValueAtPath=function(d,f,e){f=
b.utils.isString(f)?f.split(/[.[\]]/g).filter(Boolean):f;a.isArray(f)||(f=[f]);return f.reduce(function(b,d){return a.objectHas(b,d)?b[d]:e},d||{})};return a}(e.SymBfw)})(this);
(function(e){e.SymBfw.base64=function(b){var a={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",_utf8Encode:function(a){a=a.replace(/\r\n/g,"\n");for(var b="",c=0;c<a.length;c++){var f=a.charCodeAt(c);128>f?b+=String.fromCharCode(f):(127<f&&2048>f?b+=String.fromCharCode(f>>6|192):(b+=String.fromCharCode(f>>12|224),b+=String.fromCharCode(f>>6&63|128)),b+=String.fromCharCode(f&63|128))}return b},_utf8Decode:function(a){for(var b="",c=0,f,e,g;c<a.length;)f=a.charCodeAt(c),
128>f?(b+=String.fromCharCode(f),c++):191<f&&224>f?(e=a.charCodeAt(c+1),b+=String.fromCharCode((f&31)<<6|e&63),c+=2):(e=a.charCodeAt(c+1),g=a.charCodeAt(c+2),b+=String.fromCharCode((f&15)<<12|(e&63)<<6|g&63),c+=3);return b},encode:function(b){var d="",c=0;for(b=a._utf8Encode(b);c<b.length;){var f=b.charCodeAt(c++);var e=b.charCodeAt(c++);var g=b.charCodeAt(c++);var h=f>>2;f=(f&3)<<4|e>>4;var l=(e&15)<<2|g>>6;var p=g&63;isNaN(e)?l=p=64:isNaN(g)&&(p=64);d=d+a._keyStr.charAt(h)+a._keyStr.charAt(f)+a._keyStr.charAt(l)+
a._keyStr.charAt(p)}return d},decode:function(b){var d="",c=0;for(b=b.replace(/[^A-Za-z0-9\+\/=]\./g,"");c<b.length;){var f=a._keyStr.indexOf(b.charAt(c++));var e=a._keyStr.indexOf(b.charAt(c++));var g=a._keyStr.indexOf(b.charAt(c++));var h=a._keyStr.indexOf(b.charAt(c++));f=f<<2|e>>4;e=(e&15)<<4|g>>2;var l=(g&3)<<6|h;d+=String.fromCharCode(f);64!=g&&(d+=String.fromCharCode(e));64!=h&&(d+=String.fromCharCode(l))}d=a._utf8Decode(d);return d.replace(/\0.*$/g,"")}};return a}()})(this);
(function(e){var b=Math.pow(2,31)-1;e.SymBfw.extensionAdapter=function(a){var f={},d=a.utils.isNil,c=a.utils.isntNil,e=a.utils.isString,k=a.utils.isInteger,g=a.utils.isFunction,h=a.utils.isArray,l=a.utils.isObject,p=a.utils.getValueAtPath;f.getLastError=function(){return chrome.runtime.lastError};f.getInvalidTabId=function(){return d(chrome)||d(chrome.tabs)?-1:chrome.tabs.TAB_ID_NONE};f.getExtensionId=function(){return chrome.runtime.id};f.isPrivateModeAllowed=function(){return new Promise(function(a){chrome.extension.isAllowedIncognitoAccess(function(b){a(b)})})};
f.getBackgroundPage=function(){return d(chrome)||d(chrome.extension)?null:chrome.extension.getBackgroundPage()};f.getExtensionURL=function(a){if(d(chrome)||d(chrome.extension))throw Error("chrome or chrome.extension is null");if(!e(a))throw Error("extensionAdapter.getExtensionURL expects a string path argument");return chrome.extension.getURL(a)};f.getAllWindows=function(a,b){if(d(chrome)||d(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!g(a))throw Error("invalid arguments to extensionAdapter.getAllWindows");
d(b)&&(b={});chrome.windows.getAll(b,a)};f.getCurrentWindow=function(a,b){if(d(chrome)||d(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!g(a))throw Error("invalid arguments to extensionAdapter.getAllWindows");d(b)&&(b={});chrome.windows.getCurrent(b,a)};f.createWindow=function(b,c,g){g=void 0===g?!0:g;if(d(chrome)||d(chrome.windows))throw Error("chrome is null or chrome.windows is null");var n={};a.globals.BROWSER!==a.constants.BROWSER_TYPE.FIREFOX&&(n.focused=g);d(b)||
(n.url=b);chrome.windows.create(n,c)};f.createAppWindow=function(a,b){if(d(chrome)||d(chrome.windows))throw Error("chrome is null or chrome.windows is null");var n={};n.type=chrome.windows.CreateType.PANEL;d(a)||(n.url=a);chrome.windows.create(n,b)};f.createPrivateWindow=function(a,b,c){c=void 0===c?!0:c;if(d(chrome)||d(chrome.windows))throw Error("chrome is null or chrome.windows is null");c={incognito:!0,focused:c};d(a)||(c.url=a);chrome.windows.create(c,b)};f.closeWindow=function(a,b){if(d(chrome)||
d(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!k(a))throw Error("invalid arguments to extensionAdapter.closeWindow");chrome.windows.remove(a,b)};f.focusWindow=function(a,b){if(d(chrome)||d(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!k(a))throw Error("invalid arguments to extensionAdapter.focusWindow");chrome.windows.update(a,{focused:!0},b)};f.addWindowRemovedEventListener=function(a){if(d(chrome)||d(chrome.windows))throw Error("chrome is null or chrome.windows is null");
if(!g(a))throw Error("extensionAdapter.addWindowRemovedEventListener needs a callback");chrome.windows.onRemoved.addListener(a)};f.addWindowFocusedEventListener=function(a){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.windows is null");if(!g(a))throw Error("extensionAdapter.addWindowFocusedEventListener needs a callback");chrome.windows.onFocusChanged.addListener(a)};f.getTab=function(a,b){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!k(a)||
!g(b))throw Error("invalid arguments to extensionAdapter.getTab");chrome.tabs.get(a,b)};f.detectLanguageByTabId=function(a){return function(a){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!k(a))throw Error("invalid arguments to extensionAdapter.detectLanguageByTabId");return!0}(a)&&g(chrome.tabs.detectLanguage)?new Promise(function(b,n){chrome.tabs.detectLanguage(a,function(a){b(a)})}):null};f.getActiveTab=function(a,b){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");
if(!g(a))throw Error("invalid arguments to extensionAdapter.getActiveTab");var n={active:!0};k(b)?n.windowId=b:n.currentWindow=!0;chrome.tabs.query(n,function(b){a(b[0])})};f.getAllTabs=function(a){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!g(a))throw Error("invalid arguments to extensionAdapter.getAllTabs");chrome.tabs.query({},a)};f.getTabsWithURL=function(a,b){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!e(a)||
!g(b))throw Error("invalid arguments to extensionAdapter.getTabsWithURL");chrome.tabs.query({url:a},b)};f.updateTabUrl=function(a,b,c){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!k(a)||!e(b))throw Error("invalid arguments to extensionAdapter.updateTabUrl");chrome.tabs.update(a,{url:b},c)};f.activateTab=function(a,b){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(d(a)||!k(a))throw Error("invalid arguments to extensionAdapter.activateTab");
chrome.tabs.update(a,{active:!0},b)};f.createTab=function(a,b,c){c=void 0===c?!0:c;if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");d(a)?chrome.tabs.create({},b):chrome.tabs.create({url:a,active:c},b)};f.closeTab=function(a,b){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!k(a)&&!h(a))throw Error("invalid arguments to extensionAdapter.closeTab");chrome.tabs.remove(a,b)};f.closeTabAndEnsureBrowserIsAlive=function(a,b){if(!k(a)||
0>=a||c(b)&&!g(b))throw Error("Invalid arguments to extensionAdapter.closeTabAndEnsureBrowserIsAlive()");f.getAllWindows(function(n){1===n.length?f.getAllTabs(function(n){1===n.length&&f.createTab();f.closeTab(a);c(b)&&b()}):(f.closeTab(a),c(b)&&b())})};f.addTabRemovedEventListener=function(a){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!g(a))throw Error("extensionAdapter.addTabRemovedEventListener needs a callback");chrome.tabs.onRemoved.addListener(a)};f.addTabActivatedEventListener=
function(a){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!g(a))throw Error("extensionAdapter.addTabActivatedEventListener needs a callback");chrome.tabs.onActivated.addListener(a)};f.addTabReplacedEventListener=function(a){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(d(a)||!g(a))throw Error("extensionAdapter.addTabReplacedEventListener needs a callback");chrome.tabs.onReplaced.addListener(a)};f.addTabUpdatedEventListener=
function(a){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!g(a))throw Error("extensionAdapter.addTabUpdatedEventListener needs a callback");chrome.tabs.onUpdated.addListener(a)};f.addOnBeforeRequestEventListener=function(a,b,c){if(d(chrome)||d(chrome.webRequest))throw Error("chrome is null or chrome.tabs is null");if(!1===g(a))throw Error("Callback cannot be null");chrome.webRequest.onBeforeRequest.addListener(a,{urls:b},c)};f.removeOnBeforeRequestEventListener=
function(a){chrome.webRequest.onBeforeRequest.removeListener(a)};f.setBrowserIcon=function(a,b){if(d(chrome)||d(chrome.browserAction))throw Error("chrome is null or chrome.browserAction is null");if(d(a))throw Error("invalid arguments to extensionAdapter.setBrowserIcon");chrome.browserAction.setIcon(a,b)};f.sendMessage=function(a,b){if(d(chrome)||d(chrome.runtime))throw Error("chrome or chrome.runtime is null");if(d(a))throw Error("invalid arguments to extensionAdapter.sendMessage");chrome.runtime.sendMessage(a,
b)};f.sendMessageExternal=function(a,b,c){if(d(chrome)||d(chrome.runtime))throw Error("chrome or chrome.runtime is null");if(d(a))throw Error("invalid arguments to extensionAdapter.sendMessage");if(d(b))throw Error("invalid arguments to extensionAdapter.sendMessage");chrome.runtime.sendMessage(a,b,c)};f.sendMessageToTab=function(a,b,c,g){if(d(chrome)||d(chrome.tabs))throw Error("chrome or chrome.tabs is null");if(d(b)||d(a))throw Error("invalid arguments to extensionAdapter.sendMessageToTab");chrome.tabs.sendMessage(a.id,
b,g,c)};f.sendMessageToParentFrame=function(a,b,c,g){if(d(b)||d(a))throw Error("invalid arguments to extensionAdapter.sendMessageToParentFrame");f.getFrame({tabId:a.id,frameId:g}).then(function(d){f.sendMessageToTab(a,b,c,{frameId:d.parentFrameId})})};f.addMessageListener=function(a){if(d(chrome)||d(chrome.runtime))throw Error("chrome or chrome.runtime is null");if(!g(a))throw Error("invalid arguments to extensionAdapter.addMessageListener");chrome.runtime.onMessage.addListener(function(b,c,d){return a(b,
d,c.tab,c.frameId,c.url)})};f.addMessageExternalListener=function(a){if(d(chrome)||d(chrome.runtime))throw Error("chrome or chrome.runtime is null");if(!g(a))throw Error("invalid arguments to extensionAdapter.addMessageExternalListener");chrome.runtime.onMessageExternal.addListener(function(b,c,d){return a(b,c,d)})};f.addContentScriptMessageListener=function(a){f.addMessageListener(a)};f.addTabCreatedEventListener=function(a){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");
if(!g(a))throw Error("extensionAdapter.\u200baddTabCreatedEventListener needs a callback");chrome.tabs.onCreated.addListener(a)};f.addWindowCreatedEventListener=function(a){if(d(chrome)||d(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!g(a))throw Error("extensionAdapter.\u200baddWindowCreatedEventListener needs a callback");chrome.windows.onCreated.addListener(a)};f.getFrame=function(a){var b=null,c={errorOccured:!0,url:null,parentFrameId:null};if(d(chrome)||d(chrome.webNavigation))throw Error("no chrome object available");
a&&(b=d(a.frameId)?new Promise(function(a){a(c)}):new Promise(function(b){chrome.webNavigation.getFrame(a,function(a){b(a)})}));return b};f.getTabID=function(a){return d(a)?null:a.id};f.getWindowIDForTab=function(a){return d(a)?null:a.windowId};f.getWindowID=function(a){return d(a)?null:a.id};f.i18nGetMessage=function(a,b){if(d(window.chrome)||d(window.chrome.i18n))throw Error("Unsupported api");if(!e(a))throw Error("chrome.i18n.getMessage expects a string messageName argument");return chrome.i18n.getMessage(a,
b)};f.hidePopup=function(){window.open("","_self").close()};f.setBadgeText=function(a,b){if(d(chrome)||d(chrome.browserAction))throw Error("chrome or chrome.browserAction is null");if(!e(a)||4<a.length)throw Error("invalid arguments to extensionAdapter.setBadgeText");a={text:a};c(b)&&(a.tabId=b);chrome.browserAction.setBadgeText(a)};f.setTitle=function(a,b){if(d(chrome)||d(chrome.browserAction))throw Error("chrome or chrome.browserAction is null");if(!e(a))throw Error("invalid arguments to extensionAdapter.setTitle");
a={title:a};c(b)&&(a.tabId=b);chrome.browserAction.setTitle(a)};f.setBadgeBackgroundColor=function(a){if(d(chrome)||d(chrome.browserAction))throw Error("chrome or chrome.browserAction is null");if(!e(a))throw Error("invalid arguments to extensionAdapter.setBadgeBackgroundColor");chrome.browserAction.setBadgeBackgroundColor({color:a})};f.onPopoverLoad=function(a){window.addEventListener("load",a)};f.getAllHistory=function(a){a=void 0===a?"":a;return new Promise(function(c){chrome.history.search({text:a,
startTime:0,maxResults:b},function(a){var b=[];a=$jscomp.makeIterator(a);for(var d=a.next();!d.done;d=a.next())d=d.value,e(d.url)&&b.push(d.url);c(b)})})};f.addUrlsToHistory=function(a){if(!h(a))throw Error("urls must be an array");var b=[];a=$jscomp.makeIterator(a);for(var c=a.next();!c.done;c=a.next())b.push(f.addUrlToHistory(c.value));return Promise.all(b)};f.clearHistory=function(){return new Promise(function(a){chrome.history.deleteAll(function(){a()})})};f.addUrlToHistory=function(a){if(!e(a))throw Error("url must be a string");
return new Promise(function(b){chrome.history.addUrl({url:a},function(){b()})})};f.getAllCookies=function(a){a=void 0===a?null:a;return new Promise(function(b){chrome.cookies.getAll({domain:a},function(a){b(a)})})};f.removeCookie=function(a){if(d(a))throw Error("cookie cannot be null");var b=(a.secure?"https://":"http://")+a.domain+a.path;return new Promise(function(c,g){chrome.cookies.remove({name:a.name,url:b},function(a){d(a)&&g(chrome.runtime.lastError);c(a)})})};f.removeCookies=function(a){if(!h(a))throw Error("cookiesArray must be array");
var b=[];a=$jscomp.makeIterator(a);for(var c=a.next();!c.done;c=a.next())b.push(f.removeCookie(c.value));return Promise.all(b)};f.setCookie=function(a){if(d(a))throw Error("cookie cannot be null");var b={url:(new URL((a.secure?"https://":"http://")+a.domain)).toString(),httpOnly:a.httpOnly,name:a.name,sameSite:a.sameSite,secure:a.secure,storeId:a.storeId,value:a.value,path:a.path};e(a.domain)&&"."===a.domain.charAt()&&(b.domain=a.domain);c(a.expirationDate)&&(b.expirationDate=a.expirationDate);return new Promise(function(a,
g){chrome.cookies.set(b,function(b){var f=chrome.runtime.lastError;d(b)&&c(f)&&g(f);a(b)})})};f.setCookies=function(a){if(!h(a))throw Error("cookiesArray must be array");var b=[];a=$jscomp.makeIterator(a);for(var c=a.next();!c.done;c=a.next())b.push(f.setCookie(c.value));return Promise.all(b)};f.onCookieChangedForUrl=function(a,b){if(!e(a))throw Error("url must be a string");if(!g(b))throw Error("callback must be a function");chrome.cookies.onChanged.addListener(function(c){var d=p(c,"cookie.domain");
e(d)&&d.includes(a)?b(c):b()})};f.checkCookieContentSettingsForUrl=function(a){if(d(chrome)||d(chrome.contentSettings))throw Error("Unsupported api");if(!e(a))throw Error("primaryUrl must be a string");return new Promise(function(b,c){chrome.contentSettings.cookies.get({primaryUrl:a},function(a){a.setting===chrome.contentSettings.CookiesContentSetting.ALLOW?b():c()})})};f.getVersion=function(){return chrome.runtime.getManifest().version};f.setProxySettings=function(a){if(d(chrome)||d(chrome.proxy))throw Error("Unsupported api");
if(!l(a))throw Error("details must be an object");return new Promise(function(b){chrome.proxy.settings.set(a,b)})};f.getProxySettings=function(){if(d(chrome)||d(chrome.proxy))throw Error("Unsupported api");return new Promise(function(a){chrome.proxy.settings.get({},a)})};f.onProxySettingsChange=function(a){if(d(chrome)||d(chrome.proxy))throw Error("Unsupported api");if(!g(a))throw Error("callback must be a function");chrome.proxy.settings.onChange.addListener(a)};f.onProxyError=function(a){if(d(chrome)||
d(chrome.proxy))throw Error("Unsupported api");if(!g(a))throw Error("callback must be a function");chrome.proxy.onProxyError.addListener(a)};f.onWebRequestAuthRequired=function(a){if(d(chrome)||d(chrome.webRequest))throw Error("Unsupported api");if(!g(a))throw Error("callback must be a function");chrome.webRequest.onAuthRequired.addListener(a,{urls:["<all_urls>"]},["asyncBlocking"])};f.init=function(){};f.returnAdapter=function(){var a={};a.getExtensionURL=f.getExtensionURL;a.getBackgroundPage=f.getBackgroundPage;
a.sendMessage=f.sendMessage;a.addMessageListener=f.addMessageListener;a.addContentScriptMessageListener=f.addContentScriptMessageListener;a.getExtensionId=f.getExtensionId;a.init=f.init;try{return chrome.tabs?f:a}catch(q){return a}};return f.returnAdapter()}(e.SymBfw)})(this);
(function(e){e.SymBfw.clipboard=function(b){var a={},f=b.utils.isNil,d=b.logger;a.createDummyTextAreaAndSetText=function(a){var b=document.createElement("textarea");b.style.position="fixed";b.style.top=0;b.style.left=0;b.style.width="2em";b.style.height="2em";b.style.padding=0;b.style.border="none";b.style.outline="none";b.style.boxShadow="none";b.style.background="transparent";b.value=a;document.body.appendChild(b);b.select();return b};a.copyToClipboard=function(b){if(f(b)||""===b)throw Error("Value to copy to clipboard cannot be null");
b=a.createDummyTextAreaAndSetText(b);document.execCommand("copy")||d.error("Failed to copy to clipboard");document.body.removeChild(b)};return a}(e.SymBfw)})(this);
(function(e){(e.SymBfw=e.SymBfw||{}).storage=function(b){var a={},f=b.utils.isNil,d=b.utils.isntNil,c=b.utils.isFunction,e=b.logger,k=function(a,b){this.name=a;this.error=b};k.prototype.toString=function(){return"Name:"+this.name+":Error:"+this.error};a.StorageException=k;a.set=function(a,b,d){if(f(a))throw Error("Key cannot be null");if(f(b))throw Error("Value cannot be null");var g={};g[a]=b;chrome.storage.local.set(g,function(){var g=chrome.runtime.lastError,h=!1,l=null;f(g)?h=!0:(e.log("Storing{"+
a+":"+b+"} caused an error:"+g),l=new k("Browser Exception",g));c(d)&&setTimeout(function(){d(h,l)},1)})};a.get=function(a,b){if(f(a))throw Error("Key cannot be null");if(!c(b))throw Error("Callback cannot be null or is not a function");chrome.storage.local.get(a,function(c){var g=chrome.runtime.lastError,h=!1,l=null,m=null;l=c[a];f(g)&&d(l)?h=!0:(e.log("Getting value for "+a+" caused an error:"+g),m=new k("Browser Exception",g));setTimeout(function(){b(h,l,m)},1)})};a.clear=function(a){chrome.storage.local.clear(function(){var b=
chrome.runtime.lastError,d=null,g=!1;f(b)?g=!0:d=new k("Browser Exception",b);c(a)&&setTimeout(function(){a(g,d)},1)})};a.remove=function(a,b){if(f(a))throw Error("Key cannot be null");chrome.storage.local.remove(a,function(){var a=chrome.runtime.lastError,d=null,g=!1;f(a)?g=!0:d=new k("Browser Exception",a);c(b)&&setTimeout(function(){b(g,d)},1)})};return a}(e.SymBfw)})(this);
(function(e){e.SymBfw.settings=function(b){var a={containers:{}},f=b.storage,d=b.utils.isntNil,c=b.utils.isNil,e=b.utils.isFunction,k=b.logger,g=function(b,c){if(d(a.containers[b]))throw Error("Container name is not unique");this.name=b;this.persist=c;this.collection={};this.initialized=!1};g.prototype.initialize=function(b){var c=this.name,d=this;this.initialized=!0;if(!1===this.persist)a.containers[c]=this;else{var g=function(g,f){g?(a.containers[c]=d,setTimeout(function(){b(!0,d,null)},1)):setTimeout(function(){b(!1,
null,f)},1)};f.get(c,function(h,e,l){h?(d.setCollection(e),a.containers[c]=d,setTimeout(function(){b(!0,d,null)},1)):f.set(c,d.getCollection(),g)})}};g.prototype.setCollection=function(a){this.collection=a};g.prototype.getCollection=function(){return this.collection};g.prototype.setObject=function(a,b,d){if(c(a))throw Error("Key cannot be null");if(c(b))throw Error("Value cannot be null");if(!1===this.initialized)throw Error("Settings not initialized");this.collection[a]=b;!1===this.persist?e(d)&&
setTimeout(function(){d(!0,null)},1):f.set(this.name,this.collection,d)};g.prototype.getObject=function(a){if(c(a))throw Error("Key cannot be null");if(!1===this.initialized)throw Error("Settings not initialized");a=this.collection[a];c(a)&&(a=null);return a};g.prototype.removeObject=function(a,b){if(c(a))throw Error("Key cannot be null");if(!1===this.initialized)throw Error("Settings not initialized");delete this.collection[a];!1===this.persist?e(b)&&setTimeout(function(){b(!0,null)},1):f.set(this.name,
this.collection,b)};g.prototype.serialize=function(){return JSON.stringify(this.collection)};g.prototype.shouldPersist=function(){return this.persist};a.loadSettingsContainer=function(b,f,p){if(c(b))throw Error("Name cannot be null");c(f)&&(f=!1);if(f&&!e(p))throw Error("Callback cannot be null or is not a function");var h=a.containers[b];if(d(h)){if(!f)return h;setTimeout(function(){p(!0,h,null)},1)}else if(b=new g(b,f),b.initialize(p),!f)return b};a.deleteSettingsContainer=function(b,g){if(c(b))throw Error("Name cannot be null");
var h=a.containers[b];d(h)&&(a.containers[b]=null);!1===h.shouldPersist()?e(g)&&setTimeout(function(){g(!0,null)},1):f.remove(b,g)};a.resetSettingsCollection=function(b,d){if(c(b))throw Error("Name cannot be null");b=a.containers[b];if(c(b))throw Error("Container was never previously loaded");var g=b.getCollection();if(c(g))k.info("Collection is empty"),e(d)&&setTimeout(function(){d(!1,Error("Collection is empty"))},1);else{for(var h in g)delete g[h];!1===b.shouldPersist()?e(d)&&setTimeout(function(){d(!0,
null)},1):f.set(b.name,b.collection,d)}};a.Settings=g;return a}(e.SymBfw)})(this);
(function(e){e.SymBfw.secureSettings=function(b){var a={},f=b.settings,d=b.utils.isntNil,c=b.utils.isNil,e=b.utils.isFunction,k=b.utils.isString,g=b.logger,h=function(a){var b=forge.md.sha256.create();b.update(a);return b.digest().toHex()},l=function(a,b){var c=forge.hmac.create();c.start("sha256",b);c.update(a);return c.digest().toHex()},p=function(a,b,c,d,g){b=forge.util.createBuffer(b);a=a?forge.cipher.createCipher(g,c):forge.cipher.createDecipher(g,c);a.start({iv:d});a.update(b);a.finish();return a.output.getBytes()},
n=function(a,b){this.initialized=!1};n.prototype.initialize=function(a,b,e){var h=this;f.loadSettingsContainer(a,!0,function(p,k,n){if(!1===p)setTimeout(function(){e(!1,null,n)},1);else{var m=k.getObject("iv"),q=k.getObject("salt");p=null;if(c(m)||c(q))p=new Promise(function(b,c){f.resetSettingsCollection(a,function(a,d){if(!a)return c(Error("Failed to reset OCL container"));h.iv=forge.random.getBytesSync(128);h.salt=forge.random.getBytesSync(128);k.setObject("iv",JSON.stringify(h.iv));k.setObject("salt",
JSON.stringify(h.salt));b()})});else try{h.iv=JSON.parse(m),h.salt=JSON.parse(q)}catch(u){setTimeout(function(){var a="Failed to intialize: "+u.toString();g.error(u);e(!1,null,a)},1);return}m=function(){h.derivedKey=forge.pkcs5.pbkdf2(b,h.salt,1E3,32);var a=k.getObject("hmac"),c=l(h.salt,h.derivedKey);if(d(a)){if(a!==c){setTimeout(function(){e(!1,null,"Passwords does not match")},1);return}}else k.setObject("hmac",c);h.container=k;h.initialized=!0;setTimeout(function(){e(!0,h,null)},1)};c(p)?m():
p.then(m,function(a){g.error(a);e(!1,null,a)})}})};n.prototype.setObject=function(a,b,d){if(!k(a))throw Error("Key must be a string");if(c(b))throw Error("Value cannot be null");if(!this.initialized)throw Error("SecureSettings not initialized");a=h(a);b=JSON.stringify(b);b=p(!0,b,this.derivedKey,this.iv,"AES-CBC");b=forge.util.encode64(b);var g=l(b,this.derivedKey);this.container.setObject(a,{data:b,hmac:g},d)};n.prototype.getObject=function(a){if(!k(a))throw Error("Key must be a string");if(!this.initialized)throw Error("SecureSettings not initialized");
a=h(a);a=this.container.getObject(a);if(c(a))return null;var b=a.data;if(l(b,this.derivedKey)!==a.hmac)throw Error("The data is corrupted");a=forge.util.decode64(b);a=p(!1,a,this.derivedKey,this.iv,"AES-CBC");try{var d=JSON.parse(a)}catch(t){throw d="Failed to parse data: "+t.toString(),g.error(t),Error(d);}return d};n.prototype.removeObject=function(a,b){if(!k(a))throw Error("Key must be a string");if(!1===this.initialized)throw Error("SecureSettings not initialized");a=h(a);this.container.removeObject(a,
b)};a.loadSecureSettingsContainer=function(a,b,c){if(!k(a))throw Error("name must be a string");if(!k(b))throw Error("password must be a string");if(!e(c))throw Error("callback must be a function");b=h(b);(new n).initialize(a,b,c)};a.deleteSecureSettingsContainer=function(a,b){f.deleteSettingsContainer(a,b)};a.resetSecureSettingsCollection=function(a,b){if(c(a))throw Error("secureSettings container name is null");f.loadSettingsContainer(a,!0,function(a,c,d){if(!1===a)setTimeout(function(){e(b)&&b(!1,
d)},1);else{a=c.collection;for(var g in a)"salt"!==g&&"iv"!==g&&c.removeObject(g);e(b)&&b(!0,null)}})};a.SecureSettings=n;return a}(e.SymBfw)})(this);
(function(e){e.SymBfw.localizer=function(b){var a=b.utils.isNil,f=b.utils.isntNil,d=b.utils.isString,c=b.utils.isBoolean,e=b.utils.isArray,k=b.utils.isFunction,g=b.constants.localizer,h="ar he arc bcc bqi ckb dv fa glk lrc mzn pnb ps sd ug ur yi".split(" "),l={stringsMap:{},initialized:!1,setNavigatorLanguageAndLocale:function(){if(a(this.supportedLocales))throw Error("Supported locales was never set");var b=navigator.language,d=b.split("-"),g=d[0];d=d[1];var e=g.toLowerCase();f(d)&&(d=d.toLowerCase(),
e=e+"_"+d);var h=this.supportedLocales[e];c(h)&&h||(h=this.supportedLocales[g],c(h)&&h?e=g:(h=this.supportedLocales[d],c(h)&&h?e=d:(e="en",b="en-US")));this.locale=e;this.navigatorLanguage=b},getNavigatorLanguage:function(){if(f(this.navigatorLanguage))return this.navigatorLanguage;this.setNavigatorLanguageAndLocale();return this.navigatorLanguage},getLocale:function(){if(f(this.locale))return this.locale;this.setNavigatorLanguageAndLocale();return this.locale},getCurrentLanguageDirection:function(){var a=
l.getLocale(),b="ltr";-1<h.indexOf(a)&&(b="rtl");return b},loadDefaultDictionary:function(a){l.loadDictionary(g.DEFAULT_MESSAGES_DICTIONARY,a)},loadDictionary:function(c,g){if(!1===d(c))throw Error("Dictionary name cannot be null");if(!1===k(g))throw Error("Callback cannot be null");if(a(this.path))throw Error("Path to localized folder is not set. Need to call initialize before using this API");if(f(this.stringsMap[c]))setTimeout(function(){g(!0,null)},1);else{var e=this.getLocale(),h=this.path+"/"+
e+"/"+c+".json";e=new XMLHttpRequest;e.open("GET",h,!0);e.addEventListener("load",function(a){var d=a.target.status;d===("Safari"===b.globals.BROWSER?0:200)?(a=JSON.parse(a.target.response),l.stringsMap[c]=a,g(!0,null),l.initialized=!0):g(!1,Error("File at path:"+h+" does not exist. Status Code:"+d))});e.send()}},getLocalizedString:function(a){return l.getLocalizedStringFromDictionary(a,g.DEFAULT_MESSAGES_DICTIONARY)},getLocalizedStrings:function(a){return l.getLocalizedStringsFromDictionary(a,g.DEFAULT_MESSAGES_DICTIONARY)},
getAllLocalizedStrings:function(){return l.getAllLocalizedStringsFromDictionary(g.DEFAULT_MESSAGES_DICTIONARY)},getLocalizedStringFromDictionary:function(a,b){if(!1===d(a))throw Error("Unlocalized String cannot be null or is not a string");return l.getLocalizedStringsFromDictionary([a],b)[a]},getLocalizedStringsFromDictionary:function(b,c){if(!1===e(b))throw Error("Array of strings cannot be null.");if(0===b.length)throw Error("Array of strings cannot be empty.");if(!1===d(c))throw Error("Dictionary name cannot be null");
var g=this.stringsMap[c];if(a(g))throw Error("Dictionary "+c+" is being used without being loaded");c={};for(var f in b){var h=b[f],l=g[h];a(l)?c[h]=h:(l=l.message,a(l)?c[h]=h:c[h]=l)}return c},getAllLocalizedStringsFromDictionary:function(b){if(!1===d(b))throw Error("Dictionary name cannot be null");var c=this.stringsMap[b];if(a(c))throw Error("Dictionary "+b+" is being used without being loaded");b={};for(var g in c)b[g]=c[g].message;return b},getLocalizedStringsWithFormat:function(b){var c={},
d;for(d in b){for(var g=[],f=$jscomp.makeIterator(b[d]),e=f.next();!e.done;e=f.next())e=e.value,a(e)?g.push(null):g.push(l.getLocalizedString(e));g=l.getLocalizedStringWithFormat(d,g);c[d]=g}return c},getLocalizedStringWithFormat:function(a,b){return l.getLocalizedStringWithFormatFromDictionary(a,b,g.DEFAULT_MESSAGES_DICTIONARY)},getLocalizedStringWithFormatFromDictionary:function(b,c,d){if(a(c))throw Error("Format parameters cannot be null");b=l.getLocalizedStringFromDictionary(b,d);for(var g in c)d=
c[g],a(d)||(b=b.replace("{"+g+"}",d));return b},getLocalizedStringFromNativeLocalizer:function(a,c){return b.extensionAdapter.i18nGetMessage(a,c)},initialize:function(c,d,g){if(a(c))throw Error("Supported locales cannot be null");a(g)&&(g=b.extensionAdapter.getExtensionURL("content/i18n"));l.path=g;this.supportedLocales=c;b.extensionAdapter.addMessageListener(l.handleMessage);l.loadDefaultDictionary(d)},handleMessage:function(b,c,d){if(!a(b)){d=b.id;var f=b.payload;if(!a(d)&&!a(f)){var e=null,h=!0;
switch(d){case g.GET_LOCALIZED_STRING:e=l.getLocalizedString(f);break;case g.GET_LOCALIZED_STRINGS:e=l.getLocalizedStrings(f);break;case g.GET_ALL_LOCALIZED_STRINGS:e=l.getAllLocalizedStrings(f);break;case g.GET_LOCALIZED_STRING_FROM_DICTIONARY:e=l.getLocalizedStringFromDictionary(f.string,f.name);break;case g.GET_LOCALIZED_STRINGS_FROM_DICTIONARY:e=l.getLocalizedStringsFromDictionary(f.array,f.name);break;case g.GET_LOCALIZED_STRING_WITH_FORMAT:e=l.getLocalizedStringWithFormat(f.string,f.params);
break;case g.GET_LOCALIZED_STRING_WITH_FORMAT_FROM_DICTIONARY:e=l.getLocalizedStringWithFormatFromDictionary(f.string,f.params,f.name);break;case g.GET_CURRENT_LANGUAGE_DIRECTION:e=l.getCurrentLanguageDirection();break;case g.GET_LOCALIZED_STRINGS_WITH_FORMAT:e=l.getLocalizedStringsWithFormat(f.formatStringDict);break;default:h=!1}h&&c({id:b.id,payload:e})}}}};return l}(e.SymBfw)})(this);
(function(e){e=e.SymBfw=e.SymBfw||{};var b={APPLICATION_NAME:"APPLICATION_NAME",APPLICATION_VERSION:"APPLICATION_VERSION",CLIENT_ID:"CLIENT_ID",DATA_SOURCE:"DATA_SOURCE",TRACKING_ID:"TRACKING_ID",USER_AGENT:"USER_AGENT",USER_LANGUAGE:"USER_LANGUAGE",GOOGLE_ANALYTICS_PROTOCOL_VERSION:"GOOGLE_ANALYTICS_PROTOCOL_VERSION",ANONYMIZE_IP:"ANONYMIZE_IP"};b.defaultParametersList=[b.APPLICATION_NAME,b.APPLICATION_VERSION,b.CLIENT_ID,b.DATA_SOURCE,b.TRACKING_ID,b.GOOGLE_ANALYTICS_PROTOCOL_VERSION,b.ANONYMIZE_IP];
b.dataSource={BROWSER_EXTENSION:"web",MOBILE_APP:"app"};b.HIT_TYPE={PAGE_VIEW:"pageview",SCREEN_VIEW:"screenview",EVENT:"event",EXCEPTION:"exception"};b.MESSAGES={SEND_TELEMETRY_TO_BGPROXY:"b021e29a-4fe3-4a60-865f-0cf783318187"};b.parameters={NON_INTERACTION_HIT:"ni",HIT_TYPE:"t",CATEGORY:"ec",ACTION:"ea",LABEL:"el",DOCUMENT_PATH:"dp",DOCUMENT_TITLE:"dt",CUSTOM_DIMENSION1:"cd1",PRODUCT_IMPRESSION_BRAND1:"il1pi1br",ITEM_CATEGORY:"iv",CAMPAIGN_SOURCE:"cs",CAMPAIGN_MEDIUM:"cm"};b.TELEMETRY_CATEGORY=
{BROWSER:"Browser",EXTENSION:"Extension"};b.actionType={BROWSER:{LAUNCH:"launch",UPDATE:"update"},EXTENSION:{INSTALL:"install",UPDATE:"update"}};b.defaultParameters={APPLICATION_NAME:{maxLength:100,key:"an"},APPLICATION_VERSION:{maxLength:100,key:"av"},CLIENT_ID:{maxLength:100,key:"cid"},DATA_SOURCE:{maxLength:50,key:"ds",value:b.dataSource.BROWSER_EXTENSION},TRACKING_ID:{maxLength:100,key:"tid"},USER_AGENT:{maxLength:1E3,key:"ua"},USER_LANGUAGE:{maxLength:20,key:"ul"},GOOGLE_ANALYTICS_PROTOCOL_VERSION:{maxLength:100,
key:"v",value:1},ANONYMIZE_IP:{maxLength:1,key:"aip",value:1}};e.telemetryConstants=b})(this);
(function(e){e.SymBfw.telemetrySettings=function(b){var a={},f=b.settings,d=b.utils.isNil,c=b.utils.isBoolean,e=b.utils.isFunction,k=b.constants,g=b.logger;a.settingsContainer=null;a.initialize=function(b){if(!e(b))throw Error("callback must be a function");f.loadSettingsContainer(k.telemetry.BFW_TELEMETRY_SETTINGS_CONTAINER,!0,function(c,f,e){!1===c||d(f)?(g.error("failed to load BFW_TELEMETRY_SETTINGS_CONTAINER"),b(!1)):(a.settingsContainer=f,b(!0))})};a.isTelemetryEnabled=function(){if(d(this.settingsContainer))return g.log("Settings not initialized"),
!1;var a=this.settingsContainer.getObject(k.telemetry.TELEMETRY_ENABLED);return d(a)?!1:a};a.setTelemetryEnabled=function(a){if(d(this.settingsContainer))throw Error("Settings not initialized");if(!c(a))throw Error("Parameter must be a boolean");this.settingsContainer.setObject(k.telemetry.TELEMETRY_ENABLED,a)};a.isTelemetryOptOutShown=function(){if(d(this.settingsContainer))throw Error("Settings not initialized");var a=this.settingsContainer.getObject(k.telemetry.TELEMETRY_OPT_OUT_SHOWN);return d(a)?
!1:a};a.setTelemetryOptOutShown=function(a){if(d(this.settingsContainer))throw Error("Settings not initialized");if(!c(a))throw Error("Parameter must be a boolean");this.settingsContainer.setObject(k.telemetry.TELEMETRY_OPT_OUT_SHOWN,a)};a.hasUserRespondedInOptOutPage=function(){if(d(this.settingsContainer))return g.log("Settings not initialized"),!1;var a=this.settingsContainer.getObject(k.telemetry.USER_RESPONDED_IN_OPT_OUT_PAGE);return d(a)?!1:a};a.setUserRespondedInOptOutPage=function(a){if(d(this.settingsContainer))throw Error("Settings not initialized");
if(!c(a))throw Error("Parameter must be a boolean");this.settingsContainer.setObject(k.telemetry.USER_RESPONDED_IN_OPT_OUT_PAGE,a,function(a){b.telemetry.flushQueue()})};a.setLastOfferDate=function(a){if(d(a))throw Error("Date cannot be null.");this.settingsContainer.setObject(k.telemetry.LAST_OFFER_DATE,a.getTime())};a.getLastOfferDate=function(){var a=this.settingsContainer.getObject(k.telemetry.LAST_OFFER_DATE);return d(a)||!1===b.utils.isInteger(a)?null:new Date(a)};return a}(e.SymBfw)})(this);
(function(e){(e.SymBfw=e.SymBfw||{}).telemetrySCD=function(b){var a={GOOGLE_ANALYTICS_URL:"https://www.google-analytics.com/collect",REQUEST_TYPE:"POST",COLLECTION_STATE:!0,serialize:function(){return{ga_url:a.GOOGLE_ANALYTICS_URL,request_type:a.REQUEST_TYPE,collection_state:a.COLLECTION_STATE}}};return a}(e.SymBfw)})(this);
(function(e){e.SymBfw.Telemetry=function(b){var a=b.utils.isNil,f=b.utils.isntNil,d=b.utils.isFunction,c=b.utils.isArray,e=b.telemetryConstants,k=b.logger,g=b.utils.isBoolean,h=function(a,b){this.defaultParameters=null;this.initialized=!1;this._telemetryParamsQueue=[];f(a)?this.message=a:this.message=e.MESSAGES.SEND_TELEMETRY_TO_BGPROXY;this.ignoreTelemetryEnableSettings=!1;g(b)&&!0===b&&(this.ignoreTelemetryEnableSettings=!0)};h.prototype.constructMessageBody=function(b){if(a(b))throw Error("parameters cannot be null");
if(0===Object.keys(b).length)throw Error("parameters object is empty. Need at-least one property");var c="",d;for(d in b)c+=d+"="+b[d]+"&";return c=c.substring(0,c.length-1)};h.prototype.init=function(c,g){var f=this;if(!0!==this.initialized){if(a(c))throw Error("defaultParameters cannot be null");if(!d(g))throw Error("callback is not defined or is not a function");b.telemetryConstants.defaultParametersList.forEach(function(b){if(a(c[b]))throw Error("could not find mandatory parameter "+b+" in parameters list");
});var h={};for(m in c){var l=b.telemetryConstants.defaultParameters[m];a(l.key)||(h[l.key]=c[m])}var m=e.defaultParameters[e.USER_LANGUAGE];a(h[m.key])&&(h[m.key]=navigator.language);var p=this.constructMessageBody(h);if(a(p)||0===p.length)throw Error("constructMessageBody returned an empty string");b.telemetrySettings.initialize(function(a){!1===a?(k.error("failed to initialize BfwTelemetry"),g(!1)):(b.extensionAdapter.addMessageListener(f.handleMessage.bind(f)),f.defaultParameters=p,f.initialized=
!0,g(!0))})}};h.prototype.send=function(d){if(!1===this.ignoreTelemetryEnableSettings&&!1===b.telemetrySettings.isTelemetryEnabled())return!1===b.telemetrySettings.hasUserRespondedInOptOutPage()&&f(this._telemetryParamsQueue)&&this._telemetryParamsQueue.push(d),!1;if(a(this.defaultParameters)||!1===this.initialized)return!1;if(a(d))throw Error("parameters are required for sending telemetry events");var g=new XMLHttpRequest;g.open(b.telemetrySCD.REQUEST_TYPE,b.telemetrySCD.GOOGLE_ANALYTICS_URL,!0);
g.addEventListener("load",function(a){k.debug("xhr load status: "+a.target.status)});g.addEventListener("error",function(a){k.debug("xhr error status: "+a.target.status)});d=this.constructMessageBody(d);if(a(d)||0===d.length)return!1;d+="&"+this.defaultParameters;g.send(d);c(this._telemetryParamsQueue)&&0<this._telemetryParamsQueue.length&&this.flushQueue();return!0};h.prototype.handleMessage=function(b,c,d){var g=this;if(b.id===this.message&&(c=b.payload,!a(c)&&!a(c.parameters)))return setTimeout(function(){g.send(b.payload.parameters)}),
!0};h.prototype.flushQueue=function(){var a=this;setTimeout(function(){for(var b in a._telemetryParamsQueue)a.send(a._telemetryParamsQueue[b]);a._telemetryParamsQueue=[]},2E3)};return h}(e.SymBfw);e.SymBfw.telemetry=new SymBfw.Telemetry})(this);
(function(e){e.SymBfw.telemetryWrapper=function(b){var a=b.utils.isNil,f=b.utils.isString,d={TELEMETRY_CATEGORY:"bfw",TELEMETRY_TYPE:"event",componentType:{LOGGER:"logger",LOCALIZER:"localizer",STORAGE:"storage",SETTINGS:"settings",SECURE_SETTINGS:"secureSettings"},actionType:{WARN:"warn",ERROR:"error"},parameters:{EVENT:"t",CATEGORY:"ec",ACTION:"ea",PAYLOAD:"el"},send:function(c,e,k){if(!f(c))throw Error("componentType should be a string");if(!f(e))throw Error("actionType should be a string");if(a(k))throw Error("payload should not be Nil");
if(!f(k)){if(!(k instanceof Error))throw Error("payload should be an instanceof Error other than a string");k=k.toString()}var g={};g[d.parameters.EVENT]=d.TELEMETRY_TYPE;g[d.parameters.CATEGORY]=d.TELEMETRY_CATEGORY+"-"+c;g[d.parameters.ACTION]=e;g[d.parameters.PAYLOAD]=k;return(b.telemetry||b.telemetryProxy).send(g)}};return d}(e.SymBfw)})(this);
(function(e){e=e.SymBfw=e.SymBfw||{};var b={APPLICATION_NAME:"APPLICATION_NAME",APPLICATION_VERSION:"APPLICATION_VERSION",DATA_SOURCE:"DATA_SOURCE",USER_LANGUAGE:"USER_LANGUAGE",TOKEN:"TOKEN",CLIENT_ID:"CLIENT_ID"};b.defaultParametersList=[b.APPLICATION_NAME,b.APPLICATION_VERSION,b.DATA_SOURCE];b.dataSource={BROWSER_EXTENSION:"web",MOBILE_APP:"app"};b.HIT_TYPE={PAGE_VIEW:"pageview",SCREEN_VIEW:"screenview",EVENT:"event",EXCEPTION:"exception"};b.MESSAGES={SEND_TELEMETRY_TO_V2PROXY:"3fd353b0-319d-41f3-b3a3-22e893730e65"};
b.parameters={NON_INTERACTION_HIT:"ni",HIT_TYPE:"t",ACTION:"ea",LABEL:"el",DOCUMENT_PATH:"dp",DOCUMENT_TITLE:"dt",CUSTOM_DIMENSION1:"cd1",PRODUCT_IMPRESSION_BRAND1:"il1pi1br",ITEM_CATEGORY:"iv",CAMPAIGN_SOURCE:"cs",CAMPAIGN_MEDIUM:"cm"};b.TELEMETRY_CATEGORY={BROWSER:"Browser",EXTENSION:"Extension"};b.actionType={BROWSER:{LAUNCH:"launch",UPDATE:"update"},EXTENSION:{INSTALL:"install",UPDATE:"update"}};b.defaultParameters={APPLICATION_NAME:{maxLength:100,key:"app_name"},APPLICATION_VERSION:{maxLength:100,
key:"app_version"},DATA_SOURCE:{maxLength:50,key:"data_source",value:b.dataSource.BROWSER_EXTENSION},USER_LANGUAGE:{maxLength:20,key:"user_language"}};e.telemetryV2Constants=b})(this);
(function(e){e.SymBfw.TelemetryV2=function(b){var a=b.utils.isNil,f=b.utils.isntNil,d=b.utils.isFunction,c=b.utils.isArray,e=b.telemetryV2Constants,k=b.logger,g=b.utils.isBoolean,h=function(a,b){this._defaultParameters=this._mixpanel=null;this._initialized=!1;this._telemetryParamsQueue=[];f(a)?this._message=a:this._message=e.MESSAGES.SEND_TELEMETRY_TO_V2PROXY;this._ignoreTelemetryEnableSettings=!1;g(b)&&!0===b&&(this._ignoreTelemetryEnableSettings=!0)};h.prototype.init=function(c,g){var f=this;if(!0===
this._initialized)g(!0);else{if(!mixpanel)throw Error("mixpanel library not loaded from thirdparty");if(a(c))throw Error("defaultParameters cannot be null");var e=Object.assign({},c),h=e[b.telemetryV2Constants.TOKEN],l=e[b.telemetryV2Constants.CLIENT_ID];delete e[b.telemetryV2Constants.TOKEN];delete e[b.telemetryV2Constants.CLIENT_ID];if(a(h))throw Error("Property: "+b.telemetryV2Constants.TOKEN+" must be defined in defaultParameters");if(a(l))throw Error("Property: "+b.telemetryV2Constants.CLIENT_ID+
" must be defined in defaultParameters");if(!d(g))throw Error("callback is not defined or is not a function");b.telemetrySettings.initialize(function(a){!1===a?(k.error("failed to initialize BfwTelemetryV2"),g(!1)):(f.setDefaultParameters(e),f._initializeMixpanel(h,l),b.extensionAdapter.addMessageListener(f._handleMessage.bind(f)),f._initialized=!0,g(!0))})}};h.prototype.setDefaultParameters=function(c){b.telemetryV2Constants.defaultParametersList.forEach(function(b){if(a(c[b]))throw Error("could not find mandatory parameter "+
b+" in parameters list");});var d={};for(f in c){var g=b.telemetryV2Constants.defaultParameters[f];if(a(g))throw Error("Property not found in TelemetryV2Constants.defaultParameters: "+f);a(g.key)||(d[g.key]=c[f])}var f=e.defaultParameters[e.USER_LANGUAGE];a(d[f.key])&&(d[f.key]=navigator.language);this._defaultParameters=d;this._mixpanel&&this._mixpanel.register(this._defaultParameters);return!0};h.prototype.send=function(d,g){if(!1===this._ignoreTelemetryEnableSettings&&!1===b.telemetrySettings.isTelemetryEnabled())return f(this._telemetryParamsQueue)&&
!b.telemetrySettings.hasUserRespondedInOptOutPage()&&this._telemetryParamsQueue.push({event:d,parameters:g}),!1;if(a(this._defaultParameters)||!1===this._initialized)return!1;if(a(d))throw Error("event is required for sending telemetry events");this._mixpanel.track(d,g,function(a){a?k.debug("successfully sent event to mixpanel"):k.debug("error sending event to mixpanel")});c(this._telemetryParamsQueue)&&0<this._telemetryParamsQueue.length&&this.flushQueue();return!0};h.prototype._handleMessage=function(b,
c,d){var g=this;if(b.id===this._message){var f=b.payload;a(f)||setTimeout(function(){g.send(f.event,f.parameters)})}};h.prototype.flushQueue=function(){var a=this;setTimeout(function(){for(var b in a._telemetryParamsQueue){var c=a._telemetryParamsQueue[b];a.send(c.event,c.parameters)}a._telemetryParamsQueue=[]},2E3)};h.prototype._initializeMixpanel=function(a,b){mixpanel.init(a);mixpanel.identify(b);mixpanel.register(this._defaultParameters);this._mixpanel=mixpanel};return h}(e.SymBfw);e.SymBfw.telemetryV2=
new SymBfw.TelemetryV2})(this);
(function(e){e.SymBfw.Notification=function(b){var a=b.constants.uiConstants,f=b.utils.isNil,d=b.utils.isntNil,c=b.extensionAdapter,e=function(c,g,e,l){if(f(c))throw Error("A description must be provided.");if(f(g))throw Error("A type must be provided.");if(f(e))throw Error("imageUrl must be provided");d(l)?this.title=l:this.title="";switch(g){case a.NOTIFICATION.TYPE.QUESTION:case a.NOTIFICATION.TYPE.TIMED:break;default:throw Error("The notification type passed was not recognized.");}this.description=
c;this.type=g;this.guid=b.utils.createNewGuid();this.imageUrl=e};e.prototype.getDescription=function(){return this.description};e.prototype.setID=function(a){this.guid=a};e.prototype.getID=function(){return this.guid};e.prototype.getType=function(){return this.type};e.prototype.getTitle=function(){return this.title};e.prototype.getImage=function(){return c.getExtensionURL(this.imageUrl)};e.prototype.getRelativeImageURL=function(){return this.imageUrl};e.prototype.handleEvent=function(a){};e.prototype.serialize=
function(){return{description:this.description,type:this.type,notificationID:this.guid,imageUrl:this.getRelativeImageURL(),title:this.title}};e.prototype.onDisplayed=function(){};return e}(e.SymBfw)})(this);
(function(e){e.SymBfw.QuestionNotification=function(b){var a=b.utils.isNil,f=b.utils.isntNil,d=b.utils.isFunction,c=b.logger,e=b.Notification,k=b.constants.uiConstants;b=function(b,c,f,m,n,q,r){r=void 0===r?[]:r;e.call(this,b,k.NOTIFICATION.TYPE.QUESTION,n,q);if(a(c))throw Error("Data cannot be null");if(a(f))throw Error("Default button text cannot be null.");if(!1===d(m))throw Error("Default button action cannot be null.");this.data=c;this.defaultButtonText=f;this.defaultButtonAction=m;this.blockListedUrls=
r};b.prototype=Object.create(e.prototype);b.prototype.addSecondaryLink=function(b,c){if(a(b))throw Error("Secondary link text cannot be null.");if(!1===d(c))throw Error("Secondary link action cannot be null.");this.secondaryLinkText=b;this.secondaryLinkAction=c};b.prototype.addThirdButton=function(b,c){if(a(b))throw Error("Third button text cannot be null");if(!1===d(c))throw Error("Third button action cannot be null.");this._thirdButtonText=b;this._thirdButtonAction=c};b.prototype.addCloseButtonAction=
function(a){if(!1===d(a))throw Error("Close button action cannot be null.");this._closeButtonAction=a};b.prototype.getDefaultButtonAction=function(){return this.defaultButtonAction};b.prototype.getSecondaryLinkAction=function(){return this.secondaryLinkAction};b.prototype.getThirdButtonAction=function(){return this._thirdButtonAction};b.prototype.getCloseButtonAction=function(){return this._closeButtonAction};b.prototype.serialize=function(){return{description:this.getDescription(),type:this.getType(),
title:this.getTitle(),defaultButton:this.defaultButtonText,secondaryLink:this.secondaryLinkText,thirdButton:this._thirdButtonText,notificationID:this.getID(),imageUrl:this.getRelativeImageURL(),blockListedUrls:this.blockListedUrls}};b.prototype.getData=function(){return this.data};b.prototype.handleEvent=function(b){switch(b){case k.NOTIFICATION.MESSAGES.DEFAULT_BUTTON_PRESSED:b=this.getDefaultButtonAction();break;case k.NOTIFICATION.MESSAGES.SECONDARY_LINK_PRESSED:b=this.getSecondaryLinkAction();
break;case k.NOTIFICATION.MESSAGES.THIRD_BUTTON_PRESSED:b=this.getThirdButtonAction();break;case k.NOTIFICATION.MESSAGES.NOTIFICATION_CLOSED:b=a(this.getCloseButtonAction())?null:this.getCloseButtonAction();break;default:return}var d=this.getData();if(f(b))try{b(d)}catch(l){c.error(l)}};return b}(e.SymBfw)})(this);
(function(e){e.SymBfw.TimedNotification=function(b){var a=b.Notification,f=b.constants.uiConstants,d=function(b,d,e){a.call(this,b,f.NOTIFICATION.TYPE.TIMED,d,e)};d.prototype=Object.create(a.prototype);d.prototype.onDisplayed=function(){var a=this.getID();setTimeout(function(){b.notificationCenter.removeNotification(a)},f.NOTIFICATION.DEFAULT_TIMEOUT)};return d}(e.SymBfw)})(this);
(function(e){e.SymBfw.notificationCenter=function(b){var a=b.utils.isNil,f=b.logger,d=b.extensionAdapter,c=b.constants.uiConstants,e={queue:[],addNotification:function(b){if(a(b))throw Error("Notification cannot be null");var d=b.getType();switch(d){case c.NOTIFICATION.TYPE.TIMED:chrome.notifications.create({type:"basic",iconUrl:b.getImage(),title:b.getTitle(),message:b.getDescription()},function(a){b.setID(a);b.onDisplayed()});break;case c.NOTIFICATION.TYPE.QUESTION:this.queue.push(b);e.refreshQueue();
break;default:throw Error("Unsupported notification type: "+d);}},removeNotification:function(b){if(a(b))throw Error("NotificationID cannot be null");for(var c in this.queue)if(this.queue[c].getID()===b){this.queue.splice(c,1);break}try{chrome.notifications.clear(b)}catch(h){f.info(h)}finally{e.refreshQueue()}},getNotification:function(b){if(a(b))throw Error("NotificationID cannot be null");for(var c in this.queue)if(this.queue[c].getID()===b)return this.queue[c]},refreshQueue:function(){d.getActiveTab(function(b){if(!a(b)){var g=
[],f;for(f in e.queue){var k=e.queue[f].serialize();g.push(k)}d.sendMessageToTab(b,{id:c.NOTIFICATION.MESSAGES.DEFAULT_MESSAGE,payload:{eventID:c.NOTIFICATION.MESSAGES.NOTIFICATION_QUEUE_MESSAGE,notificationArray:g}},null,{frameId:0})}})},handleActivate:function(){d.getAllTabs(function(a){a.forEach(function(a){d.sendMessageToTab(a,{id:c.NOTIFICATION.MESSAGES.DEFAULT_MESSAGE,payload:{eventID:c.NOTIFICATION.MESSAGES.HIDE_NOTIFICATIONS}})});e.refreshQueue()})},handleMessage:function(b,g){if(!a(b)){var h=
b.eventID;if(!a(h)){var l=b.notificationID;switch(h){case c.NOTIFICATION.MESSAGES.DEFAULT_BUTTON_PRESSED:case c.NOTIFICATION.MESSAGES.SECONDARY_LINK_PRESSED:case c.NOTIFICATION.MESSAGES.THIRD_BUTTON_PRESSED:case c.NOTIFICATION.MESSAGES.NOTIFICATION_CLOSED:if(a(l)){f.warn("Notification ID cannot be null when eventID is "+c.NOTIFICATION.MESSAGES.DEFAULT_BUTTON_PRESSED);break}b=e.getNotification(l);if(a(b))break;b.handleEvent(h);e.removeNotification(l);break;case c.NOTIFICATION.MESSAGES.NOTIFICATION_QUEUE_MESSAGE:e.refreshQueue();
break;case c.NOTIFICATION.MESSAGES.NOTIFICATIONS_SHOWN:h=b.notificationArray;for(var k in h)if(l=h[k],b=e.getNotification(l),!a(b))b.onDisplayed();break;case c.NOTIFICATION.MESSAGES.HIDE_NOTIFICATIONS:d.sendMessageToTab(g,{id:c.NOTIFICATION.MESSAGES.DEFAULT_MESSAGE,payload:{eventID:c.NOTIFICATION.MESSAGES.HIDE_NOTIFICATIONS}})}}}},getSerializedNotifications:function(){var a=[],b;for(b in e.queue)a.push(e.queue[b]);return a},init:function(){var f=function(){e.handleActivate()};d.addWindowFocusedEventListener(f);
d.addTabActivatedEventListener(f);d.addMessageListener(function(d,f,l){if(!a(d)&&!a(d.id))switch(d.id){case c.NOTIFICATION.MESSAGES.UI_INIT:return d.id=c.NOTIFICATION.MESSAGES.UI_INIT_PROXY,b.extensionAdapter.sendMessageToTab(l,d,function(a){f(a)}),!0;case c.NOTIFICATION.MESSAGES.DEFAULT_MESSAGE:return e.handleMessage(d.payload,l)}})}};e.init();return e}(e.SymBfw)})(this);
(function(e){e.SymBfw.performanceReporterFactory=function(b){var a=b.utils.isNil,f=b.utils.isntNil,d=b.extensionAdapter,c=b.constants.performanceReporter.MESSAGES,e={_reporters:{},AUTOMATION_MODE:!1},k=function(b){if(a(b))throw Error("component cannot be null");this.component=b;this.start=Date.now();this.subComponents={};this.tldReports={}};k.prototype._reportStart=function(a){if(f(this.subComponents[a]))throw Error("type already exists");this.subComponents[a]={};this.subComponents[a].start=Date.now()};
k.prototype._reportEnd=function(b){if(a(this.subComponents[b]))throw Error("type does NOT exists");if(f(this.subComponents[b].stop))console.warn("already reported this type");else{var c=Date.now(),d=this.subComponents[b].start;this.subComponents[b].stop=c;this.subComponents[b].timeTaken=c-d}};k.prototype._reportStartFromProxy=function(b,c,d,e){if(a(b))throw Error("type cannot be null");if(a(c))throw Error("domain cannot be null");if(a(d))throw Error("frameURL cannot be null");if(a(e))throw Error("frameGUID cannot be null");
c=this.tldReports[c][e].subComponents;if(f(c[b]))throw Error("Sub-component Type already started");c[b]={};c[b].start=Date.now()};k.prototype._reportEndFromProxy=function(b,c,d,e){if(a(b))throw Error("type cannot be null");if(a(c))throw Error("domain cannot be null");if(a(d))throw Error("frameURL cannot be null");if(a(e))throw Error("frameGUID cannot be null");if(a(this.tldReports[c]))throw Error("Component for TLD not properly initialized");if(a(this.tldReports[c][e]))throw Error("Component for TLD - frameGUID, not properly initialized");
c=this.tldReports[c][e].subComponents;if(a(c[b].start))throw Error("type did not start");f(c[b].stop)?console.warn("Sub-component Type already ended"):(c[b].stop=Date.now(),c[b].timeTaken=c[b].stop-c[b].start)};k.prototype._createOrGetTLDDict=function(b,c,d){if(a(b))throw Error("domain cannot be NULL");if(a(c))throw Error("frameURL cannot be NULL");if(a(d))throw Error("frameGUID cannot be NULL");a(this.tldReports[b])&&(this.tldReports[b]={});a(this.tldReports[b][d])&&(this.tldReports[b][d]={},this.tldReports[b][d].start=
Date.now(),this.tldReports[b][d].frameURL=c,this.tldReports[b][d].subComponents={})};k.prototype.serialize=function(){var a={};a[this.component]={};a[this.component].start=this.start;a[this.component].stop=Date.now();a[this.component].timeTaken=a[this.component].stop-this.start;a[this.component].subComponents=this.subComponents;for(var b in this.tldReports)a[this.component][b]=this.tldReports[b];return a};e.serialize=function(){var a=[],b;for(b in this._reporters){var c=this._reporters[b].serialize();
a.push(c)}return a};e._getPerformanceReporter=function(a){var b=e._reporters[a];if(f(b))return b;b=new k(a);return e._reporters[a]=b};e.reportStartForComponent=function(b,c){if(!1!==e.AUTOMATION_MODE){if(a(b))throw Error("component cannot be NULL");if(a(c))throw Error("type cannot be NULL");e._getPerformanceReporter(b)._reportStart(c)}};e.reportStopForComponent=function(b,c){if(!1!==e.AUTOMATION_MODE){if(a(b))throw Error("component cannot be NULL");if(a(c))throw Error("type cannot be NULL");e._getPerformanceReporter(b)._reportEnd(c)}};
e._getPerformanceReporterFromProxy=function(b,c,d,f){if(a(d))throw Error("domain cannot be null");if(a(f))throw Error("frameURL cannot be null");if(a(c))throw Error("frameGUID cannot be null");b=e._getPerformanceReporter(b);b._createOrGetTLDDict(d,f,c);return b};e.handleMessage=function(b,d,f){if(!1!==e.AUTOMATION_MODE&&!a(b))switch(d=b.payload,b.id){case c.REPORT_START:var g=d.component;b=d.guid;var h=d.frameURL;g=e._getPerformanceReporterFromProxy(g,b,f.url,h);d=d.type;g._reportStartFromProxy(d,
f.url,h,b);break;case c.REPORT_END:g=d.component,b=d.guid,h=d.frameURL,g=e._getPerformanceReporter(g),d=d.type,g._reportEndFromProxy(d,f.url,h,b)}};d.addMessageListener(e.handleMessage);e.PerformanceReporter=k;return e}(e.SymBfw)})(this);
(function(e){e.SymBfw.certHandler=function(b){var a={},e=b.constants;a.validateCertAndGetPublicKey=function(b,c,e){try{var d=forge.pki.certificateFromPem(b);return!forge.pki.certificateFromPem(c).verify(d)||a._isCertExpired(d.validity.notAfter)?null:a._verifyCertInfo(d,e)?forge.pki.publicKeyToPem(d.publicKey):null}catch(g){return null}};a._verifyCertInfo=function(a,b){var c=a.issuer.getField(e.CERT_COMMON_NAME).value===b.CERT_ISSUER_NAME;a=a.subject.getField(e.CERT_COMMON_NAME).value===b.CERT_ISSUED;
return c&&a};a._isCertExpired=function(a){a=a.getTime();var b=(new Date).getTime();return a>b?!1:!0};return a}(e.SymBfw)})(this);
(function(e){e.SymBfw.cdnFileDownloader=function(b){var a={},e=b.constants,d=b.utils,c=b.certHandler,m=e.CDN_FILE_DOWNLOADER;a._downloadAndValidateCdnFile=function(a,b,f){return d.safeFetch(a).then(function(a){if(d.isSuccessCodeLocalFile(a.status))return a.json();throw m.RESPONSE_STATUS.UNSUCCESSFUL_RESPONSE+" "+a.status;}).then(function(a){var g=void 0===a.payload?{}:a.payload,h=void 0===a.JWT?"":a.JWT;a=c.validateCertAndGetPublicKey(void 0===a.CERT?"":a.CERT,b,f);if(d.isNil(a))throw m.RESPONSE_STATUS.PUBLIC_KEY_NOT_VERIFIED;
if(!d.verifyJson(g,h,a,[e.CDN_FILE_DOWNLOADER.ENCRYPTION_METHOD]))throw m.RESPONSE_STATUS.FILE_TAMPERED;return g}).catch(function(a){throw a;})};a.getPayloadFromCdnFile=function(a,b,c){return this._isValidUrl(a)&&!d.isNil(b)&&this._isValidCertInfo(c)?this._downloadAndValidateCdnFile(a,b,c).then(function(a){return a}).catch(function(a){throw a;}):Promise.reject(m.RESPONSE_STATUS.INVALID_PARAMETERS)};a._isValidCertInfo=function(a){if(d.isEmptyObject(a))return!1;var b=a.hasOwnProperty(m.CERT_ISSUER_NAME);
a=a.hasOwnProperty(m.CERT_ISSUED);return b&&a};a._isValidUrl=function(a){if(!d.isString(a))return!1;var b=d.urlProtocol(a);a=d.getFileNameExtension(a);return m.SUPPORTED_PROTOCOL===b&&m.SUPPORTED_FILEFORMATS.includes(a)};return a}(e.SymBfw)})(this);
