var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(c){var a=0;return function(){return a<c.length?{done:!1,value:c[a++]}:{done:!0}}};$jscomp.arrayIterator=function(c){return{next:$jscomp.arrayIteratorImpl(c)}};$jscomp.makeIterator=function(c){var a="undefined"!=typeof Symbol&&Symbol.iterator&&c[Symbol.iterator];return a?a.call(c):$jscomp.arrayIterator(c)};
$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,a,f){c!=Array.prototype&&c!=Object.prototype&&(c[a]=f.value)};
$jscomp.polyfill=function(c,a,f,b){if(a){f=$jscomp.global;c=c.split(".");for(b=0;b<c.length-1;b++){var d=c[b];d in f||(f[d]={});f=f[d]}c=c[c.length-1];b=f[c];a=a(b);a!=b&&null!=a&&$jscomp.defineProperty(f,c,{configurable:!0,writable:!0,value:a})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(c){function a(){this.batch_=null}function f(b){return b instanceof d?b:new d(function(a,d){a(b)})}if(c&&!$jscomp.FORCE_POLYFILL_PROMISE)return c;a.prototype.asyncExecute=function(b){if(null==this.batch_){this.batch_=[];var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})}this.batch_.push(b)};var b=$jscomp.global.setTimeout;a.prototype.asyncExecuteFunction=function(a){b(a,0)};a.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var b=
this.batch_;this.batch_=[];for(var a=0;a<b.length;++a){var d=b[a];b[a]=null;try{d()}catch(u){this.asyncThrow_(u)}}}this.batch_=null};a.prototype.asyncThrow_=function(b){this.asyncExecuteFunction(function(){throw b;})};var d=function(b){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var a=this.createResolveAndReject_();try{b(a.resolve,a.reject)}catch(p){a.reject(p)}};d.prototype.createResolveAndReject_=function(){function b(b){return function(e){d||(d=!0,b.call(a,e))}}var a=this,d=!1;
return{resolve:b(this.resolveTo_),reject:b(this.reject_)}};d.prototype.resolveTo_=function(b){if(b===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof d)this.settleSameAsPromise_(b);else{a:switch(typeof b){case "object":var a=null!=b;break a;case "function":a=!0;break a;default:a=!1}a?this.resolveToNonPromiseObj_(b):this.fulfill_(b)}};d.prototype.resolveToNonPromiseObj_=function(b){var a=void 0;try{a=b.then}catch(p){this.reject_(p);return}"function"==typeof a?
this.settleSameAsThenable_(a,b):this.fulfill_(b)};d.prototype.reject_=function(b){this.settle_(2,b)};d.prototype.fulfill_=function(b){this.settle_(1,b)};d.prototype.settle_=function(b,a){if(0!=this.state_)throw Error("Cannot settle("+b+", "+a+"): Promise already settled in state"+this.state_);this.state_=b;this.result_=a;this.executeOnSettledCallbacks_()};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var b=0;b<this.onSettledCallbacks_.length;++b)h.asyncExecute(this.onSettledCallbacks_[b]);
this.onSettledCallbacks_=null}};var h=new a;d.prototype.settleSameAsPromise_=function(b){var a=this.createResolveAndReject_();b.callWhenSettled_(a.resolve,a.reject)};d.prototype.settleSameAsThenable_=function(b,a){var d=this.createResolveAndReject_();try{b.call(a,d.resolve,d.reject)}catch(u){d.reject(u)}};d.prototype.then=function(b,a){function c(b,a){return"function"==typeof b?function(a){try{f(b(a))}catch(v){e(v)}}:a}var f,e,h=new d(function(b,a){f=b;e=a});this.callWhenSettled_(c(b,f),c(a,e));return h};
d.prototype.catch=function(b){return this.then(void 0,b)};d.prototype.callWhenSettled_=function(b,a){function d(){switch(c.state_){case 1:b(c.result_);break;case 2:a(c.result_);break;default:throw Error("Unexpected state: "+c.state_);}}var c=this;null==this.onSettledCallbacks_?h.asyncExecute(d):this.onSettledCallbacks_.push(d)};d.resolve=f;d.reject=function(b){return new d(function(a,d){d(b)})};d.race=function(b){return new d(function(a,d){for(var c=$jscomp.makeIterator(b),e=c.next();!e.done;e=c.next())f(e.value).callWhenSettled_(a,
d)})};d.all=function(b){var a=$jscomp.makeIterator(b),c=a.next();return c.done?f([]):new d(function(b,d){function e(a){return function(d){p[a]=d;g--;0==g&&b(p)}}var p=[],g=0;do p.push(void 0),g++,f(c.value).callWhenSettled_(e(p.length-1),d),c=a.next();while(!c.done)})};return d},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(c,a){this.$jscomp$symbol$id_=c;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:a})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function c(f){if(this instanceof c)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(f||"")+"_"+a++,f)}var a=0;return c}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.iterator;c||(c=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[c]&&$jscomp.defineProperty(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.asyncIterator;c||(c=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(c){$jscomp.initSymbolIterator();c={next:c};c[$jscomp.global.Symbol.iterator]=function(){return this};return c};
$jscomp.iteratorFromArray=function(c,a){$jscomp.initSymbolIterator();c instanceof String&&(c+="");var f=0,b={next:function(){if(f<c.length){var d=f++;return{value:a(d,c[d]),done:!1}}b.next=function(){return{done:!0,value:void 0}};return b.next()}};b[Symbol.iterator]=function(){return b};return b};$jscomp.polyfill("Array.prototype.keys",function(c){return c?c:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
(function(c){c=c.SymO2=c.SymO2||{};var a={requestType:{},header:{},contentType:{},responseType:{},domain:{},oxygen:{},session:{},spoc:{}};a.spoc.internalErrors={};a.sso={};a.sso.httpErrorResponse={};a.sso.httpErrorResponse.primaryStatus={};a.sso.httpErrorResponse.detailedStatus={};a.sso.httpErrorResponse.detailedStatus.ssoError={};a.oxygen.ETAG="ETag";a.MACHINE_GUID="machineGUID";a.OCL_CONTAINER="ocl";a.GLOBAL_CONTAINER="global";a.session.LLT="llt";a.session.EMAIL="email";a.session.NA_GUID="naguid";
a.session.USER_ID="userid";a.session.FIRST_NAME="firstname";a.session.LAST_NAME="lastname";a.session.ACCESS_TOKEN="accessToken";a.session.ACCESS_TOKEN_TTL="accessToken_ttl";a.session.DEFAULT_ACCESS_TOKEN_TTL=15E5;a.session.ID_TOKEN="idToken";a.session.ID_TOKEN_TTL="idToken_ttl";a.session.DEFAULT_ID_TOKEN_TTL=15E5;a.requestType.POST_METHOD="POST";a.requestType.GET_METHOD="GET";a.requestType.PUT_METHOD="PUT";a.requestType.DELETE_METHOD="DELETE";a.requestType.HEAD_METHOD="HEAD";a.header.AUTHORIZATION=
"Authorization";a.header.REQUEST_ID="X-Symc-Request-Id";a.header.BASIC_AUTHENTICATION="WWW-Authenticate";a.header.SYMC_MACHINE_ID="X-Symc-Machine-ID";a.header.CHALLENGES="X-Symc-Challenges";a.header.ORIGIN_HEADER="X-Symc-Origin";a.header.ETAG="ETag";a.header.IF_MATCH="if-match";a.header.RANGE="Range";a.header.ACCEPT="Accept";a.header.CONTENT_TYPE="Content-Type";a.header.CORS="Access-Control-Allow-Origin";a.header.USER_AGENT="X-Symc-User-Agent";a.header.SYMC_AUTH="X-Symc-Auth";a.header.SYMC_COOKIE=
"X-Symc-Cookie";a.header.CONNECTION="Connection";a.header.KEEP_ALIVE="Keep-Alive";a.header.NOT_MODIFIED="304 Not Modified";a.header.SYMC_EXPECT="X-Symc-Expect";a.header.SCHEMA_ERROR="X-Symc-SchemaErrors";a.contentType.PROTOBUF="application/x-protobuf ";a.contentType.JSON="application/json";a.contentType.FORM_URL_ENCODED="application/x-www-form-urlencoded";a.responseType.ARRAY_BUFFER="arraybuffer";a.spoc.INTERNAL_DOMAIN="internal";a.spoc.HTTP_DOMAIN="http";a.spoc.internalErrors.SUCCESS=0;a.spoc.internalErrors.STOPPED=
1;a.spoc.internalErrors.CANCELLED=2;a.spoc.internalErrors.UNRECOVERABLE=3;a.spoc.internalErrors.UNKNOWN=4;a.sso.httpErrorResponse.primaryStatus.SUCCESS="0000";a.sso.httpErrorResponse.primaryStatus.EBE_ERROR="0001";a.sso.httpErrorResponse.primaryStatus.SSO_ERROR="0002";a.sso.httpErrorResponse.detailedStatus.ssoError.TOKEN_EXPIRED="0001";a.sso.httpErrorResponse.detailedStatus.ssoError.TOKEN_INVALID="0002";a.sso.httpErrorResponse.detailedStatus.ssoError.INVALID_CLIENT_ID="0003";a.sso.httpErrorResponse.detailedStatus.ssoError.UNAUTHORIZED_SERVICE=
"0004";a.sso.httpErrorResponse.detailedStatus.ssoError.ACL_LACKS_PRIVILEGE="0005";a.sso.httpErrorResponse.detailedStatus.ssoError.RATE_LIMITED="0010";a.sso.httpErrorResponse.detailedStatus.ssoError.NULL_ACL="0020";a.sso.httpErrorResponse.detailedStatus.ssoError.NULL_CONTEXT="0021";a.sso.httpErrorResponse.detailedStatus.ssoError.CONTENT_LENGTH_MAXED="0022";a.sso.httpErrorResponse.detailedStatus.ssoError.MALFORMED_REQUEST="0023";a.sso.httpErrorResponse.detailedStatus.ssoError.INVALID_SIGNATURE="0024";
a.sso.httpErrorResponse.detailedStatus.ssoError.TIMESTAMP_EXPIRED="0025";a.sso.httpErrorResponse.detailedStatus.ssoError.TIMESTAMP_REQUIRED="0026";a.sso.httpErrorResponse.detailedStatus.ssoError.TIMESTAMP_DUPLICATE="0027";a.sso.httpErrorResponse.detailedStatus.ssoError.MACHINE_ID_REQUIRED="0028";a.sso.httpErrorResponse.detailedStatus.ssoError.AUTHORIZATION_MAXED_OUT="0029";a.sso.httpErrorResponse.detailedStatus.ssoError.INVALID_CERTIFICATE="0040";a.sso.httpErrorResponse.detailedStatus.ssoError.INVALID_DATE_HEADER=
"0041";a.sso.httpErrorResponse.detailedStatus.ssoError.INVALID_TEMPLATE_GUID="0050";a.sso.httpErrorResponse.detailedStatus.ssoError.MISSING_EMAIL_ADDRESS="0051";a.sso.httpErrorResponse.detailedStatus.ssoError.MISSING_ISSUER="0052";a.sso.httpErrorResponse.detailedStatus.ssoError.INVALID_EMAIL_LENGTH="0053";a.sso.httpErrorResponse.detailedStatus.ssoError.INVALID_EMAIL="0054";a.sso.httpErrorResponse.detailedStatus.ssoError.INVALID_PHONE_NUMBER="0055";a.sso.httpErrorResponse.detailedStatus.ssoError.USER_DOES_NOT_EXIST=
"2104";a.sso.httpErrorResponse.detailedStatus.ssoError.INVALID_ACCOUNT_LOGIN="2106";a.domain.COOKIES="com.symantec.cookies";a.DEFAULT_XHR_TIMEOUT=6E4;a.openIDConnect={ALG:"RS256"};c.constants=a})(this);
(function(c){(c.SymO2=c.SymO2||{}).utils=function(a,c){var b={},d=a.utils.isNil,f=a.logger,k=a.utils.isString,r=a.utils.isArray;b.arrayBufferToStringUTF16LE=function(a){if(d(a))return null;a instanceof ArrayBuffer&&(a=new Uint8Array(a));for(var c=[],e=0;e<a.byteLength;e++)c.push(a[e]);return b.byteArrayToStringUTF16LE(c)};b.stringUTF16LEToByteArray=function(b){if(!1===k(b))throw Error("Input string cannot be null or is not a string");for(var a=[],d=0;d<b.length;++d){var c=b.charCodeAt(d),f=(c&65280)>>
8;a.push(c&255);a.push(f)}return a};b.byteArrayToStringUTF16LE=function(b){if(!1===r(b))throw Error("Byte array cannot be null or is not an array");if(2>b.length)throw Error("Byte array needs to contain at least two bytes");if(0!==b.length%2)throw Error("Byte array needs to contain even number of bytes");for(var a="",d=0;d<b.length-1;d+=2){var c=b[d];if(255<c)throw Error("Encoding error: Input contains element larger than a byte.");c&=255;var f=b[d+1];if(255<f)throw Error("Encoding error: Input contains element larger than a byte.");
f=f<<8&65280;a+=String.fromCharCode(c+f)}return a};b.createUInt8BufferFromStringBuffer=function(b,a){if(d(b))return null;d(a)&&(a=b.length);a<b.length&&(a=b.length);a=new Uint8Array(a);for(var c=0,f=b.length;c<f;c++){var p=b.charCodeAt(c);if(255<p)throw Error("Encoding error: Input contains element larger than a byte.");a[c]=p}return a};b.createStringBufferFromUint8Buffer=function(b){return d(b)?null:String.fromCharCode.apply(null,new Uint8Array(b))};b.encode64AndPrint=function(a,c){var e=null;d(a)||
("string"===typeof a&&(e=a),a instanceof Uint8Array&&(e=b.createStringBufferFromUint8Buffer(a)),a=forge.util.encode64(e),f.log(c+":"+a))};b.challengeListToString=function(a){if(d(a))return null;a=b.createStringBufferFromUint8Buffer(a.toArrayBuffer());a=forge.util.encode64(a);return encodeURIComponent(a)};b.stringToChallengeList=function(a){if(d(a))return null;var h=c.proto.com.symantec.oxygen.datastore.v2.messages.ChallengeList,e=null;a=decodeURIComponent(a);a=forge.util.decode64(a);a=b.createUInt8BufferFromStringBuffer(a);
try{e=h.decode(a)}catch(l){f.error(l)}return e};b.protobufToEncodedString=function(a){if(d(a))return null;var c=null;try{var e=b.createStringBufferFromUint8Buffer(a.toArrayBuffer());c=forge.util.encode64(e)}catch(l){c=null}return c};b.encodedStringToProtobuf=function(a,c){if(d(a)||d(c))return null;var e=null;try{var h=b.createUInt8BufferFromStringBuffer(forge.util.decode64(a));e=c.decode(h)}catch(t){f.error(t),e=null}return e};return b}(c.SymBfw,c.SymO2)})(this);
(function(c){c.SymO2.telemetryWrapper=function(a,c){var b=a.utils.isString,d=a.utils.isInteger,f=a.telemetryConstants,k={TELEMETRY_CATEGORY:"OCL",NON_INTERACTION:1,actionType:{SESSION:"Session",SSO:"SSO",OXYGEN:"Oxygen",OXYGEN_SCHEMA:"Oxygen-Schema",SPOC:"Spoc"},O2_SESSION:{LOGIN:"login",LOGOUT:"logout"},send:function(c,h,u){if(!b(c))throw Error("action should be a string");if(!b(h))throw Error("label should be a string");if(!d(u)||0>u)throw Error("value should be a non-negative integer");var e={};
e[f.parameters.NON_INTERACTION_HIT]=k.NON_INTERACTION;e[f.parameters.HIT_TYPE]=f.HIT_TYPE.EVENT;e[f.parameters.CATEGORY]=k.TELEMETRY_CATEGORY;e[f.parameters.ACTION]=c+"-"+u;e[f.parameters.LABEL]=h;a.telemetry.send(e)},sendSessionLoginErrorCode:function(b){k.send(k.actionType.SESSION,k.O2_SESSION.LOGIN,b)},sendSessionLogoutCode:function(b){k.send(k.actionType.SESSION,k.O2_SESSION.LOGOUT,b)},sendSSOErrorCodeWithFullUrl:function(b,a){k.send(k.actionType.SSO,a,b)},sendOxygenErrorCodeWithFullUrl:function(b,
a){k.send(k.actionType.OXYGEN,a,b)},sendSpocErrorCodeWithFullUrl:function(b,a){k.send(k.actionType.SPOC,a,b)},sendOxygenDataStoreSchemaError:function(b,a){k.send(k.actionType.OXYGEN_SCHEMA,a,b)}};return k}(c.SymBfw,c.SymO2)})(this);
(function(c){(c.SymO2=c.SymO2||{}).authSCD=function(a,c){var b={},d=a.utils.isNil;b.SSO_LOGOUT_URL="https://login.norton.com/sso/logout";b.SSO_LOGIN_URL="https://login.norton.com/sso/idp";b.SSO_OPEN_ID_URL="https://login.norton.com/sso/idp/OPENID";b.SSO_OPENID_CONNECT_LOGIN_URL="https://login.norton.com/sso/idp/OIDC";b.SSO_OPENID_CONNECT_TOKEN_URL="https://login.norton.com/sso/oidc1/tokens";b.SSO_OPENID_CONNECT_DISCOVER_URL="https://login.norton.com/sso/oidc1/token/jwks";b.IDSAFE_PORTAL_URL="https://identitysafe.norton.com";
b.O2_URL="https://o2.norton.com/api/1";b.DS_URL="https://o2-ds.norton.com/api/datastore/v2";b.SPOC_URL="https://spoc-pool-gtm.norton.com";b.USER_AGENT="XBP/5.3.22/Chrome//Oxygen";b.SPOC_USER_AGENT="XBP/OCL";b.SPOC_DEFAULT_TIMEOUT=3600;b.SPOC_RETRY_COUNT=5;b.RETRY_TIMEOUT=3600;b.DEFAULT_TTL=1814400;b.DEFAULT_ACL_TTL=15552E3;b.setMachineGUID=function(b){d(b)||(this.machineGUID=b)};b.getMachineGUID=function(){if(d(this.machineGUID))throw Error("machineGUID is not set. SymO2.ready is not called");return this.machineGUID};
b.serialize=function(){return{sso:b.SSO_URL,portal_interstitial_url:b.IDSAFE_PORTAL_URL,o2:b.O2_URL,"o2-ds":b.DS_URL,spoc:b.SPOC_URL,machineGUID:b.getMachineGUID(),userAgent:b.USER_AGENT,spocUserAgent:b.SPOC_USER_AGENT,ssoOpenIDConnectLoginURL:b.SSO_OPENID_CONNECT_LOGIN_URL,ssoOpenIDConnectTokenURL:b.SSO_OPENID_CONNECT_TOKEN_URL}};return b}(c.SymBfw,c.SymO2)})(this);
(function(c){c=c.SymO2=c.SymO2||{};var a=dcodeIO.ProtoBuf.newBuilder({})["import"]({"package":null,messages:[{name:"com",fields:[],messages:[{name:"symantec",fields:[],messages:[{name:"oxygen",fields:[],messages:[{name:"datastore",fields:[],messages:[{name:"db",fields:[],messages:[{name:"messages",fields:[],options:{optimize_for:"SPEED"},messages:[{name:"DatastoreV1CallbackMessage",fields:[{rule:"optional",type:"string",name:"callbackUrl",id:1},{rule:"optional",type:"string",name:"mimeType",id:2},
{rule:"optional",type:"string",name:"rulePattern",id:3},{rule:"optional",type:"string",name:"userId",id:4},{rule:"optional",type:"QueueMessageDSv1Operation",name:"dsOperation",id:5},{rule:"optional",type:"uint32",name:"appId",id:6},{rule:"optional",type:"bytes",name:"dsRequest",id:7},{rule:"optional",type:"string",name:"node_path",id:8}]}],enums:[{name:"QueueMessageDSv1Operation",values:[{name:"OP_CREATE",id:1},{name:"OP_UPDATE",id:2},{name:"OP_DELETE",id:3}]}]}]},{name:"v2",fields:[],messages:[{name:"messages",
fields:[],options:{java_package:"com.symantec.oxygen.datastore.v2.messages",optimize_for:"SPEED"},messages:[{name:"Value",fields:[{rule:"required",type:"string",name:"name",id:1},{rule:"required",type:"DataTypeID",name:"type",id:2},{rule:"optional",type:"uint32",name:"data_bool",id:3},{rule:"optional",type:"string",name:"data_string",id:4},{rule:"optional",type:"uint32",name:"data_uint32",id:5},{rule:"optional",type:"uint64",name:"data_uint64",id:6},{rule:"optional",type:"uint64",name:"data_timestamp",
id:7},{rule:"optional",type:"bytes",name:"data_binary",id:8},{rule:"optional",type:"string",name:"data_stream",id:9},{rule:"repeated",type:"SetValue",name:"data_set",id:10},{rule:"optional",type:"bool",name:"overwrite",id:11}],enums:[{name:"DataTypeID",values:[{name:"TID_NIL",id:0},{name:"TID_BOOL",id:1},{name:"TID_STRING",id:2},{name:"TID_UINT32",id:3},{name:"TID_UINT64",id:4},{name:"TID_TIMESTAMP",id:5},{name:"TID_BINARY",id:6},{name:"TID_SET",id:7}]}]},{name:"SetValue",fields:[{rule:"required",
type:"SetValueDataTypeID",name:"type",id:1},{rule:"optional",type:"string",name:"data_string",id:2},{rule:"optional",type:"uint32",name:"data_uint32",id:3},{rule:"optional",type:"uint64",name:"data_uint64",id:4},{rule:"optional",type:"bytes",name:"data_binary",id:5},{rule:"optional",type:"uint64",name:"modified_time",id:6}],enums:[{name:"SetValueDataTypeID",values:[{name:"TID_STRING",id:0},{name:"TID_UINT32",id:1},{name:"TID_UINT64",id:2},{name:"TID_BINARY",id:3}]}]},{name:"Node",fields:[{rule:"required",
type:"string",name:"path",id:1},{rule:"optional",type:"bool",name:"deleted",id:2},{rule:"repeated",type:"Value",name:"values",id:3},{rule:"optional",type:"uint64",name:"node_modified",id:5},{rule:"repeated",type:"ChildNodeMeta",name:"child_nodes",id:6}]},{name:"ChildNodeMeta",fields:[{rule:"required",type:"string",name:"node_name",id:1},{rule:"required",type:"string",name:"node_url",id:2}]},{name:"NodeList",fields:[{rule:"optional",type:"string",name:"entity_id",id:1},{rule:"repeated",type:"Node",
name:"nodes",id:2}]},{name:"MultiEntityNodeList",fields:[{rule:"repeated",type:"NodeList",name:"nodeLists",id:1}]},{name:"DatastoreRangeQuery",fields:[{rule:"optional",type:"string",name:"from_revision",id:1},{rule:"repeated",type:"string",name:"to_revision",id:2}]},{name:"ErrorResultList",fields:[{rule:"repeated",type:"ErrorResult",name:"entityError",id:1}]},{name:"ErrorResult",fields:[{rule:"optional",type:"string",name:"entity_id",id:1},{rule:"optional",type:"uint32",name:"status_code",id:2}]},
{name:"Challenge",fields:[{rule:"required",type:"string",name:"entity_id",id:1},{rule:"required",type:"uint32",name:"app_id",id:2},{rule:"required",type:"uint64",name:"session_id",id:3},{rule:"optional",type:"bytes",name:"salt",id:4},{rule:"optional",type:"bytes",name:"client_data",id:5},{rule:"optional",type:"bytes",name:"decrypted_challenge",id:6},{rule:"optional",type:"bytes",name:"privateKey",id:7},{rule:"optional",type:"bytes",name:"publicKey",id:8}]},{name:"ChallengeList",fields:[{rule:"repeated",
type:"Challenge",name:"challenges",id:1}]},{name:"DataStoreSpocPayloadV2",fields:[{rule:"optional",type:"string",name:"origin",id:1},{rule:"repeated",type:"string",name:"to_revision",id:2},{rule:"repeated",type:"uint32",name:"app_id",id:3}]},{name:"DsCallbackRequestV2",fields:[{rule:"repeated",type:"NodeChange",name:"changed_nodes",id:1},{rule:"optional",type:"string",name:"entity_id",id:2},{rule:"optional",type:"string",name:"source_user_agent",id:3},{rule:"optional",type:"string",name:"request_id",
id:4}]},{name:"NodeChange",fields:[{rule:"required",type:"string",name:"path",id:1},{rule:"repeated",type:"Value",name:"values",id:2},{rule:"required",type:"DsOperation",name:"ds_operation",id:3},{rule:"optional",type:"string",name:"callbackUrl",id:4},{rule:"optional",type:"string",name:"mimeType",id:5},{rule:"optional",type:"string",name:"rulePattern",id:6}]},{name:"InvalidNode",fields:[{rule:"required",type:"string",name:"path",id:1},{rule:"required",type:"uint32",name:"reason",id:3}]},{name:"InvalidNodeList",
fields:[{rule:"optional",type:"string",name:"entity_id",id:1},{rule:"repeated",type:"InvalidNode",name:"nodes",id:2}]},{name:"InvalidMultiEntityNodeList",fields:[{rule:"repeated",type:"InvalidNodeList",name:"nodeLists",id:1}]}],enums:[{name:"DsOperation",values:[{name:"OP_READ",id:1},{name:"OP_WRITE",id:2},{name:"OP_DELETE",id:3}]}]}]}]},{name:"rest",fields:[],messages:[{name:"error",fields:[],messages:[{name:"messages",fields:[],options:{optimize_for:"SPEED"},messages:[{name:"Error",fields:[{rule:"required",
type:"string",name:"error_type",id:1},{rule:"required",type:"Code",name:"error_code",id:2},{rule:"optional",type:"string",name:"error_desc",id:3}],enums:[{name:"Code",values:[{name:"AUTH_INVALID_TOKEN",id:1},{name:"AUTH_BAD_CREDENTIALS",id:2},{name:"AUTH_GENERIC_ERROR",id:3}]}]}]}]},{name:"accounts",fields:[],messages:[{name:"messages",fields:[],options:{java_package:"com.symantec.oxygen.rest.accounts.messages",optimize_for:"SPEED"},messages:[{name:"id",fields:[{rule:"optional",type:"string",name:"OXYGEN_ACL_GUID",
id:1,options:{"default":"F8852F19-F8C5-46a1-99C3-4209748693F3"}},{rule:"optional",type:"string",name:"OXYGEN_SERVICE_ID",id:2,options:{"default":"o2api.norton.com"}},{rule:"optional",type:"int32",name:"ACL_FULL_ACCESS",id:3,options:{"default":-1}}]},{name:"AclGuidV2",fields:[{rule:"optional",type:"string",name:"ACL_GUID_REGISTER_MACHINE",id:1,options:{"default":"0D8F0C65-5BAA-4bb9-834C-808A8CC3325D"}},{rule:"optional",type:"string",name:"ACL_GUID_DATASTORE_READ",id:2,options:{"default":"4B05419E-9878-464e-B55D-F208B07F6AA7"}},
{rule:"optional",type:"string",name:"ACL_GUID_DATASTORE_WRITE",id:3,options:{"default":"5C40FD9F-3373-4a1b-BEAB-DA9E409A7B62"}},{rule:"optional",type:"string",name:"ACL_GUID_MACHINE_OWNER_INFO",id:4,options:{"default":"44396799-3A63-4385-8E0F-648723094FE3"}},{rule:"optional",type:"string",name:"ACL_GUID_FULL_ACCESS",id:5,options:{"default":"42305456-406C-4D7C-8DB8-942D7B48993A"}}]},{name:"Group",fields:[{rule:"optional",type:"string",name:"href",id:1},{rule:"optional",type:"uint64",name:"id",id:2},
{rule:"optional",type:"string",name:"name",id:3},{rule:"repeated",type:"GroupOwner",name:"owners",id:4},{rule:"repeated",type:"GroupMember",name:"members",id:5}]},{name:"GroupOwner",fields:[{rule:"required",type:"User",name:"owner",id:1},{rule:"optional",type:"Acl",name:"groupAcl",id:2}]},{name:"GroupMember",fields:[{rule:"required",type:"User",name:"member",id:1},{rule:"optional",type:"bool",name:"create_if_not_exist",id:3}]},{name:"User",fields:[{rule:"optional",type:"string",name:"href",id:1},
{rule:"optional",type:"uint64",name:"id",id:2},{rule:"optional",type:"string",name:"username",id:3},{rule:"optional",type:"string",name:"password",id:4},{rule:"optional",type:"string",name:"display_name",id:5},{rule:"optional",type:"string",name:"avatar",id:6},{rule:"optional",type:"string",name:"country",id:7},{rule:"optional",type:"string",name:"language",id:8},{rule:"optional",type:"bool",name:"email_security_alerts",id:9},{rule:"optional",type:"bool",name:"email_product_updates",id:10},{rule:"optional",
type:"string",name:"norton_account_guid",id:13},{rule:"optional",type:"string",name:"firstname",id:14,options:{"default":""}},{rule:"optional",type:"string",name:"lastname",id:15,options:{"default":""}},{rule:"optional",type:"MachineListV2",name:"machines",id:16},{rule:"repeated",type:"Group",name:"groups",id:17},{rule:"optional",type:"string",name:"ebe_language",id:18},{rule:"optional",type:"string",name:"birthday",id:19},{rule:"optional",type:"Gender",name:"gender",id:20},{rule:"optional",type:"uint64",
name:"oxygen_id",id:21},{rule:"optional",type:"uint64",name:"legacy_id",id:22}],enums:[{name:"MaxValues",values:[{name:"USERNAME_LENGTH",id:256},{name:"PASSWORD_LENGTH",id:128}]},{name:"Gender",values:[{name:"M",id:0},{name:"F",id:1}]}]},{name:"UserList",fields:[{rule:"repeated",type:"User",name:"owners",id:1},{rule:"repeated",type:"User",name:"members",id:2}]},{name:"EncryptionKey",fields:[{rule:"required",type:"bytes",name:"client_key",id:1},{rule:"required",type:"uint64",name:"entity_id",id:2}],
enums:[{name:"MaxValues",values:[{name:"CLIENTKEY_LENGTH",id:32}]}]},{name:"MachineUserAccount",fields:[{rule:"required",type:"string",name:"name",id:1},{rule:"optional",type:"string",name:"id",id:2},{rule:"optional",type:"string",name:"comment",id:3}],enums:[{name:"MaxValues",values:[{name:"USER_NAME_LENGTH",id:128},{name:"USER_ID_LENGTH",id:100},{name:"COMMENT_LENGTH",id:255}]}]},{name:"MachineTypeConst",fields:[{rule:"optional",type:"string",name:"Desktop",id:1,options:{"default":"Desktop"}},{rule:"optional",
type:"string",name:"Laptop",id:2,options:{"default":"Laptop"}},{rule:"optional",type:"string",name:"Netbook",id:3,options:{"default":"Netbook"}},{rule:"optional",type:"string",name:"Tablet",id:4,options:{"default":"Tablet"}},{rule:"optional",type:"string",name:"Phone",id:5,options:{"default":"Phone"}}]},{name:"Machine",fields:[{rule:"optional",type:"string",name:"href",id:1},{rule:"optional",type:"uint64",name:"id",id:2,options:{"default":0}},{rule:"optional",type:"string",name:"name",id:3},{rule:"optional",
type:"string",name:"os_name",id:4,options:{"default":"unknown"}},{rule:"optional",type:"string",name:"os_version",id:5,options:{"default":"unknown"}},{rule:"optional",type:"string",name:"machine_type",id:6,options:{"default":"unknown"}},{rule:"repeated",type:"MachineUserAccount",name:"users",id:7},{rule:"optional",type:"string",name:"heartbeat_guid",id:8},{rule:"optional",type:"string",name:"license_key",id:9},{rule:"optional",type:"bytes",name:"machine_key",id:10},{rule:"optional",type:"string",
name:"machine_guid",id:11},{rule:"optional",type:"string",name:"silo_guid",id:12},{rule:"optional",type:"string",name:"silo_version",id:13},{rule:"optional",type:"string",name:"silo_internal_key",id:14}],enums:[{name:"MaxValues",values:[{name:"MACHINE_NAME_LENGTH",id:200},{name:"OS_NAME_LENGTH",id:50},{name:"OS_VERSION_LENGTH",id:45}],options:{allow_alias:!0}}]},{name:"MachineInfo",fields:[{rule:"optional",type:"uint64",name:"id",id:1,options:{"default":0}},{rule:"optional",type:"string",name:"name",
id:2},{rule:"optional",type:"string",name:"os_name",id:3,options:{"default":"unknown"}},{rule:"optional",type:"string",name:"os_version",id:4,options:{"default":"unknown"}},{rule:"optional",type:"string",name:"machine_type",id:5,options:{"default":"unknown"}},{rule:"repeated",type:"MachineUserAccount",name:"users",id:6},{rule:"optional",type:"string",name:"machine_guid",id:7},{rule:"optional",type:"string",name:"claim_key",id:8},{rule:"optional",type:"uint64",name:"creation_time",id:9}],enums:[{name:"MaxValues",
values:[{name:"MACHINE_NAME_LENGTH",id:50},{name:"OS_NAME_LENGTH",id:50},{name:"OS_VERSION_LENGTH",id:50}],options:{allow_alias:!0}}]},{name:"Notification",fields:[{rule:"optional",type:"uint64",name:"id",id:1},{rule:"optional",type:"string",name:"uri",id:2},{rule:"optional",type:"uint64",name:"ttl",id:3},{rule:"optional",type:"string",name:"application",id:4},{rule:"optional",type:"string",name:"device_type",id:5},{rule:"optional",type:"uint64",name:"user",id:6},{rule:"optional",type:"string",name:"machine",
id:7},{rule:"optional",type:"uint64",name:"flags",id:8},{rule:"optional",type:"string",name:"language",id:9},{rule:"optional",type:"uint64",name:"creation_time",id:10}]},{name:"NotificationList",fields:[{rule:"repeated",type:"Notification",name:"notifications",id:1}]},{name:"GroupInviteToken",fields:[{rule:"optional",type:"uint64",name:"id",id:1},{rule:"optional",type:"string",name:"token_guid",id:2},{rule:"optional",type:"uint64",name:"group_id",id:3},{rule:"optional",type:"uint64",name:"application_id",
id:4},{rule:"optional",type:"string",name:"email",id:5},{rule:"optional",type:"uint64",name:"creation_time",id:6}]},{name:"SiloInfo",fields:[{rule:"optional",type:"uint64",name:"id",id:1},{rule:"optional",type:"string",name:"guid",id:2},{rule:"optional",type:"string",name:"version",id:3},{rule:"optional",type:"string",name:"name",id:4},{rule:"optional",type:"bytes",name:"silo_key",id:5},{rule:"optional",type:"uint64",name:"creation_time",id:6}]},{name:"MachineV2",fields:[{rule:"required",type:"MachineInfo",
name:"machine_info",id:1},{rule:"repeated",type:"SiloInfo",name:"silo_infos",id:2},{rule:"optional",type:"string",name:"href",id:3}]},{name:"Silo",fields:[{rule:"required",type:"MachineInfo",name:"machine_info",id:1},{rule:"required",type:"SiloInfo",name:"silo_Info",id:2}]},{name:"MachineList",fields:[{rule:"repeated",type:"Machine",name:"machines",id:1}]},{name:"MachineListV2",fields:[{rule:"repeated",type:"MachineV2",name:"machines",id:1}]},{name:"MachineComponent",fields:[{rule:"required",type:"uint32",
name:"app_id",id:1},{rule:"required",type:"string",name:"version",id:2}]},{name:"MachineInventory",fields:[{rule:"repeated",type:"MachineComponent",name:"components",id:1}]},{name:"AccountStatus",fields:[{rule:"required",type:"UserAccountStatus",name:"status",id:1}],enums:[{name:"UserAccountStatus",values:[{name:"UAS_NONE",id:0},{name:"UAS_NORTON_ONLY",id:1}]}]},{name:"SSOToken",fields:[{rule:"required",type:"string",name:"token",id:1}],enums:[{name:"MaxValues",values:[{name:"TOKEN_LENGTH",id:1024}]}]},
{name:"MachineOwnerInfo",fields:[{rule:"required",type:"User",name:"user",id:1},{rule:"required",type:"MachineInfo",name:"machine",id:2}]},{name:"SessionTokenHeader",fields:[{rule:"required",type:"uint32",name:"version",id:1},{rule:"required",type:"uint32",name:"key_index",id:2},{rule:"required",type:"uint32",name:"signature_index",id:3},{rule:"required",type:"bytes",name:"iv",id:4},{rule:"required",type:"bytes",name:"signature",id:5}]},{name:"SessionToken",fields:[{rule:"required",type:"SessionTokenHeader",
name:"header",id:1},{rule:"required",type:"bytes",name:"cipher_text",id:2}]},{name:"ExtendedSessionAccess",fields:[{rule:"optional",type:"int32",name:"app_id",id:1},{rule:"optional",type:"uint64",name:"ttlDataStoreRead",id:2},{rule:"optional",type:"uint64",name:"ttlDataStoreWrite",id:3},{rule:"optional",type:"uint64",name:"ttlRegisterMachine",id:4},{rule:"repeated",type:"int32",name:"app_list",id:5}]},{name:"Acl",fields:[{rule:"required",type:"uint64",name:"principal",id:1},{rule:"required",type:"uint64",
name:"target",id:2},{rule:"optional",type:"uint32",name:"application",id:3},{rule:"optional",type:"bytes",name:"permission",id:4},{rule:"optional",type:"EntityType",name:"principalType",id:5},{rule:"optional",type:"EntityType",name:"targetType",id:6},{rule:"repeated",type:"string",name:"accessGuids",id:7},{rule:"optional",type:"bool",name:"trusted",id:8}]},{name:"AclList",fields:[{rule:"repeated",type:"Acl",name:"acl_list",id:1}]},{name:"Delegation",fields:[{rule:"required",type:"uint64",name:"machine_id",
id:1},{rule:"repeated",type:"string",name:"permission",id:2}]},{name:"DelegationList",fields:[{rule:"repeated",type:"Delegation",name:"delegation",id:1}]},{name:"Delegator",fields:[{rule:"required",type:"User",name:"user",id:1},{rule:"optional",type:"string",name:"category",id:2},{rule:"repeated",type:"Delegation",name:"delegations",id:3}]},{name:"DelegatorList",fields:[{rule:"repeated",type:"Delegator",name:"delegators",id:1}]},{name:"Entity",fields:[{rule:"optional",type:"uint64",name:"id",id:1,
options:{"default":0}},{rule:"optional",type:"string",name:"name",id:2,options:{"default":"unknown"}},{rule:"optional",type:"string",name:"application",id:3,options:{"default":"unknown"}}],enums:[{name:"MaxValues",values:[{name:"ENTITY_NAME_LENGTH",id:50},{name:"ENTITY_APPLICATION_LENGTH",id:50}],options:{allow_alias:!0}}]},{name:"EntityList",fields:[{rule:"repeated",type:"Entity",name:"entities",id:1}]},{name:"TrustedServiceToken",fields:[{rule:"optional",type:"string",name:"token",id:1},{rule:"optional",
type:"uint32",name:"ttlInMinute",id:2}]},{name:"UserAttributes",fields:[{rule:"optional",type:"bool",name:"use_upper_machine_limit",id:1}]},{name:"SiloCache",fields:[]},{name:"MBApiRequest",fields:[{rule:"optional",type:"string",name:"request",id:1},{rule:"optional",type:"uint64",name:"id",id:2},{rule:"optional",type:"string",name:"authentication",id:3}]},{name:"ChallengeData",fields:[{rule:"required",type:"bytes",name:"privateKey",id:1},{rule:"required",type:"bytes",name:"publicKey",id:2},{rule:"required",
type:"bytes",name:"salt",id:3},{rule:"optional",type:"bool",name:"force",id:4},{rule:"optional",type:"bytes",name:"challengeData",id:5},{rule:"optional",type:"bytes",name:"challengeDecrypted",id:6},{rule:"optional",type:"uint64",name:"user_id",id:7},{rule:"optional",type:"uint64",name:"session_id",id:8}]},{name:"SymcRSCookieHeader",fields:[{rule:"required",type:"string",name:"name",id:1},{rule:"required",type:"string",name:"value",id:2},{rule:"optional",type:"string",name:"expires",id:3}]},{name:"SymcRSCookieHeaderList",
fields:[{rule:"repeated",type:"SymcRSCookieHeader",name:"cookies",id:1}]}],enums:[{name:"AclBit",values:[{name:"ACL_REGISTER_MACHINE",id:16},{name:"ACL_DATASTORE_READ",id:1},{name:"ACL_DATASTORE_WRITE",id:2},{name:"ACL_MACHINE_OWNER_INFO",id:3}]},{name:"AclPermissionBits",values:[{name:"ACCESS_ACL_WRITE",id:1},{name:"ACCESS_READ",id:2},{name:"ACCESS_WRITE",id:4}]},{name:"EntityType",values:[{name:"USER",id:0},{name:"SILO",id:1},{name:"GROUP",id:2},{name:"OXYGEN_ENTITY",id:3}]}]}]}]}]}]}]},{name:"spoc",
fields:[],options:{java_package:"com.symantec.spoc.messages",optimize_for:"SPEED"},messages:[{name:"SpocRegistrationArray",fields:[{rule:"repeated",type:"SpocRegistration",name:"registration",id:1}]},{name:"SpocRegistration",fields:[{rule:"required",type:"string",name:"entity",id:1},{rule:"required",type:"int32",name:"channel",id:2},{rule:"required",type:"int32",name:"revision",id:3},{rule:"optional",type:"bytes",name:"payload",id:4},{rule:"repeated",type:"NotificationService",name:"NotificationService",
id:5},{rule:"optional",type:"string",name:"ApplicationID",id:6}]},{name:"NotificationService",fields:[{rule:"required",type:"NotificationServiceType",name:"ServiceType",id:1},{rule:"required",type:"string",name:"RegistrationID",id:2},{rule:"optional",type:"string",name:"CertID",id:3},{rule:"optional",type:"MessagePriority",name:"Priority",id:4,options:{"default":"NORMAL"}}]},{name:"SpocBumpArray",fields:[{rule:"repeated",type:"SpocBump",name:"bump",id:1}]},{name:"SpocBump",fields:[{rule:"required",
type:"string",name:"entity",id:1},{rule:"required",type:"int32",name:"channel",id:2},{rule:"optional",type:"bytes",name:"payload",id:3},{rule:"optional",type:"string",name:"ApplicationID",id:4},{rule:"optional",type:"ServiceData",name:"serviceData",id:5}]},{name:"ServiceData",fields:[{rule:"optional",type:"string",name:"apsJson",id:1}]},{name:"SpocPollArray",fields:[{rule:"repeated",type:"SpocPoll",name:"poll",id:1}]},{name:"SpocPoll",fields:[{rule:"required",type:"string",name:"entity",id:1},{rule:"required",
type:"int32",name:"channel",id:2},{rule:"optional",type:"int32",name:"revision",id:3}]},{name:"SpocStateArray",fields:[{rule:"repeated",type:"SpocState",name:"state",id:1}]},{name:"SpocState",fields:[{rule:"required",type:"string",name:"entity",id:1},{rule:"required",type:"int32",name:"channel",id:2},{rule:"optional",type:"int64",name:"timestamp",id:3},{rule:"optional",type:"int32",name:"online",id:4},{rule:"optional",type:"int64",name:"timeout",id:5}]}],enums:[{name:"SPOCChannel",values:[{name:"SC_NOREV",
id:0},{name:"SC_STATE",id:1},{name:"SC_DATASTORE_UPDATE",id:2},{name:"SC_REGISTRATION_UPDATE",id:3},{name:"SC_DATA_REQUEST",id:4},{name:"SC_REMOTE_MANAGEMENT_REQUEST",id:5},{name:"SC_ENTITLEMENT_UPDATE",id:6},{name:"SC_EVENT_LOG_UPDATE",id:7},{name:"SC_INCENTIVES_UPDATE",id:8},{name:"SC_REGISTRATION_DELETE",id:9},{name:"SC_EVENT_LOG_LOCATION",id:10},{name:"SC_EVENT_LOG_NMS_MSWS",id:11},{name:"SC_PRODUCT_ENTITLEMENT_UPDATE",id:12},{name:"SC_SUBSCRIPTION_UPDATE",id:13},{name:"SC_NORTON_HOME_UPDATE",
id:20},{name:"SC_SE_PROXY",id:30},{name:"SC_NMS_COMMAND",id:31},{name:"SC_PDM_POLICY",id:40},{name:"SC_PDM_COMMAND",id:41},{name:"SC_DCS_COMMAND",id:50},{name:"SC_MTS_MESSAGE",id:100},{name:"SC_MAX",id:500}]},{name:"NotificationServiceType",values:[{name:"NS_GCM",id:1},{name:"NS_APNS",id:2},{name:"NS_WNS",id:3}]},{name:"MessagePriority",values:[{name:"HIGH",id:1},{name:"NORMAL",id:2}]}]}]}).build();c.proto=a})(this);
(function(c){c.SymO2.sso=function(a,c){var b={},d=a.utils.isNil,f=a.utils.isntNil,k=a.utils.isFunction,r=a.utils.isString,p=a.utils.isSuccessCode,u=a.base64,e=c.authSCD,l=c.constants,t=c.telemetryWrapper;b.getPublicKey=function(){if(d(this.publicKey))throw Error("Public Key not available. OCL was not properly initialized.");return this.publicKey};b.getPublicKeyIdentifier=function(){if(d(this.pubKeyID))throw Error("Public Key ID not available. OCL was not properly initialized.");return this.pubKeyID};
b.generateScopeParam=function(b){var a="openid",c;for(c in b)a+="+",a+=b[c];return a};b.getOpenIDConnectLoginURL=function(a){if(d(a))throw Error("State cannot be null.");var g=c.session,f=e.SSO_OPENID_CONNECT_LOGIN_URL,q=[];q.push("response_type=code");var n=b.generateScopeParam(g.getScopes());q.push("scope="+n);q.push("client_id="+encodeURIComponent(g.getClientID()));q.push("state="+encodeURIComponent(a));q.push("redirect_uri="+encodeURIComponent(g.getReturnURL()));return f+"?"+q.join("&")};b.parseAuthCodeAndGetTokens=
function(b,a){if(d(b))throw Error("Params cannot be null");if(!1===k(a))throw Error("Callback cannot be null");var e=null,g;for(g in b){var f=b[g].split("=");switch(f[0]){case "code":e=f[1]}}d(e)?setTimeout(function(){a(null,"Invalid Parameters")},1):c.sso.getTokensFromAuthorizationCode(e,a)};b.generateToken=function(a,w){if(d(a))throw Error("Params cannot be null");if(d(w))throw Error("Callback cannot be null");var g=c.session,q=b.generateScopeParam(g.getScopes());a.push("redirect_uri="+encodeURIComponent(g.getReturnURL()));
a.push("scope="+q);a=a.join("&");var n=e.SSO_OPENID_CONNECT_TOKEN_URL;q={};var h=g.getClientID(),m=g.getClientSecret();f(m)&&(h="Basic "+btoa(h+":"+m),q[l.header.AUTHORIZATION]=h);b.ssoConnection(n,l.requestType.POST_METHOD,function(a){var c=a.target.status;if(p(c)){var d=JSON.parse(a.target.response),e=d.access_token,m=d.refresh_token;d=d.id_token;b.parseAndValidateJWT(d)?(g.setLLT(m),g.setAccessToken(e),g.setIDToken(d),setTimeout(function(){w(c,e)},1)):setTimeout(function(){w(null,Error("Token could not be verified"))},
1)}else setTimeout(function(){t.sendSSOErrorCodeWithFullUrl(c,n+"-"+l.requestType.POST_METHOD);w(c,a)},1)},q,a)};b.parseAndValidateJWT=function(b){var a=c.session;if(d(b))throw Error("JWT cannot be null.");b=b.split(".");JSON.parse(atob(b[0]));b=JSON.parse(u.decode(b[1]));var e=b.sub;a.setEmail(b.email);a.setNAGUID(e);return!0};b.getTokensFromAuthorizationCode=function(a,c){var d=[];d.push("grant_type=authorization_code");d.push("code="+a);b.generateToken(d,c)};b.getTokensFromRefreshToken=function(a){var d=
[],e=c.session;d.push("grant_type=refresh_token");d.push("refresh_token="+e.getLLT());b.generateToken(d,a)};b.ssoConnection=function(b,a,c,e,f){if(!r(b))throw Error("API URL should be a string");if(d(a))throw Error("Http method cannot be nil");if(!k(c))throw Error("Output callback should be a function");var g=new XMLHttpRequest;g.open(a,b,!0);g.timeout=l.DEFAULT_XHR_TIMEOUT;g.addEventListener("load",function(b){c(b)});g.addEventListener("error",function(b){c(b)});g.addEventListener("timeout",function(b){c(b)});
for(var m in e)g.setRequestHeader(m,e[m]);g.setRequestHeader(l.header.ACCEPT,l.contentType.JSON);g.setRequestHeader(l.header.CONTENT_TYPE,l.contentType.FORM_URL_ENCODED);g.send(f)};b.logout=function(b){var a=new XMLHttpRequest;a.open("GET",c.authSCD.SSO_LOGOUT_URL,!0);a.addEventListener("load",function(a){k(b)&&setTimeout(function(){b(!0)},1);!1===p(a.target.status)&&t.sendSSOErrorCodeWithFullUrl(a.target.status,e.SSO_LOGOUT_URL+"-"+l.requestType.GET_METHOD)});a.addEventListener("error",function(a){k(b)&&
setTimeout(function(){b(!1)},1);t.sendSSOErrorCodeWithFullUrl(a.target.status,e.SSO_LOGOUT_URL+"-"+l.requestType.GET_METHOD)});a.send()};b.signIntoNA=function(){c.naLoginManager.loginToNA()};return b}(c.SymBfw,c.SymO2)})(this);
(function(c){c.SymO2.cct=function(a,c){var b={},d=a.utils.isNil,f=a.utils.isSuccessCode,k=a.utils.isFunction,r=a.utils.isEmptyObject,p=a.logger;b.storeOIDCTokensAndConnectToOxygen=function(b,a){if(!k(a))throw Error("Callback has to be a function");if(r(b.oidctokens))p.error("OidcTokens cannot be null"),a(!1,Error("OidcTokens cannot be null"));else{var e=b.oidctokens.access_token,h=b.oidctokens.refresh_token;b=b.oidctokens.id_token;if(d(e)||d(h)||d(b))p.error("Tokens cannot be null"),a(!1,Error("Tokens cannot be null"));
else if(c.sso.parseAndValidateJWT(b)){var g=c.session;g.setLLT(h);g.setIDToken(b);g.setAccessToken(e);c.oxygen.getUserID(function(b,c){!1===f(b)?(g.logout(),setTimeout(function(){a(!1,c)},1)):setTimeout(function(){a(!0,null)},1)},e)}else setTimeout(function(){a(!1,Error("Token could not be verified"))},1)}};return b}(c.SymBfw,c.SymO2)})(this);
(function(c){c.SymO2.cookieManager=function(a,c){var b=null,d=null,f=c.proto.com.symantec.oxygen.rest.accounts.messages.SymcRSCookieHeaderList,k=c.constants,r=a.utils.isNil,p=a.utils.isntNil,u=a.utils.isFunction,e=a.logger,l=a.utils.isString;b=function(){};b.prototype.load=function(b){if(!u(b))throw Error("Callback should be a non-null function");d=a.settings.loadSettingsContainer(k.domain.COOKIES,!1);b(!0,null)};b.prototype.unload=function(){d=null};b.prototype.get=function(b){if(r(d))e.info("CookieManager is not loaded ");
else{if(!l(b))throw Error("url should be a string");var a=d.getObject(b);if(r(a)||r(a.expires))return e.info("Did not find any cookie stored for url : "+b),null;var c=new Date(a.expires);return(new Date).getTime()>=c.getTime()?(this.remove(b),null):a.cookie}};b.prototype.add=function(b,a){if(r(d))return e.info("CookieManager is not loaded "),!1;if(!l(b))throw Error("url should be a string");if(r(a))throw Error("Value cannot be null");var g=decodeURIComponent(a);g=forge.util.decode64(g);g=c.utils.createUInt8BufferFromStringBuffer(g);
var h=f.decode(g);g=new Date;p(h.cookies)&&p(h.cookies[0].expires)?g.setSeconds(g.getSeconds()+parseInt(h.cookies[0].expires)):g.setSeconds(g.getSeconds()+86399);h={};if((new Date).getTime()>=g.getTime())return e.error("Cookie expired "+k.header.SYMC_COOKIE+" for domain: "+b),!1;h.expires=g;h.cookie=a;d.setObject(b,h);return!0};b.prototype.remove=function(b){if(r(d))return e.info("CookieManager is not loaded "),!1;if(!l(b))throw Error("url should be a string");d.removeObject(b);return!0};b.prototype.removeAll=
function(b){d=null;a.settings.deleteSettingsContainer(k.domain.COOKIES,b);return!0};return b=new b}(c.SymBfw,c.SymO2)})(this);
(function(c){c.SymO2.oxygen=function(a,c){var b={oclContainer:null},d=a.utils.isNil,f=a.utils.isntNil,k=a.utils.isString,r=a.utils.isFunction,p=a.utils.isArray,u=a.utils,e=c.authSCD,l=c.proto.com.symantec.oxygen.rest.accounts.messages,t=c.proto.com.symantec.oxygen.datastore.v2.messages,g=c.sso,w=l.EncryptionKey,v=l.ExtendedSessionAccess,q=t.NodeList,n=t.InvalidNodeList,x=t.DatastoreRangeQuery,m=c.constants,D=a.constants.httpStatusCodes,C=a.utils.isSuccessCode,z=c.utils,y=a.logger,E=c.cookieManager,
A=c.telemetryWrapper;b.setContainer=function(a){if(d(a))throw Error("container cannot be null");b.oclContainer=a};b.getUserID=function(b,a){if(!1===r(b))throw Error("Callback cannot be nil/undefined and must be of type function");var d=c.session,g=e.O2_URL+"/users/key";this.oxygenConnection(g,m.requestType.GET_METHOD,a,function(a,c){if(C(a)){var e=c.target.response,f=null;try{f=w.decode(e),d.setUserID(f.getEntityId().toNumber()),d.setClientKey(f.getClientKey())}catch(F){y.error(F);setTimeout(function(){b(null,
F.message)},1);return}setTimeout(function(){b(a,null)},1)}else setTimeout(function(){A.sendOxygenErrorCodeWithFullUrl(a,g+"-"+m.requestType.GET_METHOD);b(a,c.target.response)},1)})};b.putNodes=function(a,c,g,n){if(d(a))throw Error("EntityID cannot be null");if(d(c))throw Error("Node list cannot be null");if(!1===c instanceof q)throw Error("nodeList is not an instance of NodeList class");if(0===c.getNodes().length)throw Error("Cannot upload empty node list without any nodes");if(!1===r(g))throw Error("Callback cannot be null or is not a function");
var h=null;h=d(n)?{}:n;n=b.oclContainer.getObject(m.oxygen.ETAG);f(n)&&(h[m.header.IF_MATCH]=n);b.oxygenConnection(e.DS_URL+"/"+a,m.requestType.PUT_METHOD,null,function(b,a){var c=a.target.response,d=null,n=null;a=a.target.getResponseHeader(m.header.CHALLENGES);f(a)&&(n={},n[m.header.CHALLENGES]=a);if(!1===C(b))setTimeout(function(){A.sendOxygenErrorCodeWithFullUrl(b,e.DS_URL+"-"+m.requestType.PUT_METHOD);g(b,null,c,n)},1);else{try{d=q.decode(c)}catch(G){y.error(G);setTimeout(function(){g(null,null,
G,n)},1);return}setTimeout(function(){g(b,d,null,n)},1)}},c,h)};b.getDatastorePaths=function(a,c,g,n,h,l,k){if(!p(a)||0===a.length)throw Error("Datastore paths cannot be nil or empty");if(d(c))throw Error("EntityID cannot be nil");if(!r(g)||4<g.length||3>g.length)throw Error("outCallback cannot be nil/undefined and has to be of type function or the argument list of the callback does not match Datastore callback");d(n)&&(n=!0);d(k)&&(k=!1);d(h)&&(h={});var t=b.oclContainer.getObject(m.oxygen.ETAG),
v=null;k||d(t)||(v=new x,v.setFromRevision(t),!1!==p(l)&&v.setToRevision(l));f(v)&&(l=z.createStringBufferFromUint8Buffer(v.toArrayBuffer()),l=forge.util.encode64(l),h[m.header.RANGE]=l);c=e.DS_URL+"/"+c;for(var w in a)c=c+a[w]+",";c=c.substring(0,c.length-1);b.oxygenConnection(c+"?include_sub_nodes="+n,m.requestType.GET_METHOD,null,function(b,a){a=a.target;var c=a.response,d=null,n=null;a=a.getResponseHeader(m.header.CHALLENGES);f(a)&&(n={},n[m.header.CHALLENGES]=a);if(C(b)){try{d=q.decode(c)}catch(B){y.error(B);
setTimeout(function(){g(b,d,n,B)},1);return}setTimeout(function(){g(b,d,n,null)},1)}else if(b===D.UNAUTHORIZED){try{d=q.decode(c)}catch(B){y.error(B);setTimeout(function(){g(b,d,n,B)},1);return}setTimeout(function(){A.sendOxygenErrorCodeWithFullUrl(b,e.DS_URL+"-"+m.requestType.GET_METHOD);g(b,d,n,c)},1)}else setTimeout(function(){A.sendOxygenErrorCodeWithFullUrl(b,e.DS_URL+"-"+m.requestType.GET_METHOD);g(b,d,h,c)},1)},null,h)};b.addACLs=function(a){if(d(a))throw Error("Callback function cannot be null");
var g=new v;g.setTtlDataStoreRead(e.DEFAULT_ACL_TTL);g.setTtlDataStoreWrite(e.DEFAULT_ACL_TTL);var n=e.O2_URL+"/users/"+c.session.getUserID()+"/session/access";b.oxygenConnection(n,m.requestType.POST_METHOD,null,a,g)};b.handleSchemaError=function(b){try{var a=decodeURIComponent(b),c=forge.util.decode64(a),d=z.createUInt8BufferFromStringBuffer(c),g=n.decode(d).getNodes(),e;for(e in g){var m=g[e],f=m.getPath(),q=m.getReason();A.sendOxygenDataStoreSchemaError(q,f)}}catch(H){y.error(H)}};b.oxygenConnection=
function(n,q,h,l,t,v){var x=c.session;if(!1===k(n))throw Error("API URL cannot be nil/undefined and has to be of type string");if(!1===k(q))throw Error("method cannot be nil/undefined and has to be of type string");if(!1===r(l))throw Error("outCallback cannot be nil/undefined and has to be of type function");d(h)&&(h=x.getAccessToken());var w=a.utils.baseURL(n),p=E.get(w);if(d(p)&&d(h))g.getTokensFromRefreshToken(function(a,c){C(a)?setTimeout(function(){b.oxygenConnection(n,q,c,l,t,v)},1):setTimeout(function(){l(a,
c)},1)});else{x=new XMLHttpRequest;x.open(q,n,!0);x.timeout=m.DEFAULT_XHR_TIMEOUT;x.addEventListener("load",function(a){if(-1<e.DS_URL.indexOf(w)){var c=a.target.getResponseHeader(m.header.ETAG);f(c)&&b.oclContainer.setObject(m.oxygen.ETAG,c);a.target.status===D.INVALID_SCHEMA&&(c=a.target.getResponseHeader(m.header.SCHEMA_ERROR),f(c)&&b.handleSchemaError(c))}c=a.target.getResponseHeader(m.header.SYMC_COOKIE);f(c)&&!1===E.add(w,c)&&y.debug("Failed to add cookie "+m.header.SYMC_COOKIE+" for "+w);l(a.target.status,
a)});x.addEventListener("error",function(b){l(b.target.status,b)});x.addEventListener("timeout",function(b){l(b.target.status,b)});if(f(v))for(var z in v)x.setRequestHeader(z,v[z]);f(p)?x.setRequestHeader(m.header.SYMC_COOKIE,p):x.setRequestHeader(m.header.SYMC_AUTH,"Bearer "+h);x.setRequestHeader(m.header.ORIGIN_HEADER,e.getMachineGUID());x.setRequestHeader(m.header.SYMC_MACHINE_ID,e.getMachineGUID());x.setRequestHeader(m.header.ACCEPT,m.contentType.PROTOBUF);x.setRequestHeader(m.header.CONTENT_TYPE,
m.contentType.PROTOBUF);x.setRequestHeader(m.header.USER_AGENT,e.USER_AGENT);h="bfw-o2-"+u.createNewGuid().toLowerCase().replace(/-/g,"");x.setRequestHeader(m.header.REQUEST_ID,h);console.log(h);x.responseType=m.responseType.ARRAY_BUFFER;h=null;f(t)&&(h=t.toArrayBuffer());x.send(h)}};return b}(c.SymBfw,c.SymO2)})(this);
(function(c){c.SymO2.session=function(a,c){var b={llt:null,naGUID:null,userID:null,email:null,firstName:null,lastName:null,clientKey:null,password:null,sessionContainer:null},d=a.utils,f=d.isNil,k=d.isntNil,r=d.isFunction,p=d.isArray,u=a.utils.isSuccessCode,e=c.constants,l=c.sso,t=c.oxygen,g=a.logger,w=c.telemetryWrapper,v=a.secureSettings;b.setContainer=function(a){if(f(a))throw Error("container cannot be null");b.sessionContainer=a;a=b.sessionContainer.getObject(e.session.LLT);var c=b.sessionContainer.getObject(e.session.NA_GUID),
d=b.sessionContainer.getObject(e.session.EMAIL),g=b.sessionContainer.getObject(e.session.USER_ID),q=b.sessionContainer.getObject(e.session.ACCESS_TOKEN),h=b.sessionContainer.getObject(e.session.ID_TOKEN);b.setLLT(a,!1);b.setNAGUID(c,!1);b.setUserID(g,!1);b.setEmail(d,!1);b.setAccessToken(q,!1);b.setIDToken(h,!1)};b.initialize=function(b,a,c,d){if(f(b))throw Error("Scopes cannot be null");if(f(a))throw Error("Return URL cannot be null");if(f(c))throw Error("Client ID cannot be null");this.scopes=b;
this.returnURL=a;this.clientID=c;this.clientSecret=d};b.getScopes=function(){if(f(this.scopes))throw Error("Scopes cannot be null. OCL has not be initialized");return this.scopes};b.getReturnURL=function(){if(f(this.returnURL))throw Error("Return URL cannot be null. OCL has not been initialized.");return this.returnURL};b.getClientID=function(){if(f(this.clientID))throw Error("Client ID cannot be null. OCL has not been initialized");return this.clientID};b.getClientSecret=function(){return this.clientSecret};
b.isLoggedIn=function(a){if(!1===r(a))throw Error("Callback cannot be null or is not a function");if(f(b.sessionContainer))setTimeout(function(){a(!1,Error("sessionContainer is not loaded"))},1);else{var c=b.sessionContainer.getObject(e.session.LLT);f(c)?setTimeout(function(){a(!1,Error("LLT unavailable"))},1):setTimeout(function(){a(!0,null)},1)}};b.login=function(a,c){if(!p(a))throw Error("URL parameters cannot be null or is not an Array");if(!r(c))throw Error("Callback cannot be null or is not a function");
l.parseAuthCodeAndGetTokens(a,function(a,d){!1===u(a)?(b.logout(),setTimeout(function(){w.sendSessionLoginErrorCode(a);c(!1,d)},1)):t.getUserID(function(a,d){!1===u(a)?(b.logout(),setTimeout(function(){c(!1,d)},1)):setTimeout(function(){c(!0,null)},1)},d)})};b.logout=function(b){this.password=this.email=this.naGUID=this.llt=this.clientKey=this.userID=this.lastName=this.firstName=null;v.resetSecureSettingsCollection(e.OCL_CONTAINER,function(a,c){a||g.error("OCL resetSecureSettingsCollection returned failure");
l.logout(function(a){a?b(!0,null):(b(!1,Error("SSO returned failure")),g.error("SSO logout returned failure"));w.sendSessionLogoutCode(!0===a?1:0)})})};b.setPassword=function(b){this.password=b};b.getPassword=function(){return this.password};b.getFirstName=function(){return this.firstName};b.setFirstName=function(a,c,d){this.firstName=a;f(c)&&(c=!0);c&&b.openSettingsAndSetObject(e.session.FIRST_NAME,a,d)};b.getLastName=function(){return this.lastName};b.setLastName=function(a,c,d){this.lastName=a;
f(c)&&(c=!0);c&&b.openSettingsAndSetObject(e.session.LAST_NAME,a,d)};b.getEmail=function(){return this.email};b.setEmail=function(a,c,d){this.email=a;f(c)&&(c=!0);c&&b.openSettingsAndSetObject(e.session.EMAIL,a,d)};b.setAccessToken=function(a,c,d){this.accessToken=a;f(c)&&(c=!0);c&&(c=(new Date).getTime()+e.session.DEFAULT_ACCESS_TOKEN_TTL,b.openSettingsAndSetObject(e.session.ACCESS_TOKEN,a,d),b.openSettingsAndSetObject(e.session.ACCESS_TOKEN_TTL,c,d))};b.getAccessToken=function(){if(f(this.accessToken))return null;
var a=b.sessionContainer.getObject(e.session.ACCESS_TOKEN_TTL),c=(new Date).getTime();return 0>=a-c?(this.accessToken=null,b.sessionContainer.removeObject(e.session.ACCESS_TOKEN_TTL),b.sessionContainer.removeObject(e.session.ACCESS_TOKEN),null):this.accessToken};b.setIDToken=function(a,c,d){this._idToken=a;f(c)&&(c=!0);c&&(c=(new Date).getTime()+e.session.DEFAULT_ID_TOKEN_TTL,b.openSettingsAndSetObject(e.session.ID_TOKEN,a,d),b.openSettingsAndSetObject(e.session.ID_TOKEN_TTL,c,d))};b.getIDToken=function(){if(f(this._idToken))return null;
var a=b.sessionContainer.getObject(e.session.ID_TOKEN_TTL),c=(new Date).getTime();return 0>=a-c?(this._idToken=null,b.sessionContainer.removeObject(e.session.ID_TOKEN_TTL),b.sessionContainer.removeObject(e.session.ID_TOKEN),null):this._idToken};b.getRefreshedIDToken=function(){var b=this;return new Promise(function(a){var c=b.getIDToken();if(k(c))return a(c);l.getTokensFromRefreshToken(function(d){c=200===d?b.getIDToken():null;return a(c)})})};b.getLLT=function(){return this.llt};b.setLLT=function(a,
c,d){this.llt=a;f(c)&&(c=!0);c&&b.openSettingsAndSetObject(e.session.LLT,a,d)};b.getNAGUID=function(){return this.naGUID};b.setNAGUID=function(a,c,d){this.naGUID=a;f(c)&&(c=!0);c&&b.openSettingsAndSetObject(e.session.NA_GUID,a,d)};b.getUserID=function(){return this.userID};b.setUserID=function(a,c,d){this.userID=a;f(c)&&(c=!0);c&&b.openSettingsAndSetObject(e.session.USER_ID,a,d)};b.setClientKey=function(a){this.clientKey=a};b.getClientKey=function(){return this.clientKey};b.openSettingsAndSetObject=
function(a,c,d){if(f(b.sessionContainer))!1!==r(d)&&setTimeout(function(){d(!1,Error("sessionContainer is not loaded"))},1);else try{b.sessionContainer.setObject(a,c,d)}catch(m){!1!==r(d)&&d(!1,m)}};b.serialize=function(){return{llt:this.llt,naGUID:this.naGUID,userID:this.userID,email:this.email,accessToken:this.accessToken,idToken:this._idToken}};return b}(c.SymBfw,c.SymO2)})(this);
(function(c){c.SymO2.spocRequest=function(a,c){var b={},d=c.constants,f=a.utils.isNil,k=a.utils.isntNil,r=a.logger,p=a.utils.isString,u=a.utils.isSuccessCode,e=c.authSCD,l=c.proto.spoc.SpocRegistrationArray,t=c.utils,g=c.telemetryWrapper,w=a.constants.httpStatusCodes,v=function(a,b){if(f(a))throw Error("Domain cannot be null");if(f(b))throw Error("Status code cannot be null");this.domain=a;this.code=b};v.prototype.getDomain=function(){return this.domain};v.prototype.getCode=function(){return this.code};
var q=function(a,b,c,d,g,e){if(f(a))throw Error("Status cannot be null");if(!1===p(b))throw Error("EntityID cannot be null");if(f(c))throw Error("Channel cannot be null");if(f(d))throw Error("Revision cannot be null");this.status=a;this.entityID=b;this.channel=c;this.revisionNumber=d;this.payload=g;f(e)&&(e=null);this.appID=e};q.prototype.getEntity=function(){return this.entityID};q.prototype.getApplicationID=function(){return this.appID};q.prototype.getRevision=function(){return this.revisionNumber};
q.prototype.getChannel=function(){return this.channel};q.prototype.getPayload=function(){return this.payload};q.prototype.getStatus=function(){return this.status};q.prototype.toString=function(){var a={};a.status=this.getStatus();a.entityID=this.getEntity();a.channel=this.getChannel();a.revision=this.getRevision();var b=null,c=this.getPayload();if(k(c)){b=t.createStringBufferFromUint8Buffer(c);if(f(b))throw Error("Could not convert BumpInfo to string");b=forge.util.encode64(b)}a.payLoad=b;a.appID=
this.getApplicationID();return JSON.stringify(a)};b.BumpInfo=q;b.Status=v;b.registrationCallbacks={};b.xhr=null;b.startDate=null;b.coalescingTimer=null;b.spocRegistrationMap={};b.retryCount=e.SPOC_RETRY_COUNT;b.currentTimeout=1;b.performCallback=function(a,b){var c=this.registrationCallbacks[a],d=c.callbackObj,g=c.callback;delete this.registrationCallbacks[a];delete this.spocRegistrationMap[a];setTimeout(function(){f(d)?g(b):g.apply(d,[b])},1)};var n=function(a,b){return a+":"+b};b.stopSPOCConnection=
function(a){if(k(a)){var c=a.getEntity();var g=a.getChannel();var e=c+":"+g;delete b.registrationCallbacks[e];delete b.spocRegistrationMap[e];b.startSPOCConnection()}else for(e in k(b.xhr)&&b.xhr.abort(),this.spocRegistrationMap){a=this.spocRegistrationMap[e];c=a.getEntity();g=a.getChannel();var f=a.getRevision();a=a.getApplicationID();var m=new v(d.spoc.INTERNAL_DOMAIN,d.spoc.internalErrors.STOPPED);c=new q(m,c,g,f,null,a);b.performCallback(e,c)}};b.startSPOCConnection=function(a,c,d){this.retryCount=
e.SPOC_RETRY_COUNT;this.retryTimeout=1;k(this.coalescingTimer)&&clearTimeout(this.coalescingTimer);if(k(a)&&k(c)){var g=n(a.getEntity(),a.getChannel());this.registrationCallbacks[g]={callback:c,callbackObj:d};this.spocRegistrationMap[g]=a}this.coalescingTimer=setTimeout(function(){k(b.xhr)&&b.xhr.abort();0===x().length?r.log("No registrations available. Spoc Connection will not be created."):b.performRetry(x())},5E3)};var x=function(){var a=[],c;for(c in b.spocRegistrationMap)a.push(b.spocRegistrationMap[c]);
return a};b.notifyClientsOnError=function(a){switch(a){case w.BAD_REQUEST:case w.ENTITY_TOO_LARGE:case w.RATE_LIMITING:a=new v(d.spoc.INTERNAL_DOMAIN,d.spoc.internalErrors.UNRECOVERABLE);break;default:a=new v(d.spoc.INTERNAL_DOMAIN,d.spoc.internalErrors.UNKNOWN)}for(var c in this.spocRegistrationMap){var g=this.spocRegistrationMap[c],e=g.getEntity(),f=g.getChannel(),l=g.getRevision();g=g.getApplicationID();e=new q(a,e,f,l,null,g);b.performCallback(c,e)}};b.notifyClientsOnSuccess=function(a){a=a.getRegistration();
for(var c=0;c<a.length;c++){var g=a[c],e=g.getEntity(),f=g.getChannel(),l=g.getRevision(),n=g.getApplicationID(),h=e+":"+f,k=new v(d.spoc.INTERNAL_DOMAIN,d.spoc.internalErrors.SUCCESS);g=new q(k,e,f,l,g.getPayload(),n);b.performCallback(h,g)}b.startSPOCConnection()};b.performRetry=function(a,c){0===this.retryCount?b.notifyClientsOnError(w.RATE_LIMITING):(this.retryTimeout=b.nextRetryTimeout(this.retryTimeout),this.retryCount--,setTimeout(function(){b.connection(a,c)},1E3*this.retryTimeout))};b.nextRetryTimeout=
function(a){var b=e.SPOC_RETRY_COUNT-this.retryCount;return 0===b?a:a+b*e.RETRY_TIMEOUT+Math.floor(60*Math.random()+1)};b.connection=function(a,c){if(f(a)||0===a.length)throw Error("Registration array cannot be null or empty");f(c)&&(c=e.SPOC_DEFAULT_TIMEOUT);var n=new l;n.setRegistration(a);var h=new XMLHttpRequest;h.open(d.requestType.POST_METHOD,e.SPOC_URL+"/register?t="+c,!0);h.timeout=1E3*c;h.responseType=d.responseType.ARRAY_BUFFER;h.setRequestHeader(d.header.SYMC_EXPECT,d.header.NOT_MODIFIED);
h.setRequestHeader(d.header.CONTENT_TYPE,d.contentType.PROTOBUF);h.setRequestHeader(d.header.USER_AGENT,e.SPOC_USER_AGENT);h.addEventListener("load",function(f){var h=f.target;f=h.status;h=h.response;f===w.NOT_MODIFIED?b.startSPOCConnection():u(f)?(f=l.decode(h),b.notifyClientsOnSuccess(f)):f===w.RATE_LIMITING?b.performRetry(a,c):(g.sendSpocErrorCodeWithFullUrl(f,e.SPOC_URL+"-"+d.requestType.POST_METHOD),b.notifyClientsOnError(f))});h.addEventListener("timeout",function(a){b.startSPOCConnection()});
h.addEventListener("error",function(a){b.notifyClientsOnError(a.target.status)});this.xhr=h;n=n.toArrayBuffer();this.xhr.send(n)};return b}(c.SymBfw,c.SymO2)})(this);
(function(c){c.SymO2.SpocRegistration=function(a,c){var b=c.constants,d=a.utils.isNil,f=a.utils.isFunction,k=a.logger,r=a.utils.isString,p=c.authSCD,u=c.spocRequest,e=c.proto.spoc.SpocRegistration,l=c.proto.com.symantec.oxygen.datastore.v2.messages.DataStoreSpocPayloadV2,t=function(b,c,e,h,l){if(!r(b))throw Error("Entity ID must be a string");if(d(c))throw Error("Channel cannot be Nil");if(!f(e))throw Error("The callback must be of type function");if(d(h))throw Error("Revision Number cannot be Nil");
if(d(l))l=null;else if(!r(l))throw Error("The application ID must be a string");this.entityID=b;this.channel=c;this.callback=e;this.revisionNumber=h;this.appID=l;this.guid=a.utils.createNewGuid()};t.prototype.getIdentity=function(){return this.guid};t.prototype.getEntityID=function(){return this.entityID};t.prototype.getChannel=function(){return this.channel};t.prototype.getRevision=function(){return this.revisionNumber};t.prototype.getAppID=function(){return this.appID};t.prototype.handlePayloadForChannelTwo=
function(a){if(d(a)||0===a.byteLength)return{sameMachine:!1};var b=p.getMachineGUID(),c=null;try{var g=l.decode(a);if(g.getOrigin()===b)return{sameMachine:!0};c=g.getToRevision()}catch(n){k.error(n)}return{sameMachine:!1,toRevisions:c}};t.prototype.internalCallback=function(a){var d=a.getStatus();this.revisionNumber=a.getRevision();var e=!1;if(d.getDomain()===b.spoc.INTERNAL_DOMAIN)switch(d.getCode()){case b.spoc.internalErrors.STOPPED:e=this.callback(a);break;case b.spoc.internalErrors.UNRECOVERABLE:this.callback(a);
break;case b.spoc.internalErrors.SUCCESS:d=null;if(this.channel===c.proto.spoc.SPOCChannel.SC_DATASTORE_UPDATE&&(e=this.handlePayloadForChannelTwo(a.getPayload()),d=e.toRevisions,e.sameMachine)){e=!0;break}e=this.callback(a,d);break;default:e=this.callback(a)}e&&this.addRegistration()};t.prototype.addRegistration=function(){var a=new e;a.setEntity(this.entityID);a.setChannel(this.channel);a.setRevision(this.revisionNumber);a.setApplicationID(this.appID);u.startSPOCConnection(a,this.internalCallback,
this);this.spocReg=a};t.prototype.removeRegistration=function(){if(d(this.spocReg))throw Error("Unexpected: the spoc registration is invalid");u.stopSPOCConnection(this.spocReg);this.spocReg=null};return t}(c.SymBfw,c.SymO2)})(this);
(function(c){c.SymO2.spocManager=function(a,c){var b={},d=c.constants,f=a.utils.isNil,k=a.logger,r=a.utils.isString,p=a.utils.isFunction,u=c.proto.spoc.SpocPollArray,e=c.proto.spoc.SpocPoll,l=c.authSCD,t=a.utils.isSuccessCode;b.connections={};b.makeSpocRequest=function(a,d,e,l,h){a=new c.SpocRegistration(a,d,e,l,h);a.addRegistration();d=a.getIdentity();if(f(d))throw Error("Unable to return the identity for SpocRegistration");b.connections[d]=a;return d};b.cancelSPOCRequest=function(a){if(f(a))return k.error("identity cannot be null"),
!1;if(!b.connections.hasOwnProperty(a))return k.warn("identity not found in SpocManager"),!1;b.connections[a].removeRegistration();delete b.connections[a];return!0};b.cancelSPOCRequests=function(){c.spocRequest.stopSPOCConnection();b.connections={}};b.getConnections=function(){return b.connections};b.poll=function(a,b,c){if(!r(a))throw Error("entityID must be a string");if(f(b))throw Error("channel cannot be Nil");if(!p(c))throw Error("callback must be a function");var g=new e;g.setEntity(a);g.setChannel(b);
a=[];a.push(g);g=new u;g.setPoll(a);a=new XMLHttpRequest;a.open(d.requestType.POST_METHOD,l.SPOC_URL+"/poll",!0);a.responseType=d.responseType.ARRAY_BUFFER;a.setRequestHeader(d.header.CONTENT_TYPE,d.contentType.PROTOBUF);a.setRequestHeader(d.header.USER_AGENT,l.SPOC_USER_AGENT);a.addEventListener("load",function(a){var b=a.target;a=b.status;b=b.response;t(a)?f(b)?c(1,Error("SPOC Poll response is Nil")):(a=u.decode(b),f(a)?c(1,Error("SPOC Poll response decode failed")):(a=a.getPoll(),0===a.length?
c(1,Error("SPOC Poll retured empty revision")):(a=a[0].getRevision(),c(a,null)))):c(1,Error("SPOC Poll failed, status: "+a))});a.addEventListener("error",function(a){c(1,Error("SPOC Poll failed"))});this.xhr=a;g=g.toArrayBuffer();this.xhr.send(g)};return b}(c.SymBfw,c.SymO2)})(this);
(function(c){c.SymO2.init=function(a,c){var b={},d=c.constants,f=a.utils.isNil,k=a.utils.isntNil,r=a.settings,p=a.secureSettings,u=a.extensionAdapter;b.loadOCLContainer=function(){if(k(b.oclPromise))return b.oclPromise;b.oclPromise=new Promise(function(a,b){var e=u.getExtensionId();p.loadSecureSettingsContainer(d.OCL_CONTAINER,e,function(d,e,l){!1===d||f(e)?b("Unable to load OCL container:"+l):(c.oxygen.setContainer(e),c.session.setContainer(e),a("OCL container loaded successfully"))})});return b.oclPromise};
b.setMachineGUID=function(){if(k(b.globalPromise))return b.globalPromise;b.globalPromise=new Promise(function(b,l){r.loadSettingsContainer(d.GLOBAL_CONTAINER,!0,function(e,g,h){if(!1===e)l("Unable to load GLOBAL container:"+h);else{var k=g.getObject(d.MACHINE_GUID);f(k)?(k=a.utils.createNewGuid(),g.setObject(d.MACHINE_GUID,k,function(a,d){a?(c.authSCD.setMachineGUID(k),b("GLOBAL container loaded successfully")):l("Could not set machineGUID : "+d)})):(c.authSCD.setMachineGUID(k),b("GLOBAL container loaded successfully"))}})});
return b.globalPromise};b.ready=function(){if(k(b.readyPromise))return b.readyPromise;b.readyPromise=new Promise(function(a,c){Promise.all([b.loadOCLContainer(),b.setMachineGUID()]).then(function(b){a(b)},function(a){c(a)})});return b.readyPromise};return b}(c.SymBfw,c.SymO2)})(this);
(function(c){c.SymO2.naLoginManager=function(a,c){var b=a.extensionAdapter,d=a.utils.isNil,f=a.utils.isntNil,k=a.utils,r=a.utils.isFunction,p=c.session,u=null,e={loginToNA:function(){e._launchSSO()},_launchSSO:function(){var a=c.sso.getOpenIDConnectLoginURL("142b5c23-5ba5-4cc9-baef-3cc1c45c595b");e._focusExistingLoginTab(a,function(c){c||b.createTab(a,function(a){b.addOnBeforeRequestEventListener(e._onAuthReturnUrl,[p.getReturnURL()+"?*"],["blocking"])})})},_focusExistingLoginTab:function(a,c){if(!r(c))throw Error("No callback function defined");
b.getTabsWithURL(a,function(e){f(b.getLastError())||d(e)?c(!1):d(e[0])||d(e[0].url)?c(!1):(e=e[0],e.url!==a?c(!1):(b.activateTab(e.id),b.focusWindow(b.getWindowIDForTab(e)),c(!0)))})},_onAuthReturnUrl:function(a){if(d(a))e._publishAuthEvent("LOGIN_FAILURE");else if(b.removeOnBeforeRequestEventListener(e._onAuthReturnUrl),d(a.tabId)||d(a.url))e._publishAuthEvent("LOGIN_FAILURE");else if(u!==a.tabId)if(u=a.tabId,k.urlWithoutQueryParameters(a.url,!0)!==p.getReturnURL())e._publishAuthEvent("LOGIN_FAILURE");
else{b.closeTab(a.tabId);var f=(new URI(a.url)).query(!0);if(d(f.code)||d(f.state))e._publishAuthEvent("LOGIN_FAILURE");else if("142b5c23-5ba5-4cc9-baef-3cc1c45c595b"!==f.state)e._publishAuthEvent("LOGIN_FAILURE");else{f=Object.keys(f).map(function(a){return a+"="+f[a]});try{c.sso.parseAuthCodeAndGetTokens(f,function(a,b){200==a?e._publishAuthEvent("LOGIN_SUCCESS"):e._publishAuthEvent("LOGIN_FAILURE")})}catch(g){e._publishAuthEvent("LOGIN_FAILURE")}}}},_publishAuthEvent:function(a){k.createCustomHTMLEvent("NA_LOGIN_STATUS",
a)}};return e}(c.SymBfw,c.SymO2)})(window);
