/*
 The buffer module from node.js, for the browser.

 @author   Feross Aboukhadijeh <https://feross.org>
 @license  MIT
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(q,k,l){q!=Array.prototype&&q!=Object.prototype&&(q[k]=l.value)};$jscomp.getGlobal=function(q){return"undefined"!=typeof window&&window===q?q:"undefined"!=typeof global&&null!=global?global:q};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(q,k,l,h){if(k){l=$jscomp.global;q=q.split(".");for(h=0;h<q.length-1;h++){var p=q[h];p in l||(l[p]={});l=l[p]}q=q[q.length-1];h=l[q];k=k(h);k!=h&&null!=k&&$jscomp.defineProperty(l,q,{configurable:!0,writable:!0,value:k})}};$jscomp.polyfill("Array.prototype.fill",function(q){return q?q:function(k,l,h){var p=this.length||0;0>l&&(l=Math.max(0,p+l));if(null==h||h>p)h=p;h=Number(h);0>h&&(h=Math.max(0,p+h));for(l=Number(l||0);l<h;l++)this[l]=k;return this}},"es6","es3");
(function(q){"object"===typeof exports&&"undefined"!==typeof module?module.exports=q():"function"===typeof define&&define.amd?define([],q):("undefined"!==typeof window?window:"undefined"!==typeof global?global:"undefined"!==typeof self?self:this).Buffer=q()})(function(){return function p(k,l,h){function d(g,f){if(!l[g]){if(!k[g]){var m="function"==typeof require&&require;if(!f&&m)return m(g,!0);if(n)return n(g,!0);f=Error("Cannot find module '"+g+"'");throw f.code="MODULE_NOT_FOUND",f;}f=l[g]={exports:{}};
k[g][0].call(f.exports,function(f){var m=k[g][1][f];return d(m?m:f)},f,f.exports,p,k,l,h)}return l[g].exports}for(var n="function"==typeof require&&require,g=0;g<h.length;g++)d(h[g]);return d}({1:[function(k,l,h){function p(a){if(a>B)throw new RangeError('The value "'+a+'" is invalid for option "size"');a=new Uint8Array(a);a.__proto__=d.prototype;return a}function d(a,b,c){if("number"===typeof a){if("string"===typeof b)throw new TypeError('The "string" argument must be of type string. Received type number');
return v(a)}return n(a,b,c)}function n(a,b,c){if("string"===typeof a){var e=b;if("string"!==typeof e||""===e)e="utf8";if(!d.isEncoding(e))throw new TypeError("Unknown encoding: "+e);b=G(a,e)|0;c=p(b);a=c.write(a,e);a!==b&&(c=c.slice(0,a));return c}if(ArrayBuffer.isView(a))return f(a);if(null==a)throw TypeError("The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type "+typeof a);if(y(a,ArrayBuffer)||a&&y(a.buffer,ArrayBuffer)){if(0>b||a.byteLength<
b)throw new RangeError('"offset" is outside of buffer bounds');if(a.byteLength<b+(c||0))throw new RangeError('"length" is outside of buffer bounds');a=void 0===b&&void 0===c?new Uint8Array(a):void 0===c?new Uint8Array(a,b):new Uint8Array(a,b,c);a.__proto__=d.prototype;return a}if("number"===typeof a)throw new TypeError('The "value" argument must not be of type number. Received type number');e=a.valueOf&&a.valueOf();if(null!=e&&e!==a)return d.from(e,b,c);if(e=m(a))return e;if("undefined"!==typeof Symbol&&
null!=Symbol.toPrimitive&&"function"===typeof a[Symbol.toPrimitive])return d.from(a[Symbol.toPrimitive]("string"),b,c);throw new TypeError("The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type "+typeof a);}function g(a){if("number"!==typeof a)throw new TypeError('"size" argument must be of type number');if(0>a)throw new RangeError('The value "'+a+'" is invalid for option "size"');}function v(a){g(a);return p(0>a?0:E(a)|0)}function f(a){for(var b=
0>a.length?0:E(a.length)|0,c=p(b),e=0;e<b;e+=1)c[e]=a[e]&255;return c}function m(a){if(d.isBuffer(a)){var b=E(a.length)|0,c=p(b);if(0===c.length)return c;a.copy(c,0,0,b);return c}if(void 0!==a.length)return(b="number"!==typeof a.length)||(b=a.length,b=b!==b),b?p(0):f(a);if("Buffer"===a.type&&Array.isArray(a.data))return f(a.data)}function E(a){if(a>=B)throw new RangeError("Attempt to allocate Buffer larger than maximum size: 0x"+B.toString(16)+" bytes");return a|0}function G(a,b){if(d.isBuffer(a))return a.length;
if(ArrayBuffer.isView(a)||y(a,ArrayBuffer))return a.byteLength;if("string"!==typeof a)throw new TypeError('The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type '+typeof a);var c=a.length,e=2<arguments.length&&!0===arguments[2];if(!e&&0===c)return 0;for(var t=!1;;)switch(b){case "ascii":case "latin1":case "binary":return c;case "utf8":case "utf-8":return F(a).length;case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":return 2*c;case "hex":return c>>>1;case "base64":return C.toByteArray(H(a)).length;
default:if(t)return e?-1:F(a).length;b=(""+b).toLowerCase();t=!0}}function O(a,b,c){var e=!1;if(void 0===b||0>b)b=0;if(b>this.length)return"";if(void 0===c||c>this.length)c=this.length;if(0>=c)return"";c>>>=0;b>>>=0;if(c<=b)return"";for(a||(a="utf8");;)switch(a){case "hex":a=b;b=c;c=this.length;if(!a||0>a)a=0;if(!b||0>b||b>c)b=c;e="";for(c=a;c<b;++c)a=e,e=this[c],e=16>e?"0"+e.toString(16):e.toString(16),e=a+e;return e;case "utf8":case "utf-8":return I(this,b,c);case "ascii":a="";for(c=Math.min(this.length,
c);b<c;++b)a+=String.fromCharCode(this[b]&127);return a;case "latin1":case "binary":a="";for(c=Math.min(this.length,c);b<c;++b)a+=String.fromCharCode(this[b]);return a;case "base64":return b=0===b&&c===this.length?C.fromByteArray(this):C.fromByteArray(this.slice(b,c)),b;case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":b=this.slice(b,c);c="";for(a=0;a<b.length;a+=2)c+=String.fromCharCode(b[a]+256*b[a+1]);return c;default:if(e)throw new TypeError("Unknown encoding: "+a);a=(a+"").toLowerCase();
e=!0}}function w(a,b,c){var e=a[b];a[b]=a[c];a[c]=e}function r(a,b,c,e,t){if(0===a.length)return-1;"string"===typeof c?(e=c,c=0):2147483647<c?c=2147483647:-2147483648>c&&(c=-2147483648);c=+c;c!==c&&(c=t?0:a.length-1);0>c&&(c=a.length+c);if(c>=a.length){if(t)return-1;c=a.length-1}else if(0>c)if(t)c=0;else return-1;"string"===typeof b&&(b=d.from(b,e));if(d.isBuffer(b))return 0===b.length?-1:D(a,b,c,e,t);if("number"===typeof b)return b&=255,"function"===typeof Uint8Array.prototype.indexOf?t?Uint8Array.prototype.indexOf.call(a,
b,c):Uint8Array.prototype.lastIndexOf.call(a,b,c):D(a,[b],c,e,t);throw new TypeError("val must be string, number or Buffer");}function D(a,b,c,e,d){function t(a,b){return 1===f?a[b]:a.readUInt16BE(b*f)}var f=1,g=a.length,m=b.length;if(void 0!==e&&(e=String(e).toLowerCase(),"ucs2"===e||"ucs-2"===e||"utf16le"===e||"utf-16le"===e)){if(2>a.length||2>b.length)return-1;f=2;g/=2;m/=2;c/=2}if(d)for(e=-1;c<g;c++)if(t(a,c)===t(b,-1===e?0:c-e)){if(-1===e&&(e=c),c-e+1===m)return e*f}else-1!==e&&(c-=c-e),e=-1;
else for(c+m>g&&(c=g-m);0<=c;c--){g=!0;for(e=0;e<m;e++)if(t(a,c+e)!==t(b,e)){g=!1;break}if(g)return c}return-1}function I(a,b,c){c=Math.min(a.length,c);for(var e=[];b<c;){var d=a[b],f=null,g=239<d?4:223<d?3:191<d?2:1;if(b+g<=c)switch(g){case 1:128>d&&(f=d);break;case 2:var m=a[b+1];128===(m&192)&&(d=(d&31)<<6|m&63,127<d&&(f=d));break;case 3:m=a[b+1];var h=a[b+2];128===(m&192)&&128===(h&192)&&(d=(d&15)<<12|(m&63)<<6|h&63,2047<d&&(55296>d||57343<d)&&(f=d));break;case 4:m=a[b+1];h=a[b+2];var n=a[b+3];
128===(m&192)&&128===(h&192)&&128===(n&192)&&(d=(d&15)<<18|(m&63)<<12|(h&63)<<6|n&63,65535<d&&1114112>d&&(f=d))}null===f?(f=65533,g=1):65535<f&&(f-=65536,e.push(f>>>10&1023|55296),f=56320|f&1023);e.push(f);b+=g}a=e.length;if(a<=J)e=String.fromCharCode.apply(String,e);else{c="";for(b=0;b<a;)c+=String.fromCharCode.apply(String,e.slice(b,b+=J));e=c}return e}function u(a,b,c){if(0!==a%1||0>a)throw new RangeError("offset is not uint");if(a+b>c)throw new RangeError("Trying to access beyond buffer length");
}function x(a,b,c,e,t,f){if(!d.isBuffer(a))throw new TypeError('"buffer" argument must be a Buffer instance');if(b>t||b<f)throw new RangeError('"value" argument is out of bounds');if(c+e>a.length)throw new RangeError("Index out of range");}function K(a,b,c,e,d,f){if(c+e>a.length)throw new RangeError("Index out of range");if(0>c)throw new RangeError("Index out of range");}function L(a,b,c,e,d){b=+b;c>>>=0;d||K(a,b,c,4,3.4028234663852886E38,-3.4028234663852886E38);z.write(a,b,c,e,23,4);return c+4}function M(a,
b,c,e,d){b=+b;c>>>=0;d||K(a,b,c,8,1.7976931348623157E308,-1.7976931348623157E308);z.write(a,b,c,e,52,8);return c+8}function H(a){a=a.split("=")[0];a=a.trim().replace(P,"");if(2>a.length)return"";for(;0!==a.length%4;)a+="=";return a}function F(a,b){b=b||Infinity;for(var c,e=a.length,d=null,f=[],g=0;g<e;++g){c=a.charCodeAt(g);if(55295<c&&57344>c){if(!d){if(56319<c){-1<(b-=3)&&f.push(239,191,189);continue}else if(g+1===e){-1<(b-=3)&&f.push(239,191,189);continue}d=c;continue}if(56320>c){-1<(b-=3)&&f.push(239,
191,189);d=c;continue}c=(d-55296<<10|c-56320)+65536}else d&&-1<(b-=3)&&f.push(239,191,189);d=null;if(128>c){if(0>--b)break;f.push(c)}else if(2048>c){if(0>(b-=2))break;f.push(c>>6|192,c&63|128)}else if(65536>c){if(0>(b-=3))break;f.push(c>>12|224,c>>6&63|128,c&63|128)}else if(1114112>c){if(0>(b-=4))break;f.push(c>>18|240,c>>12&63|128,c>>6&63|128,c&63|128)}else throw Error("Invalid code point");}return f}function N(a){for(var b=[],c=0;c<a.length;++c)b.push(a.charCodeAt(c)&255);return b}function A(a,
b,c,e){for(var d=0;d<e&&!(d+c>=b.length||d>=a.length);++d)b[d+c]=a[d];return d}function y(a,b){return a instanceof b||null!=a&&null!=a.constructor&&null!=a.constructor.name&&a.constructor.name===b.name}var C=k("base64-js"),z=k("ieee754");h.Buffer=d;h.SlowBuffer=function(a){+a!=a&&(a=0);return d.alloc(+a)};h.INSPECT_MAX_BYTES=50;var B=2147483647;h.kMaxLength=B;d.TYPED_ARRAY_SUPPORT=function(){try{var a=new Uint8Array(1);a.__proto__={__proto__:Uint8Array.prototype,foo:function(){return 42}};return 42===
a.foo()}catch(b){return!1}}();d.TYPED_ARRAY_SUPPORT||"undefined"===typeof console||"function"!==typeof console.error||console.error("This browser lacks typed array (Uint8Array) support which is required by `buffer` v5.x. Use `buffer` v4.x if you require old browser support.");Object.defineProperty(d.prototype,"parent",{enumerable:!0,get:function(){if(d.isBuffer(this))return this.buffer}});Object.defineProperty(d.prototype,"offset",{enumerable:!0,get:function(){if(d.isBuffer(this))return this.byteOffset}});
"undefined"!==typeof Symbol&&null!=Symbol.species&&d[Symbol.species]===d&&Object.defineProperty(d,Symbol.species,{value:null,configurable:!0,enumerable:!1,writable:!1});d.poolSize=8192;d.from=function(a,b,c){return n(a,b,c)};d.prototype.__proto__=Uint8Array.prototype;d.__proto__=Uint8Array;d.alloc=function(a,b,c){g(a);a=0>=a?p(a):void 0!==b?"string"===typeof c?p(a).fill(b,c):p(a).fill(b):p(a);return a};d.allocUnsafe=function(a){return v(a)};d.allocUnsafeSlow=function(a){return v(a)};d.isBuffer=function(a){return null!=
a&&!0===a._isBuffer&&a!==d.prototype};d.compare=function(a,b){y(a,Uint8Array)&&(a=d.from(a,a.offset,a.byteLength));y(b,Uint8Array)&&(b=d.from(b,b.offset,b.byteLength));if(!d.isBuffer(a)||!d.isBuffer(b))throw new TypeError('The "buf1", "buf2" arguments must be one of type Buffer or Uint8Array');if(a===b)return 0;for(var c=a.length,e=b.length,f=0,g=Math.min(c,e);f<g;++f)if(a[f]!==b[f]){c=a[f];e=b[f];break}return c<e?-1:e<c?1:0};d.isEncoding=function(a){switch(String(a).toLowerCase()){case "hex":case "utf8":case "utf-8":case "ascii":case "latin1":case "binary":case "base64":case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":return!0;
default:return!1}};d.concat=function(a,b){if(!Array.isArray(a))throw new TypeError('"list" argument must be an Array of Buffers');if(0===a.length)return d.alloc(0);var c;if(void 0===b)for(c=b=0;c<a.length;++c)b+=a[c].length;b=d.allocUnsafe(b);var e=0;for(c=0;c<a.length;++c){var f=a[c];y(f,Uint8Array)&&(f=d.from(f));if(!d.isBuffer(f))throw new TypeError('"list" argument must be an Array of Buffers');f.copy(b,e);e+=f.length}return b};d.byteLength=G;d.prototype._isBuffer=!0;d.prototype.swap16=function(){var a=
this.length;if(0!==a%2)throw new RangeError("Buffer size must be a multiple of 16-bits");for(var b=0;b<a;b+=2)w(this,b,b+1);return this};d.prototype.swap32=function(){var a=this.length;if(0!==a%4)throw new RangeError("Buffer size must be a multiple of 32-bits");for(var b=0;b<a;b+=4)w(this,b,b+3),w(this,b+1,b+2);return this};d.prototype.swap64=function(){var a=this.length;if(0!==a%8)throw new RangeError("Buffer size must be a multiple of 64-bits");for(var b=0;b<a;b+=8)w(this,b,b+7),w(this,b+1,b+6),
w(this,b+2,b+5),w(this,b+3,b+4);return this};d.prototype.toString=function(){var a=this.length;return 0===a?"":0===arguments.length?I(this,0,a):O.apply(this,arguments)};d.prototype.toLocaleString=d.prototype.toString;d.prototype.equals=function(a){if(!d.isBuffer(a))throw new TypeError("Argument must be a Buffer");return this===a?!0:0===d.compare(this,a)};d.prototype.inspect=function(){var a=h.INSPECT_MAX_BYTES;var b=this.toString("hex",0,a).replace(/(.{2})/g,"$1 ").trim();this.length>a&&(b+=" ... ");
return"<Buffer "+b+">"};d.prototype.compare=function(a,b,c,e,f){y(a,Uint8Array)&&(a=d.from(a,a.offset,a.byteLength));if(!d.isBuffer(a))throw new TypeError('The "target" argument must be one of type Buffer or Uint8Array. Received type '+typeof a);void 0===b&&(b=0);void 0===c&&(c=a?a.length:0);void 0===e&&(e=0);void 0===f&&(f=this.length);if(0>b||c>a.length||0>e||f>this.length)throw new RangeError("out of range index");if(e>=f&&b>=c)return 0;if(e>=f)return-1;if(b>=c)return 1;b>>>=0;c>>>=0;e>>>=0;f>>>=
0;if(this===a)return 0;var g=f-e,m=c-b,t=Math.min(g,m);e=this.slice(e,f);a=a.slice(b,c);for(b=0;b<t;++b)if(e[b]!==a[b]){g=e[b];m=a[b];break}return g<m?-1:m<g?1:0};d.prototype.includes=function(a,b,c){return-1!==this.indexOf(a,b,c)};d.prototype.indexOf=function(a,b,c){return r(this,a,b,c,!0)};d.prototype.lastIndexOf=function(a,b,c){return r(this,a,b,c,!1)};d.prototype.write=function(a,b,c,e){if(void 0===b)e="utf8",c=this.length,b=0;else if(void 0===c&&"string"===typeof b)e=b,c=this.length,b=0;else if(isFinite(b))b>>>=
0,isFinite(c)?(c>>>=0,void 0===e&&(e="utf8")):(e=c,c=void 0);else throw Error("Buffer.write(string, encoding, offset[, length]) is no longer supported");var d=this.length-b;if(void 0===c||c>d)c=d;if(0<a.length&&(0>c||0>b)||b>this.length)throw new RangeError("Attempt to write outside buffer bounds");e||(e="utf8");for(d=!1;;)switch(e){case "hex":a:{b=Number(b)||0;e=this.length-b;c?(c=Number(c),c>e&&(c=e)):c=e;e=a.length;c>e/2&&(c=e/2);for(e=0;e<c;++e){d=parseInt(a.substr(2*e,2),16);if(d!==d){a=e;break a}this[b+
e]=d}a=e}return a;case "utf8":case "utf-8":return A(F(a,this.length-b),this,b,c);case "ascii":return A(N(a),this,b,c);case "latin1":case "binary":return A(N(a),this,b,c);case "base64":return A(C.toByteArray(H(a)),this,b,c);case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":e=a;d=this.length-b;for(var f=[],g=0;g<e.length&&!(0>(d-=2));++g){var m=e.charCodeAt(g);a=m>>8;m%=256;f.push(m);f.push(a)}return A(f,this,b,c);default:if(d)throw new TypeError("Unknown encoding: "+e);e=(""+e).toLowerCase();
d=!0}};d.prototype.toJSON=function(){return{type:"Buffer",data:Array.prototype.slice.call(this._arr||this,0)}};var J=4096;d.prototype.slice=function(a,b){var c=this.length;a=~~a;b=void 0===b?c:~~b;0>a?(a+=c,0>a&&(a=0)):a>c&&(a=c);0>b?(b+=c,0>b&&(b=0)):b>c&&(b=c);b<a&&(b=a);a=this.subarray(a,b);a.__proto__=d.prototype;return a};d.prototype.readUIntLE=function(a,b,c){a>>>=0;b>>>=0;c||u(a,b,this.length);c=this[a];for(var e=1,d=0;++d<b&&(e*=256);)c+=this[a+d]*e;return c};d.prototype.readUIntBE=function(a,
b,c){a>>>=0;b>>>=0;c||u(a,b,this.length);c=this[a+--b];for(var e=1;0<b&&(e*=256);)c+=this[a+--b]*e;return c};d.prototype.readUInt8=function(a,b){a>>>=0;b||u(a,1,this.length);return this[a]};d.prototype.readUInt16LE=function(a,b){a>>>=0;b||u(a,2,this.length);return this[a]|this[a+1]<<8};d.prototype.readUInt16BE=function(a,b){a>>>=0;b||u(a,2,this.length);return this[a]<<8|this[a+1]};d.prototype.readUInt32LE=function(a,b){a>>>=0;b||u(a,4,this.length);return(this[a]|this[a+1]<<8|this[a+2]<<16)+16777216*
this[a+3]};d.prototype.readUInt32BE=function(a,b){a>>>=0;b||u(a,4,this.length);return 16777216*this[a]+(this[a+1]<<16|this[a+2]<<8|this[a+3])};d.prototype.readIntLE=function(a,b,c){a>>>=0;b>>>=0;c||u(a,b,this.length);c=this[a];for(var e=1,d=0;++d<b&&(e*=256);)c+=this[a+d]*e;c>=128*e&&(c-=Math.pow(2,8*b));return c};d.prototype.readIntBE=function(a,b,c){a>>>=0;b>>>=0;c||u(a,b,this.length);c=b;for(var e=1,d=this[a+--c];0<c&&(e*=256);)d+=this[a+--c]*e;d>=128*e&&(d-=Math.pow(2,8*b));return d};d.prototype.readInt8=
function(a,b){a>>>=0;b||u(a,1,this.length);return this[a]&128?-1*(255-this[a]+1):this[a]};d.prototype.readInt16LE=function(a,b){a>>>=0;b||u(a,2,this.length);a=this[a]|this[a+1]<<8;return a&32768?a|4294901760:a};d.prototype.readInt16BE=function(a,b){a>>>=0;b||u(a,2,this.length);a=this[a+1]|this[a]<<8;return a&32768?a|4294901760:a};d.prototype.readInt32LE=function(a,b){a>>>=0;b||u(a,4,this.length);return this[a]|this[a+1]<<8|this[a+2]<<16|this[a+3]<<24};d.prototype.readInt32BE=function(a,b){a>>>=0;
b||u(a,4,this.length);return this[a]<<24|this[a+1]<<16|this[a+2]<<8|this[a+3]};d.prototype.readFloatLE=function(a,b){a>>>=0;b||u(a,4,this.length);return z.read(this,a,!0,23,4)};d.prototype.readFloatBE=function(a,b){a>>>=0;b||u(a,4,this.length);return z.read(this,a,!1,23,4)};d.prototype.readDoubleLE=function(a,b){a>>>=0;b||u(a,8,this.length);return z.read(this,a,!0,52,8)};d.prototype.readDoubleBE=function(a,b){a>>>=0;b||u(a,8,this.length);return z.read(this,a,!1,52,8)};d.prototype.writeUIntLE=function(a,
b,c,e){a=+a;b>>>=0;c>>>=0;e||x(this,a,b,c,Math.pow(2,8*c)-1,0);e=1;var d=0;for(this[b]=a&255;++d<c&&(e*=256);)this[b+d]=a/e&255;return b+c};d.prototype.writeUIntBE=function(a,b,c,e){a=+a;b>>>=0;c>>>=0;e||x(this,a,b,c,Math.pow(2,8*c)-1,0);e=c-1;var d=1;for(this[b+e]=a&255;0<=--e&&(d*=256);)this[b+e]=a/d&255;return b+c};d.prototype.writeUInt8=function(a,b,c){a=+a;b>>>=0;c||x(this,a,b,1,255,0);this[b]=a&255;return b+1};d.prototype.writeUInt16LE=function(a,b,c){a=+a;b>>>=0;c||x(this,a,b,2,65535,0);this[b]=
a&255;this[b+1]=a>>>8;return b+2};d.prototype.writeUInt16BE=function(a,b,c){a=+a;b>>>=0;c||x(this,a,b,2,65535,0);this[b]=a>>>8;this[b+1]=a&255;return b+2};d.prototype.writeUInt32LE=function(a,b,c){a=+a;b>>>=0;c||x(this,a,b,4,4294967295,0);this[b+3]=a>>>24;this[b+2]=a>>>16;this[b+1]=a>>>8;this[b]=a&255;return b+4};d.prototype.writeUInt32BE=function(a,b,c){a=+a;b>>>=0;c||x(this,a,b,4,4294967295,0);this[b]=a>>>24;this[b+1]=a>>>16;this[b+2]=a>>>8;this[b+3]=a&255;return b+4};d.prototype.writeIntLE=function(a,
b,c,e){a=+a;b>>>=0;e||(e=Math.pow(2,8*c-1),x(this,a,b,c,e-1,-e));e=0;var d=1,f=0;for(this[b]=a&255;++e<c&&(d*=256);)0>a&&0===f&&0!==this[b+e-1]&&(f=1),this[b+e]=(a/d>>0)-f&255;return b+c};d.prototype.writeIntBE=function(a,b,c,e){a=+a;b>>>=0;e||(e=Math.pow(2,8*c-1),x(this,a,b,c,e-1,-e));e=c-1;var d=1,f=0;for(this[b+e]=a&255;0<=--e&&(d*=256);)0>a&&0===f&&0!==this[b+e+1]&&(f=1),this[b+e]=(a/d>>0)-f&255;return b+c};d.prototype.writeInt8=function(a,b,c){a=+a;b>>>=0;c||x(this,a,b,1,127,-128);0>a&&(a=255+
a+1);this[b]=a&255;return b+1};d.prototype.writeInt16LE=function(a,b,c){a=+a;b>>>=0;c||x(this,a,b,2,32767,-32768);this[b]=a&255;this[b+1]=a>>>8;return b+2};d.prototype.writeInt16BE=function(a,b,c){a=+a;b>>>=0;c||x(this,a,b,2,32767,-32768);this[b]=a>>>8;this[b+1]=a&255;return b+2};d.prototype.writeInt32LE=function(a,b,c){a=+a;b>>>=0;c||x(this,a,b,4,2147483647,-2147483648);this[b]=a&255;this[b+1]=a>>>8;this[b+2]=a>>>16;this[b+3]=a>>>24;return b+4};d.prototype.writeInt32BE=function(a,b,c){a=+a;b>>>=
0;c||x(this,a,b,4,2147483647,-2147483648);0>a&&(a=4294967295+a+1);this[b]=a>>>24;this[b+1]=a>>>16;this[b+2]=a>>>8;this[b+3]=a&255;return b+4};d.prototype.writeFloatLE=function(a,b,c){return L(this,a,b,!0,c)};d.prototype.writeFloatBE=function(a,b,c){return L(this,a,b,!1,c)};d.prototype.writeDoubleLE=function(a,b,c){return M(this,a,b,!0,c)};d.prototype.writeDoubleBE=function(a,b,c){return M(this,a,b,!1,c)};d.prototype.copy=function(a,b,c,e){if(!d.isBuffer(a))throw new TypeError("argument should be a Buffer");
c||(c=0);e||0===e||(e=this.length);b>=a.length&&(b=a.length);b||(b=0);0<e&&e<c&&(e=c);if(e===c||0===a.length||0===this.length)return 0;if(0>b)throw new RangeError("targetStart out of bounds");if(0>c||c>=this.length)throw new RangeError("Index out of range");if(0>e)throw new RangeError("sourceEnd out of bounds");e>this.length&&(e=this.length);a.length-b<e-c&&(e=a.length-b+c);var f=e-c;if(this===a&&"function"===typeof Uint8Array.prototype.copyWithin)this.copyWithin(b,c,e);else if(this===a&&c<b&&b<e)for(e=
f-1;0<=e;--e)a[e+b]=this[e+c];else Uint8Array.prototype.set.call(a,this.subarray(c,e),b);return f};d.prototype.fill=function(a,b,c,e){if("string"===typeof a){"string"===typeof b?(e=b,b=0,c=this.length):"string"===typeof c&&(e=c,c=this.length);if(void 0!==e&&"string"!==typeof e)throw new TypeError("encoding must be a string");if("string"===typeof e&&!d.isEncoding(e))throw new TypeError("Unknown encoding: "+e);if(1===a.length){var f=a.charCodeAt(0);if("utf8"===e&&128>f||"latin1"===e)a=f}}else"number"===
typeof a&&(a&=255);if(0>b||this.length<b||this.length<c)throw new RangeError("Out of range index");if(c<=b)return this;b>>>=0;c=void 0===c?this.length:c>>>0;a||(a=0);if("number"===typeof a)for(e=b;e<c;++e)this[e]=a;else{f=d.isBuffer(a)?a:d.from(a,e);var g=f.length;if(0===g)throw new TypeError('The value "'+a+'" is invalid for argument "value"');for(e=0;e<c-b;++e)this[e+b]=f[e%g]}return this};var P=/[^+/0-9A-Za-z-_]/g},{"base64-js":2,ieee754:3}],2:[function(k,l,h){function p(d){var f=d.length;if(0<
f%4)throw Error("Invalid string. Length must be a multiple of 4");d=d.indexOf("=");-1===d&&(d=f);return[d,d===f?0:4-d%4]}function d(d,g,h){for(var f=[],m=g;m<h;m+=3)g=(d[m]<<16&16711680)+(d[m+1]<<8&65280)+(d[m+2]&255),f.push(n[g>>18&63]+n[g>>12&63]+n[g>>6&63]+n[g&63]);return f.join("")}h.byteLength=function(d){d=p(d);var f=d[1];return 3*(d[0]+f)/4-f};h.toByteArray=function(d){var f=p(d);var h=f[0];f=f[1];var n=new v(3*(h+f)/4-f),k=0,l=0<f?h-4:h,r;for(r=0;r<l;r+=4)h=g[d.charCodeAt(r)]<<18|g[d.charCodeAt(r+
1)]<<12|g[d.charCodeAt(r+2)]<<6|g[d.charCodeAt(r+3)],n[k++]=h>>16&255,n[k++]=h>>8&255,n[k++]=h&255;2===f&&(h=g[d.charCodeAt(r)]<<2|g[d.charCodeAt(r+1)]>>4,n[k++]=h&255);1===f&&(h=g[d.charCodeAt(r)]<<10|g[d.charCodeAt(r+1)]<<4|g[d.charCodeAt(r+2)]>>2,n[k++]=h>>8&255,n[k++]=h&255);return n};h.fromByteArray=function(f){for(var g=f.length,h=g%3,k=[],p=0,l=g-h;p<l;p+=16383)k.push(d(f,p,p+16383>l?l:p+16383));1===h?(f=f[g-1],k.push(n[f>>2]+n[f<<4&63]+"==")):2===h&&(f=(f[g-2]<<8)+f[g-1],k.push(n[f>>10]+n[f>>
4&63]+n[f<<2&63]+"="));return k.join("")};var n=[],g=[],v="undefined"!==typeof Uint8Array?Uint8Array:Array;for(k=0;64>k;++k)n[k]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[k],g["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charCodeAt(k)]=k;g[45]=62;g[95]=63},{}],3:[function(k,l,h){h.read=function(h,d,n,g,k){var f=8*k-g-1;var m=(1<<f)-1,p=m>>1,l=-7;k=n?k-1:0;var v=n?-1:1,w=h[d+k];k+=v;n=w&(1<<-l)-1;w>>=-l;for(l+=f;0<l;n=256*n+h[d+k],k+=v,l-=8);f=n&(1<<-l)-
1;n>>=-l;for(l+=g;0<l;f=256*f+h[d+k],k+=v,l-=8);if(0===n)n=1-p;else{if(n===m)return f?NaN:Infinity*(w?-1:1);f+=Math.pow(2,g);n-=p}return(w?-1:1)*f*Math.pow(2,n-g)};h.write=function(h,d,k,g,l,f){var m,n=8*f-l-1,p=(1<<n)-1,v=p>>1,w=23===l?Math.pow(2,-24)-Math.pow(2,-77):0;f=g?0:f-1;var r=g?1:-1,D=0>d||0===d&&0>1/d?1:0;d=Math.abs(d);isNaN(d)||Infinity===d?(d=isNaN(d)?1:0,g=p):(g=Math.floor(Math.log(d)/Math.LN2),1>d*(m=Math.pow(2,-g))&&(g--,m*=2),d=1<=g+v?d+w/m:d+w*Math.pow(2,1-v),2<=d*m&&(g++,m/=2),
g+v>=p?(d=0,g=p):1<=g+v?(d=(d*m-1)*Math.pow(2,l),g+=v):(d=d*Math.pow(2,v-1)*Math.pow(2,l),g=0));for(;8<=l;h[k+f]=d&255,f+=r,d/=256,l-=8);g=g<<l|d;for(n+=l;0<n;h[k+f]=g&255,f+=r,g/=256,n-=8);h[k+f-r]|=128*D}},{}]},{},[1])(1)});
