/*
 The buffer module from node.js, for the browser.

 @author   Feross Aboukhadijeh <https://feross.org>
 @license  MIT
 Determine if an object is a Buffer

 @author   Feross Aboukhadijeh <https://feross.org>
 @license  MIT
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(r){var c=0;return function(){return c<r.length?{done:!1,value:r[c++]}:{done:!0}}};$jscomp.arrayIterator=function(r){return{next:$jscomp.arrayIteratorImpl(r)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(r,c,k){r!=Array.prototype&&r!=Object.prototype&&(r[c]=k.value)};$jscomp.getGlobal=function(r){return"undefined"!=typeof window&&window===r?r:"undefined"!=typeof global&&null!=global?global:r};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(r,c){this.$jscomp$symbol$id_=r;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:c})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function r(k){if(this instanceof r)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(k||"")+"_"+c++,k)}var c=0;return r}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var r=$jscomp.global.Symbol.iterator;r||(r=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[r]&&$jscomp.defineProperty(Array.prototype,r,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var r=$jscomp.global.Symbol.asyncIterator;r||(r=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(r){$jscomp.initSymbolIterator();r={next:r};r[$jscomp.global.Symbol.iterator]=function(){return this};return r};
$jscomp.iteratorFromArray=function(r,c){$jscomp.initSymbolIterator();r instanceof String&&(r+="");var k=0,f={next:function(){if(k<r.length){var e=k++;return{value:c(e,r[e]),done:!1}}f.next=function(){return{done:!0,value:void 0}};return f.next()}};f[Symbol.iterator]=function(){return f};return f};
$jscomp.polyfill=function(r,c,k,f){if(c){k=$jscomp.global;r=r.split(".");for(f=0;f<r.length-1;f++){var e=r[f];e in k||(k[e]={});k=k[e]}r=r[r.length-1];f=k[r];c=c(f);c!=f&&null!=c&&$jscomp.defineProperty(k,r,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.keys",function(r){return r?r:function(){return $jscomp.iteratorFromArray(this,function(c){return c})}},"es6","es3");
$jscomp.polyfill("Array.prototype.fill",function(r){return r?r:function(c,k,f){var e=this.length||0;0>k&&(k=Math.max(0,e+k));if(null==f||f>e)f=e;f=Number(f);0>f&&(f=Math.max(0,e+f));for(k=Number(k||0);k<f;k++)this[k]=c;return this}},"es6","es3");
$jscomp.checkStringArgs=function(r,c,k){if(null==r)throw new TypeError("The 'this' value for String.prototype."+k+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+k+" must not be a regular expression");return r+""};
$jscomp.polyfill("String.prototype.repeat",function(r){return r?r:function(c){var k=$jscomp.checkStringArgs(this,null,"repeat");if(0>c||1342177279<c)throw new RangeError("Invalid count value");c|=0;for(var f="";c;)if(c&1&&(f+=k),c>>>=1)k+=k;return f}},"es6","es3");
(function(r){"object"===typeof exports&&"undefined"!==typeof module?module.exports=r():"function"===typeof define&&define.amd?define([],r):("undefined"!==typeof window?window:"undefined"!==typeof global?global:"undefined"!==typeof self?self:this).Cipher=r()})(function(){return function e(c,k,f){function b(d,a){if(!k[d]){if(!c[d]){var h="function"==typeof require&&require;if(!a&&h)return h(d,!0);if(g)return g(d,!0);a=Error("Cannot find module '"+d+"'");throw a.code="MODULE_NOT_FOUND",a;}a=k[d]={exports:{}};
c[d][0].call(a.exports,function(a){var h=c[d][1][a];return b(h?h:a)},a,a.exports,e,c,k,f)}return k[d].exports}for(var g="function"==typeof require&&require,a=0;a<f.length;a++)b(f[a]);return b}({1:[function(c,k,f){function e(b,l,m){b=b.toLowerCase();if(d[b])return a.createCipheriv(b,l,m);if(h[b])return new g({key:l,iv:m,mode:b});throw new TypeError("invalid suite type");}function b(b,l,m){b=b.toLowerCase();if(d[b])return a.createDecipheriv(b,l,m);if(h[b])return new g({key:l,iv:m,mode:b,decrypt:!0});
throw new TypeError("invalid suite type");}var g=c("browserify-des"),a=c("browserify-aes/browser"),d=c("browserify-aes/modes"),h=c("browserify-des/modes"),m=c("evp_bytestokey");f.createCipher=f.Cipher=function(a,b){a=a.toLowerCase();if(d[a]){var l=d[a].key;var p=d[a].iv}else if(h[a])l=8*h[a].key,p=h[a].iv;else throw new TypeError("invalid suite type");b=m(b,!1,l,p);return e(a,b.key,b.iv)};f.createCipheriv=f.Cipheriv=e;f.createDecipher=f.Decipher=function(a,l){a=a.toLowerCase();if(d[a]){var u=d[a].key;
var p=d[a].iv}else if(h[a])u=8*h[a].key,p=h[a].iv;else throw new TypeError("invalid suite type");l=m(l,!1,u,p);return b(a,l.key,l.iv)};f.createDecipheriv=f.Decipheriv=b;f.listCiphers=f.getCiphers=function(){return Object.keys(h).concat(a.getCiphers())}},{"browserify-aes/browser":4,"browserify-aes/modes":15,"browserify-des":23,"browserify-des/modes":24,evp_bytestokey:35}],2:[function(c,k,f){function e(a){d.isBuffer(a)||(a=d.from(a));for(var b=a.length/4|0,h=Array(b),p=0;p<b;p++)h[p]=a.readUInt32BE(4*
p);return h}function b(d){for(;0<d.length;d++)d[0]=0}function g(d,a,b,h,m){var p=b[0],l=b[1],c=b[2];b=b[3];for(var e=d[0]^a[0],g=d[1]^a[1],u=d[2]^a[2],n=d[3]^a[3],t,f,k=4,I=1;I<m;I++)d=p[e>>>24]^l[g>>>16&255]^c[u>>>8&255]^b[n&255]^a[k++],t=p[g>>>24]^l[u>>>16&255]^c[n>>>8&255]^b[e&255]^a[k++],f=p[u>>>24]^l[n>>>16&255]^c[e>>>8&255]^b[g&255]^a[k++],n=p[n>>>24]^l[e>>>16&255]^c[g>>>8&255]^b[u&255]^a[k++],e=d,g=t,u=f;d=(h[e>>>24]<<24|h[g>>>16&255]<<16|h[u>>>8&255]<<8|h[n&255])^a[k++];t=(h[g>>>24]<<24|h[u>>>
16&255]<<16|h[n>>>8&255]<<8|h[e&255])^a[k++];f=(h[u>>>24]<<24|h[n>>>16&255]<<16|h[e>>>8&255]<<8|h[g&255])^a[k++];n=(h[n>>>24]<<24|h[e>>>16&255]<<16|h[g>>>8&255]<<8|h[u&255])^a[k++];return[d>>>0,t>>>0,f>>>0,n>>>0]}function a(d){this._key=e(d);this._reset()}var d=c("safe-buffer").Buffer,h=[0,1,2,4,8,16,32,64,128,27,54],m=function(){for(var d=Array(256),a=0;256>a;a++)d[a]=128>a?a<<1:a<<1^283;a=[];for(var b=[],h=[[],[],[],[]],m=[[],[],[],[]],c=0,e=0,g=0;256>g;++g){var f=e^e<<1^e<<2^e<<3^e<<4;f=f>>>8^
f&255^99;a[c]=f;b[f]=c;var k=d[c],D=d[k],G=d[D],y=257*d[f]^16843008*f;h[0][c]=y<<24|y>>>8;h[1][c]=y<<16|y>>>16;h[2][c]=y<<8|y>>>24;h[3][c]=y;y=16843009*G^65537*D^257*k^16843008*c;m[0][f]=y<<24|y>>>8;m[1][f]=y<<16|y>>>16;m[2][f]=y<<8|y>>>24;m[3][f]=y;0===c?c=e=1:(c=k^d[d[d[G^k]]],e^=d[d[e]])}return{SBOX:a,INV_SBOX:b,SUB_MIX:h,INV_SUB_MIX:m}}();a.blockSize=16;a.keySize=32;a.prototype.blockSize=a.blockSize;a.prototype.keySize=a.keySize;a.prototype._reset=function(){for(var d=this._key,a=d.length,b=a+
6,p=4*(b+1),c=[],e=0;e<a;e++)c[e]=d[e];for(e=a;e<p;e++)d=c[e-1],0===e%a?(d=d<<8|d>>>24,d=m.SBOX[d>>>24]<<24|m.SBOX[d>>>16&255]<<16|m.SBOX[d>>>8&255]<<8|m.SBOX[d&255],d^=h[e/a|0]<<24):6<a&&4===e%a&&(d=m.SBOX[d>>>24]<<24|m.SBOX[d>>>16&255]<<16|m.SBOX[d>>>8&255]<<8|m.SBOX[d&255]),c[e]=c[e-a]^d;a=[];for(e=0;e<p;e++){d=p-e;var g=c[d-(e%4?0:4)];a[e]=4>e||4>=d?g:m.INV_SUB_MIX[0][m.SBOX[g>>>24]]^m.INV_SUB_MIX[1][m.SBOX[g>>>16&255]]^m.INV_SUB_MIX[2][m.SBOX[g>>>8&255]]^m.INV_SUB_MIX[3][m.SBOX[g&255]]}this._nRounds=
b;this._keySchedule=c;this._invKeySchedule=a};a.prototype.encryptBlockRaw=function(d){d=e(d);return g(d,this._keySchedule,m.SUB_MIX,m.SBOX,this._nRounds)};a.prototype.encryptBlock=function(a){a=this.encryptBlockRaw(a);var b=d.allocUnsafe(16);b.writeUInt32BE(a[0],0);b.writeUInt32BE(a[1],4);b.writeUInt32BE(a[2],8);b.writeUInt32BE(a[3],12);return b};a.prototype.decryptBlock=function(a){a=e(a);var b=a[1];a[1]=a[3];a[3]=b;a=g(a,this._invKeySchedule,m.INV_SUB_MIX,m.INV_SBOX,this._nRounds);b=d.allocUnsafe(16);
b.writeUInt32BE(a[0],0);b.writeUInt32BE(a[3],4);b.writeUInt32BE(a[2],8);b.writeUInt32BE(a[1],12);return b};a.prototype.scrub=function(){b(this._keySchedule);b(this._invKeySchedule);b(this._key)};k.exports.AES=a},{"safe-buffer":21}],3:[function(c,k,f){function e(h,e,c,p){a.call(this);var l=g.alloc(4,0);this._cipher=new b.AES(e);l=this._cipher.encryptBlock(l);this._ghash=new d(l);e=c;if(12===e.length)this._finID=g.concat([e,g.from([0,0,0,1])]),c=g.concat([e,g.from([0,0,0,2])]);else{c=new d(l);l=e.length;
var n=l%16;c.update(e);n&&c.update(g.alloc(16-n,0));c.update(g.alloc(8,0));e=8*l;l=g.alloc(8);l.writeUIntBE(e,0,8);c.update(l);this._finID=c.state;c=g.from(this._finID);m(c)}this._prev=g.from(c);this._cache=g.allocUnsafe(0);this._secCache=g.allocUnsafe(0);this._decrypt=p;this._len=this._alen=0;this._mode=h;this._authTag=null;this._called=!1}var b=c("./aes"),g=c("safe-buffer").Buffer,a=c("cipher-base");f=c("inherits");var d=c("./ghash"),h=c("buffer-xor"),m=c("./incr32");f(e,a);e.prototype._update=
function(d){if(!this._called&&this._alen){var a=16-this._alen%16;16>a&&(a=g.alloc(a,0),this._ghash.update(a))}this._called=!0;a=this._mode.encrypt(this,d);this._decrypt?this._ghash.update(d):this._ghash.update(a);this._len+=d.length;return a};e.prototype._final=function(){if(this._decrypt&&!this._authTag)throw Error("Unsupported state or unable to authenticate data");var d=h(this._ghash.final(8*this._alen,8*this._len),this._cipher.encryptBlock(this._finID)),a;if(a=this._decrypt){a=this._authTag;var b=
0;d.length!==a.length&&b++;for(var m=Math.min(d.length,a.length),e=0;e<m;++e)b+=d[e]^a[e];a=b}if(a)throw Error("Unsupported state or unable to authenticate data");this._authTag=d;this._cipher.scrub()};e.prototype.getAuthTag=function(){if(this._decrypt||!g.isBuffer(this._authTag))throw Error("Attempting to get auth tag in unsupported state");return this._authTag};e.prototype.setAuthTag=function(d){if(!this._decrypt)throw Error("Attempting to set auth tag in unsupported state");this._authTag=d};e.prototype.setAAD=
function(d){if(this._called)throw Error("Attempting to set AAD in unsupported state");this._ghash.update(d);this._alen+=d.length};k.exports=e},{"./aes":2,"./ghash":7,"./incr32":8,"buffer-xor":18,"cipher-base":19,inherits:20,"safe-buffer":21}],4:[function(c,k,f){k=c("./encrypter");var e=c("./decrypter"),b=c("./modes/list.json");f.createCipher=f.Cipher=k.createCipher;f.createCipheriv=f.Cipheriv=k.createCipheriv;f.createDecipher=f.Decipher=e.createDecipher;f.createDecipheriv=f.Decipheriv=e.createDecipheriv;
f.listCiphers=f.getCiphers=function(){return Object.keys(b)}},{"./decrypter":5,"./encrypter":6,"./modes/list.json":16}],5:[function(c,k,f){function e(a,h,m){u.call(this);this._cache=new b;this._last=void 0;this._cipher=new l.AES(h);this._prev=d.from(m);this._mode=a;this._autopadding=!0}function b(){this.cache=d.allocUnsafe(0)}function g(b,c,g){b=h[b.toLowerCase()];if(!b)throw new TypeError("invalid suite type");"string"===typeof g&&(g=d.from(g));if("GCM"!==b.mode&&g.length!==b.iv)throw new TypeError("invalid iv length "+
g.length);"string"===typeof c&&(c=d.from(c));if(c.length!==b.key/8)throw new TypeError("invalid key length "+c.length);return"stream"===b.type?new m(b.module,c,g,!0):"auth"===b.type?new a(b.module,c,g,!0):new e(b.module,c,g)}var a=c("./authCipher"),d=c("safe-buffer").Buffer,h=c("./modes"),m=c("./streamCipher"),u=c("cipher-base"),l=c("./aes"),n=c("evp_bytestokey");c("inherits")(e,u);e.prototype._update=function(a){this._cache.add(a);var b;for(a=[];b=this._cache.get(this._autopadding);)b=this._mode.decrypt(this,
b),a.push(b);return d.concat(a)};e.prototype._final=function(){var a=this._cache.flush();if(this._autopadding){a=this._mode.decrypt(this,a);var d=a[15];if(1>d||16<d)throw Error("unable to decrypt data");for(var b=-1;++b<d;)if(a[b+(16-d)]!==d)throw Error("unable to decrypt data");a=16===d?void 0:a.slice(0,16-d);return a}if(a)throw Error("data not multiple of block length");};e.prototype.setAutoPadding=function(a){this._autopadding=!!a;return this};b.prototype.add=function(a){this.cache=d.concat([this.cache,
a])};b.prototype.get=function(a){if(a){if(16<this.cache.length)return a=this.cache.slice(0,16),this.cache=this.cache.slice(16),a}else if(16<=this.cache.length)return a=this.cache.slice(0,16),this.cache=this.cache.slice(16),a;return null};b.prototype.flush=function(){if(this.cache.length)return this.cache};f.createDecipher=function(a,d){var b=h[a.toLowerCase()];if(!b)throw new TypeError("invalid suite type");d=n(d,!1,b.key,b.iv);return g(a,d.key,d.iv)};f.createDecipheriv=g},{"./aes":2,"./authCipher":3,
"./modes":15,"./streamCipher":22,"cipher-base":19,evp_bytestokey:35,inherits:20,"safe-buffer":21}],6:[function(c,k,f){function e(a,d,m){u.call(this);this._cache=new b;this._cipher=new l.AES(d);this._prev=h.from(m);this._mode=a;this._autopadding=!0}function b(){this.cache=h.allocUnsafe(0)}function g(b,c,g){b=a[b.toLowerCase()];if(!b)throw new TypeError("invalid suite type");"string"===typeof c&&(c=h.from(c));if(c.length!==b.key/8)throw new TypeError("invalid key length "+c.length);"string"===typeof g&&
(g=h.from(g));if("GCM"!==b.mode&&g.length!==b.iv)throw new TypeError("invalid iv length "+g.length);return"stream"===b.type?new m(b.module,c,g):"auth"===b.type?new d(b.module,c,g):new e(b.module,c,g)}var a=c("./modes"),d=c("./authCipher"),h=c("safe-buffer").Buffer,m=c("./streamCipher"),u=c("cipher-base"),l=c("./aes"),n=c("evp_bytestokey");c("inherits")(e,u);e.prototype._update=function(a){this._cache.add(a);var d;for(a=[];d=this._cache.get();)d=this._mode.encrypt(this,d),a.push(d);return h.concat(a)};
var p=h.alloc(16,16);e.prototype._final=function(){var a=this._cache.flush();if(this._autopadding)return a=this._mode.encrypt(this,a),this._cipher.scrub(),a;if(!a.equals(p))throw this._cipher.scrub(),Error("data not multiple of block length");};e.prototype.setAutoPadding=function(a){this._autopadding=!!a;return this};b.prototype.add=function(a){this.cache=h.concat([this.cache,a])};b.prototype.get=function(){if(15<this.cache.length){var a=this.cache.slice(0,16);this.cache=this.cache.slice(16);return a}return null};
b.prototype.flush=function(){for(var a=16-this.cache.length,d=h.allocUnsafe(a),b=-1;++b<a;)d.writeUInt8(a,b);return h.concat([this.cache,d])};f.createCipheriv=g;f.createCipher=function(d,b){var h=a[d.toLowerCase()];if(!h)throw new TypeError("invalid suite type");b=n(b,!1,h.key,h.iv);return g(d,b.key,b.iv)}},{"./aes":2,"./authCipher":3,"./modes":15,"./streamCipher":22,"cipher-base":19,evp_bytestokey:35,inherits:20,"safe-buffer":21}],7:[function(c,k,f){function e(a){var d=g.allocUnsafe(16);d.writeUInt32BE(a[0]>>>
0,0);d.writeUInt32BE(a[1]>>>0,4);d.writeUInt32BE(a[2]>>>0,8);d.writeUInt32BE(a[3]>>>0,12);return d}function b(a){this.h=a;this.state=g.alloc(16,0);this.cache=g.allocUnsafe(0)}var g=c("safe-buffer").Buffer,a=g.alloc(16,0);b.prototype.ghash=function(a){for(var d=-1;++d<a.length;)this.state[d]^=a[d];this._multiply()};b.prototype._multiply=function(){var a=this.h;a=[a.readUInt32BE(0),a.readUInt32BE(4),a.readUInt32BE(8),a.readUInt32BE(12)];for(var b=[0,0,0,0],m,c,g=-1;128>++g;){if(m=0!==(this.state[~~(g/
8)]&1<<7-g%8))b[0]^=a[0],b[1]^=a[1],b[2]^=a[2],b[3]^=a[3];c=0!==(a[3]&1);for(m=3;0<m;m--)a[m]=a[m]>>>1|(a[m-1]&1)<<31;a[0]>>>=1;c&&(a[0]^=-520093696)}this.state=e(b)};b.prototype.update=function(a){for(this.cache=g.concat([this.cache,a]);16<=this.cache.length;)a=this.cache.slice(0,16),this.cache=this.cache.slice(16),this.ghash(a)};b.prototype.final=function(d,b){this.cache.length&&this.ghash(g.concat([this.cache,a],16));this.ghash(e([0,d,0,b]));return this.state};k.exports=b},{"safe-buffer":21}],
8:[function(c,k,f){k.exports=function(c){for(var b=c.length,e;b--;)if(e=c.readUInt8(b),255===e)c.writeUInt8(0,b);else{e++;c.writeUInt8(e,b);break}}},{}],9:[function(c,k,f){var e=c("buffer-xor");f.encrypt=function(b,c){c=e(c,b._prev);b._prev=b._cipher.encryptBlock(c);return b._prev};f.decrypt=function(b,c){var a=b._prev;b._prev=c;b=b._cipher.decryptBlock(c);return e(b,a)}},{"buffer-xor":18}],10:[function(c,k,f){function e(a,d,h){var c=d.length,e=g(d,a._cache);a._cache=a._cache.slice(c);a._prev=b.concat([a._prev,
h?d:e]);return e}var b=c("safe-buffer").Buffer,g=c("buffer-xor");f.encrypt=function(a,d,h){for(var c=b.allocUnsafe(0),g;d.length;)if(0===a._cache.length&&(a._cache=a._cipher.encryptBlock(a._prev),a._prev=b.allocUnsafe(0)),a._cache.length<=d.length)g=a._cache.length,c=b.concat([c,e(a,d.slice(0,g),h)]),d=d.slice(g);else{c=b.concat([c,e(a,d,h)]);break}return c}},{"buffer-xor":18,"safe-buffer":21}],11:[function(c,k,f){var e=c("safe-buffer").Buffer;f.encrypt=function(b,c,a){for(var d=c.length,h=e.allocUnsafe(d),
m=-1;++m<d;){for(var g=m,l,n,p,f=b,k=c[m],x=a,v=-1,A=0;8>++v;){p=f._cipher.encryptBlock(f._prev);n=k&1<<7-v?128:0;l=p[0]^n;A+=(l&128)>>v%8;p=f;var C=f._prev;n=x?n:l;l=C.length;var D=-1,G=e.allocUnsafe(C.length);for(C=e.concat([C,e.from([n])]);++D<l;)G[D]=C[D]<<1|C[D+1]>>7;p._prev=G}h[g]=A}return h}},{"safe-buffer":21}],12:[function(c,k,f){var e=c("safe-buffer").Buffer;f.encrypt=function(b,c,a){for(var d=c.length,h=e.allocUnsafe(d),m=-1;++m<d;){var g=m,l=b,n=c[m],p=a,f=l._cipher.encryptBlock(l._prev)[0]^
n;l._prev=e.concat([l._prev.slice(1),e.from([p?n:f])]);h[g]=f}return h}},{"safe-buffer":21}],13:[function(c,k,f){var e=c("buffer-xor"),b=c("safe-buffer").Buffer,g=c("../incr32");f.encrypt=function(a,d){var h=Math.ceil(d.length/16),c=a._cache.length;a._cache=b.concat([a._cache,b.allocUnsafe(16*h)]);for(var f=0;f<h;f++){var l=a;var n=l._cipher.encryptBlockRaw(l._prev);g(l._prev);l=n;n=c+16*f;a._cache.writeUInt32BE(l[0],n+0);a._cache.writeUInt32BE(l[1],n+4);a._cache.writeUInt32BE(l[2],n+8);a._cache.writeUInt32BE(l[3],
n+12)}h=a._cache.slice(0,d.length);a._cache=a._cache.slice(d.length);return e(d,h)}},{"../incr32":8,"buffer-xor":18,"safe-buffer":21}],14:[function(c,k,f){f.encrypt=function(c,b){return c._cipher.encryptBlock(b)};f.decrypt=function(c,b){return c._cipher.decryptBlock(b)}},{}],15:[function(c,k,f){f={ECB:c("./ecb"),CBC:c("./cbc"),CFB:c("./cfb"),CFB8:c("./cfb8"),CFB1:c("./cfb1"),OFB:c("./ofb"),CTR:c("./ctr"),GCM:c("./ctr")};c=c("./list.json");for(var e in c)c[e].module=f[c[e].mode];k.exports=c},{"./cbc":9,
"./cfb":10,"./cfb1":11,"./cfb8":12,"./ctr":13,"./ecb":14,"./list.json":16,"./ofb":17}],16:[function(c,k,f){k.exports={"aes-128-ecb":{cipher:"AES",key:128,iv:0,mode:"ECB",type:"block"},"aes-192-ecb":{cipher:"AES",key:192,iv:0,mode:"ECB",type:"block"},"aes-256-ecb":{cipher:"AES",key:256,iv:0,mode:"ECB",type:"block"},"aes-128-cbc":{cipher:"AES",key:128,iv:16,mode:"CBC",type:"block"},"aes-192-cbc":{cipher:"AES",key:192,iv:16,mode:"CBC",type:"block"},"aes-256-cbc":{cipher:"AES",key:256,iv:16,mode:"CBC",
type:"block"},aes128:{cipher:"AES",key:128,iv:16,mode:"CBC",type:"block"},aes192:{cipher:"AES",key:192,iv:16,mode:"CBC",type:"block"},aes256:{cipher:"AES",key:256,iv:16,mode:"CBC",type:"block"},"aes-128-cfb":{cipher:"AES",key:128,iv:16,mode:"CFB",type:"stream"},"aes-192-cfb":{cipher:"AES",key:192,iv:16,mode:"CFB",type:"stream"},"aes-256-cfb":{cipher:"AES",key:256,iv:16,mode:"CFB",type:"stream"},"aes-128-cfb8":{cipher:"AES",key:128,iv:16,mode:"CFB8",type:"stream"},"aes-192-cfb8":{cipher:"AES",key:192,
iv:16,mode:"CFB8",type:"stream"},"aes-256-cfb8":{cipher:"AES",key:256,iv:16,mode:"CFB8",type:"stream"},"aes-128-cfb1":{cipher:"AES",key:128,iv:16,mode:"CFB1",type:"stream"},"aes-192-cfb1":{cipher:"AES",key:192,iv:16,mode:"CFB1",type:"stream"},"aes-256-cfb1":{cipher:"AES",key:256,iv:16,mode:"CFB1",type:"stream"},"aes-128-ofb":{cipher:"AES",key:128,iv:16,mode:"OFB",type:"stream"},"aes-192-ofb":{cipher:"AES",key:192,iv:16,mode:"OFB",type:"stream"},"aes-256-ofb":{cipher:"AES",key:256,iv:16,mode:"OFB",
type:"stream"},"aes-128-ctr":{cipher:"AES",key:128,iv:16,mode:"CTR",type:"stream"},"aes-192-ctr":{cipher:"AES",key:192,iv:16,mode:"CTR",type:"stream"},"aes-256-ctr":{cipher:"AES",key:256,iv:16,mode:"CTR",type:"stream"},"aes-128-gcm":{cipher:"AES",key:128,iv:12,mode:"GCM",type:"auth"},"aes-192-gcm":{cipher:"AES",key:192,iv:12,mode:"GCM",type:"auth"},"aes-256-gcm":{cipher:"AES",key:256,iv:12,mode:"GCM",type:"auth"}}},{}],17:[function(c,k,f){(function(e){function b(a){a._prev=a._cipher.encryptBlock(a._prev);
return a._prev}var g=c("buffer-xor");f.encrypt=function(a,d){for(;a._cache.length<d.length;)a._cache=e.concat([a._cache,b(a)]);var h=a._cache.slice(0,d.length);a._cache=a._cache.slice(d.length);return g(d,h)}}).call(this,c("buffer").Buffer)},{buffer:41,"buffer-xor":18}],18:[function(c,k,f){(function(c){k.exports=function(b,e){for(var a=Math.min(b.length,e.length),d=new c(a),h=0;h<a;++h)d[h]=b[h]^e[h];return d}}).call(this,c("buffer").Buffer)},{buffer:41}],19:[function(c,k,f){function e(a){g.call(this);
(this.hashMode="string"===typeof a)?this[a]=this._finalOrDigest:this.final=this._finalOrDigest;this._final&&(this.__final=this._final,this._final=null);this._encoding=this._decoder=null}var b=c("safe-buffer").Buffer,g=c("stream").Transform,a=c("string_decoder").StringDecoder;c("inherits")(e,g);e.prototype.update=function(a,h,c){"string"===typeof a&&(a=b.from(a,h));a=this._update(a);if(this.hashMode)return this;c&&(a=this._toString(a,c));return a};e.prototype.setAutoPadding=function(){};e.prototype.getAuthTag=
function(){throw Error("trying to get auth tag in unsupported state");};e.prototype.setAuthTag=function(){throw Error("trying to set auth tag in unsupported state");};e.prototype.setAAD=function(){throw Error("trying to set aad in unsupported state");};e.prototype._transform=function(a,b,c){try{this.hashMode?this._update(a):this.push(this._update(a))}catch(l){var d=l}finally{c(d)}};e.prototype._flush=function(a){try{this.push(this.__final())}catch(m){var d=m}a(d)};e.prototype._finalOrDigest=function(a){var d=
this.__final()||b.alloc(0);a&&(d=this._toString(d,a,!0));return d};e.prototype._toString=function(d,b,c){this._decoder||(this._decoder=new a(b),this._encoding=b);if(this._encoding!==b)throw Error("can't switch encodings");d=this._decoder.write(d);c&&(d+=this._decoder.end());return d};k.exports=e},{inherits:20,"safe-buffer":21,stream:66,string_decoder:67}],20:[function(c,k,f){k.exports="function"===typeof Object.create?function(c,b){b&&(c.super_=b,c.prototype=Object.create(b.prototype,{constructor:{value:c,
enumerable:!1,writable:!0,configurable:!0}}))}:function(c,b){if(b){c.super_=b;var e=function(){};e.prototype=b.prototype;c.prototype=new e;c.prototype.constructor=c}}},{}],21:[function(c,k,f){function e(a,b){for(var d in a)b[d]=a[d]}function b(d,b,c){return a(d,b,c)}var g=c("buffer"),a=g.Buffer;a.from&&a.alloc&&a.allocUnsafe&&a.allocUnsafeSlow?k.exports=g:(e(g,f),f.Buffer=b);b.prototype=Object.create(a.prototype);e(a,b);b.from=function(d,b,c){if("number"===typeof d)throw new TypeError("Argument must not be a number");
return a(d,b,c)};b.alloc=function(d,b,c){if("number"!==typeof d)throw new TypeError("Argument must be a number");d=a(d);void 0!==b?"string"===typeof c?d.fill(b,c):d.fill(b):d.fill(0);return d};b.allocUnsafe=function(d){if("number"!==typeof d)throw new TypeError("Argument must be a number");return a(d)};b.allocUnsafeSlow=function(a){if("number"!==typeof a)throw new TypeError("Argument must be a number");return g.SlowBuffer(a)}},{buffer:41}],22:[function(c,k,f){function e(d,c,e,f){a.call(this);this._cipher=
new b.AES(c);this._prev=g.from(e);this._cache=g.allocUnsafe(0);this._secCache=g.allocUnsafe(0);this._decrypt=f;this._mode=d}var b=c("./aes"),g=c("safe-buffer").Buffer,a=c("cipher-base");c("inherits")(e,a);e.prototype._update=function(a){return this._mode.encrypt(this,a,this._decrypt)};e.prototype._final=function(){this._cipher.scrub()};k.exports=e},{"./aes":2,"cipher-base":19,inherits:20,"safe-buffer":21}],23:[function(c,k,f){function e(c){b.call(this);var h=c.mode.toLowerCase(),e=d[h];var g=c.decrypt?
"decrypt":"encrypt";var n=c.key;a.isBuffer(n)||(n=a.from(n));if("des-ede"===h||"des-ede-cbc"===h)n=a.concat([n,n.slice(0,8)]);c=c.iv;a.isBuffer(c)||(c=a.from(c));this._des=e.create({key:n,iv:c,type:g})}var b=c("cipher-base");f=c("des.js");var g=c("inherits"),a=c("safe-buffer").Buffer,d={"des-ede3-cbc":f.CBC.instantiate(f.EDE),"des-ede3":f.EDE,"des-ede-cbc":f.CBC.instantiate(f.EDE),"des-ede":f.EDE,"des-cbc":f.CBC.instantiate(f.DES),"des-ecb":f.DES};d.des=d["des-cbc"];d.des3=d["des-ede3-cbc"];k.exports=
e;g(e,b);e.prototype._update=function(d){return a.from(this._des.update(d))};e.prototype._final=function(){return a.from(this._des.final())}},{"cipher-base":25,"des.js":26,inherits:33,"safe-buffer":34}],24:[function(c,k,f){f["des-ecb"]={key:8,iv:0};f["des-cbc"]=f.des={key:8,iv:8};f["des-ede3-cbc"]=f.des3={key:24,iv:8};f["des-ede3"]={key:24,iv:0};f["des-ede-cbc"]={key:16,iv:8};f["des-ede"]={key:16,iv:0}},{}],25:[function(c,k,f){arguments[4][19][0].apply(f,arguments)},{dup:19,inherits:33,"safe-buffer":34,
stream:66,string_decoder:67}],26:[function(c,k,f){f.utils=c("./des/utils");f.Cipher=c("./des/cipher");f.DES=c("./des/des");f.CBC=c("./des/cbc");f.EDE=c("./des/ede")},{"./des/cbc":27,"./des/cipher":28,"./des/des":29,"./des/ede":30,"./des/utils":31}],27:[function(c,k,f){function e(a){b.equal(a.length,8,"Invalid IV length");this.iv=Array(8);for(var d=0;d<this.iv.length;d++)this.iv[d]=a[d]}var b=c("minimalistic-assert"),g=c("inherits"),a={};f.instantiate=function(d){function b(a){d.call(this,a);this._cbcInit()}
g(b,d);for(var c=Object.keys(a),e=0;e<c.length;e++){var l=c[e];b.prototype[l]=a[l]}b.create=function(a){return new b(a)};return b};a._cbcInit=function(){this._cbcState=new e(this.options.iv)};a._update=function(a,b,c,e){var d=this.constructor.super_.prototype,h=this._cbcState.iv;if("encrypt"===this.type){for(var g=0;g<this.blockSize;g++)h[g]^=a[b+g];d._update.call(this,h,0,c,e);for(g=0;g<this.blockSize;g++)h[g]=c[e+g]}else{d._update.call(this,a,b,c,e);for(g=0;g<this.blockSize;g++)c[e+g]^=h[g];for(g=
0;g<this.blockSize;g++)h[g]=a[b+g]}}},{inherits:33,"minimalistic-assert":32}],28:[function(c,k,f){function e(b){this.options=b;this.type=this.options.type;this.blockSize=8;this._init();this.buffer=Array(this.blockSize);this.bufferOff=0}var b=c("minimalistic-assert");k.exports=e;e.prototype._init=function(){};e.prototype.update=function(b){return 0===b.length?[]:"decrypt"===this.type?this._updateDecrypt(b):this._updateEncrypt(b)};e.prototype._buffer=function(b,a){for(var d=Math.min(this.buffer.length-
this.bufferOff,b.length-a),c=0;c<d;c++)this.buffer[this.bufferOff+c]=b[a+c];this.bufferOff+=d;return d};e.prototype._flushBuffer=function(b,a){this._update(this.buffer,0,b,a);this.bufferOff=0;return this.blockSize};e.prototype._updateEncrypt=function(b){var a=0,d=0,c=Array(((this.bufferOff+b.length)/this.blockSize|0)*this.blockSize);0!==this.bufferOff&&(a+=this._buffer(b,a),this.bufferOff===this.buffer.length&&(d+=this._flushBuffer(c,d)));for(var e=b.length-(b.length-a)%this.blockSize;a<e;a+=this.blockSize)this._update(b,
a,c,d),d+=this.blockSize;for(;a<b.length;a++,this.bufferOff++)this.buffer[this.bufferOff]=b[a];return c};e.prototype._updateDecrypt=function(b){for(var a=0,d=0,c=Math.ceil((this.bufferOff+b.length)/this.blockSize)-1,e=Array(c*this.blockSize);0<c;c--)a+=this._buffer(b,a),d+=this._flushBuffer(e,d);this._buffer(b,a);return e};e.prototype.final=function(b){var a;b&&(a=this.update(b));b="encrypt"===this.type?this._finalEncrypt():this._finalDecrypt();return a?a.concat(b):b};e.prototype._pad=function(b,
a){if(0===a)return!1;for(;a<b.length;)b[a++]=0;return!0};e.prototype._finalEncrypt=function(){if(!this._pad(this.buffer,this.bufferOff))return[];var b=Array(this.blockSize);this._update(this.buffer,0,b,0);return b};e.prototype._unpad=function(b){return b};e.prototype._finalDecrypt=function(){b.equal(this.bufferOff,this.blockSize,"Not enough data to decrypt");var c=Array(this.blockSize);this._flushBuffer(c,0);return this._unpad(c)}},{"minimalistic-assert":32}],29:[function(c,k,f){function e(){this.tmp=
Array(2);this.keys=null}function b(a){d.call(this,a);var b=new e;this._desState=b;this.deriveKeys(b,a.key)}var g=c("minimalistic-assert");f=c("inherits");c=c("../des");var a=c.utils,d=c.Cipher;f(b,d);k.exports=b;b.create=function(a){return new b(a)};var h=[1,1,2,2,2,2,2,2,1,2,2,2,2,2,2,1];b.prototype.deriveKeys=function(b,d){b.keys=Array(32);g.equal(d.length,this.blockSize,"Invalid key length");var c=a.readUInt32BE(d,0);d=a.readUInt32BE(d,4);a.pc1(c,d,b.tmp,0);c=b.tmp[0];d=b.tmp[1];for(var e=0;e<
b.keys.length;e+=2){var m=h[e>>>1];c=a.r28shl(c,m);d=a.r28shl(d,m);a.pc2(c,d,b.keys,e)}};b.prototype._update=function(b,d,c,e){var h=this._desState,g=a.readUInt32BE(b,d);b=a.readUInt32BE(b,d+4);a.ip(g,b,h.tmp,0);g=h.tmp[0];b=h.tmp[1];"encrypt"===this.type?this._encrypt(h,g,b,h.tmp,0):this._decrypt(h,g,b,h.tmp,0);g=h.tmp[0];b=h.tmp[1];a.writeUInt32BE(c,g,e);a.writeUInt32BE(c,b,e+4)};b.prototype._pad=function(a,b){for(var d=a.length-b;b<a.length;b++)a[b]=d;return!0};b.prototype._unpad=function(a){for(var b=
a[a.length-1],d=a.length-b;d<a.length;d++)g.equal(a[d],b);return a.slice(0,a.length-b)};b.prototype._encrypt=function(b,d,c,e,h){for(var g=0;g<b.keys.length;g+=2){var m=b.keys[g],f=b.keys[g+1];a.expand(c,b.tmp,0);m^=b.tmp[0];f^=b.tmp[1];m=a.substitute(m,f);m=a.permute(m);f=c;c=(d^m)>>>0;d=f}a.rip(c,d,e,h)};b.prototype._decrypt=function(b,d,c,e,h){for(var g=b.keys.length-2;0<=g;g-=2){var m=b.keys[g],f=b.keys[g+1];a.expand(c,b.tmp,0);m^=b.tmp[0];f^=b.tmp[1];m=a.substitute(m,f);m=a.permute(m);f=c;c=
(d^m)>>>0;d=f}a.rip(c,d,e,h)}},{"../des":26,inherits:33,"minimalistic-assert":32}],30:[function(c,k,f){function e(a,b){g.equal(b.length,24,"Invalid key length");var c=b.slice(0,8),e=b.slice(8,16);b=b.slice(16,24);this.ciphers="encrypt"===a?[d.create({type:"encrypt",key:c}),d.create({type:"decrypt",key:e}),d.create({type:"encrypt",key:b})]:[d.create({type:"decrypt",key:b}),d.create({type:"encrypt",key:e}),d.create({type:"decrypt",key:c})]}function b(b){a.call(this,b);this._edeState=new e(this.type,
this.options.key)}var g=c("minimalistic-assert");f=c("inherits");c=c("../des");var a=c.Cipher,d=c.DES;f(b,a);k.exports=b;b.create=function(a){return new b(a)};b.prototype._update=function(a,b,d,c){var e=this._edeState;e.ciphers[0]._update(a,b,d,c);e.ciphers[1]._update(d,c,d,c);e.ciphers[2]._update(d,c,d,c)};b.prototype._pad=d.prototype._pad;b.prototype._unpad=d.prototype._unpad},{"../des":26,inherits:33,"minimalistic-assert":32}],31:[function(c,k,f){f.readUInt32BE=function(a,b){return(a[0+b]<<24|
a[1+b]<<16|a[2+b]<<8|a[3+b])>>>0};f.writeUInt32BE=function(a,b,c){a[0+c]=b>>>24;a[1+c]=b>>>16&255;a[2+c]=b>>>8&255;a[3+c]=b&255};f.ip=function(a,b,c,e){for(var d=0,h=0,g=6;0<=g;g-=2){for(var f=0;24>=f;f+=8)d<<=1,d|=b>>>f+g&1;for(f=0;24>=f;f+=8)d<<=1,d|=a>>>f+g&1}for(g=6;0<=g;g-=2){for(f=1;25>=f;f+=8)h<<=1,h|=b>>>f+g&1;for(f=1;25>=f;f+=8)h<<=1,h|=a>>>f+g&1}c[e+0]=d>>>0;c[e+1]=h>>>0};f.rip=function(a,b,c,e){for(var d=0,h=0,g=0;4>g;g++)for(var f=24;0<=f;f-=8)d<<=1,d|=b>>>f+g&1,d<<=1,d|=a>>>f+g&1;for(g=
4;8>g;g++)for(f=24;0<=f;f-=8)h<<=1,h|=b>>>f+g&1,h<<=1,h|=a>>>f+g&1;c[e+0]=d>>>0;c[e+1]=h>>>0};f.pc1=function(a,b,c,e){for(var d=0,h=0,g=7;5<=g;g--){for(var f=0;24>=f;f+=8)d<<=1,d|=b>>f+g&1;for(f=0;24>=f;f+=8)d<<=1,d|=a>>f+g&1}for(f=0;24>=f;f+=8)d<<=1,d|=b>>f+g&1;for(g=1;3>=g;g++){for(f=0;24>=f;f+=8)h<<=1,h|=b>>f+g&1;for(f=0;24>=f;f+=8)h<<=1,h|=a>>f+g&1}for(f=0;24>=f;f+=8)h<<=1,h|=a>>f+g&1;c[e+0]=d>>>0;c[e+1]=h>>>0};f.r28shl=function(a,b){return a<<b&268435455|a>>>28-b};var e=[14,11,17,4,27,23,25,
0,13,22,7,18,5,9,16,24,2,20,12,21,1,8,15,26,15,4,25,19,9,1,26,16,5,11,23,8,12,7,17,0,22,3,10,14,6,20,27,24];f.pc2=function(a,b,c,g){for(var d=0,h=0,f=e.length>>>1,m=0;m<f;m++)d<<=1,d|=a>>>e[m]&1;for(m=f;m<e.length;m++)h<<=1,h|=b>>>e[m]&1;c[g+0]=d>>>0;c[g+1]=h>>>0};f.expand=function(a,b,c){var d=0;var e=(a&1)<<5|a>>>27;for(var h=23;15<=h;h-=4)e<<=6,e|=a>>>h&63;for(h=11;3<=h;h-=4)d|=a>>>h&63,d<<=6;b[c+0]=e>>>0;b[c+1]=(d|(a&31)<<1|a>>>31)>>>0};var b=[14,0,4,15,13,7,1,4,2,14,15,2,11,13,8,1,3,10,10,6,
6,12,12,11,5,9,9,5,0,3,7,8,4,15,1,12,14,8,8,2,13,4,6,9,2,1,11,7,15,5,12,11,9,3,7,14,3,10,10,0,5,6,0,13,15,3,1,13,8,4,14,7,6,15,11,2,3,8,4,14,9,12,7,0,2,1,13,10,12,6,0,9,5,11,10,5,0,13,14,8,7,10,11,1,10,3,4,15,13,4,1,2,5,11,8,6,12,7,6,12,9,0,3,5,2,14,15,9,10,13,0,7,9,0,14,9,6,3,3,4,15,6,5,10,1,2,13,8,12,5,7,14,11,12,4,11,2,15,8,1,13,1,6,10,4,13,9,0,8,6,15,9,3,8,0,7,11,4,1,15,2,14,12,3,5,11,10,5,14,2,7,12,7,13,13,8,14,11,3,5,0,6,6,15,9,0,10,3,1,4,2,7,8,2,5,12,11,1,12,10,4,14,15,9,10,3,6,15,9,0,0,6,
12,10,11,1,7,13,13,8,15,9,1,4,3,5,14,11,5,12,2,7,8,2,4,14,2,14,12,11,4,2,1,12,7,4,10,7,11,13,6,1,8,5,5,0,3,15,15,10,13,3,0,9,14,8,9,6,4,11,2,8,1,12,11,7,10,1,13,14,7,2,8,13,15,6,9,15,12,0,5,9,6,10,3,4,0,5,14,3,12,10,1,15,10,4,15,2,9,7,2,12,6,9,8,5,0,6,13,1,3,13,4,14,14,0,7,11,5,3,11,8,9,4,14,3,15,2,5,12,2,9,8,5,12,15,3,10,7,11,0,14,4,1,10,7,1,6,13,0,11,8,6,13,4,13,11,0,2,11,14,7,15,4,0,9,8,1,13,10,3,14,12,3,9,5,7,12,5,2,10,15,6,8,1,6,1,6,4,11,11,13,13,8,12,1,3,4,7,10,14,7,10,9,15,5,6,0,8,15,0,14,
5,2,9,3,2,12,13,1,2,15,8,13,4,8,6,10,15,3,11,7,1,4,10,12,9,5,3,6,14,11,5,0,0,14,12,9,7,2,7,2,11,1,4,14,1,7,9,4,12,10,14,8,2,13,0,15,6,12,10,9,13,0,15,3,3,5,5,6,8,11];f.substitute=function(a,d){for(var c=0,e=0;4>e;e++){var g=a>>>18-6*e&63;g=b[64*e+g];c<<=4;c|=g}for(e=0;4>e;e++)g=d>>>18-6*e&63,g=b[256+64*e+g],c<<=4,c|=g;return c>>>0};var g=[16,25,12,11,3,20,4,15,31,17,9,6,27,14,1,22,30,24,8,18,0,5,29,23,13,19,2,26,10,21,28,7];f.permute=function(a){for(var b=0,c=0;c<g.length;c++)b<<=1,b|=a>>>g[c]&1;
return b>>>0};f.padSplit=function(a,b,c){for(a=a.toString(2);a.length<b;)a="0"+a;for(var d=[],e=0;e<b;e+=c)d.push(a.slice(e,e+c));return d.join(" ")}},{}],32:[function(c,k,f){function e(b,c){if(!b)throw Error(c||"Assertion failed");}k.exports=e;e.equal=function(b,c,a){if(b!=c)throw Error(a||"Assertion failed: "+b+" != "+c);}},{}],33:[function(c,k,f){arguments[4][20][0].apply(f,arguments)},{dup:20}],34:[function(c,k,f){arguments[4][21][0].apply(f,arguments)},{buffer:41,dup:21}],35:[function(c,k,f){var e=
c("safe-buffer").Buffer,b=c("md5.js");k.exports=function(c,a,d,h){e.isBuffer(c)||(c=e.from(c,"binary"));if(a&&(e.isBuffer(a)||(a=e.from(a,"binary")),8!==a.length))throw new RangeError("salt should be Buffer with 8 byte length");d/=8;for(var g=e.alloc(d),f=e.alloc(h||0),l=e.alloc(0);0<d||0<h;){var n=new b;n.update(l);n.update(c);a&&n.update(a);l=n.digest();n=0;if(0<d){var p=g.length-d;n=Math.min(d,l.length);l.copy(g,p,0,n);d-=n}n<l.length&&0<h&&(p=Math.min(h,l.length-n),l.copy(f,f.length-h,n,n+p),
h-=p)}l.fill(0);return{key:g,iv:f}}},{"md5.js":36,"safe-buffer":39}],36:[function(c,k,f){function e(){m.call(this,64);this._a=1732584193;this._b=4023233417;this._c=2562383102;this._d=271733878}function b(a,b){return a<<b|a>>>32-b}function g(a,d,c,e,g,h,f){return b(a+(d&c|~d&e)+g+h|0,f)+d|0}function a(a,d,c,e,g,h,f){return b(a+(d&e|c&~e)+g+h|0,f)+d|0}function d(a,d,c,e,g,h,f){return b(a+(d^c^e)+g+h|0,f)+d|0}function h(a,d,c,e,g,h,f){return b(a+(c^(d|~e))+g+h|0,f)+d|0}f=c("inherits");var m=c("hash-base"),
u=c("safe-buffer").Buffer,l=Array(16);f(e,m);e.prototype._update=function(){for(var b=0;16>b;++b)l[b]=this._block.readInt32LE(4*b);b=this._a;var c=this._b,e=this._c,f=this._d;b=g(b,c,e,f,l[0],3614090360,7);f=g(f,b,c,e,l[1],3905402710,12);e=g(e,f,b,c,l[2],606105819,17);c=g(c,e,f,b,l[3],3250441966,22);b=g(b,c,e,f,l[4],4118548399,7);f=g(f,b,c,e,l[5],1200080426,12);e=g(e,f,b,c,l[6],2821735955,17);c=g(c,e,f,b,l[7],4249261313,22);b=g(b,c,e,f,l[8],1770035416,7);f=g(f,b,c,e,l[9],2336552879,12);e=g(e,f,b,
c,l[10],4294925233,17);c=g(c,e,f,b,l[11],2304563134,22);b=g(b,c,e,f,l[12],1804603682,7);f=g(f,b,c,e,l[13],4254626195,12);e=g(e,f,b,c,l[14],2792965006,17);c=g(c,e,f,b,l[15],1236535329,22);b=a(b,c,e,f,l[1],4129170786,5);f=a(f,b,c,e,l[6],3225465664,9);e=a(e,f,b,c,l[11],643717713,14);c=a(c,e,f,b,l[0],3921069994,20);b=a(b,c,e,f,l[5],3593408605,5);f=a(f,b,c,e,l[10],38016083,9);e=a(e,f,b,c,l[15],3634488961,14);c=a(c,e,f,b,l[4],3889429448,20);b=a(b,c,e,f,l[9],568446438,5);f=a(f,b,c,e,l[14],3275163606,9);
e=a(e,f,b,c,l[3],4107603335,14);c=a(c,e,f,b,l[8],1163531501,20);b=a(b,c,e,f,l[13],2850285829,5);f=a(f,b,c,e,l[2],4243563512,9);e=a(e,f,b,c,l[7],1735328473,14);c=a(c,e,f,b,l[12],2368359562,20);b=d(b,c,e,f,l[5],4294588738,4);f=d(f,b,c,e,l[8],2272392833,11);e=d(e,f,b,c,l[11],1839030562,16);c=d(c,e,f,b,l[14],4259657740,23);b=d(b,c,e,f,l[1],2763975236,4);f=d(f,b,c,e,l[4],1272893353,11);e=d(e,f,b,c,l[7],4139469664,16);c=d(c,e,f,b,l[10],3200236656,23);b=d(b,c,e,f,l[13],681279174,4);f=d(f,b,c,e,l[0],3936430074,
11);e=d(e,f,b,c,l[3],3572445317,16);c=d(c,e,f,b,l[6],76029189,23);b=d(b,c,e,f,l[9],3654602809,4);f=d(f,b,c,e,l[12],3873151461,11);e=d(e,f,b,c,l[15],530742520,16);c=d(c,e,f,b,l[2],3299628645,23);b=h(b,c,e,f,l[0],4096336452,6);f=h(f,b,c,e,l[7],1126891415,10);e=h(e,f,b,c,l[14],2878612391,15);c=h(c,e,f,b,l[5],4237533241,21);b=h(b,c,e,f,l[12],1700485571,6);f=h(f,b,c,e,l[3],2399980690,10);e=h(e,f,b,c,l[10],4293915773,15);c=h(c,e,f,b,l[1],2240044497,21);b=h(b,c,e,f,l[8],1873313359,6);f=h(f,b,c,e,l[15],4264355552,
10);e=h(e,f,b,c,l[6],2734768916,15);c=h(c,e,f,b,l[13],1309151649,21);b=h(b,c,e,f,l[4],4149444226,6);f=h(f,b,c,e,l[11],3174756917,10);e=h(e,f,b,c,l[2],718787259,15);c=h(c,e,f,b,l[9],3951481745,21);this._a=this._a+b|0;this._b=this._b+c|0;this._c=this._c+e|0;this._d=this._d+f|0};e.prototype._digest=function(){this._block[this._blockOffset++]=128;56<this._blockOffset&&(this._block.fill(0,this._blockOffset,64),this._update(),this._blockOffset=0);this._block.fill(0,this._blockOffset,56);this._block.writeUInt32LE(this._length[0],
56);this._block.writeUInt32LE(this._length[1],60);this._update();var b=u.allocUnsafe(16);b.writeInt32LE(this._a,0);b.writeInt32LE(this._b,4);b.writeInt32LE(this._c,8);b.writeInt32LE(this._d,12);return b};k.exports=e},{"hash-base":37,inherits:38,"safe-buffer":39}],37:[function(c,k,f){function e(a){g.call(this);this._block=b.allocUnsafe(a);this._blockSize=a;this._blockOffset=0;this._length=[0,0,0,0];this._finalized=!1}var b=c("safe-buffer").Buffer,g=c("stream").Transform;c("inherits")(e,g);e.prototype._transform=
function(b,c,e){var a=null;try{this.update(b,c)}catch(u){a=u}e(a)};e.prototype._flush=function(b){var a=null;try{this.push(this.digest())}catch(h){a=h}b(a)};e.prototype.update=function(a,c){var d=a;if(!b.isBuffer(d)&&"string"!==typeof d)throw new TypeError("Data must be a string or a buffer");if(this._finalized)throw Error("Digest already called");b.isBuffer(a)||(a=b.from(a,c));c=this._block;for(d=0;this._blockOffset+a.length-d>=this._blockSize;){for(var e=this._blockOffset;e<this._blockSize;)c[e++]=
a[d++];this._update();this._blockOffset=0}for(;d<a.length;)c[this._blockOffset++]=a[d++];c=0;for(a=8*a.length;0<a;++c)this._length[c]+=a,a=this._length[c]/4294967296|0,0<a&&(this._length[c]-=4294967296*a);return this};e.prototype._update=function(){throw Error("_update is not implemented");};e.prototype.digest=function(b){if(this._finalized)throw Error("Digest already called");this._finalized=!0;var a=this._digest();void 0!==b&&(a=a.toString(b));this._block.fill(0);for(b=this._blockOffset=0;4>b;++b)this._length[b]=
0;return a};e.prototype._digest=function(){throw Error("_digest is not implemented");};k.exports=e},{inherits:38,"safe-buffer":39,stream:66}],38:[function(c,k,f){arguments[4][20][0].apply(f,arguments)},{dup:20}],39:[function(c,k,f){arguments[4][21][0].apply(f,arguments)},{buffer:41,dup:21}],40:[function(c,k,f){},{}],41:[function(c,k,f){function e(a){if(a>w)throw new RangeError("Invalid typed array length");a=new Uint8Array(a);a.__proto__=b.prototype;return a}function b(b,a,c){if("number"===typeof b){if("string"===
typeof a)throw Error("If encoding is specified then the first argument must be a string");return d(b)}return g(b,a,c)}function g(a,c,d){if("number"===typeof a)throw new TypeError('"value" argument must not be a number');if(K(a)){if(0>c||a.byteLength<c)throw new RangeError("'offset' is out of bounds");if(a.byteLength<c+(d||0))throw new RangeError("'length' is out of bounds");a=void 0===c&&void 0===d?new Uint8Array(a):void 0===d?new Uint8Array(a,c):new Uint8Array(a,c,d);a.__proto__=b.prototype;return a}if("string"===
typeof a){var q=c;if("string"!==typeof q||""===q)q="utf8";if(!b.isEncoding(q))throw new TypeError('"encoding" must be a valid string encoding');c=l(a,q)|0;d=e(c);a=d.write(a,q);a!==c&&(d=d.slice(0,a));return d}return m(a)}function a(b){if("number"!==typeof b)throw new TypeError('"size" argument must be a number');if(0>b)throw new RangeError('"size" argument must not be negative');}function d(b){a(b);return e(0>b?0:u(b)|0)}function h(b){for(var a=0>b.length?0:u(b.length)|0,c=e(a),d=0;d<a;d+=1)c[d]=
b[d]&255;return c}function m(a){if(b.isBuffer(a)){var c=u(a.length)|0,d=e(c);if(0===d.length)return d;a.copy(d,0,0,c);return d}if(a){if("function"===typeof ArrayBuffer.isView&&ArrayBuffer.isView(a)||"length"in a)return(c="number"!==typeof a.length)||(c=a.length,c=c!==c),c?e(0):h(a);if("Buffer"===a.type&&Array.isArray(a.data))return h(a.data)}throw new TypeError("First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.");}function u(b){if(b>=w)throw new RangeError("Attempt to allocate Buffer larger than maximum size: 0x"+
w.toString(16)+" bytes");return b|0}function l(a,c){if(b.isBuffer(a))return a.length;if("function"===typeof ArrayBuffer.isView&&ArrayBuffer.isView(a)||K(a))return a.byteLength;"string"!==typeof a&&(a=""+a);var q=a.length;if(0===q)return 0;for(var d=!1;;)switch(c){case "ascii":case "latin1":case "binary":return q;case "utf8":case "utf-8":case void 0:return B(a).length;case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":return 2*q;case "hex":return q>>>1;case "base64":return M.toByteArray(y(a)).length;
default:if(d)return B(a).length;c=(""+c).toLowerCase();d=!0}}function n(b,a,c){var d=!1;if(void 0===a||0>a)a=0;if(a>this.length)return"";if(void 0===c||c>this.length)c=this.length;if(0>=c)return"";c>>>=0;a>>>=0;if(c<=a)return"";for(b||(b="utf8");;)switch(b){case "hex":b=a;a=c;c=this.length;if(!b||0>b)b=0;if(!a||0>a||a>c)a=c;d="";for(c=b;c<a;++c)b=d,d=this[c],d=16>d?"0"+d.toString(16):d.toString(16),d=b+d;return d;case "utf8":case "utf-8":return x(this,a,c);case "ascii":b="";for(c=Math.min(this.length,
c);a<c;++a)b+=String.fromCharCode(this[a]&127);return b;case "latin1":case "binary":b="";for(c=Math.min(this.length,c);a<c;++a)b+=String.fromCharCode(this[a]);return b;case "base64":return a=0===a&&c===this.length?M.fromByteArray(this):M.fromByteArray(this.slice(a,c)),a;case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":a=this.slice(a,c);c="";for(b=0;b<a.length;b+=2)c+=String.fromCharCode(a[b]+256*a[b+1]);return c;default:if(d)throw new TypeError("Unknown encoding: "+b);b=(b+"").toLowerCase();
d=!0}}function p(b,a,c){var d=b[a];b[a]=b[c];b[c]=d}function t(a,c,d,e,f){if(0===a.length)return-1;"string"===typeof d?(e=d,d=0):2147483647<d?d=2147483647:-2147483648>d&&(d=-2147483648);d=+d;d!==d&&(d=f?0:a.length-1);0>d&&(d=a.length+d);if(d>=a.length){if(f)return-1;d=a.length-1}else if(0>d)if(f)d=0;else return-1;"string"===typeof c&&(c=b.from(c,e));if(b.isBuffer(c))return 0===c.length?-1:z(a,c,d,e,f);if("number"===typeof c)return c&=255,"function"===typeof Uint8Array.prototype.indexOf?f?Uint8Array.prototype.indexOf.call(a,
c,d):Uint8Array.prototype.lastIndexOf.call(a,c,d):z(a,[c],d,e,f);throw new TypeError("val must be string, number or Buffer");}function z(b,a,c,d,e){function q(b,a){return 1===F?b[a]:b.readUInt16BE(a*F)}var F=1,f=b.length,E=a.length;if(void 0!==d&&(d=String(d).toLowerCase(),"ucs2"===d||"ucs-2"===d||"utf16le"===d||"utf-16le"===d)){if(2>b.length||2>a.length)return-1;F=2;f/=2;E/=2;c/=2}if(e)for(d=-1;c<f;c++)if(q(b,c)===q(a,-1===d?0:c-d)){if(-1===d&&(d=c),c-d+1===E)return d*F}else-1!==d&&(c-=c-d),d=-1;
else for(c+E>f&&(c=f-E);0<=c;c--){f=!0;for(d=0;d<E;d++)if(q(b,c+d)!==q(a,d)){f=!1;break}if(f)return c}return-1}function x(b,a,c){c=Math.min(b.length,c);for(var d=[];a<c;){var q=b[a],e=null,F=239<q?4:223<q?3:191<q?2:1;if(a+F<=c)switch(F){case 1:128>q&&(e=q);break;case 2:var f=b[a+1];128===(f&192)&&(q=(q&31)<<6|f&63,127<q&&(e=q));break;case 3:f=b[a+1];var E=b[a+2];128===(f&192)&&128===(E&192)&&(q=(q&15)<<12|(f&63)<<6|E&63,2047<q&&(55296>q||57343<q)&&(e=q));break;case 4:f=b[a+1];E=b[a+2];var g=b[a+3];
128===(f&192)&&128===(E&192)&&128===(g&192)&&(q=(q&15)<<18|(f&63)<<12|(E&63)<<6|g&63,65535<q&&1114112>q&&(e=q))}null===e?(e=65533,F=1):65535<e&&(e-=65536,d.push(e>>>10&1023|55296),e=56320|e&1023);d.push(e);a+=F}b=d.length;if(b<=N)d=String.fromCharCode.apply(String,d);else{c="";for(a=0;a<b;)c+=String.fromCharCode.apply(String,d.slice(a,a+=N));d=c}return d}function v(b,a,c){if(0!==b%1||0>b)throw new RangeError("offset is not uint");if(b+a>c)throw new RangeError("Trying to access beyond buffer length");
}function A(a,c,d,e,f,g){if(!b.isBuffer(a))throw new TypeError('"buffer" argument must be a Buffer instance');if(c>f||c<g)throw new RangeError('"value" argument is out of bounds');if(d+e>a.length)throw new RangeError("Index out of range");}function C(b,a,c,d,e,f){if(c+d>b.length)throw new RangeError("Index out of range");if(0>c)throw new RangeError("Index out of range");}function D(b,a,c,d,e){a=+a;c>>>=0;e||C(b,a,c,4,3.4028234663852886E38,-3.4028234663852886E38);H.write(b,a,c,d,23,4);return c+4}function G(b,
a,c,d,e){a=+a;c>>>=0;e||C(b,a,c,8,1.7976931348623157E308,-1.7976931348623157E308);H.write(b,a,c,d,52,8);return c+8}function y(b){b=b.trim().replace(L,"");if(2>b.length)return"";for(;0!==b.length%4;)b+="=";return b}function B(b,a){a=a||Infinity;for(var c,d=b.length,q=null,e=[],f=0;f<d;++f){c=b.charCodeAt(f);if(55295<c&&57344>c){if(!q){if(56319<c){-1<(a-=3)&&e.push(239,191,189);continue}else if(f+1===d){-1<(a-=3)&&e.push(239,191,189);continue}q=c;continue}if(56320>c){-1<(a-=3)&&e.push(239,191,189);
q=c;continue}c=(q-55296<<10|c-56320)+65536}else q&&-1<(a-=3)&&e.push(239,191,189);q=null;if(128>c){if(0>--a)break;e.push(c)}else if(2048>c){if(0>(a-=2))break;e.push(c>>6|192,c&63|128)}else if(65536>c){if(0>(a-=3))break;e.push(c>>12|224,c>>6&63|128,c&63|128)}else if(1114112>c){if(0>(a-=4))break;e.push(c>>18|240,c>>12&63|128,c>>6&63|128,c&63|128)}else throw Error("Invalid code point");}return e}function J(b){for(var a=[],c=0;c<b.length;++c)a.push(b.charCodeAt(c)&255);return a}function I(b,a,c,d){for(var e=
0;e<d&&!(e+c>=a.length||e>=b.length);++e)a[e+c]=b[e];return e}function K(b){return b instanceof ArrayBuffer||null!=b&&null!=b.constructor&&"ArrayBuffer"===b.constructor.name&&"number"===typeof b.byteLength}var M=c("base64-js"),H=c("ieee754");f.Buffer=b;f.SlowBuffer=function(a){+a!=a&&(a=0);return b.alloc(+a)};f.INSPECT_MAX_BYTES=50;var w=2147483647;f.kMaxLength=w;b.TYPED_ARRAY_SUPPORT=function(){try{var b=new Uint8Array(1);b.__proto__={__proto__:Uint8Array.prototype,foo:function(){return 42}};return 42===
b.foo()}catch(q){return!1}}();b.TYPED_ARRAY_SUPPORT||"undefined"===typeof console||"function"!==typeof console.error||console.error("This browser lacks typed array (Uint8Array) support which is required by `buffer` v5.x. Use `buffer` v4.x if you require old browser support.");"undefined"!==typeof Symbol&&Symbol.species&&b[Symbol.species]===b&&Object.defineProperty(b,Symbol.species,{value:null,configurable:!0,enumerable:!1,writable:!1});b.poolSize=8192;b.from=function(b,a,c){return g(b,a,c)};b.prototype.__proto__=
Uint8Array.prototype;b.__proto__=Uint8Array;b.alloc=function(b,c,d){a(b);b=0>=b?e(b):void 0!==c?"string"===typeof d?e(b).fill(c,d):e(b).fill(c):e(b);return b};b.allocUnsafe=function(b){return d(b)};b.allocUnsafeSlow=function(b){return d(b)};b.isBuffer=function(b){return null!=b&&!0===b._isBuffer};b.compare=function(a,c){if(!b.isBuffer(a)||!b.isBuffer(c))throw new TypeError("Arguments must be Buffers");if(a===c)return 0;for(var d=a.length,e=c.length,q=0,f=Math.min(d,e);q<f;++q)if(a[q]!==c[q]){d=a[q];
e=c[q];break}return d<e?-1:e<d?1:0};b.isEncoding=function(b){switch(String(b).toLowerCase()){case "hex":case "utf8":case "utf-8":case "ascii":case "latin1":case "binary":case "base64":case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":return!0;default:return!1}};b.concat=function(a,c){if(!Array.isArray(a))throw new TypeError('"list" argument must be an Array of Buffers');if(0===a.length)return b.alloc(0);var d;if(void 0===c)for(d=c=0;d<a.length;++d)c+=a[d].length;c=b.allocUnsafe(c);var e=0;for(d=
0;d<a.length;++d){var q=a[d];if(!b.isBuffer(q))throw new TypeError('"list" argument must be an Array of Buffers');q.copy(c,e);e+=q.length}return c};b.byteLength=l;b.prototype._isBuffer=!0;b.prototype.swap16=function(){var b=this.length;if(0!==b%2)throw new RangeError("Buffer size must be a multiple of 16-bits");for(var a=0;a<b;a+=2)p(this,a,a+1);return this};b.prototype.swap32=function(){var b=this.length;if(0!==b%4)throw new RangeError("Buffer size must be a multiple of 32-bits");for(var a=0;a<b;a+=
4)p(this,a,a+3),p(this,a+1,a+2);return this};b.prototype.swap64=function(){var b=this.length;if(0!==b%8)throw new RangeError("Buffer size must be a multiple of 64-bits");for(var a=0;a<b;a+=8)p(this,a,a+7),p(this,a+1,a+6),p(this,a+2,a+5),p(this,a+3,a+4);return this};b.prototype.toString=function(){var b=this.length;return 0===b?"":0===arguments.length?x(this,0,b):n.apply(this,arguments)};b.prototype.equals=function(a){if(!b.isBuffer(a))throw new TypeError("Argument must be a Buffer");return this===
a?!0:0===b.compare(this,a)};b.prototype.inspect=function(){var b="",a=f.INSPECT_MAX_BYTES;0<this.length&&(b=this.toString("hex",0,a).match(/.{2}/g).join(" "),this.length>a&&(b+=" ... "));return"<Buffer "+b+">"};b.prototype.compare=function(a,c,d,e,f){if(!b.isBuffer(a))throw new TypeError("Argument must be a Buffer");void 0===c&&(c=0);void 0===d&&(d=a?a.length:0);void 0===e&&(e=0);void 0===f&&(f=this.length);if(0>c||d>a.length||0>e||f>this.length)throw new RangeError("out of range index");if(e>=f&&
c>=d)return 0;if(e>=f)return-1;if(c>=d)return 1;c>>>=0;d>>>=0;e>>>=0;f>>>=0;if(this===a)return 0;var q=f-e,F=d-c,g=Math.min(q,F);e=this.slice(e,f);a=a.slice(c,d);for(c=0;c<g;++c)if(e[c]!==a[c]){q=e[c];F=a[c];break}return q<F?-1:F<q?1:0};b.prototype.includes=function(b,a,c){return-1!==this.indexOf(b,a,c)};b.prototype.indexOf=function(b,a,c){return t(this,b,a,c,!0)};b.prototype.lastIndexOf=function(b,a,c){return t(this,b,a,c,!1)};b.prototype.write=function(b,a,c,d){if(void 0===a)d="utf8",c=this.length,
a=0;else if(void 0===c&&"string"===typeof a)d=a,c=this.length,a=0;else if(isFinite(a))a>>>=0,isFinite(c)?(c>>>=0,void 0===d&&(d="utf8")):(d=c,c=void 0);else throw Error("Buffer.write(string, encoding, offset[, length]) is no longer supported");var e=this.length-a;if(void 0===c||c>e)c=e;if(0<b.length&&(0>c||0>a)||a>this.length)throw new RangeError("Attempt to write outside buffer bounds");d||(d="utf8");for(e=!1;;)switch(d){case "hex":a:{a=Number(a)||0;d=this.length-a;c?(c=Number(c),c>d&&(c=d)):c=d;
d=b.length;if(0!==d%2)throw new TypeError("Invalid hex string");c>d/2&&(c=d/2);for(d=0;d<c;++d){e=parseInt(b.substr(2*d,2),16);if(e!==e){b=d;break a}this[a+d]=e}b=d}return b;case "utf8":case "utf-8":return I(B(b,this.length-a),this,a,c);case "ascii":return I(J(b),this,a,c);case "latin1":case "binary":return I(J(b),this,a,c);case "base64":return I(M.toByteArray(y(b)),this,a,c);case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":d=b;e=this.length-a;for(var f=[],q=0;q<d.length&&!(0>(e-=2));++q){var g=
d.charCodeAt(q);b=g>>8;g%=256;f.push(g);f.push(b)}return I(f,this,a,c);default:if(e)throw new TypeError("Unknown encoding: "+d);d=(""+d).toLowerCase();e=!0}};b.prototype.toJSON=function(){return{type:"Buffer",data:Array.prototype.slice.call(this._arr||this,0)}};var N=4096;b.prototype.slice=function(a,c){var d=this.length;a=~~a;c=void 0===c?d:~~c;0>a?(a+=d,0>a&&(a=0)):a>d&&(a=d);0>c?(c+=d,0>c&&(c=0)):c>d&&(c=d);c<a&&(c=a);a=this.subarray(a,c);a.__proto__=b.prototype;return a};b.prototype.readUIntLE=
function(a,b,c){a>>>=0;b>>>=0;c||v(a,b,this.length);c=this[a];for(var d=1,e=0;++e<b&&(d*=256);)c+=this[a+e]*d;return c};b.prototype.readUIntBE=function(a,b,c){a>>>=0;b>>>=0;c||v(a,b,this.length);c=this[a+--b];for(var d=1;0<b&&(d*=256);)c+=this[a+--b]*d;return c};b.prototype.readUInt8=function(a,b){a>>>=0;b||v(a,1,this.length);return this[a]};b.prototype.readUInt16LE=function(a,b){a>>>=0;b||v(a,2,this.length);return this[a]|this[a+1]<<8};b.prototype.readUInt16BE=function(a,b){a>>>=0;b||v(a,2,this.length);
return this[a]<<8|this[a+1]};b.prototype.readUInt32LE=function(a,b){a>>>=0;b||v(a,4,this.length);return(this[a]|this[a+1]<<8|this[a+2]<<16)+16777216*this[a+3]};b.prototype.readUInt32BE=function(a,b){a>>>=0;b||v(a,4,this.length);return 16777216*this[a]+(this[a+1]<<16|this[a+2]<<8|this[a+3])};b.prototype.readIntLE=function(a,b,c){a>>>=0;b>>>=0;c||v(a,b,this.length);c=this[a];for(var d=1,e=0;++e<b&&(d*=256);)c+=this[a+e]*d;c>=128*d&&(c-=Math.pow(2,8*b));return c};b.prototype.readIntBE=function(a,b,c){a>>>=
0;b>>>=0;c||v(a,b,this.length);c=b;for(var d=1,e=this[a+--c];0<c&&(d*=256);)e+=this[a+--c]*d;e>=128*d&&(e-=Math.pow(2,8*b));return e};b.prototype.readInt8=function(a,b){a>>>=0;b||v(a,1,this.length);return this[a]&128?-1*(255-this[a]+1):this[a]};b.prototype.readInt16LE=function(a,b){a>>>=0;b||v(a,2,this.length);a=this[a]|this[a+1]<<8;return a&32768?a|4294901760:a};b.prototype.readInt16BE=function(a,b){a>>>=0;b||v(a,2,this.length);a=this[a+1]|this[a]<<8;return a&32768?a|4294901760:a};b.prototype.readInt32LE=
function(a,b){a>>>=0;b||v(a,4,this.length);return this[a]|this[a+1]<<8|this[a+2]<<16|this[a+3]<<24};b.prototype.readInt32BE=function(a,b){a>>>=0;b||v(a,4,this.length);return this[a]<<24|this[a+1]<<16|this[a+2]<<8|this[a+3]};b.prototype.readFloatLE=function(a,b){a>>>=0;b||v(a,4,this.length);return H.read(this,a,!0,23,4)};b.prototype.readFloatBE=function(a,b){a>>>=0;b||v(a,4,this.length);return H.read(this,a,!1,23,4)};b.prototype.readDoubleLE=function(a,b){a>>>=0;b||v(a,8,this.length);return H.read(this,
a,!0,52,8)};b.prototype.readDoubleBE=function(a,b){a>>>=0;b||v(a,8,this.length);return H.read(this,a,!1,52,8)};b.prototype.writeUIntLE=function(a,b,c,d){a=+a;b>>>=0;c>>>=0;d||A(this,a,b,c,Math.pow(2,8*c)-1,0);d=1;var e=0;for(this[b]=a&255;++e<c&&(d*=256);)this[b+e]=a/d&255;return b+c};b.prototype.writeUIntBE=function(a,b,c,d){a=+a;b>>>=0;c>>>=0;d||A(this,a,b,c,Math.pow(2,8*c)-1,0);d=c-1;var e=1;for(this[b+d]=a&255;0<=--d&&(e*=256);)this[b+d]=a/e&255;return b+c};b.prototype.writeUInt8=function(a,b,
c){a=+a;b>>>=0;c||A(this,a,b,1,255,0);this[b]=a&255;return b+1};b.prototype.writeUInt16LE=function(a,b,c){a=+a;b>>>=0;c||A(this,a,b,2,65535,0);this[b]=a&255;this[b+1]=a>>>8;return b+2};b.prototype.writeUInt16BE=function(a,b,c){a=+a;b>>>=0;c||A(this,a,b,2,65535,0);this[b]=a>>>8;this[b+1]=a&255;return b+2};b.prototype.writeUInt32LE=function(a,b,c){a=+a;b>>>=0;c||A(this,a,b,4,4294967295,0);this[b+3]=a>>>24;this[b+2]=a>>>16;this[b+1]=a>>>8;this[b]=a&255;return b+4};b.prototype.writeUInt32BE=function(a,
b,c){a=+a;b>>>=0;c||A(this,a,b,4,4294967295,0);this[b]=a>>>24;this[b+1]=a>>>16;this[b+2]=a>>>8;this[b+3]=a&255;return b+4};b.prototype.writeIntLE=function(a,b,c,d){a=+a;b>>>=0;d||(d=Math.pow(2,8*c-1),A(this,a,b,c,d-1,-d));d=0;var e=1,f=0;for(this[b]=a&255;++d<c&&(e*=256);)0>a&&0===f&&0!==this[b+d-1]&&(f=1),this[b+d]=(a/e>>0)-f&255;return b+c};b.prototype.writeIntBE=function(a,b,c,d){a=+a;b>>>=0;d||(d=Math.pow(2,8*c-1),A(this,a,b,c,d-1,-d));d=c-1;var e=1,f=0;for(this[b+d]=a&255;0<=--d&&(e*=256);)0>
a&&0===f&&0!==this[b+d+1]&&(f=1),this[b+d]=(a/e>>0)-f&255;return b+c};b.prototype.writeInt8=function(a,b,c){a=+a;b>>>=0;c||A(this,a,b,1,127,-128);0>a&&(a=255+a+1);this[b]=a&255;return b+1};b.prototype.writeInt16LE=function(a,b,c){a=+a;b>>>=0;c||A(this,a,b,2,32767,-32768);this[b]=a&255;this[b+1]=a>>>8;return b+2};b.prototype.writeInt16BE=function(a,b,c){a=+a;b>>>=0;c||A(this,a,b,2,32767,-32768);this[b]=a>>>8;this[b+1]=a&255;return b+2};b.prototype.writeInt32LE=function(a,b,c){a=+a;b>>>=0;c||A(this,
a,b,4,2147483647,-2147483648);this[b]=a&255;this[b+1]=a>>>8;this[b+2]=a>>>16;this[b+3]=a>>>24;return b+4};b.prototype.writeInt32BE=function(a,b,c){a=+a;b>>>=0;c||A(this,a,b,4,2147483647,-2147483648);0>a&&(a=4294967295+a+1);this[b]=a>>>24;this[b+1]=a>>>16;this[b+2]=a>>>8;this[b+3]=a&255;return b+4};b.prototype.writeFloatLE=function(a,b,c){return D(this,a,b,!0,c)};b.prototype.writeFloatBE=function(a,b,c){return D(this,a,b,!1,c)};b.prototype.writeDoubleLE=function(a,b,c){return G(this,a,b,!0,c)};b.prototype.writeDoubleBE=
function(a,b,c){return G(this,a,b,!1,c)};b.prototype.copy=function(a,b,c,d){c||(c=0);d||0===d||(d=this.length);b>=a.length&&(b=a.length);b||(b=0);0<d&&d<c&&(d=c);if(d===c||0===a.length||0===this.length)return 0;if(0>b)throw new RangeError("targetStart out of bounds");if(0>c||c>=this.length)throw new RangeError("sourceStart out of bounds");if(0>d)throw new RangeError("sourceEnd out of bounds");d>this.length&&(d=this.length);a.length-b<d-c&&(d=a.length-b+c);var e=d-c;if(this===a&&c<b&&b<d)for(d=e-1;0<=
d;--d)a[d+b]=this[d+c];else if(1E3>e)for(d=0;d<e;++d)a[d+b]=this[d+c];else Uint8Array.prototype.set.call(a,this.subarray(c,c+e),b);return e};b.prototype.fill=function(a,c,d,e){if("string"===typeof a){"string"===typeof c?(e=c,c=0,d=this.length):"string"===typeof d&&(e=d,d=this.length);if(1===a.length){var f=a.charCodeAt(0);256>f&&(a=f)}if(void 0!==e&&"string"!==typeof e)throw new TypeError("encoding must be a string");if("string"===typeof e&&!b.isEncoding(e))throw new TypeError("Unknown encoding: "+
e);}else"number"===typeof a&&(a&=255);if(0>c||this.length<c||this.length<d)throw new RangeError("Out of range index");if(d<=c)return this;c>>>=0;d=void 0===d?this.length:d>>>0;a||(a=0);if("number"===typeof a)for(e=c;e<d;++e)this[e]=a;else for(a=b.isBuffer(a)?a:new b(a,e),f=a.length,e=0;e<d-c;++e)this[e+c]=a[e%f];return this};var L=/[^+/0-9A-Za-z-_]/g},{"base64-js":42,ieee754:43}],42:[function(c,k,f){function e(a){var b=a.length;if(0<b%4)throw Error("Invalid string. Length must be a multiple of 4");
return"="===a[b-2]?2:"="===a[b-1]?1:0}function b(a,b,c){for(var d=[],e=b;e<c;e+=3)b=(a[e]<<16)+(a[e+1]<<8)+a[e+2],d.push(g[b>>18&63]+g[b>>12&63]+g[b>>6&63]+g[b&63]);return d.join("")}f.byteLength=function(a){return 3*a.length/4-e(a)};f.toByteArray=function(b){var c=b.length;var f=e(b);var g=new d(3*c/4-f);var h=0<f?c-4:c;var k=0;for(c=0;c<h;c+=4){var t=a[b.charCodeAt(c)]<<18|a[b.charCodeAt(c+1)]<<12|a[b.charCodeAt(c+2)]<<6|a[b.charCodeAt(c+3)];g[k++]=t>>16&255;g[k++]=t>>8&255;g[k++]=t&255}2===f?(t=
a[b.charCodeAt(c)]<<2|a[b.charCodeAt(c+1)]>>4,g[k++]=t&255):1===f&&(t=a[b.charCodeAt(c)]<<10|a[b.charCodeAt(c+1)]<<4|a[b.charCodeAt(c+2)]>>2,g[k++]=t>>8&255,g[k++]=t&255);return g};f.fromByteArray=function(a){for(var c=a.length,d=c%3,e="",f=[],h=0,k=c-d;h<k;h+=16383)f.push(b(a,h,h+16383>k?k:h+16383));1===d?(a=a[c-1],e+=g[a>>2],e+=g[a<<4&63],e+="=="):2===d&&(a=(a[c-2]<<8)+a[c-1],e+=g[a>>10],e+=g[a>>4&63],e+=g[a<<2&63],e+="=");f.push(e);return f.join("")};var g=[],a=[],d="undefined"!==typeof Uint8Array?
Uint8Array:Array;for(c=0;64>c;++c)g[c]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[c],a["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charCodeAt(c)]=c;a[45]=62;a[95]=63},{}],43:[function(c,k,f){f.read=function(c,b,f,a,d){var e=8*d-a-1;var g=(1<<e)-1,k=g>>1,l=-7;d=f?d-1:0;var n=f?-1:1,p=c[b+d];d+=n;f=p&(1<<-l)-1;p>>=-l;for(l+=e;0<l;f=256*f+c[b+d],d+=n,l-=8);e=f&(1<<-l)-1;f>>=-l;for(l+=a;0<l;e=256*e+c[b+d],d+=n,l-=8);if(0===f)f=1-k;else{if(f===g)return e?
NaN:Infinity*(p?-1:1);e+=Math.pow(2,a);f-=k}return(p?-1:1)*e*Math.pow(2,f-a)};f.write=function(c,b,f,a,d,h){var e,g=8*h-d-1,k=(1<<g)-1,n=k>>1,p=23===d?Math.pow(2,-24)-Math.pow(2,-77):0;h=a?0:h-1;var t=a?1:-1,z=0>b||0===b&&0>1/b?1:0;b=Math.abs(b);isNaN(b)||Infinity===b?(b=isNaN(b)?1:0,a=k):(a=Math.floor(Math.log(b)/Math.LN2),1>b*(e=Math.pow(2,-a))&&(a--,e*=2),b=1<=a+n?b+p/e:b+p*Math.pow(2,1-n),2<=b*e&&(a++,e/=2),a+n>=k?(b=0,a=k):1<=a+n?(b=(b*e-1)*Math.pow(2,d),a+=n):(b=b*Math.pow(2,n-1)*Math.pow(2,
d),a=0));for(;8<=d;c[f+h]=b&255,h+=t,b/=256,d-=8);a=a<<d|b;for(g+=d;0<g;c[f+h]=a&255,h+=t,a/=256,g-=8);c[f+h-t]|=128*z}},{}],44:[function(c,k,f){function e(){this._events=this._events||{};this._maxListeners=this._maxListeners||void 0}function b(a){return"function"===typeof a}function g(a){return"object"===typeof a&&null!==a}k.exports=e;e.EventEmitter=e;e.prototype._events=void 0;e.prototype._maxListeners=void 0;e.defaultMaxListeners=10;e.prototype.setMaxListeners=function(a){if("number"!==typeof a||
0>a||isNaN(a))throw TypeError("n must be a positive number");this._maxListeners=a;return this};e.prototype.emit=function(a){var c;this._events||(this._events={});if("error"===a&&(!this._events.error||g(this._events.error)&&!this._events.error.length)){var e=arguments[1];if(e instanceof Error)throw e;var f=Error('Uncaught, unspecified "error" event. ('+e+")");f.context=e;throw f;}f=this._events[a];if(void 0===f)return!1;if(b(f))switch(arguments.length){case 1:f.call(this);break;case 2:f.call(this,
arguments[1]);break;case 3:f.call(this,arguments[1],arguments[2]);break;default:e=Array.prototype.slice.call(arguments,1),f.apply(this,e)}else if(g(f)){e=Array.prototype.slice.call(arguments,1);var k=f.slice();f=k.length;for(c=0;c<f;c++)k[c].apply(this,e)}return!0};e.prototype.addListener=function(a,c){if(!b(c))throw TypeError("listener must be a function");this._events||(this._events={});this._events.newListener&&this.emit("newListener",a,b(c.listener)?c.listener:c);this._events[a]?g(this._events[a])?
this._events[a].push(c):this._events[a]=[this._events[a],c]:this._events[a]=c;g(this._events[a])&&!this._events[a].warned&&(c=void 0!==this._maxListeners?this._maxListeners:e.defaultMaxListeners)&&0<c&&this._events[a].length>c&&(this._events[a].warned=!0,console.error("(node) warning: possible EventEmitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() to increase limit.",this._events[a].length),"function"===typeof console.trace&&console.trace());return this};e.prototype.on=
e.prototype.addListener;e.prototype.once=function(a,c){function d(){this.removeListener(a,d);e||(e=!0,c.apply(this,arguments))}if(!b(c))throw TypeError("listener must be a function");var e=!1;d.listener=c;this.on(a,d);return this};e.prototype.removeListener=function(a,c){if(!b(c))throw TypeError("listener must be a function");if(!this._events||!this._events[a])return this;var d=this._events[a];var e=d.length;var f=-1;if(d===c||b(d.listener)&&d.listener===c)delete this._events[a],this._events.removeListener&&
this.emit("removeListener",a,c);else if(g(d)){for(;0<e--;)if(d[e]===c||d[e].listener&&d[e].listener===c){f=e;break}if(0>f)return this;1===d.length?(d.length=0,delete this._events[a]):d.splice(f,1);this._events.removeListener&&this.emit("removeListener",a,c)}return this};e.prototype.removeAllListeners=function(a){if(!this._events)return this;if(!this._events.removeListener)return 0===arguments.length?this._events={}:this._events[a]&&delete this._events[a],this;if(0===arguments.length){for(c in this._events)"removeListener"!==
c&&this.removeAllListeners(c);this.removeAllListeners("removeListener");this._events={};return this}var c=this._events[a];if(b(c))this.removeListener(a,c);else if(c)for(;c.length;)this.removeListener(a,c[c.length-1]);delete this._events[a];return this};e.prototype.listeners=function(a){return this._events&&this._events[a]?b(this._events[a])?[this._events[a]]:this._events[a].slice():[]};e.prototype.listenerCount=function(a){if(this._events){a=this._events[a];if(b(a))return 1;if(a)return a.length}return 0};
e.listenerCount=function(a,b){return a.listenerCount(b)}},{}],45:[function(c,k,f){k.exports="function"===typeof Object.create?function(c,b){c.super_=b;c.prototype=Object.create(b.prototype,{constructor:{value:c,enumerable:!1,writable:!0,configurable:!0}})}:function(c,b){c.super_=b;var e=function(){};e.prototype=b.prototype;c.prototype=new e;c.prototype.constructor=c}},{}],46:[function(c,k,f){function e(b){return!!b.constructor&&"function"===typeof b.constructor.isBuffer&&b.constructor.isBuffer(b)}
k.exports=function(b){return null!=b&&(e(b)||"function"===typeof b.readFloatLE&&"function"===typeof b.slice&&e(b.slice(0,0))||!!b._isBuffer)}},{}],47:[function(c,k,f){function e(){throw Error("setTimeout has not been defined");}function b(){throw Error("clearTimeout has not been defined");}function g(a){if(l===setTimeout)return setTimeout(a,0);if((l===e||!l)&&setTimeout)return l=setTimeout,setTimeout(a,0);try{return l(a,0)}catch(A){try{return l.call(null,a,0)}catch(C){return l.call(this,a,0)}}}function a(a){if(n===
clearTimeout)return clearTimeout(a);if((n===b||!n)&&clearTimeout)return n=clearTimeout,clearTimeout(a);try{return n(a)}catch(A){try{return n.call(null,a)}catch(C){return n.call(this,a)}}}function d(){t&&z&&(t=!1,z.length?p=z.concat(p):x=-1,p.length&&h())}function h(){if(!t){var b=g(d);t=!0;for(var c=p.length;c;){z=p;for(p=[];++x<c;)z&&z[x].run();x=-1;c=p.length}z=null;t=!1;a(b)}}function m(a,b){this.fun=a;this.array=b}function u(){}c=k.exports={};try{var l="function"===typeof setTimeout?setTimeout:
e}catch(v){l=e}try{var n="function"===typeof clearTimeout?clearTimeout:b}catch(v){n=b}var p=[],t=!1,z,x=-1;c.nextTick=function(a){var b=Array(arguments.length-1);if(1<arguments.length)for(var c=1;c<arguments.length;c++)b[c-1]=arguments[c];p.push(new m(a,b));1!==p.length||t||g(h)};m.prototype.run=function(){this.fun.apply(null,this.array)};c.title="browser";c.browser=!0;c.env={};c.argv=[];c.version="";c.versions={};c.on=u;c.addListener=u;c.once=u;c.off=u;c.removeListener=u;c.removeAllListeners=u;c.emit=
u;c.prependListener=u;c.prependOnceListener=u;c.listeners=function(a){return[]};c.binding=function(a){throw Error("process.binding is not supported");};c.cwd=function(){return"/"};c.chdir=function(a){throw Error("process.chdir is not supported");};c.umask=function(){return 0}},{}],48:[function(c,k,f){k.exports=c("./lib/_stream_duplex.js")},{"./lib/_stream_duplex.js":49}],49:[function(c,k,f){function e(a){if(!(this instanceof e))return new e(a);d.call(this,a);h.call(this,a);a&&!1===a.readable&&(this.readable=
!1);a&&!1===a.writable&&(this.writable=!1);this.allowHalfOpen=!0;a&&!1===a.allowHalfOpen&&(this.allowHalfOpen=!1);this.once("end",b)}function b(){this.allowHalfOpen||this._writableState.ended||a(g,this)}function g(a){a.end()}var a=c("process-nextick-args");f=Object.keys||function(a){var b=[],c;for(c in a)b.push(c);return b};k.exports=e;k=c("core-util-is");k.inherits=c("inherits");var d=c("./_stream_readable"),h=c("./_stream_writable");k.inherits(e,d);c=f(h.prototype);for(k=0;k<c.length;k++)f=c[k],
e.prototype[f]||(e.prototype[f]=h.prototype[f]);Object.defineProperty(e.prototype,"destroyed",{get:function(){return void 0===this._readableState||void 0===this._writableState?!1:this._readableState.destroyed&&this._writableState.destroyed},set:function(a){void 0!==this._readableState&&void 0!==this._writableState&&(this._readableState.destroyed=a,this._writableState.destroyed=a)}});e.prototype._destroy=function(b,c){this.push(null);this.end();a(c,b)}},{"./_stream_readable":51,"./_stream_writable":53,
"core-util-is":57,inherits:45,"process-nextick-args":59}],50:[function(c,k,f){function e(c){if(!(this instanceof e))return new e(c);b.call(this,c)}k.exports=e;var b=c("./_stream_transform");k=c("core-util-is");k.inherits=c("inherits");k.inherits(e,b);e.prototype._transform=function(b,a,c){c(null,b)}},{"./_stream_transform":52,"core-util-is":57,inherits:45}],51:[function(c,k,f){(function(e,b){function f(a,b,c){if("function"===typeof a.prependListener)return a.prependListener(b,c);if(a._events&&a._events[b])B(a._events[b])?
a._events[b].unshift(c):a._events[b]=[c,a._events[b]];else a.on(b,c)}function a(a,b){J=J||c("./_stream_duplex");a=a||{};this.objectMode=!!a.objectMode;b instanceof J&&(this.objectMode=this.objectMode||!!a.readableObjectMode);b=a.highWaterMark;var d=this.objectMode?16:16384;this.highWaterMark=b||0===b?b:d;this.highWaterMark=Math.floor(this.highWaterMark);this.buffer=new N;this.length=0;this.pipes=null;this.pipesCount=0;this.flowing=null;this.reading=this.endEmitted=this.ended=!1;this.sync=!0;this.destroyed=
this.resumeScheduled=this.readableListening=this.emittedReadable=this.needReadable=!1;this.defaultEncoding=a.defaultEncoding||"utf8";this.awaitDrain=0;this.readingMore=!1;this.encoding=this.decoder=null;a.encoding&&(L||(L=c("string_decoder/").StringDecoder),this.decoder=new L(a.encoding),this.encoding=a.encoding)}function d(b){J=J||c("./_stream_duplex");if(!(this instanceof d))return new d(b);this._readableState=new a(b,this);this.readable=!0;b&&("function"===typeof b.read&&(this._read=b.read),"function"===
typeof b.destroy&&(this._destroy=b.destroy));I.call(this)}function h(a,b,c,d,e){var f=a._readableState;if(null===b)f.reading=!1,f.ended||(f.decoder&&(b=f.decoder.end())&&b.length&&(f.buffer.push(b),f.length+=f.objectMode?1:b.length),f.ended=!0,l(a));else{if(!e){e=b;var g;K.isBuffer(e)||e instanceof M||"string"===typeof e||void 0===e||f.objectMode||(g=new TypeError("Invalid non-string/buffer chunk"));var h=g}h?a.emit("error",h):f.objectMode||b&&0<b.length?("string"===typeof b||f.objectMode||Object.getPrototypeOf(b)===
K.prototype||(b=K.from(b)),d?f.endEmitted?a.emit("error",Error("stream.unshift() after end event")):m(a,f,b,!0):f.ended?a.emit("error",Error("stream.push() after EOF")):(f.reading=!1,f.decoder&&!c?(b=f.decoder.write(b),f.objectMode||0!==b.length?m(a,f,b,!1):f.readingMore||(f.readingMore=!0,y(p,a,f))):m(a,f,b,!1))):d||(f.reading=!1)}return!f.ended&&(f.needReadable||f.length<f.highWaterMark||0===f.length)}function m(a,b,c,d){b.flowing&&0===b.length&&!b.sync?(a.emit("data",c),a.read(0)):(b.length+=b.objectMode?
1:c.length,d?b.buffer.unshift(c):b.buffer.push(c),b.needReadable&&l(a));b.readingMore||(b.readingMore=!0,y(p,a,b))}function u(a,b){if(0>=a||0===b.length&&b.ended)return 0;if(b.objectMode)return 1;if(a!==a)return b.flowing&&b.length?b.buffer.head.data.length:b.length;if(a>b.highWaterMark){var c=a;8388608<=c?c=8388608:(c--,c|=c>>>1,c|=c>>>2,c|=c>>>4,c|=c>>>8,c|=c>>>16,c++);b.highWaterMark=c}return a<=b.length?a:b.ended?b.length:(b.needReadable=!0,0)}function l(a){var b=a._readableState;b.needReadable=
!1;b.emittedReadable||(w("emitReadable",b.flowing),b.emittedReadable=!0,b.sync?y(n,a):n(a))}function n(a){w("emit readable");a.emit("readable");v(a)}function p(a,b){for(var c=b.length;!b.reading&&!b.flowing&&!b.ended&&b.length<b.highWaterMark&&(w("maybeReadMore read 0"),a.read(0),c!==b.length);)c=b.length;b.readingMore=!1}function t(a){return function(){var b=a._readableState;w("pipeOnDrain",b.awaitDrain);b.awaitDrain&&b.awaitDrain--;0===b.awaitDrain&&a.listeners("data").length&&(b.flowing=!0,v(a))}}
function z(a){w("readable nexttick read 0");a.read(0)}function x(a,b){b.reading||(w("resume read 0"),a.read(0));b.resumeScheduled=!1;b.awaitDrain=0;a.emit("resume");v(a);b.flowing&&!b.reading&&a.read(0)}function v(a){var b=a._readableState;for(w("flow",b.flowing);b.flowing&&null!==a.read(););}function A(a,b){if(0===b.length)return null;if(b.objectMode)var c=b.buffer.shift();else if(!a||a>=b.length)c=b.decoder?b.buffer.join(""):1===b.buffer.length?b.buffer.head.data:b.buffer.concat(b.length),b.buffer.clear();
else{c=b.buffer;b=b.decoder;if(a<c.head.data.length)b=c.head.data.slice(0,a),c.head.data=c.head.data.slice(a);else{if(a===c.head.data.length)c=c.shift();else if(b){b=c.head;var d=1,e=b.data;for(a-=e.length;b=b.next;){var f=b.data,g=a>f.length?f.length:a;e=g===f.length?e+f:e+f.slice(0,a);a-=g;if(0===a){g===f.length?(++d,c.head=b.next?b.next:c.tail=null):(c.head=b,b.data=f.slice(g));break}++d}c.length-=d;c=e}else{b=K.allocUnsafe(a);d=c.head;e=1;d.data.copy(b);for(a-=d.data.length;d=d.next;){f=d.data;
g=a>f.length?f.length:a;f.copy(b,b.length-a,0,g);a-=g;if(0===a){g===f.length?(++e,c.head=d.next?d.next:c.tail=null):(c.head=d,d.data=f.slice(g));break}++e}c.length-=e;c=b}b=c}c=b}return c}function C(a){var b=a._readableState;if(0<b.length)throw Error('"endReadable()" called on non-empty stream');b.endEmitted||(b.ended=!0,y(D,b,a))}function D(a,b){a.endEmitted||0!==a.length||(a.endEmitted=!0,b.readable=!1,b.emit("end"))}function G(a,b){for(var c=0,d=a.length;c<d;c++)if(a[c]===b)return c;return-1}var y=
c("process-nextick-args");k.exports=d;var B=c("isarray"),J;d.ReadableState=a;c("events");var I=c("./internal/streams/stream"),K=c("safe-buffer").Buffer,M=b.Uint8Array||function(){};b=c("core-util-is");b.inherits=c("inherits");var H=c("util"),w=void 0;w=H&&H.debuglog?H.debuglog("stream"):function(){};var N=c("./internal/streams/BufferList");H=c("./internal/streams/destroy");var L;b.inherits(d,I);var E=["error","close","destroy","pause","resume"];Object.defineProperty(d.prototype,"destroyed",{get:function(){return void 0===
this._readableState?!1:this._readableState.destroyed},set:function(a){this._readableState&&(this._readableState.destroyed=a)}});d.prototype.destroy=H.destroy;d.prototype._undestroy=H.undestroy;d.prototype._destroy=function(a,b){this.push(null);b(a)};d.prototype.push=function(a,b){var c=this._readableState;if(c.objectMode)var d=!0;else"string"===typeof a&&(b=b||c.defaultEncoding,b!==c.encoding&&(a=K.from(a,b),b=""),d=!0);return h(this,a,b,!1,d)};d.prototype.unshift=function(a){return h(this,a,null,
!0,!1)};d.prototype.isPaused=function(){return!1===this._readableState.flowing};d.prototype.setEncoding=function(a){L||(L=c("string_decoder/").StringDecoder);this._readableState.decoder=new L(a);this._readableState.encoding=a;return this};d.prototype.read=function(a){w("read",a);a=parseInt(a,10);var b=this._readableState,c=a;0!==a&&(b.emittedReadable=!1);if(0===a&&b.needReadable&&(b.length>=b.highWaterMark||b.ended))return w("read: emitReadable",b.length,b.ended),0===b.length&&b.ended?C(this):l(this),
null;a=u(a,b);if(0===a&&b.ended)return 0===b.length&&C(this),null;var d=b.needReadable;w("need readable",d);if(0===b.length||b.length-a<b.highWaterMark)d=!0,w("length less than watermark",d);b.ended||b.reading?w("reading or ended",!1):d&&(w("do read"),b.reading=!0,b.sync=!0,0===b.length&&(b.needReadable=!0),this._read(b.highWaterMark),b.sync=!1,b.reading||(a=u(c,b)));d=0<a?A(a,b):null;null===d?(b.needReadable=!0,a=0):b.length-=a;0===b.length&&(b.ended||(b.needReadable=!0),c!==a&&b.ended&&C(this));
null!==d&&this.emit("data",d);return d};d.prototype._read=function(a){this.emit("error",Error("_read() is not implemented"))};d.prototype.pipe=function(a,b){function c(b,e){w("onunpipe");b===x&&e&&!1===e.hasUnpiped&&(e.hasUnpiped=!0,w("cleanup"),a.removeListener("close",k),a.removeListener("finish",l),a.removeListener("drain",q),a.removeListener("error",h),a.removeListener("unpipe",c),x.removeListener("end",d),x.removeListener("end",m),x.removeListener("data",g),J=!0,!B.awaitDrain||a._writableState&&
!a._writableState.needDrain||q())}function d(){w("onend");a.end()}function g(b){w("ondata");n=!1;!1!==a.write(b)||n||((1===B.pipesCount&&B.pipes===a||1<B.pipesCount&&-1!==G(B.pipes,a))&&!J&&(w("false write response, pause",x._readableState.awaitDrain),x._readableState.awaitDrain++,n=!0),x.pause())}function h(b){w("onerror",b);m();a.removeListener("error",h);0===a.listeners("error").length&&a.emit("error",b)}function k(){a.removeListener("finish",l);m()}function l(){w("onfinish");a.removeListener("close",
k);m()}function m(){w("unpipe");x.unpipe(a)}var x=this,B=this._readableState;switch(B.pipesCount){case 0:B.pipes=a;break;case 1:B.pipes=[B.pipes,a];break;default:B.pipes.push(a)}B.pipesCount+=1;w("pipe count=%d opts=%j",B.pipesCount,b);b=b&&!1===b.end||a===e.stdout||a===e.stderr?m:d;if(B.endEmitted)y(b);else x.once("end",b);a.on("unpipe",c);var q=t(x);a.on("drain",q);var J=!1,n=!1;x.on("data",g);f(a,"error",h);a.once("close",k);a.once("finish",l);a.emit("pipe",x);B.flowing||(w("pipe resume"),x.resume());
return a};d.prototype.unpipe=function(a){var b=this._readableState,c={hasUnpiped:!1};if(0===b.pipesCount)return this;if(1===b.pipesCount){if(a&&a!==b.pipes)return this;a||(a=b.pipes);b.pipes=null;b.pipesCount=0;b.flowing=!1;a&&a.emit("unpipe",this,c);return this}if(!a){a=b.pipes;var d=b.pipesCount;b.pipes=null;b.pipesCount=0;b.flowing=!1;for(b=0;b<d;b++)a[b].emit("unpipe",this,c);return this}d=G(b.pipes,a);if(-1===d)return this;b.pipes.splice(d,1);--b.pipesCount;1===b.pipesCount&&(b.pipes=b.pipes[0]);
a.emit("unpipe",this,c);return this};d.prototype.on=function(a,b){b=I.prototype.on.call(this,a,b);"data"===a?!1!==this._readableState.flowing&&this.resume():"readable"===a&&(a=this._readableState,a.endEmitted||a.readableListening||(a.readableListening=a.needReadable=!0,a.emittedReadable=!1,a.reading?a.length&&l(this):y(z,this)));return b};d.prototype.addListener=d.prototype.on;d.prototype.resume=function(){var a=this._readableState;a.flowing||(w("resume"),a.flowing=!0,a.resumeScheduled||(a.resumeScheduled=
!0,y(x,this,a)));return this};d.prototype.pause=function(){w("call pause flowing=%j",this._readableState.flowing);!1!==this._readableState.flowing&&(w("pause"),this._readableState.flowing=!1,this.emit("pause"));return this};d.prototype.wrap=function(a){var b=this._readableState,c=!1,d=this;a.on("end",function(){w("wrapped end");if(b.decoder&&!b.ended){var a=b.decoder.end();a&&a.length&&d.push(a)}d.push(null)});a.on("data",function(e){w("wrapped data");b.decoder&&(e=b.decoder.write(e));b.objectMode&&
(null===e||void 0===e)||!(b.objectMode||e&&e.length)||d.push(e)||(c=!0,a.pause())});for(var e in a)void 0===this[e]&&"function"===typeof a[e]&&(this[e]=function(b){return function(){return a[b].apply(a,arguments)}}(e));for(e=0;e<E.length;e++)a.on(E[e],d.emit.bind(d,E[e]));d._read=function(b){w("wrapped _read",b);c&&(c=!1,a.resume())};return d};d._fromList=A}).call(this,c("_process"),"undefined"!==typeof global?global:"undefined"!==typeof self?self:"undefined"!==typeof window?window:{})},{"./_stream_duplex":49,
"./internal/streams/BufferList":54,"./internal/streams/destroy":55,"./internal/streams/stream":56,_process:47,"core-util-is":57,events:44,inherits:45,isarray:58,"process-nextick-args":59,"safe-buffer":60,"string_decoder/":67,util:40}],52:[function(c,k,f){function e(a){this.afterTransform=function(b,c){var d=a._transformState;d.transforming=!1;var e=d.writecb;e?(d.writechunk=null,d.writecb=null,null!==c&&void 0!==c&&a.push(c),e(b),b=a._readableState,b.reading=!1,(b.needReadable||b.length<b.highWaterMark)&&
a._read(b.highWaterMark),b=void 0):b=a.emit("error",Error("write callback called multiple times"));return b};this.transforming=this.needTransform=!1;this.writeencoding=this.writechunk=this.writecb=null}function b(c){if(!(this instanceof b))return new b(c);a.call(this,c);this._transformState=new e(this);var d=this;this._readableState.needReadable=!0;this._readableState.sync=!1;c&&("function"===typeof c.transform&&(this._transform=c.transform),"function"===typeof c.flush&&(this._flush=c.flush));this.once("prefinish",
function(){"function"===typeof this._flush?this._flush(function(a,b){g(d,a,b)}):g(d)})}function g(a,b,c){if(b)return a.emit("error",b);null!==c&&void 0!==c&&a.push(c);b=a._transformState;if(a._writableState.length)throw Error("Calling transform done when ws.length != 0");if(b.transforming)throw Error("Calling transform done when still transforming");return a.push(null)}k.exports=b;var a=c("./_stream_duplex");k=c("core-util-is");k.inherits=c("inherits");k.inherits(b,a);b.prototype.push=function(b,
c){this._transformState.needTransform=!1;return a.prototype.push.call(this,b,c)};b.prototype._transform=function(a,b,c){throw Error("_transform() is not implemented");};b.prototype._write=function(a,b,c){var d=this._transformState;d.writecb=c;d.writechunk=a;d.writeencoding=b;d.transforming||(a=this._readableState,(d.needTransform||a.needReadable||a.length<a.highWaterMark)&&this._read(a.highWaterMark))};b.prototype._read=function(a){a=this._transformState;null!==a.writechunk&&a.writecb&&!a.transforming?
(a.transforming=!0,this._transform(a.writechunk,a.writeencoding,a.afterTransform)):a.needTransform=!0};b.prototype._destroy=function(b,c){var d=this;a.prototype._destroy.call(this,b,function(a){c(a);d.emit("close")})}},{"./_stream_duplex":49,"core-util-is":57,inherits:45}],53:[function(c,k,f){(function(e,b){function f(a){var b=this;this.entry=this.next=null;this.finish=function(){var c=b.entry;for(b.entry=null;c;){var d=c.callback;a.pendingcb--;d(void 0);c=c.next}a.corkedRequestsFree?a.corkedRequestsFree.next=
b:a.corkedRequestsFree=b}}function a(){}function d(a,b){v=v||c("./_stream_duplex");a=a||{};this.objectMode=!!a.objectMode;b instanceof v&&(this.objectMode=this.objectMode||!!a.writableObjectMode);var d=a.highWaterMark,e=this.objectMode?16:16384;this.highWaterMark=d||0===d?d:e;this.highWaterMark=Math.floor(this.highWaterMark);this.destroyed=this.finished=this.ended=this.ending=this.needDrain=this.finalCalled=!1;this.decodeStrings=!1!==a.decodeStrings;this.defaultEncoding=a.defaultEncoding||"utf8";
this.length=0;this.writing=!1;this.corked=0;this.sync=!0;this.bufferProcessing=!1;this.onwrite=function(a){var c=b._writableState,d=c.sync,e=c.writecb;c.writing=!1;c.writecb=null;c.length-=c.writelen;c.writelen=0;a?(--c.pendingcb,d?(z(e,a),z(t,b,c),b._writableState.errorEmitted=!0,b.emit("error",a)):(e(a),b._writableState.errorEmitted=!0,b.emit("error",a),t(b,c))):((a=n(c))||c.corked||c.bufferProcessing||!c.bufferedRequest||l(b,c),d?x(u,b,c,a,e):u(b,c,a,e))};this.writecb=null;this.writelen=0;this.lastBufferedRequest=
this.bufferedRequest=null;this.pendingcb=0;this.errorEmitted=this.prefinished=!1;this.bufferedRequestCount=0;this.corkedRequestsFree=new f(this)}function h(a){v=v||c("./_stream_duplex");if(!(y.call(h,this)||this instanceof v))return new h(a);this._writableState=new d(a,this);this.writable=!0;a&&("function"===typeof a.write&&(this._write=a.write),"function"===typeof a.writev&&(this._writev=a.writev),"function"===typeof a.destroy&&(this._destroy=a.destroy),"function"===typeof a.final&&(this._final=
a.final));C.call(this)}function m(a,b,c,d,e,f,g){b.writelen=d;b.writecb=g;b.writing=!0;b.sync=!0;c?a._writev(e,b.onwrite):a._write(e,f,b.onwrite);b.sync=!1}function u(a,b,c,d){!c&&0===b.length&&b.needDrain&&(b.needDrain=!1,a.emit("drain"));b.pendingcb--;d();t(a,b)}function l(a,b){b.bufferProcessing=!0;var c=b.bufferedRequest;if(a._writev&&c&&c.next){var d=Array(b.bufferedRequestCount),e=b.corkedRequestsFree;e.entry=c;for(var g=0,h=!0;c;)d[g]=c,c.isBuf||(h=!1),c=c.next,g+=1;d.allBuffers=h;m(a,b,!0,
b.length,d,"",e.finish);b.pendingcb++;b.lastBufferedRequest=null;e.next?(b.corkedRequestsFree=e.next,e.next=null):b.corkedRequestsFree=new f(b)}else{for(;c&&(d=c.chunk,m(a,b,!1,b.objectMode?1:d.length,d,c.encoding,c.callback),c=c.next,!b.writing););null===c&&(b.lastBufferedRequest=null)}b.bufferedRequestCount=0;b.bufferedRequest=c;b.bufferProcessing=!1}function n(a){return a.ending&&0===a.length&&null===a.bufferedRequest&&!a.finished&&!a.writing}function p(a,b){a._final(function(c){b.pendingcb--;
c&&a.emit("error",c);b.prefinished=!0;a.emit("prefinish");t(a,b)})}function t(a,b){var c=n(b);c&&(b.prefinished||b.finalCalled||("function"===typeof a._final?(b.pendingcb++,b.finalCalled=!0,z(p,a,b)):(b.prefinished=!0,a.emit("prefinish"))),0===b.pendingcb&&(b.finished=!0,a.emit("finish")));return c}var z=c("process-nextick-args");k.exports=h;var x=!e.browser&&-1<["v0.10","v0.9."].indexOf(e.version.slice(0,5))?setImmediate:z,v;h.WritableState=d;e=c("core-util-is");e.inherits=c("inherits");var A={deprecate:c("util-deprecate")},
C=c("./internal/streams/stream"),D=c("safe-buffer").Buffer,G=b.Uint8Array||function(){};b=c("./internal/streams/destroy");e.inherits(h,C);d.prototype.getBuffer=function(){for(var a=this.bufferedRequest,b=[];a;)b.push(a),a=a.next;return b};(function(){try{Object.defineProperty(d.prototype,"buffer",{get:A.deprecate(function(){return this.getBuffer()},"_writableState.buffer is deprecated. Use _writableState.getBuffer instead.","DEP0003")})}catch(B){}})();if("function"===typeof Symbol&&Symbol.hasInstance&&
"function"===typeof Function.prototype[Symbol.hasInstance]){var y=Function.prototype[Symbol.hasInstance];Object.defineProperty(h,Symbol.hasInstance,{value:function(a){return y.call(this,a)?!0:a&&a._writableState instanceof d}})}else y=function(a){return a instanceof this};h.prototype.pipe=function(){this.emit("error",Error("Cannot pipe, not readable"))};h.prototype.write=function(b,c,d){var e=this._writableState,f=!1,g=b;(g=(D.isBuffer(g)||g instanceof G)&&!e.objectMode)&&!D.isBuffer(b)&&(b=D.from(b));
"function"===typeof c&&(d=c,c=null);g?c="buffer":c||(c=e.defaultEncoding);"function"!==typeof d&&(d=a);if(e.ended)e=d,d=Error("write after end"),this.emit("error",d),z(e,d);else{var h;if(!(h=g)){h=b;var k=d,l=!0,x=!1;null===h?x=new TypeError("May not write null values to stream"):"string"===typeof h||void 0===h||e.objectMode||(x=new TypeError("Invalid non-string/buffer chunk"));x&&(this.emit("error",x),z(k,x),l=!1);h=l}h&&(e.pendingcb++,f=g,f||(g=b,e.objectMode||!1===e.decodeStrings||"string"!==typeof g||
(g=D.from(g,c)),b!==g&&(f=!0,c="buffer",b=g)),h=e.objectMode?1:b.length,e.length+=h,g=e.length<e.highWaterMark,g||(e.needDrain=!0),e.writing||e.corked?(h=e.lastBufferedRequest,e.lastBufferedRequest={chunk:b,encoding:c,isBuf:f,callback:d,next:null},h?h.next=e.lastBufferedRequest:e.bufferedRequest=e.lastBufferedRequest,e.bufferedRequestCount+=1):m(this,e,!1,h,b,c,d),f=g)}return f};h.prototype.cork=function(){this._writableState.corked++};h.prototype.uncork=function(){var a=this._writableState;a.corked&&
(a.corked--,a.writing||a.corked||a.finished||a.bufferProcessing||!a.bufferedRequest||l(this,a))};h.prototype.setDefaultEncoding=function(a){"string"===typeof a&&(a=a.toLowerCase());if(!(-1<"hex utf8 utf-8 ascii binary base64 ucs2 ucs-2 utf16le utf-16le raw".split(" ").indexOf((a+"").toLowerCase())))throw new TypeError("Unknown encoding: "+a);this._writableState.defaultEncoding=a;return this};h.prototype._write=function(a,b,c){c(Error("_write() is not implemented"))};h.prototype._writev=null;h.prototype.end=
function(a,b,c){var d=this._writableState;"function"===typeof a?(c=a,b=a=null):"function"===typeof b&&(c=b,b=null);null!==a&&void 0!==a&&this.write(a,b);d.corked&&(d.corked=1,this.uncork());if(!d.ending&&!d.finished){a=c;d.ending=!0;t(this,d);if(a)if(d.finished)z(a);else this.once("finish",a);d.ended=!0;this.writable=!1}};Object.defineProperty(h.prototype,"destroyed",{get:function(){return void 0===this._writableState?!1:this._writableState.destroyed},set:function(a){this._writableState&&(this._writableState.destroyed=
a)}});h.prototype.destroy=b.destroy;h.prototype._undestroy=b.undestroy;h.prototype._destroy=function(a,b){this.end();b(a)}}).call(this,c("_process"),"undefined"!==typeof global?global:"undefined"!==typeof self?self:"undefined"!==typeof window?window:{})},{"./_stream_duplex":49,"./internal/streams/destroy":55,"./internal/streams/stream":56,_process:47,"core-util-is":57,inherits:45,"process-nextick-args":59,"safe-buffer":60,"util-deprecate":61}],54:[function(c,k,f){var e=c("safe-buffer").Buffer;k.exports=
function(){function b(){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");this.tail=this.head=null;this.length=0}b.prototype.push=function(b){b={data:b,next:null};0<this.length?this.tail.next=b:this.head=b;this.tail=b;++this.length};b.prototype.unshift=function(b){b={data:b,next:this.head};0===this.length&&(this.tail=b);this.head=b;++this.length};b.prototype.shift=function(){if(0!==this.length){var b=this.head.data;this.head=1===this.length?this.tail=null:this.head.next;
--this.length;return b}};b.prototype.clear=function(){this.head=this.tail=null;this.length=0};b.prototype.join=function(b){if(0===this.length)return"";for(var a=this.head,c=""+a.data;a=a.next;)c+=b+a.data;return c};b.prototype.concat=function(b){if(0===this.length)return e.alloc(0);if(1===this.length)return this.head.data;b=e.allocUnsafe(b>>>0);for(var a=this.head,c=0;a;)a.data.copy(b,c),c+=a.data.length,a=a.next;return b};return b}()},{"safe-buffer":60}],55:[function(c,k,f){function e(b,a){b.emit("error",
a)}var b=c("process-nextick-args");k.exports={destroy:function(c,a){var d=this,f=this._writableState&&this._writableState.destroyed;this._readableState&&this._readableState.destroyed||f?a?a(c):!c||this._writableState&&this._writableState.errorEmitted||b(e,this,c):(this._readableState&&(this._readableState.destroyed=!0),this._writableState&&(this._writableState.destroyed=!0),this._destroy(c||null,function(c){!a&&c?(b(e,d,c),d._writableState&&(d._writableState.errorEmitted=!0)):a&&a(c)}))},undestroy:function(){this._readableState&&
(this._readableState.destroyed=!1,this._readableState.reading=!1,this._readableState.ended=!1,this._readableState.endEmitted=!1);this._writableState&&(this._writableState.destroyed=!1,this._writableState.ended=!1,this._writableState.ending=!1,this._writableState.finished=!1,this._writableState.errorEmitted=!1)}}},{"process-nextick-args":59}],56:[function(c,k,f){k.exports=c("events").EventEmitter},{events:44}],57:[function(c,k,f){(function(c){f.isArray=function(b){return Array.isArray?Array.isArray(b):
"[object Array]"===Object.prototype.toString.call(b)};f.isBoolean=function(b){return"boolean"===typeof b};f.isNull=function(b){return null===b};f.isNullOrUndefined=function(b){return null==b};f.isNumber=function(b){return"number"===typeof b};f.isString=function(b){return"string"===typeof b};f.isSymbol=function(b){return"symbol"===typeof b};f.isUndefined=function(b){return void 0===b};f.isRegExp=function(b){return"[object RegExp]"===Object.prototype.toString.call(b)};f.isObject=function(b){return"object"===
typeof b&&null!==b};f.isDate=function(b){return"[object Date]"===Object.prototype.toString.call(b)};f.isError=function(b){return"[object Error]"===Object.prototype.toString.call(b)||b instanceof Error};f.isFunction=function(b){return"function"===typeof b};f.isPrimitive=function(b){return null===b||"boolean"===typeof b||"number"===typeof b||"string"===typeof b||"symbol"===typeof b||"undefined"===typeof b};f.isBuffer=c.isBuffer}).call(this,{isBuffer:c("../../../../insert-module-globals/node_modules/is-buffer/index.js")})},
{"../../../../insert-module-globals/node_modules/is-buffer/index.js":46}],58:[function(c,k,f){var e={}.toString;k.exports=Array.isArray||function(b){return"[object Array]"==e.call(b)}},{}],59:[function(c,k,f){(function(c){function b(b,a,d,e){if("function"!==typeof b)throw new TypeError('"callback" argument must be a function');var f=arguments.length;switch(f){case 0:case 1:return c.nextTick(b);case 2:return c.nextTick(function(){b.call(null,a)});case 3:return c.nextTick(function(){b.call(null,a,d)});
case 4:return c.nextTick(function(){b.call(null,a,d,e)});default:var g=Array(f-1);for(f=0;f<g.length;)g[f++]=arguments[f];return c.nextTick(function(){b.apply(null,g)})}}!c.version||0===c.version.indexOf("v0.")||0===c.version.indexOf("v1.")&&0!==c.version.indexOf("v1.8.")?k.exports=b:k.exports=c.nextTick}).call(this,c("_process"))},{_process:47}],60:[function(c,k,f){function e(a,b){for(var c in a)b[c]=a[c]}function b(b,c,e){return a(b,c,e)}var g=c("buffer"),a=g.Buffer;a.from&&a.alloc&&a.allocUnsafe&&
a.allocUnsafeSlow?k.exports=g:(e(g,f),f.Buffer=b);e(a,b);b.from=function(b,c,e){if("number"===typeof b)throw new TypeError("Argument must not be a number");return a(b,c,e)};b.alloc=function(b,c,e){if("number"!==typeof b)throw new TypeError("Argument must be a number");b=a(b);void 0!==c?"string"===typeof e?b.fill(c,e):b.fill(c):b.fill(0);return b};b.allocUnsafe=function(b){if("number"!==typeof b)throw new TypeError("Argument must be a number");return a(b)};b.allocUnsafeSlow=function(a){if("number"!==
typeof a)throw new TypeError("Argument must be a number");return g.SlowBuffer(a)}},{buffer:41}],61:[function(c,k,f){(function(c){function b(b){try{if(!c.localStorage)return!1}catch(a){return!1}b=c.localStorage[b];return null==b?!1:"true"===String(b).toLowerCase()}k.exports=function(c,a){if(b("noDeprecation"))return c;var d=!1;return function(){if(!d){if(b("throwDeprecation"))throw Error(a);b("traceDeprecation")?console.trace(a):console.warn(a);d=!0}return c.apply(this,arguments)}}}).call(this,"undefined"!==
typeof global?global:"undefined"!==typeof self?self:"undefined"!==typeof window?window:{})},{}],62:[function(c,k,f){k.exports=c("./readable").PassThrough},{"./readable":63}],63:[function(c,k,f){f=k.exports=c("./lib/_stream_readable.js");f.Stream=f;f.Readable=f;f.Writable=c("./lib/_stream_writable.js");f.Duplex=c("./lib/_stream_duplex.js");f.Transform=c("./lib/_stream_transform.js");f.PassThrough=c("./lib/_stream_passthrough.js")},{"./lib/_stream_duplex.js":49,"./lib/_stream_passthrough.js":50,"./lib/_stream_readable.js":51,
"./lib/_stream_transform.js":52,"./lib/_stream_writable.js":53}],64:[function(c,k,f){k.exports=c("./readable").Transform},{"./readable":63}],65:[function(c,k,f){k.exports=c("./lib/_stream_writable.js")},{"./lib/_stream_writable.js":53}],66:[function(c,k,f){function e(){b.call(this)}k.exports=e;var b=c("events").EventEmitter;c("inherits")(e,b);e.Readable=c("readable-stream/readable.js");e.Writable=c("readable-stream/writable.js");e.Duplex=c("readable-stream/duplex.js");e.Transform=c("readable-stream/transform.js");
e.PassThrough=c("readable-stream/passthrough.js");e.Stream=e;e.prototype.pipe=function(c,a){function d(a){c.writable&&!1===c.write(a)&&p.pause&&p.pause()}function e(){p.readable&&p.resume&&p.resume()}function f(){t||(t=!0,c.end())}function g(){t||(t=!0,"function"===typeof c.destroy&&c.destroy())}function k(a){n();if(0===b.listenerCount(this,"error"))throw a;}function n(){p.removeListener("data",d);c.removeListener("drain",e);p.removeListener("end",f);p.removeListener("close",g);p.removeListener("error",
k);c.removeListener("error",k);p.removeListener("end",n);p.removeListener("close",n);c.removeListener("close",n)}var p=this;p.on("data",d);c.on("drain",e);c._isStdio||a&&!1===a.end||(p.on("end",f),p.on("close",g));var t=!1;p.on("error",k);c.on("error",k);p.on("end",n);p.on("close",n);c.on("close",n);c.emit("pipe",p);return c}},{events:44,inherits:45,"readable-stream/duplex.js":48,"readable-stream/passthrough.js":62,"readable-stream/readable.js":63,"readable-stream/transform.js":64,"readable-stream/writable.js":65}],
67:[function(c,k,f){function e(a){if(!a)return"utf8";for(var b;;)switch(a){case "utf8":case "utf-8":return"utf8";case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":return"utf16le";case "latin1":case "binary":return"latin1";case "base64":case "ascii":case "hex":return a;default:if(b)return;a=(""+a).toLowerCase();b=!0}}function b(a){var b=e(a);if("string"!==typeof b&&(t.isEncoding===z||!z(a)))throw Error("Unknown encoding: "+a);this.encoding=b||a;switch(this.encoding){case "utf16le":this.text=
h;this.end=m;a=4;break;case "utf8":this.fillLast=d;a=4;break;case "base64":this.text=u;this.end=l;a=3;break;default:this.write=n;this.end=p;return}this.lastTotal=this.lastNeed=0;this.lastChar=t.allocUnsafe(a)}function g(a){return 127>=a?0:6===a>>5?2:14===a>>4?3:30===a>>3?4:-1}function a(a,b,c){var d=b.length-1;if(d<c)return 0;var e=g(b[d]);if(0<=e)return 0<e&&(a.lastNeed=e-1),e;if(--d<c)return 0;e=g(b[d]);if(0<=e)return 0<e&&(a.lastNeed=e-2),e;if(--d<c)return 0;e=g(b[d]);return 0<=e?(0<e&&(2===e?
e=0:a.lastNeed=e-3),e):0}function d(a){var b=this.lastTotal-this.lastNeed;a:if(128!==(a[0]&192)){this.lastNeed=0;var c="\ufffd".repeat(b)}else{if(1<this.lastNeed&&1<a.length){if(128!==(a[1]&192)){this.lastNeed=1;c="\ufffd".repeat(b+1);break a}if(2<this.lastNeed&&2<a.length&&128!==(a[2]&192)){this.lastNeed=2;c="\ufffd".repeat(b+2);break a}}c=void 0}if(void 0!==c)return c;if(this.lastNeed<=a.length)return a.copy(this.lastChar,b,0,this.lastNeed),this.lastChar.toString(this.encoding,0,this.lastTotal);
a.copy(this.lastChar,b,0,a.length);this.lastNeed-=a.length}function h(a,b){if(0===(a.length-b)%2){if(b=a.toString("utf16le",b)){var c=b.charCodeAt(b.length-1);if(55296<=c&&56319>=c)return this.lastNeed=2,this.lastTotal=4,this.lastChar[0]=a[a.length-2],this.lastChar[1]=a[a.length-1],b.slice(0,-1)}return b}this.lastNeed=1;this.lastTotal=2;this.lastChar[0]=a[a.length-1];return a.toString("utf16le",b,a.length-1)}function m(a){a=a&&a.length?this.write(a):"";return this.lastNeed?a+this.lastChar.toString("utf16le",
0,this.lastTotal-this.lastNeed):a}function u(a,b){var c=(a.length-b)%3;if(0===c)return a.toString("base64",b);this.lastNeed=3-c;this.lastTotal=3;1===c?this.lastChar[0]=a[a.length-1]:(this.lastChar[0]=a[a.length-2],this.lastChar[1]=a[a.length-1]);return a.toString("base64",b,a.length-c)}function l(a){a=a&&a.length?this.write(a):"";return this.lastNeed?a+this.lastChar.toString("base64",0,3-this.lastNeed):a}function n(a){return a.toString(this.encoding)}function p(a){return a&&a.length?this.write(a):
""}var t=c("safe-buffer").Buffer,z=t.isEncoding||function(a){a=""+a;switch(a&&a.toLowerCase()){case "hex":case "utf8":case "utf-8":case "ascii":case "binary":case "base64":case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":case "raw":return!0;default:return!1}};f.StringDecoder=b;b.prototype.write=function(a){if(0===a.length)return"";if(this.lastNeed){var b=this.fillLast(a);if(void 0===b)return"";var c=this.lastNeed;this.lastNeed=0}else c=0;return c<a.length?b?b+this.text(a,c):this.text(a,c):
b||""};b.prototype.end=function(a){a=a&&a.length?this.write(a):"";return this.lastNeed?a+"\ufffd".repeat(this.lastTotal-this.lastNeed):a};b.prototype.text=function(b,c){var d=a(this,b,c);if(!this.lastNeed)return b.toString("utf8",c);this.lastTotal=d;d=b.length-(d-this.lastNeed);b.copy(this.lastChar,0,d);return b.toString("utf8",c,d)};b.prototype.fillLast=function(a){if(this.lastNeed<=a.length)return a.copy(this.lastChar,this.lastTotal-this.lastNeed,0,this.lastNeed),this.lastChar.toString(this.encoding,
0,this.lastTotal);a.copy(this.lastChar,this.lastTotal-this.lastNeed,0,a.length);this.lastNeed-=a.length}},{"safe-buffer":68}],68:[function(c,k,f){arguments[4][60][0].apply(f,arguments)},{buffer:41,dup:60}]},{},[1])(1)});
