/*
 The buffer module from node.js, for the browser.

 @author   Feross Aboukhadijeh <https://feross.org>
 @license  MIT
 Determine if an object is a Buffer

 @author   Feross Aboukhadijeh <https://feross.org>
 @license  MIT
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(r,c,f){r!=Array.prototype&&r!=Object.prototype&&(r[c]=f.value)};$jscomp.getGlobal=function(r){return"undefined"!=typeof window&&window===r?r:"undefined"!=typeof global&&null!=global?global:r};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(r,c,f,h){if(c){f=$jscomp.global;r=r.split(".");for(h=0;h<r.length-1;h++){var b=r[h];b in f||(f[b]={});f=f[b]}r=r[r.length-1];h=f[r];c=c(h);c!=h&&null!=c&&$jscomp.defineProperty(f,r,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.fill",function(r){return r?r:function(c,f,h){var b=this.length||0;0>f&&(f=Math.max(0,b+f));if(null==h||h>b)h=b;h=Number(h);0>h&&(h=Math.max(0,b+h));for(f=Number(f||0);f<h;f++)this[f]=c;return this}},"es6","es3");
$jscomp.arrayIteratorImpl=function(r){var c=0;return function(){return c<r.length?{done:!1,value:r[c++]}:{done:!0}}};$jscomp.arrayIterator=function(r){return{next:$jscomp.arrayIteratorImpl(r)}};$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.SymbolClass=function(r,c){this.$jscomp$symbol$id_=r;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:c})};
$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function r(f){if(this instanceof r)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(f||"")+"_"+c++,f)}var c=0;return r}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var r=$jscomp.global.Symbol.iterator;r||(r=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[r]&&$jscomp.defineProperty(Array.prototype,r,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var r=$jscomp.global.Symbol.asyncIterator;r||(r=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(r){$jscomp.initSymbolIterator();r={next:r};r[$jscomp.global.Symbol.iterator]=function(){return this};return r};
$jscomp.iteratorFromArray=function(r,c){$jscomp.initSymbolIterator();r instanceof String&&(r+="");var f=0,h={next:function(){if(f<r.length){var b=f++;return{value:c(b,r[b]),done:!1}}h.next=function(){return{done:!0,value:void 0}};return h.next()}};h[Symbol.iterator]=function(){return h};return h};$jscomp.polyfill("Array.prototype.keys",function(r){return r?r:function(){return $jscomp.iteratorFromArray(this,function(c){return c})}},"es6","es3");
$jscomp.checkStringArgs=function(r,c,f){if(null==r)throw new TypeError("The 'this' value for String.prototype."+f+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+f+" must not be a regular expression");return r+""};
$jscomp.polyfill("String.prototype.repeat",function(r){return r?r:function(c){var f=$jscomp.checkStringArgs(this,null,"repeat");if(0>c||1342177279<c)throw new RangeError("Invalid count value");c|=0;for(var h="";c;)if(c&1&&(h+=f),c>>>=1)f+=f;return h}},"es6","es3");
(function(r){"object"===typeof exports&&"undefined"!==typeof module?module.exports=r():"function"===typeof define&&define.amd?define([],r):("undefined"!==typeof window?window:"undefined"!==typeof global?global:"undefined"!==typeof self?self:this).CreateHASH=r()})(function(){return function b(c,f,h){function a(d,p){if(!f[d]){if(!c[d]){var l="function"==typeof require&&require;if(!p&&l)return l(d,!0);if(m)return m(d,!0);p=Error("Cannot find module '"+d+"'");throw p.code="MODULE_NOT_FOUND",p;}p=f[d]=
{exports:{}};c[d][0].call(p.exports,function(p){var l=c[d][1][p];return a(l?l:p)},p,p.exports,b,c,f,h)}return f[d].exports}for(var m="function"==typeof require&&require,l=0;l<h.length;l++)a(h[l]);return a}({1:[function(c,f,h){function b(a){d.call(this,"digest");this._hash=a}h=c("inherits");var a=c("md5.js"),m=c("ripemd160"),l=c("sha.js"),d=c("cipher-base");h(b,d);b.prototype._update=function(a){this._hash.update(a)};b.prototype._final=function(){return this._hash.digest()};f.exports=function(d){d=
d.toLowerCase();return"md5"===d?new a:"rmd160"===d||"ripemd160"===d?new m:new b(l(d))}},{"cipher-base":2,inherits:3,"md5.js":4,ripemd160:6,"sha.js":10}],2:[function(c,f,h){function b(a){m.call(this);(this.hashMode="string"===typeof a)?this[a]=this._finalOrDigest:this.final=this._finalOrDigest;this._final&&(this.__final=this._final,this._final=null);this._encoding=this._decoder=null}var a=c("safe-buffer").Buffer,m=c("stream").Transform,l=c("string_decoder").StringDecoder;c("inherits")(b,m);b.prototype.update=
function(d,p,l){"string"===typeof d&&(d=a.from(d,p));d=this._update(d);if(this.hashMode)return this;l&&(d=this._toString(d,l));return d};b.prototype.setAutoPadding=function(){};b.prototype.getAuthTag=function(){throw Error("trying to get auth tag in unsupported state");};b.prototype.setAuthTag=function(){throw Error("trying to set auth tag in unsupported state");};b.prototype.setAAD=function(){throw Error("trying to set aad in unsupported state");};b.prototype._transform=function(a,p,l){try{this.hashMode?
this._update(a):this.push(this._update(a))}catch(q){var d=q}finally{l(d)}};b.prototype._flush=function(a){try{this.push(this.__final())}catch(k){var d=k}a(d)};b.prototype._finalOrDigest=function(d){var p=this.__final()||a.alloc(0);d&&(p=this._toString(p,d,!0));return p};b.prototype._toString=function(a,p,k){this._decoder||(this._decoder=new l(p),this._encoding=p);if(this._encoding!==p)throw Error("can't switch encodings");a=this._decoder.write(a);k&&(a+=this._decoder.end());return a};f.exports=b},
{inherits:3,"safe-buffer":8,stream:43,string_decoder:44}],3:[function(c,f,h){f.exports="function"===typeof Object.create?function(b,a){a&&(b.super_=a,b.prototype=Object.create(a.prototype,{constructor:{value:b,enumerable:!1,writable:!0,configurable:!0}}))}:function(b,a){if(a){b.super_=a;var c=function(){};c.prototype=a.prototype;b.prototype=new c;b.prototype.constructor=b}}},{}],4:[function(c,f,h){function b(){k.call(this,64);this._a=1732584193;this._b=4023233417;this._c=2562383102;this._d=271733878}
function a(a,d){return a<<d|a>>>32-d}function m(d,p,l,k,b,c,q){return a(d+(p&l|~p&k)+b+c|0,q)+p|0}function l(d,p,l,k,b,c,q){return a(d+(p&k|l&~k)+b+c|0,q)+p|0}function d(d,p,l,k,b,c,q){return a(d+(p^l^k)+b+c|0,q)+p|0}function p(d,p,l,k,b,c,q){return a(d+(l^(p|~k))+b+c|0,q)+p|0}h=c("inherits");var k=c("hash-base"),E=c("safe-buffer").Buffer,q=Array(16);h(b,k);b.prototype._update=function(){for(var a=0;16>a;++a)q[a]=this._block.readInt32LE(4*a);a=this._a;var k=this._b,b=this._c,c=this._d;a=m(a,k,b,c,
q[0],3614090360,7);c=m(c,a,k,b,q[1],3905402710,12);b=m(b,c,a,k,q[2],606105819,17);k=m(k,b,c,a,q[3],3250441966,22);a=m(a,k,b,c,q[4],4118548399,7);c=m(c,a,k,b,q[5],1200080426,12);b=m(b,c,a,k,q[6],2821735955,17);k=m(k,b,c,a,q[7],4249261313,22);a=m(a,k,b,c,q[8],1770035416,7);c=m(c,a,k,b,q[9],2336552879,12);b=m(b,c,a,k,q[10],4294925233,17);k=m(k,b,c,a,q[11],2304563134,22);a=m(a,k,b,c,q[12],1804603682,7);c=m(c,a,k,b,q[13],4254626195,12);b=m(b,c,a,k,q[14],2792965006,17);k=m(k,b,c,a,q[15],1236535329,22);
a=l(a,k,b,c,q[1],4129170786,5);c=l(c,a,k,b,q[6],3225465664,9);b=l(b,c,a,k,q[11],643717713,14);k=l(k,b,c,a,q[0],3921069994,20);a=l(a,k,b,c,q[5],3593408605,5);c=l(c,a,k,b,q[10],38016083,9);b=l(b,c,a,k,q[15],3634488961,14);k=l(k,b,c,a,q[4],3889429448,20);a=l(a,k,b,c,q[9],568446438,5);c=l(c,a,k,b,q[14],3275163606,9);b=l(b,c,a,k,q[3],4107603335,14);k=l(k,b,c,a,q[8],1163531501,20);a=l(a,k,b,c,q[13],2850285829,5);c=l(c,a,k,b,q[2],4243563512,9);b=l(b,c,a,k,q[7],1735328473,14);k=l(k,b,c,a,q[12],2368359562,
20);a=d(a,k,b,c,q[5],4294588738,4);c=d(c,a,k,b,q[8],2272392833,11);b=d(b,c,a,k,q[11],1839030562,16);k=d(k,b,c,a,q[14],4259657740,23);a=d(a,k,b,c,q[1],2763975236,4);c=d(c,a,k,b,q[4],1272893353,11);b=d(b,c,a,k,q[7],4139469664,16);k=d(k,b,c,a,q[10],3200236656,23);a=d(a,k,b,c,q[13],681279174,4);c=d(c,a,k,b,q[0],3936430074,11);b=d(b,c,a,k,q[3],3572445317,16);k=d(k,b,c,a,q[6],76029189,23);a=d(a,k,b,c,q[9],3654602809,4);c=d(c,a,k,b,q[12],3873151461,11);b=d(b,c,a,k,q[15],530742520,16);k=d(k,b,c,a,q[2],3299628645,
23);a=p(a,k,b,c,q[0],4096336452,6);c=p(c,a,k,b,q[7],1126891415,10);b=p(b,c,a,k,q[14],2878612391,15);k=p(k,b,c,a,q[5],4237533241,21);a=p(a,k,b,c,q[12],1700485571,6);c=p(c,a,k,b,q[3],2399980690,10);b=p(b,c,a,k,q[10],4293915773,15);k=p(k,b,c,a,q[1],2240044497,21);a=p(a,k,b,c,q[8],1873313359,6);c=p(c,a,k,b,q[15],4264355552,10);b=p(b,c,a,k,q[6],2734768916,15);k=p(k,b,c,a,q[13],1309151649,21);a=p(a,k,b,c,q[4],4149444226,6);c=p(c,a,k,b,q[11],3174756917,10);b=p(b,c,a,k,q[2],718787259,15);k=p(k,b,c,a,q[9],
3951481745,21);this._a=this._a+a|0;this._b=this._b+k|0;this._c=this._c+b|0;this._d=this._d+c|0};b.prototype._digest=function(){this._block[this._blockOffset++]=128;56<this._blockOffset&&(this._block.fill(0,this._blockOffset,64),this._update(),this._blockOffset=0);this._block.fill(0,this._blockOffset,56);this._block.writeUInt32LE(this._length[0],56);this._block.writeUInt32LE(this._length[1],60);this._update();var a=E.allocUnsafe(16);a.writeInt32LE(this._a,0);a.writeInt32LE(this._b,4);a.writeInt32LE(this._c,
8);a.writeInt32LE(this._d,12);return a};f.exports=b},{"hash-base":5,inherits:3,"safe-buffer":8}],5:[function(c,f,h){function b(b){m.call(this);this._block=a.allocUnsafe(b);this._blockSize=b;this._blockOffset=0;this._length=[0,0,0,0];this._finalized=!1}var a=c("safe-buffer").Buffer,m=c("stream").Transform;c("inherits")(b,m);b.prototype._transform=function(a,d,b){var k=null;try{this.update(a,d)}catch(E){k=E}b(k)};b.prototype._flush=function(a){var d=null;try{this.push(this.digest())}catch(p){d=p}a(d)};
b.prototype.update=function(b,d){var c=b;if(!a.isBuffer(c)&&"string"!==typeof c)throw new TypeError("Data must be a string or a buffer");if(this._finalized)throw Error("Digest already called");a.isBuffer(b)||(b=a.from(b,d));d=this._block;for(c=0;this._blockOffset+b.length-c>=this._blockSize;){for(var k=this._blockOffset;k<this._blockSize;)d[k++]=b[c++];this._update();this._blockOffset=0}for(;c<b.length;)d[this._blockOffset++]=b[c++];d=0;for(b=8*b.length;0<b;++d)this._length[d]+=b,b=this._length[d]/
4294967296|0,0<b&&(this._length[d]-=4294967296*b);return this};b.prototype._update=function(){throw Error("_update is not implemented");};b.prototype.digest=function(a){if(this._finalized)throw Error("Digest already called");this._finalized=!0;var b=this._digest();void 0!==a&&(b=b.toString(a));this._block.fill(0);for(a=this._blockOffset=0;4>a;++a)this._length[a]=0;return b};b.prototype._digest=function(){throw Error("_digest is not implemented");};f.exports=b},{inherits:3,"safe-buffer":8,stream:43}],
6:[function(c,f,h){function b(){l.call(this,64);this._a=1732584193;this._b=4023233417;this._c=2562383102;this._d=271733878;this._e=3285377520}function a(a,b){return a<<b|a>>>32-b}var m=c("buffer").Buffer;h=c("inherits");var l=c("hash-base"),d=Array(16),p=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,7,4,13,1,10,6,15,3,12,0,9,5,2,14,11,8,3,10,14,4,9,15,8,1,2,7,0,6,13,11,5,12,1,9,11,10,0,8,12,4,13,3,7,15,14,5,6,2,4,0,5,9,7,12,2,10,14,1,3,8,11,6,15,13],k=[5,14,7,0,9,2,11,4,13,6,15,8,1,10,3,12,6,11,3,7,0,13,
5,10,14,15,8,12,4,9,1,2,15,5,1,3,7,14,6,9,11,8,12,2,10,0,4,13,8,6,4,1,3,11,15,0,5,12,2,13,9,7,10,14,12,15,10,4,1,5,8,7,6,2,13,14,0,3,9,11],E=[11,14,15,12,5,8,7,9,11,13,14,15,6,7,9,8,7,6,8,13,11,9,7,15,7,12,15,9,11,7,13,12,11,13,6,7,14,9,13,15,14,8,13,6,5,12,7,5,11,12,14,15,14,15,9,8,9,14,5,6,8,6,5,12,9,15,5,11,6,8,13,12,5,12,13,14,11,8,5,6],q=[8,9,9,11,13,15,15,5,7,7,8,11,14,14,12,6,9,13,15,7,12,8,9,11,7,7,12,7,6,15,13,11,9,7,15,11,8,6,6,14,12,13,5,14,13,13,7,5,15,5,8,11,14,14,6,14,6,9,12,9,12,5,
15,8,8,5,12,9,12,5,14,6,8,13,6,5,15,13,11,11],A=[0,1518500249,1859775393,2400959708,2840853838],t=[1352829926,1548603684,1836072691,2053994217,0];h(b,l);b.prototype._update=function(){for(var b=0;16>b;++b)d[b]=this._block.readInt32LE(4*b);var c=this._a|0;b=this._b|0;for(var l=this._c|0,m=this._d|0,h=this._e|0,f=this._a|0,I=this._b|0,L=this._c|0,F=this._d|0,B=this._e|0,w=0;80>w;w+=1){if(16>w){var C=h;C=a(c+(b^l^m)+d[p[w]]+A[0]|0,E[w])+C|0;c=B;var M=a(f+(I^(L|~F))+d[k[w]]+t[0]|0,q[w])+c|0}else 32>w?
(C=h,C=a(c+(b&l|~b&m)+d[p[w]]+A[1]|0,E[w])+C|0,c=B,M=a(f+(I&F|L&~F)+d[k[w]]+t[1]|0,q[w])+c|0):48>w?(C=h,C=a(c+((b|~l)^m)+d[p[w]]+A[2]|0,E[w])+C|0,c=B,M=a(f+((I|~L)^F)+d[k[w]]+t[2]|0,q[w])+c|0):64>w?(C=h,C=a(c+(b&m|l&~m)+d[p[w]]+A[3]|0,E[w])+C|0,c=B,M=a(f+(I&L|~I&F)+d[k[w]]+t[3]|0,q[w])+c|0):(C=h,C=a(c+(b^(l|~m))+d[p[w]]+A[4]|0,E[w])+C|0,c=B,M=a(f+(I^L^F)+d[k[w]]+t[4]|0,q[w])+c|0);c=h;h=m;m=a(l,10);l=b;b=C;f=B;B=F;F=a(L,10);L=I;I=M}l=this._b+l+F|0;this._b=this._c+m+B|0;this._c=this._d+h+f|0;this._d=
this._e+c+I|0;this._e=this._a+b+L|0;this._a=l};b.prototype._digest=function(){this._block[this._blockOffset++]=128;56<this._blockOffset&&(this._block.fill(0,this._blockOffset,64),this._update(),this._blockOffset=0);this._block.fill(0,this._blockOffset,56);this._block.writeUInt32LE(this._length[0],56);this._block.writeUInt32LE(this._length[1],60);this._update();var a=m.alloc?m.alloc(20):new m(20);a.writeInt32LE(this._a,0);a.writeInt32LE(this._b,4);a.writeInt32LE(this._c,8);a.writeInt32LE(this._d,12);
a.writeInt32LE(this._e,16);return a};f.exports=b},{buffer:18,"hash-base":7,inherits:3}],7:[function(c,f,h){arguments[4][5][0].apply(h,arguments)},{dup:5,inherits:3,"safe-buffer":8,stream:43}],8:[function(c,f,h){function b(a,b){for(var c in a)b[c]=a[c]}function a(a,b,c){return l(a,b,c)}var m=c("buffer"),l=m.Buffer;l.from&&l.alloc&&l.allocUnsafe&&l.allocUnsafeSlow?f.exports=m:(b(m,h),h.Buffer=a);a.prototype=Object.create(l.prototype);b(l,a);a.from=function(a,b,c){if("number"===typeof a)throw new TypeError("Argument must not be a number");
return l(a,b,c)};a.alloc=function(a,b,c){if("number"!==typeof a)throw new TypeError("Argument must be a number");a=l(a);void 0!==b?"string"===typeof c?a.fill(b,c):a.fill(b):a.fill(0);return a};a.allocUnsafe=function(a){if("number"!==typeof a)throw new TypeError("Argument must be a number");return l(a)};a.allocUnsafeSlow=function(a){if("number"!==typeof a)throw new TypeError("Argument must be a number");return m.SlowBuffer(a)}},{buffer:18}],9:[function(c,f,h){function b(b,c){this._block=a.alloc(b);
this._finalSize=c;this._blockSize=b;this._len=0}var a=c("safe-buffer").Buffer;b.prototype.update=function(b,c){"string"===typeof b&&(b=a.from(b,c||"utf8"));c=this._block;for(var d=this._blockSize,p=b.length,k=this._len,l=0;l<p;){for(var q=k%d,m=Math.min(p-l,d-q),h=0;h<m;h++)c[q+h]=b[l+h];k+=m;l+=m;0===k%d&&this._update(c)}this._len+=p;return this};b.prototype.digest=function(a){var b=this._len%this._blockSize;this._block[b]=128;this._block.fill(0,b+1);b>=this._finalSize&&(this._update(this._block),
this._block.fill(0));b=8*this._len;if(4294967295>=b)this._block.writeUInt32BE(b,this._blockSize-4);else{var c=(b&4294967295)>>>0;this._block.writeUInt32BE((b-c)/4294967296,this._blockSize-8);this._block.writeUInt32BE(c,this._blockSize-4)}this._update(this._block);b=this._hash();return a?b.toString(a):b};b.prototype._update=function(){throw Error("_update must be implemented by subclass");};f.exports=b},{"safe-buffer":8}],10:[function(c,f,h){h=f.exports=function(b){b=b.toLowerCase();var a=h[b];if(!a)throw Error(b+
" is not supported (we accept pull requests)");return new a};h.sha=c("./sha");h.sha1=c("./sha1");h.sha224=c("./sha224");h.sha256=c("./sha256");h.sha384=c("./sha384");h.sha512=c("./sha512")},{"./sha":11,"./sha1":12,"./sha224":13,"./sha256":14,"./sha384":15,"./sha512":16}],11:[function(c,f,h){function b(){this.init();this._w=d;a.call(this,64,56)}h=c("inherits");var a=c("./hash"),m=c("safe-buffer").Buffer,l=[1518500249,1859775393,-1894007588,-899497514],d=Array(80);h(b,a);b.prototype.init=function(){this._a=
1732584193;this._b=4023233417;this._c=2562383102;this._d=271733878;this._e=3285377520;return this};b.prototype._update=function(a){for(var b=this._w,c=this._a|0,d=this._b|0,p=this._c|0,m=this._d|0,h=this._e|0,f=0;16>f;++f)b[f]=a.readInt32BE(4*f);for(;80>f;++f)b[f]=b[f-3]^b[f-8]^b[f-14]^b[f-16];for(a=0;80>a;++a){f=~~(a/20);var H=c<<5|c>>>27;var v=0===f?d&p|~d&m:2===f?d&p|d&m|p&m:d^p^m;f=H+v+h+b[a]+l[f]|0;h=m;m=p;p=d<<30|d>>>2;d=c;c=f}this._a=c+this._a|0;this._b=d+this._b|0;this._c=p+this._c|0;this._d=
m+this._d|0;this._e=h+this._e|0};b.prototype._hash=function(){var a=m.allocUnsafe(20);a.writeInt32BE(this._a|0,0);a.writeInt32BE(this._b|0,4);a.writeInt32BE(this._c|0,8);a.writeInt32BE(this._d|0,12);a.writeInt32BE(this._e|0,16);return a};f.exports=b},{"./hash":9,inherits:3,"safe-buffer":8}],12:[function(c,f,h){function b(){this.init();this._w=d;a.call(this,64,56)}h=c("inherits");var a=c("./hash"),m=c("safe-buffer").Buffer,l=[1518500249,1859775393,-1894007588,-899497514],d=Array(80);h(b,a);b.prototype.init=
function(){this._a=1732584193;this._b=4023233417;this._c=2562383102;this._d=271733878;this._e=3285377520;return this};b.prototype._update=function(a){for(var b=this._w,c=this._a|0,d=this._b|0,p=this._c|0,m=this._d|0,h=this._e|0,f=0;16>f;++f)b[f]=a.readInt32BE(4*f);for(;80>f;++f)a=b[f-3]^b[f-8]^b[f-14]^b[f-16],b[f]=a<<1|a>>>31;for(f=0;80>f;++f){a=~~(f/20);var H=c<<5|c>>>27;var v=0===a?d&p|~d&m:2===a?d&p|d&m|p&m:d^p^m;a=H+v+h+b[f]+l[a]|0;h=m;m=p;p=d<<30|d>>>2;d=c;c=a}this._a=c+this._a|0;this._b=d+this._b|
0;this._c=p+this._c|0;this._d=m+this._d|0;this._e=h+this._e|0};b.prototype._hash=function(){var a=m.allocUnsafe(20);a.writeInt32BE(this._a|0,0);a.writeInt32BE(this._b|0,4);a.writeInt32BE(this._c|0,8);a.writeInt32BE(this._d|0,12);a.writeInt32BE(this._e|0,16);return a};f.exports=b},{"./hash":9,inherits:3,"safe-buffer":8}],13:[function(c,f,h){function b(){this.init();this._w=d;m.call(this,64,56)}h=c("inherits");var a=c("./sha256"),m=c("./hash"),l=c("safe-buffer").Buffer,d=Array(64);h(b,a);b.prototype.init=
function(){this._a=3238371032;this._b=914150663;this._c=812702999;this._d=4144912697;this._e=4290775857;this._f=1750603025;this._g=1694076839;this._h=3204075428;return this};b.prototype._hash=function(){var a=l.allocUnsafe(28);a.writeInt32BE(this._a,0);a.writeInt32BE(this._b,4);a.writeInt32BE(this._c,8);a.writeInt32BE(this._d,12);a.writeInt32BE(this._e,16);a.writeInt32BE(this._f,20);a.writeInt32BE(this._g,24);return a};f.exports=b},{"./hash":9,"./sha256":14,inherits:3,"safe-buffer":8}],14:[function(c,
f,h){function b(){this.init();this._w=d;a.call(this,64,56)}h=c("inherits");var a=c("./hash"),m=c("safe-buffer").Buffer,l=[1116352408,1899447441,3049323471,3921009573,961987163,1508970993,2453635748,2870763221,3624381080,310598401,607225278,1426881987,1925078388,2162078206,2614888103,3248222580,3835390401,4022224774,264347078,604807628,770255983,1249150122,1555081692,1996064986,2554220882,2821834349,2952996808,3210313671,3336571891,3584528711,113926993,338241895,666307205,773529912,1294757372,1396182291,
1695183700,1986661051,2177026350,2456956037,2730485921,2820302411,3259730800,3345764771,3516065817,3600352804,4094571909,275423344,430227734,506948616,659060556,883997877,958139571,1322822218,1537002063,1747873779,1955562222,2024104815,2227730452,2361852424,2428436474,2756734187,3204031479,3329325298],d=Array(64);h(b,a);b.prototype.init=function(){this._a=1779033703;this._b=3144134277;this._c=1013904242;this._d=2773480762;this._e=1359893119;this._f=2600822924;this._g=528734635;this._h=1541459225;
return this};b.prototype._update=function(a){for(var b=this._w,c=this._a|0,d=this._b|0,p=this._c|0,m=this._d|0,f=this._e|0,h=this._f|0,H=this._g|0,v=this._h|0,x=0;16>x;++x)b[x]=a.readInt32BE(4*x);for(;64>x;++x){a=b[x-2];var z=b[x-15];b[x]=((a>>>17|a<<15)^(a>>>19|a<<13)^a>>>10)+b[x-7]+((z>>>7|z<<25)^(z>>>18|z<<14)^z>>>3)+b[x-16]|0}for(x=0;64>x;++x)a=v+((f>>>6|f<<26)^(f>>>11|f<<21)^(f>>>25|f<<7))+(H^f&(h^H))+l[x]+b[x]|0,z=((c>>>2|c<<30)^(c>>>13|c<<19)^(c>>>22|c<<10))+(c&d|p&(c|d))|0,v=H,H=h,h=f,f=m+
a|0,m=p,p=d,d=c,c=a+z|0;this._a=c+this._a|0;this._b=d+this._b|0;this._c=p+this._c|0;this._d=m+this._d|0;this._e=f+this._e|0;this._f=h+this._f|0;this._g=H+this._g|0;this._h=v+this._h|0};b.prototype._hash=function(){var a=m.allocUnsafe(32);a.writeInt32BE(this._a,0);a.writeInt32BE(this._b,4);a.writeInt32BE(this._c,8);a.writeInt32BE(this._d,12);a.writeInt32BE(this._e,16);a.writeInt32BE(this._f,20);a.writeInt32BE(this._g,24);a.writeInt32BE(this._h,28);return a};f.exports=b},{"./hash":9,inherits:3,"safe-buffer":8}],
15:[function(c,f,h){function b(){this.init();this._w=d;m.call(this,128,112)}h=c("inherits");var a=c("./sha512"),m=c("./hash"),l=c("safe-buffer").Buffer,d=Array(160);h(b,a);b.prototype.init=function(){this._ah=3418070365;this._bh=1654270250;this._ch=2438529370;this._dh=355462360;this._eh=1731405415;this._fh=2394180231;this._gh=3675008525;this._hh=1203062813;this._al=3238371032;this._bl=914150663;this._cl=812702999;this._dl=4144912697;this._el=4290775857;this._fl=1750603025;this._gl=1694076839;this._hl=
3204075428;return this};b.prototype._hash=function(){function a(a,c,d){b.writeInt32BE(a,d);b.writeInt32BE(c,d+4)}var b=l.allocUnsafe(48);a(this._ah,this._al,0);a(this._bh,this._bl,8);a(this._ch,this._cl,16);a(this._dh,this._dl,24);a(this._eh,this._el,32);a(this._fh,this._fl,40);return b};f.exports=b},{"./hash":9,"./sha512":16,inherits:3,"safe-buffer":8}],16:[function(c,f,h){function b(){this.init();this._w=p;m.call(this,128,112)}function a(a,b){return a>>>0<b>>>0?1:0}h=c("inherits");var m=c("./hash"),
l=c("safe-buffer").Buffer,d=[1116352408,3609767458,1899447441,602891725,3049323471,3964484399,3921009573,2173295548,961987163,4081628472,1508970993,3053834265,2453635748,2937671579,2870763221,3664609560,3624381080,2734883394,310598401,1164996542,607225278,1323610764,1426881987,3590304994,1925078388,4068182383,2162078206,991336113,2614888103,633803317,3248222580,3479774868,3835390401,2666613458,4022224774,944711139,264347078,2341262773,604807628,2007800933,770255983,1495990901,1249150122,1856431235,
1555081692,3175218132,1996064986,2198950837,2554220882,3999719339,2821834349,766784016,2952996808,2566594879,3210313671,3203337956,3336571891,1034457026,3584528711,2466948901,113926993,3758326383,338241895,168717936,666307205,1188179964,773529912,1546045734,1294757372,1522805485,1396182291,2643833823,1695183700,2343527390,1986661051,1014477480,2177026350,1206759142,2456956037,344077627,2730485921,1290863460,2820302411,3158454273,3259730800,3505952657,3345764771,106217008,3516065817,3606008344,3600352804,
1432725776,4094571909,1467031594,275423344,851169720,430227734,3100823752,506948616,1363258195,659060556,3750685593,883997877,3785050280,958139571,3318307427,1322822218,3812723403,1537002063,2003034995,1747873779,3602036899,1955562222,1575990012,2024104815,1125592928,2227730452,2716904306,2361852424,442776044,2428436474,593698344,2756734187,3733110249,3204031479,2999351573,3329325298,3815920427,3391569614,3928383900,3515267271,566280711,3940187606,3454069534,4118630271,4000239992,116418474,1914138554,
174292421,2731055270,289380356,3203993006,460393269,320620315,685471733,587496836,852142971,1086792851,1017036298,365543100,1126000580,2618297676,1288033470,3409855158,1501505948,4234509866,1607167915,987167468,1816402316,1246189591],p=Array(160);h(b,m);b.prototype.init=function(){this._ah=1779033703;this._bh=3144134277;this._ch=1013904242;this._dh=2773480762;this._eh=1359893119;this._fh=2600822924;this._gh=528734635;this._hh=1541459225;this._al=4089235720;this._bl=2227873595;this._cl=4271175723;
this._dl=1595750129;this._el=2917565137;this._fl=725511199;this._gl=4215389547;this._hl=327033209;return this};b.prototype._update=function(b){for(var c=this._w,k=this._ah|0,p=this._bh|0,l=this._ch|0,m=this._dh|0,f=this._eh|0,h=this._fh|0,v=this._gh|0,x=this._hh|0,z=this._al|0,I=this._bl|0,L=this._cl|0,F=this._dl|0,B=this._el|0,w=this._fl|0,C=this._gl|0,M=this._hl|0,D=0;32>D;D+=2)c[D]=b.readInt32BE(4*D),c[D+1]=b.readInt32BE(4*D+4);for(;160>D;D+=2){b=c[D-30];var G=c[D-30+1],u=(b>>>1|G<<31)^(b>>>8|
G<<24)^b>>>7,N=(G>>>1|b<<31)^(G>>>8|b<<24)^(G>>>7|b<<25);b=c[D-4];G=c[D-4+1];var K=(b>>>19|G<<13)^(G>>>29|b<<3)^b>>>6;G=(G>>>19|b<<13)^(b>>>29|G<<3)^(G>>>6|b<<26);var n=c[D-32],e=c[D-32+1];b=N+c[D-14+1]|0;u=u+c[D-14]+a(b,N)|0;b=b+G|0;u=u+K+a(b,G)|0;b=b+e|0;u=u+n+a(b,e)|0;c[D]=u;c[D+1]=b}for(D=0;160>D;D+=2){u=c[D];b=c[D+1];G=k&p|l&(k|p);var g=z&I|L&(z|I);n=(k>>>28|z<<4)^(z>>>2|k<<30)^(z>>>7|k<<25);e=(z>>>28|k<<4)^(k>>>2|z<<30)^(k>>>7|z<<25);var Q=d[D],O=d[D+1],R=v^f&(h^v),P=C^B&(w^C);K=M+((B>>>14|
f<<18)^(B>>>18|f<<14)^(f>>>9|B<<23))|0;N=x+((f>>>14|B<<18)^(f>>>18|B<<14)^(B>>>9|f<<23))+a(K,M)|0;K=K+P|0;N=N+R+a(K,P)|0;K=K+O|0;N=N+Q+a(K,O)|0;K=K+b|0;N=N+u+a(K,b)|0;b=e+g|0;u=n+G+a(b,e)|0;x=v;M=C;v=h;C=w;h=f;w=B;B=F+K|0;f=m+N+a(B,F)|0;m=l;F=L;l=p;L=I;p=k;I=z;z=K+b|0;k=N+u+a(z,K)|0}this._al=this._al+z|0;this._bl=this._bl+I|0;this._cl=this._cl+L|0;this._dl=this._dl+F|0;this._el=this._el+B|0;this._fl=this._fl+w|0;this._gl=this._gl+C|0;this._hl=this._hl+M|0;this._ah=this._ah+k+a(this._al,z)|0;this._bh=
this._bh+p+a(this._bl,I)|0;this._ch=this._ch+l+a(this._cl,L)|0;this._dh=this._dh+m+a(this._dl,F)|0;this._eh=this._eh+f+a(this._el,B)|0;this._fh=this._fh+h+a(this._fl,w)|0;this._gh=this._gh+v+a(this._gl,C)|0;this._hh=this._hh+x+a(this._hl,M)|0};b.prototype._hash=function(){function a(a,c,d){b.writeInt32BE(a,d);b.writeInt32BE(c,d+4)}var b=l.allocUnsafe(64);a(this._ah,this._al,0);a(this._bh,this._bl,8);a(this._ch,this._cl,16);a(this._dh,this._dl,24);a(this._eh,this._el,32);a(this._fh,this._fl,40);a(this._gh,
this._gl,48);a(this._hh,this._hl,56);return b};f.exports=b},{"./hash":9,inherits:3,"safe-buffer":8}],17:[function(c,f,h){},{}],18:[function(c,f,h){function b(n){if(n>u)throw new RangeError("Invalid typed array length");n=new Uint8Array(n);n.__proto__=a.prototype;return n}function a(a,e,g){if("number"===typeof a){if("string"===typeof e)throw Error("If encoding is specified then the first argument must be a string");return d(a)}return m(a,e,g)}function m(n,e,g){if("number"===typeof n)throw new TypeError('"value" argument must not be a number');
if(M(n)){if(0>e||n.byteLength<e)throw new RangeError("'offset' is out of bounds");if(n.byteLength<e+(g||0))throw new RangeError("'length' is out of bounds");n=void 0===e&&void 0===g?new Uint8Array(n):void 0===g?new Uint8Array(n,e):new Uint8Array(n,e,g);n.__proto__=a.prototype;return n}if("string"===typeof n){var c=e;if("string"!==typeof c||""===c)c="utf8";if(!a.isEncoding(c))throw new TypeError('"encoding" must be a valid string encoding');e=q(n,c)|0;g=b(e);n=g.write(n,c);n!==e&&(g=g.slice(0,n));
return g}return k(n)}function l(a){if("number"!==typeof a)throw new TypeError('"size" argument must be a number');if(0>a)throw new RangeError('"size" argument must not be negative');}function d(a){l(a);return b(0>a?0:E(a)|0)}function p(a){for(var e=0>a.length?0:E(a.length)|0,g=b(e),n=0;n<e;n+=1)g[n]=a[n]&255;return g}function k(n){if(a.isBuffer(n)){var e=E(n.length)|0,g=b(e);if(0===g.length)return g;n.copy(g,0,0,e);return g}if(n){if("function"===typeof ArrayBuffer.isView&&ArrayBuffer.isView(n)||"length"in
n)return(e="number"!==typeof n.length)||(e=n.length,e=e!==e),e?b(0):p(n);if("Buffer"===n.type&&Array.isArray(n.data))return p(n.data)}throw new TypeError("First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.");}function E(a){if(a>=u)throw new RangeError("Attempt to allocate Buffer larger than maximum size: 0x"+u.toString(16)+" bytes");return a|0}function q(n,e){if(a.isBuffer(n))return n.length;if("function"===typeof ArrayBuffer.isView&&ArrayBuffer.isView(n)||M(n))return n.byteLength;
"string"!==typeof n&&(n=""+n);var g=n.length;if(0===g)return 0;for(var b=!1;;)switch(e){case "ascii":case "latin1":case "binary":return g;case "utf8":case "utf-8":case void 0:return B(n).length;case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":return 2*g;case "hex":return g>>>1;case "base64":return D.toByteArray(F(n)).length;default:if(b)return B(n).length;e=(""+e).toLowerCase();b=!0}}function A(a,e,g){var n=!1;if(void 0===e||0>e)e=0;if(e>this.length)return"";if(void 0===g||g>this.length)g=
this.length;if(0>=g)return"";g>>>=0;e>>>=0;if(g<=e)return"";for(a||(a="utf8");;)switch(a){case "hex":a=e;e=g;g=this.length;if(!a||0>a)a=0;if(!e||0>e||e>g)e=g;n="";for(g=a;g<e;++g)a=n,n=this[g],n=16>n?"0"+n.toString(16):n.toString(16),n=a+n;return n;case "utf8":case "utf-8":return H(this,e,g);case "ascii":a="";for(g=Math.min(this.length,g);e<g;++e)a+=String.fromCharCode(this[e]&127);return a;case "latin1":case "binary":a="";for(g=Math.min(this.length,g);e<g;++e)a+=String.fromCharCode(this[e]);return a;
case "base64":return e=0===e&&g===this.length?D.fromByteArray(this):D.fromByteArray(this.slice(e,g)),e;case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":e=this.slice(e,g);g="";for(a=0;a<e.length;a+=2)g+=String.fromCharCode(e[a]+256*e[a+1]);return g;default:if(n)throw new TypeError("Unknown encoding: "+a);a=(a+"").toLowerCase();n=!0}}function t(a,e,g){var n=a[e];a[e]=a[g];a[g]=n}function y(n,e,g,b,c){if(0===n.length)return-1;"string"===typeof g?(b=g,g=0):2147483647<g?g=2147483647:-2147483648>
g&&(g=-2147483648);g=+g;g!==g&&(g=c?0:n.length-1);0>g&&(g=n.length+g);if(g>=n.length){if(c)return-1;g=n.length-1}else if(0>g)if(c)g=0;else return-1;"string"===typeof e&&(e=a.from(e,b));if(a.isBuffer(e))return 0===e.length?-1:J(n,e,g,b,c);if("number"===typeof e)return e&=255,"function"===typeof Uint8Array.prototype.indexOf?c?Uint8Array.prototype.indexOf.call(n,e,g):Uint8Array.prototype.lastIndexOf.call(n,e,g):J(n,[e],g,b,c);throw new TypeError("val must be string, number or Buffer");}function J(a,
e,g,b,c){function n(a,e){return 1===d?a[e]:a.readUInt16BE(e*d)}var d=1,k=a.length,p=e.length;if(void 0!==b&&(b=String(b).toLowerCase(),"ucs2"===b||"ucs-2"===b||"utf16le"===b||"utf-16le"===b)){if(2>a.length||2>e.length)return-1;d=2;k/=2;p/=2;g/=2}if(c)for(b=-1;g<k;g++)if(n(a,g)===n(e,-1===b?0:g-b)){if(-1===b&&(b=g),g-b+1===p)return b*d}else-1!==b&&(g-=g-b),b=-1;else for(g+p>k&&(g=k-p);0<=g;g--){k=!0;for(b=0;b<p;b++)if(n(a,g+b)!==n(e,b)){k=!1;break}if(k)return g}return-1}function H(a,e,g){g=Math.min(a.length,
g);for(var b=[];e<g;){var n=a[e],c=null,d=239<n?4:223<n?3:191<n?2:1;if(e+d<=g)switch(d){case 1:128>n&&(c=n);break;case 2:var k=a[e+1];128===(k&192)&&(n=(n&31)<<6|k&63,127<n&&(c=n));break;case 3:k=a[e+1];var p=a[e+2];128===(k&192)&&128===(p&192)&&(n=(n&15)<<12|(k&63)<<6|p&63,2047<n&&(55296>n||57343<n)&&(c=n));break;case 4:k=a[e+1];p=a[e+2];var l=a[e+3];128===(k&192)&&128===(p&192)&&128===(l&192)&&(n=(n&15)<<18|(k&63)<<12|(p&63)<<6|l&63,65535<n&&1114112>n&&(c=n))}null===c?(c=65533,d=1):65535<c&&(c-=
65536,b.push(c>>>10&1023|55296),c=56320|c&1023);b.push(c);e+=d}a=b.length;if(a<=N)b=String.fromCharCode.apply(String,b);else{g="";for(e=0;e<a;)g+=String.fromCharCode.apply(String,b.slice(e,e+=N));b=g}return b}function v(a,e,g){if(0!==a%1||0>a)throw new RangeError("offset is not uint");if(a+e>g)throw new RangeError("Trying to access beyond buffer length");}function x(b,e,g,c,d,k){if(!a.isBuffer(b))throw new TypeError('"buffer" argument must be a Buffer instance');if(e>d||e<k)throw new RangeError('"value" argument is out of bounds');
if(g+c>b.length)throw new RangeError("Index out of range");}function z(a,e,g,b,c,d){if(g+b>a.length)throw new RangeError("Index out of range");if(0>g)throw new RangeError("Index out of range");}function I(a,e,g,b,c){e=+e;g>>>=0;c||z(a,e,g,4,3.4028234663852886E38,-3.4028234663852886E38);G.write(a,e,g,b,23,4);return g+4}function L(a,e,g,b,c){e=+e;g>>>=0;c||z(a,e,g,8,1.7976931348623157E308,-1.7976931348623157E308);G.write(a,e,g,b,52,8);return g+8}function F(a){a=a.trim().replace(K,"");if(2>a.length)return"";
for(;0!==a.length%4;)a+="=";return a}function B(a,e){e=e||Infinity;for(var g,b=a.length,n=null,c=[],d=0;d<b;++d){g=a.charCodeAt(d);if(55295<g&&57344>g){if(!n){if(56319<g){-1<(e-=3)&&c.push(239,191,189);continue}else if(d+1===b){-1<(e-=3)&&c.push(239,191,189);continue}n=g;continue}if(56320>g){-1<(e-=3)&&c.push(239,191,189);n=g;continue}g=(n-55296<<10|g-56320)+65536}else n&&-1<(e-=3)&&c.push(239,191,189);n=null;if(128>g){if(0>--e)break;c.push(g)}else if(2048>g){if(0>(e-=2))break;c.push(g>>6|192,g&63|
128)}else if(65536>g){if(0>(e-=3))break;c.push(g>>12|224,g>>6&63|128,g&63|128)}else if(1114112>g){if(0>(e-=4))break;c.push(g>>18|240,g>>12&63|128,g>>6&63|128,g&63|128)}else throw Error("Invalid code point");}return c}function w(a){for(var e=[],g=0;g<a.length;++g)e.push(a.charCodeAt(g)&255);return e}function C(a,e,g,b){for(var n=0;n<b&&!(n+g>=e.length||n>=a.length);++n)e[n+g]=a[n];return n}function M(a){return a instanceof ArrayBuffer||null!=a&&null!=a.constructor&&"ArrayBuffer"===a.constructor.name&&
"number"===typeof a.byteLength}var D=c("base64-js"),G=c("ieee754");h.Buffer=a;h.SlowBuffer=function(b){+b!=b&&(b=0);return a.alloc(+b)};h.INSPECT_MAX_BYTES=50;var u=2147483647;h.kMaxLength=u;a.TYPED_ARRAY_SUPPORT=function(){try{var a=new Uint8Array(1);a.__proto__={__proto__:Uint8Array.prototype,foo:function(){return 42}};return 42===a.foo()}catch(e){return!1}}();a.TYPED_ARRAY_SUPPORT||"undefined"===typeof console||"function"!==typeof console.error||console.error("This browser lacks typed array (Uint8Array) support which is required by `buffer` v5.x. Use `buffer` v4.x if you require old browser support.");
"undefined"!==typeof Symbol&&Symbol.species&&a[Symbol.species]===a&&Object.defineProperty(a,Symbol.species,{value:null,configurable:!0,enumerable:!1,writable:!1});a.poolSize=8192;a.from=function(a,e,g){return m(a,e,g)};a.prototype.__proto__=Uint8Array.prototype;a.__proto__=Uint8Array;a.alloc=function(a,e,g){l(a);a=0>=a?b(a):void 0!==e?"string"===typeof g?b(a).fill(e,g):b(a).fill(e):b(a);return a};a.allocUnsafe=function(a){return d(a)};a.allocUnsafeSlow=function(a){return d(a)};a.isBuffer=function(a){return null!=
a&&!0===a._isBuffer};a.compare=function(b,e){if(!a.isBuffer(b)||!a.isBuffer(e))throw new TypeError("Arguments must be Buffers");if(b===e)return 0;for(var g=b.length,c=e.length,n=0,d=Math.min(g,c);n<d;++n)if(b[n]!==e[n]){g=b[n];c=e[n];break}return g<c?-1:c<g?1:0};a.isEncoding=function(a){switch(String(a).toLowerCase()){case "hex":case "utf8":case "utf-8":case "ascii":case "latin1":case "binary":case "base64":case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":return!0;default:return!1}};a.concat=
function(b,e){if(!Array.isArray(b))throw new TypeError('"list" argument must be an Array of Buffers');if(0===b.length)return a.alloc(0);var g;if(void 0===e)for(g=e=0;g<b.length;++g)e+=b[g].length;e=a.allocUnsafe(e);var c=0;for(g=0;g<b.length;++g){var n=b[g];if(!a.isBuffer(n))throw new TypeError('"list" argument must be an Array of Buffers');n.copy(e,c);c+=n.length}return e};a.byteLength=q;a.prototype._isBuffer=!0;a.prototype.swap16=function(){var a=this.length;if(0!==a%2)throw new RangeError("Buffer size must be a multiple of 16-bits");
for(var e=0;e<a;e+=2)t(this,e,e+1);return this};a.prototype.swap32=function(){var a=this.length;if(0!==a%4)throw new RangeError("Buffer size must be a multiple of 32-bits");for(var e=0;e<a;e+=4)t(this,e,e+3),t(this,e+1,e+2);return this};a.prototype.swap64=function(){var a=this.length;if(0!==a%8)throw new RangeError("Buffer size must be a multiple of 64-bits");for(var e=0;e<a;e+=8)t(this,e,e+7),t(this,e+1,e+6),t(this,e+2,e+5),t(this,e+3,e+4);return this};a.prototype.toString=function(){var a=this.length;
return 0===a?"":0===arguments.length?H(this,0,a):A.apply(this,arguments)};a.prototype.equals=function(b){if(!a.isBuffer(b))throw new TypeError("Argument must be a Buffer");return this===b?!0:0===a.compare(this,b)};a.prototype.inspect=function(){var a="",e=h.INSPECT_MAX_BYTES;0<this.length&&(a=this.toString("hex",0,e).match(/.{2}/g).join(" "),this.length>e&&(a+=" ... "));return"<Buffer "+a+">"};a.prototype.compare=function(b,e,g,c,d){if(!a.isBuffer(b))throw new TypeError("Argument must be a Buffer");
void 0===e&&(e=0);void 0===g&&(g=b?b.length:0);void 0===c&&(c=0);void 0===d&&(d=this.length);if(0>e||g>b.length||0>c||d>this.length)throw new RangeError("out of range index");if(c>=d&&e>=g)return 0;if(c>=d)return-1;if(e>=g)return 1;e>>>=0;g>>>=0;c>>>=0;d>>>=0;if(this===b)return 0;var n=d-c,k=g-e,p=Math.min(n,k);c=this.slice(c,d);b=b.slice(e,g);for(e=0;e<p;++e)if(c[e]!==b[e]){n=c[e];k=b[e];break}return n<k?-1:k<n?1:0};a.prototype.includes=function(a,e,b){return-1!==this.indexOf(a,e,b)};a.prototype.indexOf=
function(a,e,b){return y(this,a,e,b,!0)};a.prototype.lastIndexOf=function(a,e,b){return y(this,a,e,b,!1)};a.prototype.write=function(a,e,b,c){if(void 0===e)c="utf8",b=this.length,e=0;else if(void 0===b&&"string"===typeof e)c=e,b=this.length,e=0;else if(isFinite(e))e>>>=0,isFinite(b)?(b>>>=0,void 0===c&&(c="utf8")):(c=b,b=void 0);else throw Error("Buffer.write(string, encoding, offset[, length]) is no longer supported");var g=this.length-e;if(void 0===b||b>g)b=g;if(0<a.length&&(0>b||0>e)||e>this.length)throw new RangeError("Attempt to write outside buffer bounds");
c||(c="utf8");for(g=!1;;)switch(c){case "hex":a:{e=Number(e)||0;c=this.length-e;b?(b=Number(b),b>c&&(b=c)):b=c;c=a.length;if(0!==c%2)throw new TypeError("Invalid hex string");b>c/2&&(b=c/2);for(c=0;c<b;++c){g=parseInt(a.substr(2*c,2),16);if(g!==g){a=c;break a}this[e+c]=g}a=c}return a;case "utf8":case "utf-8":return C(B(a,this.length-e),this,e,b);case "ascii":return C(w(a),this,e,b);case "latin1":case "binary":return C(w(a),this,e,b);case "base64":return C(D.toByteArray(F(a)),this,e,b);case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":c=
a;g=this.length-e;for(var n=[],d=0;d<c.length&&!(0>(g-=2));++d){var k=c.charCodeAt(d);a=k>>8;k%=256;n.push(k);n.push(a)}return C(n,this,e,b);default:if(g)throw new TypeError("Unknown encoding: "+c);c=(""+c).toLowerCase();g=!0}};a.prototype.toJSON=function(){return{type:"Buffer",data:Array.prototype.slice.call(this._arr||this,0)}};var N=4096;a.prototype.slice=function(b,e){var g=this.length;b=~~b;e=void 0===e?g:~~e;0>b?(b+=g,0>b&&(b=0)):b>g&&(b=g);0>e?(e+=g,0>e&&(e=0)):e>g&&(e=g);e<b&&(e=b);b=this.subarray(b,
e);b.__proto__=a.prototype;return b};a.prototype.readUIntLE=function(a,e,b){a>>>=0;e>>>=0;b||v(a,e,this.length);b=this[a];for(var g=1,c=0;++c<e&&(g*=256);)b+=this[a+c]*g;return b};a.prototype.readUIntBE=function(a,e,b){a>>>=0;e>>>=0;b||v(a,e,this.length);b=this[a+--e];for(var g=1;0<e&&(g*=256);)b+=this[a+--e]*g;return b};a.prototype.readUInt8=function(a,e){a>>>=0;e||v(a,1,this.length);return this[a]};a.prototype.readUInt16LE=function(a,e){a>>>=0;e||v(a,2,this.length);return this[a]|this[a+1]<<8};
a.prototype.readUInt16BE=function(a,e){a>>>=0;e||v(a,2,this.length);return this[a]<<8|this[a+1]};a.prototype.readUInt32LE=function(a,e){a>>>=0;e||v(a,4,this.length);return(this[a]|this[a+1]<<8|this[a+2]<<16)+16777216*this[a+3]};a.prototype.readUInt32BE=function(a,e){a>>>=0;e||v(a,4,this.length);return 16777216*this[a]+(this[a+1]<<16|this[a+2]<<8|this[a+3])};a.prototype.readIntLE=function(a,e,b){a>>>=0;e>>>=0;b||v(a,e,this.length);b=this[a];for(var g=1,c=0;++c<e&&(g*=256);)b+=this[a+c]*g;b>=128*g&&
(b-=Math.pow(2,8*e));return b};a.prototype.readIntBE=function(a,e,b){a>>>=0;e>>>=0;b||v(a,e,this.length);b=e;for(var g=1,c=this[a+--b];0<b&&(g*=256);)c+=this[a+--b]*g;c>=128*g&&(c-=Math.pow(2,8*e));return c};a.prototype.readInt8=function(a,e){a>>>=0;e||v(a,1,this.length);return this[a]&128?-1*(255-this[a]+1):this[a]};a.prototype.readInt16LE=function(a,e){a>>>=0;e||v(a,2,this.length);a=this[a]|this[a+1]<<8;return a&32768?a|4294901760:a};a.prototype.readInt16BE=function(a,e){a>>>=0;e||v(a,2,this.length);
a=this[a+1]|this[a]<<8;return a&32768?a|4294901760:a};a.prototype.readInt32LE=function(a,e){a>>>=0;e||v(a,4,this.length);return this[a]|this[a+1]<<8|this[a+2]<<16|this[a+3]<<24};a.prototype.readInt32BE=function(a,e){a>>>=0;e||v(a,4,this.length);return this[a]<<24|this[a+1]<<16|this[a+2]<<8|this[a+3]};a.prototype.readFloatLE=function(a,e){a>>>=0;e||v(a,4,this.length);return G.read(this,a,!0,23,4)};a.prototype.readFloatBE=function(a,e){a>>>=0;e||v(a,4,this.length);return G.read(this,a,!1,23,4)};a.prototype.readDoubleLE=
function(a,e){a>>>=0;e||v(a,8,this.length);return G.read(this,a,!0,52,8)};a.prototype.readDoubleBE=function(a,e){a>>>=0;e||v(a,8,this.length);return G.read(this,a,!1,52,8)};a.prototype.writeUIntLE=function(a,e,b,c){a=+a;e>>>=0;b>>>=0;c||x(this,a,e,b,Math.pow(2,8*b)-1,0);c=1;var g=0;for(this[e]=a&255;++g<b&&(c*=256);)this[e+g]=a/c&255;return e+b};a.prototype.writeUIntBE=function(a,b,c,d){a=+a;b>>>=0;c>>>=0;d||x(this,a,b,c,Math.pow(2,8*c)-1,0);d=c-1;var e=1;for(this[b+d]=a&255;0<=--d&&(e*=256);)this[b+
d]=a/e&255;return b+c};a.prototype.writeUInt8=function(a,b,c){a=+a;b>>>=0;c||x(this,a,b,1,255,0);this[b]=a&255;return b+1};a.prototype.writeUInt16LE=function(a,b,c){a=+a;b>>>=0;c||x(this,a,b,2,65535,0);this[b]=a&255;this[b+1]=a>>>8;return b+2};a.prototype.writeUInt16BE=function(a,b,c){a=+a;b>>>=0;c||x(this,a,b,2,65535,0);this[b]=a>>>8;this[b+1]=a&255;return b+2};a.prototype.writeUInt32LE=function(a,b,c){a=+a;b>>>=0;c||x(this,a,b,4,4294967295,0);this[b+3]=a>>>24;this[b+2]=a>>>16;this[b+1]=a>>>8;this[b]=
a&255;return b+4};a.prototype.writeUInt32BE=function(a,b,c){a=+a;b>>>=0;c||x(this,a,b,4,4294967295,0);this[b]=a>>>24;this[b+1]=a>>>16;this[b+2]=a>>>8;this[b+3]=a&255;return b+4};a.prototype.writeIntLE=function(a,b,c,d){a=+a;b>>>=0;d||(d=Math.pow(2,8*c-1),x(this,a,b,c,d-1,-d));d=0;var e=1,g=0;for(this[b]=a&255;++d<c&&(e*=256);)0>a&&0===g&&0!==this[b+d-1]&&(g=1),this[b+d]=(a/e>>0)-g&255;return b+c};a.prototype.writeIntBE=function(a,b,c,d){a=+a;b>>>=0;d||(d=Math.pow(2,8*c-1),x(this,a,b,c,d-1,-d));d=
c-1;var e=1,g=0;for(this[b+d]=a&255;0<=--d&&(e*=256);)0>a&&0===g&&0!==this[b+d+1]&&(g=1),this[b+d]=(a/e>>0)-g&255;return b+c};a.prototype.writeInt8=function(a,b,c){a=+a;b>>>=0;c||x(this,a,b,1,127,-128);0>a&&(a=255+a+1);this[b]=a&255;return b+1};a.prototype.writeInt16LE=function(a,b,c){a=+a;b>>>=0;c||x(this,a,b,2,32767,-32768);this[b]=a&255;this[b+1]=a>>>8;return b+2};a.prototype.writeInt16BE=function(a,b,c){a=+a;b>>>=0;c||x(this,a,b,2,32767,-32768);this[b]=a>>>8;this[b+1]=a&255;return b+2};a.prototype.writeInt32LE=
function(a,b,c){a=+a;b>>>=0;c||x(this,a,b,4,2147483647,-2147483648);this[b]=a&255;this[b+1]=a>>>8;this[b+2]=a>>>16;this[b+3]=a>>>24;return b+4};a.prototype.writeInt32BE=function(a,b,c){a=+a;b>>>=0;c||x(this,a,b,4,2147483647,-2147483648);0>a&&(a=4294967295+a+1);this[b]=a>>>24;this[b+1]=a>>>16;this[b+2]=a>>>8;this[b+3]=a&255;return b+4};a.prototype.writeFloatLE=function(a,b,c){return I(this,a,b,!0,c)};a.prototype.writeFloatBE=function(a,b,c){return I(this,a,b,!1,c)};a.prototype.writeDoubleLE=function(a,
b,c){return L(this,a,b,!0,c)};a.prototype.writeDoubleBE=function(a,b,c){return L(this,a,b,!1,c)};a.prototype.copy=function(a,b,c,d){c||(c=0);d||0===d||(d=this.length);b>=a.length&&(b=a.length);b||(b=0);0<d&&d<c&&(d=c);if(d===c||0===a.length||0===this.length)return 0;if(0>b)throw new RangeError("targetStart out of bounds");if(0>c||c>=this.length)throw new RangeError("sourceStart out of bounds");if(0>d)throw new RangeError("sourceEnd out of bounds");d>this.length&&(d=this.length);a.length-b<d-c&&(d=
a.length-b+c);var e=d-c;if(this===a&&c<b&&b<d)for(d=e-1;0<=d;--d)a[d+b]=this[d+c];else if(1E3>e)for(d=0;d<e;++d)a[d+b]=this[d+c];else Uint8Array.prototype.set.call(a,this.subarray(c,c+e),b);return e};a.prototype.fill=function(b,c,g,d){if("string"===typeof b){"string"===typeof c?(d=c,c=0,g=this.length):"string"===typeof g&&(d=g,g=this.length);if(1===b.length){var e=b.charCodeAt(0);256>e&&(b=e)}if(void 0!==d&&"string"!==typeof d)throw new TypeError("encoding must be a string");if("string"===typeof d&&
!a.isEncoding(d))throw new TypeError("Unknown encoding: "+d);}else"number"===typeof b&&(b&=255);if(0>c||this.length<c||this.length<g)throw new RangeError("Out of range index");if(g<=c)return this;c>>>=0;g=void 0===g?this.length:g>>>0;b||(b=0);if("number"===typeof b)for(d=c;d<g;++d)this[d]=b;else for(b=a.isBuffer(b)?b:new a(b,d),e=b.length,d=0;d<g-c;++d)this[d+c]=b[d%e];return this};var K=/[^+/0-9A-Za-z-_]/g},{"base64-js":19,ieee754:20}],19:[function(c,f,h){function b(a){var b=a.length;if(0<b%4)throw Error("Invalid string. Length must be a multiple of 4");
return"="===a[b-2]?2:"="===a[b-1]?1:0}function a(a,b,c){for(var d=[],k=b;k<c;k+=3)b=(a[k]<<16)+(a[k+1]<<8)+a[k+2],d.push(m[b>>18&63]+m[b>>12&63]+m[b>>6&63]+m[b&63]);return d.join("")}h.byteLength=function(a){return 3*a.length/4-b(a)};h.toByteArray=function(a){var c=a.length;var p=b(a);var m=new d(3*c/4-p);var f=0<p?c-4:c;var h=0;for(c=0;c<f;c+=4){var y=l[a.charCodeAt(c)]<<18|l[a.charCodeAt(c+1)]<<12|l[a.charCodeAt(c+2)]<<6|l[a.charCodeAt(c+3)];m[h++]=y>>16&255;m[h++]=y>>8&255;m[h++]=y&255}2===p?(y=
l[a.charCodeAt(c)]<<2|l[a.charCodeAt(c+1)]>>4,m[h++]=y&255):1===p&&(y=l[a.charCodeAt(c)]<<10|l[a.charCodeAt(c+1)]<<4|l[a.charCodeAt(c+2)]>>2,m[h++]=y>>8&255,m[h++]=y&255);return m};h.fromByteArray=function(b){for(var c=b.length,d=c%3,l="",p=[],f=0,h=c-d;f<h;f+=16383)p.push(a(b,f,f+16383>h?h:f+16383));1===d?(b=b[c-1],l+=m[b>>2],l+=m[b<<4&63],l+="=="):2===d&&(b=(b[c-2]<<8)+b[c-1],l+=m[b>>10],l+=m[b>>4&63],l+=m[b<<2&63],l+="=");p.push(l);return p.join("")};var m=[],l=[],d="undefined"!==typeof Uint8Array?
Uint8Array:Array;for(c=0;64>c;++c)m[c]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[c],l["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charCodeAt(c)]=c;l[45]=62;l[95]=63},{}],20:[function(c,f,h){h.read=function(b,a,c,l,d){var p=8*d-l-1;var k=(1<<p)-1,m=k>>1,f=-7;d=c?d-1:0;var h=c?-1:1,t=b[a+d];d+=h;c=t&(1<<-f)-1;t>>=-f;for(f+=p;0<f;c=256*c+b[a+d],d+=h,f-=8);p=c&(1<<-f)-1;c>>=-f;for(f+=l;0<f;p=256*p+b[a+d],d+=h,f-=8);if(0===c)c=1-m;else{if(c===k)return p?
NaN:Infinity*(t?-1:1);p+=Math.pow(2,l);c-=m}return(t?-1:1)*p*Math.pow(2,c-l)};h.write=function(b,a,c,l,d,p){var k,f=8*p-d-1,m=(1<<f)-1,h=m>>1,t=23===d?Math.pow(2,-24)-Math.pow(2,-77):0;p=l?0:p-1;var y=l?1:-1,J=0>a||0===a&&0>1/a?1:0;a=Math.abs(a);isNaN(a)||Infinity===a?(a=isNaN(a)?1:0,l=m):(l=Math.floor(Math.log(a)/Math.LN2),1>a*(k=Math.pow(2,-l))&&(l--,k*=2),a=1<=l+h?a+t/k:a+t*Math.pow(2,1-h),2<=a*k&&(l++,k/=2),l+h>=m?(a=0,l=m):1<=l+h?(a=(a*k-1)*Math.pow(2,d),l+=h):(a=a*Math.pow(2,h-1)*Math.pow(2,
d),l=0));for(;8<=d;b[c+p]=a&255,p+=y,a/=256,d-=8);l=l<<d|a;for(f+=d;0<f;b[c+p]=l&255,p+=y,l/=256,f-=8);b[c+p-y]|=128*J}},{}],21:[function(c,f,h){function b(){this._events=this._events||{};this._maxListeners=this._maxListeners||void 0}function a(a){return"function"===typeof a}function m(a){return"object"===typeof a&&null!==a}f.exports=b;b.EventEmitter=b;b.prototype._events=void 0;b.prototype._maxListeners=void 0;b.defaultMaxListeners=10;b.prototype.setMaxListeners=function(a){if("number"!==typeof a||
0>a||isNaN(a))throw TypeError("n must be a positive number");this._maxListeners=a;return this};b.prototype.emit=function(b){var c;this._events||(this._events={});if("error"===b&&(!this._events.error||m(this._events.error)&&!this._events.error.length)){var l=arguments[1];if(l instanceof Error)throw l;var k=Error('Uncaught, unspecified "error" event. ('+l+")");k.context=l;throw k;}k=this._events[b];if(void 0===k)return!1;if(a(k))switch(arguments.length){case 1:k.call(this);break;case 2:k.call(this,
arguments[1]);break;case 3:k.call(this,arguments[1],arguments[2]);break;default:l=Array.prototype.slice.call(arguments,1),k.apply(this,l)}else if(m(k)){l=Array.prototype.slice.call(arguments,1);var f=k.slice();k=f.length;for(c=0;c<k;c++)f[c].apply(this,l)}return!0};b.prototype.addListener=function(c,d){if(!a(d))throw TypeError("listener must be a function");this._events||(this._events={});this._events.newListener&&this.emit("newListener",c,a(d.listener)?d.listener:d);this._events[c]?m(this._events[c])?
this._events[c].push(d):this._events[c]=[this._events[c],d]:this._events[c]=d;m(this._events[c])&&!this._events[c].warned&&(d=void 0!==this._maxListeners?this._maxListeners:b.defaultMaxListeners)&&0<d&&this._events[c].length>d&&(this._events[c].warned=!0,console.error("(node) warning: possible EventEmitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() to increase limit.",this._events[c].length),"function"===typeof console.trace&&console.trace());return this};b.prototype.on=
b.prototype.addListener;b.prototype.once=function(b,c){function d(){this.removeListener(b,d);k||(k=!0,c.apply(this,arguments))}if(!a(c))throw TypeError("listener must be a function");var k=!1;d.listener=c;this.on(b,d);return this};b.prototype.removeListener=function(b,c){if(!a(c))throw TypeError("listener must be a function");if(!this._events||!this._events[b])return this;var d=this._events[b];var k=d.length;var l=-1;if(d===c||a(d.listener)&&d.listener===c)delete this._events[b],this._events.removeListener&&
this.emit("removeListener",b,c);else if(m(d)){for(;0<k--;)if(d[k]===c||d[k].listener&&d[k].listener===c){l=k;break}if(0>l)return this;1===d.length?(d.length=0,delete this._events[b]):d.splice(l,1);this._events.removeListener&&this.emit("removeListener",b,c)}return this};b.prototype.removeAllListeners=function(b){if(!this._events)return this;if(!this._events.removeListener)return 0===arguments.length?this._events={}:this._events[b]&&delete this._events[b],this;if(0===arguments.length){for(c in this._events)"removeListener"!==
c&&this.removeAllListeners(c);this.removeAllListeners("removeListener");this._events={};return this}var c=this._events[b];if(a(c))this.removeListener(b,c);else if(c)for(;c.length;)this.removeListener(b,c[c.length-1]);delete this._events[b];return this};b.prototype.listeners=function(b){return this._events&&this._events[b]?a(this._events[b])?[this._events[b]]:this._events[b].slice():[]};b.prototype.listenerCount=function(b){if(this._events){b=this._events[b];if(a(b))return 1;if(b)return b.length}return 0};
b.listenerCount=function(a,b){return a.listenerCount(b)}},{}],22:[function(c,f,h){f.exports="function"===typeof Object.create?function(b,a){b.super_=a;b.prototype=Object.create(a.prototype,{constructor:{value:b,enumerable:!1,writable:!0,configurable:!0}})}:function(b,a){b.super_=a;var c=function(){};c.prototype=a.prototype;b.prototype=new c;b.prototype.constructor=b}},{}],23:[function(c,f,h){function b(a){return!!a.constructor&&"function"===typeof a.constructor.isBuffer&&a.constructor.isBuffer(a)}
f.exports=function(a){return null!=a&&(b(a)||"function"===typeof a.readFloatLE&&"function"===typeof a.slice&&b(a.slice(0,0))||!!a._isBuffer)}},{}],24:[function(c,f,h){function b(){throw Error("setTimeout has not been defined");}function a(){throw Error("clearTimeout has not been defined");}function m(a){if(q===setTimeout)return setTimeout(a,0);if((q===b||!q)&&setTimeout)return q=setTimeout,setTimeout(a,0);try{return q(a,0)}catch(x){try{return q.call(null,a,0)}catch(z){return q.call(this,a,0)}}}function l(b){if(A===
clearTimeout)return clearTimeout(b);if((A===a||!A)&&clearTimeout)return A=clearTimeout,clearTimeout(b);try{return A(b)}catch(x){try{return A.call(null,b)}catch(z){return A.call(this,b)}}}function d(){y&&J&&(y=!1,J.length?t=J.concat(t):H=-1,t.length&&p())}function p(){if(!y){var a=m(d);y=!0;for(var b=t.length;b;){J=t;for(t=[];++H<b;)J&&J[H].run();H=-1;b=t.length}J=null;y=!1;l(a)}}function k(a,b){this.fun=a;this.array=b}function E(){}c=f.exports={};try{var q="function"===typeof setTimeout?setTimeout:
b}catch(v){q=b}try{var A="function"===typeof clearTimeout?clearTimeout:a}catch(v){A=a}var t=[],y=!1,J,H=-1;c.nextTick=function(a){var b=Array(arguments.length-1);if(1<arguments.length)for(var c=1;c<arguments.length;c++)b[c-1]=arguments[c];t.push(new k(a,b));1!==t.length||y||m(p)};k.prototype.run=function(){this.fun.apply(null,this.array)};c.title="browser";c.browser=!0;c.env={};c.argv=[];c.version="";c.versions={};c.on=E;c.addListener=E;c.once=E;c.off=E;c.removeListener=E;c.removeAllListeners=E;c.emit=
E;c.prependListener=E;c.prependOnceListener=E;c.listeners=function(a){return[]};c.binding=function(a){throw Error("process.binding is not supported");};c.cwd=function(){return"/"};c.chdir=function(a){throw Error("process.chdir is not supported");};c.umask=function(){return 0}},{}],25:[function(c,f,h){f.exports=c("./lib/_stream_duplex.js")},{"./lib/_stream_duplex.js":26}],26:[function(c,f,h){function b(c){if(!(this instanceof b))return new b(c);d.call(this,c);p.call(this,c);c&&!1===c.readable&&(this.readable=
!1);c&&!1===c.writable&&(this.writable=!1);this.allowHalfOpen=!0;c&&!1===c.allowHalfOpen&&(this.allowHalfOpen=!1);this.once("end",a)}function a(){this.allowHalfOpen||this._writableState.ended||l(m,this)}function m(a){a.end()}var l=c("process-nextick-args");h=Object.keys||function(a){var b=[],c;for(c in a)b.push(c);return b};f.exports=b;f=c("core-util-is");f.inherits=c("inherits");var d=c("./_stream_readable"),p=c("./_stream_writable");f.inherits(b,d);c=h(p.prototype);for(f=0;f<c.length;f++)h=c[f],
b.prototype[h]||(b.prototype[h]=p.prototype[h]);Object.defineProperty(b.prototype,"destroyed",{get:function(){return void 0===this._readableState||void 0===this._writableState?!1:this._readableState.destroyed&&this._writableState.destroyed},set:function(a){void 0!==this._readableState&&void 0!==this._writableState&&(this._readableState.destroyed=a,this._writableState.destroyed=a)}});b.prototype._destroy=function(a,b){this.push(null);this.end();l(b,a)}},{"./_stream_readable":28,"./_stream_writable":30,
"core-util-is":34,inherits:22,"process-nextick-args":36}],27:[function(c,f,h){function b(c){if(!(this instanceof b))return new b(c);a.call(this,c)}f.exports=b;var a=c("./_stream_transform");f=c("core-util-is");f.inherits=c("inherits");f.inherits(b,a);b.prototype._transform=function(a,b,c){c(null,a)}},{"./_stream_transform":29,"core-util-is":34,inherits:22}],28:[function(c,f,h){(function(b,a){function h(a,b,c){if("function"===typeof a.prependListener)return a.prependListener(b,c);if(a._events&&a._events[b])B(a._events[b])?
a._events[b].unshift(c):a._events[b]=[c,a._events[b]];else a.on(b,c)}function l(a,b){w=w||c("./_stream_duplex");a=a||{};this.objectMode=!!a.objectMode;b instanceof w&&(this.objectMode=this.objectMode||!!a.readableObjectMode);b=a.highWaterMark;var e=this.objectMode?16:16384;this.highWaterMark=b||0===b?b:e;this.highWaterMark=Math.floor(this.highWaterMark);this.buffer=new N;this.length=0;this.pipes=null;this.pipesCount=0;this.flowing=null;this.reading=this.endEmitted=this.ended=!1;this.sync=!0;this.destroyed=
this.resumeScheduled=this.readableListening=this.emittedReadable=this.needReadable=!1;this.defaultEncoding=a.defaultEncoding||"utf8";this.awaitDrain=0;this.readingMore=!1;this.encoding=this.decoder=null;a.encoding&&(K||(K=c("string_decoder/").StringDecoder),this.decoder=new K(a.encoding),this.encoding=a.encoding)}function d(a){w=w||c("./_stream_duplex");if(!(this instanceof d))return new d(a);this._readableState=new l(a,this);this.readable=!0;a&&("function"===typeof a.read&&(this._read=a.read),"function"===
typeof a.destroy&&(this._destroy=a.destroy));C.call(this)}function p(a,b,c,d,f){var e=a._readableState;if(null===b)e.reading=!1,e.ended||(e.decoder&&(b=e.decoder.end())&&b.length&&(e.buffer.push(b),e.length+=e.objectMode?1:b.length),e.ended=!0,q(a));else{if(!f){f=b;var g;M.isBuffer(f)||f instanceof D||"string"===typeof f||void 0===f||e.objectMode||(g=new TypeError("Invalid non-string/buffer chunk"));var p=g}p?a.emit("error",p):e.objectMode||b&&0<b.length?("string"===typeof b||e.objectMode||Object.getPrototypeOf(b)===
M.prototype||(b=M.from(b)),d?e.endEmitted?a.emit("error",Error("stream.unshift() after end event")):k(a,e,b,!0):e.ended?a.emit("error",Error("stream.push() after EOF")):(e.reading=!1,e.decoder&&!c?(b=e.decoder.write(b),e.objectMode||0!==b.length?k(a,e,b,!1):e.readingMore||(e.readingMore=!0,F(t,a,e))):k(a,e,b,!1))):d||(e.reading=!1)}return!e.ended&&(e.needReadable||e.length<e.highWaterMark||0===e.length)}function k(a,b,c,d){b.flowing&&0===b.length&&!b.sync?(a.emit("data",c),a.read(0)):(b.length+=b.objectMode?
1:c.length,d?b.buffer.unshift(c):b.buffer.push(c),b.needReadable&&q(a));b.readingMore||(b.readingMore=!0,F(t,a,b))}function E(a,b){if(0>=a||0===b.length&&b.ended)return 0;if(b.objectMode)return 1;if(a!==a)return b.flowing&&b.length?b.buffer.head.data.length:b.length;if(a>b.highWaterMark){var c=a;8388608<=c?c=8388608:(c--,c|=c>>>1,c|=c>>>2,c|=c>>>4,c|=c>>>8,c|=c>>>16,c++);b.highWaterMark=c}return a<=b.length?a:b.ended?b.length:(b.needReadable=!0,0)}function q(a){var b=a._readableState;b.needReadable=
!1;b.emittedReadable||(u("emitReadable",b.flowing),b.emittedReadable=!0,b.sync?F(A,a):A(a))}function A(a){u("emit readable");a.emit("readable");v(a)}function t(a,b){for(var c=b.length;!b.reading&&!b.flowing&&!b.ended&&b.length<b.highWaterMark&&(u("maybeReadMore read 0"),a.read(0),c!==b.length);)c=b.length;b.readingMore=!1}function y(a){return function(){var b=a._readableState;u("pipeOnDrain",b.awaitDrain);b.awaitDrain&&b.awaitDrain--;0===b.awaitDrain&&a.listeners("data").length&&(b.flowing=!0,v(a))}}
function J(a){u("readable nexttick read 0");a.read(0)}function H(a,b){b.reading||(u("resume read 0"),a.read(0));b.resumeScheduled=!1;b.awaitDrain=0;a.emit("resume");v(a);b.flowing&&!b.reading&&a.read(0)}function v(a){var b=a._readableState;for(u("flow",b.flowing);b.flowing&&null!==a.read(););}function x(a,b){if(0===b.length)return null;if(b.objectMode)var c=b.buffer.shift();else if(!a||a>=b.length)c=b.decoder?b.buffer.join(""):1===b.buffer.length?b.buffer.head.data:b.buffer.concat(b.length),b.buffer.clear();
else{c=b.buffer;b=b.decoder;if(a<c.head.data.length)b=c.head.data.slice(0,a),c.head.data=c.head.data.slice(a);else{if(a===c.head.data.length)c=c.shift();else if(b){b=c.head;var e=1,d=b.data;for(a-=d.length;b=b.next;){var g=b.data,k=a>g.length?g.length:a;d=k===g.length?d+g:d+g.slice(0,a);a-=k;if(0===a){k===g.length?(++e,c.head=b.next?b.next:c.tail=null):(c.head=b,b.data=g.slice(k));break}++e}c.length-=e;c=d}else{b=M.allocUnsafe(a);e=c.head;d=1;e.data.copy(b);for(a-=e.data.length;e=e.next;){g=e.data;
k=a>g.length?g.length:a;g.copy(b,b.length-a,0,k);a-=k;if(0===a){k===g.length?(++d,c.head=e.next?e.next:c.tail=null):(c.head=e,e.data=g.slice(k));break}++d}c.length-=d;c=b}b=c}c=b}return c}function z(a){var b=a._readableState;if(0<b.length)throw Error('"endReadable()" called on non-empty stream');b.endEmitted||(b.ended=!0,F(I,b,a))}function I(a,b){a.endEmitted||0!==a.length||(a.endEmitted=!0,b.readable=!1,b.emit("end"))}function L(a,b){for(var c=0,e=a.length;c<e;c++)if(a[c]===b)return c;return-1}var F=
c("process-nextick-args");f.exports=d;var B=c("isarray"),w;d.ReadableState=l;c("events");var C=c("./internal/streams/stream"),M=c("safe-buffer").Buffer,D=a.Uint8Array||function(){};a=c("core-util-is");a.inherits=c("inherits");var G=c("util"),u=void 0;u=G&&G.debuglog?G.debuglog("stream"):function(){};var N=c("./internal/streams/BufferList");G=c("./internal/streams/destroy");var K;a.inherits(d,C);var n=["error","close","destroy","pause","resume"];Object.defineProperty(d.prototype,"destroyed",{get:function(){return void 0===
this._readableState?!1:this._readableState.destroyed},set:function(a){this._readableState&&(this._readableState.destroyed=a)}});d.prototype.destroy=G.destroy;d.prototype._undestroy=G.undestroy;d.prototype._destroy=function(a,b){this.push(null);b(a)};d.prototype.push=function(a,b){var c=this._readableState;if(c.objectMode)var e=!0;else"string"===typeof a&&(b=b||c.defaultEncoding,b!==c.encoding&&(a=M.from(a,b),b=""),e=!0);return p(this,a,b,!1,e)};d.prototype.unshift=function(a){return p(this,a,null,
!0,!1)};d.prototype.isPaused=function(){return!1===this._readableState.flowing};d.prototype.setEncoding=function(a){K||(K=c("string_decoder/").StringDecoder);this._readableState.decoder=new K(a);this._readableState.encoding=a;return this};d.prototype.read=function(a){u("read",a);a=parseInt(a,10);var b=this._readableState,c=a;0!==a&&(b.emittedReadable=!1);if(0===a&&b.needReadable&&(b.length>=b.highWaterMark||b.ended))return u("read: emitReadable",b.length,b.ended),0===b.length&&b.ended?z(this):q(this),
null;a=E(a,b);if(0===a&&b.ended)return 0===b.length&&z(this),null;var d=b.needReadable;u("need readable",d);if(0===b.length||b.length-a<b.highWaterMark)d=!0,u("length less than watermark",d);b.ended||b.reading?u("reading or ended",!1):d&&(u("do read"),b.reading=!0,b.sync=!0,0===b.length&&(b.needReadable=!0),this._read(b.highWaterMark),b.sync=!1,b.reading||(a=E(c,b)));d=0<a?x(a,b):null;null===d?(b.needReadable=!0,a=0):b.length-=a;0===b.length&&(b.ended||(b.needReadable=!0),c!==a&&b.ended&&z(this));
null!==d&&this.emit("data",d);return d};d.prototype._read=function(a){this.emit("error",Error("_read() is not implemented"))};d.prototype.pipe=function(a,c){function d(b,c){u("onunpipe");b===m&&c&&!1===c.hasUnpiped&&(c.hasUnpiped=!0,u("cleanup"),a.removeListener("close",f),a.removeListener("finish",p),a.removeListener("drain",B),a.removeListener("error",k),a.removeListener("unpipe",d),m.removeListener("end",e),m.removeListener("end",l),m.removeListener("data",g),H=!0,!n.awaitDrain||a._writableState&&
!a._writableState.needDrain||B())}function e(){u("onend");a.end()}function g(b){u("ondata");w=!1;!1!==a.write(b)||w||((1===n.pipesCount&&n.pipes===a||1<n.pipesCount&&-1!==L(n.pipes,a))&&!H&&(u("false write response, pause",m._readableState.awaitDrain),m._readableState.awaitDrain++,w=!0),m.pause())}function k(b){u("onerror",b);l();a.removeListener("error",k);0===a.listeners("error").length&&a.emit("error",b)}function f(){a.removeListener("finish",p);l()}function p(){u("onfinish");a.removeListener("close",
f);l()}function l(){u("unpipe");m.unpipe(a)}var m=this,n=this._readableState;switch(n.pipesCount){case 0:n.pipes=a;break;case 1:n.pipes=[n.pipes,a];break;default:n.pipes.push(a)}n.pipesCount+=1;u("pipe count=%d opts=%j",n.pipesCount,c);c=c&&!1===c.end||a===b.stdout||a===b.stderr?l:e;if(n.endEmitted)F(c);else m.once("end",c);a.on("unpipe",d);var B=y(m);a.on("drain",B);var H=!1,w=!1;m.on("data",g);h(a,"error",k);a.once("close",f);a.once("finish",p);a.emit("pipe",m);n.flowing||(u("pipe resume"),m.resume());
return a};d.prototype.unpipe=function(a){var b=this._readableState,c={hasUnpiped:!1};if(0===b.pipesCount)return this;if(1===b.pipesCount){if(a&&a!==b.pipes)return this;a||(a=b.pipes);b.pipes=null;b.pipesCount=0;b.flowing=!1;a&&a.emit("unpipe",this,c);return this}if(!a){a=b.pipes;var d=b.pipesCount;b.pipes=null;b.pipesCount=0;b.flowing=!1;for(b=0;b<d;b++)a[b].emit("unpipe",this,c);return this}d=L(b.pipes,a);if(-1===d)return this;b.pipes.splice(d,1);--b.pipesCount;1===b.pipesCount&&(b.pipes=b.pipes[0]);
a.emit("unpipe",this,c);return this};d.prototype.on=function(a,b){b=C.prototype.on.call(this,a,b);"data"===a?!1!==this._readableState.flowing&&this.resume():"readable"===a&&(a=this._readableState,a.endEmitted||a.readableListening||(a.readableListening=a.needReadable=!0,a.emittedReadable=!1,a.reading?a.length&&q(this):F(J,this)));return b};d.prototype.addListener=d.prototype.on;d.prototype.resume=function(){var a=this._readableState;a.flowing||(u("resume"),a.flowing=!0,a.resumeScheduled||(a.resumeScheduled=
!0,F(H,this,a)));return this};d.prototype.pause=function(){u("call pause flowing=%j",this._readableState.flowing);!1!==this._readableState.flowing&&(u("pause"),this._readableState.flowing=!1,this.emit("pause"));return this};d.prototype.wrap=function(a){var b=this._readableState,c=!1,d=this;a.on("end",function(){u("wrapped end");if(b.decoder&&!b.ended){var a=b.decoder.end();a&&a.length&&d.push(a)}d.push(null)});a.on("data",function(e){u("wrapped data");b.decoder&&(e=b.decoder.write(e));b.objectMode&&
(null===e||void 0===e)||!(b.objectMode||e&&e.length)||d.push(e)||(c=!0,a.pause())});for(var e in a)void 0===this[e]&&"function"===typeof a[e]&&(this[e]=function(b){return function(){return a[b].apply(a,arguments)}}(e));for(e=0;e<n.length;e++)a.on(n[e],d.emit.bind(d,n[e]));d._read=function(b){u("wrapped _read",b);c&&(c=!1,a.resume())};return d};d._fromList=x}).call(this,c("_process"),"undefined"!==typeof global?global:"undefined"!==typeof self?self:"undefined"!==typeof window?window:{})},{"./_stream_duplex":26,
"./internal/streams/BufferList":31,"./internal/streams/destroy":32,"./internal/streams/stream":33,_process:24,"core-util-is":34,events:21,inherits:22,isarray:35,"process-nextick-args":36,"safe-buffer":37,"string_decoder/":44,util:17}],29:[function(c,f,h){function b(a){this.afterTransform=function(b,c){var d=a._transformState;d.transforming=!1;var k=d.writecb;k?(d.writechunk=null,d.writecb=null,null!==c&&void 0!==c&&a.push(c),k(b),b=a._readableState,b.reading=!1,(b.needReadable||b.length<b.highWaterMark)&&
a._read(b.highWaterMark),b=void 0):b=a.emit("error",Error("write callback called multiple times"));return b};this.transforming=this.needTransform=!1;this.writeencoding=this.writechunk=this.writecb=null}function a(c){if(!(this instanceof a))return new a(c);l.call(this,c);this._transformState=new b(this);var d=this;this._readableState.needReadable=!0;this._readableState.sync=!1;c&&("function"===typeof c.transform&&(this._transform=c.transform),"function"===typeof c.flush&&(this._flush=c.flush));this.once("prefinish",
function(){"function"===typeof this._flush?this._flush(function(a,b){m(d,a,b)}):m(d)})}function m(a,b,c){if(b)return a.emit("error",b);null!==c&&void 0!==c&&a.push(c);b=a._transformState;if(a._writableState.length)throw Error("Calling transform done when ws.length != 0");if(b.transforming)throw Error("Calling transform done when still transforming");return a.push(null)}f.exports=a;var l=c("./_stream_duplex");f=c("core-util-is");f.inherits=c("inherits");f.inherits(a,l);a.prototype.push=function(a,
b){this._transformState.needTransform=!1;return l.prototype.push.call(this,a,b)};a.prototype._transform=function(a,b,c){throw Error("_transform() is not implemented");};a.prototype._write=function(a,b,c){var d=this._transformState;d.writecb=c;d.writechunk=a;d.writeencoding=b;d.transforming||(a=this._readableState,(d.needTransform||a.needReadable||a.length<a.highWaterMark)&&this._read(a.highWaterMark))};a.prototype._read=function(a){a=this._transformState;null!==a.writechunk&&a.writecb&&!a.transforming?
(a.transforming=!0,this._transform(a.writechunk,a.writeencoding,a.afterTransform)):a.needTransform=!0};a.prototype._destroy=function(a,b){var c=this;l.prototype._destroy.call(this,a,function(a){b(a);c.emit("close")})}},{"./_stream_duplex":26,"core-util-is":34,inherits:22}],30:[function(c,f,h){(function(b,a){function m(a){var b=this;this.entry=this.next=null;this.finish=function(){var c=b.entry;for(b.entry=null;c;){var d=c.callback;a.pendingcb--;d(void 0);c=c.next}a.corkedRequestsFree?a.corkedRequestsFree.next=
b:a.corkedRequestsFree=b}}function l(){}function d(a,b){v=v||c("./_stream_duplex");a=a||{};this.objectMode=!!a.objectMode;b instanceof v&&(this.objectMode=this.objectMode||!!a.writableObjectMode);var d=a.highWaterMark,k=this.objectMode?16:16384;this.highWaterMark=d||0===d?d:k;this.highWaterMark=Math.floor(this.highWaterMark);this.destroyed=this.finished=this.ended=this.ending=this.needDrain=this.finalCalled=!1;this.decodeStrings=!1!==a.decodeStrings;this.defaultEncoding=a.defaultEncoding||"utf8";
this.length=0;this.writing=!1;this.corked=0;this.sync=!0;this.bufferProcessing=!1;this.onwrite=function(a){var c=b._writableState,d=c.sync,k=c.writecb;c.writing=!1;c.writecb=null;c.length-=c.writelen;c.writelen=0;a?(--c.pendingcb,d?(J(k,a),J(y,b,c),b._writableState.errorEmitted=!0,b.emit("error",a)):(k(a),b._writableState.errorEmitted=!0,b.emit("error",a),y(b,c))):((a=A(c))||c.corked||c.bufferProcessing||!c.bufferedRequest||q(b,c),d?H(E,b,c,a,k):E(b,c,a,k))};this.writecb=null;this.writelen=0;this.lastBufferedRequest=
this.bufferedRequest=null;this.pendingcb=0;this.errorEmitted=this.prefinished=!1;this.bufferedRequestCount=0;this.corkedRequestsFree=new m(this)}function h(a){v=v||c("./_stream_duplex");if(!(F.call(h,this)||this instanceof v))return new h(a);this._writableState=new d(a,this);this.writable=!0;a&&("function"===typeof a.write&&(this._write=a.write),"function"===typeof a.writev&&(this._writev=a.writev),"function"===typeof a.destroy&&(this._destroy=a.destroy),"function"===typeof a.final&&(this._final=
a.final));z.call(this)}function k(a,b,c,d,k,f,h){b.writelen=d;b.writecb=h;b.writing=!0;b.sync=!0;c?a._writev(k,b.onwrite):a._write(k,f,b.onwrite);b.sync=!1}function E(a,b,c,d){!c&&0===b.length&&b.needDrain&&(b.needDrain=!1,a.emit("drain"));b.pendingcb--;d();y(a,b)}function q(a,b){b.bufferProcessing=!0;var c=b.bufferedRequest;if(a._writev&&c&&c.next){var d=Array(b.bufferedRequestCount),f=b.corkedRequestsFree;f.entry=c;for(var h=0,l=!0;c;)d[h]=c,c.isBuf||(l=!1),c=c.next,h+=1;d.allBuffers=l;k(a,b,!0,
b.length,d,"",f.finish);b.pendingcb++;b.lastBufferedRequest=null;f.next?(b.corkedRequestsFree=f.next,f.next=null):b.corkedRequestsFree=new m(b)}else{for(;c&&(d=c.chunk,k(a,b,!1,b.objectMode?1:d.length,d,c.encoding,c.callback),c=c.next,!b.writing););null===c&&(b.lastBufferedRequest=null)}b.bufferedRequestCount=0;b.bufferedRequest=c;b.bufferProcessing=!1}function A(a){return a.ending&&0===a.length&&null===a.bufferedRequest&&!a.finished&&!a.writing}function t(a,b){a._final(function(c){b.pendingcb--;
c&&a.emit("error",c);b.prefinished=!0;a.emit("prefinish");y(a,b)})}function y(a,b){var c=A(b);c&&(b.prefinished||b.finalCalled||("function"===typeof a._final?(b.pendingcb++,b.finalCalled=!0,J(t,a,b)):(b.prefinished=!0,a.emit("prefinish"))),0===b.pendingcb&&(b.finished=!0,a.emit("finish")));return c}var J=c("process-nextick-args");f.exports=h;var H=!b.browser&&-1<["v0.10","v0.9."].indexOf(b.version.slice(0,5))?setImmediate:J,v;h.WritableState=d;b=c("core-util-is");b.inherits=c("inherits");var x={deprecate:c("util-deprecate")},
z=c("./internal/streams/stream"),I=c("safe-buffer").Buffer,L=a.Uint8Array||function(){};a=c("./internal/streams/destroy");b.inherits(h,z);d.prototype.getBuffer=function(){for(var a=this.bufferedRequest,b=[];a;)b.push(a),a=a.next;return b};(function(){try{Object.defineProperty(d.prototype,"buffer",{get:x.deprecate(function(){return this.getBuffer()},"_writableState.buffer is deprecated. Use _writableState.getBuffer instead.","DEP0003")})}catch(B){}})();if("function"===typeof Symbol&&Symbol.hasInstance&&
"function"===typeof Function.prototype[Symbol.hasInstance]){var F=Function.prototype[Symbol.hasInstance];Object.defineProperty(h,Symbol.hasInstance,{value:function(a){return F.call(this,a)?!0:a&&a._writableState instanceof d}})}else F=function(a){return a instanceof this};h.prototype.pipe=function(){this.emit("error",Error("Cannot pipe, not readable"))};h.prototype.write=function(a,b,c){var d=this._writableState,f=!1,h=a;(h=(I.isBuffer(h)||h instanceof L)&&!d.objectMode)&&!I.isBuffer(a)&&(a=I.from(a));
"function"===typeof b&&(c=b,b=null);h?b="buffer":b||(b=d.defaultEncoding);"function"!==typeof c&&(c=l);if(d.ended)d=c,c=Error("write after end"),this.emit("error",c),J(d,c);else{var m;if(!(m=h)){m=a;var p=c,H=!0,n=!1;null===m?n=new TypeError("May not write null values to stream"):"string"===typeof m||void 0===m||d.objectMode||(n=new TypeError("Invalid non-string/buffer chunk"));n&&(this.emit("error",n),J(p,n),H=!1);m=H}m&&(d.pendingcb++,f=h,f||(h=a,d.objectMode||!1===d.decodeStrings||"string"!==typeof h||
(h=I.from(h,b)),a!==h&&(f=!0,b="buffer",a=h)),m=d.objectMode?1:a.length,d.length+=m,h=d.length<d.highWaterMark,h||(d.needDrain=!0),d.writing||d.corked?(m=d.lastBufferedRequest,d.lastBufferedRequest={chunk:a,encoding:b,isBuf:f,callback:c,next:null},m?m.next=d.lastBufferedRequest:d.bufferedRequest=d.lastBufferedRequest,d.bufferedRequestCount+=1):k(this,d,!1,m,a,b,c),f=h)}return f};h.prototype.cork=function(){this._writableState.corked++};h.prototype.uncork=function(){var a=this._writableState;a.corked&&
(a.corked--,a.writing||a.corked||a.finished||a.bufferProcessing||!a.bufferedRequest||q(this,a))};h.prototype.setDefaultEncoding=function(a){"string"===typeof a&&(a=a.toLowerCase());if(!(-1<"hex utf8 utf-8 ascii binary base64 ucs2 ucs-2 utf16le utf-16le raw".split(" ").indexOf((a+"").toLowerCase())))throw new TypeError("Unknown encoding: "+a);this._writableState.defaultEncoding=a;return this};h.prototype._write=function(a,b,c){c(Error("_write() is not implemented"))};h.prototype._writev=null;h.prototype.end=
function(a,b,c){var d=this._writableState;"function"===typeof a?(c=a,b=a=null):"function"===typeof b&&(c=b,b=null);null!==a&&void 0!==a&&this.write(a,b);d.corked&&(d.corked=1,this.uncork());if(!d.ending&&!d.finished){a=c;d.ending=!0;y(this,d);if(a)if(d.finished)J(a);else this.once("finish",a);d.ended=!0;this.writable=!1}};Object.defineProperty(h.prototype,"destroyed",{get:function(){return void 0===this._writableState?!1:this._writableState.destroyed},set:function(a){this._writableState&&(this._writableState.destroyed=
a)}});h.prototype.destroy=a.destroy;h.prototype._undestroy=a.undestroy;h.prototype._destroy=function(a,b){this.end();b(a)}}).call(this,c("_process"),"undefined"!==typeof global?global:"undefined"!==typeof self?self:"undefined"!==typeof window?window:{})},{"./_stream_duplex":26,"./internal/streams/destroy":32,"./internal/streams/stream":33,_process:24,"core-util-is":34,inherits:22,"process-nextick-args":36,"safe-buffer":37,"util-deprecate":38}],31:[function(c,f,h){var b=c("safe-buffer").Buffer;f.exports=
function(){function a(){if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");this.tail=this.head=null;this.length=0}a.prototype.push=function(a){a={data:a,next:null};0<this.length?this.tail.next=a:this.head=a;this.tail=a;++this.length};a.prototype.unshift=function(a){a={data:a,next:this.head};0===this.length&&(this.tail=a);this.head=a;++this.length};a.prototype.shift=function(){if(0!==this.length){var a=this.head.data;this.head=1===this.length?this.tail=null:this.head.next;
--this.length;return a}};a.prototype.clear=function(){this.head=this.tail=null;this.length=0};a.prototype.join=function(a){if(0===this.length)return"";for(var b=this.head,c=""+b.data;b=b.next;)c+=a+b.data;return c};a.prototype.concat=function(a){if(0===this.length)return b.alloc(0);if(1===this.length)return this.head.data;a=b.allocUnsafe(a>>>0);for(var c=this.head,d=0;c;)c.data.copy(a,d),d+=c.data.length,c=c.next;return a};return a}()},{"safe-buffer":37}],32:[function(c,f,h){function b(a,b){a.emit("error",
b)}var a=c("process-nextick-args");f.exports={destroy:function(c,f){var d=this,h=this._writableState&&this._writableState.destroyed;this._readableState&&this._readableState.destroyed||h?f?f(c):!c||this._writableState&&this._writableState.errorEmitted||a(b,this,c):(this._readableState&&(this._readableState.destroyed=!0),this._writableState&&(this._writableState.destroyed=!0),this._destroy(c||null,function(c){!f&&c?(a(b,d,c),d._writableState&&(d._writableState.errorEmitted=!0)):f&&f(c)}))},undestroy:function(){this._readableState&&
(this._readableState.destroyed=!1,this._readableState.reading=!1,this._readableState.ended=!1,this._readableState.endEmitted=!1);this._writableState&&(this._writableState.destroyed=!1,this._writableState.ended=!1,this._writableState.ending=!1,this._writableState.finished=!1,this._writableState.errorEmitted=!1)}}},{"process-nextick-args":36}],33:[function(c,f,h){f.exports=c("events").EventEmitter},{events:21}],34:[function(c,f,h){(function(b){h.isArray=function(a){return Array.isArray?Array.isArray(a):
"[object Array]"===Object.prototype.toString.call(a)};h.isBoolean=function(a){return"boolean"===typeof a};h.isNull=function(a){return null===a};h.isNullOrUndefined=function(a){return null==a};h.isNumber=function(a){return"number"===typeof a};h.isString=function(a){return"string"===typeof a};h.isSymbol=function(a){return"symbol"===typeof a};h.isUndefined=function(a){return void 0===a};h.isRegExp=function(a){return"[object RegExp]"===Object.prototype.toString.call(a)};h.isObject=function(a){return"object"===
typeof a&&null!==a};h.isDate=function(a){return"[object Date]"===Object.prototype.toString.call(a)};h.isError=function(a){return"[object Error]"===Object.prototype.toString.call(a)||a instanceof Error};h.isFunction=function(a){return"function"===typeof a};h.isPrimitive=function(a){return null===a||"boolean"===typeof a||"number"===typeof a||"string"===typeof a||"symbol"===typeof a||"undefined"===typeof a};h.isBuffer=b.isBuffer}).call(this,{isBuffer:c("../../../../insert-module-globals/node_modules/is-buffer/index.js")})},
{"../../../../insert-module-globals/node_modules/is-buffer/index.js":23}],35:[function(c,f,h){var b={}.toString;f.exports=Array.isArray||function(a){return"[object Array]"==b.call(a)}},{}],36:[function(c,f,h){(function(b){function a(a,c,d,f){if("function"!==typeof a)throw new TypeError('"callback" argument must be a function');var k=arguments.length;switch(k){case 0:case 1:return b.nextTick(a);case 2:return b.nextTick(function(){a.call(null,c)});case 3:return b.nextTick(function(){a.call(null,c,d)});
case 4:return b.nextTick(function(){a.call(null,c,d,f)});default:var h=Array(k-1);for(k=0;k<h.length;)h[k++]=arguments[k];return b.nextTick(function(){a.apply(null,h)})}}!b.version||0===b.version.indexOf("v0.")||0===b.version.indexOf("v1.")&&0!==b.version.indexOf("v1.8.")?f.exports=a:f.exports=b.nextTick}).call(this,c("_process"))},{_process:24}],37:[function(c,f,h){function b(a,b){for(var c in a)b[c]=a[c]}function a(a,b,c){return l(a,b,c)}var m=c("buffer"),l=m.Buffer;l.from&&l.alloc&&l.allocUnsafe&&
l.allocUnsafeSlow?f.exports=m:(b(m,h),h.Buffer=a);b(l,a);a.from=function(a,b,c){if("number"===typeof a)throw new TypeError("Argument must not be a number");return l(a,b,c)};a.alloc=function(a,b,c){if("number"!==typeof a)throw new TypeError("Argument must be a number");a=l(a);void 0!==b?"string"===typeof c?a.fill(b,c):a.fill(b):a.fill(0);return a};a.allocUnsafe=function(a){if("number"!==typeof a)throw new TypeError("Argument must be a number");return l(a)};a.allocUnsafeSlow=function(a){if("number"!==
typeof a)throw new TypeError("Argument must be a number");return m.SlowBuffer(a)}},{buffer:18}],38:[function(c,f,h){(function(b){function a(a){try{if(!b.localStorage)return!1}catch(l){return!1}a=b.localStorage[a];return null==a?!1:"true"===String(a).toLowerCase()}f.exports=function(b,c){if(a("noDeprecation"))return b;var d=!1;return function(){if(!d){if(a("throwDeprecation"))throw Error(c);a("traceDeprecation")?console.trace(c):console.warn(c);d=!0}return b.apply(this,arguments)}}}).call(this,"undefined"!==
typeof global?global:"undefined"!==typeof self?self:"undefined"!==typeof window?window:{})},{}],39:[function(c,f,h){f.exports=c("./readable").PassThrough},{"./readable":40}],40:[function(c,f,h){h=f.exports=c("./lib/_stream_readable.js");h.Stream=h;h.Readable=h;h.Writable=c("./lib/_stream_writable.js");h.Duplex=c("./lib/_stream_duplex.js");h.Transform=c("./lib/_stream_transform.js");h.PassThrough=c("./lib/_stream_passthrough.js")},{"./lib/_stream_duplex.js":26,"./lib/_stream_passthrough.js":27,"./lib/_stream_readable.js":28,
"./lib/_stream_transform.js":29,"./lib/_stream_writable.js":30}],41:[function(c,f,h){f.exports=c("./readable").Transform},{"./readable":40}],42:[function(c,f,h){f.exports=c("./lib/_stream_writable.js")},{"./lib/_stream_writable.js":30}],43:[function(c,f,h){function b(){a.call(this)}f.exports=b;var a=c("events").EventEmitter;c("inherits")(b,a);b.Readable=c("readable-stream/readable.js");b.Writable=c("readable-stream/writable.js");b.Duplex=c("readable-stream/duplex.js");b.Transform=c("readable-stream/transform.js");
b.PassThrough=c("readable-stream/passthrough.js");b.Stream=b;b.prototype.pipe=function(b,c){function d(a){b.writable&&!1===b.write(a)&&t.pause&&t.pause()}function f(){t.readable&&t.resume&&t.resume()}function h(){y||(y=!0,b.end())}function l(){y||(y=!0,"function"===typeof b.destroy&&b.destroy())}function m(b){A();if(0===a.listenerCount(this,"error"))throw b;}function A(){t.removeListener("data",d);b.removeListener("drain",f);t.removeListener("end",h);t.removeListener("close",l);t.removeListener("error",
m);b.removeListener("error",m);t.removeListener("end",A);t.removeListener("close",A);b.removeListener("close",A)}var t=this;t.on("data",d);b.on("drain",f);b._isStdio||c&&!1===c.end||(t.on("end",h),t.on("close",l));var y=!1;t.on("error",m);b.on("error",m);t.on("end",A);t.on("close",A);b.on("close",A);b.emit("pipe",t);return b}},{events:21,inherits:22,"readable-stream/duplex.js":25,"readable-stream/passthrough.js":39,"readable-stream/readable.js":40,"readable-stream/transform.js":41,"readable-stream/writable.js":42}],
44:[function(c,f,h){function b(a){if(!a)return"utf8";for(var b;;)switch(a){case "utf8":case "utf-8":return"utf8";case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":return"utf16le";case "latin1":case "binary":return"latin1";case "base64":case "ascii":case "hex":return a;default:if(b)return;a=(""+a).toLowerCase();b=!0}}function a(a){var c=b(a);if("string"!==typeof c&&(y.isEncoding===J||!J(a)))throw Error("Unknown encoding: "+a);this.encoding=c||a;switch(this.encoding){case "utf16le":this.text=
p;this.end=k;a=4;break;case "utf8":this.fillLast=d;a=4;break;case "base64":this.text=E;this.end=q;a=3;break;default:this.write=A;this.end=t;return}this.lastTotal=this.lastNeed=0;this.lastChar=y.allocUnsafe(a)}function m(a){return 127>=a?0:6===a>>5?2:14===a>>4?3:30===a>>3?4:-1}function l(a,b,c){var d=b.length-1;if(d<c)return 0;var f=m(b[d]);if(0<=f)return 0<f&&(a.lastNeed=f-1),f;if(--d<c)return 0;f=m(b[d]);if(0<=f)return 0<f&&(a.lastNeed=f-2),f;if(--d<c)return 0;f=m(b[d]);return 0<=f?(0<f&&(2===f?
f=0:a.lastNeed=f-3),f):0}function d(a){var b=this.lastTotal-this.lastNeed;a:if(128!==(a[0]&192)){this.lastNeed=0;var c="\ufffd".repeat(b)}else{if(1<this.lastNeed&&1<a.length){if(128!==(a[1]&192)){this.lastNeed=1;c="\ufffd".repeat(b+1);break a}if(2<this.lastNeed&&2<a.length&&128!==(a[2]&192)){this.lastNeed=2;c="\ufffd".repeat(b+2);break a}}c=void 0}if(void 0!==c)return c;if(this.lastNeed<=a.length)return a.copy(this.lastChar,b,0,this.lastNeed),this.lastChar.toString(this.encoding,0,this.lastTotal);
a.copy(this.lastChar,b,0,a.length);this.lastNeed-=a.length}function p(a,b){if(0===(a.length-b)%2){if(b=a.toString("utf16le",b)){var c=b.charCodeAt(b.length-1);if(55296<=c&&56319>=c)return this.lastNeed=2,this.lastTotal=4,this.lastChar[0]=a[a.length-2],this.lastChar[1]=a[a.length-1],b.slice(0,-1)}return b}this.lastNeed=1;this.lastTotal=2;this.lastChar[0]=a[a.length-1];return a.toString("utf16le",b,a.length-1)}function k(a){a=a&&a.length?this.write(a):"";return this.lastNeed?a+this.lastChar.toString("utf16le",
0,this.lastTotal-this.lastNeed):a}function E(a,b){var c=(a.length-b)%3;if(0===c)return a.toString("base64",b);this.lastNeed=3-c;this.lastTotal=3;1===c?this.lastChar[0]=a[a.length-1]:(this.lastChar[0]=a[a.length-2],this.lastChar[1]=a[a.length-1]);return a.toString("base64",b,a.length-c)}function q(a){a=a&&a.length?this.write(a):"";return this.lastNeed?a+this.lastChar.toString("base64",0,3-this.lastNeed):a}function A(a){return a.toString(this.encoding)}function t(a){return a&&a.length?this.write(a):
""}var y=c("safe-buffer").Buffer,J=y.isEncoding||function(a){a=""+a;switch(a&&a.toLowerCase()){case "hex":case "utf8":case "utf-8":case "ascii":case "binary":case "base64":case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":case "raw":return!0;default:return!1}};h.StringDecoder=a;a.prototype.write=function(a){if(0===a.length)return"";if(this.lastNeed){var b=this.fillLast(a);if(void 0===b)return"";var c=this.lastNeed;this.lastNeed=0}else c=0;return c<a.length?b?b+this.text(a,c):this.text(a,c):
b||""};a.prototype.end=function(a){a=a&&a.length?this.write(a):"";return this.lastNeed?a+"\ufffd".repeat(this.lastTotal-this.lastNeed):a};a.prototype.text=function(a,b){var c=l(this,a,b);if(!this.lastNeed)return a.toString("utf8",b);this.lastTotal=c;c=a.length-(c-this.lastNeed);a.copy(this.lastChar,0,c);return a.toString("utf8",b,c)};a.prototype.fillLast=function(a){if(this.lastNeed<=a.length)return a.copy(this.lastChar,this.lastTotal-this.lastNeed,0,this.lastNeed),this.lastChar.toString(this.encoding,
0,this.lastTotal);a.copy(this.lastChar,this.lastTotal-this.lastNeed,0,a.length);this.lastNeed-=a.length}},{"safe-buffer":45}],45:[function(c,f,h){arguments[4][37][0].apply(h,arguments)},{buffer:18,dup:37}]},{},[1])(1)});
