(function(g){(g.NSSS=g.NSSS||{}).annotatePage=function(c,e){var b={};b.isTop=window===window.top;var k=e.utils.isNil,g=e.utils.isntNil,n=e.utils.getCompanyDomain,u=c.nfmEvents,m=c.constants,f=c.uiConstants,h=f.MESSAGES,l=e.extensionAdapter,p=c.NSSSHelper,q=e.utils.createNewGuid(),r=e.performanceReporterFactoryProxy,t="Annotation Time: "+Date.now();b._popupClosed=!0;b.COLLECT_URL_TIMEOUT=500;b._canAllowAnnotations=function(){if(f.EXTENSION_TYPE===f.SAFEWEB_EXTENSION&&"Chrome"===e.globals.BROWSER||
f.EXTENSION_TYPE===f.TWO_IN_ONE&&"Safari"===e.globals.BROWSER)if(e.utils.getOSType()===e.constants.os.WINDOWS){var a=n(window.location.href),b=n(document.referrer);a=k(a)?null:a.toLowerCase();b=k(b)?null:b.toLowerCase();if(k(a)||a===m.MYWAY||b===m.MYWAY)return!1}else return 0<=window.location.host.toLowerCase().search("ask")||0<=document.referrer.search("nortonsafe.search.ask.com")?!0:p.isYahooSERPPage(window.location.href);else if(f.EXTENSION_TYPE===f.THREE_IN_ONE&&c.constants.VENDOR===c.constants.YAHOO)return p.isYahooSERPPage(window.location.href);
return!0};b.collectURLs=function(){r.reportStart(m.performanceReporter.NSSS,t);if(!1!==b._canAllowAnnotations()&&!k(Shasta)){var a=Shasta.collectURLs();(g(a.resultURLs)&&0<a.resultURLs.length||g(a.advtURLs)&&0<a.advtURLs.length)&&l.sendMessage({name:h.COLLECT_URL_RESPONSE,message:{eventID:u.SEARCH_URLS,search_urls:a.resultURLs,advt_urls:a.advtURLs,frameId:q}})}};b.showAnnotationPopup=function(a){if(b.isTop){var c=document.getElementById("annotationPopup");c.style.display="block";var d=a.top,e=a.left,
g=e+406,f=d+238;innerHeight<f&&(f-=innerHeight,d-=f);innerWidth<g&&(f=g-innerWidth,e-=f);0>d&&(d=2);c.style.top=d+"px";c.style.left=e+"px";c.style.border="none";c=document.getElementById("annotationPopup").contentWindow;d=a.annotationURLObject.annotationData;d.index=a.index;c.postMessage({name:"preparePopup",message:d},"*")}};b.closeAnnotationPopup=function(){if(b.isTop){var a=document.getElementById("annotationPopup");g(a)&&(a.style.display="none")}};b.annotateURLs=function(a){var c=a.annotationResults;
if(!k(Shasta)){if(b.isTop){var d=document.getElementById("annotationPopup");k(d)&&(d=document.createElement("iframe"),d.id="annotationPopup",d.style.cssText="position:fixed;top:0;left:0;display:none;width:408px;height:240px;z-index:1000;",d.src=l.getExtensionURL("content/ui/SiteRatingPane.html"),document.body.appendChild(d))}g(a.frameId)&&a.frameId!==q||(Shasta.setResults(c),r.reportEnd(m.performanceReporter.NSSS,t),document.addEventListener("showAnnotationPopup",function(a){l.sendMessage({name:h.SHOW_ANNOTATION_POPUP,
message:a.detail});b._popupClosed=!1}),document.addEventListener("closeAnnotationPopup",function(a){!1===b._popupClosed&&(l.sendMessage({name:h.CLOSE_ANNOATION_POPUP}),b._popupClosed=!0)}))}};b.canCloseAnnotationPopup=function(){b.isTop&&document.getElementById("annotationPopup").contentWindow.postMessage({name:"canCloseAnnotation"},"*")};b.handleCustomMessages=function(a){switch(a.name){case "annotate-urls":b.annotateURLs(a);break;case h.SHOW_ANNOTATION_POPUP:b.showAnnotationPopup(a.data);break;
case h.CLOSE_ANNOATION_POPUP:b.canCloseAnnotationPopup()}};b.handleOpenFullReport=function(a){l.sendMessage({name:h.OPEN_FULLREPORT,message:{index:a.detail}})};b.receiveMessage=function(a){switch(a.data.name){case "closeAnnotationPopup":b.closeAnnotationPopup();break;case "openFullReportFromPanel":l.sendMessage({name:h.OPEN_FULLREPORT,message:{index:a.data.message.index}})}};b.handleBasicMessage=function(a,c,d){b.handleCustomMessages(a)};b.handleWindowLoad=function(){document.addEventListener("CollectUrlEvent",
function(){setTimeout(c.annotatePage.collectURLs,c.annotatePage.COLLECT_URL_TIMEOUT)});setTimeout(c.annotatePage.collectURLs,c.annotatePage.COLLECT_URL_TIMEOUT)};return b}(g.NSSS,g.SymBfw)})(executionContext);SymBfw.extensionAdapter.addMessageListener(NSSS.annotatePage.handleBasicMessage);window.addEventListener("load",function(){NSSS.annotatePage.handleWindowLoad()});document.addEventListener("openFullReport",NSSS.annotatePage.handleOpenFullReport);
window.addEventListener("message",NSSS.annotatePage.receiveMessage,!1);
