var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,c,b){a instanceof String&&(a=String(a));for(var g=a.length,f=0;f<g;f++){var d=a[f];if(c.call(b,d,f,a))return{i:f,v:d}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,c,b,g){if(c){b=$jscomp.global;a=a.split(".");for(g=0;g<a.length-1;g++){var f=a[g];f in b||(b[f]={});b=b[f]}a=a[a.length-1];g=b[a];c=c(g);c!=g&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6","es3");$jscomp.polyfill("Object.is",function(a){return a?a:function(a,b){return a===b?0!==a||1/a===1/b:a!==a&&b!==b}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,b){var c=this;c instanceof String&&(c=String(c));var f=c.length;b=b||0;for(0>b&&(b=Math.max(b+f,0));b<f;b++){var d=c[b];if(d===a||Object.is(d,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,c,b){if(null==a)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,b){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,b||0)}},"es6","es3");
(function(a){a.SymBfw.notificationCenterProxy=function(a){var b=a.utils.isNil,c=a.utils.isntNil,f=a.logger,d=a.constants.uiConstants.NOTIFICATION,k=a.uiUtils,l=a.utils.isArray,h=a.extensionAdapter,e={timeoutShowNotification:null,closeNotifications:function(){var a=d.IFRAME_ID+"-"+h.getExtensionId();a=document.querySelectorAll("[id='"+a+"']");if(c(a))for(var b=0;b<a.length;b++)document.documentElement.removeChild(a[b])},handleMessage:function(a){switch(a.eventID){case d.MESSAGES.NOTIFICATION_QUEUE_MESSAGE:if(!l(a.notificationArray)){f.error("unexpected payload for NOTIFICATION_QUEUE_MESSAGE");
break}c(e.timeoutShowNotification)&&clearTimeout(e.timeoutShowNotification);e.timeoutShowNotification=setTimeout(function(){e.notificationArray=a.notificationArray;if(0===e.notificationArray.length)e.closeNotifications();else{for(var b in e.notificationArray){var d=e.notificationArray[b].blockListedUrls,f=!0;c(d)&&0!==d.length&&c(d.find(function(a){return a.includes(document.location.origin)}))&&(f=!1);e.notificationArray[b].isAllowed=f}e.showNotifications();e.timeoutShowNotification=null}},100);
break;case d.MESSAGES.HIDE_NOTIFICATIONS:e.closeNotifications()}},showNotifications:function(){e.closeNotifications();var a=h.getExtensionURL(d.HTML),b=h.getExtensionURL(d.STYLE);k.injectStyle(b);b=d.IFRAME_ID+"-"+h.getExtensionId();k.createFrame(b,a,d.HEIGHT,d.WIDTH)},addEventListener:function(){h.addContentScriptMessageListener(function(a,c,f){switch(a.id){case d.MESSAGES.DEFAULT_MESSAGE:if(b(a.payload))break;return e.handleMessage(a.payload);case d.MESSAGES.UI_INIT_PROXY:return c({notifications:e.notificationArray,
direction:k.getDirection()})}})},initialize:function(){k.isTopLevelWindow()&&(e.addEventListener(),h.sendMessage({id:d.MESSAGES.DEFAULT_MESSAGE,payload:{eventID:d.MESSAGES.NOTIFICATION_QUEUE_MESSAGE}}))}};window.addEventListener("pageshow",function(a){a.persisted&&e.initialize()});e.initialize();return e}(a.SymBfw)})(this);
