var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(c){var n=0;return function(){return n<c.length?{done:!1,value:c[n++]}:{done:!0}}};$jscomp.arrayIterator=function(c){return{next:$jscomp.arrayIteratorImpl(c)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,n,q){c!=Array.prototype&&c!=Object.prototype&&(c[n]=q.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(c,n){this.$jscomp$symbol$id_=c;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:n})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function c(q){if(this instanceof c)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(q||"")+"_"+n++,q)}var n=0;return c}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.iterator;c||(c=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[c]&&$jscomp.defineProperty(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.asyncIterator;c||(c=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(c){$jscomp.initSymbolIterator();c={next:c};c[$jscomp.global.Symbol.iterator]=function(){return this};return c};
$jscomp.iteratorFromArray=function(c,n){$jscomp.initSymbolIterator();c instanceof String&&(c+="");var q=0,r={next:function(){if(q<c.length){var a=q++;return{value:n(a,c[a]),done:!1}}r.next=function(){return{done:!0,value:void 0}};return r.next()}};r[Symbol.iterator]=function(){return r};return r};
$jscomp.polyfill=function(c,n,q,r){if(n){q=$jscomp.global;c=c.split(".");for(r=0;r<c.length-1;r++){var a=c[r];a in q||(q[a]={});q=q[a]}c=c[c.length-1];r=q[c];n=n(r);n!=r&&null!=n&&$jscomp.defineProperty(q,c,{configurable:!0,writable:!0,value:n})}};$jscomp.polyfill("Array.prototype.keys",function(c){return c?c:function(){return $jscomp.iteratorFromArray(this,function(c){return c})}},"es6","es3");
$jscomp.checkStringArgs=function(c,n,q){if(null==c)throw new TypeError("The 'this' value for String.prototype."+q+" must not be null or undefined");if(n instanceof RegExp)throw new TypeError("First argument to String.prototype."+q+" must not be a regular expression");return c+""};
$jscomp.polyfill("String.prototype.startsWith",function(c){return c?c:function(c,q){var r=$jscomp.checkStringArgs(this,c,"startsWith");c+="";var a=r.length,b=c.length;q=Math.max(0,Math.min(q|0,r.length));for(var e=0;e<b&&q<a;)if(r[q++]!=c[e++])return!1;return e>=b}},"es6","es3");$jscomp.makeIterator=function(c){var n="undefined"!=typeof Symbol&&Symbol.iterator&&c[Symbol.iterator];return n?n.call(c):$jscomp.arrayIterator(c)};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(c){function n(){this.batch_=null}function q(b){return b instanceof a?b:new a(function(a,e){a(b)})}if(c&&!$jscomp.FORCE_POLYFILL_PROMISE)return c;n.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var r=$jscomp.global.setTimeout;n.prototype.asyncExecuteFunction=function(a){r(a,0)};n.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var t=a[b];a[b]=null;try{t()}catch(h){this.asyncThrow_(h)}}}this.batch_=null};n.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var a=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(t){b.reject(t)}};a.prototype.createResolveAndReject_=function(){function a(a){return function(g){t||(t=!0,a.call(b,g))}}var b=this,t=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};a.prototype.resolveTo_=function(b){if(b===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof a)this.settleSameAsPromise_(b);else{a:switch(typeof b){case "object":var f=null!=b;break a;case "function":f=!0;break a;default:f=!1}f?this.resolveToNonPromiseObj_(b):this.fulfill_(b)}};a.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(t){this.reject_(t);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};a.prototype.reject_=function(a){this.settle_(2,a)};a.prototype.fulfill_=function(a){this.settle_(1,a)};a.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};a.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)b.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var b=new n;a.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};a.prototype.settleSameAsThenable_=function(a,b){var f=this.createResolveAndReject_();try{a.call(b,f.resolve,f.reject)}catch(h){f.reject(h)}};a.prototype.then=function(b,f){function e(a,b){return"function"==typeof a?function(b){try{h(a(b))}catch(w){g(w)}}:b}var h,g,c=new a(function(a,b){h=a;g=b});this.callWhenSettled_(e(b,h),e(f,g));return c};
a.prototype.catch=function(a){return this.then(void 0,a)};a.prototype.callWhenSettled_=function(a,f){function e(){switch(h.state_){case 1:a(h.result_);break;case 2:f(h.result_);break;default:throw Error("Unexpected state: "+h.state_);}}var h=this;null==this.onSettledCallbacks_?b.asyncExecute(e):this.onSettledCallbacks_.push(e)};a.resolve=q;a.reject=function(b){return new a(function(a,e){e(b)})};a.race=function(b){return new a(function(a,e){for(var f=$jscomp.makeIterator(b),g=f.next();!g.done;g=f.next())q(g.value).callWhenSettled_(a,
e)})};a.all=function(b){var f=$jscomp.makeIterator(b),e=f.next();return e.done?q([]):new a(function(a,b){function g(b){return function(g){d[b]=g;l--;0==l&&a(d)}}var d=[],l=0;do d.push(void 0),l++,q(e.value).callWhenSettled_(g(d.length-1),b),e=f.next();while(!e.done)})};return a},"es6","es3");
!function s(c,n,q){function a(f,e){if(!n[f]){if(!c[f]){var h="function"==typeof require&&require;if(!e&&h)return h(f,!0);if(b)return b(f,!0);e=Error("Cannot find module '"+f+"'");throw e.code="MODULE_NOT_FOUND",e;}e=n[f]={exports:{}};c[f][0].call(e.exports,function(b){return a(c[f][1][b]||b)},e,e.exports,s,c,n,q)}return n[f].exports}for(var b="function"==typeof require&&require,e=0;e<q.length;e++)a(q[e]);return a}({1:[function(c,n,q){(function(){!function(c){var a;(c.FG=c.FG||{}).config=((a={page_process_timeout:1E3,
add_dock_timeout:200,add_ui_elements_timeout:250,remove_popup_timeout:2E3,iframe_post_timeout:100,add_dock_interval:125,add_dock_max_timeout:5E3,phishing_category_id:18,webmail_category_id:52,social_networking_id:55,financial_category_id:31,trading_category_id:32,uncategorized:90,default_risk_threshold_value:5,minimum_risk_threshold_value:1,response_success:100,response_failure:101,dock_start_minimized:!0,dock_show_always:!1,max_urls_per_request:30,beta:!1,url_markup_default_state:!0,max_banking_prompts_default:3,
max_banking_prompts_perpetual:999999,max_rate_limit_isolation_requests_OB:100,max_rate_limit_isolation_api:1E4,max_rate_limit_reset_interval:36E5,settings_key:{}}).settings_key.root="c74e3142-5342-44b1-b7b3-a32d80a55ca6",a.settings_key.url_markup="0f7aae85-cb4c-4991-90b7-4c27b8e7f69c",a.settings_key.online_banking="45e41ff5-6c11-4e5e-b5fd-8715b1d1a190",a.settings_key.online_banking_session_override="023b1a5d-1753-4ce9-9cff-f0bf54252b4b",a.settings_key.sign_in_flow_origin="b9016546-d9a3-4850-a097-3e34508bad22",
a.settings_key.scan_notification="796e1dda-4c45-4bb9-bf71-57d26c523923",a.settings_key.dock_timeout="f4fe49e3-90d2-4f93-97b9-c0d3de82364d",a.settings_key.use_modal="cade52d7-ae9f-44bd-b529-fd10d47ea0b1",a.settings_key.lg_sign_in_not_required_mode="643463ce-b557-429f-98ae-3577dec0b207",a.settings_key.feature_ui_configs_file_id="6bc2c7b7-8819-462d-acb5-9299bd908e26",a.settings_key.feature_ui_config_id="13e0849c-ef78-476d-b617-202654da8c6c",a.settings_key.max_banking_prompts="d8cc1e97-a6a2-4a7d-9479-fdd8e4684f68",
a.settings_key.banking_prompts_count="e165face-77cf-43eb-bb7d-3265ccd27ebf",a.settings_key.banking_sites="0b9a806d-9954-4e57-85b3-96b00d54d548",a.settings_key.ratelimit_runtime_count="b0fcd033-4be1-4b67-b59f-ce17d2935a99",a.settings_key.ratelimit_max_tries="38088dd1-21cc-444a-ad0c-fb4ac17740a0",a.settings_key.ratelimit_runtime_count_OB="0464e166-cd8e-46cb-8237-10a3e491fa44",a.settings_key.ratelimit_max_tries_OB="96d96c1c-6493-44ae-bc79-936c803a6710",a.settings_key.ratelimit_reset_interval="7a3a2967-cb2c-453a-a61e-43764fbf5691",
a.settings_key.dock_start_minimized="67733cb0-77de-41b7-9aa8-8e31a915758e",a.settings_key.dock_show_always="47258e7e-72e6-468e-809b-6f09dfb349a8",a.debug=!1,a.active_everywhere=!1,a.standalone=!1,a.staging=!1,a.sign_in_not_required_mode=!0,a.enable_online_banking=!0,a.only_whitelisted_banking_sites=!0,a.keyword_isolation_url="email-isolation.prod.fire.glass",a.keyword_isolation_url_norton_specific="isolate.norton.com",a.telemetry={},a.telemetry.TRACKING_ID="__FG_TRACKING_ID__",a.telemetry.SEND_PING=
"{04EFD197-5D63-43D6-A225-8E78B2514584}",a.telemetry.ping={},a.telemetry.ping.RatingsQuery={TOP_URL:"a",SCANNED_URLS:"b",BAD_URLS:"c",UNKNOWN_URLS:"d"},a.telemetry.ping.IsolationLaunch={TOP_URL:"a",ISOLATION_URL:"b",OPT_OUT:"c"},a.telemetry.ping.IsolationUsage={URL:"a",USE_TIME:"b",NAVIGATION_COMPLETE:"c",IDLE_TIME:"d",CLICK_COUNT:"e",KEY_COUNT:"f"},a.help_ids={SAFEMODE_01:10001,SAFEMODE_02:10002},a.notifications={},a.notifications.type={pageScanNotification:0},a.uiMessageProxy={},a.uiMessageProxy.EVENT_ID=
"{d3034228-f99f-459e-b971-6bd8e702e59b}",a.docControls={},a.docControls.EVENT_ID="{444eb5be-50bc-4d68-a133-d92d34de1ef6}",a.dialogRenderer={},a.dialogRenderer.EVENT_ID="{6400d87a-4919-47af-b243-b162194be77d}",a.dialogRendererProxy={},a.dialogRendererProxy.EVENT_ID="{87e8946f-b2eb-4776-9f09-5a3fe39c848e}",a.safeModeDialog={},a.safeModeDialog.EVENT_ID="{22bc9f72-b437-4745-812d-4ee3f3e41fc4}",a.dockMouseEvent={},a.dockMouseEvent.EVENT_ID="{50d7ef15-de29-4ea9-8268-99cd06288eb3}",a.dockMouseEvent.eventType=
{mouseEnter:0,mouseLeave:1,mouseOverFaq:2,click:3,close:4},a.dockPopupEvent={},a.dockPopupEvent.EVENT_ID="{4ebf0520-614e-4af2-b2c2-200ec3a63d18}",a.dockPopupEvent.eventType={show:0,hide:1,close:2},a.dockResourceEvent={},a.dockResourceEvent.EVENT_ID="{9a0c0b88-4dfe-4451-ba67-d73a636e1a92}",a.dockResourceEvent.eventType={unload:0},a.safeModeDialog.dialogType={threatIsolation:0,onlineBanking:1},a.safeModeDialog.dialogMode={signin:0,interstitial:1},a.safeModeDialog.displayState={hide:0,show:1},a.dockConfig=
{},a.dockConfig.sslStatus={insecure:0,secure:1},a.dockConfig.urlCategory={general:0,onlineBanking:1},a.dockConfig.trigger={onDemand:0,prompt:1},a.onlineBanking={Isolation_State:{On:0,Off:1,Prompt:2}},a.strings={},a.strings.dictionary="fg_strings",a.strings.security_popup={fg_security_header_text:"SUSPICIOUS LINK",fg_popup_description_text:"Norton now warns you of suspicious links in your email to protect you from malicious activity."},a.strings.dock={fg_leavefeedback_text:"Leave Feedback",fgdock_signin:"Try this feature"},
a.strings.banking_protection_disabled={message_text:"Banking Protection Disabled"},a.strings.banking_protection_enabled={message_text:"Banking Protection Enabled"},a.strings.isolation_mode_enabled={message_text:"You're browsing safely in Isolation Mode"},a.strings.faq_popup={fg_faq_msg:"Provides additional security for online transactions and helps keep your financial information and other personal data away from hackers.",fg_faq_msg_signed_in:"Provides additional security for online transactions and helps keep your financial information and other personal data away from hackers. You can turn this feature off in",
help:"Learn More",help_signed_in:"Settings"},a.strings.safemode_dialog={fg_desc_title:"If you visit this site...",fg_desc_isolation_summary:"Isolation Mode",fg_desc_isolation_text:"provides additional protection when visiting risky websites that may contain malware or browser exploits.",help:"Learn More",fg_signin_message:"Sign in to your Norton account to enable Isolation Mode.",footer_link:"Continue Without Isolation Mode",fg_signin_btn_text:"Sign In",fg_continue_btn_text:"Continue",fg_cancel_btn_text:"Cancel",
fg_leavefeedback_text:"Leave Feedback",fg_desc_title_banking:"Banking Protection",fg_desc_banking_protection_summary:"Isolation Mode",fg_desc_banking_protection_text:"provides additional security for online transactions and helps keep your financial information and other personal data away from hackers.",fg_signin_message_2:"Sign in to your Norton account to enable Isolation Mode.",help_2:"Learn More",fg_settings_this_website:"Remember for this website",fg_settings_all_websites:"Remember for all banking websites"},
a.strings.page_scan_notification={title:"",description:"We\u2019ll highlight suspicious links in Webmail, Facebook, Twitter and other accounts.",learn_more:"Learn More",ok_button:"OK"},a.default_country="US",a.site_redirector_url="http://sitedirector.symantec.com/932743328?ssdcat=SSDCAT_VALUE&env=prod&origin=nsss&displang=iso3:ISO3_LAN_CODE&displocale=iso3:ISO3_COUNTRY_CODE",a.ISO2_2_ISO3_lang={AB:"ABK",AA:"AAR",AF:"AFR",AK:"AKA",SQ:"SQI",AM:"AMH",AR:"ARA",AN:"ARG",HY:"HYE",AS:"ASM",AV:"AVA",AE:"AVE",
AY:"AYM",AZ:"AZE",BM:"BAM",BA:"BAK",EU:"EUS",BE:"BEL",BN:"BEN",BH:"BIH",BI:"BIS",BS:"BOS",BR:"BRE",BG:"BUL",MY:"MYA",CA:"CAT",CH:"CHA",CE:"CHE",NY:"NYA",ZH:"ZHO",CV:"CHV",KW:"COR",CO:"COS",CR:"CRE",HR:"HRV",CS:"CES",DA:"DAN",DV:"DIV",NL:"NLD",DZ:"DZO",EN:"ENG",EO:"EPO",ET:"EST",EE:"EWE",FO:"FAO",FJ:"FIJ",FI:"FIN",FR:"FRA",FF:"FUL",GL:"GLG",KA:"KAT",DE:"DEU",EL:"ELL",GN:"GRN",GU:"GUJ",HT:"HAT",HA:"HAU",HE:"HEB",HZ:"HER",HI:"HIN",HO:"HMO",HU:"HUN",IA:"INA",ID:"IND",IE:"ILE",GA:"GLE",IG:"IBO",IK:"IPK",
IO:"IDO",IS:"ISL",IT:"ITA",IU:"IKU",JA:"JPN",JV:"JAV",KL:"KAL",KN:"KAN",KR:"KAU",KS:"KAS",KK:"KAZ",KM:"KHM",KI:"KIK",RW:"KIN",KY:"KIR",KV:"KOM",KG:"KON",KO:"KOR",KU:"KUR",KJ:"KUA",LA:"LAT",LB:"LTZ",LG:"LUG",LI:"LIM",LN:"LIN",LO:"LAO",LT:"LIT",LU:"LUB",LV:"LAV",GV:"GLV",MK:"MKD",MG:"MLG",MS:"MSA",ML:"MAL",MT:"MLT",MI:"MRI",MR:"MAR",MH:"MAH",MN:"MON",NA:"NAU",NV:"NAV",ND:"NDE",NE:"NEP",NG:"NDO",NB:"NOB",NN:"NNO",NO:"NOR",II:"III",NR:"NBL",OC:"OCI",OJ:"OJI",CU:"CHU",OM:"ORM",OR:"ORI",OS:"OSS",PA:"PAN",
PI:"PLI",FA:"FAS",PL:"POL",PS:"PUS",PT:"POR",QU:"QUE",RM:"ROH",RN:"RUN",RO:"RON",RU:"RUS",SA:"SAN",SC:"SRD",SD:"SND",SE:"SME",SM:"SMO",SG:"SAG",SR:"SRP",GD:"GLA",SN:"SNA",SI:"SIN",SK:"SLK",SL:"SLV",SO:"SOM",ST:"SOT",ES:"SPA",SU:"SUN",SW:"SWA",SS:"SSW",SV:"SWE",TA:"TAM",TE:"TEL",TG:"TGK",TH:"THA",TI:"TIR",BO:"BOD",TK:"TUK",TL:"TGL",TN:"TSN",TO:"TON",TR:"TUR",TS:"TSO",TT:"TAT",TW:"TWI",TY:"TAH",UG:"UIG",UK:"UKR",UR:"URD",UZ:"UZB",VE:"VEN",VI:"VIE",VO:"VOL",WA:"WLN",CY:"CYM",WO:"WOL",FY:"FRY",XH:"XHO",
YI:"YID",YO:"YOR",ZA:"ZHA",ZU:"ZUL"},a.ISO2_2_ISO3_locale={AX:"ALA",AF:"AFG",AL:"ALB",DZ:"DZA",AS:"ASM",AD:"AND",AO:"AGO",AI:"AIA",AQ:"ATA",AG:"ATG",AR:"ARG",AM:"ARM",AW:"ABW",AU:"AUS",AT:"AUT",AZ:"AZE",BS:"BHS",BH:"BHR",BD:"BGD",BB:"BRB",BY:"BLR",BE:"BEL",BZ:"BLZ",BJ:"BEN",BM:"BMU",BT:"BTN",BO:"BOL",BA:"BIH",BW:"BWA",BV:"BVT",BR:"BRA",IO:"IOT",BN:"BRN",BG:"BGR",BF:"BFA",BI:"BDI",KH:"KHM",CM:"CMR",CA:"CAN",CV:"CPV",KY:"CYM",CF:"CAF",TD:"TCD",CL:"CHL",CN:"CHN",CX:"CXR",CC:"CCK",CO:"COL",KM:"COM",CD:"COD",
CG:"COG",CK:"COK",CR:"CRI",CI:"CIV",HR:"HRV",CU:"CUB",CY:"CYP",CZ:"CZE",DK:"DNK",DJ:"DJI",DM:"DMA",DO:"DOM",EC:"ECU",EG:"EGY",SV:"SLV",GQ:"GNQ",ER:"ERI",EE:"EST",ET:"ETH",FK:"FLK",FO:"FRO",FJ:"FJI",FI:"FIN",FR:"FRA",GF:"GUF",PF:"PYF",TF:"ATF",GA:"GAB",GM:"GMB",GE:"GEO",DE:"DEU",GH:"GHA",GI:"GIB",GR:"GRC",GL:"GRL",GD:"GRD",GP:"GLP",GU:"GUM",GT:"GTM",GN:"GIN",GW:"GNB",GY:"GUY",HT:"HTI",HM:"HMD",HN:"HND",HK:"HKG",HU:"HUN",IS:"ISL",IN:"IND",ID:"IDN",IR:"IRN",IQ:"IRQ",IE:"IRL",IL:"ISR",IT:"ITA",JM:"JAM",
JP:"JPN",JO:"JOR",KZ:"KAZ",KE:"KEN",KI:"KIR",KP:"PRK",KR:"KOR",KW:"KWT",KG:"KGZ",LA:"LAO",LV:"LVA",LB:"LBN",LS:"LSO",LR:"LBR",LY:"LBY",LI:"LIE",LT:"LTU",LU:"LUX",MO:"MAC",MK:"MKD",MG:"MDG",MW:"MWI",MY:"MYS",MV:"MDV",ML:"MLI",MT:"MLT",MH:"MHL",MQ:"MTQ",MR:"MRT",MU:"MUS",YT:"MYT",MX:"MEX",FM:"FSM",MD:"MDA",MC:"MCO",MN:"MNG",MS:"MSR",MA:"MAR",MZ:"MOZ",MM:"MMR",NA:"NAM",NR:"NRU",NP:"NPL",NL:"NLD",AN:"ANT",NC:"NCL",NZ:"NZL",NI:"NIC",NE:"NER",NG:"NGA",NU:"NIU",NF:"NFK",MP:"MNP",NO:"NOR",OM:"OMN",PK:"PAK",
PW:"PLW",PS:"PSE",PA:"PAN",PG:"PNG",PY:"PRY",PE:"PER",PH:"PHL",PN:"PCN",PL:"POL",PT:"PRT",PR:"PRI",QA:"QAT",RE:"REU",RO:"ROU",RU:"RUS",RW:"RWA",SH:"SHN",KN:"KNA",LC:"LCA",PM:"SPM",VC:"VCT",WS:"WSM",SM:"SMR",ST:"STP",SA:"SAU",SN:"SEN",CS:"SCG",SC:"SYC",SL:"SLE",SG:"SGP",SK:"SVK",SI:"SVN",SB:"SLB",SO:"SOM",ZA:"ZAF",GS:"SGS",ES:"ESP",LK:"LKA",SD:"SDN",SR:"SUR",SJ:"SJM",SZ:"SWZ",SE:"SWE",CH:"CHE",SY:"SYR",TW:"TWN",TJ:"TJK",TZ:"TZA",TH:"THA",TL:"TLS",TG:"TGO",TK:"TKL",TO:"TON",TT:"TTO",TN:"TUN",TR:"TUR",
TM:"TKM",TC:"TCA",TV:"TUV",UG:"UGA",UA:"UKR",AE:"ARE",GB:"GBR",US:"USA",UM:"UMI",UY:"URY",UZ:"UZB",VU:"VUT",VA:"VAT",VE:"VEN",VN:"VNM",VG:"VGB",VI:"VIR",WF:"WLF",EH:"ESH",YE:"YEM",ZM:"ZMB",ZW:"ZWE"},a.ssdcat="310",a.helpid="&helpid=webisolation",a.helpid_url_markup="&helpid=suspiciouslink",a.helpid_online_banking="&helpid=onlinebanking",a.leave_feedback_link="https://feedback.norton.com/pfb/pFeedback.aspx?products=webisolation",a.leave_feedback_link_OB="https://feedback.norton.com/pfb/pFeedback_form.aspx?products=onlinebanking",
a.feature_type={invalid:0,link_guard:1,block_page:2,online_banking:3},a.kill_location="https://branding.symantec.com/upgrade/WEBISOLATION/KFG22.txt",a.kill_location_LG="https://branding.symantec.com/upgrade/WEBISOLATION/KLG22.txt",a.kill_location_BP="https://branding.symantec.com/upgrade/WEBISOLATION/KBP22.txt",a.kill_location_OB="https://branding.symantec.com/upgrade/WEBISOLATION/KOB22.txt",a.feature_ui_configs_location="https://branding.symantec.com/upgrade/WEBISOLATION/feature_ui_configs.json",
a.config_json_timeout=1E3,a.config_json_interval=288E5,Object.freeze(a))}(this);(function(c){"use esversion 6";var a,b,e,f,r,h;(c.FG=c.FG||{}).telemetry=(a=c.SymBfw,b=c.FG,e=a.utils.isNil,f=a.telemetryConstants,a.logger,r=b.config,h={TELEMETRY_CATEGORY:{FIREGLASS:"Fireglass",ONLINE_BANKING:"OnlineBanking"},ACTION_TYPE:{RATINGS_QUERY:"RatingsQuery",RATINGS_QUERY_BAD:"RatingsQueryBad",RATINGS_QUERY_BAD_PRESIGNIN:"RatingsQueryBadPresignin",RATINGS_QUERY_SCANNED:"RatingsQueryScanned",ISOLATION_LAUNCH:"IsolationLaunch",
TAB_ACTIVITY:"TabActivity",GENERIC:"Generic",INTERSTITIAL_DIALOG_DISPLAYED:"IDDisplayed",INTERSTITIAL_DIALOG_DISPLAYED_SIGNIN:"IDDisplayedSignin",INTERSTITIAL_DIALOG_DISPLAYED_CONTINUE:"IDDisplayedContinue",INTERSTITIAL_DIALOG_DISPLAYED_CONTINUE_NO_ISOLATION:"IDDisplayedContinueNoIsolation",INTERSTITIAL_DIALOG_DISPLAYED_CLOSED:"IDDisplayedClosed",INTERSTITIAL_DIALOG_DISPLAYED_LEARN_MORE_CLICKED:"IDDisplayedLearnMoreClicked",INTERSTITIAL_DIALOG_DISPLAYED_FROM_BLOCKPAGE:"IDBPDisplayed",INTERSTITIAL_DIALOG_DISPLAYED_FROM_BLOCKPAGE_SIGNIN:"IDBPDisplayedSignin",
INTERSTITIAL_DIALOG_DISPLAYED_FROM_BLOCKPAGE_CONTINUE:"IDBPDisplayedContinue",INTERSTITIAL_DIALOG_DISPLAYED_FROM_BLOCKPAGE_NO_ISOLATION:"IDBPDisplayedContinueNoIsolation",INTERSTITIAL_DIALOG_DISPLAYED_FROM_BLOCKPAGE_CLOSED:"IDBPDisplayedClosed",INTERSTITIAL_DIALOG_DISPLAYED_FROM_BLOCKPAGE_LEARN_MORE_CLICKED:"IDBPDisplayedLearnMoreClicked",OBTAIN_URL_RATINGS:"ObtainURLRatings",OBTAIN_URL_RATING:"ObtainURLRating",OBTAIN_URL_RATING_CACHE_HIT:"ObtainURLRatingCacheHit",PAGE_SCANNED:"PageScanned",TRY_FEATURE_DOCK_SHOWN:"TryThisFeatureDockShown",
TRY_FEATURE_DOCK:"TryThisFeature",SIGN_IN_FLOW_DISPLAYED:"SigninFlowDisplayed",SIGN_IN_FLOW_COMPLETED:"SigninFlowCompleted",LEARN_MORE_CLICKED_DOCK:"LearnMoreDock",SECURITY_POPUP_DISPLAYED:"SecurityPopupDisplayed",BAD_LINK_CLICKED:"BadLinkClicked",BAD_LINK_CLICKED_PRESIGNIN:"BadLinkClickedPresignin",INTERSTITIAL_DIALOG_DISPLAYED_REMEMBER_SITE_SPECIFIC:"IDRememberSiteSpecific",INTERSTITIAL_DIALOG_DISPLAYED_REMEMBER_GLOBAL:"IDRememberGlobal",AUTO_ISOLATE:"AutoIsolate",MARKUP_NOTIFICATION_SHOWN:"MarkupNotificationShown",
ISOLATION_SESSION_DURATION:"IsolationSessionDuration",USER_VISITED_BANKING_SITE:"UserVisitedBankingSite",USER_VISITED_WEBMAIL_SITE:"UserVisitedWebmailSite",USER_VISITED_SOCIAL_MEDIA_SITE:"UserVisitedSocialMediaSite",FEATURE_TURNED_OFF:"FeatureTurnedOff",FEATURE_DISABLED:"FeatureDisabled",DOCK_X_BUTTON_CLICKED:"DockXButtonClicked"},pingActionEx:function(a,b){try{var d={};d[f.parameters.CATEGORY]=a;d[f.parameters.ACTION]=b;h.send(d)}catch(l){}},pingActionValueEx:function(a,b,d){try{var l={};l[f.parameters.CATEGORY]=
a;l[f.parameters.ACTION]=b;l.ev=d;h.send(l)}catch(u){}},pingActionLabelEx:function(a,b,d){try{var l={};l[f.parameters.CATEGORY]=a;l[f.parameters.ACTION]=b;l[f.parameters.LABEL]=d;h.send(l)}catch(u){}},pingAction:function(a){try{h.pingActionEx(h.TELEMETRY_CATEGORY.FIREGLASS,a)}catch(p){}},pingActionValue:function(a,b){try{h.pingActionValueEx(h.TELEMETRY_CATEGORY.FIREGLASS,a,b)}catch(d){}},pingActionLabel:function(a,b){try{h.pingActionLabelEx(h.TELEMETRY_CATEGORY.FIREGLASS,a,b)}catch(d){}},pingActionOB:function(a){try{h.pingActionEx(h.TELEMETRY_CATEGORY.ONLINE_BANKING,
a)}catch(p){}},pingActionValueOB:function(a,b){try{h.pingActionValueEx(h.TELEMETRY_CATEGORY.ONLINE_BANKING,a,b)}catch(d){}},pingActionLabelOB:function(a,b){try{h.pingActionLabelEx(h.TELEMETRY_CATEGORY.ONLINE_BANKING,a,b)}catch(d){}},pingRatingsQuery:function(a){var b=a.origin,d=a.scanned,l=a.bad;a=a.unknown;var g=r.telemetry.ping.RatingsQuery,e={};e[f.parameters.CATEGORY]=h.TELEMETRY_CATEGORY.FIREGLASS;e[f.parameters.ACTION]=h.ACTION_TYPE.RATINGS_QUERY;e[g.TOP_URL]=b;e[g.SCANNED_URLS]=d;e[g.BAD_URLS]=
l;e[g.UNKNOWN_URLS]=a;h.pingActionValue(h.ACTION_TYPE.RATINGS_QUERY_BAD,l);h.pingActionValue(h.ACTION_TYPE.RATINGS_QUERY_SCANNED,d);h.send(e)},pingIsolationLaunch:function(a){var b=a.origin,d=a.url;a=a.optOut;var l=r.telemetry.ping.IsolationLaunch,e={};e[f.parameters.CATEGORY]=h.TELEMETRY_CATEGORY.FIREGLASS;e[f.parameters.ACTION]=h.ACTION_TYPE.ISOLATION_LAUNCH;e[l.TOP_URL]=b;e[l.ISOLATION_URL]=d;e[l.OPT_OUT]=a||!1;h.send(e)},pingTabActivity:function(a){var b=a.url,d=a.useTime,l=a.navigationComplete,
e=a.clickCount,g=a.keyCount;a=a.idleTime;var k=r.telemetry.ping.IsolationUsage,m={};m[f.parameters.CATEGORY]=h.TELEMETRY_CATEGORY.FIREGLASS;m[f.parameters.ACTION]=h.ACTION_TYPE.TAB_ACTIVITY;m[k.URL]=b;m[k.USE_TIME]=d;m[k.NAVIGATION_COMPLETE]=l;m[k.CLICK_COUNT]=e;m[k.KEY_COUNT]=g;m[k.IDLE_TIME]=a;h.send(m)},sendGenericPing:function(a){a[f.parameters.CATEGORY]=h.TELEMETRY_CATEGORY.FIREGLASS;a[f.parameters.ACTION]=h.ACTION_TYPE.GENERIC;h.send(a)},send:function(a){var b=this._getBfwTelemetry(),d;for(d in a[f.parameters.HIT_TYPE]=
f.HIT_TYPE.EVENT,a)e(a[d])&&delete a[d];b.send(a)},_getBfwTelemetry:function(){return a.telemetry||a.telemetryProxy}})})(this);(function(c){(c.FG=c.FG||{}).content=function(a,b){function e(a){b.helpers.get_cache(function(e){f(e)&&(b.parser.update_urls_scanned(e.urls_scanned),b.parser.update_urls_rewritten(e.urls_rewritten,!0));b.helpers.is_logged_in(function(e){b.helpers.split_array_to_chunks(b.parser.get_urls(a,!e),b.config.max_urls_per_request).forEach(function(a){b.helpers.get_ratings(a,function(a){f(a)&&
(b.parser.update_urls_rewritten(a),(a=Object.keys(a).length)&&(b.telemetry.pingActionValue(b.telemetry.ACTION_TYPE.RATINGS_QUERY_BAD,a),b.helpers.showOneTimeScanNotification(),e||b.telemetry.pingActionValue(b.telemetry.ACTION_TYPE.RATINGS_QUERY_BAD_PRESIGNIN,a)))})})})})}var f=a.utils.isntNil,c=(a.logger,{});return c.page_process_timer_dom=null,c.page_process_timer_click=null,c.active=!1,c.init_page=function(a){try{c.active||(c.active=!0,b.helpers.inject_ui_elements(),b.dom_observer.start(document.body,
function(){c.page_process_timer_dom=b.helpers.reset_timer(c.page_process_timer_dom,b.config.page_process_timeout,function(){e(a)})}),document.addEventListener("click",function(){c.page_process_timer_click=b.helpers.reset_timer(c.page_process_timer_click,b.config.page_process_timeout,function(){e(a)})}))}catch(g){}},c.uninit_page=function(){c.active&&(c.active=!1,b.dom_observer.stop(),b.helpers.clear_timer(b.config.page_process_timer))},c.init_page_online_banking=function(e){try{if(!c.active_banking&&
a.utils.isTopLevelWindow()){var f={new_tab:!(c.active_banking=!0),isolate:!0,risk_only:!1,defer:!0};b.helpers.get_skip_session(!1,function(a,d){d||b.helpers.get_settings_online_banking(!1,function(a,d){b.helpers.is_logged_in(function(a){var k=!1,m=!1;if(d&&a?m=!0:k=!0,k&&b.helpers.get_use_modal_setting(!1,function(k,m){b.helpers.can_prompt_onlinebanking(e,function(k){b.helpers.get_dock_show_always(!1,function(l,c){if(!m&&(d&&!a||c)&&(k=!0),k)l=m?b.helpers.show_online_banking_isolation_dialog:b.helpers.show_online_banking_dock,
b.telemetry.pingActionOB(b.telemetry.ACTION_TYPE.TRY_FEATURE_DOCK_SHOWN),l(e,function(k){k&&(a?(b.helpers.set_settings_online_banking(!0),b.helpers.update_online_banking_nag_counts()):b.helpers.set_settings_sigin_flow_origin(b.config.feature_type.online_banking),b.telemetry.pingActionOB(b.telemetry.ACTION_TYPE.TRY_FEATURE_DOCK),b.helpers.launch_url_with_callback(e,function(a){},f))},{rememberSite:!1})})})}),m)return b.helpers.check_rate_limit_onlinebanking(function(a){a&&b.helpers.launch_url_with_callback(e,
function(a){},f)}),void b.telemetry.pingActionOB(b.telemetry.ACTION_TYPE.AUTO_ISOLATE)})})})}}catch(p){}},c.uninit_page_online_banking=function(){c.active_banking&&(c.active_banking=!1)},window.addEventListener("beforeunload",function(a){c.uninit_page()}),a.extensionAdapter.addMessageListener(function(a,e,c){if(f(a.type)&&b.message_handler_content.hasOwnProperty(a.type))return b.message_handler_content[a.type](a,e,c)}),c}(c.SymBfw,c.FG)})(this);(function(c){var a,b,e;(c.FG=c.FG||{}).dom_observer=
(a=c.SymBfw,b=a.utils.isNil,e={config:{attributes:!1,childList:!0,characterData:!1,subtree:!0},start:function(a,c){try{b(a)||(e.observer=new MutationObserver(function(a){c()}),e.observer.observe(a,e.config))}catch(h){}},stop:function(){try{e.observer.disconnect()}catch(f){}}})})(this);(function(c){var a,b,e,f,r,h,g,p,d;(c.FG=c.FG||{}).parser=(a=c.SymBfw,b=c.FG,f="href codebase cite background action longdesc src profile usemap classid data formaction icon manifest poster".split(" "),r=["download"],
h=/^.*\.(JPG|JPEG|MP4|GIF|PNG|CSS|JS|XML|ICO|JSON|SVG|PDF|JPG:THUMB|PNG:THUMB)$/i,g=/^.*\.(JPG\?|JPEG\?|MP4\?|GIF\?|PNG\?|CSS\?|JS\?|XML\?|ICO\?|JSON\?|SVG\?|PDF\?|JPG:THUMB\?|PNG:THUMB\?)/i,p=/^.*(FBCDN.NET|TWIMG.COM|GOOGLEUSERCONTENT.COM|GOOGLE.COM|MESSENGER.COM|GSTATIC.COM|YOUTUBE.COM|BLOGGER.COM|FACEBOOK.COM|MSN.COM|YAHOO.COM|TWITTER.COM)$/i,d=/^.*(T.CO)$/i,(e={}).tld="",e.wrs_enabled=!1,e.get_domain=function(b){try{if(!a.utils.isString(b))return null;var d=b.toLowerCase(),l=URI.parse(b);a.utils.isntNil(l.hostname)&&
(d=l.hostname.toLowerCase());for(d=d.replace(/^www\./gi,"");0<d.length;){var k=d.indexOf(".");if(0>k||k>=d.length-4)break;d=d.substr(k+1)}return d}catch(m){}return null},e.validate_url=function(b){try{if(a.utils.isNil(URI))return!1;var l=URI.parse(b);if(a.utils.isNil(l.protocol)||"HTTP"!==l.protocol.toUpperCase()&&"HTTPS"!==l.protocol.toUpperCase())return!1;var c=b.match(h);if(a.utils.isntNil(c))return!1;var k=b.match(g);if(a.utils.isntNil(k))return!1;var m=e.get_domain(b);if(a.utils.isntNil(m)){if(a.utils.isntNil(e.tld)&&
m===e.tld)return!1;var v=m.match(p);if(a.utils.isntNil(v))return!1;if(e.wrs_enabled){var f=m.match(d);if(a.utils.isntNil(f))return!1}}}catch(y){return!1}return!0},e.get_urls=function(b,d){var l={};e.tld=e.get_domain(b);e.wrs_enabled=d;try{f.forEach(function(b){var k=document.querySelectorAll("["+b+"]:not([fg_scanned])");if(a.utils.isntNil(k)&&k.length)for(var d=0;d<k.length;d++){for(var c=!1,f=0;f<r.length;f++)if(k[d].hasAttribute(r[f])){c=!0;break}c||(c=k[d].getAttribute(b),e.validate_url(c)&&(l[c]=
!0,k[d].setAttribute("fg_scanned","1")))}})}catch(k){}return Object.keys(l)},e.update_urls_scanned=function(b){try{f.forEach(function(d){var c=document.querySelectorAll("["+d+"]:not([fg_scanned])");if(a.utils.isntNil(c)&&c.length)for(var k=0;k<c.length;k++){var m=c[k].getAttribute(d);a.utils.isntNil(m)&&b.hasOwnProperty(m)&&c[k].setAttribute("fg_scanned","1")}})}catch(u){}},e.update_urls_rewritten=function(d,c){d===Object(d)&&f.forEach(function(c){var k=document.querySelectorAll("["+c+"]:not([fg_rewritten])");
if(a.utils.isntNil(k)&&k.length)for(var m=function(){var m=k[e],l=m.getAttribute(c);a.utils.isntNil(l)&&d.hasOwnProperty(l)&&(m.setAttribute("fg_rewritten","1"),m.addEventListener("click",function(a){return a.preventDefault(),b.telemetry.pingAction(b.telemetry.ACTION_TYPE.BAD_LINK_CLICKED),b.helpers.is_logged_in(function(a){a||b.telemetry.pingActionValue(b.telemetry.ACTION_TYPE.BAD_LINK_CLICKED_PRESIGNIN)}),b.helpers.show_safe_mode_modal(!0,l),!1}),m.addEventListener("mouseenter",function(a){b.helpers.show_security_popup(!0,
a.clientX,a.clientY)}),m.addEventListener("mouseleave",function(a){b.helpers.show_security_popup(!1,0,0)}))},e=0;e<k.length;e++)m()})},e)})(this);(function(c){var a,b,e,f,r,h,g,p,d,l,u,n;(c.FG=c.FG||{}).helpers=(a=c.SymBfw,b=c.FG,e=a.utils.isntNil,f=a.utils.isNil,r=a.utils.isString,h=a.utils.isFunction,g=a.extensionAdapter,a.logger,p=b.config,l=function(a,d){return d.dialog.type===b.config.safeModeDialog.dialogType.threatIsolation?(b.helpers.launch_help_link(b.config.helpid),b.telemetry.pingAction(b.telemetry.ACTION_TYPE.INTERSTITIAL_DIALOG_DISPLAYED_LEARN_MORE_CLICKED)):
(b.helpers.launch_help_link(b.config.helpid_online_banking),b.telemetry.pingActionOB(b.telemetry.ACTION_TYPE.INTERSTITIAL_DIALOG_DISPLAYED_LEARN_MORE_CLICKED)),1},u=function(a,d){return d.dialog.type===b.config.safeModeDialog.dialogType.threatIsolation?b.helpers.launch_url(b.config.leave_feedback_link):b.helpers.launch_url(b.config.leave_feedback_link_OB),1},n=function(a,d){return d.dialog.type===b.config.safeModeDialog.dialogType.threatIsolation?b.telemetry.pingAction(b.telemetry.ACTION_TYPE.INTERSTITIAL_DIALOG_DISPLAYED_CLOSED):
b.telemetry.pingActionOB(b.telemetry.ACTION_TYPE.INTERSTITIAL_DIALOG_DISPLAYED_CLOSED),0},(d={add_dock_timer:null,add_ui_elements_timer:null,dom_popup_security_warning:null,dom_fg_dock:null,dom_fg_doc_controls:null,check_dock_timer:null,dom_fg_bezel_top:null,dom_fg_bezel_left:null,dom_fg_bezel_right:null,dom_fg_bezel_bottom:null,dock_loaded:!1,dockcontrol_loaded:!1,page_scan_notification_displayed:!1,tab_id:0,set_tab_id:function(a){d.tab_id=a},split_array_to_chunks:function(a,b){for(var k=[],d=0,
m=a.length;d<m;)k.push(a.slice(d,d+=b));return k},set_cache:function(a,b){g.sendMessage({type:"fg_set_cache",data:{urls_scanned:a,urls_rewritten:b}},function(a){})},get_cache:function(a){g.sendMessage({type:"fg_get_cache"},function(b){a(b)})},is_feature_killed:function(a,b){g.sendMessage({type:"fg_is_feature_killed",feature_type:b},function(b){a(b)})},get_settings:function(a,b,d){g.sendMessage({type:"fg_get_settings",settings_key:a,settings_defv:b},function(a){e(d)&&d(a.success,a.value)})},set_settings:function(a,
b,d){g.sendMessage({type:"fg_set_settings",settings_key:a,settings_value:b},function(a){h(d)&&d(a.success)})},set_settings_url_markup:function(a){d.set_settings(b.config.settings_key.url_markup,a)},get_settings_url_markup:function(a,c){d.get_settings(b.config.settings_key.url_markup,a,c)},set_settings_online_banking:function(a){d.set_settings(b.config.settings_key.online_banking,a)},get_settings_online_banking:function(a,c){d.get_settings(b.config.settings_key.online_banking,a,c)},set_settings_sigin_flow_origin:function(a){d.set_settings(b.config.settings_key.sign_in_flow_origin,
a)},get_skip_session_settings_key:function(){return String(b.config.settings_key.online_banking_session_override+"_"+d.tab_id)},set_skip_session:function(a){d.set_settings(d.get_skip_session_settings_key(),a)},get_skip_session:function(a,b){d.get_settings(d.get_skip_session_settings_key(),a,b)},set_dock_timeout:function(a){d.set_settings(b.config.settings_key.dock_timeout,a)},get_dock_timeout:function(a,c){d.get_settings(b.config.settings_key.dock_timeout,a,c)},get_use_modal_setting:function(a,c){d.get_settings(b.config.settings_key.use_modal,
a,c)},get_dock_start_minmized:function(a,c){d.get_settings(b.config.settings_key.dock_start_minimized,a,c)},get_dock_show_always:function(a,c){d.get_settings(b.config.settings_key.dock_show_always,a,c)},update_online_banking_nag_counts:function(){g.sendMessage({type:"fg_update_online_banking_nag_counts"},function(a){})},check_rate_limit_onlinebanking:function(a){g.sendMessage({type:"fg_check_rate_limit_onlinebanking"},function(b){a(b)})},get_ratings:function(a,b){g.sendMessage({type:"fg_get_ratings",
data:{urls_scanned:a}},function(a){b(a)})},get_rating:function(a,b){g.sendMessage({type:"fg_get_rating",data:{urls_scanned:a}},function(a){b(a)})},get_localized_strings:function(a,b){g.sendMessage({type:"fg_get_strings",ui_type:a},function(a){b(a)})},launch_url:function(a){d.launch_url_with_callback(a,function(a){},{isolate:1<arguments.length&&void 0!==arguments[1]&&arguments[1],defer:2<arguments.length&&void 0!==arguments[2]&&arguments[2]})},launch_url_with_callback:function(a,b,d){var k=d.new_tab,
c=d.isolate,e=d.defer;d=d.risk_only;g.sendMessage({type:"fg_launch_url",url:a,new_tab:void 0===k||k,isolate:void 0!==c&&c,defer:void 0!==e&&e,risk_only:void 0!==d&&d},function(a){b(a)})},open_site_redirector:function(a,b){g.sendMessage({type:"fg_open_site_redir",ssdcat:a,ssdhelpid:b},function(a){})},is_logged_in:function(a){g.sendMessage({type:"fg_is_loggedin"},function(b){a(b)})},log_out:function(a){g.sendMessage({type:"fg_signout_na"},function(a){})},launch_help_link:function(a){d.open_site_redirector(b.config.ssdcat,
a)},clear_timer:function(a){a&&window.clearTimeout(a)},reset_timer:function(a,b,c){var k=null;try{d.clear_timer(a),k=window.setTimeout(function(){c()},b)}catch(y){}return k},post_message_to_iframe:function(a,d){try{e(a)&&e(d)&&setTimeout(function(){var b=g.getExtensionURL("");d.origin=b;a.contentWindow.postMessage(d,b)},b.config.iframe_post_timeout)}catch(v){}},inject_iframe:function(a,b,d){if(e(a)&&e(b)){var c=document.createElement("iframe");c.id=a;c.frameBorder="0";c.src=b;c.style.display="none";
h(d)&&(c.onload=function(){d()});document.body.appendChild(c)}},set_text:function(a,b,d){e(b)&&e(d)&&e(a)&&(a=a.getElementById(b),e(a)&&(a.innerHTML=d))},inject_dock:function(c){try{!a.utils.isTopLevelWindow()||e(d.dom_fg_dock)&&document.body.contains(d.dom_fg_dock)||(a.utils.isNil(d.check_dock_timer)&&(d.check_dock_timer=window.setInterval(function(){d.inject_dock(c)},1E3)),d.add_dock_timer=d.reset_timer(d.add_dock_timer,b.config.add_dock_timeout,function(){switch(c){case p.dockConfig.trigger.prompt:break;
default:d.inject_bezel()}d.inject_banner(c)}))}catch(m){}},startIsolationTabMonitor:function(){0!=a.utils.isTopLevelWindow()&&(d.startTime=window.performance.now(),window.addEventListener("beforeunload",function(a){a=Math.round((window.performance.now()-d.startTime)/1E3);b.telemetry.pingActionValueOB(b.telemetry.ACTION_TYPE.ISOLATION_SESSION_DURATION,a)}))},inject_bezel:function(){try{var a=0,c=window.setInterval(function(){a>b.config.add_dock_max_timeout&&(window.clearInterval(c),c=0);var e=d.get_session_storage();
if(!f(e)&&e.urlCategory===b.config.dockConfig.urlCategory.onlineBanking&&e.sslStatus===b.config.dockConfig.sslStatus.secure){a+=b.config.add_dock_interval;e=document.getElementById("fgdock_iframe_top");var k=document.getElementById("fgdock_iframe_left"),l=document.getElementById("fgdock_iframe_right"),m=document.getElementById("fgdock_iframe_bottom");if(f(m)||f(k)||f(l)||f(e))return f(m)&&d.inject_iframe("fgdock_iframe_bottom",g.getExtensionURL("content/ui/fireglass/fg_bezel.html")),f(e)&&d.inject_iframe("fgdock_iframe_top",
g.getExtensionURL("content/ui/fireglass/fg_bezel.html")),f(k)&&d.inject_iframe("fgdock_iframe_left",g.getExtensionURL("content/ui/fireglass/fg_bezel.html")),void(f(l)&&d.inject_iframe("fgdock_iframe_right",g.getExtensionURL("content/ui/fireglass/fg_bezel.html")));d.dom_fg_bezel_top=e;d.dom_fg_bezel_left=k;d.dom_fg_bezel_right=l;d.dom_fg_bezel_bottom=m;d.show_bezel(!0);c&&window.clearInterval(c)}},b.config.add_dock_interval)}catch(v){}},inject_banner:function(a){try{var c=0,l=window.setInterval(function(){c>
b.config.add_dock_max_timeout&&(window.clearInterval(l),l=0);c+=b.config.add_dock_interval;b.helpers.get_dock_start_minmized(p.dock_start_minimized,function(c,k){c=null;k=k?"collapsed":"expanded";if(a===p.dockConfig.trigger.prompt||(c=d.get_session_storage(),!f(c))){var m=document.getElementById("fgdock_iframe"),h=document.getElementById("fgdoccontrols_iframe");if(f(m)||f(h))return f(m)&&(d.dock_loaded=!1,d.inject_iframe("fgdock_iframe",g.getExtensionURL("content/ui/fireglass/fg_dock.html"),function(){d.dock_loaded=
!0})),e(c)&&c.urlCategory===b.config.dockConfig.urlCategory.onlineBanking&&d.startIsolationTabMonitor(),void(f(h)&&(d.dockcontrol_loaded=!1,d.inject_iframe("fgdoccontrols_iframe",g.getExtensionURL("content/ui/fireglass/fg_doc_controls.html"),function(){d.dockcontrol_loaded=!0})));!1!==d.dock_loaded&&!1!==d.dockcontrol_loaded&&(d.dom_fg_dock=m,d.dom_fg_doc_controls=h,d.post_message_to_iframe(d.dom_fg_dock,{sessionInfo:c,prompt:a===p.dockConfig.trigger.prompt}),d.post_message_to_iframe(d.dom_fg_doc_controls,
{session:c,state:k,msg_type:"fg_doc_init",ctrl_type:"dock_showhide"}),a===p.dockConfig.trigger.prompt&&m.setAttribute("mode","signin"),h.setAttribute("ctrl","dock_showhide"),h.setAttribute("state",k),m.setAttribute("state",k),h.setAttribute("class",k),m.setAttribute("class",k),d.show_dock(!0),l&&window.clearInterval(l))}})},b.config.add_dock_interval)}catch(x){}},get_session_storage:function(){try{if(e(sessionStorage)&&e(sessionStorage.getItem("fgMetaData"))){var a=JSON.parse(sessionStorage.getItem("fgMetaData")),
c={};return e(a)&&(e(a.UrlCategories)&&0<a.UrlCategories.length&&(a.UrlCategories[0].id==b.config.financial_category_id||a.UrlCategories[0].id==b.config.trading_category_id?c.urlCategory=b.config.dockConfig.urlCategory.onlineBanking:c.urlCategory=b.config.dockConfig.urlCategory.general),e(a.SslStatus)&&(JSON.parse(a.SslStatus).IsSecureConnection?c.sslStatus=b.config.dockConfig.sslStatus.secure:c.sslStatus=b.config.dockConfig.sslStatus.insecure),e(a.address)&&(c.address=a.address),c.tabid=d.tab_id),
0<Object.keys(c).length?c:null}return null}catch(v){}},inject_ui_elements:function(){try{d.add_ui_elements_timer=d.reset_timer(d.add_ui_elements_timer,b.config.add_ui_elements_timeout,function(){d.inject_security_popup()})}catch(k){}},doc_control_update_elements_state:function(a){for(var b in a){var d=document.getElementById(b);if(!f(d)){var c=a[b].attributes;if(!f(c)){for(var l in c)d.setAttribute(l,c[l]);c=a[b].styles;if(!f(c)){var k=c.add;if(e(k))for(var g in k)d.classList.add(k[g]);c=c.remove;
if(e(c))for(var h in c)d.classList.remove(c[h])}}}}},doc_control_message_proc:function(a,b,c){if(!(f(a)||f(a.id)||f(a.data)))switch(b=a.data,a.id){case p.docControls.EVENT_ID:if(f(b.elements))break;d.doc_control_update_elements_state(b.elements);break;case p.dockMouseEvent.EVENT_ID:if(f(b.evt_type))break;b.evt_type===p.dockMouseEvent.eventType.mouseEnter||b.evt_type===p.dockMouseEvent.eventType.mouseLeave?d.post_message_to_iframe(d.dom_fg_doc_controls,{msg_type:"fg_dock_mouse_evt",evt_type:b.evt_type}):
b.evt_type!==p.dockMouseEvent.eventType.click||f(b.id)||d._invokeDockEventHandler(b.id);break;case p.dockResourceEvent.EVENT_ID:f(b.evt_type)||d._onDockResourceEvt(b.evt_type)}},listen_to_doc_control_message:function(){!1!==a.utils.isTopLevelWindow()&&g.addMessageListener(d.doc_control_message_proc)},inject_security_popup:function(){try{var a=document.getElementById("fg_security_popup_iframe");f(a)&&(d.inject_iframe("fg_security_popup_iframe",g.getExtensionURL("content/ui/fireglass/fg_popup.html")),
d.dom_popup_security_warning=document.getElementById("fg_security_popup_iframe"))}catch(m){}},is_extension_url:function(a){return 0!=r(a)&&a.startsWith(g.getExtensionURL(""))}})._registerDockEvtHandlers=function(a){this._dockEventHandlers=a},d._clearDockEvtHandlers=function(){this._dockEventHandlers=null},d._invokeDockEventHandler=function(a){if(!f(this._dockEventHandlers)&&this._dockEventHandlers.hasOwnProperty(a)){var b=this._dockEventHandlers[a];if(h(b)){var d=0;try{d=b(a)}catch(x){}f(d)}}},d._removeDockElements=
function(){d._clearDockEvtHandlers();var a=document.getElementById("fgdock_iframe");e(a)&&(document.body.removeChild(a),d.dom_fg_dock=null,d.dock_loaded=!1);a=document.getElementById("fgdoccontrols_iframe");e(a)&&(document.body.removeChild(a),d.dom_fg_doc_controls=null,d.dockcontrol_loaded=!1)},d._onDockResourceEvt=function(a){if(!f(a))switch(a){case p.dockResourceEvent.eventType.unload:d.inject_dock()}},d.show_online_banking_dock=function(a,c){var e=null;try{e=URI.parse(a).hostname}catch(x){}f(e)?
c(!1):(d._registerDockEvtHandlers({fgdock_signin:function(a){return d.is_logged_in(function(a){}),c(!0),0},fgdock_close:function(e){return c(!1),d.is_logged_in(function(d){d?b.helpers.launch_url_with_callback(a,function(a){},{new_tab:!1,isolate:!1}):b.helpers._removeDockElements()}),0}}),d.inject_dock(p.dockConfig.trigger.prompt))},d.show_online_banking_isolation_dialog=function(a,c){var e=(2<arguments.length&&void 0!==arguments[2]?arguments[2]:{}).rememberSite,k=void 0!==e&&e;e=null;try{e=URI.parse(a).hostname}catch(z){}if(f(e))c(!1);
else{b.telemetry.pingActionOB(b.telemetry.ACTION_TYPE.INTERSTITIAL_DIALOG_DISPLAYED);e=function(a,d){switch(c(!1),a){case "default_close":case "default_cancel":return n(0,d);case "footer_link":b.telemetry.pingActionOB(b.telemetry.ACTION_TYPE.INTERSTITIAL_DIALOG_DISPLAYED_CONTINUE_NO_ISOLATION)}return 0};e={help_2:l,leavefeedback:u,footer_link:e,default_ok:function(a,e){return d.is_logged_in(function(a){!0===a?b.telemetry.pingActionOB(b.telemetry.ACTION_TYPE.INTERSTITIAL_DIALOG_DISPLAYED_CONTINUE):
b.telemetry.pingActionOB(b.telemetry.ACTION_TYPE.INTERSTITIAL_DIALOG_DISPLAYED_SIGNIN)}),c(!0),0},default_cancel:e,default_close:e,fg_check_01:function(a,d){return!0===d.element.value&&b.telemetry.pingActionOB(b.telemetry.ACTION_TYPE.INTERSTITIAL_DIALOG_DISPLAYED_REMEMBER_SITE_SPECIFIC),k=!0===d.element.value,1}};var g={};g.dialogType=p.safeModeDialog.dialogType.onlineBanking;g.dialogData={fg_check_01:{value:k}};d._show_safemode_dialog_internal(a,g,e,function(a){0==a&&c(!1)})}},d.show_safe_mode_modal=
function(a,c,e){if(b.telemetry.pingAction(b.telemetry.ACTION_TYPE.INTERSTITIAL_DIALOG_DISPLAYED),a){var f=new URL(location.href);a={help:l,leavefeedback:u,footer_link:function(a,e){d.launch_url(c,!1);b.telemetry.pingAction(b.telemetry.ACTION_TYPE.INTERSTITIAL_DIALOG_DISPLAYED_CONTINUE_NO_ISOLATION);b.telemetry.pingIsolationLaunch({origin:f.hostname,url:c,optOut:!0})},default_ok:function(a,e){d.launch_url(c,!0);b.telemetry.pingAction(b.telemetry.ACTION_TYPE.INTERSTITIAL_DIALOG_DISPLAYED_CONTINUE);
b.telemetry.pingIsolationLaunch({origin:f.hostname,url:c})},default_cancel:n,default_close:n};var k={};k.dialogType=p.safeModeDialog.dialogType.threatIsolation;d._show_safemode_dialog_internal(c,k,a,e)}else b.safeModeDialog.close()},d.nss_safe_mode_prompt=function(a,c){if(b.telemetry.pingAction(b.telemetry.ACTION_TYPE.INTERSTITIAL_DIALOG_DISPLAYED_FROM_BLOCKPAGE),0!=d.is_extension_url(window.location.href)){var e=function(a,d){b.telemetry.pingAction(b.telemetry.ACTION_TYPE.INTERSTITIAL_DIALOG_DISPLAYED_FROM_BLOCKPAGE_CLOSED)},
l={help:function(a,c){return b.telemetry.pingAction(b.telemetry.ACTION_TYPE.INTERSTITIAL_DIALOG_DISPLAYED_FROM_BLOCKPAGE_LEARN_MORE_CLICKED),d.launch_help_link(b.config.helpid),1},leavefeedback:u,footer_link:function(d,e){return b.telemetry.pingAction(b.telemetry.ACTION_TYPE.INTERSTITIAL_DIALOG_DISPLAYED_FROM_BLOCKPAGE_NO_ISOLATION),c(a)},default_ok:function(c,e){b.telemetry.pingAction(b.telemetry.ACTION_TYPE.INTERSTITIAL_DIALOG_DISPLAYED_FROM_BLOCKPAGE_CONTINUE);d.launch_url(a,!0);b.telemetry.pingIsolationLaunch({origin:origin.hostname,
url:a})},default_cancel:e,default_close:e},f={};f.dialogType=p.safeModeDialog.dialogType.threatIsolation;d.is_feature_killed(function(e){if(!0===e)return b.telemetry.pingAction(b.telemetry.ACTION_TYPE.FEATURE_DISABLED),void c(a);d._show_safemode_dialog_internal(a,f,l,function(b){0==b&&c(a)})},b.config.feature_type.block_page)}},d._show_safemode_dialog_internal=function(a,c,e,l){d.is_logged_in(function(a){c.dialogMode=a?p.safeModeDialog.dialogMode.interstitial:p.safeModeDialog.dialogMode.signin;b.safeModeDialog.displayModalDialog(c,
e,l)})},d.show_security_popup=function(a,b,c){d.dom_popup_security_warning.style.top=c+"px";d.dom_popup_security_warning.style.left=b+"px";d.dom_popup_security_warning.style.display=a?"block":"none"},d.show_dock=function(a){a=a?"block":"none";d.dom_fg_dock.style.display=a;d.dom_fg_doc_controls.style.display=a},d.show_bezel=function(a){a=a?"block":"none";e(d.dom_fg_bezel_top)&&(d.dom_fg_bezel_top.style.display=a,d.dom_fg_bezel_left.style.display=a,d.dom_fg_bezel_right.style.display=a,d.dom_fg_bezel_bottom.style.display=
a)},d.sendMessageToProxy=function(a,b){g.sendMessage({type:"fg_message_proxy",id:p.uiMessageProxy.EVENT_ID,realId:a,data:b})},d.sendMessageToProxyWithResponse=function(a,b,c){g.sendMessage({type:"fg_message_proxy",id:p.uiMessageProxy.EVENT_ID,realId:a,responseId:b,data:c})},d.showOneTimeScanNotification=function(){d.page_scan_notification_displayed||(d.page_scan_notification_displayed=!0,g.sendMessage({type:"fg_show_notification",notification_type:b.config.notifications.type.pageScanNotification,
notification_args:{}}))},d.can_prompt_onlinebanking=function(a,b){g.sendMessage({type:"fg_can_prompt_onlinebanking",domain:a},function(a){e(b)&&b(a)})},d.listen_to_doc_control_message(),d)})(this);(function(c){var a,b;(c.FG=c.FG||{}).message_handler_content=(c.SymBfw,a=c.FG,(b={}).telemetry_timer=window.setTimeout(function(){},3E3),b.fg_update_dock=function(b,c,r){a.helpers.set_tab_id(b.tabid);a.helpers.inject_dock();c()},b.fg_activate_scan=function(b,c,r){if(a.helpers.set_tab_id(b.tabid),b.enable)switch(b.category){case a.config.webmail_category_id:case a.config.social_networking_id:a.content.init_page(b.url);
break;case a.config.financial_category_id:a.content.init_page_online_banking(b.url)}else a.content.uninit_page(),a.content.uninit_page_online_banking();c()},b)})(this);(this.FG=this.FG||{}).safeModeDialog=function(c,a){var b=c.utils.isNil,e=c.utils.isntNil,f=c.utils.isFunction,n=(c.logger,c.extensionAdapter),h=a.config,g={_iframe:null,_curState:2,_initPromise:{}};g._initPromise.resolveProxy=function(a,b){this._resolve=a;this._reject=b};g._initPromise.resolve=function(a){this._resolve(a)};g._initPromise.reject=
function(a){this._reject(a)};g._initPromise.getPromise=function(){return this._promise};g._initPromise.setup=function(){var a=this;this._promise=new Promise(function(b,c){a.resolveProxy(b,c)})};g._initPromise.setup();g.getId=function(){return"fg_safemode_modal_iframe"};g.getViewName=function(){return"fg_safemode_modal.html"};g._prepareFrameContainer=function(){if(this._iframe)return!0;var a=this,b=n.getExtensionURL("/content/ui/fireglass/"+a.getViewName());a._iframe=document.createElement("iframe");
a._iframe.src=b;a._iframe.id=this.getId();a._iframe.frameBorder="0";a._iframe.style.display="none";a._iframe.style.position="fixed";a._iframe.style.top="0px";a._iframe.style.left="0px";a._iframe.style.right="0px";a._iframe.style.bottom="0px";a._iframe.style.height="100%";a._iframe.style.width="100%";a._iframe.style["z-index"]="99999";a._iframe.onload=function(){a._initPromise.resolve(!0)};document.body.appendChild(a._iframe)};g.isActive=function(){return 2!=this._curState};g._detachFrame=function(){b(this._iframe)||
(document.body.removeChild(this._iframe),this._iframe=null,this._initPromise.setup())};g._closeDialog=function(){return!(b(this._iframe)||(this._curState=2,this._detachFrame(),this._sendMessageToRendererProxy({type:1}),this._proxyId=null))};g._showDialog=function(a){return!b(this._iframe)&&(this._sendMessageToView({state:h.safeModeDialog.displayState.show,props:a}),this._iframe.style.display="block",this._curState=1,!0)};g._sendMessageToRendererProxy=function(c){e(this._proxyId)&&b(c.proxyId)&&(c.proxyId=
this._proxyId);a.helpers.sendMessageToProxy(h.dialogRendererProxy.EVENT_ID,c)};g._sendMessageToView=function(a){try{var b=n.getExtensionURL("");a.origin=b;this._iframe.contentWindow.postMessage(a,b)}catch(w){}};g._handleProxyMessage=function(a){var b=this;switch(a.type){case 0:this._initPromise.getPromise().then(function(c){c=!1;0==b.isActive()&&(c=!0,b._proxyId=a.proxyId,b._showDialog(a.dlgType));b._sendMessageToRendererProxy({proxyId:a.proxyId,type:0,success:c})},function(c){b._sendMessageToRendererProxy({proxyId:a.proxyId,
type:0,success:!1})});break;case 1:this._initPromise.getPromise().then(function(a){b._closeDialog()});break;case 3:this.init()}};g._handleViewMessage=function(a){switch(a.type){case "change":case "click":switch(a.type){case "click":var b=2;break;case "change":b=4;break;case "open":b=0;break;case "close":b=1;break;case "init":b=3;break;default:b=-1}this._sendMessageToRendererProxy({type:b,evtData:a});break;case "show":this._initPromise.resolve(!0)}};g._messageProc=function(a,c,d){b(a)||b(a.id)||a.id!=
h.dialogRenderer.EVENT_ID||(a=a.data,a.proxyId?g._handleProxyMessage(a,c):g._handleViewMessage(a,c))};g.listenToMessage=function(){if(0!=c.utils.isTopLevelWindow()&&!e(this._isListening)){var a=this;document.addEventListener("keyup",function(b){"Esc"!=b.key&&"Escape"!=b.key||a._initPromise.getPromise().then(function(b){a._closeDialog()})});this._isListening=!0;n.addMessageListener(g._messageProc)}};g.init=function(){0!=c.utils.isTopLevelWindow()&&(e(this._iframe)||this._prepareFrameContainer())};
g.listenToMessage();a.modalDialogRenderer=g;var p={_eventHandlers:null,_curState:2,_callback:null,_id:null,_clear:function(){this._callback=this._eventHandlers=null},_sendMessageToRenderer:function(b){b.proxyId=this._id;a.helpers.sendMessageToProxyWithResponse(h.dialogRenderer.EVENT_ID,h.dialogRendererProxy.EVENT_ID,b)},isActive:function(){return 2!=this._curState},showDialog:function(a,b,c){this.isActive()?f(c)&&c(!1):(this._curState=0,this._eventHandlers=b,this._callback=c,this._sendMessageToRenderer({type:0,
dlgType:a}))},closeDialog:function(a){this.isActive()?(this._callback=a,this._sendMessageToRenderer({type:1})):f(a)&&a(!1)},_invokeEventHandler:function(a,c){if(!b(this._eventHandlers)&&this._eventHandlers.hasOwnProperty(a)){var d=this._eventHandlers[a];if(f(d)){var e=0;try{e=d(a,c)}catch(m){}!b(e)&&e||this.closeDialog()}}},_messageProc:function(a,c,d){if(!b(a)&&!b(a.id)&&a.id==h.dialogRendererProxy.EVENT_ID&&(a=a.data,a.proxyId==p._id))switch(a.type){case 0:c=p._callback;p._callback=null;a.success?
p._curState=1:(p._curState=2,p._clear());f(c)&&c(a.success);break;case 4:case 2:a=a.evtData;p._invokeEventHandler(a.id,a.evtData);break;case 1:f(p._callback)&&p._callback(a.success),p._curState=2,p._clear()}},init:function(){b(this._id)&&(this._id=c.utils.createNewGuid(),n.addMessageListener(this._messageProc));this._sendMessageToRenderer({type:3})}},d={};return d._renderer=p,d.displayModalDialog=function(a,b,c){this.init();this._renderer.showDialog(a,b,c)},d.close=function(){this._renderer.closeDialog()},
d.init=function(){this._renderer.init()},d}(this.SymBfw,this.FG)}).apply(window)},{}]},{},[1]);
