var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,d,a){b!=Array.prototype&&b!=Object.prototype&&(b[d]=a.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(b,d,a,c){if(d){a=$jscomp.global;b=b.split(".");for(c=0;c<b.length-1;c++){var g=b[c];g in a||(a[g]={});a=a[g]}b=b[b.length-1];c=a[b];d=d(c);d!=c&&null!=d&&$jscomp.defineProperty(a,b,{configurable:!0,writable:!0,value:d})}};$jscomp.polyfill("Object.is",function(b){return b?b:function(b,a){return b===a?0!==b||1/b===1/a:b!==b&&a!==a}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(b){return b?b:function(b,a){var c=this;c instanceof String&&(c=String(c));var d=c.length;a=a||0;for(0>a&&(a=Math.max(a+d,0));a<d;a++){var f=c[a];if(f===b||Object.is(f,b))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(b,d,a){if(null==b)throw new TypeError("The 'this' value for String.prototype."+a+" must not be null or undefined");if(d instanceof RegExp)throw new TypeError("First argument to String.prototype."+a+" must not be a regular expression");return b+""};$jscomp.polyfill("String.prototype.includes",function(b){return b?b:function(b,a){return-1!==$jscomp.checkStringArgs(this,b,"includes").indexOf(b,a||0)}},"es6","es3");
$jscomp.polyfill("String.prototype.startsWith",function(b){return b?b:function(b,a){var c=$jscomp.checkStringArgs(this,b,"startsWith");b+="";var d=c.length,f=b.length;a=Math.max(0,Math.min(a|0,c.length));for(var e=0;e<f&&a<d;)if(c[a++]!=b[e++])return!1;return e>=f}},"es6","es3");var executionContext=this;
(function(b){var d=b.NSSS=b.NSSS||{},a={DEFAULT_HOMEPAGE:"defaultHomepage",DEFAULT_SEARCH:"defaultSearch",TABID:"tabID",TAB_OVERALLSTATUS:"tabstatus",DID_ONBOARDINGFLOW:"didOnBoardingFlow",SHOW_FULLREPORT:"showFullReport",SHOW_REPORTSITE:"showReportSite",NSSS_GLOBAL_SETTINGS_CONTAINER:"44CB4D75-FAD1-449D-9C9E-B0A3090B18B8",NSSS_INSTALLDATEKEY:"extensionInstalldate",BLOCKPAGE:"blockPage",CGUIDKEY:"cutomerGuid",PARAMSTRINGKEY:"paramstring",VENDORKEY:"vendor",DS_OCODE:"##DS_OCODE##",DHP_OCODE:"##DHP_OCODE##",
SEARCH_OCODE:"##SEARCH_OCODE##",BLOCKEDPAGE_SEARCH_OCODE:"##BLOCKEDPAGE_SEARCH_OCODE##",TPR:"##TPRVALUE##",PRT:"##PRTVALUE##",VERSION:"##VERSION##",PARTNERIDKEY:"chn",CAMPAIGN_MEDIUM:"campaignMedium",IS_FLAVORIZED:"flavorized",DEFAULT_PARTNER_ID:"store",PRODUCT_NAME:"Norton Safe Web",TELEMETRY_TRACKING_ID:"##TRACKING_ID##",BACKUP_HOMEPAGE:"backupHomePage"};a.PRODUCT_LABEL=b.SymBfw.extensionAdapter.getExtensionId()+"-"+a.VERSION;a.TELEMETRY_OPTOUT_URL="https://##TELEMETRY_OPTOUT_URI##.norton.com/xbp-tour";
a.TELEMETRY_OPTOUT_TIMEOUT="##TELEMETRYTIMEOUT##";a.DEFAULT_INFO_ICON="##DEFAULT_INFO_ICON##";a.IS_HP_FIRST_LAUNCH="isHPFirstLaunch";a.IS_DSP_FIRST_LAUNCH="isDSPFirstLaunch";a.HP_ID="ophopjonlomiomjdjphigoapegkicmih";a.MYWAY_SECURE_SEARCH_CHROME_EXTN_ID="aipacdclkmcnfkfoiebiokfemanllgag";a.MYWAY_IFRAME_HP_URL="https://hp.norton.myway.com/norton/";a.MYWAY_IFRAME_HP_URL_FF="https://ak.staticimgfarm.com/images/webtooltab/ttdetect-2/prd/ttdetect.html#https://hp.norton.myway.com";a.MYWAY_CHROME_EXTN_PAGE_URL=
"chrome-extension://"+a.MYWAY_SECURE_SEARCH_CHROME_EXTN_ID;a.CHROME_NEW_TAB_URL="chrome://newtab/";a.FIREFOX_EXTN_URL_START_KEYWORD="moz-extension://";a.FIREFOX_EXTN_NEW_DYNAMIC_TAB_HTML="dynamicNewTab.html";a.FIREFOX_EXTN_NEW_DYNAMIC_HOMEPAGE_HTML="dynamicHomePage.html";a.SHOULD_BLOCK_KEY="shouldBlock";a.CONTINUE_SITE_LOADED_KEY="blockedSiteLoaded";a.NORTONSAFE_HOSTNAME="##NORTONSAFE_HOSTNAME##";a.SAFE_WEB_EXTENSION="Norton Safe Web";a.SEARCHBOX_VISIBLE="##SEARCHBOX_VISIBLE##";a.NATIVE_TAB_PREFIX=
["chrome://","about:"];a.ABOUT_BLANK="about:blank";a.SETTINGS_PAGE="/content/ui/settings.html";a.BUTTON_GLOBAL_CHECKED="../images/btn-global-checked.svg";a.BUTTON_GLOBAL_UNCHECKED="../images/btn-global-unchecked.svg";a.DEFAULT_COUNTRY="US";a.CAUTION_IMAGE="##CAUTION_IMAGE##";a.WARNING_IMAGE="##WARNING_IMAGE##";a.UNTESTED_IMAGE="##UNTESTED_IMAGE##";a.SAFE_IMAGE="##SAFE_IMAGE##";a.RETINAL_UNTESTED_IMAGE="##RETINAL_UNTESTED_IMAGE##";a.RETINAL_SAFE_IMAGE="##RETINAL_SAFE_IMAGE##";a.SETTINGS_KEY_DS="defaultSearchEnabled";
a.HOME_PAGE_URL="https://search.norton.com/";a.SEARCH_URL="https://nortonsafe.search.ask.com/web";a.VENDOR="ask";a.STORE_URL_NAME="##STORE_URL_NAME##";a.ALLOW_SUSPICIOUS_BLOCK_LIST="allowSuspiciousBlockList";a.ALLOW_SUSPICIOUS_BLOCK_DURATION=18E5;a.MYWAY="myway";a.VENDOR_IS_PRESENT="vendorIsPresent";a.GET_INSTALL_DATE="getInstallDate";a.GET_ASSOCIATION_DATE="getAssociationDate";a.IAC="ask";a.YAHOO="yahoo";a.ACTUAL_HREF="actualhref";a.REPLACED_HREF="replacedhref";a.CLICK_PREVENTION_GUID="clickPreventionGUID";a.CLICK_PREVENTION_NODE_LIST=
"clickPreventionNodeList";a.URL_IDENTIFIER="urlIdentifier";a.subLinksURLIdentifiers="sublinksURLIdentifiers";a.FINAL_REDIRECTED_TAB_URL="finalRedirectedTabUrl";a.events={CLICK:"click",MOUSE_DOWN:"mousedown"};b={};var c={};a.HP={Chrome:(b[a.YAHOO]="embphknneakipabfiipdgklmpllaibmh",b[a.IAC]=null,b),Firefox:(c[a.YAHOO]="nortonhomepage_ven_y@symantec.com",c[a.IAC]=null,c)};b={};c={};a.DS={Chrome:(b[a.YAHOO]="mpnlkmlkncncpgnnkmkgoobfpnjmblnk",b[a.IAC]=null,b),Firefox:(c[a.YAHOO]="nortonsafesearch_ul_ven_y_2@symantec.com",
c[a.IAC]=null,c)};a.EXTENSION_PAIR_IDS={"Norton Safe Search":a.HP,"Norton Home Page":a.DS};a.CLICK_PREVENTION_MAP="clickPreventionMap";a.CLICK_PREVENTED_TAB="clickPreventedTab";a.PRIVACY_POLICY_SSDCAT=150;a.DEFAULT_ORIGIN_VALUE="nsss";a.NEWFEATURE_ORIGIN_VALUE="NewFeature";a.IPS_LEARN_MORE_SSDCAT=137;a.SITE_DIRECTOR_URL="http://sitedirector.symantec.com/932743328?ssdcat=SSDCAT_VALUE&env=prod&origin=ORIGIN&displang=iso3:ISO3_LAN_CODE&displocale=iso3:ISO3_COUNTRY_CODE";a.SITE_DIRECTOR_IPS_URL="http://sitedirector.symantec.com/932743328?ssdcat=SSDCAT_VALUE&env=prod&origin=ORIGIN&lang=LAN_CODE";
a.SITE_DIRECTOR_ADDITIONAL_PARAM="&layouttype=LAYOUT_TYPE&partnerid=PARTNERID&puid=PUID";a.ISPID="&ispid=55555";a.ISO2_ISO3_LANGUAGE={AB:"ABK",AA:"AAR",AF:"AFR",AK:"AKA",SQ:"SQI",AM:"AMH",AR:"ARA",AN:"ARG",HY:"HYE",AS:"ASM",AV:"AVA",AE:"AVE",AY:"AYM",AZ:"AZE",BM:"BAM",BA:"BAK",EU:"EUS",BE:"BEL",BN:"BEN",BH:"BIH",BI:"BIS",BS:"BOS",BR:"BRE",BG:"BUL",MY:"MYA",CA:"CAT",CH:"CHA",CE:"CHE",NY:"NYA",ZH:"ZHO",CV:"CHV",KW:"COR",CO:"COS",CR:"CRE",HR:"HRV",CS:"CES",DA:"DAN",DV:"DIV",NL:"NLD",DZ:"DZO",EN:"ENG",
EO:"EPO",ET:"EST",EE:"EWE",FO:"FAO",FJ:"FIJ",FI:"FIN",FR:"FRA",FF:"FUL",GL:"GLG",KA:"KAT",DE:"DEU",EL:"ELL",GN:"GRN",GU:"GUJ",HT:"HAT",HA:"HAU",HE:"HEB",HZ:"HER",HI:"HIN",HO:"HMO",HU:"HUN",IA:"INA",ID:"IND",IE:"ILE",GA:"GLE",IG:"IBO",IK:"IPK",IO:"IDO",IS:"ISL",IT:"ITA",IU:"IKU",JA:"JPN",JV:"JAV",KL:"KAL",KN:"KAN",KR:"KAU",KS:"KAS",KK:"KAZ",KM:"KHM",KI:"KIK",RW:"KIN",KY:"KIR",KV:"KOM",KG:"KON",KO:"KOR",KU:"KUR",KJ:"KUA",LA:"LAT",LB:"LTZ",LG:"LUG",LI:"LIM",LN:"LIN",LO:"LAO",LT:"LIT",LU:"LUB",LV:"LAV",
GV:"GLV",MK:"MKD",MG:"MLG",MS:"MSA",ML:"MAL",MT:"MLT",MI:"MRI",MR:"MAR",MH:"MAH",MN:"MON",NA:"NAU",NV:"NAV",ND:"NDE",NE:"NEP",NG:"NDO",NB:"NOB",NN:"NNO",NO:"NOR",II:"III",NR:"NBL",OC:"OCI",OJ:"OJI",CU:"CHU",OM:"ORM",OR:"ORI",OS:"OSS",PA:"PAN",PI:"PLI",FA:"FAS",PL:"POL",PS:"PUS",PT:"POR",QU:"QUE",RM:"ROH",RN:"RUN",RO:"RON",RU:"RUS",SA:"SAN",SC:"SRD",SD:"SND",SE:"SME",SM:"SMO",SG:"SAG",SR:"SRP",GD:"GLA",SN:"SNA",SI:"SIN",SK:"SLK",SL:"SLV",SO:"SOM",ST:"SOT",ES:"SPA",SU:"SUN",SW:"SWA",SS:"SSW",SV:"SWE",
TA:"TAM",TE:"TEL",TG:"TGK",TH:"THA",TI:"TIR",BO:"BOD",TK:"TUK",TL:"TGL",TN:"TSN",TO:"TON",TR:"TUR",TS:"TSO",TT:"TAT",TW:"TWI",TY:"TAH",UG:"UIG",UK:"UKR",UR:"URD",UZ:"UZB",VE:"VEN",VI:"VIE",VO:"VOL",WA:"WLN",CY:"CYM",WO:"WOL",FY:"FRY",XH:"XHO",YI:"YID",YO:"YOR",ZA:"ZHA",ZU:"ZUL"};a.FIREGLASS_SUPPORTED_LAYOUTS=["RETAIL","ESD"];a.ISO2_ISO3_COUNTRY={AX:"ALA",AF:"AFG",AL:"ALB",DZ:"DZA",AS:"ASM",AD:"AND",AO:"AGO",AI:"AIA",AQ:"ATA",AG:"ATG",AR:"ARG",AM:"ARM",AW:"ABW",AU:"AUS",AT:"AUT",AZ:"AZE",BS:"BHS",
BH:"BHR",BD:"BGD",BB:"BRB",BY:"BLR",BE:"BEL",BZ:"BLZ",BJ:"BEN",BM:"BMU",BT:"BTN",BO:"BOL",BA:"BIH",BW:"BWA",BV:"BVT",BR:"BRA",IO:"IOT",BN:"BRN",BG:"BGR",BF:"BFA",BI:"BDI",KH:"KHM",CM:"CMR",CA:"CAN",CV:"CPV",KY:"CYM",CF:"CAF",TD:"TCD",CL:"CHL",CN:"CHN",CX:"CXR",CC:"CCK",CO:"COL",KM:"COM",CD:"COD",CG:"COG",CK:"COK",CR:"CRI",CI:"CIV",HR:"HRV",CU:"CUB",CY:"CYP",CZ:"CZE",DK:"DNK",DJ:"DJI",DM:"DMA",DO:"DOM",EC:"ECU",EG:"EGY",SV:"SLV",GQ:"GNQ",ER:"ERI",EE:"EST",ET:"ETH",FK:"FLK",FO:"FRO",FJ:"FJI",FI:"FIN",
FR:"FRA",GF:"GUF",PF:"PYF",TF:"ATF",GA:"GAB",GM:"GMB",GE:"GEO",DE:"DEU",GH:"GHA",GI:"GIB",GR:"GRC",GL:"GRL",GD:"GRD",GP:"GLP",GU:"GUM",GT:"GTM",GN:"GIN",GW:"GNB",GY:"GUY",HT:"HTI",HM:"HMD",HN:"HND",HK:"HKG",HU:"HUN",IS:"ISL",IN:"IND",ID:"IDN",IR:"IRN",IQ:"IRQ",IE:"IRL",IL:"ISR",IT:"ITA",JM:"JAM",JP:"JPN",JO:"JOR",KZ:"KAZ",KE:"KEN",KI:"KIR",KP:"PRK",KR:"KOR",KW:"KWT",KG:"KGZ",LA:"LAO",LV:"LVA",LB:"LBN",LS:"LSO",LR:"LBR",LY:"LBY",LI:"LIE",LT:"LTU",LU:"LUX",MO:"MAC",MK:"MKD",MG:"MDG",MW:"MWI",MY:"MYS",
MV:"MDV",ML:"MLI",MT:"MLT",MH:"MHL",MQ:"MTQ",MR:"MRT",MU:"MUS",YT:"MYT",MX:"MEX",FM:"FSM",MD:"MDA",MC:"MCO",MN:"MNG",MS:"MSR",MA:"MAR",MZ:"MOZ",MM:"MMR",NA:"NAM",NR:"NRU",NP:"NPL",NL:"NLD",AN:"ANT",NC:"NCL",NZ:"NZL",NI:"NIC",NE:"NER",NG:"NGA",NU:"NIU",NF:"NFK",MP:"MNP",NO:"NOR",OM:"OMN",PK:"PAK",PW:"PLW",PS:"PSE",PA:"PAN",PG:"PNG",PY:"PRY",PE:"PER",PH:"PHL",PN:"PCN",PL:"POL",PT:"PRT",PR:"PRI",QA:"QAT",RE:"REU",RO:"ROU",RU:"RUS",RW:"RWA",SH:"SHN",KN:"KNA",LC:"LCA",PM:"SPM",VC:"VCT",WS:"WSM",SM:"SMR",
ST:"STP",SA:"SAU",SN:"SEN",CS:"SCG",SC:"SYC",SL:"SLE",SG:"SGP",SK:"SVK",SI:"SVN",SB:"SLB",SO:"SOM",ZA:"ZAF",GS:"SGS",ES:"ESP",LK:"LKA",SD:"SDN",SR:"SUR",SJ:"SJM",SZ:"SWZ",SE:"SWE",CH:"CHE",SY:"SYR",TW:"TWN",TJ:"TJK",TZ:"TZA",TH:"THA",TL:"TLS",TG:"TGO",TK:"TKL",TO:"TON",TT:"TTO",TN:"TUN",TR:"TUR",TM:"TKM",TC:"TCA",TV:"TUV",UG:"UGA",UA:"UKR",AE:"ARE",GB:"GBR",US:"USA",UM:"UMI",UY:"URY",UZ:"UZB",VU:"VUT",VA:"VAT",VE:"VEN",VN:"VNM",VG:"VGB",VI:"VIR",WF:"WLF",EH:"ESH",YE:"YEM",ZM:"ZMB",ZW:"ZWE"};a.ONBOARDING_URL=
"https://##IDSAFE_PORTAL_URL##.norton.com/";a.URL_PARAMS_KEY={PARTNERID:"partnerid",CGUID:"guid",DATE_OF_INSTALL:"doi",DATE_OF_ASSOCIATION:"doa",OCODE:"o",PRT:"prt",VERSION:"ver",TPR:"tpr",PARTNER_UNIT_ID:"puid",PRODUCT_NAME:"product",LAYOUT_TYPE:"layouttype",TRACK_ID:"trackId"};a.IS_SERP_CAMPAIGN_ENABLED=!0;a.SERP_SESSION={BLOCK_BY_SERP_CAMPAIGN:"blockedBySerp",OPENER_TAB_ID:"serpOpenerTabId"};a.SERP_CAMPAIGN_SUPPORTED_DOMAIN={"yahoo.com":"YAHOO","ask.com":"ASK"};a.YAHOO_DOMAIN_NAME="yahoo.com";
a.SERP_CAMPAIGN_PARAM={ASK:{CAMPAIGN_NAME:"cmpgn",CAMPAIGN_VALUE:"medici"},YAHOO:{CAMPAIGN_NAME:"type",CAMPAIGN_VALUE:"medici"}};a.SERP_RESULT_CLICKED="03d4787f-800c-486c-be47-bbf38fd426d8";a.SCAM_INGSIGHT="scam";a.ONBOARDING_PORTAL_DOMAIN_MAP={"norton.com":["identitysafe","search","searchsafe"],"myway.com":["secure.norton"]};a.telemetryOptOut={REOFFER_TIME_WINDOW:7776E6,NOTIFICATION_LEEWAY:3E5};a.IS_WCID_HEURISTICS_LOW_PRIORITY=!0;a.SCAM_INSIGHT_BLOCK_PAGE_PATH="content/ui/scam-insight-block-page.html";
a.BLOCK_PAGE_PATH="content/ui/blockedPage.html";a.webProtectionPolicy={WEB_PROTECTION_POLICY_CONTAINER:"62517E4C-BFAD-46DE-977B-1A388E5399C7",SAFEWEB_STATUS:"AEE8B6DB-FB95-46D2-9C21-B594440BDF91",WCID_HEURISTICS_STATUS:"B0E77D14-7B68-477E-981C-21EB2E65A7C9",WCID_CHECK_URL_STATUS:"4621C921-C4C1-4813-9F24-83FF7800471F",IPS_STATUS:"A81DABD1-935C-4504-91C8-90BC99EE4E29"};a.IPS={SITE_RATING:{IPS_STATE:16},RATING_TYPE:{IPS:"BBF78165-B712-4E8A-A720-02F3D6C07CC5"},SUPPORTED_BROWSERS:["Chrome","Firefox","Edge"]};
a.performanceReporter={NSSS:"NSSS"};a.scamInsightAgeRating={VERY_NEW:"verynew",NEW:"new"};a.scamInsightPrevalenceRating={NO_USERS:"nousers",FEW_USERS:"fewusers"};a.scamInsightScore={LOWER_LIMIT:25,UPPER_LIMIT:49};a.yahooVendorConstants={HSPART:"hspart",HSPART_VALUE:"symantec",HSIMP:"hsimp",HSIMP_VALUE:"yhs-ext_onb",HSIMP_VALUE_THREE_IN_ONE:"yhs-ext_safe"};a.WCID_ANALYSIS_WAIT_TIME=2E3;a.CHROME_STORE_URL="https://chrome.google.com/webstore/detail/";a.HEARTBEAT_CONFIG={HEARTBEAT_SDK_PING_INTERVAL:864E5,
DATA_SOURCE:"extension"};a.TIME={THIRTY_MINUTES:18E5};a.GEO_LOCATION_API_URL="https://cloudconnect2.norton.com/v1/geolocationapi/location/countryembargoinformation/";a.SAFARI_VENDOR_OFFERING={supportedCountry:["US","CA"]};a.FG_LEARN_MORE_SSDCAT="310";a.SSD_HELPID="&helpid=onlinebanking";d.constants=a})(this);
(function(b){(b.NSSS=b.NSSS||{}).uiConstants={MESSAGES:{BLOCKEDPAGE_SEARCH:"93D3C1B6-E181-48DA-8841-EB995ADC5D48",BLOCKEDPAGE_INIT:"049B762D-F8CB-4BB1-93AB-F9D55E13D65E",BEFORE_UNLOAD_EVENT:"6D54B993-F098-4C47-B4CC-596C3D22E402",DOMEVENT:"4BEBC3FD-7552-4AE9-9FB1-717AA14B650A",SHOW_ANNOTATION_POPUP:"9BBDD5C9-4BAF-44EC-9F29-67AD5E2CF524",CLOSE_ANNOATION_POPUP:"47420986-DBE5-471F-8D64-64DCEBDF8541",COLLECT_URL_RESPONSE:"0AD25128-5D2A-422C-88F8-3F50E8579C69",OPEN_FULLREPORT:"FAAABCAF-50C5-4EE5-B18B-4E4FA9425B70",
FLAVOR_RETRIEVED:"554E40BF-48A3-416D-8988-9661B90F94CC",OPEN_DO_NOT_BLOCK_PAGE:"54E66C14-3E30-4F16-B4BC-259C662FF64B",HANDLE_UI_EVENTS:"B2C77321-D8F4-47A8-DCCF-D99BE95F4BC9",UPDATE_POPOVER_UI:"642A1139-910F-4D9A-B15F-12BBB6AA6276",SCAM_INSIGHT_BLOCKPAGE_INIT:"de656873-852a-4c10-8698-be4040be18ff",SCAM_EXIT_SITE:"da5f0029-7869-41af-bfc6-cd5138f13c07",SCAM_CONTINUE_TO_SITE:"9e7cd3d3-759c-49f6-87ae-4c49180d6118",SCAM_REPORT_ISSUE:"97d7cc47-bfdd-480e-9d28-0d069d965283",SET_TELEMETRY_ENABLED:"6213A0CF-075B-42BB-861A-0E54D62DE44E",
SET_LINK_GUARD_ENABLED_NOTIFICATION:"F1E723C0-325B-4B40-8105-DE45FF866910",SETTINGS_PRIVACY_POLICY:"53E7B83C-CB55-463F-91B0-41F125589605",SIGN_OUT:"5CC02BA4-A79E-4451-B64A-B61217EC6B16",SETTINGS_PAGE_UI_INIT:"99534CCC-1303-4135-B98F-2B57FB3C2115",OPEN_IPS_LEARN_MORE_URL:"B63BF039-0BF2-4ED4-AD7F-61C482CF5E1D",UPDATE_FG_LINK_GUARD:"AC2A03CC-8755-48A8-9713-B37F8792056D",UPDATE_FG_VALUES:"96DD5DC7-E54C-4028-AA35-4E26C5EEED34",SET_DS_VENDOR:"051cc1e3-0abf-45de-97ea-318b8904104a",STORE_CLICK_PREVENTION_URL:"0F830272-E06E-4E97-BC06-4D2BD5DC8D9A",
RETRIEVE_CLICK_PREVENTION_URL:"9EAC3837-7ECF-4C03-9A74-D848ECD9012C",ADD_TO_CLICK_PREVENTION_SAFELIST:"7A4A8585-40B8-406C-B63B-3CD865C58584",UNDO_CLICK_PREVENTION:"2E9E571E-93AA-468E-AC40-B451BE79B1C5",REDO_CLICK_PREVENTION:"890F7575-59ED-42D4-9DEE-D76FF84941F0",CLICK_PREVENTION_FAILURE_TELEMETRY:"D7FADF7A-4055-4005-82BC-3F75FE2C2ACB",FG_LEARN_MORE_LINK:"dff56850-8158-4b01-a3c3-12dacad9ec40"},BLOCKPAGE:{TYPE:{KNOWNBAD:"knownbad",SUSPECTEDBAD:"suspectedbad",MALICIOUS:"malicious",MALICIOUSSHOP:"maliciousshop",
IPS:"IPS"},HTML:"blockedPage.html",parameterKeys:{ORIGINAL_URL:"originalURL",REPORT_URL:"reportURL",BLOCK_PAGE_TYPE:"blockPageType",ULANG:"ulang",CONTINUE_TO_SITE_URL:"continueToSiteURL"}},SCAM_INSIGHT_BLOCK_PAGE:{strings:"Safe Web;Scam Insight: Personal Information Risk;This site is safe, but\u2026;It asks for personal information and is not well established with the Norton Community. Use caution when entering any of your information on this site. ;Visit ;Norton ;to learn more about personal information risk on Web sites.;Age: ;Very New;This website was published very recently.;New;This website has been available for a short time.;Prevalence: ;No Users;No Norton community members have used this site.;Few Users;Very few Norton community members have used this site.;Continue to Site;Exit Site;If you think this website is categorized incorrectly, ;Report Issue.".split(";")},
SETTINGS_UI:{strings:"Home Page;Safe Web;Safe Search;Settings;Share Data with Norton;Share usage and error data anonymously with Norton and help us make our products even better;Privacy Policy;Signed in as;Sign out;Link Guard;Identify unsafe links in Webmail, Facebook, and Twitter;Banking Protection;Banking Protection can help protect your sensitive online transactions.;Learn More".split(";")},BROWSER_NOTIFICATION:{strings:["You have successfully logged out of your Norton Account","Sorry, something went wrong. Please try again."]},
FG_BANKING_PROTECTION:{isolationMode:[0,1,2],isolationModeChange:{ISOLATION_CHANGE:"isolation mode change",DELETED:"hostname entry deleted"}},EXTENSION_TYPE:"sw",SAFEWEB_EXTENSION:"sw",TWO_IN_ONE:"2in1",THREE_IN_ONE:"three-in-one",BROWSER_NOTIFICATION_IMAGE:"../../Icon-48.png"}})(executionContext);
(function(b){(b.NSSS=b.NSSS||{}).NSSSHelper=function(b,a){var c={},d=b.utils.isNil,f=b.utils.isString,e=a.constants;c.constants={chromeInterstitialSegmentString:"chromeInterstitial"};c.getCurrentWindowLocation=function(){return document.location.href};c.isLandingPageURL=function(a){if(d(a)||!f(a))return!1;a=new URI(a);return"https"!==a.protocol()?!1:e.ONBOARDING_PORTAL_DOMAIN_MAP.hasOwnProperty(a.domain())&&e.ONBOARDING_PORTAL_DOMAIN_MAP[a.domain()].includes(a.subdomain())?!0:!1};c.isChromeInterstitialPageURL=
function(b){if(d(b))return!1;var h=c.constants.chromeInterstitialSegmentString;b=new URI(b);return"https"===b.protocol()&&a.constants.ONBOARDING_PORTAL_DOMAIN_MAP.hasOwnProperty(b.domain())&&a.constants.ONBOARDING_PORTAL_DOMAIN_MAP[b.domain()].includes(b.subdomain())&&(b=b.segment(),1===b.length&&b[0]===h)?!0:!1};c.isCurrentExtensionURL=function(a){var c=b.globals.BROWSER;a=new URI(a);var d=a.path().split("/");switch(c){case "Chrome":if(d.includes(b.extensionAdapter.getExtensionId()))return!0;break;
case "Safari":c=a.search(!0).id;a=b.extensionAdapter.getExtensionId().split("-")[0];if(c&&c.startsWith(a))return!0;break;case "Edge":if(d.includes(e.STORE_URL_NAME))return!0}};c.isYahooSERPPage=function(a){if(!f(a))return!1;a=new URI(a);return"https"===a.protocol()&&a.domain()===e.YAHOO_DOMAIN_NAME&&a.hasSearch(e.yahooVendorConstants.HSPART,e.yahooVendorConstants.HSPART_VALUE)&&(a.hasSearch(e.yahooVendorConstants.HSIMP,e.yahooVendorConstants.HSIMP_VALUE)||a.hasSearch(e.yahooVendorConstants.HSIMP,
e.yahooVendorConstants.HSIMP_VALUE_THREE_IN_ONE))?!0:!1};c.isValidURL=function(a){if(!f(a))return!1;a=new URI(a);var b=a.protocol();if(d(b)||0===b.length)return!1;b=a.domain();return d(b)||0===b.length?!1:!0};return c}(b.SymBfw,b.NSSS)})(executionContext);
