var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(f){var e=0;return function(){return e<f.length?{done:!1,value:f[e++]}:{done:!0}}};$jscomp.arrayIterator=function(f){return{next:$jscomp.arrayIteratorImpl(f)}};$jscomp.makeIterator=function(f){var e="undefined"!=typeof Symbol&&Symbol.iterator&&f[Symbol.iterator];return e?e.call(f):$jscomp.arrayIterator(f)};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(f,e,d){f!=Array.prototype&&f!=Object.prototype&&(f[e]=d.value)};$jscomp.getGlobal=function(f){return"undefined"!=typeof window&&window===f?f:"undefined"!=typeof global&&null!=global?global:f};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(f,e){this.$jscomp$symbol$id_=f;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:e})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function f(d){if(this instanceof f)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(d||"")+"_"+e++,d)}var e=0;return f}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var f=$jscomp.global.Symbol.iterator;f||(f=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[f]&&$jscomp.defineProperty(Array.prototype,f,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var f=$jscomp.global.Symbol.asyncIterator;f||(f=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(f){$jscomp.initSymbolIterator();f={next:f};f[$jscomp.global.Symbol.iterator]=function(){return this};return f};
$jscomp.iteratorFromArray=function(f,e){$jscomp.initSymbolIterator();f instanceof String&&(f+="");var d=0,c={next:function(){if(d<f.length){var b=d++;return{value:e(b,f[b]),done:!1}}c.next=function(){return{done:!0,value:void 0}};return c.next()}};c[Symbol.iterator]=function(){return c};return c};
$jscomp.polyfill=function(f,e,d,c){if(e){d=$jscomp.global;f=f.split(".");for(c=0;c<f.length-1;c++){var b=f[c];b in d||(d[b]={});d=d[b]}f=f[f.length-1];c=d[f];e=e(c);e!=c&&null!=e&&$jscomp.defineProperty(d,f,{configurable:!0,writable:!0,value:e})}};$jscomp.polyfill("Array.prototype.keys",function(f){return f?f:function(){return $jscomp.iteratorFromArray(this,function(e){return e})}},"es6","es3");$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(f){function e(){this.batch_=null}function d(g){return g instanceof b?g:new b(function(a,b){a(g)})}if(f&&!$jscomp.FORCE_POLYFILL_PROMISE)return f;e.prototype.asyncExecute=function(g){if(null==this.batch_){this.batch_=[];var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})}this.batch_.push(g)};var c=$jscomp.global.setTimeout;e.prototype.asyncExecuteFunction=function(a){c(a,0)};e.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var d=a[b];a[b]=null;try{d()}catch(k){this.asyncThrow_(k)}}}this.batch_=null};e.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var b=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var g=this.createResolveAndReject_();try{a(g.resolve,g.reject)}catch(h){g.reject(h)}};b.prototype.createResolveAndReject_=function(){function a(a){return function(g){d||(d=!0,a.call(b,g))}}var b=this,d=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};b.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof b)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var g=null!=a;break a;case "function":g=!0;break a;default:g=!1}g?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};b.prototype.resolveToNonPromiseObj_=function(a){var g=void 0;try{g=a.then}catch(h){this.reject_(h);return}"function"==typeof g?
this.settleSameAsThenable_(g,a):this.fulfill_(a)};b.prototype.reject_=function(a){this.settle_(2,a)};b.prototype.fulfill_=function(a){this.settle_(1,a)};b.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};b.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var g=0;g<this.onSettledCallbacks_.length;++g)a.asyncExecute(this.onSettledCallbacks_[g]);
this.onSettledCallbacks_=null}};var a=new e;b.prototype.settleSameAsPromise_=function(a){var g=this.createResolveAndReject_();a.callWhenSettled_(g.resolve,g.reject)};b.prototype.settleSameAsThenable_=function(a,b){var g=this.createResolveAndReject_();try{a.call(b,g.resolve,g.reject)}catch(k){g.reject(k)}};b.prototype.then=function(a,d){function g(a,g){return"function"==typeof a?function(l){try{c(a(l))}catch(r){e(r)}}:g}var c,e,m=new b(function(a,g){c=a;e=g});this.callWhenSettled_(g(a,c),g(d,e));return m};
b.prototype.catch=function(a){return this.then(void 0,a)};b.prototype.callWhenSettled_=function(g,b){function d(){switch(c.state_){case 1:g(c.result_);break;case 2:b(c.result_);break;default:throw Error("Unexpected state: "+c.state_);}}var c=this;null==this.onSettledCallbacks_?a.asyncExecute(d):this.onSettledCallbacks_.push(d)};b.resolve=d;b.reject=function(a){return new b(function(g,b){b(a)})};b.race=function(a){return new b(function(b,g){for(var c=$jscomp.makeIterator(a),e=c.next();!e.done;e=c.next())d(e.value).callWhenSettled_(b,
g)})};b.all=function(a){var g=$jscomp.makeIterator(a),c=g.next();return c.done?d([]):new b(function(a,b){function e(b){return function(g){l[b]=g;m--;0==m&&a(l)}}var l=[],m=0;do l.push(void 0),m++,d(c.value).callWhenSettled_(e(l.length-1),b),c=g.next();while(!c.done)})};return b},"es6","es3");$jscomp.polyfill("Object.is",function(f){return f?f:function(e,d){return e===d?0!==e||1/e===1/d:e!==e&&d!==d}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(f){return f?f:function(e,d){var c=this;c instanceof String&&(c=String(c));var b=c.length;d=d||0;for(0>d&&(d=Math.max(d+b,0));d<b;d++){var a=c[d];if(a===e||Object.is(a,e))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(f,e,d){if(null==f)throw new TypeError("The 'this' value for String.prototype."+d+" must not be null or undefined");if(e instanceof RegExp)throw new TypeError("First argument to String.prototype."+d+" must not be a regular expression");return f+""};$jscomp.polyfill("String.prototype.includes",function(f){return f?f:function(e,d){return-1!==$jscomp.checkStringArgs(this,e,"includes").indexOf(e,d||0)}},"es6","es3");
(function(f){(f.SymBfw=f.SymBfw||{}).globals={BROWSER:"Chrome",PRODUCT_GUID:"DC6B1B05-C7B2-43EB-81E3-CBD3896553C2"}})(this);(function(f){(f.SymBfw=f.SymBfw||{}).logger=function(e){return{debug:function(d){},log:function(d){},error:function(d){console.error(d);var c=e.telemetryWrapper;c.send(c.componentType.LOGGER,c.actionType.ERROR,d)},warn:function(d){console.warn(d);var c=e.telemetryWrapper;c.send(c.componentType.LOGGER,c.actionType.WARN,d)},info:function(d){console.info(d)}}}(f.SymBfw)})(this);
(function(f){f=f.SymBfw;var e={httpStatusCodes:{},localizer:{DEFAULT_MESSAGES_DICTIONARY:"strings",GET_LOCALIZED_STRING:"44F4D54E-AB86-454C-A494-DE3AD87E72F9",GET_LOCALIZED_STRINGS:"0D1C5EEF-749F-4EEB-AD6D-F9C26018EE91",GET_ALL_LOCALIZED_STRINGS:"33445b60-9a88-4d99-829f-564704b2a960",GET_LOCALIZED_STRING_FROM_DICTIONARY:"D15C0B4C-DC1B-403F-A3C8-8BB42137B325",GET_LOCALIZED_STRINGS_FROM_DICTIONARY:"88313974-C371-4A8D-9196-0A2CE43C8327",GET_LOCALIZED_STRING_WITH_FORMAT:"F3D7C8CE-B1A9-425A-AD24-4120C592AF86",
GET_LOCALIZED_STRING_WITH_FORMAT_FROM_DICTIONARY:"9066F4CC-31A4-45F5-A07A-81DDC38E5F99",GET_CURRENT_LANGUAGE_DIRECTION:"C30B2719-DD82-41EC-E93A-8A602444F90A",GET_LOCALIZED_STRINGS_WITH_FORMAT:"E225C9A6-209A-4702-8E48-3B6EFBF67E26"},clipboard:{messages:{CLEAR_CLIPBOARD:"aa232db5-1dba-473a-ab4b-e9c378b7978b"},DEFAULT_TIMEOUT:6E4}};e.httpStatusCodes.OK=200;e.httpStatusCodes.PARTIAL_CONTENT=206;e.httpStatusCodes.CREATED=201;e.httpStatusCodes.NO_CONTENT=204;e.httpStatusCodes.INCORRECT_URI=302;e.httpStatusCodes.NOT_MODIFIED=
304;e.httpStatusCodes.BAD_REQUEST=400;e.httpStatusCodes.UNAUTHORIZED=401;e.httpStatusCodes.INVALID_SCHEMA=403;e.httpStatusCodes.NOT_FOUND=404;e.httpStatusCodes.HEADER_ERROR=406;e.httpStatusCodes.GONE=410;e.httpStatusCodes.ENTITY_TOO_LARGE=413;e.httpStatusCodes.DATASTORE_RATE_LIMITED=429;e.httpStatusCodes.RATE_LIMITING=503;e.httpStatusCodes.SERVER_ERROR=500;e.DEFAULT_FETCH_TIMEOUT=6E4;e.CERT_COMMON_NAME="CN";e.telemetry={TELEMETRY_ENABLED:"293E0764-AF48-4C52-B675-0161A7B6BECE",TELEMETRY_OPT_OUT_SHOWN:"FE795012-44D6-491D-A8A1-E83633892C9D",
BFW_TELEMETRY_SETTINGS_CONTAINER:"233D07C0-6318-4BCE-A36A-82DFB19F3B2A",USER_RESPONDED_IN_OPT_OUT_PAGE:"8157BC1F-5ED8-4373-A18D-8CD8E0263752",LAST_OFFER_DATE:"9EA53F0C-7F18-44A5-8138-C11F27D66FC1"};e.os={WINDOWS:"Windows",MAC:"Mac",UNKNOWN:"Unknown"};e.CDN_FILE_DOWNLOADER={ENCRYPTION_METHOD:"RS256",SUPPORTED_PROTOCOL:"https",SUPPORTED_FILEFORMATS:["json"],RESPONSE_STATUS:{UNSUCCESSFUL_RESPONSE:"Error in fetching the file with status code",FILE_TAMPERED:"CDN file has been tampered",PUBLIC_KEY_NOT_VERIFIED:"Public key verification has failed",
INVALID_PARAMETERS:"Invalid paramaters"},CERT_ISSUER_NAME:"CERT_ISSUER_NAME",CERT_ISSUED:"CERT_ISSUED"};e.uiConstants={NOTIFICATION:{IFRAME_ID:"symc-notification-popup",HTML:"content/ui/notification.html",STYLE:"content/ui/content-page.css",STACK_COUNT:1,DEFAULT_TIMEOUT:1E4,HEIGHT:160,WIDTH:460,TYPE:{QUESTION:0,TIMED:1},BUTTON:{DEFAULT:0,SECONDARY:1},MESSAGES:{DEFAULT_MESSAGE:"8DB8FE17-6F5E-485E-81EE-1112762F48E4",DEFAULT_BUTTON_PRESSED:"209CBB4D-6D6B-46F4-9EA7-303181937BF6",SECONDARY_LINK_PRESSED:"8881560D-E8A2-41FA-A81D-A90D41311D0D",
THIRD_BUTTON_PRESSED:"196F06EB-956E-44EE-A60D-F4741C5CF4D3",NOTIFICATION_CLOSED:"EA7414A5-667F-4459-BAC2-38464F3330A3",NOTIFICATION_QUEUE_MESSAGE:"A88CCFCD-B98D-4607-B780-79A1CF7ADFAD",NOTIFICATIONS_SHOWN:"57C094C2-F0F0-44C2-9BBF-9E147135FB50",UI_INIT:"EE5B61D6-3A55-4ABB-B304-02BDAD9698FE",UI_INIT_PROXY:"0FABE0DB-1C87-475B-D89E-F4EC0EE963DE",HIDE_NOTIFICATIONS:"8211780F-93EC-4E37-8933-E60CB6052E84"}},CONTENT_PAGE_STYLE_ID:"symc-content-stylesheet"};e.performanceReporter={MESSAGES:{REPORT_START:"2379B4CB-E725-4818-8FCC-A9372EABBF45",
REPORT_END:"1F62DD4E-56AD-4528-9A69-BFE9EC135B9F",GET_PERFORMANCE_REPORTER:"2306DE62-ACA8-40AE-9909-517474C1120B"}};e.utils={IP:"ip"};e.NAVIGATION_COMPLETE="complete";e.STORE_URLS={Chrome:"https://chrome.google.com/webstore/",Firefox:"https://addons.mozilla.org/",Safari:"https://safari-extensions.apple.com/",Edge:"https://www.microsoft.com/[a-zA-Z]+[-]?[a-zA-Z]*/(p|store)/"};e.BROWSER_TYPE={CHROME:"Chrome",FIREFOX:"Firefox",EDGE:"Edge",SAFARI:"Safari"};f.constants=e})(this);
(function(f){f.SymBfw.utils=function(e){var d={},c=e.constants;d.createNewGuid=function(){var a=(new Date).getTime();return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(b){var g=(a+16*Math.random())%16|0;a=Math.floor(a/16);return("x"==b?g:g&7|8).toString(16)})};d.stringUTF16LEToByteArray=function(a){if(!1===this.isString(a))throw Error("Input string cannot be null or is not a string");for(var b=[],d=0;d<a.length;++d){var c=a.charCodeAt(d),e=(c&65280)>>8;b.push(c&255);b.push(e)}return b};
d.arrayBufferToStringUTF16LE=function(a){if(this.isNil(a))return null;a instanceof ArrayBuffer&&(a=new Uint8Array(a));for(var b=[],d=0;d<a.byteLength;d++)b.push(a[d]);return this.byteArrayToStringUTF16LE(b)};d.byteArrayToStringUTF16LE=function(a){if(!1===this.isArray(a))throw Error("Byte array cannot be null or is not an array");if(2>a.length)throw Error("Byte array needs to contain at least two bytes");if(0!==a.length%2)throw Error("Byte array needs to contain even number of bytes");for(var b="",
d=0;d<a.length-1;d+=2){var c=a[d];if(255<c)throw Error("Encoding error: Input contains element larger than a byte.");c&=255;var e=a[d+1];if(255<e)throw Error("Encoding error: Input contains element larger than a byte.");e=e<<8&65280;b+=String.fromCharCode(c+e)}return b};d.downloadFileFromUrl=function(a){var b=document.createElement("iframe");b.style.display="none";b.src=a;b.width="1";b.height="1";b.frameborder="0";document.body.appendChild(b);setTimeout(function(){document.body.removeChild(b)},5E3)};
d.obfuscatePassword=function(a,b){if(!1===this.isString(a))throw Error("password  cannot be null and has to be a string");if(!1===this.isString(b))throw Error("obfuscationKey  cannot be null and has to be a string");a=new Uint8Array(e.utils.stringUTF16LEToByteArray(a));b=new Uint8Array(e.utils.stringUTF16LEToByteArray(b));b=e.utils._obfuscateData(a,b);return b=e.utils.arrayBufferToStringUTF16LE(b)};d._obfuscateData=function(a,b){if(d.isNil(a)||d.isNil(b))return null;a instanceof ArrayBuffer&&(a=new Uint8Array(a));
b instanceof ArrayBuffer&&(b=new Uint8Array(b));for(var g=a.byteLength,c=new Uint8Array(g),e=0;e<g;e++)c[e]=a[e]^b[e%g];return c};d.getOSType=function(){var a=c.os.UNKNOWN;-1!=navigator.appVersion.toLowerCase().indexOf("win")?a=c.os.WINDOWS:-1!=navigator.appVersion.toLowerCase().indexOf("mac")&&(a=c.os.MAC);return a};d.isNil=function(a){return"undefined"===typeof a||null===a?!0:!1};d.isntNil=function(a){return"undefined"!==typeof a&&null!==a?!0:!1};d.isEmptyObject=function(a){return d.isNil(a)||0===
Object.keys(a).length?!0:!1};d.objectHas=function(a,b){return d.isObject(a)&&d.isString(b)?Object.prototype.hasOwnProperty.call(a,b):!1};d.isString=function(a){return d.isntNil(a)&&"string"===typeof a?!0:!1};d.isFunction=function(a){return d.isntNil(a)&&"function"===typeof a?!0:!1};d.isArray=function(a){return Array.isArray(a)};d.isObject=function(a){return d.isntNil(a)&&"object"===typeof a&&a.constructor===Object?!0:!1};d.isBoolean=function(a){return d.isntNil(a)&&"boolean"===typeof a?!0:!1};var b=
{ac:{com:!0,gov:!0,mil:!0,net:!0,org:!0,edu:!0},ad:{nom:!0},ae:{ac:!0,co:!0,gov:!0,mil:!0,name:!0,net:!0,org:!0,pro:!0,sch:!0},af:{com:!0,edu:!0,gov:!0,net:!0,org:!0},ai:{off:!0,com:!0,net:!0,org:!0},al:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0,uniti:!0,tirana:!0,soros:!0,upt:!0,inima:!0},an:{com:!0,net:!0,org:!0,edu:!0},ag:{com:!0,org:!0,net:!0,co:!0,nom:!0},ao:{co:!0,ed:!0,gv:!0,it:!0,og:!0,pb:!0},ar:{com:!0,edu:!0,gob:!0,gov:!0,"int":!0,mil:!0,net:!0,org:!0,tur:!0},arpa:{e164:!0,"in-addr":!0,
iris:!0,ip6:!0,uri:!0,urn:!0},at:{ac:!0,co:!0,gv:!0,or:!0,priv:!0},au:{asn:!0,com:!0,net:!0,id:!0,org:!0,csiro:!0,oz:!0,info:!0,conf:!0,act:!0,nsw:!0,nt:!0,qld:!0,sa:!0,tas:!0,vic:!0,wa:!0},aw:{com:!0},az:{com:!0,net:!0,"int":!0,gov:!0,biz:!0,org:!0,edu:!0,mil:!0,pp:!0,name:!0,info:!0},ba:{co:!0,com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0,rs:!0,unbi:!0,unmo:!0,unsa:!0,untz:!0,unze:!0},bb:{biz:!0,co:!0,com:!0,edu:!0,gov:!0,info:!0,net:!0,org:!0,store:!0,tv:!0},bd:{com:!0,edu:!0,net:!0,gov:!0,org:!0,
mil:!0},be:{ac:!0},bf:{gov:!0},bh:{biz:!0,cc:!0,com:!0,edu:!0,gov:!0,info:!0,net:!0,org:!0},bm:{com:!0,edu:!0,org:!0,gov:!0,net:!0},bn:{com:!0,edu:!0,gov:!0,net:!0,org:!0},bo:{com:!0,edu:!0,gob:!0,gov:!0,"int":!0,mil:!0,net:!0,org:!0,tv:!0},br:{adm:!0,adv:!0,agr:!0,am:!0,arq:!0,art:!0,ato:!0,b:!0,bio:!0,blog:!0,bmd:!0,cim:!0,cng:!0,cnt:!0,com:!0,coop:!0,ecn:!0,edu:!0,eng:!0,esp:!0,etc:!0,eti:!0,far:!0,flog:!0,fm:!0,fnd:!0,fot:!0,fst:!0,g12:!0,ggf:!0,gov:!0,imb:!0,ind:!0,inf:!0,jor:!0,jus:!0,lel:!0,
mat:!0,med:!0,mil:!0,mus:!0,net:!0,nom:!0,not:!0,ntr:!0,odo:!0,org:!0,ppg:!0,pro:!0,psc:!0,psi:!0,qsl:!0,rec:!0,slg:!0,srv:!0,tmp:!0,trd:!0,tur:!0,tv:!0,vet:!0,vlog:!0,wiki:!0,zlg:!0},bs:{com:!0,edu:!0,gov:!0,net:!0,org:!0},bt:{com:!0,edu:!0,gov:!0,net:!0,org:!0},bw:{co:!0,org:!0},by:{gov:!0,mil:!0},bz:{du:!0,et:!0,om:!0,ov:!0,rg:!0},ca:{ab:!0,bc:!0,mb:!0,nb:!0,nf:!0,nl:!0,ns:!0,nt:!0,nu:!0,on:!0,pe:!0,qc:!0,sk:!0,yk:!0},cc:{co:!0},ck:{biz:!0,co:!0,edu:!0,gen:!0,gov:!0,info:!0,net:!0,org:!0},cn:{ac:!0,
ah:!0,bj:!0,com:!0,cq:!0,edu:!0,fj:!0,gd:!0,gov:!0,gs:!0,gx:!0,gz:!0,ha:!0,hb:!0,he:!0,hi:!0,hl:!0,hn:!0,jl:!0,js:!0,jx:!0,ln:!0,mil:!0,net:!0,nm:!0,nx:!0,org:!0,qh:!0,sc:!0,sd:!0,sh:!0,sn:!0,sx:!0,tj:!0,tw:!0,xj:!0,xz:!0,yn:!0,zj:!0},co:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,nom:!0,org:!0},cr:{ac:!0,c:!0,co:!0,ed:!0,fi:!0,go:!0,or:!0,sa:!0},cx:{gov:!0},cy:{ac:!0,biz:!0,com:!0,ekloges:!0,gov:!0,ltd:!0,name:!0,net:!0,org:!0,parliament:!0,press:!0,pro:!0,tm:!0},cu:{com:!0,edu:!0,org:!0,net:!0,gov:!0,inf:!0},
dm:{com:!0,net:!0,org:!0,edu:!0,gov:!0},"do":{art:!0,com:!0,edu:!0,gob:!0,gov:!0,mil:!0,net:!0,org:!0,sld:!0,web:!0},dz:{art:!0,asso:!0,com:!0,edu:!0,gov:!0,net:!0,org:!0,pol:!0},ec:{com:!0,edu:!0,fin:!0,gov:!0,info:!0,med:!0,mil:!0,net:!0,org:!0,pro:!0},ee:{com:!0,org:!0,fie:!0,pri:!0},eg:{com:!0,edu:!0,eun:!0,gov:!0,mil:!0,name:!0,net:!0,org:!0,sci:!0},er:{com:!0,edu:!0,gov:!0,ind:!0,mil:!0,net:!0,org:!0,rochest:!0,w:!0},es:{com:!0,edu:!0,gob:!0,nom:!0,org:!0},et:{biz:!0,com:!0,edu:!0,gov:!0,info:!0,
name:!0,net:!0,org:!0},fi:{aland:!0},fj:{ac:!0,biz:!0,com:!0,info:!0,mil:!0,name:!0,net:!0,org:!0,pro:!0},fk:{ac:!0,co:!0,gov:!0,net:!0,nom:!0,org:!0},fr:{asso:!0,com:!0,f:!0,gouv:!0,nom:!0,prd:!0,presse:!0,tm:!0},ge:{com:!0,edu:!0,gov:!0,org:!0,mil:!0,net:!0,pvt:!0},gg:{co:!0,net:!0,org:!0},gh:{com:!0,edu:!0,gov:!0,mil:!0,org:!0},gi:{com:!0,ltd:!0,gov:!0,mod:!0,edu:!0,org:!0},gn:{ac:!0,com:!0,gov:!0,net:!0,org:!0},gp:{com:!0,net:!0,edu:!0,asso:!0,org:!0},gr:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0},
gt:{com:!0,edu:!0,gob:!0,ind:!0,mil:!0,net:!0,org:!0},gu:{com:!0,edu:!0,gov:!0,net:!0,org:!0},hk:{com:!0,edu:!0,gov:!0,idv:!0,net:!0,org:!0},ht:{com:!0,net:!0,firm:!0,shop:!0,info:!0,pro:!0,adult:!0,org:!0,art:!0,pol:!0,rel:!0,asso:!0,perso:!0,coop:!0,med:!0,edu:!0,gouv:!0},hu:{2E3:!0,agrar:!0,bolt:!0,casino:!0,city:!0,co:!0,erotica:!0,erotika:!0,film:!0,forum:!0,games:!0,hotel:!0,info:!0,ingatlan:!0,jogasz:!0,konyvelo:!0,lakas:!0,media:!0,news:!0,org:!0,priv:!0,reklam:!0,sex:!0,shop:!0,sport:!0,
suli:!0,szex:!0,tm:!0,tozsde:!0,utazas:!0,video:!0},id:{ac:!0,co:!0,go:!0,mil:!0,net:!0,or:!0,sch:!0,web:!0},il:{ac:!0,co:!0,gov:!0,idf:!0,k12:!0,muni:!0,net:!0,org:!0},im:{co:!0,"ltd.co":!0,"plc.co":!0,net:!0,gov:!0,org:!0,nic:!0,ac:!0},"in":{ac:!0,co:!0,edu:!0,ernet:!0,firm:!0,gen:!0,gov:!0,i:!0,ind:!0,mil:!0,net:!0,nic:!0,org:!0,res:!0},iq:{com:!0,edu:!0,gov:!0,i:!0,mil:!0,net:!0,org:!0},ir:{ac:!0,co:!0,dnssec:!0,gov:!0,i:!0,id:!0,net:!0,org:!0,sch:!0},it:{edu:!0,gov:!0},je:{co:!0,net:!0,org:!0},
jo:{com:!0,edu:!0,gov:!0,mil:!0,name:!0,net:!0,org:!0,sch:!0},jp:{ac:!0,ad:!0,co:!0,ed:!0,go:!0,gr:!0,lg:!0,ne:!0,or:!0},ke:{ac:!0,co:!0,go:!0,info:!0,me:!0,mobi:!0,ne:!0,or:!0,sc:!0},kh:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0,per:!0},ki:{biz:!0,com:!0,de:!0,edu:!0,gov:!0,info:!0,mob:!0,net:!0,org:!0,tel:!0},km:{asso:!0,com:!0,coop:!0,edu:!0,gouv:!0,k:!0,medecin:!0,mil:!0,nom:!0,notaires:!0,pharmaciens:!0,presse:!0,tm:!0,veterinaire:!0},kn:{edu:!0,gov:!0,net:!0,org:!0},kr:{ac:!0,busan:!0,chungbuk:!0,
chungnam:!0,co:!0,daegu:!0,daejeon:!0,es:!0,gangwon:!0,go:!0,gwangju:!0,gyeongbuk:!0,gyeonggi:!0,gyeongnam:!0,hs:!0,incheon:!0,jeju:!0,jeonbuk:!0,jeonnam:!0,k:!0,kg:!0,mil:!0,ms:!0,ne:!0,or:!0,pe:!0,re:!0,sc:!0,seoul:!0,ulsan:!0},kw:{com:!0,edu:!0,gov:!0,net:!0,org:!0},ky:{com:!0,edu:!0,gov:!0,net:!0,org:!0},kz:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0},lb:{com:!0,edu:!0,gov:!0,net:!0,org:!0},lc:{com:!0,org:!0,edu:!0,gov:!0},li:{com:!0,net:!0,org:!0,gov:!0},lk:{assn:!0,com:!0,edu:!0,gov:!0,grp:!0,
hotel:!0,"int":!0,ltd:!0,net:!0,ngo:!0,org:!0,sch:!0,soc:!0,web:!0},lr:{com:!0,edu:!0,gov:!0,net:!0,org:!0},ls:{org:!0,co:!0},lt:{gov:!0,mil:!0},lu:{gov:!0,mil:!0,org:!0,net:!0},lv:{asn:!0,com:!0,conf:!0,edu:!0,gov:!0,id:!0,mil:!0,net:!0,org:!0},ly:{com:!0,edu:!0,gov:!0,id:!0,med:!0,net:!0,org:!0,plc:!0,sch:!0},ma:{ac:!0,co:!0,gov:!0,m:!0,net:!0,org:!0,press:!0},mc:{asso:!0,tm:!0},me:{ac:!0,co:!0,edu:!0,gov:!0,its:!0,net:!0,org:!0,priv:!0},mg:{com:!0,edu:!0,gov:!0,mil:!0,nom:!0,org:!0,prd:!0,tm:!0},
mk:{com:!0,edu:!0,gov:!0,inf:!0,name:!0,net:!0,org:!0,pro:!0},ml:{com:!0,edu:!0,gov:!0,net:!0,org:!0,presse:!0},mn:{edu:!0,gov:!0,org:!0},mo:{com:!0,edu:!0,gov:!0,net:!0,org:!0},mt:{com:!0,edu:!0,gov:!0,net:!0,org:!0},mv:{aero:!0,biz:!0,com:!0,coop:!0,edu:!0,gov:!0,info:!0,"int":!0,mil:!0,museum:!0,name:!0,net:!0,org:!0,pro:!0},mw:{ac:!0,co:!0,com:!0,coop:!0,edu:!0,gov:!0,"int":!0,museum:!0,net:!0,org:!0},mx:{com:!0,edu:!0,gob:!0,net:!0,org:!0},my:{com:!0,edu:!0,gov:!0,mil:!0,name:!0,net:!0,org:!0,
sch:!0},nf:{arts:!0,com:!0,firm:!0,info:!0,net:!0,other:!0,per:!0,rec:!0,store:!0,web:!0},ng:{biz:!0,com:!0,edu:!0,gov:!0,mil:!0,mobi:!0,name:!0,net:!0,org:!0,sch:!0},ni:{ac:!0,co:!0,com:!0,edu:!0,gob:!0,mil:!0,net:!0,nom:!0,org:!0},no:{mil:!0,stat:!0,kommune:!0,herad:!0,priv:!0,vgs:!0,fhs:!0,museum:!0,fylkesbibl:!0,folkebibl:!0,idrett:!0},np:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0},nr:{biz:!0,com:!0,edu:!0,gov:!0,info:!0,net:!0,org:!0},om:{ac:!0,biz:!0,co:!0,com:!0,edu:!0,gov:!0,med:!0,mil:!0,
museum:!0,net:!0,org:!0,pro:!0,sch:!0},pe:{com:!0,edu:!0,gob:!0,mil:!0,net:!0,nom:!0,org:!0,sld:!0},pf:{com:!0,org:!0,edu:!0},pg:{"com.pg":!0,net:!0},ph:{com:!0,edu:!0,gov:!0,i:!0,mil:!0,net:!0,ngo:!0,org:!0},pk:{biz:!0,com:!0,edu:!0,fam:!0,gob:!0,gok:!0,gon:!0,gop:!0,gos:!0,gov:!0,net:!0,org:!0,web:!0},pl:{art:!0,bialystok:!0,biz:!0,com:!0,edu:!0,gda:!0,gdansk:!0,gorzow:!0,gov:!0,info:!0,katowice:!0,krakow:!0,lodz:!0,lublin:!0,mil:!0,net:!0,ngo:!0,olsztyn:!0,org:!0,poznan:!0,pwr:!0,radom:!0,slupsk:!0,
szczecin:!0,torun:!0,warszawa:!0,waw:!0,wroc:!0,wroclaw:!0,zgora:!0},pr:{ac:!0,biz:!0,com:!0,edu:!0,est:!0,gov:!0,info:!0,isla:!0,name:!0,net:!0,org:!0,pro:!0,prof:!0},pro:{law:!0,med:!0,cpa:!0},ps:{com:!0,edu:!0,gov:!0,net:!0,org:!0,plo:!0,sec:!0},pt:{com:!0,edu:!0,gov:!0,"int":!0,net:!0,nome:!0,org:!0,publ:!0},pw:{belau:!0,co:!0,ed:!0,go:!0,ne:!0,or:!0},ro:{arts:!0,com:!0,firm:!0,info:!0,nom:!0,nt:!0,org:!0,rec:!0,store:!0,tm:!0,www:!0},rs:{ac:!0,co:!0,edu:!0,gov:!0,"in":!0,org:!0},sb:{com:!0,edu:!0,
gov:!0,net:!0,org:!0},sc:{com:!0,edu:!0,gov:!0,net:!0,org:!0},sh:{co:!0,com:!0,edu:!0,gov:!0,net:!0,nom:!0,org:!0},sl:{com:!0,edu:!0,gov:!0,net:!0,org:!0},st:{co:!0,com:!0,consulado:!0,edu:!0,embaixada:!0,gov:!0,mil:!0,net:!0,org:!0,principe:!0,saotome:!0,store:!0},sv:{com:!0,edu:!0,gob:!0,org:!0,red:!0},sz:{ac:!0,co:!0,org:!0},tr:{av:!0,bbs:!0,bel:!0,biz:!0,com:!0,dr:!0,edu:!0,gen:!0,gov:!0,info:!0,k12:!0,name:!0,net:!0,org:!0,pol:!0,tel:!0,tsk:!0,tv:!0,web:!0},tt:{aero:!0,biz:!0,cat:!0,co:!0,com:!0,
coop:!0,edu:!0,gov:!0,info:!0,"int":!0,jobs:!0,mil:!0,mobi:!0,museum:!0,name:!0,net:!0,org:!0,pro:!0,tel:!0,travel:!0},tw:{club:!0,com:!0,ebiz:!0,edu:!0,game:!0,gov:!0,idv:!0,mil:!0,net:!0,org:!0},mu:{ac:!0,co:!0,com:!0,gov:!0,net:!0,or:!0,org:!0},mz:{ac:!0,co:!0,edu:!0,gov:!0,org:!0},na:{co:!0,com:!0},nz:{ac:!0,co:!0,cri:!0,geek:!0,gen:!0,govt:!0,health:!0,iwi:!0,maori:!0,mil:!0,net:!0,org:!0,parliament:!0,school:!0},pa:{abo:!0,ac:!0,com:!0,edu:!0,gob:!0,ing:!0,med:!0,net:!0,nom:!0,org:!0,sld:!0},
py:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0},qa:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0},re:{asso:!0,com:!0,nom:!0},ru:{ac:!0,adygeya:!0,altai:!0,amur:!0,arkhangelsk:!0,astrakhan:!0,bashkiria:!0,belgorod:!0,bir:!0,bryansk:!0,buryatia:!0,cbg:!0,chel:!0,chelyabinsk:!0,chita:!0,chukotka:!0,chuvashia:!0,com:!0,dagestan:!0,"e-burg":!0,edu:!0,gov:!0,grozny:!0,"int":!0,irkutsk:!0,ivanovo:!0,izhevsk:!0,jar:!0,"joshkar-ola":!0,kalmykia:!0,kaluga:!0,kamchatka:!0,karelia:!0,kazan:!0,kchr:!0,kemerovo:!0,
khabarovsk:!0,khakassia:!0,khv:!0,kirov:!0,koenig:!0,komi:!0,kostroma:!0,kranoyarsk:!0,kuban:!0,kurgan:!0,kursk:!0,lipetsk:!0,magadan:!0,mari:!0,"mari-el":!0,marine:!0,mil:!0,mordovia:!0,mosreg:!0,msk:!0,murmansk:!0,nalchik:!0,net:!0,nnov:!0,nov:!0,novosibirsk:!0,nsk:!0,omsk:!0,orenburg:!0,org:!0,oryol:!0,penza:!0,perm:!0,pp:!0,pskov:!0,ptz:!0,rnd:!0,ryazan:!0,sakhalin:!0,samara:!0,saratov:!0,simbirsk:!0,smolensk:!0,spb:!0,stavropol:!0,stv:!0,surgut:!0,tambov:!0,tatarstan:!0,tom:!0,tomsk:!0,tsaritsyn:!0,
tsk:!0,tula:!0,tuva:!0,tver:!0,tyumen:!0,udm:!0,udmurtia:!0,"ulan-ude":!0,vladikavkaz:!0,vladimir:!0,vladivostok:!0,volgograd:!0,vologda:!0,voronezh:!0,vrn:!0,vyatka:!0,yakutia:!0,yamal:!0,yekaterinburg:!0,"yuzhno-sakhalinsk":!0},rw:{ac:!0,co:!0,com:!0,edu:!0,gouv:!0,gov:!0,"int":!0,mil:!0,net:!0},sa:{com:!0,edu:!0,gov:!0,med:!0,net:!0,org:!0,pub:!0,sch:!0},sd:{com:!0,edu:!0,gov:!0,info:!0,med:!0,net:!0,org:!0,tv:!0},se:{a:!0,ac:!0,b:!0,bd:!0,c:!0,d:!0,e:!0,f:!0,g:!0,h:!0,i:!0,k:!0,l:!0,m:!0,n:!0,
o:!0,org:!0,p:!0,parti:!0,pp:!0,press:!0,r:!0,s:!0,t:!0,tm:!0,u:!0,w:!0,x:!0,y:!0,z:!0},sg:{com:!0,edu:!0,gov:!0,idn:!0,net:!0,org:!0,per:!0},sn:{art:!0,com:!0,edu:!0,gouv:!0,org:!0,perso:!0,univ:!0},sy:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,news:!0,org:!0},th:{ac:!0,co:!0,go:!0,"in":!0,mi:!0,net:!0,or:!0},tj:{ac:!0,biz:!0,co:!0,com:!0,edu:!0,go:!0,gov:!0,info:!0,"int":!0,mil:!0,name:!0,net:!0,nic:!0,org:!0,test:!0,web:!0},tn:{agrinet:!0,com:!0,defense:!0,edunet:!0,ens:!0,fin:!0,gov:!0,ind:!0,info:!0,
intl:!0,mincom:!0,nat:!0,net:!0,org:!0,perso:!0,rnrt:!0,rns:!0,rnu:!0,tourism:!0},tz:{ac:!0,co:!0,go:!0,ne:!0,or:!0},ua:{biz:!0,cherkassy:!0,chernigov:!0,chernovtsy:!0,ck:!0,cn:!0,co:!0,com:!0,crimea:!0,cv:!0,dn:!0,dnepropetrovsk:!0,donetsk:!0,dp:!0,edu:!0,gov:!0,"if":!0,"in":!0,"ivano-frankivsk":!0,kh:!0,kharkov:!0,kherson:!0,khmelnitskiy:!0,kiev:!0,kirovograd:!0,km:!0,kr:!0,ks:!0,kv:!0,lg:!0,lugansk:!0,lutsk:!0,lviv:!0,me:!0,mk:!0,net:!0,nikolaev:!0,od:!0,odessa:!0,org:!0,pl:!0,poltava:!0,pp:!0,
rovno:!0,rv:!0,sebastopol:!0,sumy:!0,te:!0,ternopil:!0,uzhgorod:!0,vinnica:!0,vn:!0,zaporizhzhe:!0,zhitomir:!0,zp:!0,zt:!0},ug:{ac:!0,co:!0,go:!0,ne:!0,or:!0,org:!0,sc:!0},uk:{ac:!0,bl:!0,"british-library":!0,co:!0,cym:!0,gov:!0,govt:!0,icnet:!0,jet:!0,lea:!0,ltd:!0,me:!0,mil:!0,mod:!0,"national-library-scotland":!0,nel:!0,net:!0,nhs:!0,nic:!0,nls:!0,org:!0,orgn:!0,parliament:!0,plc:!0,police:!0,sch:!0,scot:!0,soc:!0},us:{dni:!0,fed:!0,isa:!0,kids:!0,nsn:!0},uy:{com:!0,edu:!0,gub:!0,mil:!0,net:!0,
org:!0},ve:{co:!0,com:!0,edu:!0,gob:!0,info:!0,mil:!0,net:!0,org:!0,web:!0},vi:{co:!0,com:!0,k12:!0,net:!0,org:!0},vn:{ac:!0,biz:!0,com:!0,edu:!0,gov:!0,health:!0,info:!0,"int":!0,name:!0,net:!0,org:!0,pro:!0},ye:{co:!0,com:!0,gov:!0,ltd:!0,me:!0,net:!0,org:!0,plc:!0},yu:{ac:!0,co:!0,edu:!0,gov:!0,org:!0},za:{ac:!0,agric:!0,alt:!0,bourse:!0,city:!0,co:!0,cybernet:!0,db:!0,edu:!0,gov:!0,grondar:!0,iaccess:!0,imt:!0,inca:!0,landesign:!0,law:!0,mil:!0,net:!0,ngo:!0,nis:!0,nom:!0,olivetti:!0,org:!0,pix:!0,
school:!0,tm:!0,web:!0},zm:{ac:!0,co:!0,com:!0,edu:!0,gov:!0,net:!0,org:!0,sch:!0}};d.getSLD=function(a){if(d.isNil(a))return null;var g=a.split("."),c=g.length-2;if(0>c)return null;a=g[c];g=g[c+1];c=b[g];return d.isNil(c)||d.isNil(c[a])?null:a+"."+g};d.depthOfTLDorSLD=function(a){if(d.isNil(a))return null;a=d.getSLD(a);return d.isntNil(a)?2:1};d.isInteger=function(a){return d.isNil(a)?!1:"number"===typeof a&&isFinite(a)&&Math.floor(a)===a};d.isSuccessCode=function(a){return d.isNil(a)?!1:a===c.httpStatusCodes.OK||
a===c.httpStatusCodes.PARTIAL_CONTENT||a===c.httpStatusCodes.CREATED||a===c.httpStatusCodes.NO_CONTENT?!0:!1};d.safeFetch=function(a,b,d){b=void 0===b?{}:b;d=void 0===d?c.DEFAULT_FETCH_TIMEOUT:d;return new Promise(function(c,g){var e=setTimeout(function(){g(Error("Request timed out "+a))},d);fetch(a,b).then(function(a){clearTimeout(e);c(a)}).catch(function(a){clearTimeout(e);g(a)})})};d.isSuccessCodeLocalFile=function(a){return d.isInteger(a)?"Safari"===e.globals.BROWSER&&0===a||a===c.httpStatusCodes.OK?
!0:!1:!1};d.urlWithoutQueryParameters=function(a,b){d.isNil(b)&&(b=!0);if(d.isNil(a))return null;var c=new URI(a),g=c.protocol();if(d.isNil(g)||""===g||"http"!==g&&"https"!==g)g="http",c=new URI(g+"://"+a);a=c.hostname();c=c.path();if(d.isNil(c)||"/"===c)c="";return b?g+"://"+a+c:a+c};d.baseURL=function(a){return d.isNil(a)?null:(new URI(a)).hostname()};d.pathName=function(a){return d.isNil(a)?null:(new URI(a)).pathname()};d.urlProtocol=function(a){if(d.isNil(a))return null;a=(new URI(a)).protocol();
return""===a?null:a};d.getUrlTLD=function(a){if(d.isNil(a))return null;a=(new URI(a)).tld();return""===a?null:a};d.getCompanyDomain=function(a){if(d.isNil(a))return null;var b=(new URI(a)).hostname();a=d.getUrlTLD(a);return""===b?null:d.isntNil(a)&&0<b.indexOf(a)?(b=b.substring(0,b.lastIndexOf(a)-1).split("."),b[b.length-1]):b};d.getDomain=function(a){if(d.isNil(a))return null;a=(new URI(a)).domain();return""===a?null:a};d.isUrlAnIp=function(a){return d.isNil(a)?null:(new URI(a)).is(c.utils.IP)};
d.getFileNameExtension=function(a){if(!d.isString(a))return null;a=(new URI(a)).suffix();return""===a?null:a};d.appendToObject=function(a,b){if(d.isNil(a)||d.isNil(b))throw Error("invalid arguments to appendToObject");Object.keys(b).forEach(function(c){a[c]=b[c]})};d.createCustomHTMLEvent=function(a,b){if(!1===this.isString(a))throw Error("Event name cannot be null and has to be a string");a=new CustomEvent(a,{detail:b});window.dispatchEvent(a)};d.isTopLevelWindow=function(){return"Edge"===e.globals.BROWSER?
window.top.location==window.self.location?!0:!1:window.top==window.self?!0:!1};d.getActiveElement=function(){return document.activeElement};d.verifyJson=function(a,b,c,d){try{var g=forge.md.sha256.create();g.update(JSON.stringify(a));var e=g.digest().toHex(),f=KEYUTIL.getKey(c);if(!0===KJUR.jws.JWS.verify(b,f,d)){var l=b64utoutf8(b.split(".")[1]);return KJUR.jws.JWS.readSafeJSONString(l).hash===e}return!1}catch(q){return!1}};d.isNewVersionUpdated=function(a,b){b=b.split(".");a=a.split(".");var c=
b[1]!==a[1];return b[0]!==a[0]||c?!0:!1};d.isStorePageURL=function(b){return d.isString(b)?"Edge"===e.globals.BROWSER?(new RegExp(c.STORE_URLS[e.globals.BROWSER])).test(b):-1===b.indexOf(c.STORE_URLS[e.globals.BROWSER])?!1:!0:!1};d.upperCaseFirstLetter=function(b){return d.isString(b)?b.charAt(0).toUpperCase()+b.slice(1):b};d.setTimeout=function(b){return new Promise(function(a,c){return d.isInteger(b)?window.setTimeout(a,b):c(Error("Delay must be an integer"))})};d.getValueAtPath=function(b,c,f){c=
e.utils.isString(c)?c.split(/[.[\]]/g).filter(Boolean):c;d.isArray(c)||(c=[c]);return c.reduce(function(b,a){return d.objectHas(b,a)?b[a]:f},b||{})};return d}(f.SymBfw)})(this);
(function(f){f.SymBfw.base64=function(e){var d={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",_utf8Encode:function(c){c=c.replace(/\r\n/g,"\n");for(var b="",a=0;a<c.length;a++){var d=c.charCodeAt(a);128>d?b+=String.fromCharCode(d):(127<d&&2048>d?b+=String.fromCharCode(d>>6|192):(b+=String.fromCharCode(d>>12|224),b+=String.fromCharCode(d>>6&63|128)),b+=String.fromCharCode(d&63|128))}return b},_utf8Decode:function(c){for(var b="",a=0,d,e,f;a<c.length;)d=c.charCodeAt(a),
128>d?(b+=String.fromCharCode(d),a++):191<d&&224>d?(e=c.charCodeAt(a+1),b+=String.fromCharCode((d&31)<<6|e&63),a+=2):(e=c.charCodeAt(a+1),f=c.charCodeAt(a+2),b+=String.fromCharCode((d&15)<<12|(e&63)<<6|f&63),a+=3);return b},encode:function(c){var b="",a=0;for(c=d._utf8Encode(c);a<c.length;){var e=c.charCodeAt(a++);var f=c.charCodeAt(a++);var h=c.charCodeAt(a++);var k=e>>2;e=(e&3)<<4|f>>4;var n=(f&15)<<2|h>>6;var p=h&63;isNaN(f)?n=p=64:isNaN(h)&&(p=64);b=b+d._keyStr.charAt(k)+d._keyStr.charAt(e)+d._keyStr.charAt(n)+
d._keyStr.charAt(p)}return b},decode:function(c){var b="",a=0;for(c=c.replace(/[^A-Za-z0-9\+\/=]\./g,"");a<c.length;){var e=d._keyStr.indexOf(c.charAt(a++));var f=d._keyStr.indexOf(c.charAt(a++));var h=d._keyStr.indexOf(c.charAt(a++));var k=d._keyStr.indexOf(c.charAt(a++));e=e<<2|f>>4;f=(f&15)<<4|h>>2;var n=(h&3)<<6|k;b+=String.fromCharCode(e);64!=h&&(b+=String.fromCharCode(f));64!=k&&(b+=String.fromCharCode(n))}b=d._utf8Decode(b);return b.replace(/\0.*$/g,"")}};return d}()})(this);
(function(f){var e=Math.pow(2,31)-1;f.SymBfw.extensionAdapter=function(d){var c={},b=d.utils.isNil,a=d.utils.isntNil,g=d.utils.isString,f=d.utils.isInteger,h=d.utils.isFunction,k=d.utils.isArray,n=d.utils.isObject,p=d.utils.getValueAtPath;c.getLastError=function(){return chrome.runtime.lastError};c.getInvalidTabId=function(){return b(chrome)||b(chrome.tabs)?-1:chrome.tabs.TAB_ID_NONE};c.getExtensionId=function(){return chrome.runtime.id};c.isPrivateModeAllowed=function(){return new Promise(function(b){chrome.extension.isAllowedIncognitoAccess(function(a){b(a)})})};
c.getBackgroundPage=function(){return b(chrome)||b(chrome.extension)?null:chrome.extension.getBackgroundPage()};c.getExtensionURL=function(a){if(b(chrome)||b(chrome.extension))throw Error("chrome or chrome.extension is null");if(!g(a))throw Error("extensionAdapter.getExtensionURL expects a string path argument");return chrome.extension.getURL(a)};c.getAllWindows=function(a,c){if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!h(a))throw Error("invalid arguments to extensionAdapter.getAllWindows");
b(c)&&(c={});chrome.windows.getAll(c,a)};c.getCurrentWindow=function(a,c){if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!h(a))throw Error("invalid arguments to extensionAdapter.getAllWindows");b(c)&&(c={});chrome.windows.getCurrent(c,a)};c.createWindow=function(a,c,e){e=void 0===e?!0:e;if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");var l={};d.globals.BROWSER!==d.constants.BROWSER_TYPE.FIREFOX&&(l.focused=e);b(a)||
(l.url=a);chrome.windows.create(l,c)};c.createAppWindow=function(a,c){if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");var l={};l.type=chrome.windows.CreateType.PANEL;b(a)||(l.url=a);chrome.windows.create(l,c)};c.createPrivateWindow=function(a,c,d){d=void 0===d?!0:d;if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");d={incognito:!0,focused:d};b(a)||(d.url=a);chrome.windows.create(d,c)};c.closeWindow=function(a,c){if(b(chrome)||
b(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!f(a))throw Error("invalid arguments to extensionAdapter.closeWindow");chrome.windows.remove(a,c)};c.focusWindow=function(a,c){if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!f(a))throw Error("invalid arguments to extensionAdapter.focusWindow");chrome.windows.update(a,{focused:!0},c)};c.addWindowRemovedEventListener=function(a){if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");
if(!h(a))throw Error("extensionAdapter.addWindowRemovedEventListener needs a callback");chrome.windows.onRemoved.addListener(a)};c.addWindowFocusedEventListener=function(a){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.windows is null");if(!h(a))throw Error("extensionAdapter.addWindowFocusedEventListener needs a callback");chrome.windows.onFocusChanged.addListener(a)};c.getTab=function(a,c){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!f(a)||
!h(c))throw Error("invalid arguments to extensionAdapter.getTab");chrome.tabs.get(a,c)};c.detectLanguageByTabId=function(a){return function(a){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!f(a))throw Error("invalid arguments to extensionAdapter.detectLanguageByTabId");return!0}(a)&&h(chrome.tabs.detectLanguage)?new Promise(function(b,c){chrome.tabs.detectLanguage(a,function(a){b(a)})}):null};c.getActiveTab=function(a,c){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");
if(!h(a))throw Error("invalid arguments to extensionAdapter.getActiveTab");var d={active:!0};f(c)?d.windowId=c:d.currentWindow=!0;chrome.tabs.query(d,function(b){a(b[0])})};c.getAllTabs=function(a){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!h(a))throw Error("invalid arguments to extensionAdapter.getAllTabs");chrome.tabs.query({},a)};c.getTabsWithURL=function(a,c){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!g(a)||
!h(c))throw Error("invalid arguments to extensionAdapter.getTabsWithURL");chrome.tabs.query({url:a},c)};c.updateTabUrl=function(a,c,d){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!f(a)||!g(c))throw Error("invalid arguments to extensionAdapter.updateTabUrl");chrome.tabs.update(a,{url:c},d)};c.activateTab=function(a,c){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(b(a)||!f(a))throw Error("invalid arguments to extensionAdapter.activateTab");
chrome.tabs.update(a,{active:!0},c)};c.createTab=function(a,c,d){d=void 0===d?!0:d;if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");b(a)?chrome.tabs.create({},c):chrome.tabs.create({url:a,active:d},c)};c.closeTab=function(a,c){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!f(a)&&!k(a))throw Error("invalid arguments to extensionAdapter.closeTab");chrome.tabs.remove(a,c)};c.closeTabAndEnsureBrowserIsAlive=function(b,d){if(!f(b)||
0>=b||a(d)&&!h(d))throw Error("Invalid arguments to extensionAdapter.closeTabAndEnsureBrowserIsAlive()");c.getAllWindows(function(e){1===e.length?c.getAllTabs(function(e){1===e.length&&c.createTab();c.closeTab(b);a(d)&&d()}):(c.closeTab(b),a(d)&&d())})};c.addTabRemovedEventListener=function(a){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!h(a))throw Error("extensionAdapter.addTabRemovedEventListener needs a callback");chrome.tabs.onRemoved.addListener(a)};c.addTabActivatedEventListener=
function(a){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!h(a))throw Error("extensionAdapter.addTabActivatedEventListener needs a callback");chrome.tabs.onActivated.addListener(a)};c.addTabReplacedEventListener=function(a){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(b(a)||!h(a))throw Error("extensionAdapter.addTabReplacedEventListener needs a callback");chrome.tabs.onReplaced.addListener(a)};c.addTabUpdatedEventListener=
function(a){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!h(a))throw Error("extensionAdapter.addTabUpdatedEventListener needs a callback");chrome.tabs.onUpdated.addListener(a)};c.addOnBeforeRequestEventListener=function(a,c,d){if(b(chrome)||b(chrome.webRequest))throw Error("chrome is null or chrome.tabs is null");if(!1===h(a))throw Error("Callback cannot be null");chrome.webRequest.onBeforeRequest.addListener(a,{urls:c},d)};c.removeOnBeforeRequestEventListener=
function(a){chrome.webRequest.onBeforeRequest.removeListener(a)};c.setBrowserIcon=function(a,c){if(b(chrome)||b(chrome.browserAction))throw Error("chrome is null or chrome.browserAction is null");if(b(a))throw Error("invalid arguments to extensionAdapter.setBrowserIcon");chrome.browserAction.setIcon(a,c)};c.sendMessage=function(a,c){if(b(chrome)||b(chrome.runtime))throw Error("chrome or chrome.runtime is null");if(b(a))throw Error("invalid arguments to extensionAdapter.sendMessage");chrome.runtime.sendMessage(a,
c)};c.sendMessageExternal=function(a,c,d){if(b(chrome)||b(chrome.runtime))throw Error("chrome or chrome.runtime is null");if(b(a))throw Error("invalid arguments to extensionAdapter.sendMessage");if(b(c))throw Error("invalid arguments to extensionAdapter.sendMessage");chrome.runtime.sendMessage(a,c,d)};c.sendMessageToTab=function(a,c,d,e){if(b(chrome)||b(chrome.tabs))throw Error("chrome or chrome.tabs is null");if(b(c)||b(a))throw Error("invalid arguments to extensionAdapter.sendMessageToTab");chrome.tabs.sendMessage(a.id,
c,e,d)};c.sendMessageToParentFrame=function(a,d,e,g){if(b(d)||b(a))throw Error("invalid arguments to extensionAdapter.sendMessageToParentFrame");c.getFrame({tabId:a.id,frameId:g}).then(function(b){c.sendMessageToTab(a,d,e,{frameId:b.parentFrameId})})};c.addMessageListener=function(a){if(b(chrome)||b(chrome.runtime))throw Error("chrome or chrome.runtime is null");if(!h(a))throw Error("invalid arguments to extensionAdapter.addMessageListener");chrome.runtime.onMessage.addListener(function(b,c,d){return a(b,
d,c.tab,c.frameId,c.url)})};c.addMessageExternalListener=function(a){if(b(chrome)||b(chrome.runtime))throw Error("chrome or chrome.runtime is null");if(!h(a))throw Error("invalid arguments to extensionAdapter.addMessageExternalListener");chrome.runtime.onMessageExternal.addListener(function(b,c,d){return a(b,c,d)})};c.addContentScriptMessageListener=function(a){c.addMessageListener(a)};c.addTabCreatedEventListener=function(a){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");
if(!h(a))throw Error("extensionAdapter.\u200baddTabCreatedEventListener needs a callback");chrome.tabs.onCreated.addListener(a)};c.addWindowCreatedEventListener=function(a){if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!h(a))throw Error("extensionAdapter.\u200baddWindowCreatedEventListener needs a callback");chrome.windows.onCreated.addListener(a)};c.getFrame=function(a){var c=null,d={errorOccured:!0,url:null,parentFrameId:null};if(b(chrome)||b(chrome.webNavigation))throw Error("no chrome object available");
a&&(c=b(a.frameId)?new Promise(function(a){a(d)}):new Promise(function(b){chrome.webNavigation.getFrame(a,function(a){b(a)})}));return c};c.getTabID=function(a){return b(a)?null:a.id};c.getWindowIDForTab=function(a){return b(a)?null:a.windowId};c.getWindowID=function(a){return b(a)?null:a.id};c.i18nGetMessage=function(a,c){if(b(window.chrome)||b(window.chrome.i18n))throw Error("Unsupported api");if(!g(a))throw Error("chrome.i18n.getMessage expects a string messageName argument");return chrome.i18n.getMessage(a,
c)};c.hidePopup=function(){window.open("","_self").close()};c.setBadgeText=function(c,d){if(b(chrome)||b(chrome.browserAction))throw Error("chrome or chrome.browserAction is null");if(!g(c)||4<c.length)throw Error("invalid arguments to extensionAdapter.setBadgeText");c={text:c};a(d)&&(c.tabId=d);chrome.browserAction.setBadgeText(c)};c.setTitle=function(c,d){if(b(chrome)||b(chrome.browserAction))throw Error("chrome or chrome.browserAction is null");if(!g(c))throw Error("invalid arguments to extensionAdapter.setTitle");
c={title:c};a(d)&&(c.tabId=d);chrome.browserAction.setTitle(c)};c.setBadgeBackgroundColor=function(a){if(b(chrome)||b(chrome.browserAction))throw Error("chrome or chrome.browserAction is null");if(!g(a))throw Error("invalid arguments to extensionAdapter.setBadgeBackgroundColor");chrome.browserAction.setBadgeBackgroundColor({color:a})};c.onPopoverLoad=function(a){window.addEventListener("load",a)};c.getAllHistory=function(a){a=void 0===a?"":a;return new Promise(function(b){chrome.history.search({text:a,
startTime:0,maxResults:e},function(a){var c=[];a=$jscomp.makeIterator(a);for(var d=a.next();!d.done;d=a.next())d=d.value,g(d.url)&&c.push(d.url);b(c)})})};c.addUrlsToHistory=function(a){if(!k(a))throw Error("urls must be an array");var b=[];a=$jscomp.makeIterator(a);for(var d=a.next();!d.done;d=a.next())b.push(c.addUrlToHistory(d.value));return Promise.all(b)};c.clearHistory=function(){return new Promise(function(a){chrome.history.deleteAll(function(){a()})})};c.addUrlToHistory=function(a){if(!g(a))throw Error("url must be a string");
return new Promise(function(b){chrome.history.addUrl({url:a},function(){b()})})};c.getAllCookies=function(a){a=void 0===a?null:a;return new Promise(function(b){chrome.cookies.getAll({domain:a},function(a){b(a)})})};c.removeCookie=function(a){if(b(a))throw Error("cookie cannot be null");var c=(a.secure?"https://":"http://")+a.domain+a.path;return new Promise(function(d,e){chrome.cookies.remove({name:a.name,url:c},function(a){b(a)&&e(chrome.runtime.lastError);d(a)})})};c.removeCookies=function(a){if(!k(a))throw Error("cookiesArray must be array");
var b=[];a=$jscomp.makeIterator(a);for(var d=a.next();!d.done;d=a.next())b.push(c.removeCookie(d.value));return Promise.all(b)};c.setCookie=function(c){if(b(c))throw Error("cookie cannot be null");var d={url:(new URL((c.secure?"https://":"http://")+c.domain)).toString(),httpOnly:c.httpOnly,name:c.name,sameSite:c.sameSite,secure:c.secure,storeId:c.storeId,value:c.value,path:c.path};g(c.domain)&&"."===c.domain.charAt()&&(d.domain=c.domain);a(c.expirationDate)&&(d.expirationDate=c.expirationDate);return new Promise(function(c,
e){chrome.cookies.set(d,function(d){var g=chrome.runtime.lastError;b(d)&&a(g)&&e(g);c(d)})})};c.setCookies=function(a){if(!k(a))throw Error("cookiesArray must be array");var b=[];a=$jscomp.makeIterator(a);for(var d=a.next();!d.done;d=a.next())b.push(c.setCookie(d.value));return Promise.all(b)};c.onCookieChangedForUrl=function(a,b){if(!g(a))throw Error("url must be a string");if(!h(b))throw Error("callback must be a function");chrome.cookies.onChanged.addListener(function(c){var d=p(c,"cookie.domain");
g(d)&&d.includes(a)?b(c):b()})};c.checkCookieContentSettingsForUrl=function(a){if(b(chrome)||b(chrome.contentSettings))throw Error("Unsupported api");if(!g(a))throw Error("primaryUrl must be a string");return new Promise(function(b,c){chrome.contentSettings.cookies.get({primaryUrl:a},function(a){a.setting===chrome.contentSettings.CookiesContentSetting.ALLOW?b():c()})})};c.getVersion=function(){return chrome.runtime.getManifest().version};c.setProxySettings=function(a){if(b(chrome)||b(chrome.proxy))throw Error("Unsupported api");
if(!n(a))throw Error("details must be an object");return new Promise(function(b){chrome.proxy.settings.set(a,b)})};c.getProxySettings=function(){if(b(chrome)||b(chrome.proxy))throw Error("Unsupported api");return new Promise(function(a){chrome.proxy.settings.get({},a)})};c.onProxySettingsChange=function(a){if(b(chrome)||b(chrome.proxy))throw Error("Unsupported api");if(!h(a))throw Error("callback must be a function");chrome.proxy.settings.onChange.addListener(a)};c.onProxyError=function(a){if(b(chrome)||
b(chrome.proxy))throw Error("Unsupported api");if(!h(a))throw Error("callback must be a function");chrome.proxy.onProxyError.addListener(a)};c.onWebRequestAuthRequired=function(a){if(b(chrome)||b(chrome.webRequest))throw Error("Unsupported api");if(!h(a))throw Error("callback must be a function");chrome.webRequest.onAuthRequired.addListener(a,{urls:["<all_urls>"]},["asyncBlocking"])};c.init=function(){};c.returnAdapter=function(){var a={};a.getExtensionURL=c.getExtensionURL;a.getBackgroundPage=c.getBackgroundPage;
a.sendMessage=c.sendMessage;a.addMessageListener=c.addMessageListener;a.addContentScriptMessageListener=c.addContentScriptMessageListener;a.getExtensionId=c.getExtensionId;a.init=c.init;try{return chrome.tabs?c:a}catch(q){return a}};return c.returnAdapter()}(f.SymBfw)})(this);
(function(f){f.SymBfw.clipboard=function(e){var d={},c=e.utils.isNil,b=e.logger;d.createDummyTextAreaAndSetText=function(a){var b=document.createElement("textarea");b.style.position="fixed";b.style.top=0;b.style.left=0;b.style.width="2em";b.style.height="2em";b.style.padding=0;b.style.border="none";b.style.outline="none";b.style.boxShadow="none";b.style.background="transparent";b.value=a;document.body.appendChild(b);b.select();return b};d.copyToClipboard=function(a){if(c(a)||""===a)throw Error("Value to copy to clipboard cannot be null");
a=d.createDummyTextAreaAndSetText(a);document.execCommand("copy")||b.error("Failed to copy to clipboard");document.body.removeChild(a)};return d}(f.SymBfw)})(this);
(function(f){f.SymBfw.localizerProxy=function(e){var d=e.utils.isNil,c=e.utils.isFunction,b=e.constants.localizer,a={getLocalizedString:function(c,d){a.sendMessage(b.GET_LOCALIZED_STRING,c,d)},getLocalizedStrings:function(c,d){a.sendMessage(b.GET_LOCALIZED_STRINGS,c,d)},getAllLocalizedStrings:function(c){a.sendMessage(b.GET_ALL_LOCALIZED_STRINGS,{},c)},getLocalizedStringFromDictionary:function(c,d,e){a.sendMessage(b.GET_LOCALIZED_STRING_FROM_DICTIONARY,{string:c,name:d},e)},getLocalizedStringsFromDictionary:function(c,
d,e){a.sendMessage(b.GET_LOCALIZED_STRINGS_FROM_DICTIONARY,{array:c,name:d},e)},getLocalizedStringsWithFormat:function(c,d){a.sendMessage(b.GET_LOCALIZED_STRINGS_WITH_FORMAT,{formatStringDict:c},d)},getLocalizedStringWithFormat:function(c,d,e){a.sendMessage(b.GET_LOCALIZED_STRING_WITH_FORMAT,{string:c,params:d},e)},getLocalizedStringWithFormatFromDictionary:function(c,d,e,f){a.sendMessage(b.GET_LOCALIZED_STRING_WITH_FORMAT_FROM_DICTIONARY,{string:c,params:d,name:e},f)},getCurrentLanguageDirection:function(c){a.sendMessage(b.GET_CURRENT_LANGUAGE_DIRECTION,
{},c)},sendMessage:function(a,f,h){if(d(a))throw Error("Message ID cannot be null");if(d(f))throw Error("Payload cannot be null");if(!1===c(h))throw Error("Callback cannot be null");e.extensionAdapter.sendMessage({id:a,payload:f},function(a){switch(a.id){case b.GET_LOCALIZED_STRING:case b.GET_LOCALIZED_STRINGS:case b.GET_ALL_LOCALIZED_STRINGS:case b.GET_LOCALIZED_STRING_FROM_DICTIONARY:case b.GET_LOCALIZED_STRINGS_FROM_DICTIONARY:case b.GET_LOCALIZED_STRING_WITH_FORMAT:case b.GET_LOCALIZED_STRING_WITH_FORMAT_FROM_DICTIONARY:case b.GET_CURRENT_LANGUAGE_DIRECTION:case b.GET_LOCALIZED_STRINGS_WITH_FORMAT:h(a.payload)}})}};
return a}(f.SymBfw)})(this);
(function(f){f=f.SymBfw=f.SymBfw||{};var e={APPLICATION_NAME:"APPLICATION_NAME",APPLICATION_VERSION:"APPLICATION_VERSION",CLIENT_ID:"CLIENT_ID",DATA_SOURCE:"DATA_SOURCE",TRACKING_ID:"TRACKING_ID",USER_AGENT:"USER_AGENT",USER_LANGUAGE:"USER_LANGUAGE",GOOGLE_ANALYTICS_PROTOCOL_VERSION:"GOOGLE_ANALYTICS_PROTOCOL_VERSION",ANONYMIZE_IP:"ANONYMIZE_IP"};e.defaultParametersList=[e.APPLICATION_NAME,e.APPLICATION_VERSION,e.CLIENT_ID,e.DATA_SOURCE,e.TRACKING_ID,e.GOOGLE_ANALYTICS_PROTOCOL_VERSION,e.ANONYMIZE_IP];
e.dataSource={BROWSER_EXTENSION:"web",MOBILE_APP:"app"};e.HIT_TYPE={PAGE_VIEW:"pageview",SCREEN_VIEW:"screenview",EVENT:"event",EXCEPTION:"exception"};e.MESSAGES={SEND_TELEMETRY_TO_BGPROXY:"b021e29a-4fe3-4a60-865f-0cf783318187"};e.parameters={NON_INTERACTION_HIT:"ni",HIT_TYPE:"t",CATEGORY:"ec",ACTION:"ea",LABEL:"el",DOCUMENT_PATH:"dp",DOCUMENT_TITLE:"dt",CUSTOM_DIMENSION1:"cd1",PRODUCT_IMPRESSION_BRAND1:"il1pi1br",ITEM_CATEGORY:"iv",CAMPAIGN_SOURCE:"cs",CAMPAIGN_MEDIUM:"cm"};e.TELEMETRY_CATEGORY=
{BROWSER:"Browser",EXTENSION:"Extension"};e.actionType={BROWSER:{LAUNCH:"launch",UPDATE:"update"},EXTENSION:{INSTALL:"install",UPDATE:"update"}};e.defaultParameters={APPLICATION_NAME:{maxLength:100,key:"an"},APPLICATION_VERSION:{maxLength:100,key:"av"},CLIENT_ID:{maxLength:100,key:"cid"},DATA_SOURCE:{maxLength:50,key:"ds",value:e.dataSource.BROWSER_EXTENSION},TRACKING_ID:{maxLength:100,key:"tid"},USER_AGENT:{maxLength:1E3,key:"ua"},USER_LANGUAGE:{maxLength:20,key:"ul"},GOOGLE_ANALYTICS_PROTOCOL_VERSION:{maxLength:100,
key:"v",value:1},ANONYMIZE_IP:{maxLength:1,key:"aip",value:1}};f.telemetryConstants=e})(this);(function(f){f.SymBfw.telemetryProxy=function(e){var d=e.utils.isNil,c=e.telemetryConstants;return{send:function(b){if(d(b))throw Error("parameters cannot be null");e.extensionAdapter.sendMessage({id:c.MESSAGES.SEND_TELEMETRY_TO_BGPROXY,payload:{parameters:b}})}}}(f.SymBfw)})(this);
(function(f){f=f.SymBfw=f.SymBfw||{};var e={APPLICATION_NAME:"APPLICATION_NAME",APPLICATION_VERSION:"APPLICATION_VERSION",DATA_SOURCE:"DATA_SOURCE",USER_LANGUAGE:"USER_LANGUAGE",TOKEN:"TOKEN",CLIENT_ID:"CLIENT_ID"};e.defaultParametersList=[e.APPLICATION_NAME,e.APPLICATION_VERSION,e.DATA_SOURCE];e.dataSource={BROWSER_EXTENSION:"web",MOBILE_APP:"app"};e.HIT_TYPE={PAGE_VIEW:"pageview",SCREEN_VIEW:"screenview",EVENT:"event",EXCEPTION:"exception"};e.MESSAGES={SEND_TELEMETRY_TO_V2PROXY:"3fd353b0-319d-41f3-b3a3-22e893730e65"};
e.parameters={NON_INTERACTION_HIT:"ni",HIT_TYPE:"t",ACTION:"ea",LABEL:"el",DOCUMENT_PATH:"dp",DOCUMENT_TITLE:"dt",CUSTOM_DIMENSION1:"cd1",PRODUCT_IMPRESSION_BRAND1:"il1pi1br",ITEM_CATEGORY:"iv",CAMPAIGN_SOURCE:"cs",CAMPAIGN_MEDIUM:"cm"};e.TELEMETRY_CATEGORY={BROWSER:"Browser",EXTENSION:"Extension"};e.actionType={BROWSER:{LAUNCH:"launch",UPDATE:"update"},EXTENSION:{INSTALL:"install",UPDATE:"update"}};e.defaultParameters={APPLICATION_NAME:{maxLength:100,key:"app_name"},APPLICATION_VERSION:{maxLength:100,
key:"app_version"},DATA_SOURCE:{maxLength:50,key:"data_source",value:e.dataSource.BROWSER_EXTENSION},USER_LANGUAGE:{maxLength:20,key:"user_language"}};f.telemetryV2Constants=e})(this);(function(f){f.SymBfw.telemetryV2Proxy=function(e){var d=e.utils.isNil,c=e.telemetryV2Constants;return{send:function(b,a){if(d(b))throw Error("event cannot be null");e.extensionAdapter.sendMessage({id:c.MESSAGES.SEND_TELEMETRY_TO_V2PROXY,payload:{event:b,parameters:a}})}}}(f.SymBfw)})(this);
(function(f){f.SymBfw.telemetryWrapper=function(e){var d=e.utils.isNil,c=e.utils.isString,b={TELEMETRY_CATEGORY:"bfw",TELEMETRY_TYPE:"event",componentType:{LOGGER:"logger",LOCALIZER:"localizer",STORAGE:"storage",SETTINGS:"settings",SECURE_SETTINGS:"secureSettings"},actionType:{WARN:"warn",ERROR:"error"},parameters:{EVENT:"t",CATEGORY:"ec",ACTION:"ea",PAYLOAD:"el"},send:function(a,f,m){if(!c(a))throw Error("componentType should be a string");if(!c(f))throw Error("actionType should be a string");if(d(m))throw Error("payload should not be Nil");
if(!c(m)){if(!(m instanceof Error))throw Error("payload should be an instanceof Error other than a string");m=m.toString()}var g={};g[b.parameters.EVENT]=b.TELEMETRY_TYPE;g[b.parameters.CATEGORY]=b.TELEMETRY_CATEGORY+"-"+a;g[b.parameters.ACTION]=f;g[b.parameters.PAYLOAD]=m;return(e.telemetry||e.telemetryProxy).send(g)}};return b}(f.SymBfw)})(this);
(function(f){var e={},d=SymBfw.utils.isntNil,c=SymBfw.utils.isNil,b=SymBfw.localizerProxy,a=SymBfw.constants.uiConstants;e.direction="ltr";e.updateFrameSizeAndLocation=function(a,b,e,f){a=document.getElementById(a);c(a)||(d(e)&&a.setAttribute("width",e),d(b)&&a.setAttribute("height",b),d(f)&&a.setAttribute("style","left:"+f.left+"px;top:"+f.top+"px;"))};e.createFrame=function(a,c,f,k,n){b.getCurrentLanguageDirection(function(b){e.direction=b;var g=document.createElement("IFRAME");g.setAttribute("id",
a);g.setAttribute("src",c);g.setAttribute("class","symc-notification-hide");g.setAttribute("frameBorder",0);g.setAttribute("dir",b);d(k)&&g.setAttribute("width",k);d(f)&&g.setAttribute("height",f);d(n)&&g.setAttribute("style","left:"+n.left+"px;top:"+n.top+"px;");document.documentElement.appendChild(g);g.addEventListener("load",function(){"symc-in-page-popup"!==g.getAttribute("id")&&g.setAttribute("class","symc-notification-show")})})};e.getDirection=function(){return e.direction};e.injectStyle=function(b){var c=
document.documentElement,e=document.getElementById(a.CONTENT_PAGE_STYLE_ID);d(e)&&c.removeChild(e);e=document.createElement("LINK");e.setAttribute("id",a.CONTENT_PAGE_STYLE_ID);e.setAttribute("rel","stylesheet");e.setAttribute("href",b);c.appendChild(e)};e.isPageRTL=function(a){for(;d(a);){var b=a.getAttribute("dir");if(d(b)&&"rtl"===b)return!0;a=a.parentElement}return!1};e.isTopLevelWindow=function(){return window===window.top?!0:!1};f.SymBfw.uiUtils=e})(this);
(function(f){f.SymBfw.performanceReporterFactoryProxy=function(e){var d=e.utils.isNil,c=e.extensionAdapter,b=e.constants.performanceReporter.MESSAGES,a={AUTOMATION_MODE:!1,reportStart:function(c,d){a.sendMessage(b.REPORT_START,{component:c,type:d})},reportEnd:function(c,d){a.sendMessage(b.REPORT_END,{component:c,type:d})},sendMessage:function(b,f){if(!1!==a.AUTOMATION_MODE){if(d(b))throw Error("messageID cannot be null");if(d(f))throw Error("payload cannot be null");d(this._frameGUID)&&(this._frameGUID=
e.utils.createNewGuid());f.guid=this._frameGUID;f.frameURL=document.URL;c.sendMessage({id:b,payload:f})}}};return a}(f.SymBfw)})(this);
