(function(b){b=b.FG=b.FG||{};var a={page_process_timeout:1E3,add_dock_timeout:200,add_ui_elements_timeout:250,remove_popup_timeout:2E3,iframe_post_timeout:100,add_dock_interval:125,add_dock_max_timeout:5E3,phishing_category_id:18,webmail_category_id:52,social_networking_id:55,financial_category_id:31,trading_category_id:32,uncategorized:90,default_risk_threshold_value:5,minimum_risk_threshold_value:1,response_success:100,response_failure:101,dock_start_minimized:!0,dock_show_always:!1,max_urls_per_request:30,
beta:!1,url_markup_default_state:!0,max_banking_prompts_default:3,max_banking_prompts_perpetual:999999,max_rate_limit_isolation_requests_OB:100,max_rate_limit_isolation_api:1E4,max_rate_limit_reset_interval:36E5,settings_key:{}};a.settings_key.root="c74e3142-5342-44b1-b7b3-a32d80a55ca6";a.settings_key.url_markup="0f7aae85-cb4c-4991-90b7-4c27b8e7f69c";a.settings_key.online_banking="45e41ff5-6c11-4e5e-b5fd-8715b1d1a190";a.settings_key.online_banking_session_override="023b1a5d-1753-4ce9-9cff-f0bf54252b4b";
a.settings_key.sign_in_flow_origin="b9016546-d9a3-4850-a097-3e34508bad22";a.settings_key.scan_notification="796e1dda-4c45-4bb9-bf71-57d26c523923";a.settings_key.dock_timeout="f4fe49e3-90d2-4f93-97b9-c0d3de82364d";a.settings_key.use_modal="cade52d7-ae9f-44bd-b529-fd10d47ea0b1";a.settings_key.lg_sign_in_not_required_mode="643463ce-b557-429f-98ae-3577dec0b207";a.settings_key.feature_ui_configs_file_id="6bc2c7b7-8819-462d-acb5-9299bd908e26";a.settings_key.feature_ui_config_id="13e0849c-ef78-476d-b617-202654da8c6c";
a.settings_key.max_banking_prompts="d8cc1e97-a6a2-4a7d-9479-fdd8e4684f68";a.settings_key.banking_prompts_count="e165face-77cf-43eb-bb7d-3265ccd27ebf";a.settings_key.banking_sites="0b9a806d-9954-4e57-85b3-96b00d54d548";a.settings_key.ratelimit_runtime_count="b0fcd033-4be1-4b67-b59f-ce17d2935a99";a.settings_key.ratelimit_max_tries="38088dd1-21cc-444a-ad0c-fb4ac17740a0";a.settings_key.ratelimit_runtime_count_OB="0464e166-cd8e-46cb-8237-10a3e491fa44";a.settings_key.ratelimit_max_tries_OB="96d96c1c-6493-44ae-bc79-936c803a6710";
a.settings_key.ratelimit_reset_interval="7a3a2967-cb2c-453a-a61e-43764fbf5691";a.settings_key.dock_start_minimized="67733cb0-77de-41b7-9aa8-8e31a915758e";a.settings_key.dock_show_always="47258e7e-72e6-468e-809b-6f09dfb349a8";a.debug=!1;a.active_everywhere=!1;a.standalone=!1;a.staging=!1;a.sign_in_not_required_mode=!0;a.enable_online_banking=!0;a.only_whitelisted_banking_sites=!0;a.keyword_isolation_url="email-isolation.prod.fire.glass";a.keyword_isolation_url_norton_specific="isolate.norton.com";
a.telemetry={};a.telemetry.TRACKING_ID="__FG_TRACKING_ID__";a.telemetry.SEND_PING="{04EFD197-5D63-43D6-A225-8E78B2514584}";a.telemetry.ping={};a.telemetry.ping.RatingsQuery={TOP_URL:"a",SCANNED_URLS:"b",BAD_URLS:"c",UNKNOWN_URLS:"d"};a.telemetry.ping.IsolationLaunch={TOP_URL:"a",ISOLATION_URL:"b",OPT_OUT:"c"};a.telemetry.ping.IsolationUsage={URL:"a",USE_TIME:"b",NAVIGATION_COMPLETE:"c",IDLE_TIME:"d",CLICK_COUNT:"e",KEY_COUNT:"f"};a.help_ids={SAFEMODE_01:10001,SAFEMODE_02:10002};a.notifications={};
a.notifications.type={pageScanNotification:0};a.uiMessageProxy={};a.uiMessageProxy.EVENT_ID="{d3034228-f99f-459e-b971-6bd8e702e59b}";a.docControls={};a.docControls.EVENT_ID="{444eb5be-50bc-4d68-a133-d92d34de1ef6}";a.dialogRenderer={};a.dialogRenderer.EVENT_ID="{6400d87a-4919-47af-b243-b162194be77d}";a.dialogRendererProxy={};a.dialogRendererProxy.EVENT_ID="{87e8946f-b2eb-4776-9f09-5a3fe39c848e}";a.safeModeDialog={};a.safeModeDialog.EVENT_ID="{22bc9f72-b437-4745-812d-4ee3f3e41fc4}";a.dockMouseEvent=
{};a.dockMouseEvent.EVENT_ID="{50d7ef15-de29-4ea9-8268-99cd06288eb3}";a.dockMouseEvent.eventType={mouseEnter:0,mouseLeave:1,mouseOverFaq:2,click:3,close:4};a.dockPopupEvent={};a.dockPopupEvent.EVENT_ID="{4ebf0520-614e-4af2-b2c2-200ec3a63d18}";a.dockPopupEvent.eventType={show:0,hide:1,close:2};a.dockResourceEvent={};a.dockResourceEvent.EVENT_ID="{9a0c0b88-4dfe-4451-ba67-d73a636e1a92}";a.dockResourceEvent.eventType={unload:0};a.safeModeDialog.dialogType={threatIsolation:0,onlineBanking:1};a.safeModeDialog.dialogMode=
{signin:0,interstitial:1};a.safeModeDialog.displayState={hide:0,show:1};a.dockConfig={};a.dockConfig.sslStatus={insecure:0,secure:1};a.dockConfig.urlCategory={general:0,onlineBanking:1};a.dockConfig.trigger={onDemand:0,prompt:1};a.onlineBanking={Isolation_State:{On:0,Off:1,Prompt:2}};a.strings={};a.strings.dictionary="fg_strings";a.strings.security_popup={fg_security_header_text:"SUSPICIOUS LINK",fg_popup_description_text:"Norton now warns you of suspicious links in your email to protect you from malicious activity."};
a.strings.dock={fg_leavefeedback_text:"Leave Feedback",fgdock_signin:"Try this feature"};a.strings.banking_protection_disabled={message_text:"Banking Protection Disabled"};a.strings.banking_protection_enabled={message_text:"Banking Protection Enabled"};a.strings.isolation_mode_enabled={message_text:"You're browsing safely in Isolation Mode"};a.strings.faq_popup={fg_faq_msg:"Provides additional security for online transactions and helps keep your financial information and other personal data away from hackers.",
fg_faq_msg_signed_in:"Provides additional security for online transactions and helps keep your financial information and other personal data away from hackers. You can turn this feature off in",help:"Learn More",help_signed_in:"Settings"};a.strings.safemode_dialog={fg_desc_title:"If you visit this site...",fg_desc_isolation_summary:"Isolation Mode",fg_desc_isolation_text:"provides additional protection when visiting risky websites that may contain malware or browser exploits.",help:"Learn More",fg_signin_message:"Sign in to your Norton account to enable Isolation Mode.",
footer_link:"Continue Without Isolation Mode",fg_signin_btn_text:"Sign In",fg_continue_btn_text:"Continue",fg_cancel_btn_text:"Cancel",fg_leavefeedback_text:"Leave Feedback",fg_desc_title_banking:"Banking Protection",fg_desc_banking_protection_summary:"Isolation Mode",fg_desc_banking_protection_text:"provides additional security for online transactions and helps keep your financial information and other personal data away from hackers.",fg_signin_message_2:"Sign in to your Norton account to enable Isolation Mode.",
help_2:"Learn More",fg_settings_this_website:"Remember for this website",fg_settings_all_websites:"Remember for all banking websites"};a.strings.page_scan_notification={title:"",description:"We\u2019ll highlight suspicious links in Webmail, Facebook, Twitter and other accounts.",learn_more:"Learn More",ok_button:"OK"};a.default_country="US";a.site_redirector_url="http://sitedirector.symantec.com/932743328?ssdcat=SSDCAT_VALUE&env=prod&origin=nsss&displang=iso3:ISO3_LAN_CODE&displocale=iso3:ISO3_COUNTRY_CODE";
a.ISO2_2_ISO3_lang={AB:"ABK",AA:"AAR",AF:"AFR",AK:"AKA",SQ:"SQI",AM:"AMH",AR:"ARA",AN:"ARG",HY:"HYE",AS:"ASM",AV:"AVA",AE:"AVE",AY:"AYM",AZ:"AZE",BM:"BAM",BA:"BAK",EU:"EUS",BE:"BEL",BN:"BEN",BH:"BIH",BI:"BIS",BS:"BOS",BR:"BRE",BG:"BUL",MY:"MYA",CA:"CAT",CH:"CHA",CE:"CHE",NY:"NYA",ZH:"ZHO",CV:"CHV",KW:"COR",CO:"COS",CR:"CRE",HR:"HRV",CS:"CES",DA:"DAN",DV:"DIV",NL:"NLD",DZ:"DZO",EN:"ENG",EO:"EPO",ET:"EST",EE:"EWE",FO:"FAO",FJ:"FIJ",FI:"FIN",FR:"FRA",FF:"FUL",GL:"GLG",KA:"KAT",DE:"DEU",EL:"ELL",GN:"GRN",
GU:"GUJ",HT:"HAT",HA:"HAU",HE:"HEB",HZ:"HER",HI:"HIN",HO:"HMO",HU:"HUN",IA:"INA",ID:"IND",IE:"ILE",GA:"GLE",IG:"IBO",IK:"IPK",IO:"IDO",IS:"ISL",IT:"ITA",IU:"IKU",JA:"JPN",JV:"JAV",KL:"KAL",KN:"KAN",KR:"KAU",KS:"KAS",KK:"KAZ",KM:"KHM",KI:"KIK",RW:"KIN",KY:"KIR",KV:"KOM",KG:"KON",KO:"KOR",KU:"KUR",KJ:"KUA",LA:"LAT",LB:"LTZ",LG:"LUG",LI:"LIM",LN:"LIN",LO:"LAO",LT:"LIT",LU:"LUB",LV:"LAV",GV:"GLV",MK:"MKD",MG:"MLG",MS:"MSA",ML:"MAL",MT:"MLT",MI:"MRI",MR:"MAR",MH:"MAH",MN:"MON",NA:"NAU",NV:"NAV",ND:"NDE",
NE:"NEP",NG:"NDO",NB:"NOB",NN:"NNO",NO:"NOR",II:"III",NR:"NBL",OC:"OCI",OJ:"OJI",CU:"CHU",OM:"ORM",OR:"ORI",OS:"OSS",PA:"PAN",PI:"PLI",FA:"FAS",PL:"POL",PS:"PUS",PT:"POR",QU:"QUE",RM:"ROH",RN:"RUN",RO:"RON",RU:"RUS",SA:"SAN",SC:"SRD",SD:"SND",SE:"SME",SM:"SMO",SG:"SAG",SR:"SRP",GD:"GLA",SN:"SNA",SI:"SIN",SK:"SLK",SL:"SLV",SO:"SOM",ST:"SOT",ES:"SPA",SU:"SUN",SW:"SWA",SS:"SSW",SV:"SWE",TA:"TAM",TE:"TEL",TG:"TGK",TH:"THA",TI:"TIR",BO:"BOD",TK:"TUK",TL:"TGL",TN:"TSN",TO:"TON",TR:"TUR",TS:"TSO",TT:"TAT",
TW:"TWI",TY:"TAH",UG:"UIG",UK:"UKR",UR:"URD",UZ:"UZB",VE:"VEN",VI:"VIE",VO:"VOL",WA:"WLN",CY:"CYM",WO:"WOL",FY:"FRY",XH:"XHO",YI:"YID",YO:"YOR",ZA:"ZHA",ZU:"ZUL"};a.ISO2_2_ISO3_locale={AX:"ALA",AF:"AFG",AL:"ALB",DZ:"DZA",AS:"ASM",AD:"AND",AO:"AGO",AI:"AIA",AQ:"ATA",AG:"ATG",AR:"ARG",AM:"ARM",AW:"ABW",AU:"AUS",AT:"AUT",AZ:"AZE",BS:"BHS",BH:"BHR",BD:"BGD",BB:"BRB",BY:"BLR",BE:"BEL",BZ:"BLZ",BJ:"BEN",BM:"BMU",BT:"BTN",BO:"BOL",BA:"BIH",BW:"BWA",BV:"BVT",BR:"BRA",IO:"IOT",BN:"BRN",BG:"BGR",BF:"BFA",BI:"BDI",
KH:"KHM",CM:"CMR",CA:"CAN",CV:"CPV",KY:"CYM",CF:"CAF",TD:"TCD",CL:"CHL",CN:"CHN",CX:"CXR",CC:"CCK",CO:"COL",KM:"COM",CD:"COD",CG:"COG",CK:"COK",CR:"CRI",CI:"CIV",HR:"HRV",CU:"CUB",CY:"CYP",CZ:"CZE",DK:"DNK",DJ:"DJI",DM:"DMA",DO:"DOM",EC:"ECU",EG:"EGY",SV:"SLV",GQ:"GNQ",ER:"ERI",EE:"EST",ET:"ETH",FK:"FLK",FO:"FRO",FJ:"FJI",FI:"FIN",FR:"FRA",GF:"GUF",PF:"PYF",TF:"ATF",GA:"GAB",GM:"GMB",GE:"GEO",DE:"DEU",GH:"GHA",GI:"GIB",GR:"GRC",GL:"GRL",GD:"GRD",GP:"GLP",GU:"GUM",GT:"GTM",GN:"GIN",GW:"GNB",GY:"GUY",
HT:"HTI",HM:"HMD",HN:"HND",HK:"HKG",HU:"HUN",IS:"ISL",IN:"IND",ID:"IDN",IR:"IRN",IQ:"IRQ",IE:"IRL",IL:"ISR",IT:"ITA",JM:"JAM",JP:"JPN",JO:"JOR",KZ:"KAZ",KE:"KEN",KI:"KIR",KP:"PRK",KR:"KOR",KW:"KWT",KG:"KGZ",LA:"LAO",LV:"LVA",LB:"LBN",LS:"LSO",LR:"LBR",LY:"LBY",LI:"LIE",LT:"LTU",LU:"LUX",MO:"MAC",MK:"MKD",MG:"MDG",MW:"MWI",MY:"MYS",MV:"MDV",ML:"MLI",MT:"MLT",MH:"MHL",MQ:"MTQ",MR:"MRT",MU:"MUS",YT:"MYT",MX:"MEX",FM:"FSM",MD:"MDA",MC:"MCO",MN:"MNG",MS:"MSR",MA:"MAR",MZ:"MOZ",MM:"MMR",NA:"NAM",NR:"NRU",
NP:"NPL",NL:"NLD",AN:"ANT",NC:"NCL",NZ:"NZL",NI:"NIC",NE:"NER",NG:"NGA",NU:"NIU",NF:"NFK",MP:"MNP",NO:"NOR",OM:"OMN",PK:"PAK",PW:"PLW",PS:"PSE",PA:"PAN",PG:"PNG",PY:"PRY",PE:"PER",PH:"PHL",PN:"PCN",PL:"POL",PT:"PRT",PR:"PRI",QA:"QAT",RE:"REU",RO:"ROU",RU:"RUS",RW:"RWA",SH:"SHN",KN:"KNA",LC:"LCA",PM:"SPM",VC:"VCT",WS:"WSM",SM:"SMR",ST:"STP",SA:"SAU",SN:"SEN",CS:"SCG",SC:"SYC",SL:"SLE",SG:"SGP",SK:"SVK",SI:"SVN",SB:"SLB",SO:"SOM",ZA:"ZAF",GS:"SGS",ES:"ESP",LK:"LKA",SD:"SDN",SR:"SUR",SJ:"SJM",SZ:"SWZ",
SE:"SWE",CH:"CHE",SY:"SYR",TW:"TWN",TJ:"TJK",TZ:"TZA",TH:"THA",TL:"TLS",TG:"TGO",TK:"TKL",TO:"TON",TT:"TTO",TN:"TUN",TR:"TUR",TM:"TKM",TC:"TCA",TV:"TUV",UG:"UGA",UA:"UKR",AE:"ARE",GB:"GBR",US:"USA",UM:"UMI",UY:"URY",UZ:"UZB",VU:"VUT",VA:"VAT",VE:"VEN",VN:"VNM",VG:"VGB",VI:"VIR",WF:"WLF",EH:"ESH",YE:"YEM",ZM:"ZMB",ZW:"ZWE"};a.ssdcat="310";a.helpid="&helpid=webisolation";a.helpid_url_markup="&helpid=suspiciouslink";a.helpid_online_banking="&helpid=onlinebanking";a.leave_feedback_link="https://feedback.norton.com/pfb/pFeedback.aspx?products=webisolation";
a.leave_feedback_link_OB="https://feedback.norton.com/pfb/pFeedback_form.aspx?products=onlinebanking";a.feature_type={invalid:0,link_guard:1,block_page:2,online_banking:3};a.kill_location="https://branding.symantec.com/upgrade/WEBISOLATION/KFG22.txt";a.kill_location_LG="https://branding.symantec.com/upgrade/WEBISOLATION/KLG22.txt";a.kill_location_BP="https://branding.symantec.com/upgrade/WEBISOLATION/KBP22.txt";a.kill_location_OB="https://branding.symantec.com/upgrade/WEBISOLATION/KOB22.txt";a.feature_ui_configs_location=
"https://branding.symantec.com/upgrade/WEBISOLATION/feature_ui_configs.json";a.config_json_timeout=1E3;a.config_json_interval=288E5;a=Object.freeze(a);b.config=a})(this);
