var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(b){var c=0;return function(){return c<b.length?{done:!1,value:b[c++]}:{done:!0}}};$jscomp.arrayIterator=function(b){return{next:$jscomp.arrayIteratorImpl(b)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,c,a){b!=Array.prototype&&b!=Object.prototype&&(b[c]=a.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(b,c){this.$jscomp$symbol$id_=b;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:c})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function b(a){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(a||"")+"_"+c++,a)}var c=0;return b}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.asyncIterator;b||(b=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};
$jscomp.iteratorFromArray=function(b,c){$jscomp.initSymbolIterator();b instanceof String&&(b+="");var a=0,d={next:function(){if(a<b.length){var e=a++;return{value:c(e,b[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill=function(b,c,a,d){if(c){a=$jscomp.global;b=b.split(".");for(d=0;d<b.length-1;d++){var e=b[d];e in a||(a[e]={});a=a[e]}b=b[b.length-1];d=a[b];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(a,b,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.keys",function(b){return b?b:function(){return $jscomp.iteratorFromArray(this,function(b){return b})}},"es6","es3");$jscomp.polyfill("Object.getOwnPropertySymbols",function(b){return b?b:function(){return[]}},"es6","es5");
$jscomp.polyfill("Array.prototype.entries",function(b){return b?b:function(){return $jscomp.iteratorFromArray(this,function(b,a){return[b,a]})}},"es6","es3");
$jscomp.polyfill("Array.from",function(b){return b?b:function(b,a,d){a=null!=a?a:function(a){return a};var e=[],c="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof c){b=c.call(b);for(var h=0;!(c=b.next()).done;)e.push(a.call(d,c.value,h++))}else for(c=b.length,h=0;h<c;h++)e.push(a.call(d,b[h],h));return e}},"es6","es3");$jscomp.owns=function(b,c){return Object.prototype.hasOwnProperty.call(b,c)};
$jscomp.assign="function"==typeof Object.assign?Object.assign:function(b,c){for(var a=1;a<arguments.length;a++){var d=arguments[a];if(d)for(var e in d)$jscomp.owns(d,e)&&(b[e]=d[e])}return b};$jscomp.polyfill("Object.assign",function(b){return b||$jscomp.assign},"es6","es3");$jscomp.makeIterator=function(b){var c="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];return c?c.call(b):$jscomp.arrayIterator(b)};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(b){function c(){this.batch_=null}function a(a){return a instanceof e?a:new e(function(b,d){b(a)})}if(b&&!$jscomp.FORCE_POLYFILL_PROMISE)return b;c.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var d=$jscomp.global.setTimeout;c.prototype.asyncExecuteFunction=function(a){d(a,0)};c.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var d=a[b];a[b]=null;try{d()}catch(m){this.asyncThrow_(m)}}}this.batch_=null};c.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var e=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(k){b.reject(k)}};e.prototype.createResolveAndReject_=function(){function a(a){return function(e){d||(d=!0,a.call(b,e))}}var b=this,d=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};e.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};e.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(k){this.reject_(k);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};e.prototype.reject_=function(a){this.settle_(2,a)};e.prototype.fulfill_=function(a){this.settle_(1,a)};e.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)f.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var f=new c;e.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};e.prototype.settleSameAsThenable_=function(a,b){var d=this.createResolveAndReject_();try{a.call(b,d.resolve,d.reject)}catch(m){d.reject(m)}};e.prototype.then=function(a,b){function d(a,b){return"function"==typeof a?function(b){try{c(a(b))}catch(u){h(u)}}:b}var c,h,f=new e(function(a,b){c=a;h=b});this.callWhenSettled_(d(a,c),d(b,h));return f};
e.prototype.catch=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,b){function d(){switch(e.state_){case 1:a(e.result_);break;case 2:b(e.result_);break;default:throw Error("Unexpected state: "+e.state_);}}var e=this;null==this.onSettledCallbacks_?f.asyncExecute(d):this.onSettledCallbacks_.push(d)};e.resolve=a;e.reject=function(a){return new e(function(b,d){d(a)})};e.race=function(b){return new e(function(d,e){for(var c=$jscomp.makeIterator(b),f=c.next();!f.done;f=c.next())a(f.value).callWhenSettled_(d,
e)})};e.all=function(b){var d=$jscomp.makeIterator(b),c=d.next();return c.done?a([]):new e(function(b,e){function f(a){return function(d){h[a]=d;l--;0==l&&b(h)}}var h=[],l=0;do h.push(void 0),l++,a(c.value).callWhenSettled_(f(h.length-1),e),c=d.next();while(!c.done)})};return e},"es6","es3");$jscomp.underscoreProtoCanBeSet=function(){var b={a:!0},c={};try{return c.__proto__=b,c.a}catch(a){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(b,c){b.__proto__=c;if(b.__proto__!==c)throw new TypeError(b+" is not extensible");return b}:null;$jscomp.polyfill("Object.setPrototypeOf",function(b){return b||$jscomp.setPrototypeOf},"es6","es5");$jscomp.polyfill("Object.is",function(b){return b?b:function(b,a){return b===a?0!==b||1/b===1/a:b!==b&&a!==a}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(b){return b?b:function(b,a){var d=this;d instanceof String&&(d=String(d));var e=d.length;a=a||0;for(0>a&&(a=Math.max(a+e,0));a<e;a++){var c=d[a];if(c===b||Object.is(c,b))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(b,c,a){if(null==b)throw new TypeError("The 'this' value for String.prototype."+a+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+a+" must not be a regular expression");return b+""};$jscomp.polyfill("String.prototype.includes",function(b){return b?b:function(b,a){return-1!==$jscomp.checkStringArgs(this,b,"includes").indexOf(b,a||0)}},"es6","es3");
$jscomp.findInternal=function(b,c,a){b instanceof String&&(b=String(b));for(var d=b.length,e=0;e<d;e++){var f=b[e];if(c.call(a,f,e,b))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,a){return $jscomp.findInternal(this,b,a).v}},"es6","es3");
!function(b){function c(d){if(a[d])return a[d].exports;var e=a[d]={i:d,l:!1,exports:{}};return b[d].call(e.exports,e,e.exports,c),e.l=!0,e.exports}var a={};c.m=b;c.c=a;c.d=function(a,b,f){c.o(a,b)||Object.defineProperty(a,b,{enumerable:!0,get:f})};c.r=function(a){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(a,Symbol.toStringTag,{value:"Module"});Object.defineProperty(a,"__esModule",{value:!0})};c.t=function(a,b){if((1&b&&(a=c(a)),8&b)||4&b&&"object"==typeof a&&a&&a.__esModule)return a;
var d=Object.create(null);if(c.r(d),Object.defineProperty(d,"default",{enumerable:!0,value:a}),2&b&&"string"!=typeof a)for(var e in a)c.d(d,e,function(b){return a[b]}.bind(null,e));return d};c.n=function(a){var b=a&&a.__esModule?function(){return a.default}:function(){return a};return c.d(b,"a",b),b};c.o=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};c.p="";c(c.s=164)}([function(b,c,a){b.exports=a(118)},function(b,c){b=b.exports={version:"2.6.9"};"number"==typeof __e&&(__e=b)},function(b,
c,a){function d(a,b,d,c,m,p,g){try{var f=a[p](g),h=f.value}catch(r){return void d(r)}f.done?b(h):e.resolve(h).then(c,m)}var e=a(60);b.exports=function(a){return function(){var b=this,c=arguments;return new e(function(e,f){function h(a){d(k,e,f,h,l,"next",a)}function l(a){d(k,e,f,h,l,"throw",a)}var k=a.apply(b,c);h(void 0)})}}},function(b,c,a){var d=a(5),e=a(1),f=a(13),h=a(14),l=a(17),k=function(a,b,c){var m,g,p,u=a&k.F,t=a&k.G,n=a&k.S,x=a&k.P,w=a&k.B,v=a&k.W,z=t?e:e[b]||(e[b]={}),C=z.prototype;n=
t?d:n?d[b]:(d[b]||{}).prototype;for(m in t&&(c=b),c)(g=!u&&n&&void 0!==n[m])&&l(z,m)||(p=g?n[m]:c[m],z[m]=t&&"function"!=typeof n[m]?c[m]:w&&g?f(p,d):v&&n[m]==p?function(a){var b=function(b,d,e){if(this instanceof a){switch(arguments.length){case 0:return new a;case 1:return new a(b);case 2:return new a(b,d)}return new a(b,d,e)}return a.apply(this,arguments)};return b.prototype=a.prototype,b}(p):x&&"function"==typeof p?f(Function.call,p):p,x&&((z.virtual||(z.virtual={}))[m]=p,a&k.R&&C&&!C[m]&&h(C,
m,p)))};k.F=1;k.G=2;k.S=4;k.P=8;k.B=16;k.W=32;k.U=64;k.R=128;b.exports=k},function(b,c){b.exports=function(a,b){if(!(a instanceof b))throw new TypeError("Cannot call a class as a function");}},function(b,c){b=b.exports="undefined"!=typeof window&&Math==Math?window:"undefined"!=typeof self&&self.Math==Math?self:Function("return this")();"number"==typeof __g&&(__g=b)},function(b,c,a){function d(a,b){for(var d=0;d<b.length;d++){var c=b[d];c.enumerable=c.enumerable||!1;c.configurable=!0;"value"in c&&
(c.writable=!0);e(a,c.key,c)}}var e=a(81);b.exports=function(a,b,e){return b&&d(a.prototype,b),e&&d(a,e),a}},function(b,c,a){var d=a(46)("wks"),e=a(34),f=a(5).Symbol,h="function"==typeof f;(b.exports=function(a){return d[a]||(d[a]=h&&f[a]||(h?f:e)("Symbol."+a))}).store=d},function(b,c){b.exports=function(a){return"object"==typeof a?null!==a:"function"==typeof a}},function(b,c,a){var d=a(10),e=a(64),f=a(41),h=Object.defineProperty;c.f=a(11)?Object.defineProperty:function(a,b,c){if(d(a),b=f(b,!0),d(c),
e)try{return h(a,b,c)}catch(p){}if("get"in c||"set"in c)throw TypeError("Accessors not supported!");return"value"in c&&(a[b]=c.value),a}},function(b,c,a){var d=a(8);b.exports=function(a){if(!d(a))throw TypeError(a+" is not an object!");return a}},function(b,c,a){b.exports=!a(15)(function(){return 7!=Object.defineProperty({},"a",{get:function(){return 7}}).a})},function(b,c,a){b.exports=a(116)},function(b,c,a){var d=a(16);b.exports=function(a,b,c){if(d(a),void 0===b)return a;switch(c){case 1:return function(d){return a.call(b,
d)};case 2:return function(d,e){return a.call(b,d,e)};case 3:return function(d,e,c){return a.call(b,d,e,c)}}return function(){return a.apply(b,arguments)}}},function(b,c,a){var d=a(9),e=a(23);b.exports=a(11)?function(a,b,c){return d.f(a,b,e(1,c))}:function(a,b,d){return a[b]=d,a}},function(b,c){b.exports=function(a){try{return!!a()}catch(d){return!0}}},function(b,c){b.exports=function(a){if("function"!=typeof a)throw TypeError(a+" is not a function!");return a}},function(b,c){var a={}.hasOwnProperty;
b.exports=function(b,e){return a.call(b,e)}},function(b,c,a){var d=a(43);b.exports=function(a){return Object(d(a))}},function(b,c,a){b.exports=a(100)},function(b,c,a){var d=a(42),e=a(43);b.exports=function(a){return d(e(a))}},function(b,c){b.exports={}},function(b,c,a){var d=a(98)(!0);a(49)(String,"String",function(a){this._t=String(a);this._i=0},function(){var a,b=this._t,c=this._i;return c>=b.length?{value:void 0,done:!0}:(a=d(b,c),this._i+=a.length,{value:a,done:!1})})},function(b,c){b.exports=
function(a,b){return{enumerable:!(1&a),configurable:!(2&a),writable:!(4&a),value:b}}},function(b,c,a){var d=a(65),e=a(47);b.exports=Object.keys||function(a){return d(a,e)}},function(b,c){var a={}.toString;b.exports=function(b){return a.call(b).slice(8,-1)}},function(b,c){b.exports=!0},function(b,c,a){a(94);b=a(5);c=a(14);var d=a(21);a=a(7)("toStringTag");for(var e="CSSRuleList CSSStyleDeclaration CSSValueList ClientRectList DOMRectList DOMStringList DOMTokenList DataTransferItemList FileList HTMLAllCollection HTMLCollection HTMLFormElement HTMLSelectElement MediaList MimeTypeArray NamedNodeMap NodeList PaintRequestList Plugin PluginArray SVGLengthList SVGNumberList SVGPathSegList SVGPointList SVGStringList SVGTransformList SourceBufferList StyleSheetList TextTrackCueList TextTrackList TouchList".split(" "),
f=0;f<e.length;f++){var h=e[f],l=b[h];(l=l&&l.prototype)&&!l[a]&&c(l,a,h);d[h]=d.Array}},function(b,c,a){var d=a(10),e=a(97),f=a(47),h=a(45)("IE_PROTO"),l=function(){},k=function(){var b=a(40)("iframe");var d=f.length;b.style.display="none";a(68).appendChild(b);b.src="javascript:";(b=b.contentWindow.document).open();b.write("<script>document.F=Object\x3c/script>");b.close();for(k=b.F;d--;)delete k.prototype[f[d]];return k()};b.exports=Object.create||function(a,b){var c;return null!==a?(l.prototype=
d(a),c=new l,l.prototype=null,c[h]=a):c=k(),void 0===b?c:e(c,b)}},function(b,c,a){var d=a(9).f,e=a(17),f=a(7)("toStringTag");b.exports=function(a,b,c){a&&!e(a=c?a:a.prototype,f)&&d(a,f,{configurable:!0,value:b})}},function(b,c,a){var d=a(13),e=a(71),f=a(72),h=a(10),l=a(33),k=a(50),m={},p={};(c=b.exports=function(a,b,c,r,u){var g,q;u=u?function(){return a}:k(a);c=d(c,r,b?2:1);r=0;if("function"!=typeof u)throw TypeError(a+" is not iterable!");if(f(u))for(u=l(a.length);u>r;r++){if((q=b?c(h(g=a[r])[0],
g[1]):c(a[r]))===m||q===p)return q}else for(u=u.call(a);!(g=u.next()).done;)if((q=e(u,c,g.value,b))===m||q===p)return q}).BREAK=m;c.RETURN=p},function(b,c,a){function d(a){return b.exports=d=f?e:function(a){return a.__proto__||e(a)},d(a)}var e=a(137),f=a(84);b.exports=d},function(b,c,a){var d=a(81);b.exports=function(a,b,c){return b in a?d(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0}):a[b]=c,a}},function(b,c,a){var d=a(44),e=Math.min;b.exports=function(a){return 0<a?e(d(a),9007199254740991):
0}},function(b,c){var a=0,d=Math.random();b.exports=function(b){return"Symbol(".concat(void 0===b?"":b,")_",(++a+d).toString(36))}},function(b,c){c.f={}.propertyIsEnumerable},function(b,c,a){var d=a(25),e=a(7)("toStringTag"),f="Arguments"==d(function(){return arguments}());b.exports=function(a){var b;if(void 0===a)var c="Undefined";else{if(null===a)var h="Null";else{a:{var p=a=Object(a);try{h=p[e];break a}catch(g){}h=void 0}h="string"==typeof(c=h)?c:f?d(a):"Object"==(b=d(a))&&"function"==typeof a.callee?
"Arguments":b}c=h}return c}},function(b,c,a){b.exports=a(102)},function(b,c,a){var d=a(127),e=a(61);b.exports=function(a,b){return!b||"object"!==d(b)&&"function"!=typeof b?e(a):b}},function(b,c,a){var d=a(85),e=a(59);b.exports=function(a,b){if("function"!=typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function");a.prototype=d(b&&b.prototype,{constructor:{value:a,writable:!0,configurable:!0}});b&&e(a,b)}},function(b,c,a){c=a(8);var d=a(5).document,e=c(d)&&c(d.createElement);
b.exports=function(a){return e?d.createElement(a):{}}},function(b,c,a){var d=a(8);b.exports=function(a,b){if(!d(a))return a;var c,e;if(b&&"function"==typeof(c=a.toString)&&!d(e=c.call(a))||"function"==typeof(c=a.valueOf)&&!d(e=c.call(a))||!b&&"function"==typeof(c=a.toString)&&!d(e=c.call(a)))return e;throw TypeError("Can't convert object to primitive value");}},function(b,c,a){var d=a(25);b.exports=Object("z").propertyIsEnumerable(0)?Object:function(a){return"String"==d(a)?a.split(""):Object(a)}},
function(b,c){b.exports=function(a){if(null==a)throw TypeError("Can't call method on  "+a);return a}},function(b,c){var a=Math.ceil,d=Math.floor;b.exports=function(b){return isNaN(b=+b)?0:(0<b?d:a)(b)}},function(b,c,a){var d=a(46)("keys"),e=a(34);b.exports=function(a){return d[a]||(d[a]=e(a))}},function(b,c,a){c=a(1);var d=a(5),e=d["__core-js_shared__"]||(d["__core-js_shared__"]={});(b.exports=function(a,b){return e[a]||(e[a]=void 0!==b?b:{})})("versions",[]).push({version:c.version,mode:a(26)?"pure":
"global",copyright:"\u00a9 2019 Denis Pushkarev (zloirock.ru)"})},function(b,c){b.exports="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ")},function(b,c){c.f=Object.getOwnPropertySymbols},function(b,c,a){var d=a(26),e=a(3),f=a(67),h=a(14),l=a(21),k=a(96),m=a(29),p=a(69),g=a(7)("iterator"),q=!([].keys&&"next"in[].keys()),y=function(){return this};b.exports=function(a,b,c,n,x,w,v){k(c,b,n);var z,C,r;n=function(a){return!q&&a in A?A[a]:function(){return new c(this,
a)}};var t=b+" Iterator",u="values"==x,G=!1,A=a.prototype,D=A[g]||A["@@iterator"]||x&&A[x],B=D||n(x),L=x?u?n("entries"):B:void 0,H="Array"==b&&A.entries||D;if(H&&(r=p(H.call(new a)))!==Object.prototype&&r.next&&(m(r,t,!0),d||"function"==typeof r[g]||h(r,g,y)),u&&D&&"values"!==D.name&&(G=!0,B=function(){return D.call(this)}),d&&!v||!q&&!G&&A[g]||h(A,g,B),l[b]=B,l[t]=y,x)if(z={values:u?B:n("values"),keys:w?B:n("keys"),entries:L},v)for(C in z)C in A||f(A,C,z[C]);else e(e.P+e.F*(q||G),b,z);return z}},
function(b,c,a){var d=a(36),e=a(7)("iterator"),f=a(21);b.exports=a(1).getIteratorMethod=function(a){if(null!=a)return a[e]||a["@@iterator"]||f[d(a)]}},function(b,c){},function(b,c,a){var d=a(14);b.exports=function(a,b,c){for(var e in b)c&&a[e]?a[e]=b[e]:d(a,e,b[e]);return a}},function(b,c){b.exports=function(a,b,c,f){if(!(a instanceof b)||void 0!==f&&f in a)throw TypeError(c+": incorrect invocation!");return a}},function(b,c,a){var d=a(34)("meta"),e=a(8),f=a(17),h=a(9).f,l=0,k=Object.isExtensible||
function(){return!0},m=!a(15)(function(){return k(Object.preventExtensions({}))}),p=function(a){h(a,d,{value:{i:"O"+ ++l,w:{}}})},g=b.exports={KEY:d,NEED:!1,fastKey:function(a,b){if(!e(a))return"symbol"==typeof a?a:("string"==typeof a?"S":"P")+a;if(!f(a,d)){if(!k(a))return"F";if(!b)return"E";p(a)}return a[d].i},getWeak:function(a,b){if(!f(a,d)){if(!k(a))return!0;if(!b)return!1;p(a)}return a[d].w},onFreeze:function(a){return m&&g.NEED&&k(a)&&!f(a,d)&&p(a),a}}},function(b,c,a){var d=a(25);b.exports=
Array.isArray||function(a){return"Array"==d(a)}},function(b,c,a){function d(a){var b,d;this.promise=new a(function(a,c){if(void 0!==b||void 0!==d)throw TypeError("Bad Promise constructor");b=a;d=c});this.resolve=e(b);this.reject=e(d)}var e=a(16);b.exports.f=function(a){return new d(a)}},function(b,c,a){c.f=a(7)},function(b,c,a){var d=a(5),e=a(1),f=a(26),h=a(57),l=a(9).f;b.exports=function(a){var b=e.Symbol||(e.Symbol=f?{}:d.Symbol||{});"_"==a.charAt(0)||a in b||l(b,a,{value:h.f(a)})}},function(b,
c,a){function d(a,c){return b.exports=d=e||function(a,b){return a.__proto__=b,a},d(a,c)}var e=a(84);b.exports=d},function(b,c,a){b.exports=a(119)},function(b,c){b.exports=function(a){if(void 0===a)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return a}},function(b,c,a){b.exports=a(88)},function(b,c,a){b.exports=a(93)},function(b,c,a){b.exports=!a(11)&&!a(15)(function(){return 7!=Object.defineProperty(a(40)("div"),"a",{get:function(){return 7}}).a})},function(b,
c,a){var d=a(17),e=a(20),f=a(91)(!1),h=a(45)("IE_PROTO");b.exports=function(a,b){var c;a=e(a);var l=0,k=[];for(c in a)c!=h&&d(a,c)&&k.push(c);for(;b.length>l;)d(a,c=b[l++])&&(~f(k,c)||k.push(c));return k}},function(b,c){b.exports=function(a,b){return{value:b,done:!!a}}},function(b,c,a){b.exports=a(14)},function(b,c,a){c=a(5).document;b.exports=c&&c.documentElement},function(b,c,a){var d=a(17),e=a(18),f=a(45)("IE_PROTO"),h=Object.prototype;b.exports=Object.getPrototypeOf||function(a){return a=e(a),
d(a,f)?a[f]:"function"==typeof a.constructor&&a instanceof a.constructor?a.constructor.prototype:a instanceof Object?h:null}},function(b,c,a){var d=a(3),e=a(1),f=a(15);b.exports=function(a,b){var c=(e.Object||{})[a]||Object[a],h={};h[a]=b(c);d(d.S+d.F*f(function(){c(1)}),"Object",h)}},function(b,c,a){var d=a(10);b.exports=function(a,b,c,l){try{return l?b(d(c)[0],c[1]):b(c)}catch(k){throw b=a.return,void 0!==b&&d(b.call(a)),k;}}},function(b,c,a){var d=a(21),e=a(7)("iterator"),f=Array.prototype;b.exports=
function(a){return void 0!==a&&(d.Array===a||f[e]===a)}},function(b,c,a){var d=a(5),e=a(1),f=a(9),h=a(11),l=a(7)("species");b.exports=function(a){a="function"==typeof e[a]?e[a]:d[a];h&&a&&!a[l]&&f.f(a,l,{configurable:!0,get:function(){return this}})}},function(b,c,a){var d=a(8);b.exports=function(a,b){if(!d(a)||a._t!==b)throw TypeError("Incompatible receiver, "+b+" required!");return a}},function(b,c,a){var d=a(10),e=a(16),f=a(7)("species");b.exports=function(a,b){var c;a=d(a).constructor;return void 0===
a||null==(c=d(a)[f])?b:e(c)}},function(b,c,a){var d,e,f,h=a(13),l=a(77),k=a(68),m=a(40),p=a(5),g=p.process;c=p.setImmediate;var q=p.clearImmediate,y=p.MessageChannel,r=p.Dispatch,u=0,t={},n=function(){var a=+this;if(t.hasOwnProperty(a)){var b=t[a];delete t[a];b()}},x=function(a){n.call(a.data)};c&&q||(c=function(a){for(var b=[],c=1;arguments.length>c;)b.push(arguments[c++]);return t[++u]=function(){l("function"==typeof a?a:Function(a),b)},d(u),u},q=function(a){delete t[a]},"process"==a(25)(g)?d=function(a){g.nextTick(h(n,
a,1))}:r&&r.now?d=function(a){r.now(h(n,a,1))}:y?(f=(e=new y).port2,e.port1.onmessage=x,d=h(f.postMessage,f,1)):p.addEventListener&&"function"==typeof postMessage&&!p.importScripts?(d=function(a){p.postMessage(a+"","*")},p.addEventListener("message",x,!1)):d="onreadystatechange"in m("script")?function(a){k.appendChild(m("script")).onreadystatechange=function(){k.removeChild(this);n.call(a)}}:function(a){setTimeout(h(n,a,1),0)});b.exports={set:c,clear:q}},function(b,c){b.exports=function(a,b,c){var d=
void 0===c;switch(b.length){case 0:return d?a():a.call(c);case 1:return d?a(b[0]):a.call(c,b[0]);case 2:return d?a(b[0],b[1]):a.call(c,b[0],b[1]);case 3:return d?a(b[0],b[1],b[2]):a.call(c,b[0],b[1],b[2]);case 4:return d?a(b[0],b[1],b[2],b[3]):a.call(c,b[0],b[1],b[2],b[3])}return a.apply(c,b)}},function(b,c){b.exports=function(a){try{return{e:!1,v:a()}}catch(d){return{e:!0,v:d}}}},function(b,c,a){var d=a(10),e=a(8),f=a(56);b.exports=function(a,b){if(d(a),e(b)&&b.constructor===a)return b;a=f.f(a);
return(0,a.resolve)(b),a.promise}},function(b,c,a){var d=a(7)("iterator"),e=!1;try{var f=[7][d]();f.return=function(){e=!0};Array.from(f,function(){throw 2;})}catch(h){}b.exports=function(a,b){if(!b&&!e)return!1;var c=!1;try{b=[7];var f=b[d]();f.next=function(){return{done:c=!0}};b[d]=function(){return f};a(b)}catch(p){}return c}},function(b,c,a){b.exports=a(125)},function(b,c,a){var d=a(65),e=a(47).concat("length","prototype");c.f=Object.getOwnPropertyNames||function(a){return d(a,e)}},function(b,
c,a){var d=a(35),e=a(23),f=a(20),h=a(41),l=a(17),k=a(64),m=Object.getOwnPropertyDescriptor;c.f=a(11)?m:function(a,b){if(a=f(a),b=h(b,!0),k)try{return m(a,b)}catch(q){}if(l(a,b))return e(!d.f.call(a,b),a[b])}},function(b,c,a){b.exports=a(140)},function(b,c,a){b.exports=a(143)},function(b,c,a){function d(a){var c="function"==typeof f?new f:void 0;return b.exports=d=function(a){function b(){return m(a,arguments,h(this).constructor)}if(null===a||!k(a))return a;if("function"!=typeof a)throw new TypeError("Super expression must either be null or a function");
if(void 0!==c){if(c.has(a))return c.get(a);c.set(a,b)}return b.prototype=e(a.prototype,{constructor:{value:b,enumerable:!1,writable:!0,configurable:!0}}),l(b,a)},d(a)}var e=a(85),f=a(37),h=a(31),l=a(59),k=a(145),m=a(146);b.exports=d},function(b,c,a){var d=a(151),e=a(155),f=a(163);b.exports=function(a){return d(a)||e(a)||f()}},function(b,c,a){a(89);b.exports=a(1).Object.assign},function(b,c,a){b=a(3);b(b.S+b.F,"Object",{assign:a(90)})},function(b,c,a){var d=a(11),e=a(24),f=a(48),h=a(35),l=a(18),k=
a(42),m=Object.assign;b.exports=!m||a(15)(function(){var a={},b={},c=Symbol();return a[c]=7,"abcdefghijklmnopqrst".split("").forEach(function(a){b[a]=a}),7!=m({},a)[c]||"abcdefghijklmnopqrst"!=Object.keys(m({},b)).join("")})?function(a,b){for(var c=l(a),m=arguments.length,g=1,p=f.f,t=h.f;m>g;)for(var n,x=k(arguments[g++]),w=p?e(x).concat(p(x)):e(x),v=w.length,z=0;v>z;)n=w[z++],d&&!t.call(x,n)||(c[n]=x[n]);return c}:m},function(b,c,a){var d=a(20),e=a(33),f=a(92);b.exports=function(a){return function(b,
c,h){var k;b=d(b);var l=e(b.length);h=f(h,l);if(a&&c!=c)for(;l>h;){if((k=b[h++])!=k)return!0}else for(;l>h;h++)if((a||h in b)&&b[h]===c)return a||h||0;return!a&&-1}}},function(b,c,a){var d=a(44),e=Math.max,f=Math.min;b.exports=function(a,b){return 0>(a=d(a))?e(a+b,0):f(a,b)}},function(b,c,a){a(27);a(22);b.exports=a(99)},function(b,c,a){c=a(95);var d=a(66),e=a(21),f=a(20);b.exports=a(49)(Array,"Array",function(a,b){this._t=f(a);this._i=0;this._k=b},function(){var a=this._t,b=this._k,c=this._i++;return!a||
c>=a.length?(this._t=void 0,d(1)):d(0,"keys"==b?c:"values"==b?a[c]:[c,a[c]])},"values");e.Arguments=e.Array;c("keys");c("values");c("entries")},function(b,c){b.exports=function(){}},function(b,c,a){var d=a(28),e=a(23),f=a(29),h={};a(14)(h,a(7)("iterator"),function(){return this});b.exports=function(a,b,c){a.prototype=d(h,{next:e(1,c)});f(a,b+" Iterator")}},function(b,c,a){var d=a(9),e=a(10),f=a(24);b.exports=a(11)?Object.defineProperties:function(a,b){e(a);for(var c,h=f(b),l=h.length,g=0;l>g;)d.f(a,
c=h[g++],b[c]);return a}},function(b,c,a){var d=a(44),e=a(43);b.exports=function(a){return function(b,c){var f,h;b=String(e(b));c=d(c);var l=b.length;return 0>c||c>=l?a?"":void 0:55296>(f=b.charCodeAt(c))||56319<f||c+1===l||56320>(h=b.charCodeAt(c+1))||57343<h?a?b.charAt(c):f:a?b.slice(c,c+2):h-56320+(f-55296<<10)+65536}}},function(b,c,a){var d=a(10),e=a(50);b.exports=a(1).getIterator=function(a){var b=e(a);if("function"!=typeof b)throw TypeError(a+" is not iterable!");return d(b.call(a))}},function(b,
c,a){a(101);b.exports=a(1).Object.keys},function(b,c,a){var d=a(18),e=a(24);a(70)("keys",function(){return function(a){return e(d(a))}})},function(b,c,a){a(51);a(22);a(27);a(103);a(109);a(112);a(114);b.exports=a(1).Map},function(b,c,a){var d=a(104),e=a(74);b.exports=a(105)("Map",function(a){return function(){return a(this,0<arguments.length?arguments[0]:void 0)}},{get:function(a){return(a=d.getEntry(e(this,"Map"),a))&&a.v},set:function(a,b){return d.def(e(this,"Map"),0===a?0:a,b)}},d,!0)},function(b,
c,a){var d=a(9).f,e=a(28),f=a(52),h=a(13),l=a(53),k=a(30),m=a(49),p=a(66),g=a(73),q=a(11),y=a(54).fastKey,r=a(74),u=q?"_s":"size",t=function(a,b){var c=y(b);if("F"!==c)return a._i[c];for(a=a._f;a;a=a.n)if(a.k==b)return a};b.exports={getConstructor:function(a,b,c,g){var m=a(function(a,d){l(a,m,b,"_i");a._t=b;a._i=e(null);a._f=void 0;a._l=void 0;a[u]=0;null!=d&&k(d,c,a[g],a)});return f(m.prototype,{clear:function(){for(var a=r(this,b),c=a._i,d=a._f;d;d=d.n)d.r=!0,d.p&&(d.p=d.p.n=void 0),delete c[d.i];
a._f=a._l=void 0;a[u]=0},delete:function(a){var c=r(this,b);if(a=t(c,a)){var d=a.n,e=a.p;delete c._i[a.i];a.r=!0;e&&(e.n=d);d&&(d.p=e);c._f==a&&(c._f=d);c._l==a&&(c._l=e);c[u]--}return!!a},forEach:function(a){r(this,b);for(var c,d=h(a,1<arguments.length?arguments[1]:void 0,3);c=c?c.n:this._f;)for(d(c.v,c.k,this);c&&c.r;)c=c.p},has:function(a){return!!t(r(this,b),a)}}),q&&d(m.prototype,"size",{get:function(){return r(this,b)[u]}}),m},def:function(a,b,c){var d,e,f=t(a,b);return f?f.v=c:(a._l=f={i:e=
y(b,!0),k:b,v:c,p:d=a._l,n:void 0,r:!1},a._f||(a._f=f),d&&(d.n=f),a[u]++,"F"!==e&&(a._i[e]=f)),a},getEntry:t,setStrong:function(a,b,c){m(a,b,function(a,c){this._t=r(a,b);this._k=c;this._l=void 0},function(){for(var a=this._k,b=this._l;b&&b.r;)b=b.p;return this._t&&(this._l=b=b?b.n:this._t._f)?p(0,"keys"==a?b.k:"values"==a?b.v:[b.k,b.v]):(this._t=void 0,p(1))},c?"entries":"values",!c,!0);g(b)}}},function(b,c,a){var d=a(5),e=a(3),f=a(54),h=a(15),l=a(14),k=a(52),m=a(30),p=a(53),g=a(8),q=a(29),y=a(9).f,
r=a(106)(0),u=a(11);b.exports=function(a,b,c,w,v,z){var t=d[a],n=t,x=v?"set":"add",J=n&&n.prototype,G={};return u&&"function"==typeof n&&(z||J.forEach&&!h(function(){(new n).entries().next()}))?(n=b(function(b,c){p(b,n,a,"_c");b._c=new t;null!=c&&m(c,v,b[x],b)}),r("add clear delete forEach get has set keys values entries toJSON".split(" "),function(a){var b="add"==a||"set"==a;a in J&&(!z||"clear"!=a)&&l(n.prototype,a,function(c,d){if(p(this,n,a),!b&&z&&!g(c))return"get"==a&&void 0;c=this._c[a](0===
c?0:c,d);return b?this:c})}),z||y(n.prototype,"size",{get:function(){return this._c.size}})):(n=w.getConstructor(b,a,v,x),k(n.prototype,c),f.NEED=!0),q(n,a),G[a]=n,e(e.G+e.W+e.F,G),z||w.setStrong(n,a,v),n}},function(b,c,a){var d=a(13),e=a(42),f=a(18),h=a(33),l=a(107);b.exports=function(a,b){var c=1==a,k=2==a,m=3==a,y=4==a,r=6==a,u=5==a||r,t=b||l;return function(b,l,g){var q,p,n=f(b),w=e(n);l=d(l,g,3);g=h(w.length);var x=0;for(b=c?t(b,g):k?t(b,0):void 0;g>x;x++)if((u||x in w)&&(p=l(q=w[x],x,n),a))if(c)b[x]=
p;else if(p)switch(a){case 3:return!0;case 5:return q;case 6:return x;case 2:b.push(q)}else if(y)return!1;return r?-1:m||y?y:b}}},function(b,c,a){var d=a(108);b.exports=function(a,b){return new (d(a))(b)}},function(b,c,a){var d=a(8),e=a(55),f=a(7)("species");b.exports=function(a){var b;return e(a)&&("function"!=typeof(b=a.constructor)||b!==Array&&!e(b.prototype)||(b=void 0),d(b)&&null===(b=b[f])&&(b=void 0)),void 0===b?Array:b}},function(b,c,a){b=a(3);b(b.P+b.R,"Map",{toJSON:a(110)("Map")})},function(b,
c,a){var d=a(36),e=a(111);b.exports=function(a){return function(){if(d(this)!=a)throw TypeError(a+"#toJSON isn't generic");return e(this)}}},function(b,c,a){var d=a(30);b.exports=function(a,b){var c=[];return d(a,!1,c.push,c,b),c}},function(b,c,a){a(113)("Map")},function(b,c,a){var d=a(3);b.exports=function(a){d(d.S,a,{of:function(){for(var a=arguments.length,b=Array(a);a--;)b[a]=arguments[a];return new this(b)}})}},function(b,c,a){a(115)("Map")},function(b,c,a){var d=a(3),e=a(16),f=a(13),h=a(30);
b.exports=function(a){d(d.S,a,{from:function(a,b,c){var d,k,l,m;return e(this),(d=void 0!==b)&&e(b),null==a?new this:(k=[],d?(l=0,m=f(b,c,2),h(a,!1,function(a){k.push(m(a,l++))})):h(a,!1,k.push,k),new this(k))}})}},function(b,c,a){a(117);b.exports=a(1).Date.now},function(b,c,a){b=a(3);b(b.S,"Date",{now:function(){return(new Date).getTime()}})},function(b,c,a){b=function(a){function b(a,b,e,f){b=Object.create((b&&b.prototype instanceof d?b:d).prototype);f=new r(f||[]);return b._invoke=function(a,b,
d){var e=I;return function(f,h){if(e===G)throw Error("Generator is already running");if(e===A){if("throw"===f)throw h;return t()}d.method=f;for(d.arg=h;;){if(f=d.delegate)if(f=g(f,d)){if(f===D)continue;return f}if("next"===d.method)d.sent=d._sent=d.arg;else if("throw"===d.method){if(e===I)throw e=A,d.arg;d.dispatchException(d.arg)}else"return"===d.method&&d.abrupt("return",d.arg);e=G;f=c(a,b,d);if("normal"===f.type){if(e=d.done?A:J,f.arg===D)continue;return{value:f.arg,done:d.done}}"throw"===f.type&&
(e=A,d.method="throw",d.arg=f.arg)}}}(a,e,f),b}function c(a,b,c){try{return{type:"normal",arg:a.call(b,c)}}catch(E){return{type:"throw",arg:E}}}function d(){}function l(){}function k(){}function m(a){["next","throw","return"].forEach(function(b){a[b]=function(a){return this._invoke(b,a)}})}function p(a){var b;this._invoke=function(d,e){function f(){return new Promise(function(b,f){!function T(b,d,e,f){b=c(a[b],a,d);if("throw"!==b.type){var h=b.arg;return(b=h.value)&&"object"==typeof b&&w.call(b,"__await")?
Promise.resolve(b.__await).then(function(a){T("next",a,e,f)},function(a){T("throw",a,e,f)}):Promise.resolve(b).then(function(a){h.value=a;e(h)},function(a){return T("throw",a,e,f)})}f(b.arg)}(d,e,b,f)})}return b=b?b.then(f,f):f()}}function g(a,b){var d=a.iterator[b.method];if(d===n){if(b.delegate=null,"throw"===b.method){if(a.iterator.return&&(b.method="return",b.arg=n,g(a,b),"throw"===b.method))return D;b.method="throw";b.arg=new TypeError("The iterator does not provide a 'throw' method")}return D}d=
c(d,a.iterator,b.arg);return"throw"===d.type?(b.method="throw",b.arg=d.arg,b.delegate=null,D):(d=d.arg)?d.done?(b[a.resultName]=d.value,b.next=a.nextLoc,"return"!==b.method&&(b.method="next",b.arg=n),b.delegate=null,D):d:(b.method="throw",b.arg=new TypeError("iterator result is not an object"),b.delegate=null,D)}function q(a){var b={tryLoc:a[0]};1 in a&&(b.catchLoc=a[1]);2 in a&&(b.finallyLoc=a[2],b.afterLoc=a[3]);this.tryEntries.push(b)}function y(a){var b=a.completion||{};b.type="normal";delete b.arg;
a.completion=b}function r(a){this.tryEntries=[{tryLoc:"root"}];a.forEach(q,this);this.reset(!0)}function u(a){if(a){var b=a[z];if(b)return b.call(a);if("function"==typeof a.next)return a;if(!isNaN(a.length)){var c=-1;b=function F(){for(;++c<a.length;)if(w.call(a,c))return F.value=a[c],F.done=!1,F;return F.value=n,F.done=!0,F};return b.next=b}}return{next:t}}function t(){return{value:n,done:!0}}var n,x=Object.prototype,w=x.hasOwnProperty,v="function"==typeof Symbol?Symbol:{},z=v.iterator||"@@iterator",
C=v.asyncIterator||"@@asyncIterator",Q=v.toStringTag||"@@toStringTag";a.wrap=b;var I="suspendedStart",J="suspendedYield",G="executing",A="completed",D={};v={};v[z]=function(){return this};var B=Object.getPrototypeOf;(B=B&&B(B(u([]))))&&B!==x&&w.call(B,z)&&(v=B);var L=k.prototype=d.prototype=Object.create(v);return l.prototype=L.constructor=k,k.constructor=l,k[Q]=l.displayName="GeneratorFunction",a.isGeneratorFunction=function(a){a="function"==typeof a&&a.constructor;return!!a&&(a===l||"GeneratorFunction"===
(a.displayName||a.name))},a.mark=function(a){return Object.setPrototypeOf?Object.setPrototypeOf(a,k):(a.__proto__=k,Q in a||(a[Q]="GeneratorFunction")),a.prototype=Object.create(L),a},a.awrap=function(a){return{__await:a}},m(p.prototype),p.prototype[C]=function(){return this},a.AsyncIterator=p,a.async=function(c,d,e,f){var h=new p(b(c,d,e,f));return a.isGeneratorFunction(d)?h:h.next().then(function(a){return a.done?a.value:h.next()})},m(L),L[Q]="Generator",L[z]=function(){return this},L.toString=
function(){return"[object Generator]"},a.keys=function(a){var b=[],c;for(c in a)b.push(c);return b.reverse(),function F(){for(;b.length;){var c=b.pop();if(c in a)return F.value=c,F.done=!1,F}return F.done=!0,F}},a.values=u,r.prototype={constructor:r,reset:function(a){if(this.prev=0,this.next=0,this.sent=this._sent=n,this.done=!1,this.delegate=null,this.method="next",this.arg=n,this.tryEntries.forEach(y),!a)for(var b in this)"t"===b.charAt(0)&&w.call(this,b)&&!isNaN(+b.slice(1))&&(this[b]=n)},stop:function(){this.done=
!0;var a=this.tryEntries[0].completion;if("throw"===a.type)throw a.arg;return this.rval},dispatchException:function(a){function b(b,d){return f.type="throw",f.arg=a,c.next=b,d&&(c.method="next",c.arg=n),!!d}if(this.done)throw a;for(var c=this,d=this.tryEntries.length-1;0<=d;--d){var e=this.tryEntries[d],f=e.completion;if("root"===e.tryLoc)return b("end");if(e.tryLoc<=this.prev){var h=w.call(e,"catchLoc"),k=w.call(e,"finallyLoc");if(h&&k){if(this.prev<e.catchLoc)return b(e.catchLoc,!0);if(this.prev<
e.finallyLoc)return b(e.finallyLoc)}else if(h){if(this.prev<e.catchLoc)return b(e.catchLoc,!0)}else{if(!k)throw Error("try statement without catch or finally");if(this.prev<e.finallyLoc)return b(e.finallyLoc)}}}},abrupt:function(a,b){for(var c=this.tryEntries.length-1;0<=c;--c){var d=this.tryEntries[c];if(d.tryLoc<=this.prev&&w.call(d,"finallyLoc")&&this.prev<d.finallyLoc){var e=d;break}}e&&("break"===a||"continue"===a)&&e.tryLoc<=b&&b<=e.finallyLoc&&(e=null);c=e?e.completion:{};return c.type=a,c.arg=
b,e?(this.method="next",this.next=e.finallyLoc,D):this.complete(c)},complete:function(a,b){if("throw"===a.type)throw a.arg;return"break"===a.type||"continue"===a.type?this.next=a.arg:"return"===a.type?(this.rval=this.arg=a.arg,this.method="return",this.next="end"):"normal"===a.type&&b&&(this.next=b),D},finish:function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];if(c.finallyLoc===a)return this.complete(c.completion,c.afterLoc),y(c),D}},catch:function(a){for(var b=this.tryEntries.length-
1;0<=b;--b){var c=this.tryEntries[b];if(c.tryLoc===a){a=c.completion;if("throw"===a.type){var d=a.arg;y(c)}return d}}throw Error("illegal catch attempt");},delegateYield:function(a,b,c){return this.delegate={iterator:u(a),resultName:b,nextLoc:c},"next"===this.method&&(this.arg=n),D}},a}(b.exports);try{regeneratorRuntime=b}catch(d){Function("r","regeneratorRuntime = r")(b)}},function(b,c,a){a(51);a(22);a(27);a(120);a(123);a(124);b.exports=a(1).Promise},function(b,c,a){var d,e,f,h=a(26),l=a(5),k=a(13),
m=a(36);b=a(3);var p=a(8),g=a(16),q=a(53),y=a(30),r=a(75),u=a(76).set,t=a(121)();c=a(56);var n=a(78),x=a(122),w=a(79),v=l.TypeError,z=l.process,C=z&&z.versions,Q=C&&C.v8||"",I=l.Promise,J="process"==m(z),G=function(){},A=e=c.f;m=!!function(){try{var b=I.resolve(1),c=(b.constructor={})[a(7)("species")]=function(a){a(G,G)};return(J||"function"==typeof PromiseRejectionEvent)&&b.then(G)instanceof c&&0!==Q.indexOf("6.6")&&-1===x.indexOf("Chrome/66")}catch(U){}}();var D=function(a){var b;return!(!p(a)||
"function"!=typeof(b=a.then))&&b},B=function(a,b){if(!a._n){a._n=!0;var c=a._c;t(function(){for(var d=a._v,e=1==a._s,f=0;c.length>f;){var h=void 0,k=void 0,l=void 0,g=c[f++],m=e?g.ok:g.fail,p=g.resolve,q=g.reject,n=g.domain;try{m?(e||(2==a._h&&H(a),a._h=1),!0===m?l=d:(n&&n.enter(),l=m(d),n&&(n.exit(),h=!0)),l===g.promise?q(v("Promise-chain cycle")):(k=D(l))?k.call(l,p,q):p(l)):q(d)}catch(X){n&&!h&&n.exit(),q(X)}}a._c=[];a._n=!1;b&&!a._h&&L(a)})}},L=function(a){u.call(l,function(){var b,c,d,e=a._v,
f=1!==a._h&&0===(a._a||a._c).length;if(f&&(b=n(function(){J?z.emit("unhandledRejection",e,a):(c=l.onunhandledrejection)?c({promise:a,reason:e}):(d=l.console)&&d.error&&d.error("Unhandled promise rejection",e)}),a._h=J||1!==a._h&&0===(a._a||a._c).length?2:1),a._a=void 0,f&&b.e)throw b.v;})},H=function(a){u.call(l,function(){var b;J?z.emit("rejectionHandled",a):(b=l.onrejectionhandled)&&b({promise:a,reason:a._v})})},O=function(a){var b=this;b._d||(b._d=!0,(b=b._w||b)._v=a,b._s=2,b._a||(b._a=b._c.slice()),
B(b,!0))},P=function(a){var b,c=this;if(!c._d){c._d=!0;c=c._w||c;try{if(c===a)throw v("Promise can't be resolved itself");(b=D(a))?t(function(){var d={_w:c,_d:!1};try{b.call(a,k(P,d,1),k(O,d,1))}catch(R){O.call(d,R)}}):(c._v=a,c._s=1,B(c,!1))}catch(K){O.call({_w:c,_d:!1},K)}}};m||(I=function(a){q(this,I,"Promise","_h");g(a);d.call(this);try{a(k(P,this,1),k(O,this,1))}catch(Y){O.call(this,Y)}},(d=function(a){this._c=[];this._a=void 0;this._s=0;this._d=!1;this._v=void 0;this._h=0;this._n=!1}).prototype=
a(52)(I.prototype,{then:function(a,b){var c=A(r(this,I));return c.ok="function"!=typeof a||a,c.fail="function"==typeof b&&b,c.domain=J?z.domain:void 0,this._c.push(c),this._a&&this._a.push(c),this._s&&B(this,!1),c.promise},catch:function(a){return this.then(void 0,a)}}),f=function(){var a=new d;this.promise=a;this.resolve=k(P,a,1);this.reject=k(O,a,1)},c.f=A=function(a){return a===I||a===E?new f(a):e(a)});b(b.G+b.W+b.F*!m,{Promise:I});a(29)(I,"Promise");a(73)("Promise");var E=a(1).Promise;b(b.S+b.F*
!m,"Promise",{reject:function(a){var b=A(this);return(0,b.reject)(a),b.promise}});b(b.S+b.F*(h||!m),"Promise",{resolve:function(a){return w(h&&this===E?I:this,a)}});b(b.S+b.F*!(m&&a(80)(function(a){I.all(a).catch(G)})),"Promise",{all:function(a){var b=this,c=A(b),d=c.resolve,e=c.reject,f=n(function(){var c=[],f=0,h=1;y(a,!1,function(a){var k=f++,l=!1;c.push(void 0);h++;b.resolve(a).then(function(a){l||(l=!0,c[k]=a,--h||d(c))},e)});--h||d(c)});return f.e&&e(f.v),c.promise},race:function(a){var b=this,
c=A(b),d=c.reject,e=n(function(){y(a,!1,function(a){b.resolve(a).then(c.resolve,d)})});return e.e&&d(e.v),c.promise}})},function(b,c,a){var d=a(5),e=a(76).set,f=d.MutationObserver||d.WebKitMutationObserver,h=d.process,l=d.Promise,k="process"==a(25)(h);b.exports=function(){var a,b,c=function(){var c;for(k&&(c=h.domain)&&c.exit();a;){var d=a.fn;a=a.next;try{d()}catch(x){throw a?q():b=void 0,x;}}b=void 0;c&&c.enter()};if(k)var q=function(){h.nextTick(c)};else if(!f||d.navigator&&d.navigator.standalone)if(l&&
l.resolve){var y=l.resolve(void 0);q=function(){y.then(c)}}else q=function(){e.call(d,c)};else{var r=!0,u=document.createTextNode("");(new f(c)).observe(u,{characterData:!0});q=function(){u.data=r=!r}}return function(c){c={fn:c,next:void 0};b&&(b.next=c);a||(a=c,q());b=c}}},function(b,c,a){c=a(5).navigator;b.exports=c&&c.userAgent||""},function(b,c,a){b=a(3);var d=a(1),e=a(5),f=a(75),h=a(79);b(b.P+b.R,"Promise",{finally:function(a){var b=f(this,d.Promise||e.Promise),c="function"==typeof a;return this.then(c?
function(c){return h(b,a()).then(function(){return c})}:a,c?function(c){return h(b,a()).then(function(){throw c;})}:a)}})},function(b,c,a){b=a(3);var d=a(56),e=a(78);b(b.S,"Promise",{try:function(a){var b=d.f(this);a=e(a);return(a.e?b.reject:b.resolve)(a.v),b.promise}})},function(b,c,a){a(126);var d=a(1).Object;b.exports=function(a,b,c){return d.defineProperty(a,b,c)}},function(b,c,a){b=a(3);b(b.S+b.F*!a(11),"Object",{defineProperty:a(9).f})},function(b,c,a){function d(a){return(d="function"==typeof h&&
"symbol"==typeof f?function(a){return typeof a}:function(a){return a&&"function"==typeof h&&a.constructor===h&&a!==h.prototype?"symbol":typeof a})(a)}function e(a){return"function"==typeof h&&"symbol"===d(f)?b.exports=e=function(a){return d(a)}:b.exports=e=function(a){return a&&"function"==typeof h&&a.constructor===h&&a!==h.prototype?"symbol":d(a)},e(a)}var f=a(128),h=a(130);b.exports=e},function(b,c,a){b.exports=a(129)},function(b,c,a){a(22);a(27);b.exports=a(57).f("iterator")},function(b,c,a){b.exports=
a(131)},function(b,c,a){a(132);a(51);a(135);a(136);b.exports=a(1).Symbol},function(b,c,a){b=a(5);var d=a(17),e=a(11);c=a(3);var f=a(67),h=a(54).KEY,l=a(15),k=a(46),m=a(29),p=a(34),g=a(7),q=a(57),y=a(58),r=a(133),u=a(55),t=a(10),n=a(8),x=a(18),w=a(20),v=a(41),z=a(23),C=a(28),Q=a(134),I=a(83),J=a(48),G=a(9),A=a(24),D=I.f,B=G.f,L=Q.f,H=b.Symbol,O=b.JSON,P=O&&O.stringify,E=g("_hidden"),F=g("toPrimitive"),Y={}.propertyIsEnumerable,U=k("symbol-registry"),K=k("symbols"),R=k("op-symbols"),M=Object.prototype;
k="function"==typeof H&&!!J.f;var N=b.QObject,V=!N||!N.prototype||!N.prototype.findChild,T=e&&l(function(){return 7!=C(B({},"a",{get:function(){return B(this,"a",{value:7}).a}})).a})?function(a,b,c){var d=D(M,b);d&&delete M[b];B(a,b,c);d&&a!==M&&B(M,b,d)}:B,ca=function(a){var b=K[a]=C(H.prototype);return b._k=a,b},Z=k&&"symbol"==typeof H.iterator?function(a){return"symbol"==typeof a}:function(a){return a instanceof H},S=function(a,b,c){return a===M&&S(R,b,c),t(a),b=v(b,!0),t(c),d(K,b)?(c.enumerable?
(d(a,E)&&a[E][b]&&(a[E][b]=!1),c=C(c,{enumerable:z(0,!1)})):(d(a,E)||B(a,E,z(1,{})),a[E][b]=!0),T(a,b,c)):B(a,b,c)},W=function(a,b){t(a);for(var c,d=r(b=w(b)),e=0,f=d.length;f>e;)S(a,c=d[e++],b[c]);return a},da=function(a){var b=Y.call(this,a=v(a,!0));return!(this===M&&d(K,a)&&!d(R,a))&&(!(b||!d(this,a)||!d(K,a)||d(this,E)&&this[E][a])||b)};N=function(a,b){if(a=w(a),b=v(b,!0),a!==M||!d(K,b)||d(R,b)){var c=D(a,b);return!c||!d(K,b)||d(a,E)&&a[E][b]||(c.enumerable=!0),c}};var X=function(a){var b;a=L(w(a));
for(var c=[],e=0;a.length>e;)d(K,b=a[e++])||b==E||b==h||c.push(b);return c},ba=function(a){var b,c=a===M;a=L(c?R:w(a));for(var e=[],f=0;a.length>f;)!d(K,b=a[f++])||c&&!d(M,b)||e.push(K[b]);return e};k||(f((H=function(){if(this instanceof H)throw TypeError("Symbol is not a constructor!");var a=p(0<arguments.length?arguments[0]:void 0),b=function(c){this===M&&b.call(R,c);d(this,E)&&d(this[E],a)&&(this[E][a]=!1);T(this,a,z(1,c))};return e&&V&&T(M,a,{configurable:!0,set:b}),ca(a)}).prototype,"toString",
function(){return this._k}),I.f=N,G.f=S,a(82).f=Q.f=X,a(35).f=da,J.f=ba,e&&!a(26)&&f(M,"propertyIsEnumerable",da,!0),q.f=function(a){return ca(g(a))});c(c.G+c.W+c.F*!k,{Symbol:H});f="hasInstance isConcatSpreadable iterator match replace search species split toPrimitive toStringTag unscopables".split(" ");for(q=0;f.length>q;)g(f[q++]);A=A(g.store);for(f=0;A.length>f;)y(A[f++]);c(c.S+c.F*!k,"Symbol",{for:function(a){return d(U,a+="")?U[a]:U[a]=H(a)},keyFor:function(a){if(!Z(a))throw TypeError(a+" is not a symbol!");
for(var b in U)if(U[b]===a)return b},useSetter:function(){V=!0},useSimple:function(){V=!1}});c(c.S+c.F*!k,"Object",{create:function(a,b){return void 0===b?C(a):W(C(a),b)},defineProperty:S,defineProperties:W,getOwnPropertyDescriptor:N,getOwnPropertyNames:X,getOwnPropertySymbols:ba});y=l(function(){J.f(1)});c(c.S+c.F*y,"Object",{getOwnPropertySymbols:function(a){return J.f(x(a))}});O&&c(c.S+c.F*(!k||l(function(){var a=H();return"[null]"!=P([a])||"{}"!=P({a:a})||"{}"!=P(Object(a))})),"JSON",{stringify:function(a){for(var b,
c,d=[a],e=1;arguments.length>e;)d.push(arguments[e++]);if(c=b=d[1],(n(b)||void 0!==a)&&!Z(a))return u(b)||(b=function(a,b){if("function"==typeof c&&(b=c.call(this,a,b)),!Z(b))return b}),d[1]=b,P.apply(O,d)}});H.prototype[F]||a(14)(H.prototype,F,H.prototype.valueOf);m(H,"Symbol");m(Math,"Math",!0);m(b.JSON,"JSON",!0)},function(b,c,a){var d=a(24),e=a(48),f=a(35);b.exports=function(a){var b=d(a),c=e.f;if(c){var h;c=c(a);for(var p=f.f,g=0;c.length>g;)p.call(a,h=c[g++])&&b.push(h)}return b}},function(b,
c,a){var d=a(20),e=a(82).f,f={}.toString,h="object"==typeof window&&window&&Object.getOwnPropertyNames?Object.getOwnPropertyNames(window):[];b.exports.f=function(a){if(h&&"[object Window]"==f.call(a))try{var b=e(a)}catch(m){b=h.slice()}else b=e(d(a));return b}},function(b,c,a){a(58)("asyncIterator")},function(b,c,a){a(58)("observable")},function(b,c,a){b.exports=a(138)},function(b,c,a){a(139);b.exports=a(1).Object.getPrototypeOf},function(b,c,a){var d=a(18),e=a(69);a(70)("getPrototypeOf",function(){return function(a){return e(d(a))}})},
function(b,c,a){a(141);b.exports=a(1).Object.setPrototypeOf},function(b,c,a){b=a(3);b(b.S,"Object",{setPrototypeOf:a(142).set})},function(b,c,a){var d=a(8),e=a(10),f=function(a,b){if(e(a),!d(b)&&null!==b)throw TypeError(b+": can't set as prototype!");};b.exports={set:Object.setPrototypeOf||("__proto__"in{}?function(b,c,d){try{(d=a(13)(Function.call,a(83).f(Object.prototype,"__proto__").set,2))(b,[]),c=!(b instanceof Array)}catch(m){c=!0}return function(a,b){return f(a,b),c?a.__proto__=b:d(a,b),a}}({},
!1):void 0),check:f}},function(b,c,a){a(144);var d=a(1).Object;b.exports=function(a,b){return d.create(a,b)}},function(b,c,a){b=a(3);b(b.S,"Object",{create:a(28)})},function(b,c){b.exports=function(a){return-1!==Function.toString.call(a).indexOf("[native code]")}},function(b,c,a){function d(a,c,k){return function(){if("undefined"==typeof Reflect||!e||e.sham)return!1;if("function"==typeof Proxy)return!0;try{return Date.prototype.toString.call(e(Date,[],function(){})),!0}catch(m){return!1}}()?b.exports=
d=e:b.exports=d=function(a,b,c){var d=[null];d.push.apply(d,b);a=new (Function.bind.apply(a,d));return c&&f(a,c.prototype),a},d.apply(null,arguments)}var e=a(147),f=a(59);b.exports=d},function(b,c,a){b.exports=a(148)},function(b,c,a){a(149);b.exports=a(1).Reflect.construct},function(b,c,a){b=a(3);var d=a(28),e=a(16),f=a(10),h=a(8);c=a(15);var l=a(150),k=(a(5).Reflect||{}).construct,m=c(function(){function a(){}return!(k(function(){},[],a)instanceof a)}),p=!c(function(){k(function(){})});b(b.S+b.F*
(m||p),"Reflect",{construct:function(a,b){e(a);f(b);var c=3>arguments.length?a:e(arguments[2]);if(p&&!m)return k(a,b,c);if(a==c){switch(b.length){case 0:return new a;case 1:return new a(b[0]);case 2:return new a(b[0],b[1]);case 3:return new a(b[0],b[1],b[2]);case 4:return new a(b[0],b[1],b[2],b[3])}c=[null];return c.push.apply(c,b),new (l.apply(a,c))}c=c.prototype;c=d(h(c)?c:Object.prototype);var g=Function.apply.call(a,c,b);return h(g)?g:c}})},function(b,c,a){var d=a(16),e=a(8),f=a(77),h=[].slice,
l={};b.exports=Function.bind||function(a){var b=d(this),c=h.call(arguments,1),k=function(){var d=c.concat(h.call(arguments));if(this instanceof k){var e=d.length;if(!(e in l)){for(var g=[],m=0;m<e;m++)g[m]="a["+m+"]";l[e]=Function("F,a","return new F("+g.join(",")+")")}d=l[e](b,d)}else d=f(b,d,a);return d};return e(b.prototype)&&(k.prototype=b.prototype),k}},function(b,c,a){var d=a(152);b.exports=function(a){if(d(a)){for(var b=0,c=Array(a.length);b<a.length;b++)c[b]=a[b];return c}}},function(b,c,
a){b.exports=a(153)},function(b,c,a){a(154);b.exports=a(1).Array.isArray},function(b,c,a){b=a(3);b(b.S,"Array",{isArray:a(55)})},function(b,c,a){var d=a(156),e=a(160);b.exports=function(a){if(e(Object(a))||"[object Arguments]"===Object.prototype.toString.call(a))return d(a)}},function(b,c,a){b.exports=a(157)},function(b,c,a){a(22);a(158);b.exports=a(1).Array.from},function(b,c,a){var d=a(13);b=a(3);var e=a(18),f=a(71),h=a(72),l=a(33),k=a(159),m=a(50);b(b.S+b.F*!a(80)(function(a){Array.from(a)}),"Array",
{from:function(a){var b=e(a);var c="function"==typeof this?this:Array;var p=arguments.length;var r=1<p?arguments[1]:void 0,u=void 0!==r,t=0,n=m(b);if(u&&(r=d(r,2<p?arguments[2]:void 0,2)),null==n||c==Array&&h(n))for(c=new c(p=l(b.length));p>t;t++)k(c,t,u?r(b[t],t):b[t]);else for(b=n.call(b),c=new c;!(p=b.next()).done;t++)k(c,t,u?f(b,r,[p.value,t],!0):p.value);return c.length=t,c}})},function(b,c,a){var d=a(9),e=a(23);b.exports=function(a,b,c){b in a?d.f(a,b,e(0,c)):a[b]=c}},function(b,c,a){b.exports=
a(161)},function(b,c,a){a(27);a(22);b.exports=a(162)},function(b,c,a){var d=a(36),e=a(7)("iterator"),f=a(21);b.exports=a(1).isIterable=function(a){a=Object(a);return void 0!==a[e]||"@@iterator"in a||f.hasOwnProperty(d(a))}},function(b,c){b.exports=function(){throw new TypeError("Invalid attempt to spread non-iterable instance");}},function(b,c,a){function d(a){if(z(a)||!C(a))throw Q.error(new w(v.INVALID_ARGUMENT)),new w(v.INVALID_ARGUMENT);return 6E4*a}function e(a){throw I.error(a),a;}function f(a,
b){return new J.a(function(c,d){(G(a)||G(b))&&d(new w(v.INVALID_ARGUMENT));SymBfw.settings.loadSettingsContainer(a,b,function(a,b,e){e?d(Error(e)):!a||G(b)?d(new w(v.STORAGE_LOAD_FAILED)):c(b)})})}a.r(c);b=a(62);var h=a.n(b);b=a(63);var l=a.n(b);b=a(19);var k=a.n(b);b=a(37);var m=a.n(b);b=a(12);var p=a.n(b);b=a(0);var g=a.n(b);b=a(2);var q=a.n(b);b=a(4);var y=a.n(b);b=a(6);var r=a.n(b);b=a(38);var u=a.n(b);b=a(31);var t=a.n(b);b=a(61);var n=a.n(b);b=a(39);var x=a.n(b);b=a(86);var w=function(a){function b(a){var c,
d=a.message;a=a.code;return y()(this,b),c=u()(this,t()(b).call(this,d)),Error.captureStackTrace&&Error.captureStackTrace(n()(c),b),c.code=a||"missing_error_code",c}return x()(b,a),b}(a.n(b)()(Error)),v={API_SERVER_ERROR:{code:"api_server_error",message:"API server error."},ENTRY_NOT_FOUND_IN_CACHE:{code:"entry_not_found_in_cache",message:"Entry not found in cache."},STORAGE_LOAD_FAILED:{code:"storage_load_failed",message:"Failed to load settings container."},INVALID_ARGUMENT:{code:"invalid_argument",
message:"Argument provided to the function is not valid."},CLIENT_NOT_DEFINED:{code:"client_not_defined",message:"CompromisedPasswordClient is not defined."},SCHEDULER_INSTANCE_ERROR:{code:"scheduler_instance_arguments",message:"Scheduler is missing required arguments."},SCHEDULER_LOAD_CONTAINER_FAILED:{code:"scheduler_load_container_failed",message:"Scheduler load settings container has failed."},SCHEDULER_INVALID_TIMEOUT:{code:"scheduler_invalid_timeout",message:"Invalid timeout value to calculate remaining time to execute scheduler job"},
MISSING_REQUIRED_POLL_FREQUENCY_IN_MINS:{code:"missing_scheduler_frequency",message:"Scheduler cannot be instantied without providing POLL_FREQUENCY_IN_MINS"},INVALID_LOGIN_ACCOUNTS:{code:"invalid_login_accounts",message:"Invalid login accounts passed."},NO_LOGIN_ACCOUNT:{code:"no_login_account",message:"No login accounts passed."},ACCOUNT_WITH_INVALID_PROPERTY_PASSWORD:{code:"account_with_invalid_property_password",message:"Account has invalid property `password`."},ACCOUNT_WITH_INVALID_PROPERTY_GUID:{code:"account_with_invalid_property_guid",
message:"Account has invalid property `guid`."},TELEMETRY_PAYLOAD_SHOULD_BE_STRING:{code:"telemetry_payload",message:"Telemetry payload should be string."}};b=SymBfw;c=b.utils;var z=c.isNil,C=c.isInteger,Q=b.logger,I=SymBfw.logger;b=a(60);var J=a.n(b),G=SymBfw.utils.isNil;b=SymBfw.utils;var A=b.isInteger,D=b.isFunction,B=function(){function a(b,c){y()(this,a);A(b)&&D(c)||e(new w(v.SCHEDULER_INSTANCE_ERROR));this._frequencyInMins=b;this._handleSchedulerTimeout=c;this.schedulerContainer=this._clearSchedulerTimeout=
null}var b,c,h;return r()(a,[{key:"init",value:(h=q()(g.a.mark(function ea(){return g.a.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return a.next=2,f("83BCB9F9-B495-47F4-ABE4-BA02281530B4",!0);case 2:this.schedulerContainer=a.sent;case 3:case "end":return a.stop()}},ea,this)})),function(){return h.apply(this,arguments)})},{key:"_getDefaultFrequencyInMillis",value:function(){return d(this._frequencyInMins)}},{key:"fetchLastExecTime",value:function(){return this.schedulerContainer.getObject("CAA0391F-20B8-43B2-A6A8-977D84353838")}},
{key:"_getRemainingTimeToExecInMillis",value:function(){var a=p()(),b=this.fetchLastExecTime(),c=this._getDefaultFrequencyInMillis();if(!A(b))return 0;(!A(c)||0>b||b>a)&&e(new w(v.SCHEDULER_INVALID_TIMEOUT));a=c-(a-b);return 0>=a?0:a}},{key:"_setSchedulerTimeout",value:function(){var a=this._getRemainingTimeToExecInMillis();if(0===a)return this._handleSchedulerTimeout(),void this._stopSchedulerTimeout();this._clearSchedulerTimeout=setTimeout(this._handleSchedulerTimeout,a)}},{key:"_stopSchedulerTimeout",
value:function(){clearTimeout(this._clearSchedulerTimeout);this._clearSchedulerTimeout=null}},{key:"start",value:(c=q()(g.a.mark(function ja(){return g.a.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:this._setSchedulerTimeout();case 1:case "end":return a.stop()}},ja,this)})),function(){return c.apply(this,arguments)})},{key:"stop",value:(b=q()(g.a.mark(function fa(){return g.a.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:this._stopSchedulerTimeout();case 1:case "end":return a.stop()}},
fa,this)})),function(){return b.apply(this,arguments)})}]),a}(),L={url:"https://api.pwnedpasswords.com/range"};b=a(87);var H=a.n(b);b=SymBfw;c=b.utils;var O=c.isNil,P=c.isString,E=c.isObject,F=c.isArray,Y=b.logger,U=new (function(){function a(){y()(this,a);this.cachedRecords=null}var b;return r()(a,[{key:"init",value:(b=q()(g.a.mark(function aa(){return g.a.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return a.next=2,f("A2AF891A-FE1D-40C1-AB87-C625E37D2579",!0);case 2:this.cachedRecords=a.sent;
case 3:case "end":return a.stop()}},aa,this)})),function(){return b.apply(this,arguments)})},{key:"get",value:function(a){P(a)||e(new w(v.INVALID_ARGUMENT));var b=this.cachedRecords.getObject(a);return O(b)?{guid:a,timestamp:null,error:v.ENTRY_NOT_FOUND_IN_CACHE}:b}},{key:"set",value:function(a,b){P(a)&&E(b)||e(new w(v.INVALID_ARGUMENT));this.cachedRecords.setObject(a,b)}},{key:"remove",value:function(a){P(a)||e(new w(v.INVALID_ARGUMENT));this.cachedRecords.removeObject(a)}},{key:"getAll",value:function(){return this.cachedRecords.getCollection()}},
{key:"removeAll",value:function(){try{SymBfw.settings.resetSettingsCollection("A2AF891A-FE1D-40C1-AB87-C625E37D2579",function(a,b){if(!a)throw Error(b);})}catch(aa){e(Error(aa))}}},{key:"pruneCache",value:function(a){var b=this;F(a)||e(new w(v.INVALID_ARGUMENT));var c=[],d=this.getAll();k()(d).forEach(function(d){a.includes(d)||(b.cachedRecords.removeObject(d),c=[].concat(H()(c),[d]))});Y.info("".concat(c.length," guids was removed from the cacheStorage: [").concat(c,"]"))}}]),a}());b=function(){function a(){if(y()(this,
a),this.constructor===a)throw Error("Abstract classes cannot be instantiated");}var b;return r()(a,[{key:"init",value:function(a){throw Error("API not implemented");}},{key:"getLeakedDetails",value:(b=q()(g.a.mark(function ea(a,b){return g.a.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:throw Error("API not implemented");case 1:case "end":return a.stop()}},ea)})),function(a,c){return b.apply(this,arguments)})}]),a}();c=a(32);var K=a.n(c);a=SymBfw;var R=a.utils.isString,M=a.logger,N=new (function(){function a(){y()(this,
a);this.parameters={CATEGORY:SymBfw.telemetryConstants.parameters.CATEGORY,ACTION:SymBfw.telemetryConstants.parameters.ACTION,PAYLOAD:SymBfw.telemetryConstants.parameters.LABEL,HIT_TYPE:SymBfw.telemetryConstants.parameters.HIT_TYPE}}return r()(a,[{key:"send",value:function(a,b,c){var d;if(!R(a)||!R(b))throw M.error(new w(v.INVALID_ARGUMENT)),new w(v.INVALID_ARGUMENT);if(!R(c))throw M.error(v.TELEMETRY_PAYLOAD_SHOULD_BE_STRING),new w(v.TELEMETRY_PAYLOAD_SHOULD_BE_STRING);a=(d={},K()(d,this.parameters.CATEGORY,
a),K()(d,this.parameters.ACTION,b),K()(d,this.parameters.PAYLOAD,c),K()(d,this.parameters.HIT_TYPE,SymBfw.telemetryConstants.HIT_TYPE.EVENT),d);return(SymBfw.telemetry||SymBfw.telemetryProxy).send(a)}},{key:"sendSchedulerMissedTelemetry",value:function(a,b,c){a=(a-b)/d(c)-1;0<a&&this.send("scheduler","missed_scheduler_execution","".concat(Math.floor(a)))}},{key:"sendNewBreachTelemetry",value:function(a,b){b=b.filter(function(b){return!a.includes(b)}).length;0<b&&this.send("new_breach","info","".concat(b))}}]),
a}());a=SymBfw;var V=a.utils.objectHas,T=a.logger,ca=function(a){function b(){var a;return y()(this,b),(a=u()(this,t()(b).call(this)))._url="",a}var c,d;return x()(b,a),r()(b,[{key:"init",value:function(a){V(a,"url")||e(new w(v.INVALID_ARGUMENT));this._url=a.url}},{key:"_normalizeResponse",value:function(a,b,c){a={guid:a,timestamp:p()()};(c=c.split("\n").find(function(a){return a.includes(b)}))?(c=Number(c.split(":")[1]),a.data={leakCount:c,isLeaked:0<c}):a.data={leakCount:0,isLeaked:!1};return a}},
{key:"_handleError",value:function(a,b){var c=b.code;b=b.message;return{guid:a,timestamp:p()(),error:{code:c,message:b}}}},{key:"_queryServer",value:(d=q()(g.a.mark(function fa(a,b){var c,d;return g.a.wrap(function(f){for(;;)switch(f.prev=f.next){case 0:return c=b.cacheBuster,f.next=3,fetch("".concat(this._url,"/").concat(a,"?").concat(c));case 3:return(d=f.sent).ok||(N.send("server","failure","".concat(d.status)),e(new w(v.API_SERVER_ERROR))),f.abrupt("return",d.text());case 6:case "end":return f.stop()}},
fa,this)})),function(a,b){return d.apply(this,arguments)})},{key:"getLeakedDetails",value:(c=q()(g.a.mark(function ka(a,b){var c,d,f,h,k,l,m,p,n;return g.a.wrap(function(g){for(;;)switch(g.prev=g.next){case 0:if(V(b,"cacheBuster")||e(new w(v.INVALID_ARGUMENT)),V(a,"guid")){g.next=4;break}return c=new w(v.ACCOUNT_WITH_INVALID_PROPERTY_GUID),g.abrupt("return",this._handleError(a.guid,c));case 4:if(a.password){g.next=7;break}return d=new w(v.ACCOUNT_WITH_INVALID_PROPERTY_PASSWORD),g.abrupt("return",
this._handleError(a.guid,d));case 7:return h=a.guid,k=a.password,l=KJUR.crypto.Util.sha1(k).toUpperCase(),m=l.substring(0,5),p=l.substring(5),g.prev=11,g.next=14,this._queryServer(m,b);case 14:n=g.sent;f=this._normalizeResponse(h,p,n);g.next=22;break;case 18:g.prev=18,g.t0=g.catch(11),f=this._handleError(h,g.t0),T.error(g.t0);case 22:return g.abrupt("return",f);case 23:case "end":return g.stop()}},ka,this,[[11,18]])})),function(a,b){return c.apply(this,arguments)})}]),b}(b),Z=new (function(){function a(){y()(this,
a);this._requestManagerInstance=null}return r()(a,[{key:"getInstance",value:function(a){return this._requestManagerInstance=new ca,this._requestManagerInstance.init(a),this._requestManagerInstance}}]),a}());a=SymBfw;var S=a.logger;a=a.utils;var W=a.isNil,da=a.isBoolean,X=a.isFunction,ba=a.isArray,ia=a.isInteger;a=function(){function a(){y()(this,a);this._scheduler=this._requestManager=this._cacheStorage=this._config=this._compromisedPasswordClient=null;this._isCancelled=!1}var b,c,d,f,n,u,t,x;return r()(a,
[{key:"init",value:(x=q()(g.a.mark(function ha(a){return g.a.wrap(function(b){for(;;)switch(b.prev=b.next){case 0:return W(a)&&e(new w(v.CLIENT_NOT_DEFINED)),this._compromisedPasswordClient=a,this._config=this._compromisedPasswordClient.getConfig(),!W(this._config)&&ia(this._config.POLL_FREQUENCY_IN_MINS)||e(new w(v.MISSING_REQUIRED_POLL_FREQUENCY_IN_MINS)),this._cacheStorage=U,this._requestManager=Z.getInstance(L),this._scheduler=new B(this._config.POLL_FREQUENCY_IN_MINS,this._handleSchedulerTimeout.bind(this)),
b.next=9,this._scheduler.init();case 9:return b.next=11,this._cacheStorage.init();case 11:case "end":return b.stop()}},ha,this)})),function(a){return x.apply(this,arguments)})},{key:"_getAllLoginAccounts",value:(t=q()(g.a.mark(function ha(){var a;return g.a.wrap(function(b){for(;;)switch(b.prev=b.next){case 0:return b.next=2,this._compromisedPasswordClient.getAllLoginAccounts();case 2:return a=b.sent,ba(a)||e(new w(v.INVALID_LOGIN_ACCOUNTS)),a.length||e(new w(v.NO_LOGIN_ACCOUNT)),b.abrupt("return",
a);case 6:case "end":return b.stop()}},ha,this)})),function(){return t.apply(this,arguments)})},{key:"_pruneCachedAccounts",value:function(a){a=a.map(function(a){return a.guid});this._cacheStorage.pruneCache(a)}},{key:"_handleSchedulerTimeout",value:(u=q()(g.a.mark(function la(){var a,b,c,d,e,f,n,q,r,u,t,w,v,x,z,y,A,B,D,C;return g.a.wrap(function(g){for(;;)switch(g.prev=g.next){case 0:return a=p()(),b=new m.a,g.prev=2,this._compromisedPasswordClient.onSchedulerStarted(),S.info("[CompromisedPassword]: Scheduler started and called onSchedulerStarted method"),
g.next=7,this._getAllLoginAccounts();case 7:c=g.sent,this._pruneCachedAccounts(c),d=k()(this._cacheStorage.getAll()),e=[],f={cacheBuster:a},n=0,q=!0,r=!1,u=void 0,g.prev=16,t=l()(c);case 18:if(q=(w=t.next()).done){g.next=42;break}if(v=w.value,x=v.password,z=KJUR.crypto.Util.sha1(x),y=b.get(z),A=void 0,!y){g.next=28;break}A=h()({},y,{guid:v.guid});g.next=36;break;case 28:return B=p()(),g.next=31,this._requestManager.getLeakedDetails(v,f);case 31:A=g.sent,D=p()(),b.set(z,A),n+=D-B;case 36:e.push(A),
this._cacheStorage.set(A.guid,A),this._compromisedPasswordClient.handleCompromisedPasswordResult(A);case 39:q=!0;g.next=18;break;case 42:g.next=48;break;case 44:g.prev=44,g.t0=g.catch(16),r=!0,u=g.t0;case 48:g.prev=48,g.prev=49,q||null==t.return||t.return();case 51:if(g.prev=51,!r){g.next=54;break}throw u;case 54:return g.finish(51);case 55:return g.finish(48);case 56:b.clear();this._compromisedPasswordClient.onSchedulerCompleted(e);S.info("[CompromisedPassword]: Scheduler finished and called onSchedulerCompleted method with results payload");
C=k()(this._cacheStorage.getAll());N.sendNewBreachTelemetry(d,C);N.send("scheduler","accounts_processing_time","".concat(n));g.next=70;break;case 64:g.prev=64,g.t1=g.catch(2),S.error(g.t1),b.clear(),this._compromisedPasswordClient.onSchedulerCompleted(g.t1),S.info("[CompromisedPassword]: Scheduler had an error and called onSchedulerCompleted method with error payload");case 70:this._scheduler.schedulerContainer.setObject("CAA0391F-20B8-43B2-A6A8-977D84353838",a);case 71:case "end":return g.stop()}},
la,this,[[2,64],[16,44,48,56],[49,,51,55]])})),function(){return u.apply(this,arguments)})},{key:"startScheduler",value:(n=q()(g.a.mark(function ma(){return g.a.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return a.next=2,this._scheduler.start();case 2:case "end":return a.stop()}},ma,this)})),function(){return n.apply(this,arguments)})},{key:"stopScheduler",value:(f=q()(g.a.mark(function na(){return g.a.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return a.next=2,this._scheduler.stop();
case 2:case "end":return a.stop()}},na,this)})),function(){return f.apply(this,arguments)})},{key:"startPasswordCheck",value:(d=q()(g.a.mark(function oa(){var a,b,c,d,f,n,q,r,u,t,x,z,y,A,B,D,C,G,E,H,I,J,F=arguments;return g.a.wrap(function(g){for(;;)switch(g.prev=g.next){case 0:if(a=0<F.length&&void 0!==F[0]&&F[0],b=1<F.length?F[1]:void 0,c=2<F.length?F[2]:void 0,da(a)&&X(c)||e(new w(v.INVALID_ARGUMENT)),d=p()(),f=new m.a,g.prev=6,n=ba(b)&&0<b.length?b.slice():b,!W(n)){g.next=13;break}return g.next=
11,this._getAllLoginAccounts();case 11:n=g.sent,this._pruneCachedAccounts(n);case 13:q=k()(this._cacheStorage.getAll()),r=0,u={cacheBuster:d},t=!0,x=!1,z=void 0,g.prev=19,y=l()(n);case 21:if(t=(A=y.next()).done){g.next=52;break}if(B=A.value,!this._isCancelled){g.next=29;break}return this._isCancelled=!1,D=p()()-d,S.info("[CompromisedPassword]: Start password check was cancelled"),N.send("manual_trigger","cancelled","".concat(D)),g.abrupt("break",52);case 29:if(C=void 0,!a){g.next=46;break}if(G=B.password,
E=KJUR.crypto.Util.sha1(G),!(H=f.get(E))){g.next=38;break}C=h()({},H,{guid:B.guid});g.next=43;break;case 38:return g.next=40,this._requestManager.getLeakedDetails(B,u);case 40:C=g.sent,f.set(E,C),r++;case 43:this._cacheStorage.set(C.guid,C);g.next=48;break;case 46:I=B.guid,C=this._cacheStorage.get(I);case 48:c(C);case 49:t=!0;g.next=21;break;case 52:g.next=58;break;case 54:g.prev=54,g.t0=g.catch(19),x=!0,z=g.t0;case 58:g.prev=58,g.prev=59,t||null==y.return||y.return();case 61:if(g.prev=61,!x){g.next=
64;break}throw z;case 64:return g.finish(61);case 65:return g.finish(58);case 66:f.clear();a?N.send("manual_trigger","info","".concat(r)):N.sendSchedulerMissedTelemetry(d,this._scheduler.fetchLastExecTime(),this._config.POLL_FREQUENCY_IN_MINS);J=k()(this._cacheStorage.getAll());N.sendNewBreachTelemetry(q,J);g.next=76;break;case 72:g.prev=72,g.t1=g.catch(6),f.clear(),e(g.t1);case 76:case "end":return g.stop()}},oa,this,[[6,72],[19,54,58,66],[59,,61,65]])})),function(){return d.apply(this,arguments)})},
{key:"cancelPasswordCheck",value:(c=q()(g.a.mark(function pa(){return g.a.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:this._isCancelled=!0;case 1:case "end":return a.stop()}},pa,this)})),function(){return c.apply(this,arguments)})},{key:"clearCache",value:(b=q()(g.a.mark(function qa(){return g.a.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:this._cacheStorage.removeAll(),N.send("cache_storage_clearing","info","clear_cache");case 2:case "end":return a.stop()}},qa,this)})),function(){return b.apply(this,
arguments)})}]),a}();b=function(){function a(){if(y()(this,a),this.constructor===a)throw Error("Abstract classes cannot be instantiated");}var b;return r()(a,[{key:"getConfig",value:function(){throw Error("API not implemented");}},{key:"getAllLoginAccounts",value:(b=q()(g.a.mark(function aa(){return g.a.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:throw Error("API not implemented");case 1:case "end":return a.stop()}},aa)})),function(){return b.apply(this,arguments)})},{key:"onSchedulerCompleted",
value:function(a){throw Error("API not implemented");}},{key:"onSchedulerStarted",value:function(){throw Error("API not implemented");}},{key:"handleCompromisedPasswordResult",value:function(a){throw Error("API not implemented");}}]),a}();console.log("SDK compromissed password BG");window.CompromisedPasswordSDK={};window.CompromisedPasswordSDK.compromisedPasswordManager=new a;window.CompromisedPasswordSDK.ICompromisedPasswordClient=b}]);
