var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(c||"")+"_"+b++,c)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
!function(a,b){"object"==typeof exports&&"object"==typeof module?module.exports=b():"function"==typeof define&&define.amd?define([],b):"object"==typeof exports?exports.fgHelperSDK=b():a.fgHelperSDK=b()}(window,function(){return function(a){function b(d){if(c[d])return c[d].exports;var e=c[d]={i:d,l:!1,exports:{}};return a[d].call(e.exports,e,e.exports,b),e.l=!0,e.exports}var c={};return b.m=a,b.c=c,b.d=function(a,e,c){b.o(a,e)||Object.defineProperty(a,e,{enumerable:!0,get:c})},b.r=function(a){$jscomp.initSymbol();
$jscomp.initSymbol();$jscomp.initSymbol();"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(a,Symbol.toStringTag,{value:"Module"});Object.defineProperty(a,"__esModule",{value:!0})},b.t=function(a,e){if((1&e&&(a=b(a)),8&e)||4&e&&"object"==typeof a&&a&&a.__esModule)return a;var d=Object.create(null);if(b.r(d),Object.defineProperty(d,"default",{enumerable:!0,value:a}),2&e&&"string"!=typeof a)for(var c in a)b.d(d,c,function(b){return a[b]}.bind(null,c));return d},b.n=function(a){var e=
a&&a.__esModule?function(){return a.default}:function(){return a};return b.d(e,"a",e),e},b.o=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)},b.p="",b(b.s=0)}({"./source/FGHelperConstants.js":function(a,b,c){b.a={JWT_CONSTANTS:{FG_JWT_SESSION_STORAGE_NAME:"fgMetaDataJWS",FG_JWT_ENCRYPTION_METHOD:"RS256"},MESSAGE_TYPE:{FG_VERIFY_EXTRACT_URL:"a09a5397-913f-44a0-94fd-1b5ca23546ff",JWT_FAILURE_TELEMETRY:"d985e9bd-5af3-4d3c-ab3a-633afed4b407"},FG_PUBLIC_KEY_SERVER_URL:"https://fgl-fileserver.s3-eu-west-1.amazonaws.com/Norton-Extension/isolation_meta_data_public.pem",
TELEMETRY_CATEGORY:{NPW_ISOLATION:"npw_isolation"},ACTION_TYPE:{UNABLE_TO_GET_PUBLIC_KEY:"unable_to_get_public_key",VERIFICATION_FAILS:"verification_fails",UNABLE_TO_GET_JWT:"unable_to_get_jwt",ISOLATION_MODE_WITH_NPW:"isolation_mode_with_npw"},ADDITIONAL_PARAMS:{ISOLATION_URL:"isolation_url"}}},"./source/FGHelperIndex.js":function(a,b,c){c.r(b);var d=c("./source/FGHelperConstants.js"),e=SymBfw.utils.isString;a=function(){};a.prototype.verifyBlob=function(a,b,c){var g=null;if(!e(a)||!e(b)||!e(c))return!1;
b=KEYUTIL.getKey(b);try{g=KJUR.jws.JWS.verify(a,b,c)}catch(u){SymBfw.logger.error("Failed to verify JWT blob"),g=!1}return g};a.prototype.extractURL=function(a){if(!e(a))return null;a=a.split(".");a=b64utos(a[1]);a=KJUR.jws.JWS.readSafeJSONString(a);return JSON.parse(a.data).Url};var l=new a;a=SymBfw.utils;var n=a.isntNil,p=a.isNil,h=a.isString;a=function(){this._eventCategory=d.a.TELEMETRY_CATEGORY.NPW_ISOLATION;this._productVersion=null};a.prototype.init=function(a){if(p(a))throw Error("config object null");
this._productVersion=a._productVersion};a.prototype.sendPublicKeyFailureTelemetry=function(){this.send(this._eventCategory,d.a.ACTION_TYPE.UNABLE_TO_GET_PUBLIC_KEY,this._productVersion)};a.prototype.sendVerificationFailureTelemetry=function(a){this.send(this._eventCategory,d.a.ACTION_TYPE.VERIFICATION_FAILS,this._productVersion,a)};a.prototype.sendDataBlobFailureTelemetry=function(){this.send(this._eventCategory,d.a.ACTION_TYPE.UNABLE_TO_GET_JWT,this._productVersion)};a.prototype.send=function(a,
b,c,e){if(!h(a)||!h(b)||!h(c))throw Error("parameter must be of type string");var d={};d[SymBfw.telemetryConstants.parameters.HIT_TYPE]=SymBfw.telemetryConstants.HIT_TYPE.EVENT;d[SymBfw.telemetryConstants.parameters.CATEGORY]=a;d[SymBfw.telemetryConstants.parameters.ACTION]=b;d[SymBfw.telemetryConstants.parameters.LABEL]=c;n(e)&&(d[SymBfw.telemetryConstants.parameters.CUSTOM_DIMENSION1]=e);SymBfw.telemetry.send(d)};var f=new a,r=SymBfw.utils.isString,k=function(){this._productVersion=null};$jscomp.global.Object.defineProperties(k.prototype,
{prodVersion:{configurable:!0,enumerable:!0,set:function(a){if(!r(a))throw Error("Product version must be of type string");this._productVersion=a},get:function(){return this._productVersion}}});var m=SymBfw.utils,t=SymBfw.extensionAdapter;a=function(){this._publicKey=null};a.prototype.init=function(a){var b=this;if(!(a instanceof k))throw new TypeError("FGHelper SDK initialization Failed - Invalid Configuration Object");f.init(a);m.safeFetch(d.a.FG_PUBLIC_KEY_SERVER_URL).then(function(a){if(m.isSuccessCodeLocalFile(a.status))return a.text();
throw f.sendPublicKeyFailureTelemetry(),Error("error in fetching public key");}).then(function(a){b._publicKey=a}).catch(function(a){throw f.sendPublicKeyFailureTelemetry(),a;});t.addMessageListener(this.handleMessage.bind(this))};a.prototype.handleMessage=function(a,b,c){switch(a.id){case d.a.MESSAGE_TYPE.FG_VERIFY_EXTRACT_URL:try{c={},c.urlLoaded=this._verifyAndExtractUrl(a.payload),b(c)}catch(q){SymBfw.logger.error("Failed to verify JWT."+q)}break;case d.a.MESSAGE_TYPE.JWT_FAILURE_TELEMETRY:f.sendDataBlobFailureTelemetry()}};
a.prototype._verifyAndExtractUrl=function(a){if(0==l.verifyBlob(a.jwtBlob,this._publicKey,d.a.JWT_CONSTANTS.FG_JWT_ENCRYPTION_METHOD))throw f.sendVerificationFailureTelemetry(a.isolationURL),Error("error in verification");return l.extractURL(a.jwtBlob)};a=new a;b.default={fgHelperBG:a,FGHelperConfig:k}},0:function(a,b,c){a.exports=c("./source/FGHelperIndex.js")}}).default});
