var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(c||"")+"_"+b++,c)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.inherits=function(a,b){a.prototype=$jscomp.objectCreate(b.prototype);a.prototype.constructor=a;if($jscomp.setPrototypeOf){var c=$jscomp.setPrototypeOf;c(a,b)}else for(c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.superClass_=b.prototype};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(a){return a instanceof e?a:new e(function(b,c){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){d(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];a[b]=null;try{c()}catch(p){this.asyncThrow_(p)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var e=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(h){b.reject(h)}};e.prototype.createResolveAndReject_=function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}var b=this,c=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};e.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};e.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(h){this.reject_(h);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};e.prototype.reject_=function(a){this.settle_(2,a)};e.prototype.fulfill_=function(a){this.settle_(1,a)};e.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)g.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var g=new b;e.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};e.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(p){c.reject(p)}};e.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{d(a(b))}catch(u){g(u)}}:b}var d,g,k=new e(function(a,b){d=a;g=b});this.callWhenSettled_(c(a,d),c(b,g));return k};
e.prototype.catch=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?g.asyncExecute(c):this.onSettledCallbacks_.push(c)};e.resolve=c;e.reject=function(a){return new e(function(b,c){c(a)})};e.race=function(a){return new e(function(b,d){for(var e=$jscomp.makeIterator(a),g=e.next();!g.done;g=e.next())c(g.value).callWhenSettled_(b,
d)})};e.all=function(a){var b=$jscomp.makeIterator(a),d=b.next();return d.done?c([]):new e(function(a,e){function g(b){return function(c){k[b]=c;h--;0==h&&a(k)}}var k=[],h=0;do k.push(void 0),h++,c(d.value).callWhenSettled_(g(k.length-1),e),d=b.next();while(!d.done)})};return e},"es6","es3");$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var c=a.next();$jscomp.generator.ensureIteratorResultIsObject_(c);if(c.done)this.yieldResult=c.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(c.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var d=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(d);if(!d.done)return this.context_.stop_(),d;var e=d.value}catch(g){return this.context_.yieldAllIterator_=null,this.context_.throw_(g),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(b){return a.next(b)}function c(b){return a.throw(b)}return new Promise(function(d,e){function g(a){a.done?d(a.value):Promise.resolve(a.value).then(b,c).then(g,e)}g(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};$jscomp.polyfill("Object.entries",function(a){return a?a:function(a){var b=[],d;for(d in a)$jscomp.owns(a,d)&&b.push([d,a[d]]);return b}},"es8","es3");$jscomp.polyfill("Object.values",function(a){return a?a:function(a){var b=[],d;for(d in a)$jscomp.owns(a,d)&&b.push(a[d]);return b}},"es8","es3");
!function(a,b){"object"==typeof exports&&"object"==typeof module?module.exports=b():"function"==typeof define&&define.amd?define([],b):"object"==typeof exports?exports.HeartbeatSDK=b():a.HeartbeatSDK=b()}(window,function(){return function(a){function b(d){if(c[d])return c[d].exports;var e=c[d]={i:d,l:!1,exports:{}};return a[d].call(e.exports,e,e.exports,b),e.l=!0,e.exports}var c={};return b.m=a,b.c=c,b.d=function(a,c,g){b.o(a,c)||Object.defineProperty(a,c,{enumerable:!0,get:g})},b.r=function(a){$jscomp.initSymbol();
$jscomp.initSymbol();$jscomp.initSymbol();"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(a,Symbol.toStringTag,{value:"Module"});Object.defineProperty(a,"__esModule",{value:!0})},b.t=function(a,c){if((1&c&&(a=b(a)),8&c)||4&c&&"object"==typeof a&&a&&a.__esModule)return a;var d=Object.create(null);if(b.r(d),Object.defineProperty(d,"default",{enumerable:!0,value:a}),2&c&&"string"!=typeof a)for(var e in a)b.d(d,e,function(b){return a[b]}.bind(null,e));return d},b.n=function(a){var c=
a&&a.__esModule?function(){return a.default}:function(){return a};return b.d(c,"a",c),c},b.o=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)},b.p="",b(b.s=0)}({"./source/HBIndex.js":function(a,b,c){c.r(b);var d={portal:"WEB_APPLICATION",mobile:"MOBILE_APPLICATION",extension:"BROWSER_EXTENSION"},e=function(){this._userLang=this._apiKey=this._dataSource=this._machineId=this._prodVersion=this._prodName=null;this._retryIntervalMillis=864E5;this.install={};this.install.isInstallPingEnabled=
!0;this.install.isFreshInstall=null;this.heartBeat={};this.heartBeat.isHeartBeatPingEnabled=!0;this.heartBeat.heartBeatIntervalInMilliSec=null;this._isLocalStorageNeeded=!1;this._isTelemetryEnabled=null};$jscomp.global.Object.defineProperties(e.prototype,{prodName:{configurable:!0,enumerable:!0,set:function(a){this._prodName=a},get:function(){return this._prodName}},prodVersion:{configurable:!0,enumerable:!0,set:function(a){this._prodVersion=a},get:function(){return this._prodVersion}},machineId:{configurable:!0,
enumerable:!0,set:function(a){this._machineId=a},get:function(){return this._machineId}},apiKey:{configurable:!0,enumerable:!0,set:function(a){this._apiKey=a},get:function(){return this._apiKey}},dataSource:{configurable:!0,enumerable:!0,set:function(a){this._dataSource=d[a]},get:function(){return this._dataSource}},userLanguage:{configurable:!0,enumerable:!0,set:function(a){this._userLang=a},get:function(){return this._userLang}},retryIntervalMillis:{configurable:!0,enumerable:!0,set:function(a){this._retryIntervalMillis=
a},get:function(){return this._retryIntervalMillis}},isInstallPingEnabled:{configurable:!0,enumerable:!0,set:function(a){this.install.isInstallPingEnabled=a},get:function(){return this.install.isInstallPingEnabled}},isFreshInstall:{configurable:!0,enumerable:!0,set:function(a){this.install.isFreshInstall=a},get:function(){return this.install.isFreshInstall}},isHeartBeatPingEnabled:{configurable:!0,enumerable:!0,set:function(a){this.heartBeat.isHeartBeatPingEnabled=a},get:function(){return this.heartBeat.isHeartBeatPingEnabled}},
heartBeatIntervalInMilliSec:{configurable:!0,enumerable:!0,set:function(a){this.heartBeat.heartBeatIntervalInMilliSec=a},get:function(){return this.heartBeat.heartBeatIntervalInMilliSec}},isLocalStorageNeeded:{configurable:!0,enumerable:!0,set:function(a){this._isLocalStorageNeeded=a},get:function(){return this._isLocalStorageNeeded}},isTelemetryEnabled:{configurable:!0,enumerable:!0,set:function(a){this._isTelemetryEnabled=a},get:function(){return this._isTelemetryEnabled}}});a=function(){};a.prototype.perform=
function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){throw Error("Derived class needs to implement this function");})};c=function(){this._container={}};c.prototype.loadContainer=function(a){var b=this;return new Promise(function(f,c){b.isLocalStorageNeeded=a;b.isLocalStorageNeeded?(b.container=window.localStorage,f(!0)):SymBfw.settings.loadSettingsContainer("HEARTBEAT_SDK_CONTAINER",!0,function(a,d,l){(!1===a||SymBfw.utils.isNil(d))&&c(l);b.container=d;f(!0)})})};c.prototype.getContainerByName=
function(a){if(SymBfw.utils.isNil(a)||SymBfw.utils.isNil(this.container))throw Error("Unable to retrieve the container value");return this.isLocalStorageNeeded?this.container.getItem(a):this.container.getObject(a)};c.prototype.setContainerByName=function(a,b){if(SymBfw.utils.isNil(a)||SymBfw.utils.isNil(this.container))throw Error("Unable to set the container value");this.isLocalStorageNeeded?this.container.setItem(a,b):this.container.setObject(a,b)};$jscomp.global.Object.defineProperties(c.prototype,
{container:{configurable:!0,enumerable:!0,get:function(){return this._container.storage},set:function(a){this._container.storage=a}},isLocalStorageNeeded:{configurable:!0,enumerable:!0,get:function(){return this._container.isLocalStorageNeeded},set:function(a){this._container.isLocalStorageNeeded=a}}});var g=Object.freeze(new c),k=SymBfw.utils.isNil;c=function(){this.defaultParameters={};this.userLang=this.apiKey=this.dataSource=this.machineId=this.prodVersion=this.prodName=null};c.prototype.init=
function(a){if(k(a)||0===Object.keys(a).length)throw Error("configObj cannot be null");this.prodName=a.prodName;this.prodVersion=a.prodVersion;this.machineId=a.machineId;this.dataSource=a.dataSource;this.apiKey=a.apiKey;this.userLang=a.userLanguage};c.prototype._constructQueryParams=function(a){var b="";a=$jscomp.makeIterator(Object.entries(a));for(var f=a.next();!f.done;f=a.next()){var c=$jscomp.makeIterator(f.value);f=c.next().value;c=c.next().value;b+=f+"="+c+"&"}return b.substring(0,b.length-
1)};c.prototype._constructDefaultParams=function(){var a={};return this.defaultParameters=(a.an=this.prodName,a.av=this.prodVersion,a.cid=this.machineId,a.ds=this.dataSource,a.tid=this.apiKey,a.ul=this.userLang,a.v=1,a.aip=1,a.t="event",a.cd2=this.machineId,a),this._constructQueryParams(this.defaultParameters)};c.prototype.send=function(a){var b=this,f,c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(d){if(1==d.nextAddress){if(k(a))return d.return(Promise.reject("parameters are required for sending telemetry events"));
f=b._constructDefaultParams();f+="&"+b._constructQueryParams(a);c={method:"POST",body:f};d.setCatchFinallyBlocks(2);return d.yield(fetch("https://www.google-analytics.com/collect",c),4)}if(2!=d.nextAddress)return d.return(200===d.yieldResult.status?Promise.resolve("telemetry sent successfully"):Promise.reject("Error in sending telemetry"));d.enterCatchBlock();return d.return(Promise.reject("Error in sending telemetry"))})};var r=new c,h=function(){this._telemetryEnabled=this._updateInterval=this._hbPingRetryInterval=
this._hbPingInterval=this._containerKeyName=null;return this};$jscomp.inherits(h,a);h.prototype._getCurrentUTCTimestamp=function(){return Math.floor((new Date).getTime())};h.prototype._checkPingTimeArrived=function(){var a=JSON.parse(g.getContainerByName(this._containerKeyName));return!!SymBfw.utils.isNil(a)||a+this._hbPingInterval<this._getCurrentUTCTimestamp()};h.prototype._constructHeartBeatPing=function(){var a,b={};return a=SymBfw.utils.isNil(this._telemetryEnabled)?"unknown":!0===this._telemetryEnabled?
"enabled":"disabled",b.ec="UserBase",b.ea="HeartBeat",b.cd3=a,b};h.prototype.perform=function(a){var b=this;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){if(1==f.nextAddress){if(SymBfw.utils.isEmptyObject(a))throw Error("HeartBeat ping configuration is empty");if(b._containerKeyName="hbLastUpdateTimeKey",b._hbPingInterval=a.heartBeatIntervalInMilliSec,b._hbPingRetryInterval=a.retryIntervalMillis,b._updateInterval=a.heartBeatIntervalInMilliSec,b._telemetryEnabled=a._isTelemetryEnabled,
!a.isHeartBeatPingEnabled)return f.jumpTo(0);f.setCatchFinallyBlocks(3);return f.yield(b._sendHeartBeatPing(),5)}if(3!=f.nextAddress)return f.leaveTryBlock(0);f.enterCatchBlock();SymBfw.logger.error("Failed to send the Telemetry");f.jumpToEnd()})};h.prototype._sendHeartBeatPing=function(){var a=this,b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){switch(f.nextAddress){case 1:if(!a._checkPingTimeArrived()){f.jumpTo(2);break}b=a._constructHeartBeatPing();f.setCatchFinallyBlocks(3);
return f.yield(r.send(b),5);case 5:g.setContainerByName(a._containerKeyName,a._getCurrentUTCTimestamp());f.leaveTryBlock(2);break;case 3:f.enterCatchBlock(),SymBfw.logger.error("Failed to send the Telementry and retry interval set");case 2:setTimeout(function(){a._sendHeartBeatPing()},18E5),f.jumpToEnd()}})};var p=SymBfw.utils,n=function(){this._container=null;return this};$jscomp.inherits(n,a);n.prototype.perform=function(a){var b=this;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){if(1==
f.nextAddress){if(p.isEmptyObject(a))throw Error("Install Ping configuration is missing");if(!a.isInstallPingEnabled)return f.return(!1);b.container=g;return b._canTriggerInstallPing(a)?f.yield(b._sendInstallPing(),3):f.jumpTo(2)}return f.return(!0)})};n.prototype._canTriggerInstallPing=function(a){a=a.isFreshInstall;var b=!1,f=this.container.getContainerByName("installPingStatusKey");if(p.isNil(f)){if(a)return!0;this.container.setContainerByName("installPingStatusKey","0")}else"2"===f&&(b=!0);return b};
n.prototype._sendInstallPing=function(){var a=this,b,c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){switch(f.nextAddress){case 1:return b=a._constructInstallPing(),c=null,f.setCatchFinallyBlocks(2,3),f.yield(r.send(b),5);case 5:c="1";case 3:f.enterFinallyBlock();a.container.setContainerByName("installPingStatusKey",c);f.leaveFinallyBlock(0);break;case 2:f.enterCatchBlock(),c="2",f.jumpTo(3)}})};n.prototype._constructInstallPing=function(){var a={};return a.ec="UserBase",a.ea="Install",
a};$jscomp.global.Object.defineProperties(n.prototype,{container:{configurable:!0,enumerable:!0,get:function(){return this._container},set:function(a){this._container=a}}});var z=SymBfw.utils;c=function(){};c.prototype.init=function(a){var b=this,f,c,d;return $jscomp.asyncExecutePromiseGeneratorProgram(function(l){if(1==l.nextAddress){if(!(a instanceof e&&b._isValidConfigObj(a)))throw new TypeError("HeartBeat SDK initialization Failed - Invalid Configuration Object");l.setCatchFinallyBlocks(2);f=
a;c=f.isLocalStorageNeeded;return l.yield(g.loadContainer(c),4)}if(2!=l.nextAddress)return r.init(a),(new n).perform(a),(new h).perform(a),l.leaveTryBlock(0);d=l.enterCatchBlock();SymBfw.logger.error("HB initialization Failed :",d.message);l.jumpToEnd()})};c.prototype._isValidConfigObj=function(a){a=Object.values(a);for(var b in a)if(a[b]instanceof Object){if(!this._isValidConfigObj(a[b]))return!1}else if(z.isNil(a[b]))return!1;return!0};c=new c;var t=function(){this._userLanguage=this._apiKey=this._dataSource=
this._machineId=this._prodVersion=this._prodName=null;this._isLocalStorageNeeded=!1;this._pingData=this._pingName=this._isMOTEnabled=this._pingIntervalInMillis=null};$jscomp.global.Object.defineProperties(t.prototype,{prodName:{configurable:!0,enumerable:!0,set:function(a){this._prodName=a},get:function(){return this._prodName}},prodVersion:{configurable:!0,enumerable:!0,set:function(a){this._prodVersion=a},get:function(){return this._prodVersion}},machineId:{configurable:!0,enumerable:!0,set:function(a){this._machineId=
a},get:function(){return this._machineId}},apiKey:{configurable:!0,enumerable:!0,set:function(a){this._apiKey=a},get:function(){return this._apiKey}},dataSource:{configurable:!0,enumerable:!0,set:function(a){this._dataSource=d[a]},get:function(){return this._dataSource}},userLanguage:{configurable:!0,enumerable:!0,set:function(a){this._userLanguage=a},get:function(){return this._userLanguage}},isLocalStorageNeeded:{configurable:!0,enumerable:!0,set:function(a){this._isLocalStorageNeeded=a},get:function(){return this._isLocalStorageNeeded}},
pingIntervalInMillis:{configurable:!0,enumerable:!0,set:function(a){this._pingIntervalInMillis=a},get:function(){return this._pingIntervalInMillis}},isMOTEnabled:{configurable:!0,enumerable:!0,set:function(a){this._isMOTEnabled=a},get:function(){return this._isMOTEnabled}},pingName:{configurable:!0,enumerable:!0,set:function(a){this._pingName=a},get:function(){return this._pingName}},pingData:{configurable:!0,enumerable:!0,set:function(a){this._pingData=a},get:function(){return this._pingData}}});
var q=SymBfw.utils,y=q.isNil,u=q.isntNil,A=q.isInteger,B=q.isString,C=q.isObject,D=q.isEmptyObject,m=function(){this._pollTimer=this._pingData=this._hbRecurrentPingInterval=this._containerKeyName=null;return this};$jscomp.inherits(m,a);m.prototype.init=function(a){if(D(a))throw Error("recurrentPingConfig cannot be null");if(!A(a._pingIntervalInMillis))throw Error("ping interval should be an integer");if(!B(a._pingName))throw Error("invalid ping name");if(!C(a._pingData))throw Error("invalid ping data");
this._hbRecurrentPingInterval=a._pingIntervalInMillis;this._pingData=a._pingData;this._containerKeyName=a._pingName+"_lastupdatetime"};m.prototype._checkPingTimeReached=function(){var a=JSON.parse(g.getContainerByName(this._containerKeyName));return!!y(a)||a+this._hbRecurrentPingInterval<this._getCurrentUTCTimestamp()};m.prototype.perform=function(){var a=this;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return a._checkPingTimeReached()?b.yield(a._sendTelemetry(),
3):b.jumpTo(2);a._pollTimer=setTimeout(function(){a.perform()},18E5);b.jumpToEnd()})};m.prototype._sendTelemetry=function(){var a=this;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return b.setCatchFinallyBlocks(2),b.yield(r.send(a._pingData),4);if(2!=b.nextAddress)return g.setContainerByName(a._containerKeyName,a._getCurrentUTCTimestamp()),b.leaveTryBlock(0);b.enterCatchBlock();SymBfw.logger.error("Failed to send the recurrent ping and retry interval set");b.jumpToEnd()})};
m.prototype.stop=function(){u(this._pollTimer)&&(clearTimeout(this._pollTimer),this._pollTimer=null)};m.prototype._getCurrentUTCTimestamp=function(){return Math.floor((new Date).getTime())};a=SymBfw.utils;var w=a.isString,x=a.isNil,v=a.isEmptyObject;a=function(){this._pingObjMap={}};a.prototype.init=function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){a.jumpToEnd()})};a.prototype.createPing=function(a){var b=this,c,d,f,e;return $jscomp.asyncExecutePromiseGeneratorProgram(function(h){if(1==
h.nextAddress){if(!(a instanceof t))throw new TypeError("Active vault user ping initialization failed - Invalid Configuration Object");if(x(a._isLocalStorageNeeded)||x(a._pingName))throw Error("config object values cannot be empty");h.setCatchFinallyBlocks(2);c=a;d=c.isLocalStorageNeeded;return h.yield(g.loadContainer(d),4)}if(2!=h.nextAddress){if(!v(b._pingObjMap[a._pingName]))throw Error(a._pingName+" already exists");f=new m;f.init(a);b._pingObjMap[a._pingName]=f;r.init(a);return h.leaveTryBlock(0)}e=
h.enterCatchBlock();SymBfw.logger.error("Recurrent Ping Creation Failed :",e.message);h.jumpToEnd()})};a.prototype.start=function(a){if(!w(a))throw Error("Invalid ping name");a=this._pingObjMap[a];if(v(a))throw Error("Invalid ping object");a.perform()};a.prototype.stop=function(a){if(!w(a))throw Error("Invalid ping name");a=this._pingObjMap[a];if(v(a))throw Error("Invalid ping object");a.stop()};a=new a;b.default={hbManager:c,HBConfig:e,HBRecurrentPingConfig:t,hbRecurrentPingManager:a}},0:function(a,
b,c){a.exports=c("./source/HBIndex.js")}}).default});
