var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(b){var a=0;return function(){return a<b.length?{done:!1,value:b[a++]}:{done:!0}}};$jscomp.arrayIterator=function(b){return{next:$jscomp.arrayIteratorImpl(b)}};$jscomp.makeIterator=function(b){var a="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];return a?a.call(b):$jscomp.arrayIterator(b)};$jscomp.owns=function(b,a){return Object.prototype.hasOwnProperty.call(b,a)};$jscomp.ASSUME_ES5=!1;
$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,a,g){b!=Array.prototype&&b!=Object.prototype&&(b[a]=g.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(b,a,g,e){if(a){g=$jscomp.global;b=b.split(".");for(e=0;e<b.length-1;e++){var c=b[e];c in g||(g[c]={});g=g[c]}b=b[b.length-1];e=g[b];a=a(e);a!=e&&null!=a&&$jscomp.defineProperty(g,b,{configurable:!0,writable:!0,value:a})}};$jscomp.polyfill("Object.values",function(b){return b?b:function(a){var b=[],e;for(e in a)$jscomp.owns(a,e)&&b.push(a[e]);return b}},"es8","es3");$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(b){function a(){this.batch_=null}function g(a){return a instanceof c?a:new c(function(m,b){m(a)})}if(b&&!$jscomp.FORCE_POLYFILL_PROMISE)return b;a.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var m=this;this.asyncExecuteFunction(function(){m.executeBatch_()})}this.batch_.push(a)};var e=$jscomp.global.setTimeout;a.prototype.asyncExecuteFunction=function(a){e(a,0)};a.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];a[b]=null;try{c()}catch(f){this.asyncThrow_(f)}}}this.batch_=null};a.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var c=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(k){b.reject(k)}};c.prototype.createResolveAndReject_=function(){function a(a){return function(g){c||(c=!0,a.call(b,g))}}var b=this,c=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};c.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof c)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};c.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(k){this.reject_(k);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};c.prototype.reject_=function(a){this.settle_(2,a)};c.prototype.fulfill_=function(a){this.settle_(1,a)};c.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};c.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)d.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var d=new a;c.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};c.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(f){c.reject(f)}};c.prototype.then=function(a,b){function g(a,b){return"function"==typeof a?function(b){try{d(a(b))}catch(r){h(r)}}:b}var d,h,e=new c(function(a,b){d=a;h=b});this.callWhenSettled_(g(a,d),g(b,h));return e};
c.prototype.catch=function(a){return this.then(void 0,a)};c.prototype.callWhenSettled_=function(a,b){function c(){switch(g.state_){case 1:a(g.result_);break;case 2:b(g.result_);break;default:throw Error("Unexpected state: "+g.state_);}}var g=this;null==this.onSettledCallbacks_?d.asyncExecute(c):this.onSettledCallbacks_.push(c)};c.resolve=g;c.reject=function(a){return new c(function(b,c){c(a)})};c.race=function(a){return new c(function(b,c){for(var d=$jscomp.makeIterator(a),e=d.next();!e.done;e=d.next())g(e.value).callWhenSettled_(b,
c)})};c.all=function(a){var b=$jscomp.makeIterator(a),d=b.next();return d.done?g([]):new c(function(a,c){function e(b){return function(c){h[b]=c;f--;0==f&&a(h)}}var h=[],f=0;do h.push(void 0),f++,g(d.value).callWhenSettled_(e(h.length-1),c),d=b.next();while(!d.done)})};return c},"es6","es3");
$jscomp.polyfill("Array.from",function(b){return b?b:function(a,b,e){b=null!=b?b:function(a){return a};var c=[],d="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if("function"==typeof d){a=d.call(a);for(var g=0;!(d=a.next()).done;)c.push(b.call(e,d.value,g++))}else for(d=a.length,g=0;g<d;g++)c.push(b.call(e,a[g],g));return c}},"es6","es3");$jscomp.polyfill("Object.is",function(b){return b?b:function(a,b){return a===b?0!==a||1/a===1/b:a!==a&&b!==b}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(b){return b?b:function(a,b){var e=this;e instanceof String&&(e=String(e));var c=e.length;b=b||0;for(0>b&&(b=Math.max(b+c,0));b<c;b++){var d=e[b];if(d===a||Object.is(d,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(b,a,g){if(null==b)throw new TypeError("The 'this' value for String.prototype."+g+" must not be null or undefined");if(a instanceof RegExp)throw new TypeError("First argument to String.prototype."+g+" must not be a regular expression");return b+""};$jscomp.polyfill("String.prototype.includes",function(b){return b?b:function(a,b){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,b||0)}},"es6","es3");
(function(b){b.IDSafe.interactiveStepHandler=function(a){var b=a.utils.isntNil,e=a.extensionAdapter,c=a.logger,d={clickListenerElement:null,enterListenerElement:null,payload:null,addEventListeners:function(a,e){d.payload=a;d.payload.pageId=null;window.addEventListener("beforeunload",d._clickAndUnloadEventHandler);b(e.XpathClickElement)&&(d.clickListenerElement=document.evaluate(e.XpathClickElement,document,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue,b(d.clickListenerElement)?(d.clickListenerElement.addEventListener("click",
d._clickAndUnloadEventHandler),c.debug("Click listener has been added to: "+e.XpathClickElement)):c.debug("XpathClickElement was defined but the element wasn`t found."));b(e.XpathEnterElement)&&(d.enterListenerElement=document.evaluate(e.XpathEnterElement,document,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue,b(d.enterListenerElement)?(d.enterListenerElement.addEventListener("keyup",d._enterEventListenerHandler),c.debug("Enter keyup listener has been added to: "+e.XpathEnterElement)):
c.debug("XpathEnterElement was defined but the element wasn`t found."))},_removeEventListeners:function(){b(d.clickListenerElement)&&d.clickListenerElement.removeEventListener("click",d._clickAndUnloadEventHandler);b(d.enterListenerElement)&&d.enterListenerElement.removeEventListener("keyup",d._enterEventListenerHandler);window.removeEventListener("beforeunload",d._clickAndUnloadEventHandler);d.clickListenerElement=null;d.enterListenerElement=null},_clickAndUnloadEventHandler:function(){e.sendMessage(d.payload);
d._removeEventListeners()},_enterEventListenerHandler:function(a){13===a.keyCode&&(e.sendMessage(d.payload),d._removeEventListeners())}};return d}(b.SymBfw)})(executionContext);
(function(b){b.IDSafe.passwordChangerActionFactory=function(a,b){var e=a.utils.isntNil,c=a.utils.isFunction;a=b.constants;var d={_createPasswordChangerFill:function(){return new b.PasswordChangerFill},_createPasswordChangerClick:function(){return new b.PasswordChangerClick},_createPasswordChangerOpenUrl:function(){return new b.PasswordChangerOpenUrl},_createPasswordChangerVerify:function(){return new b.PasswordChangerVerify},_actionsFactory:{}};d._actionsFactory[a.passwordChangerAction.FILL]=d._createPasswordChangerFill;
d._actionsFactory[a.passwordChangerAction.CLICK]=d._createPasswordChangerClick;d._actionsFactory[a.passwordChangerAction.OPENURL]=d._createPasswordChangerOpenUrl;d._actionsFactory[a.passwordChangerAction.VERIFY]=d._createPasswordChangerVerify;d.createActionObject=function(a){return c(d._actionsFactory[a])&&(a=d._actionsFactory[a](),e(a))?a:null};return d}(b.SymBfw,b.IDSafe)})(executionContext);
(function(b){var a=IDSafe.uiConstants.AUTO_PASSWORD_CHANGER_OVERLAY,g=a.TYPES,e=a.MESSAGES,c=SymBfw.uiUtils,d=SymBfw.extensionAdapter,m=SymBfw.utils.isNil,l=SymBfw.utils.isntNil,k=SymBfw.utils.isEmptyObject,f=SymBfw.localizerProxy,h={_isListenersAdded:!1,_currentType:null,_data:{},_strings:{interactive:"Please enter the information required below to change your password.",inProgress:"{0} is changing your {1} password. Do not close this page.",success:"Your new {0} Login has been saved successfully.",
failure:"An error occurred and your Login was not changed. We are working on this, please try again later."},show:function(a,b){if(window.self===window.top){if(m(b)||k(b))throw Error("Location cannot be null");if(m(a)||-1===Object.values(g).indexOf(a))throw Error("Unsupported popup type: "+a);l(h._currentType)||(h._currentType=a,h._isListenersAdded||(h._addListener(),h._isListenersAdded=!0),h._injectPopup(b))}},_addListener:function(){d.addContentScriptMessageListener(function(a,b,c){switch(a.id){case e.OVERLAY_HIDE:h.close();
break;case e.OVERLAY_INIT:b({type:h._currentType,data:h._data})}})},_injectPopup:function(b){var e=h._strings[h._currentType],g=new Promise(function(a,b){f.getCurrentLanguageDirection(function(b){a(b)})}),q=new Promise(function(a,b){var c={};c[e]=["__LONG_PRODUCT_NAME__",document.location.host];f.getLocalizedStringsWithFormat(c,function(c){SymBfw.utils.isEmptyObject(c)?b():a(c[e])})});Promise.all([g,q]).then(function(e){var f=e[1];h._data.direction=e[0];h._data.localizedString=f;h._data.type=h._currentType;
h.popupHtml=d.getExtensionURL(a.HTML);h.style=d.getExtensionURL(a.STYLE);c.injectStyle(h.style);h._createBannerFrame(b)})},close:function(){for(var b=document.querySelectorAll("#"+a.IFRAME_ID),c=0;c<b.length;c++)document.documentElement.removeChild(b[c]);h._currentType=null;h._isListenersAdded=!1},_createBannerFrame:function(b){l(window.top.document.getElementById(a.IFRAME_ID))||m(b)||k(b)||c.createFrame(a.IFRAME_ID,h.popupHtml,a.HEIGHT,a.WIDTH,b)}};b.IDSafe.passwordChangerOverlay=h})(executionContext);
(function(b){b.IDSafe.PasswordChangerActions=function(a,b){var e=b.uiConstants.SECURITY_DASHBOARD,c=e.TASK_STATUS,d=e.MESSAGES,g=a.utils.isNil,l=a.utils.isntNil,k=a.extensionAdapter,f=a.logger,h=b.constants.passwordChangerState,t=b.interactiveStepHandler,n=b.eventUITelemetryWrapper,p=n.constants.elementId;a=function(){this._clbContinue=this._clbStop=this._pageRule=this._element=null};a.prototype.initialize=function(a,b,c,e,d){this._currentIndex=a;this._pageRule=b;this._clbStop=c;this._clbContinue=
e;this._clbPostExecute=d;this._isInitatedFromAjax=!1;this._PromiseTimer=null};a.prototype.getCurrentIndex=function(){return this._currentIndex};a.prototype.sendMessage=function(a,b,e,h){h=void 0===h?!1:h;var g={};g.id=d.TASK_STATUS;g.numberOfsuccess=a;g.pageId=this._pageRule.pageId;if(b==c.NEXT_PAGE||b==c.FAILED||b==c.GET_PAGE)f.log("PswChgr stoppet from sendMessage  "+b),this._clbStop();g.status=b;g.pageIndex=e;g.currentPageKey=this._pageRule.currentPageKey;!0===h?(t.addEventListeners(g,this._pageRule.Actions[a]),
k.sendMessage({id:d.TASK_STATUS,status:c.INTERACTIVE_STEP,currentPageKey:this._pageRule.currentPageKey,pageId:this._pageRule.pageId}),n.sendDashBoardChangePasswordUIEventTelemetry(p.DASHBOARD_AUTO_CHANGE,p.DASHBOARD_AUTO_CHANGE_INTERACTIVE_STEP,window.location.hostname+window.location.pathname)):b==c.FAILED||b==c.GET_PAGE?setTimeout(function(){return k.sendMessage(g)},1E3):k.sendMessage(g)};a.prototype.handlePageSucess=function(a){if(a.OnSuccessGoToPage){a.OnSuccessGoToPage===h.COMPLETED?this.sendMessage(this._currentIndex,
c.SUCCESS,null):a.OnSuccessGoToPage===h.FAILED&&this.sendMessage(this._currentIndex,c.FAILED,null);var b=!1;l(a.interactive)&&(b=!0);if(l(a.SavePassword)){var e={};e.id=d.TASK_STATUS;e.status=c.NEW_PASSWORD;e.password=document.evaluate(a.SavePassword,document,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue.value;k.sendMessage(e)}this.sendMessage(this._currentIndex,c.NEXT_PAGE,a.OnSuccessGoToPage,b)}};a.prototype.handlePageError=function(a){a.OnErrGoToPage?this.sendMessage(this._currentIndex,
c.GET_PAGE,a.OnErrGoToPage):a.OnErrGoToAction?(this._currentIndex=a.OnErrGoToAction-1,this._clbContinue()):this._pageRule.status!=h.COMPLETED&&this._pageRule.status!=h.FAILED&&this.sendMessage(this._currentIndex,c.FAILED,null)};a.prototype.getElemenForXpath=function(a){this._element=document.evaluate(a,document,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue};a.prototype.PromiseClb=function(a){g(a._PromiseTimer)&&clearTimeout(a._PromiseTimer);f.log("PswChgr mutation event received");
a._isInitatedFromAjax=!0;a.excuteAction.call(a);a._observer.disconnect()};a.prototype.createMutationObserver=function(a){var b=this;this._PromiseTimer=setTimeout(function(){b.PromiseClb(b)},2E3);this._observer=new MutationObserver(function(a){g(b._PromiseTimer)&&clearTimeout(b._PromiseTimer);b._PromiseTimer=setTimeout(function(){b.PromiseClb(b)},1E3)});this._observer.observe(a,{attributes:!0,childList:!0,subtree:!0})};a.prototype.excuteAction=function(){var a=this._pageRule.Actions[this._currentIndex];
f.log("PswChgr"+JSON.stringify(a));if(g(a.Xpath))return!1;this.getElemenForXpath(a.Xpath);if(g(this._element)){if(l(a.ajax)&&!this._isInitatedFromAjax)return this.createMutationObserver(document.body),!1;this.handlePageError(a);return!1}this.handlePageSucess(a);this._clbPostExecute();return!0};return a}(b.SymBfw,b.IDSafe)})(executionContext);
(function(b){b.IDSafe.PasswordChangerClick=function(a,b){a=function(){b.PasswordChangerActions.call(this)};a.prototype=Object.create(b.PasswordChangerActions.prototype);a.prototype.excuteAction=function(){b.PasswordChangerActions.prototype.excuteAction.call(this)};a.prototype.postExcute=function(){!0===this._element.disabled&&(this._element.disabled=!1);this._element.click();this._clbContinue()};return a}(b.SymBfw,b.IDSafe)})(executionContext);
(function(b){b.IDSafe.PasswordChangerFill=function(a,b){a=function(){b.PasswordChangerActions.call(this)};a.prototype=Object.create(b.PasswordChangerActions.prototype);a.prototype.excuteAction=function(){b.PasswordChangerActions.prototype.excuteAction.call(this)};a.prototype._simulateTyping=function(a,b){b=void 0===b?"":b;var c=a.tagName.toLowerCase();if("input"===c||"textarea"===c){b=b.toString?b.toString():b;c=document.activeElement;a.focus();if(a.onfocus)a.onfocus();this._clearInputValue(a);for(var e=
0;e<b.length;e++)a.dispatchEvent(new Event("keydown",{bubbles:!1,cancelable:!1})),a.dispatchEvent(new Event("keypress",{bubbles:!1,cancelable:!1})),a.value+=b[e],a.dispatchEvent(new Event("input",{bubbles:!0})),a.dispatchEvent(new Event("keyup",{bubbles:!1,cancelable:!1}));a.dispatchEvent(new Event("change",{bubbles:!0,cancelable:!0}));if(a.onchange)a.onchange();a.blur();if(a.onblur)a.onblur();c&&c.focus()}};a.prototype._clearInputValue=function(a){a.dispatchEvent(new KeyboardEvent("keydown",{bubbles:!1,
cancelable:!1}));a.dispatchEvent(new KeyboardEvent("keypress",{bubbles:!1,cancelable:!1}));a.value="";a.dispatchEvent(new Event("input",{bubbles:!0}));a.dispatchEvent(new KeyboardEvent("keyup",{bubbles:!1,cancelable:!1}));a.dispatchEvent(new Event("change",{bubbles:!0,cancelable:!0}))};a.prototype.postExcute=function(){this._simulateTyping(this._element,this._pageRule.Actions[this._currentIndex].Data);this._clbContinue()};return a}(b.SymBfw,b.IDSafe)})(executionContext);
(function(b){b.IDSafe.PasswordChangerVerify=function(a,b){a=function(){b.PasswordChangerActions.call(this)};a.prototype=Object.create(b.PasswordChangerActions.prototype);a.prototype.excuteAction=function(){b.PasswordChangerActions.prototype.excuteAction.call(this)};a.prototype.postExcute=function(){this._clbContinue()};return a}(b.SymBfw,b.IDSafe)})(executionContext);
(function(b){b.IDSafe.PasswordChangerOpenUrl=function(a,b){var e=a.utils.isntNil;a=function(){b.PasswordChangerActions.call(this)};a.prototype=Object.create(b.PasswordChangerActions.prototype);a.prototype.excuteAction=function(){var a=this._pageRule.Actions[this._currentIndex];e(a.OpenUrl)&&(this.handlePageSucess(a),this.changeUrl(a.OpenUrl,window.document.location));this._clbContinue()};a.prototype.changeUrl=function(a,b){e(b)&&(b.href=a)};return a}(b.SymBfw,b.IDSafe)})(executionContext);
(function(b){var a=IDSafe.uiConstants.SECURITY_DASHBOARD.MESSAGES,g=SymBfw.extensionAdapter,e=SymBfw.utils.isNil,c=SymBfw.utils.isntNil,d=SymBfw.logger,m=IDSafe.passwordChangerOverlay,l=IDSafe.uiConstants.AUTO_PASSWORD_CHANGER_OVERLAY,k=IDSafe.constants.passwordChangerAction,f={isListenersAdded:!1,_reject:null,_resolve:null,_isRejected:!1,actionIndex:0,delayBetweenEachAction:100,_page:null,DomLoadedMaxRetryCount:3,DomLoadedCurrentRetryCount:0,DomLoadedRetryCountTimer:null,DomLoadedRetryinterval:1E3,
runLoop:function(){var a=this;f.actionIndex+=1;var b=this._page.Actions.length;d.log("PswChgr passwordChangerInit.actionIndex"+f.actionIndex+" nlenth "+b);f.actionIndex<b&&(new Promise(function(b,c){setTimeout(function(){console.log("PswChgr current Index ==>"+f.actionIndex);f._reject=c;f._resolve=b;f.processAction(a._page)},f.delayBetweenEachAction)})).then(f.runLoop.bind(this)).catch(function(){console.log("PswChgr rejected")})},processAction:function(a){var b=a.Actions[f.actionIndex];e(b)||e(b.Action)?
d.log("PswChgr Action not found for the rule "+JSON.stringify(b)):(b=IDSafe.passwordChangerActionFactory.createActionObject(b.Action),e(b)||(b.initialize(f.actionIndex,a,f.stopActions,f.continueActions,b.postExcute),b.excuteAction(),f.actionIndex=b.getCurrentIndex()))},stopActions:function(){c(f._reject)&&(d.log("PswChgr action got stopped"),f._reject(),f.reject=null,f._isRejected=!0)},continueActions:function(){!f._isRejected&&c(f._resolve)&&(f._resolve(),f._resolve=null)},isAllowedSite:function(a,
b){if(e(b)||e(a))return!1;var c;b=$jscomp.makeIterator(b);for(c=b.next();!c.done;c=b.next()){c=c.value;var d=a.substring(0,c.length);if(c===d)return!0}return!1},createRunLoop:function(a){f.actionIndex=-1;f.isAllowedSite(document.URL,a.allowedUrl)&&(f._page=a,d.log("stoppped from createRunLoop"),f.stopActions(),f._isRejected=!1,f.runLoop())},CheckDomLoadedAndRetry:function(a){c(f.DomLoadedRetryCountTimer)&&clearTimeout(f.DomLoadedRetryCountTimer);var b=a.Actions[f.actionIndex];d.log("PswChgr action Index "+
f.actionIndex+" Action "+JSON.stringify(b));var e=document.evaluate(b.Xpath,document,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue;c(e)||f.DomLoadedCurrentRetryCount>=f.DomLoadedMaxRetryCount||b.Action===k.OPENURL?f.createRunLoop(a):(d.log("PswChgr DomLoadedCurrentRetryCount"+f.DomLoadedCurrentRetryCount),f.DomLoadedCurrentRetryCount++,f.DomLoadedRetryCountTimer=setTimeout(f.CheckDomLoadedAndRetry,f.DomLoadedRetryinterval,a))},getAutochangeTelemetry:function(a){var b=window.location.href,
c=Array.from(document.querySelectorAll("iframe")).map(function(a){return a.src}).filter(function(a){return a.includes("http")||a.includes("https")});a=a.filter(function(a){return null!==document.evaluate(a,document,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue});var d=document.querySelectorAll("input");d=Array.from(d).map(function(a){return{id:a.id,name:a.name,className:a.className,placeholder:a.placeholder}});return{frameUrls:c,pageUrl:b,selectorsFound:a,inputsOnSite:d}},addListener:function(){g.addContentScriptMessageListener(function(b,
c,d){switch(b.id){case a.PAGE_ACTIONS:f.actionIndex=0;f.DomLoadedCurrentRetryCount=0;f.CheckDomLoadedAndRetry(b);break;case a.AUTO_CHANGE_RUNNING:b.isAutoChangeRunning&&document.querySelector("html").setAttribute("data-autochangebyidsafe",!0);break;case a.AUTOCHANGE_BANNER_TYPE:b.bannerType===l.TYPES.INTERACTIVE||b.bannerType===l.TYPES.SUCCESS||b.bannerType===l.TYPES.FAILURE?(m.close(),m.show(b.bannerType,{left:0,top:0})):b.bannerType===l.TYPES.IN_PROGRESS&&m.show(l.TYPES.IN_PROGRESS,{left:0,top:0});
break;case a.AUTOCHANGE_CS_TELEMETRY:self===top&&(b=f.getAutochangeTelemetry(b.selectors),c(b))}})}};f.isListenersAdded||(f.addListener(),f.isListenersAdded=!0);b.IDSafe.passwordChangerInit=f})(executionContext);
