var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var d=0;return function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,c){a!=Array.prototype&&a!=Object.prototype&&(a[d]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,d){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:d})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(c||"")+"_"+d++,c)}var d=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.iteratorFromArray=function(a,d){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,e={next:function(){if(c<a.length){var g=c++;return{value:d(g,a[g]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};
$jscomp.polyfill=function(a,d,c,e){if(d){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var g=a[e];g in c||(c[g]={});c=c[g]}a=a[a.length-1];e=c[a];d=d(e);d!=e&&null!=d&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:d})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
(function(a){isCCTDOM(document.location.origin)&&((a.IDSafe=a.IDSafe||{}).cctListener=function(a,c,e){var d=a.utils.isNil,p=a.utils.isntNil,q=a.logger,k=c.constants.eventName,n=a.extensionAdapter,f=e.constants,r=a.globals.BROWSER,h={_storeAndGetFingerPrint:function(){var a=localStorage.getItem(f.FINGERPRINT);if(d(a)){var m=(new Date).getTime();a="xxxxxxxxxyxxxxxx".replace(/[xy]/g,function(a){var b=(m+16*Math.random())%16|0;m=Math.floor(m/16);return("x"==a?b:b&7|8).toString(16)});localStorage.setItem(f.FINGERPRINT,
a)}return a},_storeAndGetMachineGuid:function(){var b=localStorage.getItem(f.MACHINE_GUID);d(b)&&(b=a.utils.createNewGuid(),localStorage.setItem(f.MACHINE_GUID,b));return b},_getElements:function(a){a=navigator.language;var b=a.split("-"),c=b[0];b=b[1];d(b)&&"ja"===c&&(b="JP");d(b)&&(b="US");a={Action:f.CCT.ACTION,LayoutMediaSKU:f.CCT.LAYOUTMEDIA_SKU,LayoutProductLanguage:c,OSLanguage:c,Fingerprint:h._storeAndGetFingerPrint(),EndPointId:h._storeAndGetMachineGuid(),MachineName:navigator.platform,OSLocale:a,
RequesterIds:f.CCT.REQUESTERIDS,PartnerUnitId:f.CCT.PARTNER_UNITID,Country:b};c={};for(var e in event.data.payload){b=event.data.payload[e];var l=a[b];d(l)&&(l=null);c[b]=l}return c},_postMessageToCCT:function(a){var b={id:c.constants.responseEvent};b.responseData=a;window.postMessage(b,f.CCT_DOMAIN)},handleCCTRequest:function(a){if(a.source===window&&isCCTDOM(document.location.origin)&&a.data.id===c.constants.requestEvent&&!d(a.data.eventID)&&Object.keys(k).some(function(b){return k[b]===a.data.eventID})){k.SHOW_PROGRESS===
a.data.eventID?e.loader.show():(k.HIDE_PROGRESS===a.data.eventID||k.SHOW===a.data.eventID)&&e.loader.hide();var b={id:a.data.eventID,payload:a.data.payload};if("Edge"===r)try{n.sendMessage(b);var f={};f.eventID=b.id;if(k.GET_ELEMENTS===a.data.eventID){var g=h._getElements(b.payload);f.data=g;f.code=!0}else k.PROCESS===a.data.eventID?(f.state=!0,f.jobName=a.data.payload.Job,f.responseData=null):f.response=!0;h._postMessageToCCT(f)}catch(l){q.error("Something went wrong inside Edge Browser Execution.")}else n.sendMessage(b,
function(a){d(a)||isCCTDOM(document.location.origin)&&h._postMessageToCCT(a)})}},load:function(){isCCTDOM(document.location.origin)&&(window.addEventListener("message",h.handleCCTRequest,!1),document.addEventListener("readystatechange",function(a){"interactive"!==a.target.readyState&&"complete"!==a.target.readyState||p(document.getElementById(e.loader.constants.ID))||e.loader.show()},!1))}};h.load();return h}(a.SymBfw,a.XIDSafe,a.IDSafe))})(executionContext);
function isCCTDOM(a){return IDSafe.constants.HTTPS_PROTOCOL+"://"+IDSafe.constants.CCT_HOST===a};
