var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.owns=function(a,c){return Object.prototype.hasOwnProperty.call(a,c)};$jscomp.assign="function"==typeof Object.assign?Object.assign:function(a,c){for(var b=1;b<arguments.length;b++){var e=arguments[b];if(e)for(var d in e)$jscomp.owns(e,d)&&(a[d]=e[d])}return a};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,c,b,e){if(c){b=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var d=a[e];d in b||(b[d]={});b=b[d]}a=a[a.length-1];e=b[a];c=c(e);c!=e&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Object.assign",function(a){return a||$jscomp.assign},"es6","es3");$jscomp.findInternal=function(a,c,b){a instanceof String&&(a=String(a));for(var e=a.length,d=0;d<e;d++){var g=a[d];if(c.call(b,g,d,a))return{i:d,v:g}}return{i:-1,v:void 0}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6","es3");$jscomp.checkStringArgs=function(a,c,b){if(null==a)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");return a+""};
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(a,b){var c=$jscomp.checkStringArgs(this,a,"startsWith");a+="";var d=c.length,g=a.length;b=Math.max(0,Math.min(b|0,c.length));for(var h=0;h<g&&b<d;)if(c[b++]!=a[h++])return!1;return h>=g}},"es6","es3");$jscomp.polyfill("Object.is",function(a){return a?a:function(a,b){return a===b?0!==a||1/a===1/b:a!==a&&b!==b}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,b){var c=this;c instanceof String&&(c=String(c));var d=c.length;b=b||0;for(0>b&&(b=Math.max(b+d,0));b<d;b++){var g=c[b];if(g===a||Object.is(g,a))return!0}return!1}},"es7","es3");$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,b){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,b||0)}},"es6","es3");
$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):$jscomp.arrayIterator(a)};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function c(){this.batch_=null}function b(a){return a instanceof d?a:new d(function(h,b){h(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;c.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var h=this;this.asyncExecuteFunction(function(){h.executeBatch_()})}this.batch_.push(a)};var e=$jscomp.global.setTimeout;c.prototype.asyncExecuteFunction=function(a){e(a,0)};c.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];a[b]=null;try{c()}catch(k){this.asyncThrow_(k)}}}this.batch_=null};c.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var d=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(m){b.reject(m)}};d.prototype.createResolveAndReject_=function(){function a(a){return function(h){c||(c=!0,a.call(b,h))}}var b=this,c=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};d.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof d)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};d.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(m){this.reject_(m);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};d.prototype.reject_=function(a){this.settle_(2,a)};d.prototype.fulfill_=function(a){this.settle_(1,a)};d.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)g.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var g=new c;d.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};d.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(k){c.reject(k)}};d.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{e(a(b))}catch(q){h(q)}}:b}var e,h,f=new d(function(a,b){e=a;h=b});this.callWhenSettled_(c(a,e),c(b,h));return f};
d.prototype.catch=function(a){return this.then(void 0,a)};d.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?g.asyncExecute(c):this.onSettledCallbacks_.push(c)};d.resolve=b;d.reject=function(a){return new d(function(b,c){c(a)})};d.race=function(a){return new d(function(c,d){for(var e=$jscomp.makeIterator(a),g=e.next();!g.done;g=e.next())b(g.value).callWhenSettled_(c,
d)})};d.all=function(a){var c=$jscomp.makeIterator(a),e=c.next();return e.done?b([]):new d(function(a,d){function f(b){return function(c){l[b]=c;g--;0==g&&a(l)}}var l=[],g=0;do l.push(void 0),g++,b(e.value).callWhenSettled_(f(l.length-1),d),e=c.next();while(!e.done)})};return d},"es6","es3");
(function(a){var c=IDSafe.uiConstants,b=c.COMPROMISED_PASSWORD_RIBBON,e=SymBfw,d=e.uiUtils,g=e.extensionAdapter,h=e.localizerProxy,n=e.logger;e=e.utils;var m=e.isEmptyObject,k=e.isntNil,p=e.isNil,f={};f._ribbons=[{text:"Sign in to your Norton account or create an account if you don't already have one.",step:{text:"Step {0}",number:1},url:a.SymO2?[SymO2.authSCD.SSO_LOGIN_URL]:[]},{text:"After you unlock your vault, the password autochange with {0} will launch.",step:{text:"Step {0}",number:2},url:[g.getExtensionURL(c.VAULT_UNLOCK.UNLOCK_VAULT_URL)]},
{text:"Please create a vault for your logins by choosing a strong and unique password.",step:{text:"Step {0}",number:2},url:[g.getExtensionURL(c.NO_VAULT.HTML),g.getExtensionURL(c.NO_VAULT.CREATE_VAULT_URL)]},{text:"Your vault is now created and the password autochange with {0} will start shortly.",step:{text:"Step {0}",number:3},url:[g.getExtensionURL(c.CREATE_VAULT.SETUP_COMPLETE_PAGE_HTML)]}];f._currentRibbon=null;f._domain=null;f._addTopIndentationToFlowStepView=function(){var a=document.querySelector("#container"),
b=document.querySelector(".theme_default.login");k(b)&&b.classList.add("compromised-password-ribbon-padding");k(a)&&"BODY"===a.parentElement.tagName&&a.classList.add("compromised-password-ribbon-padding")};f.init=function(){f.addListeners();SymBfw.extensionAdapter.sendMessage({id:b.MESSAGES.RIBBON_INIT},function(a){if(!p(a)){var b=a.isLoggedIn,d=a.domain;if(a.isInProgress){f._addTopIndentationToFlowStepView();f._domain=d;var e=f._ribbons.filter(function(a){return!b||1!==a.step.number}).map(function(a){return Object.assign({},
a,{step:Object.assign({},a.step,{number:b?a.step.number-1:a.step.number})})}).find(function(a){return a.url.find(function(a){return window.location.href.startsWith(a)})});if(!m(e)){var h=e.step.text,l=e.text;a={};f._localize((a[l]=[f._domain],a[h]=[""+e.step.number],a)).then(function(a){f._currentRibbon={text:a[l],step:a[h],url:e.url};e.url.includes(g.getExtensionURL(c.VAULT_UNLOCK.UNLOCK_VAULT_URL))&&1===e.step.number&&(f._currentRibbon.step="");f._injectIframe()}).catch(function(a){return n.error(a)})}}}})};
f.addListeners=function(){g.addContentScriptMessageListener(function(a,c,d){switch(a.id){case b.MESSAGES.RIBBON_HIDE:f.close();break;case b.MESSAGES.RIBBON_SHOW:c(f._currentRibbon)}})};f._injectIframe=function(){window.top.document.getElementById(b.IFRAME_ID)||h.getCurrentLanguageDirection(function(a){f._currentRibbon.dir=a;f.popupHtml=g.getExtensionURL(b.HTML);f.style=g.getExtensionURL(c.POPUP.STYLE);d.injectStyle(f.style);SymBfw.uiUtils.createFrame(b.IFRAME_ID,f.popupHtml,b.HEIGHT,b.WIDTH,{left:0,
top:0})})};f.close=function(){var a=document.querySelectorAll("#"+b.IFRAME_ID),c=document.querySelector("#container"),d=document.querySelector(".theme_default.login");k(d)&&d.classList.remove("compromised-password-ribbon-padding");k(c)&&c.classList.remove("compromised-password-ribbon-padding");for(c=0;c<a.length;c++)document.documentElement.removeChild(a[c])};f._localize=function(a){return new Promise(function(b,c){h.getLocalizedStringsWithFormat(a,function(a){SymBfw.utils.isEmptyObject(a)?c():b(a)})})};
a.IDSafe.compromisedPasswordRibbon=f;f.init()})(executionContext);
