var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(d){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(d||"")+"_"+b++,d)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var d=0,c={next:function(){if(d<a.length){var g=d++;return{value:b(g,a[g]),done:!1}}c.next=function(){return{done:!0,value:void 0}};return c.next()}};c[Symbol.iterator]=function(){return c};return c};
$jscomp.polyfill=function(a,b,d,c){if(b){d=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var g=a[c];g in d||(d[g]={});d=d[g]}a=a[a.length-1];c=d[a];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
$jscomp.polyfill("Object.values",function(a){return a?a:function(a){var b=[],c;for(c in a)$jscomp.owns(a,c)&&b.push(a[c]);return b}},"es8","es3");
(function(a){a.IDSafe.formHandler=function(a,d,c,g){var b=a.logger,q=a.utils.isNil,h=a.utils.isString,u=a.utils.createNewGuid,k=c.utils.isWaxLoginForm,r=c.utils.isWaxCardForm,l=c.utils.isWaxChangePasswordForm,n=c.constants.groupType,p=a.utils.isFunction,v=a.utils.isEmptyObject,f={_waxFormsDict:{},_formFoundCallback:null,_formSubmitCallback:null,_formRemovedCallback:null,waxInit:function(a,t,b){if(!p(a)||!p(t)||!p(b))throw Error("callback must be a function");c.main.registerFormsFound(f._onFormsFound);
c.main.registerFormSubmitted(f._onFormSubmitted);f._formFoundCallback=a;f._formSubmitCallback=t;f._formRemovedCallback=b;c.main.init()},_onFormsFound:function(a){if(!v(f._waxFormsDict)){a=f._getDifferenceInWaxForms(a);var e=a.removedWaxFormIDs;e.forEach(function(a){delete f._waxFormsDict[a]});f._formRemovedCallback(e);a=a.newWaxForms;if(0===a.length)return}a.forEach(function(a){if(k(a)||r(a)||l(a)){var e=u();f._waxFormsDict[e]=a;f._formFoundCallback(a.getFormType(),e,a)}})},_getLoginObjectFromLoginForm:function(a){return{username:a.getUsername(),
password:a.getPassword()}},_getChangePasswordObject:function(a){return{formType:n.CHANGE_PASSWORD_PAGE,vaultItemID:a.getVaultItemId(),password:a.getPassword()}},_onFormSubmitted:function(a){if(l(a))var e=f._getChangePasswordObject(a);else if(k(a))if(e=f._getLoginObjectFromLoginForm(a),a._formType==n.LOGIN){if(0==e.username.trim().length||0==e.password.trim().length){b.debug("Not saving credentials as username or password field is empty");return}}else{if(a._formType==n.PARTIAL_LOGIN){if(!h(e.username)&&
h(e.password)&&0==e.password.trim().length){b.debug("Not saving credentials as password field is empty");return}if(h(e.username)&&h(e.password)&&(0==e.username.trim().length||0==e.password.trim().length)){b.debug("Form classified as partial login even when username and password fields are available. Not saving credentials as username or password field is empty");return}}}else return;f._formSubmitCallback(a.getFormType(),e)},fillForm:function(a,b,d){if(q(a))throw Error("formID cannot be nil");if(q(b))throw Error("vaultItem cannot be nil");
a=f._waxFormsDict[a];if(!k(a)&&!r(a)&&!l(a))throw Error("waxForm is not a supported form type");return c.formFiller.fillForm(a,b,d)},_isEqualWaxFields:function(a,b){return a.getFieldType()!==b.getFieldType()||a.getInputType()!==b.getInputType()||a.getElement()!==b.getElement()?!1:!0},_isShallowEqualWaxForms:function(a,b){if(a.getFormType()!==b.getFormType()||a.getHtmlForm()!==b.getHtmlForm())return!1;var c=a.getCategorizedWaxFields()||[],e=b.getCategorizedWaxFields()||[];if(c.length!==e.length)return!1;
for(var d=0;d<c.length;d++)if(!1===f._isEqualWaxFields(c[d],e[d]))return!1;return a.canDisplayPopup()!=b.canDisplayPopup()?!1:!0},_getDifferenceInWaxForms:function(a){for(var b=[],c=[],d=[],e=Object.keys(f._waxFormsDict),g=Object.values(f._waxFormsDict),h=0;h<a.length;h++){for(var k=a[h],l=!1,m=0;m<g.length;m++)if(!0===f._isShallowEqualWaxForms(g[m],k)){l=!0;d.push(e[m]);break}!1===l&&b.push(k)}for(a=0;a<e.length;a++)g=e[a],-1===d.indexOf(g)&&c.push(g);return{newWaxForms:b,removedWaxFormIDs:c}},reAnalyzePage:function(){c.main.analyzePage()}};
return f}(a.SymBfw,a.SymO2,a.SymWax,a.IDSafe)})(executionContext);
