var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.owns=function(a,c){return Object.prototype.hasOwnProperty.call(a,c)};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,h){a!=Array.prototype&&a!=Object.prototype&&(a[c]=h.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,c,h,g){if(c){h=$jscomp.global;a=a.split(".");for(g=0;g<a.length-1;g++){var d=a[g];d in h||(h[d]={});h=h[d]}a=a[a.length-1];g=h[a];c=c(g);c!=g&&null!=c&&$jscomp.defineProperty(h,a,{configurable:!0,writable:!0,value:c})}};
$jscomp.polyfill("Object.values",function(a){return a?a:function(a){var c=[],g;for(g in a)$jscomp.owns(a,g)&&c.push(a[g]);return c}},"es8","es3");$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):$jscomp.arrayIterator(a)};
$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function c(){this.batch_=null}function h(b){return b instanceof d?b:new d(function(f,a){f(b)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;c.prototype.asyncExecute=function(b){if(null==this.batch_){this.batch_=[];var f=this;this.asyncExecuteFunction(function(){f.executeBatch_()})}this.batch_.push(b)};var g=$jscomp.global.setTimeout;c.prototype.asyncExecuteFunction=function(b){g(b,0)};c.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var b=
this.batch_;this.batch_=[];for(var f=0;f<b.length;++f){var a=b[f];b[f]=null;try{a()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};c.prototype.asyncThrow_=function(b){this.asyncExecuteFunction(function(){throw b;})};var d=function(b){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var a=this.createResolveAndReject_();try{b(a.resolve,a.reject)}catch(k){a.reject(k)}};d.prototype.createResolveAndReject_=function(){function b(b){return function(f){c||(c=!0,b.call(a,f))}}var a=this,c=!1;
return{resolve:b(this.resolveTo_),reject:b(this.reject_)}};d.prototype.resolveTo_=function(b){if(b===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof d)this.settleSameAsPromise_(b);else{a:switch(typeof b){case "object":var a=null!=b;break a;case "function":a=!0;break a;default:a=!1}a?this.resolveToNonPromiseObj_(b):this.fulfill_(b)}};d.prototype.resolveToNonPromiseObj_=function(b){var a=void 0;try{a=b.then}catch(k){this.reject_(k);return}"function"==typeof a?
this.settleSameAsThenable_(a,b):this.fulfill_(b)};d.prototype.reject_=function(b){this.settle_(2,b)};d.prototype.fulfill_=function(b){this.settle_(1,b)};d.prototype.settle_=function(b,a){if(0!=this.state_)throw Error("Cannot settle("+b+", "+a+"): Promise already settled in state"+this.state_);this.state_=b;this.result_=a;this.executeOnSettledCallbacks_()};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var b=0;b<this.onSettledCallbacks_.length;++b)m.asyncExecute(this.onSettledCallbacks_[b]);
this.onSettledCallbacks_=null}};var m=new c;d.prototype.settleSameAsPromise_=function(b){var a=this.createResolveAndReject_();b.callWhenSettled_(a.resolve,a.reject)};d.prototype.settleSameAsThenable_=function(a,c){var b=this.createResolveAndReject_();try{a.call(c,b.resolve,b.reject)}catch(l){b.reject(l)}};d.prototype.then=function(a,c){function b(a,b){return"function"==typeof a?function(b){try{f(a(b))}catch(n){e(n)}}:b}var f,e,p=new d(function(a,b){f=a;e=b});this.callWhenSettled_(b(a,f),b(c,e));return p};
d.prototype.catch=function(a){return this.then(void 0,a)};d.prototype.callWhenSettled_=function(a,c){function b(){switch(d.state_){case 1:a(d.result_);break;case 2:c(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?m.asyncExecute(b):this.onSettledCallbacks_.push(b)};d.resolve=h;d.reject=function(a){return new d(function(b,c){c(a)})};d.race=function(a){return new d(function(b,c){for(var d=$jscomp.makeIterator(a),e=d.next();!e.done;e=d.next())h(e.value).callWhenSettled_(b,
c)})};d.all=function(a){var b=$jscomp.makeIterator(a),c=b.next();return c.done?h([]):new d(function(a,d){function e(b){return function(c){f[b]=c;g--;0==g&&a(f)}}var f=[],g=0;do f.push(void 0),g++,h(c.value).callWhenSettled_(e(f.length-1),d),c=b.next();while(!c.done)})};return d},"es6","es3");
(function(a){var c=IDSafe.uiConstants.AUTO_PASSWORD_CHANGER_OVERLAY,h=c.TYPES,g=c.MESSAGES,d=SymBfw.uiUtils,m=SymBfw.extensionAdapter,b=SymBfw.utils.isNil,f=SymBfw.utils.isntNil,k=SymBfw.utils.isEmptyObject,l=SymBfw.localizerProxy,e={_isListenersAdded:!1,_currentType:null,_data:{},_strings:{interactive:"Please enter the information required below to change your password.",inProgress:"{0} is changing your {1} password. Do not close this page.",success:"Your new {0} Login has been saved successfully.",
failure:"An error occurred and your Login was not changed. We are working on this, please try again later."},show:function(a,c){if(window.self===window.top){if(b(c)||k(c))throw Error("Location cannot be null");if(b(a)||-1===Object.values(h).indexOf(a))throw Error("Unsupported popup type: "+a);f(e._currentType)||(e._currentType=a,e._isListenersAdded||(e._addListener(),e._isListenersAdded=!0),e._injectPopup(c))}},_addListener:function(){m.addContentScriptMessageListener(function(a,b,c){switch(a.id){case g.OVERLAY_HIDE:e.close();
break;case g.OVERLAY_INIT:b({type:e._currentType,data:e._data})}})},_injectPopup:function(a){var b=e._strings[e._currentType],f=new Promise(function(a,b){l.getCurrentLanguageDirection(function(b){a(b)})}),g=new Promise(function(a,c){var d={};d[b]=["__LONG_PRODUCT_NAME__",document.location.host];l.getLocalizedStringsWithFormat(d,function(d){SymBfw.utils.isEmptyObject(d)?c():a(d[b])})});Promise.all([f,g]).then(function(b){var f=b[1];e._data.direction=b[0];e._data.localizedString=f;e._data.type=e._currentType;
e.popupHtml=m.getExtensionURL(c.HTML);e.style=m.getExtensionURL(c.STYLE);d.injectStyle(e.style);e._createBannerFrame(a)})},close:function(){for(var a=document.querySelectorAll("#"+c.IFRAME_ID),b=0;b<a.length;b++)document.documentElement.removeChild(a[b]);e._currentType=null;e._isListenersAdded=!1},_createBannerFrame:function(a){f(window.top.document.getElementById(c.IFRAME_ID))||b(a)||k(a)||d.createFrame(c.IFRAME_ID,e.popupHtml,c.HEIGHT,c.WIDTH,a)}};a.IDSafe.passwordChangerOverlay=e})(executionContext);
