(function(l){l.IDSafe.telemetryWrapper=function(f){var n=f.utils.isNil,g=f.utils.isntNil,p=f.utils.isString,k=f.utils.isInteger,l=f.utils.isObject,h=f.telemetryConstants,m=f.logger,q=IDSafe.constants.autochange,t=q.AUTOCHANGE_LABEL,u=q.AUTOCHANGE_FAILED,a={LOGIN_TYPE_SPOC:"SPOC",LOGIN_TYPE_LOCAL:"LOCAL",TELEMETRY_CATEGORY:{IDSCRYPTO:"IDSCrypto",BROWSER:"Browser",IDSAFE:"IDSafe",LOGIN:"Login",WAX:"Wax",OPENID:"OpenID",CCT:"cct",IDSVAULT:"IDSVault",PASSWORDCHANGER:"PasswordChanger",WELCOME_NOTIFICATION:"Welcome_Notification",
MOBILE_UNLOCK:"mobile_unlock",COMPROMISED_PASSWORDS:"Compromised_Passwords"},IDS_CRYPTO_ERROR_CONSTANTS:{DIGEST_COMPARISON_FAILURE:"Digest Comparison failure",TYPE_COMPARISON_FAILURE:"Type comparison failure",CHECKSUM_COMPARISON_FAILURE:"Checksum comparison failure",UNABLE_TO_ANSWER_CHALLENGE:"Unable to answer challenge",UNABLE_TO_CALCULATE_CHECKSUM:"Unable to calculate checksum",UNABLE_TO_DECRYPT_ITEM:"Unable to decrypt item",UNABLE_TO_ENCRYPT_ITEM:"Unable to encrypt item",UNABLE_TO_OBFUSCATE_ITEM:"Unable to obfuscate item"},
actionType:{BROWSER:{LAUNCH:"launch",UPDATE:"update"},CCT:{LAUNCH:"launch",SUCCESS:"success"},IDSAFE:{UPDATE:"update"},WELCOME_NOTIFICATION:{LEARN_MORE:"Learn_More",CLOSE:"Close"},LOGIN:{ADD:"add",MODIFY:"modify",DELETE:"delete",SEARCH:"search",SIGNIN:"signin"},WAX:{FORMSUBMIT:"formsubmit",FILLFAILURE:"fillfailure",HTTPSNOTFOUND:"httpsnotfound"},OPENID:{LAUNCH:"launch",LOGINSUCCESS:"loginsuccess",PAGECLOSED:"pageclosed"},PASSWORDCHANGER:{AUTOCHANGEPASSWORD:"autochangepassword"},IDSVAULT:{MERGE:"merge",
VAULTSTATISTICS:"vaultstatistics",LOGINURLCOUNT:"loginurlcount",UPDATE:"update",CREATEVAULT:"createvault",DELETEVAULT:"deletevault",CHANGEVAULTPASSWORD:"changevaultpassword",OPENVAULT:"openvault"},MOBILE_UNLOCK:{MOBILERESPONSE:"mobileresponse",MOBILEUNLOCKSUCCESS:"mobileunlocksuccess"},COMPROMISED_PASSWORDS:{REPLACEPASSWORDSINMOT:"replacepasswordsinmot",NOTIFICATIONDISMISSED:"notificationdismissed",LEARNMORECLICKED:"learnmoreclicked",SITENOTSUPPORTED:"sitenotsupported",OPENVAULTFROMCP:"openvaultfromcp",
CPEVENTS:"cpevents"}},COMPROMISED_PASSWORD_PAYLOAD_CONSTANTS:{AUTOCHANGE_LAUNCHED:"autochangelaunched",VAULT_CREATED_SUCCESS:"vaultcreatedsuccess",VAULT_OPEN_SUCCCESS:"vaultopensuccess",PASSWORD_REPLACED_SUCCESS:"passwordreplacesuccesss",LERAN_MORE_CLICKED:"learnmoreclicked",NOTIFICATION_DISMISSED:"notificadtiondismissed",NOTIFICATION_SHOWN:"notificationshown",COMPROMISED_PASSWORD_DETECTED:"compromisedpassworddetected",AUTOCHANGE_SUCCESS:"autochangesuccess",NOTIFICATION_CLICKED:"notificationclicked"},
OPENID_LABEL:{DELETEVAULT:"deletevault"},CCT_LABEL:{CCTLAUNCH:"cctLaunch",CCTSUCCESS:"cctSuccess"},IDSVAULT_LABEL:{SIZE:"size",AVAILABILITY:"availability",PASSWORD:"password",PASSWORDHINT:"passwordhint",CREATEVAULTSUCCESS:"createvaultsuccess",FAILEDTOCREATE:"failedtocreate",DELETEVAULTSUCCESS:"deletevaultsuccess",FAILEDTODELETE:"failedtodelete",CHANGEVAULTPASSWORDFAILED:"changevaultpasswordfailed",CHANGEVAULTPASSWORDSUCCESS:"changevaultpasswordsuccess"},WAX_FORMSUBMIT_VALUE:{MANUAL:2,AUTOSUBMIT:1},
WAX_FILLFAILURE_VALUE:{LOGINFORM:1},sendVaultMobileUnlockResponselTime:function(b){try{var c=a.TELEMETRY_CATEGORY.MOBILE_UNLOCK,d=a.actionType.MOBILE_UNLOCK.MOBILERESPONSE;this.checkStringIsValid(b);a.send(c,d,b)}catch(e){m.debug(e)}},sendVaultMobileUnlockSuccessTime:function(b){try{var c=a.TELEMETRY_CATEGORY.MOBILE_UNLOCK,d=a.actionType.MOBILE_UNLOCK.MOBILEUNLOCKSUCCESS;this.checkStringIsValid(b);a.send(c,d,b)}catch(e){m.debug(e)}},sendIDSCryptoError:function(b,c){var d=a.TELEMETRY_CATEGORY.IDSCRYPTO;
this.checkStringIsValid(b);this.checkStringIsValid(c);a.send(d,c,b)},sendVaultHealthStatus:function(b){var c=a.TELEMETRY_CATEGORY.IDSVAULT,d=a.actionType.IDSVAULT.OPENVAULT;b=JSON.stringify(b);a.send(c,d,b)},createVaultFailure:function(b,c){a.send(a.TELEMETRY_CATEGORY.IDSVAULT,a.actionType.IDSVAULT.CREATEVAULT,a.IDSVAULT_LABEL.FAILEDTOCREATE+"(additionalInfo-"+c+",state-"+b+")")},createVaultSuccess:function(b){b=void 0===b?null:b;var c=a.TELEMETRY_CATEGORY.IDSVAULT,d=a.actionType.IDSVAULT.CREATEVAULT,
e=a.IDSVAULT_LABEL.CREATEVAULTSUCCESS;l(b)&&g(b.key)&&g(b.value)?a.send(c,d,e,b):a.sendTelemetry(c,d,e)},deleteVaultSuccess:function(){a.send(a.TELEMETRY_CATEGORY.IDSVAULT,a.actionType.IDSVAULT.DELETEVAULT,a.IDSVAULT_LABEL.DELETEVAULTSUCCESS)},deleteVaultSSOLoginSuccess:function(){a.send(a.TELEMETRY_CATEGORY.OPENID,a.actionType.OPENID.LOGINSUCCESS,a.OPENID_LABEL.DELETEVAULT)},deleteVaultSSOPageClosed:function(){a.send(a.TELEMETRY_CATEGORY.OPENID,a.actionType.OPENID.PAGECLOSED,a.OPENID_LABEL.DELETEVAULT)},
deleteVaultFailure:function(b,c){a.send(a.TELEMETRY_CATEGORY.IDSVAULT,a.actionType.IDSVAULT.DELETEVAULT,a.IDSVAULT_LABEL.FAILEDTODELETE+"(additionalInfo-"+c+",state-"+b+")")},autoPasswordChanger:function(b,c){c=void 0===c?null:c;var d=a.TELEMETRY_CATEGORY.PASSWORDCHANGER,e=a.actionType.PASSWORDCHANGER.AUTOCHANGEPASSWORD;l(c)&&g(c.key)&&g(c.value)?a.send(d,e,b,c):a.send(d,e,b)},changeVaultPasswordFailure:function(b,c){a.send(a.TELEMETRY_CATEGORY.IDSVAULT,a.actionType.IDSVAULT.CHANGEVAULTPASSWORD,a.IDSVAULT_LABEL.CHANGEVAULTPASSWORDFAILED+
"(additionalInfo-"+c+",state-"+b+")")},changeVaultPasswordSuccess:function(){a.send(a.TELEMETRY_CATEGORY.IDSVAULT,a.actionType.IDSVAULT.CHANGEVAULTPASSWORD,a.IDSVAULT_LABEL.CHANGEVAULTPASSWORDSUCCESS)},sendBrowserSignin:function(b){var c=a.TELEMETRY_CATEGORY.LOGIN,d=a.actionType.LOGIN.SIGNIN;this.checkStringIsValid(b);a.sendTelemetry(c,d,b)},sendBrowserUpdate:function(b){var c=a.TELEMETRY_CATEGORY.BROWSER,d=a.actionType.BROWSER.UPDATE;this.checkStringIsValid(b);a.send(c,d,b)},sendExtensionInstall:function(){var b=
h.TELEMETRY_CATEGORY.EXTENSION,c=h.actionType.EXTENSION.INSTALL,d=f.extensionAdapter.getExtensionId()+"-"+IDSafe.extension.getVersion();a.send(b,c,d)},sendExtensionUpdate:function(){var b=h.TELEMETRY_CATEGORY.EXTENSION,c=h.actionType.EXTENSION.UPDATE,d=f.extensionAdapter.getExtensionId()+"-"+IDSafe.extension.getVersion();a.send(b,c,d)},sendLearnMoreClicked:function(){var b=a.TELEMETRY_CATEGORY.WELCOME_NOTIFICATION,c=a.actionType.WELCOME_NOTIFICATION.LEARN_MORE,d=f.extensionAdapter.getExtensionId()+
"-"+IDSafe.extension.getVersion();a.send(b,c,d)},sendCloseClicked:function(){var b=a.TELEMETRY_CATEGORY.WELCOME_NOTIFICATION,c=a.actionType.WELCOME_NOTIFICATION.CLOSE,d=f.extensionAdapter.getExtensionId()+"-"+IDSafe.extension.getVersion();a.send(b,c,d)},sendCCTLaunched:function(){a.sendTelemetry(a.TELEMETRY_CATEGORY.CCT,a.actionType.CCT.LAUNCH,a.CCT_LABEL.CCTLAUNCH)},sendCCTSuccess:function(){a.send(a.TELEMETRY_CATEGORY.CCT,a.actionType.CCT.SUCCESS,a.CCT_LABEL.CCTSUCCESS)},sendLoginAdd:function(b,
c){var d=a.TELEMETRY_CATEGORY.LOGIN;if(b!==this.LOGIN_TYPE_SPOC&&b!==this.LOGIN_TYPE_LOCAL)throw Error("type must be either SPOC or LOCAL");b=a.actionType.LOGIN.ADD+"-"+b;!1===k(c)&&(c=1);a.send(d,b,c+"")},sendLoginModify:function(b,c){var d=a.TELEMETRY_CATEGORY.LOGIN;if(b!==this.LOGIN_TYPE_SPOC&&b!==this.LOGIN_TYPE_LOCAL)throw Error("type must be either SPOC or LOCAL");b=a.actionType.LOGIN.MODIFY+"-"+b;!1===k(c)&&(c=1);a.send(d,b,c+"")},sendLoginDelete:function(b,c){var d=a.TELEMETRY_CATEGORY.LOGIN;
if(b!==this.LOGIN_TYPE_SPOC&&b!==this.LOGIN_TYPE_LOCAL)throw Error("type must be either SPOC or LOCAL");b=a.actionType.LOGIN.DELETE+"-"+b;!1===k(c)&&(c=1);a.send(d,b,c+"")},sendWaxFormSubmit:function(b,c,d){var e=a.TELEMETRY_CATEGORY.WAX;this.checkStringIsValid(b);this.checkValueInRange(c,1,2);b=a.actionType.WAX.FORMSUBMIT+"-"+b;f.utils.isBoolean(d)&&d&&(b=b+"-"+IDSafe.constants.NPW_ISOLATION);a.send(e,b,c+"")},sendWaxFillFailure:function(b){var c=a.TELEMETRY_CATEGORY.WAX,d=a.actionType.WAX.FILLFAILURE;
this.checkStringIsValid(b);a.send(c,d,b)},sendWaxFillHttpsNotFoundFailure:function(b){var c=a.TELEMETRY_CATEGORY.WAX,d=a.actionType.WAX.HTTPSNOTFOUND;this.checkStringIsValid(b);a.send(c,d,b)},sendIDSVaultMerge:function(b){var c=a.TELEMETRY_CATEGORY.IDSVAULT,d=a.actionType.IDSVAULT.MERGE;this.checkStringIsValid(b);a.send(c,d,b)},sendIDSVaultStatistics:function(b,c){var d=a.TELEMETRY_CATEGORY.IDSVAULT;switch(b){case a.IDSVAULT_LABEL.SIZE:this.checkValueInRange(c);break;case a.IDSVAULT_LABEL.AVAILABILITY:this.checkValueInRange(c,
0,1);break;default:throw Error("label must be either 'size' or 'availability'");}a.sendTelemetry(d,a.actionType.IDSVAULT.VAULTSTATISTICS+"-"+b,c+"")},sendIDSVaultLoginURLCount:function(b,c){var d=a.TELEMETRY_CATEGORY.IDSVAULT;this.checkStringIsValid(b);this.checkValueInRange(c);a.send(d,a.actionType.IDSVAULT.LOGINURLCOUNT+"-"+b,c+"")},sendIDSVaultUpdate:function(b){var c=a.TELEMETRY_CATEGORY.IDSVAULT,d=a.actionType.IDSVAULT.UPDATE,e=a.IDSVAULT_LABEL.PASSWORDHINT;if(b!==a.IDSVAULT_LABEL.PASSWORD&&
b!==e)throw Error("label must be either 'password' or 'passwordhint'");a.send(c,d,b)},sendTelemetry:function(a,c,d){var b=this,r=IDSafe.globalSettings.getValue(IDSafe.constants.NUDGE_SCREEN_OPEN)?{key:h.parameters.CUSTOM_DIMENSION5,value:IDSafe.constants.NPW_NUDGE}:null;c===this.actionType.LOGIN.SIGNIN?f.extensionAdapter.getActiveTab(function(e){e.url===f.extensionAdapter.getExtensionURL(IDSafe.uiConstants.NUDGE_SCREEN.CONTENT_PAGE_URL)?b.send(a,c,d,r):b.send(a,c,d)}):this.send(a,c,d,r)},send:function(a,
c,d,e){e=void 0===e?null:e;this.checkStringIsValid(a);this.checkStringIsValid(c);this.checkStringIsValid(d);if(!this.actionExists(a,c))throw Error(a+" does not have action "+c+".");if(g(e)&&(!1===p(e.key)||0===e.length&&!1===p(e.value)||0===e.length))throw Error("customDimension.value or customDimension.key should be a string");var b={};b[h.parameters.HIT_TYPE]=h.HIT_TYPE.EVENT;b[h.parameters.CATEGORY]=a;b[h.parameters.ACTION]=c;b[h.parameters.LABEL]=d;g(e)&&(b[e.key]=e.value);(f.telemetry||f.telemetryProxy).send(b)},
sendAutochangeErrorTelemetry:function(b){m.debug("Autochange telemetry data is: "+b.length+" bytes long.");a.sendSocialTelemetry(t,u,b)},sendSocialTelemetry:function(a,c,d){var b=h.parameters,g={};a=(g[b.HIT_TYPE]=h.HIT_TYPE.SOCIAL,g[b.SOCIAL_NETWORK]=a,g[b.SOCIAL_ACTION]=c,g[b.SOCIAL_TARGET]=d,g);(f.telemetry||f.telemetryProxy).send(a)},checkValueInRange:function(a,c,d){c=c||0;if(!f.utils.isInteger(a))throw Error("value must be an integer");if(a<c)throw Error("value must be greater than or equal to "+
c);if(g(d)&&a>d)throw Error("value must be less than or equal to "+d);},checkStringIsValid:function(a){if(!p(a))throw Error(a+" must be of type string");},actionExists:function(b,c){if(b===a.TELEMETRY_CATEGORY.IDSCRYPTO){b=a.IDS_CRYPTO_ERROR_CONSTANTS;for(var d in b)if(b[d]===c)return!0;return!1}if(n(a.actionType[b.toUpperCase()])&&n(h.actionType[b.toUpperCase()]))return!1;d=c.indexOf("-");var e=c;-1<d&&(e=c.substring(0,d),console.log(e));return g(a.actionType[b.toUpperCase()])&&g(a.actionType[b.toUpperCase()][e.toUpperCase()])||
g(h.actionType[b.toUpperCase()])&&g(h.actionType[b.toUpperCase()][e.toUpperCase()])?!0:!1},sendLoginTelemetryFromSPOC:function(b){if(n(b))throw Error("nodeStatusList is nil");if("object"!==typeof b)throw Error("nodeStatusList must be of type object");var c=b.added,d=b.updated;b=b.deleted;if(!k(c)||!k(d)||!k(b))throw Error("nodeStatusList addedNodes/updatedNodes/deleteNodes must be integers");0<c&&a.sendLoginAdd(a.LOGIN_TYPE_SPOC,c);0<d&&a.sendLoginModify(a.LOGIN_TYPE_SPOC,d);0<b&&a.sendLoginDelete(a.LOGIN_TYPE_SPOC,
b)},getDefaultParametersForWaxTelemetry:function(){var a=f.telemetryConstants;return{APPLICATION_NAME:IDSafe.constants.NORTON_IDENTITY_SAFE+"_"+f.extensionAdapter.getExtensionId(),APPLICATION_VERSION:IDSafe.extension.getVersion(),DATA_SOURCE:a.dataSource.BROWSER_EXTENSION,USER_LANGUAGE:navigator.language,ANONYMIZE_IP:1,GOOGLE_ANALYTICS_PROTOCOL_VERSION:1}},sendAutochangeNotSupportedCP:function(b){try{this.checkStringIsValid(b),a.send(a.TELEMETRY_CATEGORY.COMPROMISED_PASSWORDS,a.actionType.COMPROMISED_PASSWORDS.SITENOTSUPPORTED,
b)}catch(c){m.debug(c)}},sendCompromisedPasswordNotificationClicked:function(){a.send(a.TELEMETRY_CATEGORY.COMPROMISED_PASSWORDS,a.actionType.COMPROMISED_PASSWORDS.CPEVENTS,a.COMPROMISED_PASSWORD_PAYLOAD_CONSTANTS.NOTIFICATION_CLICKED)},sendCompromisedPasswordNotificationShown:function(){a.send(a.TELEMETRY_CATEGORY.COMPROMISED_PASSWORDS,a.actionType.COMPROMISED_PASSWORDS.CPEVENTS,a.COMPROMISED_PASSWORD_PAYLOAD_CONSTANTS.NOTIFICATION_SHOWN)},sendCompromisedPasswordDetected:function(){a.send(a.TELEMETRY_CATEGORY.COMPROMISED_PASSWORDS,
a.actionType.COMPROMISED_PASSWORDS.CPEVENTS,a.COMPROMISED_PASSWORD_PAYLOAD_CONSTANTS.COMPROMISED_PASSWORD_DETECTED)},sendVaultOpenFromCP:function(){a.send(a.TELEMETRY_CATEGORY.COMPROMISED_PASSWORDS,a.actionType.COMPROMISED_PASSWORDS.OPENVAULTFROMCP,a.COMPROMISED_PASSWORD_PAYLOAD_CONSTANTS.VAULT_OPEN_SUCCCESS)},sendPasswordReplacedMOT:function(){a.send(a.TELEMETRY_CATEGORY.COMPROMISED_PASSWORDS,a.actionType.COMPROMISED_PASSWORDS.REPLACEPASSWORDSINMOT,a.COMPROMISED_PASSWORD_PAYLOAD_CONSTANTS.PASSWORD_REPLACED_SUCCESS)},
sendLearnMoreClickedCP:function(){a.send(a.TELEMETRY_CATEGORY.COMPROMISED_PASSWORDS,a.actionType.COMPROMISED_PASSWORDS.LEARNMORECLICKED,a.COMPROMISED_PASSWORD_PAYLOAD_CONSTANTS.LERAN_MORE_CLICKED)},sendNotificationDismissedCp:function(){a.send(a.TELEMETRY_CATEGORY.COMPROMISED_PASSWORDS,a.actionType.COMPROMISED_PASSWORDS.NOTIFICATIONDISMISSED,a.COMPROMISED_PASSWORD_PAYLOAD_CONSTANTS.NOTIFICATION_DISMISSED)}};return a}(l.SymBfw)})(executionContext);
