(function(b){(b.IDSafe=b.IDSafe||{}).pageViewTelemetryWrapper=function(e,b){var l=e.utils.isntNil,h=e.utils.isString,g=e.telemetryConstants,f={constants:{}};f.constants.DOCUMENT_TITLE={MISC_SETTINGS_MENU:"misc-settings-view",LOGIN_LIST_VIEW:"login-list-view",LOGIN_DETAILS_VIEW:"login-details-view",MAIN_UI_NA_SIGNIN:"mainui-NA-sign-in",MAIN_UI_OPEN_VAULT:"mainui-open-vault",NA_SIGN_OUT_POPUP:"NA-signout-popup",CLOSE_VAULT_CONFIRMATION:"close-vault-confirmation",VAULT_UNLOCK_TAB:"vault-unlock",SSO_LOGIN:"sso-login",
LOCKED_LOGIN_UNLOCK_UI:"login-pwd-protect",VERIFY_VAULT_PASSWORD_UI:"verify-vault-password-ui",NO_VAULT_DETECTED:"no-vault-detected",SAVE_UPDATE_LOGIN_NOTIFICATION:"save-update-login-notification",SINGLE_LOGIN_ANCHORED_POPUP_FIELD_CLICK:"single-login-fill-popup-field-click",MULTI_LOGIN_ANCHORED_POPUP_FIELD_CLICK:"multi-login-fill-popup-field-click",SINGLE_LOGIN_ANCHORED_POPUP_PAGE_LOAD:"single-login-fill-popup-page-load",MULTI_LOGIN_ANCHORED_POPUP_PAGE_LOAD:"multi-login-fill-popup-page-load",CARD_FIELD_BADGE_CLICK:"card-field-badge-click",
CARD_FIELD_BADGE_POPUP_PAGE_LOAD:"card-field-badge-popup-page-load",CREATE_VAULT_PASSWORD_UI:"create-vault-password-ui",CREATE_VAULT_CONFIRM_PASSWORD_UI:"create-vault-confirm-password-ui",CREATE_VAULT_PASSWORD_HINT_UI:"create-vault-password-hint-ui",CREATE_VAULT_TAB_CLOSE:"create-vault-tab-close",DELETE_VAULT_PAGE_SHOWN:"delete-vault-page-shown",DELETE_VAULT_OPTION_SHOWN:"delete-vault-option-shown",CHANGE_VAULT_PASSWORD_PAGE_SHOWN:"change-vault-password-page-shown",VAULT_TAB_UI_SHOWN:"vault-tab-ui-shown",
VTU_LOGIN_LIST_SHOWN:"vtu-login-list-shown",VTU_WALLET_LIST_SHOWN:"vtu-wallet-list-shown",VTU_ADDRESS_LIST_SHOWN:"vtu-address-list-shown",VTU_NOTES_LIST_SHOWN:"vtu-notes-list-shown",VTU_LOGIN_GRID_SHOWN:"vtu-login-grid-shown",VTU_PASSWORD_PROTECTION_SHOWN:"vtu-password-protection-shown",VTU_DELETE_PAGE_SHOWN:"vtu-delete-page-shown",VTU_DELETE_INPROGRESS_SHOWN:"vtu-delete-inprogress-shown",VTU_LOGIN_ADD_SHOWN:"vtu-login-add-shown",VTU_LOGIN_EDIT_SHOWN:"vtu-login-edit-shown",VTU_WALLET_ADD_SHOWN:"vtu-wallet-add-shown",
VTU_WALLET_EDIT_SHOWN:"vtu-wallet-edit-shown",VTU_ADDRESS_ADD_SHOWN:"vtu-address-add-shown",VTU_ADDRESS_EDIT_SHOWN:"vtu-address-edit-shown",VTU_NOTES_ADD_SHOWN:"vtu-notes-add-shown",VTU_NOTES_EDIT_SHOWN:"vtu-notes-edit-shown",IMPORT_DOWNLOAD_PAGE_SHOWN:"import-download-page-shown",IMPORT_UPLOAD_COMPLETE_SHOWN:{"Chrome and Firefox passwords":"import-upload-complete-shown-browser",Dashlane:"import-upload-complete-shown-dashlane",LastPass:"import-upload-complete-shown-lastpass","LastPass (binary version)":"import-upload-complete-shown-lastpass-binary",
"1Password":"import-upload-complete-shown-onepass"},IMPORT_LOGIN_LIST_SHOWN:{"Chrome and Firefox passwords":"import-login-list-shown-browser",Dashlane:"import-login-list-shown-dashlane",LastPass:"import-login-list-shown-lastpass","LastPass (binary version)":"import-login-list-shown-lastpass-binary","1Password":"import-login-list-shown-onepass"},IMPORT_SUCCESS:{"Chrome and Firefox passwords":"import-success-browser",Dashlane:"import-success-dashlane",LastPass:"import-success-lastpass","LastPass (binary version)":"import-success-lastpass-binary",
"1Password":"import-success-onepass"},IMPORT_FAILURE:{"Chrome and Firefox passwords":"import-failure-browser",Dashlane:"import-failure-dashlane",LastPass:"import-failure-lastpass","LastPass (binary version)":"import-failure-lastpass-binary","1Password":"import-failure-onepass"},SECURITY_DASHBOARD_UI_SHOWN:"security-dashboard-ui-shown",PASSWORD_GENERATOR_SHOWN:"password-generator-shown",CHANGE_PASSWORD_FIELD_BADGE_CLICK:"change-password-field-badge-click",CHANGE_PASSWORD_POPUP_PAGE_LOAD:"change-password-popup-page-load",
SPLASH_SCREEN_SHOWN:"splash-screen-shown",NO_DEVICES_DETECTED_PAGE_SHOWN:"no-devices-detected-page-shown",NO_DEVICES_DETECTED_PAGE_SHOWN_AFTER_CONTINUE:"no-devices-detected-page-shown-after-clicking-continue",DEVICES_LIST_PAGE_SHOWN:"devices-list-page-shown",SETUP_COMPLETE_PAGE_SHOWN:"setup-complete-page-shown",MOBILE_UNLOCK_SETTINGS_PAGE_SHOWN:"mobile-unlock-settings-page-shown",UNLOCK_REQUEST_SENT_PAGE_SHOWN:"unlock-request-sent-page-shown",UNLOCK_REQUEST_TIMEDOUT_PAGE_SHOWN:"unlock-request-timedout-page-shown",
UNLOCK_REQUEST_CANCELED_PAGE_SHOWN:"unlock-request-canceled-page-shown",UNLOCK_REQUEST_COULD_NOT_BE_SENT_PAGE_SHOWN:"unlock-request-could-not-be-sent-page-shown",NUDGE_SCREEN_SHOWN:"nudge-screen-shown",NUDGE_SCREEN_CLOSED:"nudge-screen-closed"};f.sendLoginFillPopupPageViewTelemetry=function(d,c,a){this.send(d,1<c?!0===a?this.constants.DOCUMENT_TITLE.MULTI_LOGIN_ANCHORED_POPUP_FIELD_CLICK:this.constants.DOCUMENT_TITLE.MULTI_LOGIN_ANCHORED_POPUP_PAGE_LOAD:!0===a?this.constants.DOCUMENT_TITLE.SINGLE_LOGIN_ANCHORED_POPUP_FIELD_CLICK:
this.constants.DOCUMENT_TITLE.SINGLE_LOGIN_ANCHORED_POPUP_PAGE_LOAD)};f.sendCardFieldFillPopupPageViewTelemetry=function(d,c,a){this.send(d,!0===a?this.constants.DOCUMENT_TITLE.CARD_FIELD_BADGE_CLICK:this.constants.DOCUMENT_TITLE.CARD_FIELD_BADGE_POPUP_PAGE_LOAD,c.toString())};f.sendChangePasswordFieldFillPopupPageViewTelemetry=function(d,c,a){this.send(d,!0===a?this.constants.DOCUMENT_TITLE.CHANGE_PASSWORD_FIELD_BADGE_CLICK:this.constants.DOCUMENT_TITLE.CHANGE_PASSWORD_POPUP_PAGE_LOAD,c.toString())};
f.sendTelemetry=function(d,c){var a=this;c===this.constants.DOCUMENT_TITLE.MAIN_UI_NA_SIGNIN?e.extensionAdapter.getActiveTab(function(k){k.url===e.extensionAdapter.getExtensionURL(b.uiConstants.NUDGE_SCREEN.CONTENT_PAGE_URL)?a.send(d,c,b.constants.NPW_NUDGE):a.send(d,c)}):e.extensionAdapter.sendMessage({id:b.uiConstants.NUDGE_SCREEN.MESSAGES.GET_NUDGE_SCREEN_STATUS},function(k){k?a.send(d,c,b.constants.NPW_NUDGE):a.send(d,c)})};f.send=function(d,c,a){if(!1===h(d)||0===d.length)throw Error("documentPath should be a string");
if(!1===h(c)||0===c.length)throw Error("documentTitle should be a string");if(l(a)&&(!1===h(a)||0===a.length))throw Error("customDimensionValue should be a string");var b={};b[g.parameters.HIT_TYPE]=g.HIT_TYPE.PAGE_VIEW;b[g.parameters.DOCUMENT_PATH]=d;b[g.parameters.DOCUMENT_TITLE]=c;l(a)&&(b[g.parameters.CUSTOM_DIMENSION1]=a);e.telemetryProxy.send(b)};return f}(b.SymBfw,b.IDSafe)})(executionContext);
