var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};
$jscomp.polyfill=function(a,b,d,f){if(b){d=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var e=a[f];e in d||(d[e]={});d=d[e]}a=a[a.length-1];f=d[a];b=b(f);b!=f&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function d(a){return a instanceof e?a:new e(function(b,h){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var f=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){f(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var e=a[b];a[b]=null;try{e()}catch(w){this.asyncThrow_(w)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var e=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(u){b.reject(u)}};e.prototype.createResolveAndReject_=function(){function a(a){return function(c){e||(e=!0,a.call(b,c))}}var b=this,e=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};e.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};e.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(u){this.reject_(u);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};e.prototype.reject_=function(a){this.settle_(2,a)};e.prototype.fulfill_=function(a){this.settle_(1,a)};e.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)l.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var l=new b;e.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};e.prototype.settleSameAsThenable_=function(a,b){var e=this.createResolveAndReject_();try{a.call(b,e.resolve,e.reject)}catch(w){e.reject(w)}};e.prototype.then=function(a,b){function d(a,b){return"function"==typeof a?function(b){try{h(a(b))}catch(A){c(A)}}:b}var h,c,f=new e(function(a,b){h=a;c=b});this.callWhenSettled_(d(a,h),d(b,c));return f};
e.prototype.catch=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,b){function e(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?l.asyncExecute(e):this.onSettledCallbacks_.push(e)};e.resolve=d;e.reject=function(a){return new e(function(b,e){e(a)})};e.race=function(a){return new e(function(b,e){for(var f=$jscomp.makeIterator(a),c=f.next();!c.done;c=f.next())d(c.value).callWhenSettled_(b,
e)})};e.all=function(a){var b=$jscomp.makeIterator(a),f=b.next();return f.done?d([]):new e(function(a,c){function e(b){return function(c){h[b]=c;l--;0==l&&a(h)}}var h=[],l=0;do h.push(void 0),l++,d(f.value).callWhenSettled_(e(h.length-1),c),f=b.next();while(!f.done)})};return e},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(d){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(d||"")+"_"+b++,d)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(d){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var d=a.next();$jscomp.generator.ensureIteratorResultIsObject_(d);if(d.done)this.yieldResult=d.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(d.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,d){d?this.finallyContexts_[d]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,d){try{var f=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(f);if(!f.done)return this.context_.stop_(),f;var e=f.value}catch(l){return this.context_.yieldAllIterator_=null,this.context_.throw_(l),this.nextStep_()}this.context_.yieldAllIterator_=null;d.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(b){return a.next(b)}function d(b){return a.throw(b)}return new Promise(function(f,e){function l(a){a.done?f(a.value):Promise.resolve(a.value).then(b,d).then(l,e)}l(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.polyfill("Object.is",function(a){return a?a:function(a,d){return a===d?0!==a||1/a===1/d:a!==a&&d!==d}},"es6","es3");$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,d){var b=this;b instanceof String&&(b=String(b));var e=b.length;d=d||0;for(0>d&&(d=Math.max(d+e,0));d<e;d++){var l=b[d];if(l===a||Object.is(l,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,b,d){if(null==a)throw new TypeError("The 'this' value for String.prototype."+d+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+d+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,d){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,d||0)}},"es6","es3");
(function(a){a.IDSafe.waxContent=function(a,d,f,e){var b=a.logger,h=a.utils.isNil,D=a.utils.isFunction,u=a.utils.isString,w=a.utils.isArray,c={},n=e.uiConstants.MESSAGES,E=e.uiConstants.LOGIN_UNLOCK.messages,p=e.uiConstants.POPUP,x=e.uiConstants.POPUP.MESSAGES,A=a.uiUtils,v=a.utils.isntNil,r=e.uiConstants.FIELDSTYLING,F=e.idsSettingsProxy,q=e.constants,m=a.extensionAdapter,G=f.constants,H=f.utils,I=a.utils.createNewGuid,B=e.pageViewTelemetryWrapper,y=a.utils,J=a.utils.urlWithoutQueryParameters,C=
a.utils.baseURL,K=e.uiConstants.SECURITY_DASHBOARD.MESSAGES;c._timeoutStartProcessing=0;c._waxForms=[];c._primaryWaxForm=null;c._messageSenderId=null;c._isToolbarFound=!1;c._getURLProtocol=function(){return window.document.location.protocol.split(":")[0]};c._setLoginForm=function(a){h(a)?(c._waxForms=[],c._primaryWaxForm=null):(c._waxForms.push(a),c._startProcessWaxForms())};c._startProcessWaxForms=function(){0!==c._timeoutStartProcessing&&(clearTimeout(c._timeoutStartProcessing),c._timeoutStartProcessing=
0);c._timeoutStartProcessing=setTimeout(function(){c._timeoutStartProcessing=0;var a=c._getPrimaryLoginForm();if(h(a))c._removeFieldStylingElement(),e.popup.close();else{c._doFieldStyling(a);m.sendMessage({id:n.IS_URL_EXCLUDED_FROM_ADDING_MUTATION_OBSERVER},function(k){k?b.debug("Not adding mutation observer "):c._addMutationObserver(a)});c._processFlows(a,!1);var t=0,g=setInterval(function(){c._reShowPopupAndDoFieldStyling()&&5>t?t++:clearInterval(g)},800)}},1)};c._getPrimaryLoginForm=function(){if(v(c._primaryWaxForm))return c._primaryWaxForm;
var a=c._waxForms;if(!w(a)||0===a.length)return c._primaryWaxForm;for(var b=a.length-1;0<=b;b--){var e=a[b];if(e.isFormComplete())return c._primaryWaxForm=e,c._primaryWaxForm}c._primaryWaxForm=a[0];return c._primaryWaxForm};c._setInputElement=function(a){c._inputElement=a};c._checkIfVaultIsLocked=function(a){if(!D(a))throw Error("Callback cannot be null or is not a function");m.sendMessage({id:n.VAULT_ISLOGGEDIN},function(b){a(b)})};c._canShowSigninPopup=function(a){if(!D(a))throw Error("Callback cannot be null or is not a function");
m.sendMessage({id:n.CAN_SHOW_SIGNIN_POPUP},function(c){h(c)?b.warn("Received null response to show popup"):h(c.canShow)?b.error("unexpected response"):a(c.canShow)})};c._onLoginFormSubmission=function(a,b){var e;return $jscomp.asyncExecutePromiseGeneratorProgram(function(k){e={};e.url=document.URL;e.formType=a;e.loginInfo=b;y.isTopLevelWindow()?c.loginFormSubmission(a,b):m.sendMessage({id:n.GET_SANDBOX_INFORMATION,payload:e});k.jumpToEnd()})};c.loginFormSubmission=function(a,c){var e,k;return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==
a.nextAddress){b.debug("IDSafeWAX: onLoginFormSubmission");e={};e.loginInfo=c;if(C(document.URL)!==q.FG_ISOLATION_URL_DOMAIN)return e.senderURL=document.URL,a.jumpTo(2);k=e;return a.yield(fgHelperSDK.checkLoadedURL(),3)}2!=a.nextAddress&&(k.senderURL=a.yieldResult,e.isIsolationURL=!0);m.sendMessage({id:n.VAULT_PROCESS_LOGIN_FORM_SUBMISSION,payload:e});a.jumpToEnd()})};c._fillForm=function(a,b){if(!h(a)){var k=c._getURLProtocol();b.ignoreHttp&&k!==q.HTTPS_PROTOCOL?e.telemetryWrapper.sendWaxFillHttpsNotFoundFailure(window.location.hostname):
c._fillUnlockedForm(a,b)}};c._fillUnlockedForm=function(a,b){var k=c._primaryWaxForm;h(k)||h(a)||e.formHandler.fillForm(k.formID,a,b)};c.getVaultItemById=function(a,b,c,e,d){m.sendMessage({id:a,payload:{id:b}},function(a){d.ignoreHttp=e;c(a,d)})};c.showSigninPopup=function(a){0>=a.left&&(a.left=1);e.popup.show(p.TYPE.SIGNIN,void 0,void 0,a,void 0)};c.showFillPopup=function(a,b,g,d){0>=g.left&&(g.left=1);e.popup.show(p.TYPE.FILL,a,b,g,function(a){if(a.id===e.uiConstants.POPUP.MESSAGES.POPUP_LOGIN_ITEM_SELECTED||
a.id===e.uiConstants.POPUP.MESSAGES.POPUP_CARD_ITEM_SELECTED){e.popup.close();var k=C(J(window.location.href));k===q.FG_ISOLATION_URL_DOMAIN&&e.eventUITelemetryWrapper.send(e.eventUITelemetryWrapper.constants.action.CLICK,e.eventUITelemetryWrapper.constants.elementId.ISOLATION_MODE_LOGIN_FILL,p.HTML);m.sendMessage({id:x.ITEM_SELECTED_INPAGE_POPUP_ON_TOP_FRAME,payload:{itemRetrievalID:a.payload.itemRetrievalID,itemID:a.payload.itemID,formType:b,msgSenderIndentifier:d,siteUrl:u(k)?k:""}})}else a.id===
e.uiConstants.POPUP.MESSAGES.POPUP_GENERATE_PASSWORD_CLICKED&&(m.sendMessage({id:e.uiConstants.PASSWORD_GENERATOR.MESSAGES.GENERATE_PASSWORD,payload:{length:12,includeLetters:!0,includeNumbers:!0,includeMixedCase:!0,includeSymbols:!0}},function(b){c._fillForm({result:b,itemId:a.payload.itemID},!0)}),e.popup.close())})};c._addChromeToolbarMutationObserver=function(a){if(!h(a)){var b=null,e=new MutationObserver(function(a){v(b)&&(clearTimeout(b),b=null);b=setTimeout(function(){if(c._isToolbarFound)e.disconnect();
else{var a=document.querySelectorAll(q.NCO_CHROMETOOLBAR)[0];v(a)&&(c._isToolbarFound=!0,c._reShowPopupAndDoFieldStyling())}},250)});e.observe(a,{attributes:!0,childList:!0,subtree:!0})}};c._canShowPopupInWindow=function(){return y.isTopLevelWindow()?!0:!1};c._processMenuItems=function(a){if(c._canShowPopupInWindow()){var b=e.popup.currentPopupType;if(!b||!a.centerPosition&&b)switch(a.popupType){case p.TYPE.SIGNIN:c[a.processFunction](a.loc);return;case p.TYPE.FILL:v(a.srcAttribute)&&(a.itemsPayload.srcAttribute=
a.srcAttribute);c[a.processFunction](a.itemsPayload,a.formType,a.loc,a.msgSenderIndentifier,a.clicked);return}else return}setTimeout(function(){m.sendMessage({id:x.SHOW_INPAGE_POPUP_ON_TOP_FRAME,payload:a})},5)};c._processFlows=function(a,b){var k,d,t;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){if(1==g.nextAddress){k=document.URL;d={popupType:p.TYPE.SIGNIN,formType:null,frameName:document.defaultView.name,loc:null,clicked:b,itemsPayload:{showDontAsk:!1},processFunction:""};if(C(k)!==
q.FG_ISOLATION_URL_DOMAIN)return d.srcAttribute=document.location.href,g.jumpTo(2);t=d;return g.yield(fgHelperSDK.checkLoadedURL(),3)}2!=g.nextAddress&&(t.srcAttribute=g.yieldResult);d.msgSenderIndentifier=c._msgSenderIndentifier=I();c._checkIfVaultIsLocked(function(k){var g=a.getInputElementForPopup();if(!h(g)){c._setInputElement(g);g=g.getElement();d.loc=e.popup.getLocation(g,e.uiConstants.POPUP.WIDTH);if(h(k)||k){d.processFunction="showSigninPopup";if(b){d.itemsPayload.showDontAsk=!1;c._processMenuItems(d);
return}if(f.utils.isWaxChangePasswordForm(a))return;c._canShowSigninPopup(function(a){a&&(d.itemsPayload.showDontAsk=!0,c._processMenuItems(d))})}else{g=c._primaryWaxForm;k=b?{ignoreHttp:!1}:{ignoreHttp:!0};if(h(g))return;g=g.getInputElementForPopup();if(h(g))return;g=g.getElement();d.loc=e.popup.getLocation(g,e.uiConstants.POPUP.WIDTH);d.popupType=p.TYPE.FILL;d.formType=a.formType;d.itemsPayload=k;f.utils.isWaxLoginForm(a)?d.processFunction="_processLoginMenuItems":f.utils.isWaxCardForm(a)?d.processFunction=
"_processCardMenuItems":f.utils.isWaxChangePasswordForm(a)&&(d.processFunction="_processChangePasswordForm");c._processMenuItems(d)}c._addChromeToolbarMutationObserver(document.documentElement)}});g.jumpToEnd()})};c._processLoginMenuItems=function(a,b,e,d,f){m.sendMessage({id:n.VAULT_GET_LOGINS_BY_URL,payload:a},function(a){if(!h(a)&&0<a.length){var g=!1;v(a[0].partiallyFilled)&&(g=a[0].partiallyFilled);(1<a.length&&!0!==g||f)&&c.showFillPopup(a,b,e,d);if(!f){var k=a[0];F.getAllIDSSettings(function(g){var t=
g[q.settings.AUTO_FILL];g=g[q.settings.REQUIRE_VAULT_PASSWORD];!h(k.autofill)&&!k.autofill||!h(t)&&!t||k.secure||g?0<a.length&&c.showFillPopup(a,b,e,d):c.getVaultItemById(n.VAULT_GET_LOGIN_BY_ID,k.id,c._fillForm,!0)})}B.sendLoginFillPopupPageViewTelemetry(p.HTML,a.length,f)}})};c._processCardMenuItems=function(a,b,g,d,f){m.sendMessage({id:n.VAULT_GET_CARD_ITEMS,payload:a},function(a){h(a)||0===a.length||(c.showFillPopup(a,b,g,d),B.sendCardFieldFillPopupPageViewTelemetry(p.HTML,a.length,f),!0===f&&
e.eventUITelemetryWrapper.sendCardFieldDecoratorEventTelemetry(e.eventUITelemetryWrapper.constants.action.CLICK,e.eventUITelemetryWrapper.constants.elementId.CARD_FIELD_BADGE,p.HTML))})};c._processChangePasswordForm=function(a,b,g,d,f){m.sendMessage({id:n.VAULT_GET_LOGINS_BY_URL,payload:a},function(a){h(a)||0===a.length||(c.showFillPopup(a,b,g,d),B.sendChangePasswordFieldFillPopupPageViewTelemetry(p.HTML,a.length,f),!0===f&&e.eventUITelemetryWrapper.sendChangePasswordFieldDecoratorEventTelemetry(e.eventUITelemetryWrapper.constants.action.CLICK,
e.eventUITelemetryWrapper.constants.elementId.CHANGE_PASSWORD_FIELD_BADGE,p.HTML))})};c._getFieldStylingPosition=function(a,b){a=a.getBoundingClientRect();var c=a.height*r.DIV_HEIGHT_RATIO/r.DIV_HEIGHT_REC;return{left:b?a.left+a.width*r.DIV_LEFT_RTL/r.DIV_WIDTH_REC:a.left+a.width*r.DIV_LEFT_LTR/r.DIV_WIDTH_REC-c,top:a.top+(a.height-c)/2+window.scrollY,height:c,width:c}};c._removeFieldStylingElement=function(){for(;;){var a=document.getElementById(r.DIV_ID);if(h(a))break;a.parentNode.removeChild(a)}};
c._doFieldStyling=function(a){h(a)||(c._checkIfVaultIsLocked(function(b){b&&c._doFieldStylingForForm(a)}),f.utils.isWaxChangePasswordForm(a)?m.sendMessage({id:n.VAULT_GET_LOGINS_BY_URL,payload:{ignoreHttp:!1}},function(b){h(b)||1<=b.length&&c._doFieldStylingForForm(a)}):c._doFieldStylingForForm(a))};c._doFieldStylingForForm=function(a){b.debug("IDSafeWAX: removeFieldStylingElement");c._removeFieldStylingElement();a.getFieldsForStyling().forEach(function(b){if(!h(b)){var d=b.getElement();h(d)||b._fieldType===
G.loginType.PASSWORD&&d.offsetWidth<e.uiConstants.BADGE.MAX_OFFSET_WIDTH||(b=A.isPageRTL(d),H.createFieldStylingElement(d,b,r,function(){c._processFlows(a,!0)}))}})};c._reShowPopupAndDoFieldStyling=function(){c._doFieldStyling(c._primaryWaxForm);if(h(c._inputElement))return!1;v(e.popup.currentPopupType)&&e.popup.updateSizeAndLocation(c._inputElement._element);return!0};var z=0;window.addEventListener("resize",function(a){b.debug("IDSWAX: window resize event");0!==z&&clearTimeout(z);z=setTimeout(function(){c._reShowPopupAndDoFieldStyling();
z=0},100)});document.addEventListener("click",function(){window.top.postMessage({id:x.POPUP_EVENT_CLOSE},"*")});document.addEventListener("keydown",function(){window.top.postMessage({id:x.POPUP_EVENT_CLOSE},"*")});c._addMutationObserver=function(a){m.sendMessage({id:n.IS_URL_EXCLUDED_FROM_CAPTURE},function(d){if(d)b.debug("Not adding mutation observer as we don't want to capture logins");else if(f.utils.isWaxLoginForm(a)||f.utils.isWaxCardForm(a)){v(c._observer)&&(c._observer.disconnect(),c._observer=
null);var g=a.getFieldsVisibility(),k=0;c._observer=new MutationObserver(function(c){b.debug("IDSafeWAX: mutations observed");c.forEach(function(a){b.debug(a)});0!==k&&clearTimeout(k);k=setTimeout(function(){var c=a.getFieldsVisibility();b.debug(c);JSON.stringify(g)!==JSON.stringify(c)&&(b.debug("reanalyzing the form due to mutation"),e.formHandler.reAnalyzePage());g=c;k=0},500)});a.setMutationObserver(c._observer,{attributes:!0,childList:!0,subtree:!0})}})};c._onLoginFormFound=function(a,e,d){if(!u(a)||
!u(e)||h(d))throw Error("IDSafeWAX: onLoginFormFound: Invalid Aruguments");b.debug("IDSafeWAX: onLoginFormFound");d.formType=a;d.formID=e;c._primaryWaxForm=null;c._setLoginForm(d)};c._handleMessage=function(a,b,d){b=a.payload;d=c._primaryWaxForm;switch(a.id){case n.VAULT_LOGGEDIN:e.popup.close();if(h(d))break;c._startProcessWaxForms();break;case E.LOGIN_UNLOCKED:c.getVaultItemById(n.VAULT_GET_LOGIN_BY_ID,b.loginId,function(a){h(a)||c._fillUnlockedForm(a)});break;case x.SHOW_INPAGE_POPUP_ON_TOP_FRAME_BG:d=
document.querySelectorAll("iframe[src='"+b.srcAttribute+"']");d=0==d.length?c._findFramesInDocument(b):d;if(0<d.length){if(d[0].hasAttribute(q.SANDBOX)){var g=d[0].sandbox.value.split(" ");if(!q.ALLOWED_SANDBOX_VALUES.every(function(a){return g.includes(a)}))break}a=d[0].getBoundingClientRect();d=b.loc;d.top=a.top+d.top+window.scrollY;d.left=a.left+d.left+window.scrollX;b.loc=d;c._processMenuItems(b)}else 0==d.length&&y.isTopLevelWindow()&&(d=b.loc,d.top=window.innerHeight/2-e.uiConstants.POPUP.HEIGHT/
2,d.left=window.innerWidth/2-e.uiConstants.POPUP.WIDTH/2,b.loc=d,b.centerPosition=!0,c._processMenuItems(b));break;case x.ITEM_SELECTED_INPAGE_POPUP_ON_TOP_FRAME_BG:c._msgSenderIndentifier==b.msgSenderIndentifier&&c.getVaultItemById(b.itemRetrievalID,b.itemID,c._fillForm,!1,{siteDomain:b.siteUrl});break;case n.GET_SANDBOX_INFORMATION_CS:d=document.querySelectorAll("iframe[src='"+b.url+"']");if(0<d.length){a={};d=$jscomp.makeIterator(d);for(var f=d.next();!f.done;a={$jscomp$loop$prop$sandboxValueArray$3$5:a.$jscomp$loop$prop$sandboxValueArray$3$5},
f=d.next())if(f=f.value,f.hasAttribute(q.SANDBOX)&&(a.$jscomp$loop$prop$sandboxValueArray$3$5=f.sandbox.value.split(" "),!q.ALLOWED_SANDBOX_VALUES.every(function(a){return function(b){return a.$jscomp$loop$prop$sandboxValueArray$3$5.includes(b)}}(a))))return}c.loginFormSubmission(b.formType,b.loginInfo)}};c._findFramesInDocument=function(b){var c=[],d=y.isTopLevelWindow(),f=a.globals.BROWSER===e.uiConstants.BROWSER_TYPE.SAFARI||a.globals.BROWSER===e.uiConstants.BROWSER_TYPE.EDGE?!0:!1;d=f&&!d?!0:
!1;var k="iframe"===y.getActiveElement().tagName.toLowerCase()?y.getActiveElement():null,h=document.querySelectorAll("iframe"),m;for(m in h)if(h.hasOwnProperty(m)){var l=h[m];if(""!=b.frameName.trim()&&b.frameName.trim()==l.name.trim()&&!d){c.push(l);break}else if(-1!==b.srcAttribute.indexOf(l.src.split(/[?#]/)[0])&&0!=l.src.length&&!d){c.push(l);break}else if(k==l&&!f){c.push(l);break}}return c};c._onLoginFormRemoved=function(a){if(w(a)&&0!==a.length){var b=[];c._waxForms.forEach(function(c){-1===
a.indexOf(c.formID)&&b.push(c)});c._waxForms=b;c._primaryWaxForm=null;c._removeFieldStylingElement();e.popup.close();c._startProcessWaxForms()}};c._init=function(a){b.debug("IDSafeWAX: starting...");a||(e.formHandler.waxInit(c._onLoginFormFound,c._onLoginFormSubmission,c._onLoginFormRemoved),m.addContentScriptMessageListener(c._handleMessage))};c._checkAndInitializeWax=function(){m.sendMessage({id:K.AUTO_CHANGE_RUNNING},c._init)};c._checkAndInitializeWax();return c}(a.SymBfw,a.SymO2,a.SymWax,a.IDSafe)})(executionContext);
