var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(f){var e=0;return function(){return e<f.length?{done:!1,value:f[e++]}:{done:!0}}};$jscomp.arrayIterator=function(f){return{next:$jscomp.arrayIteratorImpl(f)}};$jscomp.makeIterator=function(f){var e="undefined"!=typeof Symbol&&Symbol.iterator&&f[Symbol.iterator];return e?e.call(f):$jscomp.arrayIterator(f)};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(f,e,d){f!=Array.prototype&&f!=Object.prototype&&(f[e]=d.value)};$jscomp.getGlobal=function(f){return"undefined"!=typeof window&&window===f?f:"undefined"!=typeof global&&null!=global?global:f};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(f,e){this.$jscomp$symbol$id_=f;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:e})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function f(d){if(this instanceof f)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(d||"")+"_"+e++,d)}var e=0;return f}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var f=$jscomp.global.Symbol.iterator;f||(f=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[f]&&$jscomp.defineProperty(Array.prototype,f,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var f=$jscomp.global.Symbol.asyncIterator;f||(f=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(f){$jscomp.initSymbolIterator();f={next:f};f[$jscomp.global.Symbol.iterator]=function(){return this};return f};
$jscomp.iteratorFromArray=function(f,e){$jscomp.initSymbolIterator();f instanceof String&&(f+="");var d=0,a={next:function(){if(d<f.length){var b=d++;return{value:e(b,f[b]),done:!1}}a.next=function(){return{done:!0,value:void 0}};return a.next()}};a[Symbol.iterator]=function(){return a};return a};
$jscomp.polyfill=function(f,e,d,a){if(e){d=$jscomp.global;f=f.split(".");for(a=0;a<f.length-1;a++){var b=f[a];b in d||(d[b]={});d=d[b]}f=f[f.length-1];a=d[f];e=e(a);e!=a&&null!=e&&$jscomp.defineProperty(d,f,{configurable:!0,writable:!0,value:e})}};$jscomp.polyfill("Array.prototype.keys",function(f){return f?f:function(){return $jscomp.iteratorFromArray(this,function(e){return e})}},"es6","es3");$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(f){function e(){this.batch_=null}function d(c){return c instanceof b?c:new b(function(b,h){b(c)})}if(f&&!$jscomp.FORCE_POLYFILL_PROMISE)return f;e.prototype.asyncExecute=function(c){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(c)};var a=$jscomp.global.setTimeout;e.prototype.asyncExecuteFunction=function(c){a(c,0)};e.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var c=
this.batch_;this.batch_=[];for(var b=0;b<c.length;++b){var a=c[b];c[b]=null;try{a()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};e.prototype.asyncThrow_=function(c){this.asyncExecuteFunction(function(){throw c;})};var b=function(c){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{c(b.resolve,b.reject)}catch(g){b.reject(g)}};b.prototype.createResolveAndReject_=function(){function c(c){return function(h){a||(a=!0,c.call(b,h))}}var b=this,a=!1;
return{resolve:c(this.resolveTo_),reject:c(this.reject_)}};b.prototype.resolveTo_=function(c){if(c===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(c instanceof b)this.settleSameAsPromise_(c);else{a:switch(typeof c){case "object":var h=null!=c;break a;case "function":h=!0;break a;default:h=!1}h?this.resolveToNonPromiseObj_(c):this.fulfill_(c)}};b.prototype.resolveToNonPromiseObj_=function(c){var b=void 0;try{b=c.then}catch(g){this.reject_(g);return}"function"==typeof b?
this.settleSameAsThenable_(b,c):this.fulfill_(c)};b.prototype.reject_=function(c){this.settle_(2,c)};b.prototype.fulfill_=function(c){this.settle_(1,c)};b.prototype.settle_=function(c,b){if(0!=this.state_)throw Error("Cannot settle("+c+", "+b+"): Promise already settled in state"+this.state_);this.state_=c;this.result_=b;this.executeOnSettledCallbacks_()};b.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var b=0;b<this.onSettledCallbacks_.length;++b)c.asyncExecute(this.onSettledCallbacks_[b]);
this.onSettledCallbacks_=null}};var c=new e;b.prototype.settleSameAsPromise_=function(c){var b=this.createResolveAndReject_();c.callWhenSettled_(b.resolve,b.reject)};b.prototype.settleSameAsThenable_=function(c,b){var a=this.createResolveAndReject_();try{c.call(b,a.resolve,a.reject)}catch(l){a.reject(l)}};b.prototype.then=function(c,a){function h(c,b){return"function"==typeof c?function(b){try{d(c(b))}catch(r){e(r)}}:b}var d,e,k=new b(function(c,b){d=c;e=b});this.callWhenSettled_(h(c,d),h(a,e));return k};
b.prototype.catch=function(c){return this.then(void 0,c)};b.prototype.callWhenSettled_=function(b,a){function h(){switch(d.state_){case 1:b(d.result_);break;case 2:a(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?c.asyncExecute(h):this.onSettledCallbacks_.push(h)};b.resolve=d;b.reject=function(c){return new b(function(b,a){a(c)})};b.race=function(c){return new b(function(b,a){for(var h=$jscomp.makeIterator(c),e=h.next();!e.done;e=h.next())d(e.value).callWhenSettled_(b,
a)})};b.all=function(c){var a=$jscomp.makeIterator(c),h=a.next();return h.done?d([]):new b(function(c,b){function e(b){return function(a){m[b]=a;k--;0==k&&c(m)}}var m=[],k=0;do m.push(void 0),k++,d(h.value).callWhenSettled_(e(m.length-1),b),h=a.next();while(!h.done)})};return b},"es6","es3");$jscomp.polyfill("Object.is",function(f){return f?f:function(e,d){return e===d?0!==e||1/e===1/d:e!==e&&d!==d}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(f){return f?f:function(e,d){var a=this;a instanceof String&&(a=String(a));var b=a.length;d=d||0;for(0>d&&(d=Math.max(d+b,0));d<b;d++){var c=a[d];if(c===e||Object.is(c,e))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(f,e,d){if(null==f)throw new TypeError("The 'this' value for String.prototype."+d+" must not be null or undefined");if(e instanceof RegExp)throw new TypeError("First argument to String.prototype."+d+" must not be a regular expression");return f+""};$jscomp.polyfill("String.prototype.includes",function(f){return f?f:function(e,d){return-1!==$jscomp.checkStringArgs(this,e,"includes").indexOf(e,d||0)}},"es6","es3");
(function(f){(f.SymBfw=f.SymBfw||{}).globals={BROWSER:"Chrome",PRODUCT_GUID:"DC6B1B05-C7B2-43EB-81E3-CBD3896553C2"}})(window);(function(f){(f.SymBfw=f.SymBfw||{}).logger=function(e){return{debug:function(d){},log:function(d){},error:function(d){console.error(d);var a=e.telemetryWrapper;a.send(a.componentType.LOGGER,a.actionType.ERROR,d)},warn:function(d){console.warn(d);var a=e.telemetryWrapper;a.send(a.componentType.LOGGER,a.actionType.WARN,d)},info:function(d){console.info(d)}}}(f.SymBfw)})(window);
(function(f){f=f.SymBfw;var e={httpStatusCodes:{},localizer:{DEFAULT_MESSAGES_DICTIONARY:"strings",GET_LOCALIZED_STRING:"44F4D54E-AB86-454C-A494-DE3AD87E72F9",GET_LOCALIZED_STRINGS:"0D1C5EEF-749F-4EEB-AD6D-F9C26018EE91",GET_ALL_LOCALIZED_STRINGS:"33445b60-9a88-4d99-829f-564704b2a960",GET_LOCALIZED_STRING_FROM_DICTIONARY:"D15C0B4C-DC1B-403F-A3C8-8BB42137B325",GET_LOCALIZED_STRINGS_FROM_DICTIONARY:"88313974-C371-4A8D-9196-0A2CE43C8327",GET_LOCALIZED_STRING_WITH_FORMAT:"F3D7C8CE-B1A9-425A-AD24-4120C592AF86",
GET_LOCALIZED_STRING_WITH_FORMAT_FROM_DICTIONARY:"9066F4CC-31A4-45F5-A07A-81DDC38E5F99",GET_CURRENT_LANGUAGE_DIRECTION:"C30B2719-DD82-41EC-E93A-8A602444F90A",GET_LOCALIZED_STRINGS_WITH_FORMAT:"E225C9A6-209A-4702-8E48-3B6EFBF67E26"},clipboard:{messages:{CLEAR_CLIPBOARD:"aa232db5-1dba-473a-ab4b-e9c378b7978b"},DEFAULT_TIMEOUT:6E4}};e.httpStatusCodes.OK=200;e.httpStatusCodes.PARTIAL_CONTENT=206;e.httpStatusCodes.CREATED=201;e.httpStatusCodes.NO_CONTENT=204;e.httpStatusCodes.INCORRECT_URI=302;e.httpStatusCodes.NOT_MODIFIED=
304;e.httpStatusCodes.BAD_REQUEST=400;e.httpStatusCodes.UNAUTHORIZED=401;e.httpStatusCodes.INVALID_SCHEMA=403;e.httpStatusCodes.NOT_FOUND=404;e.httpStatusCodes.HEADER_ERROR=406;e.httpStatusCodes.GONE=410;e.httpStatusCodes.ENTITY_TOO_LARGE=413;e.httpStatusCodes.DATASTORE_RATE_LIMITED=429;e.httpStatusCodes.RATE_LIMITING=503;e.httpStatusCodes.SERVER_ERROR=500;e.DEFAULT_FETCH_TIMEOUT=6E4;e.CERT_COMMON_NAME="CN";e.telemetry={TELEMETRY_ENABLED:"293E0764-AF48-4C52-B675-0161A7B6BECE",TELEMETRY_OPT_OUT_SHOWN:"FE795012-44D6-491D-A8A1-E83633892C9D",
BFW_TELEMETRY_SETTINGS_CONTAINER:"233D07C0-6318-4BCE-A36A-82DFB19F3B2A",USER_RESPONDED_IN_OPT_OUT_PAGE:"8157BC1F-5ED8-4373-A18D-8CD8E0263752",LAST_OFFER_DATE:"9EA53F0C-7F18-44A5-8138-C11F27D66FC1"};e.os={WINDOWS:"Windows",MAC:"Mac",UNKNOWN:"Unknown"};e.CDN_FILE_DOWNLOADER={ENCRYPTION_METHOD:"RS256",SUPPORTED_PROTOCOL:"https",SUPPORTED_FILEFORMATS:["json"],RESPONSE_STATUS:{UNSUCCESSFUL_RESPONSE:"Error in fetching the file with status code",FILE_TAMPERED:"CDN file has been tampered",PUBLIC_KEY_NOT_VERIFIED:"Public key verification has failed",
INVALID_PARAMETERS:"Invalid paramaters"},CERT_ISSUER_NAME:"CERT_ISSUER_NAME",CERT_ISSUED:"CERT_ISSUED"};e.uiConstants={NOTIFICATION:{IFRAME_ID:"symc-notification-popup",HTML:"content/ui/notification.html",STYLE:"content/ui/content-page.css",STACK_COUNT:1,DEFAULT_TIMEOUT:1E4,HEIGHT:200,WIDTH:460,TYPE:{QUESTION:0,TIMED:1},BUTTON:{DEFAULT:0,SECONDARY:1},MESSAGES:{DEFAULT_MESSAGE:"8DB8FE17-6F5E-485E-81EE-1112762F48E4",DEFAULT_BUTTON_PRESSED:"209CBB4D-6D6B-46F4-9EA7-303181937BF6",SECONDARY_LINK_PRESSED:"8881560D-E8A2-41FA-A81D-A90D41311D0D",
THIRD_BUTTON_PRESSED:"196F06EB-956E-44EE-A60D-F4741C5CF4D3",NOTIFICATION_CLOSED:"EA7414A5-667F-4459-BAC2-38464F3330A3",NOTIFICATION_QUEUE_MESSAGE:"A88CCFCD-B98D-4607-B780-79A1CF7ADFAD",NOTIFICATIONS_SHOWN:"57C094C2-F0F0-44C2-9BBF-9E147135FB50",UI_INIT:"EE5B61D6-3A55-4ABB-B304-02BDAD9698FE",UI_INIT_PROXY:"0FABE0DB-1C87-475B-D89E-F4EC0EE963DE",HIDE_NOTIFICATIONS:"8211780F-93EC-4E37-8933-E60CB6052E84"}},CONTENT_PAGE_STYLE_ID:"symc-content-stylesheet"};e.performanceReporter={MESSAGES:{REPORT_START:"2379B4CB-E725-4818-8FCC-A9372EABBF45",
REPORT_END:"1F62DD4E-56AD-4528-9A69-BFE9EC135B9F",GET_PERFORMANCE_REPORTER:"2306DE62-ACA8-40AE-9909-517474C1120B"}};e.utils={IP:"ip"};e.NAVIGATION_COMPLETE="complete";e.STORE_URLS={Chrome:"https://chrome.google.com/webstore/",Firefox:"https://addons.mozilla.org/",Safari:"https://safari-extensions.apple.com/",Edge:"https://www.microsoft.com/[a-zA-Z]+[-]?[a-zA-Z]*/(p|store)/"};e.BROWSER_TYPE={CHROME:"Chrome",FIREFOX:"Firefox",EDGE:"Edge",SAFARI:"Safari"};e.RANDOM_NUMBER_LIMITS={MIN:0,MAX:4294967295};
f.constants=e})(window);
(function(f){f.SymBfw.utils=function(e){var d={},a=e.constants;d.createNewGuid=function(){var c=(new Date).getTime();return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(b){var a=(c+16*Math.random())%16|0;c=Math.floor(c/16);return("x"==b?a:a&7|8).toString(16)})};d.stringUTF16LEToByteArray=function(c){if(!1===this.isString(c))throw Error("Input string cannot be null or is not a string");for(var b=[],a=0;a<c.length;++a){var d=c.charCodeAt(a),e=(d&65280)>>8;b.push(d&255);b.push(e)}return b};
d.arrayBufferToStringUTF16LE=function(c){if(this.isNil(c))return null;c instanceof ArrayBuffer&&(c=new Uint8Array(c));for(var b=[],a=0;a<c.byteLength;a++)b.push(c[a]);return this.byteArrayToStringUTF16LE(b)};d.byteArrayToStringUTF16LE=function(c){if(!1===this.isArray(c))throw Error("Byte array cannot be null or is not an array");if(2>c.length)throw Error("Byte array needs to contain at least two bytes");if(0!==c.length%2)throw Error("Byte array needs to contain even number of bytes");for(var b="",
a=0;a<c.length-1;a+=2){var d=c[a];if(255<d)throw Error("Encoding error: Input contains element larger than a byte.");d&=255;var e=c[a+1];if(255<e)throw Error("Encoding error: Input contains element larger than a byte.");e=e<<8&65280;b+=String.fromCharCode(d+e)}return b};d.downloadFileFromUrl=function(c){var b=document.createElement("iframe");b.style.display="none";b.src=c;b.width="1";b.height="1";b.frameborder="0";document.body.appendChild(b);setTimeout(function(){document.body.removeChild(b)},5E3)};
d.obfuscatePassword=function(c,b){if(!1===this.isString(c))throw Error("password  cannot be null and has to be a string");if(!1===this.isString(b))throw Error("obfuscationKey  cannot be null and has to be a string");c=new Uint8Array(e.utils.stringUTF16LEToByteArray(c));b=new Uint8Array(e.utils.stringUTF16LEToByteArray(b));b=e.utils._obfuscateData(c,b);return b=e.utils.arrayBufferToStringUTF16LE(b)};d._obfuscateData=function(c,b){if(d.isNil(c)||d.isNil(b))return null;c instanceof ArrayBuffer&&(c=new Uint8Array(c));
b instanceof ArrayBuffer&&(b=new Uint8Array(b));for(var a=c.byteLength,e=new Uint8Array(a),h=0;h<a;h++)e[h]=c[h]^b[h%a];return e};d.getOSType=function(){var c=a.os.UNKNOWN;-1!=navigator.appVersion.toLowerCase().indexOf("win")?c=a.os.WINDOWS:-1!=navigator.appVersion.toLowerCase().indexOf("mac")&&(c=a.os.MAC);return c};d.isNil=function(c){return"undefined"===typeof c||null===c?!0:!1};d.isntNil=function(c){return"undefined"!==typeof c&&null!==c?!0:!1};d.isEmptyObject=function(c){return d.isNil(c)||0===
Object.keys(c).length?!0:!1};d.objectHas=function(c,b){return d.isObject(c)&&d.isString(b)?Object.prototype.hasOwnProperty.call(c,b):!1};d.isString=function(c){return d.isntNil(c)&&"string"===typeof c?!0:!1};d.isFunction=function(c){return d.isntNil(c)&&"function"===typeof c?!0:!1};d.isArray=function(c){return Array.isArray(c)};d.isObject=function(c){return d.isntNil(c)&&"object"===typeof c&&c.constructor===Object?!0:!1};d.isBoolean=function(c){return d.isntNil(c)&&"boolean"===typeof c?!0:!1};var b=
{ac:{com:!0,gov:!0,mil:!0,net:!0,org:!0,edu:!0},ad:{nom:!0},ae:{ac:!0,co:!0,gov:!0,mil:!0,name:!0,net:!0,org:!0,pro:!0,sch:!0},af:{com:!0,edu:!0,gov:!0,net:!0,org:!0},ai:{off:!0,com:!0,net:!0,org:!0},al:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0,uniti:!0,tirana:!0,soros:!0,upt:!0,inima:!0},an:{com:!0,net:!0,org:!0,edu:!0},ag:{com:!0,org:!0,net:!0,co:!0,nom:!0},ao:{co:!0,ed:!0,gv:!0,it:!0,og:!0,pb:!0},ar:{com:!0,edu:!0,gob:!0,gov:!0,"int":!0,mil:!0,net:!0,org:!0,tur:!0},arpa:{e164:!0,"in-addr":!0,
iris:!0,ip6:!0,uri:!0,urn:!0},at:{ac:!0,co:!0,gv:!0,or:!0,priv:!0},au:{asn:!0,com:!0,net:!0,id:!0,org:!0,csiro:!0,oz:!0,info:!0,conf:!0,act:!0,nsw:!0,nt:!0,qld:!0,sa:!0,tas:!0,vic:!0,wa:!0},aw:{com:!0},az:{com:!0,net:!0,"int":!0,gov:!0,biz:!0,org:!0,edu:!0,mil:!0,pp:!0,name:!0,info:!0},ba:{co:!0,com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0,rs:!0,unbi:!0,unmo:!0,unsa:!0,untz:!0,unze:!0},bb:{biz:!0,co:!0,com:!0,edu:!0,gov:!0,info:!0,net:!0,org:!0,store:!0,tv:!0},bd:{com:!0,edu:!0,net:!0,gov:!0,org:!0,
mil:!0},be:{ac:!0},bf:{gov:!0},bh:{biz:!0,cc:!0,com:!0,edu:!0,gov:!0,info:!0,net:!0,org:!0},bm:{com:!0,edu:!0,org:!0,gov:!0,net:!0},bn:{com:!0,edu:!0,gov:!0,net:!0,org:!0},bo:{com:!0,edu:!0,gob:!0,gov:!0,"int":!0,mil:!0,net:!0,org:!0,tv:!0},br:{adm:!0,adv:!0,agr:!0,am:!0,arq:!0,art:!0,ato:!0,b:!0,bio:!0,blog:!0,bmd:!0,cim:!0,cng:!0,cnt:!0,com:!0,coop:!0,ecn:!0,edu:!0,eng:!0,esp:!0,etc:!0,eti:!0,far:!0,flog:!0,fm:!0,fnd:!0,fot:!0,fst:!0,g12:!0,ggf:!0,gov:!0,imb:!0,ind:!0,inf:!0,jor:!0,jus:!0,lel:!0,
mat:!0,med:!0,mil:!0,mus:!0,net:!0,nom:!0,not:!0,ntr:!0,odo:!0,org:!0,ppg:!0,pro:!0,psc:!0,psi:!0,qsl:!0,rec:!0,slg:!0,srv:!0,tmp:!0,trd:!0,tur:!0,tv:!0,vet:!0,vlog:!0,wiki:!0,zlg:!0},bs:{com:!0,edu:!0,gov:!0,net:!0,org:!0},bt:{com:!0,edu:!0,gov:!0,net:!0,org:!0},bw:{co:!0,org:!0},by:{gov:!0,mil:!0},bz:{du:!0,et:!0,om:!0,ov:!0,rg:!0},ca:{ab:!0,bc:!0,mb:!0,nb:!0,nf:!0,nl:!0,ns:!0,nt:!0,nu:!0,on:!0,pe:!0,qc:!0,sk:!0,yk:!0},cc:{co:!0},ck:{biz:!0,co:!0,edu:!0,gen:!0,gov:!0,info:!0,net:!0,org:!0},cn:{ac:!0,
ah:!0,bj:!0,com:!0,cq:!0,edu:!0,fj:!0,gd:!0,gov:!0,gs:!0,gx:!0,gz:!0,ha:!0,hb:!0,he:!0,hi:!0,hl:!0,hn:!0,jl:!0,js:!0,jx:!0,ln:!0,mil:!0,net:!0,nm:!0,nx:!0,org:!0,qh:!0,sc:!0,sd:!0,sh:!0,sn:!0,sx:!0,tj:!0,tw:!0,xj:!0,xz:!0,yn:!0,zj:!0},co:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,nom:!0,org:!0},cr:{ac:!0,c:!0,co:!0,ed:!0,fi:!0,go:!0,or:!0,sa:!0},cx:{gov:!0},cy:{ac:!0,biz:!0,com:!0,ekloges:!0,gov:!0,ltd:!0,name:!0,net:!0,org:!0,parliament:!0,press:!0,pro:!0,tm:!0},cu:{com:!0,edu:!0,org:!0,net:!0,gov:!0,inf:!0},
dm:{com:!0,net:!0,org:!0,edu:!0,gov:!0},"do":{art:!0,com:!0,edu:!0,gob:!0,gov:!0,mil:!0,net:!0,org:!0,sld:!0,web:!0},dz:{art:!0,asso:!0,com:!0,edu:!0,gov:!0,net:!0,org:!0,pol:!0},ec:{com:!0,edu:!0,fin:!0,gov:!0,info:!0,med:!0,mil:!0,net:!0,org:!0,pro:!0},ee:{com:!0,org:!0,fie:!0,pri:!0},eg:{com:!0,edu:!0,eun:!0,gov:!0,mil:!0,name:!0,net:!0,org:!0,sci:!0},er:{com:!0,edu:!0,gov:!0,ind:!0,mil:!0,net:!0,org:!0,rochest:!0,w:!0},es:{com:!0,edu:!0,gob:!0,nom:!0,org:!0},et:{biz:!0,com:!0,edu:!0,gov:!0,info:!0,
name:!0,net:!0,org:!0},fi:{aland:!0},fj:{ac:!0,biz:!0,com:!0,info:!0,mil:!0,name:!0,net:!0,org:!0,pro:!0},fk:{ac:!0,co:!0,gov:!0,net:!0,nom:!0,org:!0},fr:{asso:!0,com:!0,f:!0,gouv:!0,nom:!0,prd:!0,presse:!0,tm:!0},ge:{com:!0,edu:!0,gov:!0,org:!0,mil:!0,net:!0,pvt:!0},gg:{co:!0,net:!0,org:!0},gh:{com:!0,edu:!0,gov:!0,mil:!0,org:!0},gi:{com:!0,ltd:!0,gov:!0,mod:!0,edu:!0,org:!0},gn:{ac:!0,com:!0,gov:!0,net:!0,org:!0},gp:{com:!0,net:!0,edu:!0,asso:!0,org:!0},gr:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0},
gt:{com:!0,edu:!0,gob:!0,ind:!0,mil:!0,net:!0,org:!0},gu:{com:!0,edu:!0,gov:!0,net:!0,org:!0},hk:{com:!0,edu:!0,gov:!0,idv:!0,net:!0,org:!0},ht:{com:!0,net:!0,firm:!0,shop:!0,info:!0,pro:!0,adult:!0,org:!0,art:!0,pol:!0,rel:!0,asso:!0,perso:!0,coop:!0,med:!0,edu:!0,gouv:!0},hu:{2E3:!0,agrar:!0,bolt:!0,casino:!0,city:!0,co:!0,erotica:!0,erotika:!0,film:!0,forum:!0,games:!0,hotel:!0,info:!0,ingatlan:!0,jogasz:!0,konyvelo:!0,lakas:!0,media:!0,news:!0,org:!0,priv:!0,reklam:!0,sex:!0,shop:!0,sport:!0,
suli:!0,szex:!0,tm:!0,tozsde:!0,utazas:!0,video:!0},id:{ac:!0,co:!0,go:!0,mil:!0,net:!0,or:!0,sch:!0,web:!0},il:{ac:!0,co:!0,gov:!0,idf:!0,k12:!0,muni:!0,net:!0,org:!0},im:{co:!0,"ltd.co":!0,"plc.co":!0,net:!0,gov:!0,org:!0,nic:!0,ac:!0},"in":{ac:!0,co:!0,edu:!0,ernet:!0,firm:!0,gen:!0,gov:!0,i:!0,ind:!0,mil:!0,net:!0,nic:!0,org:!0,res:!0},iq:{com:!0,edu:!0,gov:!0,i:!0,mil:!0,net:!0,org:!0},ir:{ac:!0,co:!0,dnssec:!0,gov:!0,i:!0,id:!0,net:!0,org:!0,sch:!0},it:{edu:!0,gov:!0},je:{co:!0,net:!0,org:!0},
jo:{com:!0,edu:!0,gov:!0,mil:!0,name:!0,net:!0,org:!0,sch:!0},jp:{ac:!0,ad:!0,co:!0,ed:!0,go:!0,gr:!0,lg:!0,ne:!0,or:!0},ke:{ac:!0,co:!0,go:!0,info:!0,me:!0,mobi:!0,ne:!0,or:!0,sc:!0},kh:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0,per:!0},ki:{biz:!0,com:!0,de:!0,edu:!0,gov:!0,info:!0,mob:!0,net:!0,org:!0,tel:!0},km:{asso:!0,com:!0,coop:!0,edu:!0,gouv:!0,k:!0,medecin:!0,mil:!0,nom:!0,notaires:!0,pharmaciens:!0,presse:!0,tm:!0,veterinaire:!0},kn:{edu:!0,gov:!0,net:!0,org:!0},kr:{ac:!0,busan:!0,chungbuk:!0,
chungnam:!0,co:!0,daegu:!0,daejeon:!0,es:!0,gangwon:!0,go:!0,gwangju:!0,gyeongbuk:!0,gyeonggi:!0,gyeongnam:!0,hs:!0,incheon:!0,jeju:!0,jeonbuk:!0,jeonnam:!0,k:!0,kg:!0,mil:!0,ms:!0,ne:!0,or:!0,pe:!0,re:!0,sc:!0,seoul:!0,ulsan:!0},kw:{com:!0,edu:!0,gov:!0,net:!0,org:!0},ky:{com:!0,edu:!0,gov:!0,net:!0,org:!0},kz:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0},lb:{com:!0,edu:!0,gov:!0,net:!0,org:!0},lc:{com:!0,org:!0,edu:!0,gov:!0},li:{com:!0,net:!0,org:!0,gov:!0},lk:{assn:!0,com:!0,edu:!0,gov:!0,grp:!0,
hotel:!0,"int":!0,ltd:!0,net:!0,ngo:!0,org:!0,sch:!0,soc:!0,web:!0},lr:{com:!0,edu:!0,gov:!0,net:!0,org:!0},ls:{org:!0,co:!0},lt:{gov:!0,mil:!0},lu:{gov:!0,mil:!0,org:!0,net:!0},lv:{asn:!0,com:!0,conf:!0,edu:!0,gov:!0,id:!0,mil:!0,net:!0,org:!0},ly:{com:!0,edu:!0,gov:!0,id:!0,med:!0,net:!0,org:!0,plc:!0,sch:!0},ma:{ac:!0,co:!0,gov:!0,m:!0,net:!0,org:!0,press:!0},mc:{asso:!0,tm:!0},me:{ac:!0,co:!0,edu:!0,gov:!0,its:!0,net:!0,org:!0,priv:!0},mg:{com:!0,edu:!0,gov:!0,mil:!0,nom:!0,org:!0,prd:!0,tm:!0},
mk:{com:!0,edu:!0,gov:!0,inf:!0,name:!0,net:!0,org:!0,pro:!0},ml:{com:!0,edu:!0,gov:!0,net:!0,org:!0,presse:!0},mn:{edu:!0,gov:!0,org:!0},mo:{com:!0,edu:!0,gov:!0,net:!0,org:!0},mt:{com:!0,edu:!0,gov:!0,net:!0,org:!0},mv:{aero:!0,biz:!0,com:!0,coop:!0,edu:!0,gov:!0,info:!0,"int":!0,mil:!0,museum:!0,name:!0,net:!0,org:!0,pro:!0},mw:{ac:!0,co:!0,com:!0,coop:!0,edu:!0,gov:!0,"int":!0,museum:!0,net:!0,org:!0},mx:{com:!0,edu:!0,gob:!0,net:!0,org:!0},my:{com:!0,edu:!0,gov:!0,mil:!0,name:!0,net:!0,org:!0,
sch:!0},nf:{arts:!0,com:!0,firm:!0,info:!0,net:!0,other:!0,per:!0,rec:!0,store:!0,web:!0},ng:{biz:!0,com:!0,edu:!0,gov:!0,mil:!0,mobi:!0,name:!0,net:!0,org:!0,sch:!0},ni:{ac:!0,co:!0,com:!0,edu:!0,gob:!0,mil:!0,net:!0,nom:!0,org:!0},no:{mil:!0,stat:!0,kommune:!0,herad:!0,priv:!0,vgs:!0,fhs:!0,museum:!0,fylkesbibl:!0,folkebibl:!0,idrett:!0},np:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0},nr:{biz:!0,com:!0,edu:!0,gov:!0,info:!0,net:!0,org:!0},om:{ac:!0,biz:!0,co:!0,com:!0,edu:!0,gov:!0,med:!0,mil:!0,
museum:!0,net:!0,org:!0,pro:!0,sch:!0},pe:{com:!0,edu:!0,gob:!0,mil:!0,net:!0,nom:!0,org:!0,sld:!0},pf:{com:!0,org:!0,edu:!0},pg:{"com.pg":!0,net:!0},ph:{com:!0,edu:!0,gov:!0,i:!0,mil:!0,net:!0,ngo:!0,org:!0},pk:{biz:!0,com:!0,edu:!0,fam:!0,gob:!0,gok:!0,gon:!0,gop:!0,gos:!0,gov:!0,net:!0,org:!0,web:!0},pl:{art:!0,bialystok:!0,biz:!0,com:!0,edu:!0,gda:!0,gdansk:!0,gorzow:!0,gov:!0,info:!0,katowice:!0,krakow:!0,lodz:!0,lublin:!0,mil:!0,net:!0,ngo:!0,olsztyn:!0,org:!0,poznan:!0,pwr:!0,radom:!0,slupsk:!0,
szczecin:!0,torun:!0,warszawa:!0,waw:!0,wroc:!0,wroclaw:!0,zgora:!0},pr:{ac:!0,biz:!0,com:!0,edu:!0,est:!0,gov:!0,info:!0,isla:!0,name:!0,net:!0,org:!0,pro:!0,prof:!0},pro:{law:!0,med:!0,cpa:!0},ps:{com:!0,edu:!0,gov:!0,net:!0,org:!0,plo:!0,sec:!0},pt:{com:!0,edu:!0,gov:!0,"int":!0,net:!0,nome:!0,org:!0,publ:!0},pw:{belau:!0,co:!0,ed:!0,go:!0,ne:!0,or:!0},ro:{arts:!0,com:!0,firm:!0,info:!0,nom:!0,nt:!0,org:!0,rec:!0,store:!0,tm:!0,www:!0},rs:{ac:!0,co:!0,edu:!0,gov:!0,"in":!0,org:!0},sb:{com:!0,edu:!0,
gov:!0,net:!0,org:!0},sc:{com:!0,edu:!0,gov:!0,net:!0,org:!0},sh:{co:!0,com:!0,edu:!0,gov:!0,net:!0,nom:!0,org:!0},sl:{com:!0,edu:!0,gov:!0,net:!0,org:!0},st:{co:!0,com:!0,consulado:!0,edu:!0,embaixada:!0,gov:!0,mil:!0,net:!0,org:!0,principe:!0,saotome:!0,store:!0},sv:{com:!0,edu:!0,gob:!0,org:!0,red:!0},sz:{ac:!0,co:!0,org:!0},tr:{av:!0,bbs:!0,bel:!0,biz:!0,com:!0,dr:!0,edu:!0,gen:!0,gov:!0,info:!0,k12:!0,name:!0,net:!0,org:!0,pol:!0,tel:!0,tsk:!0,tv:!0,web:!0},tt:{aero:!0,biz:!0,cat:!0,co:!0,com:!0,
coop:!0,edu:!0,gov:!0,info:!0,"int":!0,jobs:!0,mil:!0,mobi:!0,museum:!0,name:!0,net:!0,org:!0,pro:!0,tel:!0,travel:!0},tw:{club:!0,com:!0,ebiz:!0,edu:!0,game:!0,gov:!0,idv:!0,mil:!0,net:!0,org:!0},mu:{ac:!0,co:!0,com:!0,gov:!0,net:!0,or:!0,org:!0},mz:{ac:!0,co:!0,edu:!0,gov:!0,org:!0},na:{co:!0,com:!0},nz:{ac:!0,co:!0,cri:!0,geek:!0,gen:!0,govt:!0,health:!0,iwi:!0,maori:!0,mil:!0,net:!0,org:!0,parliament:!0,school:!0},pa:{abo:!0,ac:!0,com:!0,edu:!0,gob:!0,ing:!0,med:!0,net:!0,nom:!0,org:!0,sld:!0},
py:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0},qa:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0},re:{asso:!0,com:!0,nom:!0},ru:{ac:!0,adygeya:!0,altai:!0,amur:!0,arkhangelsk:!0,astrakhan:!0,bashkiria:!0,belgorod:!0,bir:!0,bryansk:!0,buryatia:!0,cbg:!0,chel:!0,chelyabinsk:!0,chita:!0,chukotka:!0,chuvashia:!0,com:!0,dagestan:!0,"e-burg":!0,edu:!0,gov:!0,grozny:!0,"int":!0,irkutsk:!0,ivanovo:!0,izhevsk:!0,jar:!0,"joshkar-ola":!0,kalmykia:!0,kaluga:!0,kamchatka:!0,karelia:!0,kazan:!0,kchr:!0,kemerovo:!0,
khabarovsk:!0,khakassia:!0,khv:!0,kirov:!0,koenig:!0,komi:!0,kostroma:!0,kranoyarsk:!0,kuban:!0,kurgan:!0,kursk:!0,lipetsk:!0,magadan:!0,mari:!0,"mari-el":!0,marine:!0,mil:!0,mordovia:!0,mosreg:!0,msk:!0,murmansk:!0,nalchik:!0,net:!0,nnov:!0,nov:!0,novosibirsk:!0,nsk:!0,omsk:!0,orenburg:!0,org:!0,oryol:!0,penza:!0,perm:!0,pp:!0,pskov:!0,ptz:!0,rnd:!0,ryazan:!0,sakhalin:!0,samara:!0,saratov:!0,simbirsk:!0,smolensk:!0,spb:!0,stavropol:!0,stv:!0,surgut:!0,tambov:!0,tatarstan:!0,tom:!0,tomsk:!0,tsaritsyn:!0,
tsk:!0,tula:!0,tuva:!0,tver:!0,tyumen:!0,udm:!0,udmurtia:!0,"ulan-ude":!0,vladikavkaz:!0,vladimir:!0,vladivostok:!0,volgograd:!0,vologda:!0,voronezh:!0,vrn:!0,vyatka:!0,yakutia:!0,yamal:!0,yekaterinburg:!0,"yuzhno-sakhalinsk":!0},rw:{ac:!0,co:!0,com:!0,edu:!0,gouv:!0,gov:!0,"int":!0,mil:!0,net:!0},sa:{com:!0,edu:!0,gov:!0,med:!0,net:!0,org:!0,pub:!0,sch:!0},sd:{com:!0,edu:!0,gov:!0,info:!0,med:!0,net:!0,org:!0,tv:!0},se:{a:!0,ac:!0,b:!0,bd:!0,c:!0,d:!0,e:!0,f:!0,g:!0,h:!0,i:!0,k:!0,l:!0,m:!0,n:!0,
o:!0,org:!0,p:!0,parti:!0,pp:!0,press:!0,r:!0,s:!0,t:!0,tm:!0,u:!0,w:!0,x:!0,y:!0,z:!0},sg:{com:!0,edu:!0,gov:!0,idn:!0,net:!0,org:!0,per:!0},sn:{art:!0,com:!0,edu:!0,gouv:!0,org:!0,perso:!0,univ:!0},sy:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,news:!0,org:!0},th:{ac:!0,co:!0,go:!0,"in":!0,mi:!0,net:!0,or:!0},tj:{ac:!0,biz:!0,co:!0,com:!0,edu:!0,go:!0,gov:!0,info:!0,"int":!0,mil:!0,name:!0,net:!0,nic:!0,org:!0,test:!0,web:!0},tn:{agrinet:!0,com:!0,defense:!0,edunet:!0,ens:!0,fin:!0,gov:!0,ind:!0,info:!0,
intl:!0,mincom:!0,nat:!0,net:!0,org:!0,perso:!0,rnrt:!0,rns:!0,rnu:!0,tourism:!0},tz:{ac:!0,co:!0,go:!0,ne:!0,or:!0},ua:{biz:!0,cherkassy:!0,chernigov:!0,chernovtsy:!0,ck:!0,cn:!0,co:!0,com:!0,crimea:!0,cv:!0,dn:!0,dnepropetrovsk:!0,donetsk:!0,dp:!0,edu:!0,gov:!0,"if":!0,"in":!0,"ivano-frankivsk":!0,kh:!0,kharkov:!0,kherson:!0,khmelnitskiy:!0,kiev:!0,kirovograd:!0,km:!0,kr:!0,ks:!0,kv:!0,lg:!0,lugansk:!0,lutsk:!0,lviv:!0,me:!0,mk:!0,net:!0,nikolaev:!0,od:!0,odessa:!0,org:!0,pl:!0,poltava:!0,pp:!0,
rovno:!0,rv:!0,sebastopol:!0,sumy:!0,te:!0,ternopil:!0,uzhgorod:!0,vinnica:!0,vn:!0,zaporizhzhe:!0,zhitomir:!0,zp:!0,zt:!0},ug:{ac:!0,co:!0,go:!0,ne:!0,or:!0,org:!0,sc:!0},uk:{ac:!0,bl:!0,"british-library":!0,co:!0,cym:!0,gov:!0,govt:!0,icnet:!0,jet:!0,lea:!0,ltd:!0,me:!0,mil:!0,mod:!0,"national-library-scotland":!0,nel:!0,net:!0,nhs:!0,nic:!0,nls:!0,org:!0,orgn:!0,parliament:!0,plc:!0,police:!0,sch:!0,scot:!0,soc:!0},us:{dni:!0,fed:!0,isa:!0,kids:!0,nsn:!0},uy:{com:!0,edu:!0,gub:!0,mil:!0,net:!0,
org:!0},ve:{co:!0,com:!0,edu:!0,gob:!0,info:!0,mil:!0,net:!0,org:!0,web:!0},vi:{co:!0,com:!0,k12:!0,net:!0,org:!0},vn:{ac:!0,biz:!0,com:!0,edu:!0,gov:!0,health:!0,info:!0,"int":!0,name:!0,net:!0,org:!0,pro:!0},ye:{co:!0,com:!0,gov:!0,ltd:!0,me:!0,net:!0,org:!0,plc:!0},yu:{ac:!0,co:!0,edu:!0,gov:!0,org:!0},za:{ac:!0,agric:!0,alt:!0,bourse:!0,city:!0,co:!0,cybernet:!0,db:!0,edu:!0,gov:!0,grondar:!0,iaccess:!0,imt:!0,inca:!0,landesign:!0,law:!0,mil:!0,net:!0,ngo:!0,nis:!0,nom:!0,olivetti:!0,org:!0,pix:!0,
school:!0,tm:!0,web:!0},zm:{ac:!0,co:!0,com:!0,edu:!0,gov:!0,net:!0,org:!0,sch:!0}};d.getSLD=function(c){if(d.isNil(c))return null;var a=c.split("."),e=a.length-2;if(0>e)return null;c=a[e];a=a[e+1];e=b[a];return d.isNil(e)||d.isNil(e[c])?null:c+"."+a};d.depthOfTLDorSLD=function(c){if(d.isNil(c))return null;c=d.getSLD(c);return d.isntNil(c)?2:1};d.isInteger=function(c){return d.isNil(c)?!1:"number"===typeof c&&isFinite(c)&&Math.floor(c)===c};d.isNumber=function(c){return d.isNil(c)?!1:"number"===typeof c&&
isFinite(c)};d.isSuccessCode=function(c){return d.isNil(c)?!1:c===a.httpStatusCodes.OK||c===a.httpStatusCodes.PARTIAL_CONTENT||c===a.httpStatusCodes.CREATED||c===a.httpStatusCodes.NO_CONTENT?!0:!1};d.safeFetch=function(c,b,d){b=void 0===b?{}:b;d=void 0===d?a.DEFAULT_FETCH_TIMEOUT:d;return new Promise(function(a,e){var h=setTimeout(function(){e(Error("Request timed out "+c))},d);fetch(c,b).then(function(b){clearTimeout(h);a(b)}).catch(function(b){clearTimeout(h);e(b)})})};d.isSuccessCodeLocalFile=
function(b){return d.isInteger(b)?"Safari"===e.globals.BROWSER&&0===b||b===a.httpStatusCodes.OK?!0:!1:!1};d.urlWithoutQueryParameters=function(b,a){d.isNil(a)&&(a=!0);if(d.isNil(b))return null;var c=new URI(b),e=c.protocol();if(d.isNil(e)||""===e||"http"!==e&&"https"!==e)e="http",c=new URI(e+"://"+b);b=c.hostname();c=c.path();if(d.isNil(c)||"/"===c)c="";return a?e+"://"+b+c:b+c};d.baseURL=function(b){return d.isNil(b)?null:(new URI(b)).hostname()};d.pathName=function(b){return d.isNil(b)?null:(new URI(b)).pathname()};
d.urlProtocol=function(b){if(d.isNil(b))return null;b=(new URI(b)).protocol();return""===b?null:b};d.getUrlTLD=function(b){if(d.isNil(b))return null;b=(new URI(b)).tld();return""===b?null:b};d.getCompanyDomain=function(b){if(d.isNil(b))return null;var c=(new URI(b)).hostname();b=d.getUrlTLD(b);return""===c?null:d.isntNil(b)&&0<c.indexOf(b)?(c=c.substring(0,c.lastIndexOf(b)-1).split("."),c[c.length-1]):c};d.getDomain=function(b){if(d.isNil(b))return null;b=(new URI(b)).domain();return""===b?null:b};
d.isUrlAnIp=function(b){return d.isNil(b)?null:(new URI(b)).is(a.utils.IP)};d.getFileNameExtension=function(b){if(!d.isString(b))return null;b=(new URI(b)).suffix();return""===b?null:b};d.appendToObject=function(b,a){if(d.isNil(b)||d.isNil(a))throw Error("invalid arguments to appendToObject");Object.keys(a).forEach(function(c){b[c]=a[c]})};d.createCustomHTMLEvent=function(b,a){if(!1===d.isString(b))throw Error("Event name cannot be null and has to be a string");b=new CustomEvent(b,{detail:a});window.dispatchEvent(b)};
d.isTopLevelWindow=function(){return"Edge"===e.globals.BROWSER?window.top.location==window.self.location?!0:!1:window.top==window.self?!0:!1};d.getActiveElement=function(){return document.activeElement};d.verifyJson=function(b,a,d,e){try{var c=forge.md.sha256.create();c.update(JSON.stringify(b));var h=c.digest().toHex(),f=KEYUTIL.getKey(d);if(!0===KJUR.jws.JWS.verify(a,f,e)){var m=b64utoutf8(a.split(".")[1]);return KJUR.jws.JWS.readSafeJSONString(m).hash===h}return!1}catch(q){return!1}};d.isNewVersionUpdated=
function(b,a){a=a.split(".");b=b.split(".");var c=a[1]!==b[1];return a[0]!==b[0]||c?!0:!1};d.isStorePageURL=function(b){return d.isString(b)?"Edge"===e.globals.BROWSER?(new RegExp(a.STORE_URLS[e.globals.BROWSER])).test(b):-1===b.indexOf(a.STORE_URLS[e.globals.BROWSER])?!1:!0:!1};d.upperCaseFirstLetter=function(b){return d.isString(b)?b.charAt(0).toUpperCase()+b.slice(1):b};d.setTimeout=function(b){return new Promise(function(c,a){return d.isInteger(b)?window.setTimeout(c,b):a(Error("Delay must be an integer"))})};
d.getValueAtPath=function(b,a,f){a=e.utils.isString(a)?a.split(/[.[\]]/g).filter(Boolean):a;d.isArray(a)||(a=[a]);return a.reduce(function(b,c){return d.objectHas(b,c)?b[c]:f},b||{})};d.setDoNotTrack=function(b){b=void 0===b?!1:b;if(!d.isBoolean(b))throw Error("Parameter to setDoNotTrack should be a boolean");try{Object.defineProperty(navigator,"doNotTrack",{value:b?"1":"0",writable:!1,configurable:!0})}catch(h){}};d.getRandomIntInRange=function(b,e){if(!d.isInteger(b)||!d.isInteger(e)||b>e||b<a.RANDOM_NUMBER_LIMITS.MIN||
e>a.RANDOM_NUMBER_LIMITS.MAX)throw Error("Invalid min or max value");var c=new Uint32Array(1);window.crypto.getRandomValues(c);return Math.floor(c[0]/4294967296*(e-b+1))+b};return d}(f.SymBfw)})(window);
(function(f){f.SymBfw.base64=function(e){var d={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",_utf8Encode:function(a){a=a.replace(/\r\n/g,"\n");for(var b="",c=0;c<a.length;c++){var d=a.charCodeAt(c);128>d?b+=String.fromCharCode(d):(127<d&&2048>d?b+=String.fromCharCode(d>>6|192):(b+=String.fromCharCode(d>>12|224),b+=String.fromCharCode(d>>6&63|128)),b+=String.fromCharCode(d&63|128))}return b},_utf8Decode:function(a){for(var b="",c=0,d,e,f;c<a.length;)d=a.charCodeAt(c),
128>d?(b+=String.fromCharCode(d),c++):191<d&&224>d?(e=a.charCodeAt(c+1),b+=String.fromCharCode((d&31)<<6|e&63),c+=2):(e=a.charCodeAt(c+1),f=a.charCodeAt(c+2),b+=String.fromCharCode((d&15)<<12|(e&63)<<6|f&63),c+=3);return b},encode:function(a){var b="",c=0;for(a=d._utf8Encode(a);c<a.length;){var e=a.charCodeAt(c++);var f=a.charCodeAt(c++);var g=a.charCodeAt(c++);var l=e>>2;e=(e&3)<<4|f>>4;var n=(f&15)<<2|g>>6;var p=g&63;isNaN(f)?n=p=64:isNaN(g)&&(p=64);b=b+d._keyStr.charAt(l)+d._keyStr.charAt(e)+d._keyStr.charAt(n)+
d._keyStr.charAt(p)}return b},decode:function(a){var b="",c=0;for(a=a.replace(/[^A-Za-z0-9\+\/=]\./g,"");c<a.length;){var e=d._keyStr.indexOf(a.charAt(c++));var f=d._keyStr.indexOf(a.charAt(c++));var g=d._keyStr.indexOf(a.charAt(c++));var l=d._keyStr.indexOf(a.charAt(c++));e=e<<2|f>>4;f=(f&15)<<4|g>>2;var n=(g&3)<<6|l;b+=String.fromCharCode(e);64!=g&&(b+=String.fromCharCode(f));64!=l&&(b+=String.fromCharCode(n))}b=d._utf8Decode(b);return b.replace(/\0.*$/g,"")}};return d}()})(window);
(function(f){var e=Math.pow(2,31)-1;f.SymBfw.extensionAdapter=function(d){var a={},b=d.utils.isNil,c=d.utils.isntNil,f=d.utils.isString,k=d.utils.isInteger,g=d.utils.isFunction,l=d.utils.isArray,n=d.utils.isObject,p=d.utils.getValueAtPath;a.getWindowIDNone=function(){if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");return chrome.windows.WINDOW_ID_NONE};a.getLastError=function(){return chrome.runtime.lastError};a.getInvalidTabId=function(){return b(chrome)||b(chrome.tabs)?
-1:chrome.tabs.TAB_ID_NONE};a.getExtensionId=function(){return chrome.runtime.id};a.reloadExtension=function(){if(b(chrome)||b(chrome.runtime))throw Error("chrome is null or chrome.runtime is null");chrome.runtime.reload()};a.isPrivateModeAllowed=function(){return new Promise(function(b){chrome.extension.isAllowedIncognitoAccess(function(a){b(a)})})};a.getBackgroundPage=function(){return b(chrome)||b(chrome.extension)?null:chrome.extension.getBackgroundPage()};a.getExtensionURL=function(a){if(b(chrome)||
b(chrome.extension))throw Error("chrome or chrome.extension is null");if(!f(a))throw Error("extensionAdapter.getExtensionURL expects a string path argument");return chrome.extension.getURL(a)};a.getAllWindows=function(a,c){if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!g(a))throw Error("invalid arguments to extensionAdapter.getAllWindows");b(c)&&(c={});chrome.windows.getAll(c,a)};a.getCurrentWindow=function(a,c){if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");
if(!g(a))throw Error("invalid arguments to extensionAdapter.getAllWindows");b(c)&&(c={});chrome.windows.getCurrent(c,a)};a.createWindow=function(a,e,f){f=void 0===f?!0:f;if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");var m={};d.globals.BROWSER!==d.constants.BROWSER_TYPE.FIREFOX&&(m.focused=f);c(a)&&(m.url=a);chrome.windows.create(m,e)};a.createAppWindow=function(a,d){if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");var m=
{};m.type=chrome.windows.CreateType.PANEL;c(a)&&(m.url=a);chrome.windows.create(m,d)};a.createPrivateWindow=function(a,d,e){e=void 0===e?!0:e;if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");e={incognito:!0,focused:e};c(a)&&(e.url=a);chrome.windows.create(e,d)};a.closeWindow=function(a,c){if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!k(a))throw Error("invalid arguments to extensionAdapter.closeWindow");chrome.windows.remove(a,
c)};a.focusWindow=function(a,c){if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!k(a))throw Error("invalid arguments to extensionAdapter.focusWindow");chrome.windows.update(a,{focused:!0},c)};a.addWindowRemovedEventListener=function(a){if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!g(a))throw Error("extensionAdapter.addWindowRemovedEventListener needs a callback");chrome.windows.onRemoved.addListener(a)};a.removeWindowRemovedEventListener=
function(a){if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!g(a))throw Error("extensionAdapter.removeWindowRemovedEventListener needs a callback");chrome.windows.onRemoved.hasListeners()&&chrome.windows.onRemoved.removeListener(a)};a.addWindowFocusedEventListener=function(a){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.windows is null");if(!g(a))throw Error("extensionAdapter.addWindowFocusedEventListener needs a callback");chrome.windows.onFocusChanged.addListener(a)};
a.getTab=function(a,c){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!k(a)||!g(c))throw Error("invalid arguments to extensionAdapter.getTab");chrome.tabs.get(a,c)};a.detectLanguageByTabId=function(a){return function(a){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!k(a))throw Error("invalid arguments to extensionAdapter.detectLanguageByTabId");return!0}(a)&&g(chrome.tabs.detectLanguage)?new Promise(function(b,c){chrome.tabs.detectLanguage(a,
function(a){b(a)})}):null};a.getActiveTab=function(a,c){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!g(a))throw Error("invalid arguments to extensionAdapter.getActiveTab");var d={active:!0};k(c)?d.windowId=c:d.currentWindow=!0;chrome.tabs.query(d,function(b){a(b[0])})};a.getAllTabs=function(a){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!g(a))throw Error("invalid arguments to extensionAdapter.getAllTabs");chrome.tabs.query({},
a)};a.getTabsWithURL=function(a,c){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!f(a)||!g(c))throw Error("invalid arguments to extensionAdapter.getTabsWithURL");chrome.tabs.query({url:a},c)};a.updateTabUrl=function(a,c,d){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!k(a)||!f(c))throw Error("invalid arguments to extensionAdapter.updateTabUrl");chrome.tabs.update(a,{url:c},d)};a.activateTab=function(a,c){if(b(chrome)||
b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(b(a)||!k(a))throw Error("invalid arguments to extensionAdapter.activateTab");chrome.tabs.update(a,{active:!0},c)};a.createTab=function(a,c,d){d=void 0===d?!0:d;if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");b(a)?chrome.tabs.create({},c):chrome.tabs.create({url:a,active:d},c)};a.closeTab=function(a,c){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!k(a)&&!l(a))throw Error("invalid arguments to extensionAdapter.closeTab");
chrome.tabs.remove(a,c)};a.closeTabAndEnsureBrowserIsAlive=function(b,d){if(!k(b)||0>=b||c(d)&&!g(d))throw Error("Invalid arguments to extensionAdapter.closeTabAndEnsureBrowserIsAlive()");a.getAllWindows(function(e){1===e.length?a.getAllTabs(function(e){1===e.length&&a.createTab();a.closeTab(b);c(d)&&d()}):(a.closeTab(b),c(d)&&d())})};a.addTabRemovedEventListener=function(a){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!g(a))throw Error("extensionAdapter.addTabRemovedEventListener needs a callback");
chrome.tabs.onRemoved.addListener(a)};a.removeTabRemovedEventListener=function(a){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!g(a))throw Error("extensionAdapter.removeTabRemovedEventListener needs a callback");chrome.tabs.onRemoved.hasListener(a)&&chrome.tabs.onRemoved.removeListener(a)};a.addTabActivatedEventListener=function(a){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!g(a))throw Error("extensionAdapter.addTabActivatedEventListener needs a callback");
chrome.tabs.onActivated.addListener(a)};a.addTabReplacedEventListener=function(a){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(b(a)||!g(a))throw Error("extensionAdapter.addTabReplacedEventListener needs a callback");chrome.tabs.onReplaced.addListener(a)};a.addTabUpdatedEventListener=function(a){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!g(a))throw Error("extensionAdapter.addTabUpdatedEventListener needs a callback");
chrome.tabs.onUpdated.addListener(a)};a.removeTabUpdatedEventListener=function(a){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!g(a))throw Error("extensionAdapter.removeTabUpdatedEventListener needs a callback");chrome.tabs.onUpdated.hasListener(a)&&chrome.tabs.onUpdated.removeListener(a)};a.addOnBeforeRequestEventListener=function(a,c,d){if(b(chrome)||b(chrome.webRequest))throw Error("chrome is null or chrome.tabs is null");if(!1===g(a))throw Error("Callback cannot be null");
chrome.webRequest.onBeforeRequest.addListener(a,{urls:c},d)};a.removeOnBeforeRequestEventListener=function(b){chrome.webRequest.onBeforeRequest.removeListener(b)};a.addWebRequestErrorListener=function(b,a){window.chrome.webRequest.onErrorOccurred.addListener(b,a)};a.removeWebRequestErrorListener=function(b){window.chrome.webRequest.onErrorOccurred.removeListener(b)};a.setBrowserIcon=function(a,c){if(b(chrome)||b(chrome.browserAction))throw Error("chrome is null or chrome.browserAction is null");if(b(a))throw Error("invalid arguments to extensionAdapter.setBrowserIcon");
chrome.browserAction.setIcon(a,c)};a.sendMessage=function(a,c){if(b(chrome)||b(chrome.runtime))throw Error("chrome or chrome.runtime is null");if(b(a))throw Error("invalid arguments to extensionAdapter.sendMessage");chrome.runtime.sendMessage(a,c)};a.sendMessageExternal=function(a,c,d){if(b(chrome)||b(chrome.runtime))throw Error("chrome or chrome.runtime is null");if(b(a))throw Error("invalid arguments to extensionAdapter.sendMessage");if(b(c))throw Error("invalid arguments to extensionAdapter.sendMessage");
chrome.runtime.sendMessage(a,c,d)};a.sendMessageToTab=function(a,c,d,e){if(b(chrome)||b(chrome.tabs))throw Error("chrome or chrome.tabs is null");if(b(c)||b(a))throw Error("invalid arguments to extensionAdapter.sendMessageToTab");chrome.tabs.sendMessage(a.id,c,e,d)};a.sendMessageToParentFrame=function(c,d,e,f){if(b(d)||b(c))throw Error("invalid arguments to extensionAdapter.sendMessageToParentFrame");a.getFrame({tabId:c.id,frameId:f}).then(function(b){a.sendMessageToTab(c,d,e,{frameId:b.parentFrameId})})};
a.addMessageListener=function(a){if(b(chrome)||b(chrome.runtime))throw Error("chrome or chrome.runtime is null");if(!g(a))throw Error("invalid arguments to extensionAdapter.addMessageListener");chrome.runtime.onMessage.addListener(function(b,c,d){return a(b,d,c.tab,c.frameId,c.url)})};a.addMessageExternalListener=function(a){if(b(chrome)||b(chrome.runtime))throw Error("chrome or chrome.runtime is null");if(!g(a))throw Error("invalid arguments to extensionAdapter.addMessageExternalListener");chrome.runtime.onMessageExternal.addListener(function(b,
c,d){return a(b,c,d)})};a.addContentScriptMessageListener=function(b){a.addMessageListener(b)};a.addTabCreatedEventListener=function(a){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!g(a))throw Error("extensionAdapter.\u200baddTabCreatedEventListener needs a callback");chrome.tabs.onCreated.addListener(a)};a.removeTabCreatedEventListener=function(a){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!g(a))throw Error("extensionAdapter.removeTabCreatedEventListener needs a callback");
chrome.tabs.onCreated.hasListener(a)&&chrome.tabs.onCreated.removeListener(a)};a.addWindowCreatedEventListener=function(a){if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!g(a))throw Error("extensionAdapter.\u200baddWindowCreatedEventListener needs a callback");chrome.windows.onCreated.addListener(a)};a.getFrame=function(a){var c=null,d={errorOccured:!0,url:null,parentFrameId:null};if(b(chrome)||b(chrome.webNavigation))throw Error("no chrome object available");
a&&(c=b(a.frameId)?new Promise(function(b){b(d)}):new Promise(function(b){chrome.webNavigation.getFrame(a,function(a){b(a)})}));return c};a.getTabID=function(a){return b(a)?null:a.id};a.getWindowIDForTab=function(a){return b(a)?null:a.windowId};a.getWindowID=function(a){return b(a)?null:a.id};a.i18nGetMessage=function(a,c){if(b(window.chrome)||b(window.chrome.i18n))throw Error("Unsupported api");if(!f(a))throw Error("chrome.i18n.getMessage expects a string messageName argument");return chrome.i18n.getMessage(a,
c)};a.hidePopup=function(){window.open("","_self").close()};a.setBadgeText=function(a,d){if(b(chrome)||b(chrome.browserAction))throw Error("chrome or chrome.browserAction is null");if(!f(a)||4<a.length)throw Error("invalid arguments to extensionAdapter.setBadgeText");a={text:a};c(d)&&(a.tabId=d);chrome.browserAction.setBadgeText(a)};a.setTitle=function(a,d){if(b(chrome)||b(chrome.browserAction))throw Error("chrome or chrome.browserAction is null");if(!f(a))throw Error("invalid arguments to extensionAdapter.setTitle");
a={title:a};c(d)&&(a.tabId=d);chrome.browserAction.setTitle(a)};a.setBadgeBackgroundColor=function(a){if(b(chrome)||b(chrome.browserAction))throw Error("chrome or chrome.browserAction is null");if(!f(a))throw Error("invalid arguments to extensionAdapter.setBadgeBackgroundColor");chrome.browserAction.setBadgeBackgroundColor({color:a})};a.onPopoverLoad=function(b){window.addEventListener("load",b)};a.getAllHistory=function(b){b=void 0===b?"":b;return new Promise(function(a){chrome.history.search({text:b,
startTime:0,maxResults:e},function(b){var c=[];b=$jscomp.makeIterator(b);for(var d=b.next();!d.done;d=b.next())d=d.value,f(d.url)&&c.push(d.url);a(c)})})};a.addUrlsToHistory=function(b){if(!l(b))throw Error("urls must be an array");var c=[];b=$jscomp.makeIterator(b);for(var d=b.next();!d.done;d=b.next())c.push(a.addUrlToHistory(d.value));return Promise.all(c)};a.clearHistory=function(){return new Promise(function(b){chrome.history.deleteAll(function(){b()})})};a.addUrlToHistory=function(b){if(!f(b))throw Error("url must be a string");
return new Promise(function(a){chrome.history.addUrl({url:b},function(){a()})})};a.deleteUrlFromHistory=function(a,c){if(b(chrome)||b(chrome.history))throw Error("Unsupported api");if(!f(a))throw Error("url must be a string");chrome.history.deleteUrl({url:a},c)};a.addHistoryOnVisitedListener=function(a){if(b(chrome)||b(chrome.history)||b(chrome.history.onVisited))throw Error("Unsupported api");if(!g(a))throw Error("callback must be a function");chrome.history.onVisited.addListener(a)};a.removeHistoryOnVisitedListener=
function(a){if(b(chrome)||b(chrome.history)||b(chrome.history.onVisited))throw Error("Unsupported api");if(!g(a))throw Error("callback must be a function");chrome.history.onVisited.hasListeners()&&chrome.history.onVisited.removeListener(a)};a.removeBrowsingData=function(a,c,d){if(b(chrome)||b(chrome.browsingData))throw Error("Unsupported api");if(!n(a))throw Error("removalOptions must be an object");if(!n(c))throw Error("dataToRemove must be an object");chrome.browsingData.remove(a,c,d)};a.getAllCookies=
function(b){b=void 0===b?null:b;return new Promise(function(a){chrome.cookies.getAll({domain:b},function(b){a(b)})})};a.removeCookie=function(a){if(b(a))throw Error("cookie cannot be null");var c=(a.secure?"https://":"http://")+a.domain+a.path;return new Promise(function(d,e){chrome.cookies.remove({name:a.name,url:c},function(a){b(a)&&e(chrome.runtime.lastError);d(a)})})};a.removeCookies=function(b,c){if(!l(b))throw Error("cookiesArray must be array");var d=[],e=b;l(c)&&(e=b.filter(function(b){return!c.some(function(a){return a.domain===
b.domain&&a.path===b.path})}));b=$jscomp.makeIterator(e);for(e=b.next();!e.done;e=b.next())d.push(a.removeCookie(e.value));return Promise.all(d)};a.setCookie=function(a){if(b(a))throw Error("cookie cannot be null");var d={url:(new URL((a.secure?"https://":"http://")+a.domain)).toString(),httpOnly:a.httpOnly,name:a.name,sameSite:a.sameSite,secure:a.secure,storeId:a.storeId,value:a.value,path:a.path};f(a.domain)&&"."===a.domain.charAt()&&(d.domain=a.domain);c(a.expirationDate)&&(d.expirationDate=a.expirationDate);
return new Promise(function(a,e){chrome.cookies.set(d,function(d){var f=chrome.runtime.lastError;b(d)&&c(f)&&e(f);a(d)})})};a.setCookies=function(b){if(!l(b))throw Error("cookiesArray must be array");var c=[];b=$jscomp.makeIterator(b);for(var d=b.next();!d.done;d=b.next())c.push(a.setCookie(d.value));return Promise.all(c)};a.onCookieChangedForUrl=function(b,a){if(!f(b))throw Error("url must be a string");if(!g(a))throw Error("callback must be a function");chrome.cookies.onChanged.addListener(function(c){var d=
p(c,"cookie.domain");f(d)&&d.includes(b)?a(c):a()})};a.checkCookieContentSettingsForUrl=function(a){if(b(chrome)||b(chrome.contentSettings))throw Error("Unsupported api");if(!f(a))throw Error("primaryUrl must be a string");return new Promise(function(b,c){chrome.contentSettings.cookies.get({primaryUrl:a},function(a){a.setting===chrome.contentSettings.CookiesContentSetting.BLOCK?c(Error("Cookie was blocked")):b()})})};a.getVersion=function(){return chrome.runtime.getManifest().version};a.setProxySettings=
function(a){if(b(chrome)||b(chrome.proxy))throw Error("Unsupported api");if(!n(a))throw Error("details must be an object");return new Promise(function(b){chrome.proxy.settings.set(a,b)})};a.getProxySettings=function(){if(b(chrome)||b(chrome.proxy))throw Error("Unsupported api");return new Promise(function(b){chrome.proxy.settings.get({},b)})};a.onProxySettingsChange=function(a){if(b(chrome)||b(chrome.proxy))throw Error("Unsupported api");if(!g(a))throw Error("callback must be a function");chrome.proxy.settings.onChange.addListener(a)};
a.onProxyError=function(a){if(b(chrome)||b(chrome.proxy))throw Error("Unsupported api");if(!g(a))throw Error("callback must be a function");chrome.proxy.onProxyError.addListener(a)};a.onWebRequestAuthRequired=function(a){if(b(chrome)||b(chrome.webRequest))throw Error("Unsupported api");if(!g(a))throw Error("callback must be a function");chrome.webRequest.onAuthRequired.addListener(a,{urls:["<all_urls>"]},["asyncBlocking"])};a.init=function(){};a.returnAdapter=function(){var b={};b.getExtensionURL=
a.getExtensionURL;b.getBackgroundPage=a.getBackgroundPage;b.sendMessage=a.sendMessage;b.addMessageListener=a.addMessageListener;b.addContentScriptMessageListener=a.addContentScriptMessageListener;b.getExtensionId=a.getExtensionId;b.init=a.init;try{return chrome.tabs?a:b}catch(q){return b}};return a.returnAdapter()}(f.SymBfw)})(window);
(function(f){f.SymBfw.clipboard=function(e){var d={},a=e.utils.isNil,b=e.logger;d.createDummyTextAreaAndSetText=function(b){var a=document.createElement("textarea");a.style.position="fixed";a.style.top=0;a.style.left=0;a.style.width="2em";a.style.height="2em";a.style.padding=0;a.style.border="none";a.style.outline="none";a.style.boxShadow="none";a.style.background="transparent";a.value=b;document.body.appendChild(a);a.select();return a};d.copyToClipboard=function(c){if(a(c)||""===c)throw Error("Value to copy to clipboard cannot be null");
c=d.createDummyTextAreaAndSetText(c);document.execCommand("copy")||b.error("Failed to copy to clipboard");document.body.removeChild(c)};return d}(f.SymBfw)})(window);
(function(f){f.SymBfw.localizerProxy=function(e){var d=e.utils.isNil,a=e.utils.isFunction,b=e.constants.localizer,c={getLocalizedString:function(a,d){c.sendMessage(b.GET_LOCALIZED_STRING,a,d)},getLocalizedStrings:function(a,d){c.sendMessage(b.GET_LOCALIZED_STRINGS,a,d)},getAllLocalizedStrings:function(a){c.sendMessage(b.GET_ALL_LOCALIZED_STRINGS,{},a)},getLocalizedStringFromDictionary:function(a,d,e){c.sendMessage(b.GET_LOCALIZED_STRING_FROM_DICTIONARY,{string:a,name:d},e)},getLocalizedStringsFromDictionary:function(a,
d,e){c.sendMessage(b.GET_LOCALIZED_STRINGS_FROM_DICTIONARY,{array:a,name:d},e)},getLocalizedStringsWithFormat:function(a,d){c.sendMessage(b.GET_LOCALIZED_STRINGS_WITH_FORMAT,{formatStringDict:a},d)},getLocalizedStringWithFormat:function(a,d,e){c.sendMessage(b.GET_LOCALIZED_STRING_WITH_FORMAT,{string:a,params:d},e)},getLocalizedStringWithFormatFromDictionary:function(a,d,e,f){c.sendMessage(b.GET_LOCALIZED_STRING_WITH_FORMAT_FROM_DICTIONARY,{string:a,params:d,name:e},f)},getCurrentLanguageDirection:function(a){c.sendMessage(b.GET_CURRENT_LANGUAGE_DIRECTION,
{},a)},sendMessage:function(c,f,g){if(d(c))throw Error("Message ID cannot be null");if(d(f))throw Error("Payload cannot be null");if(!1===a(g))throw Error("Callback cannot be null");e.extensionAdapter.sendMessage({id:c,payload:f},function(a){switch(a.id){case b.GET_LOCALIZED_STRING:case b.GET_LOCALIZED_STRINGS:case b.GET_ALL_LOCALIZED_STRINGS:case b.GET_LOCALIZED_STRING_FROM_DICTIONARY:case b.GET_LOCALIZED_STRINGS_FROM_DICTIONARY:case b.GET_LOCALIZED_STRING_WITH_FORMAT:case b.GET_LOCALIZED_STRING_WITH_FORMAT_FROM_DICTIONARY:case b.GET_CURRENT_LANGUAGE_DIRECTION:case b.GET_LOCALIZED_STRINGS_WITH_FORMAT:g(a.payload)}})}};
return c}(f.SymBfw)})(window);
(function(f){f=f.SymBfw=f.SymBfw||{};var e={APPLICATION_NAME:"APPLICATION_NAME",APPLICATION_VERSION:"APPLICATION_VERSION",CLIENT_ID:"CLIENT_ID",DATA_SOURCE:"DATA_SOURCE",TRACKING_ID:"TRACKING_ID",USER_AGENT:"USER_AGENT",USER_LANGUAGE:"USER_LANGUAGE",GOOGLE_ANALYTICS_PROTOCOL_VERSION:"GOOGLE_ANALYTICS_PROTOCOL_VERSION",ANONYMIZE_IP:"ANONYMIZE_IP"};e.defaultParametersList=[e.APPLICATION_NAME,e.APPLICATION_VERSION,e.CLIENT_ID,e.DATA_SOURCE,e.TRACKING_ID,e.GOOGLE_ANALYTICS_PROTOCOL_VERSION,e.ANONYMIZE_IP];
e.dataSource={BROWSER_EXTENSION:"web",MOBILE_APP:"app"};e.HIT_TYPE={PAGE_VIEW:"pageview",SCREEN_VIEW:"screenview",EVENT:"event",EXCEPTION:"exception",SOCIAL:"social"};e.MESSAGES={SEND_TELEMETRY_TO_BGPROXY:"b021e29a-4fe3-4a60-865f-0cf783318187"};e.parameters={NON_INTERACTION_HIT:"ni",HIT_TYPE:"t",CATEGORY:"ec",ACTION:"ea",LABEL:"el",SOCIAL_NETWORK:"sn",SOCIAL_ACTION:"sa",SOCIAL_TARGET:"st",DOCUMENT_PATH:"dp",DOCUMENT_TITLE:"dt",CUSTOM_DIMENSION1:"cd1",CUSTOM_DIMENSION3:"cd3",CUSTOM_DIMENSION4:"cd4",
CUSTOM_DIMENSION5:"cd5",PRODUCT_IMPRESSION_BRAND1:"il1pi1br",ITEM_CATEGORY:"iv",CAMPAIGN_SOURCE:"cs",CAMPAIGN_MEDIUM:"cm",CLIENT_ID:"cd2"};e.TELEMETRY_CATEGORY={BROWSER:"Browser",EXTENSION:"Extension"};e.actionType={BROWSER:{LAUNCH:"launch",UPDATE:"update"},EXTENSION:{INSTALL:"install",UPDATE:"update"}};e.defaultParameters={APPLICATION_NAME:{maxLength:100,key:"an"},APPLICATION_VERSION:{maxLength:100,key:"av"},CLIENT_ID:{maxLength:100,key:"cid"},DATA_SOURCE:{maxLength:50,key:"ds",value:e.dataSource.BROWSER_EXTENSION},
TRACKING_ID:{maxLength:100,key:"tid"},USER_AGENT:{maxLength:1E3,key:"ua"},USER_LANGUAGE:{maxLength:20,key:"ul"},GOOGLE_ANALYTICS_PROTOCOL_VERSION:{maxLength:100,key:"v",value:1},ANONYMIZE_IP:{maxLength:1,key:"aip",value:1}};f.telemetryConstants=e})(window);(function(f){f.SymBfw.telemetryProxy=function(e){var d=e.utils.isNil,a=e.telemetryConstants;return{send:function(b){if(d(b))throw Error("parameters cannot be null");e.extensionAdapter.sendMessage({id:a.MESSAGES.SEND_TELEMETRY_TO_BGPROXY,payload:{parameters:b}})}}}(f.SymBfw)})(window);
(function(f){f.SymBfw=f.SymBfw||{};f=f.SymBfw;var e={CONFIG:{IGNORE_TELEMETRY_ENABLED_SETTINGS:"IGNORE_TELEMETRY_ENABLED_SETTINGS",WAIT_TIME:"WAIT_TIME",DELIVERED_CALLBACK:"DELIVERED_CALLBACK",TOKEN:"TOKEN",DISTINCT_ID:"DISTINCT_ID",MIXPANEL_CONFIG:"MIXPANEL_CONFIG"},MESSAGES:{SEND_MESSAGE_TO_MESSAGE_BG:"49d07cbd-55cc-4e0b-a6c6-f76d225ef165",SEND_MESSAGE_TO_MESSAGE_PROXY:"4cdb9813-d1b3-44c2-a691-8294589a5a89"}};e.MESSAGES.TYPE={ACTIVATE:"activate",DELIVERED_MINI:"delivered_mini",DELIVERED_TAKEOVER:"delivered_takeover",
RETRIEVE_MESSAGE:"retrieve_message",CLOSE_MESSAGE:"close_message",RENDER_VIDEO:"render_video"};e.PARAMETERS={TOKEN:"TOKEN",DISTINCT_ID:"DISTINCT_ID",WAIT_TIME:"WAIT_TIME",MIXPANEL_CONFIG:"MIXPANEL_CONFIG"};e.UI={MESSAGE:"mixpanel-notification-wrapper",MINI:"mixpanel-notification-mini",VIDEO:"mixpanel-notification-video-frame"};e.STYLE={SHOW_MINI:"show-mini",SHOW_TAKEOVER:"show-takeover",HIDE:"hide"};f.inProductMessagingConstants=e})(window);
(function(f){f=f.SymBfw=f.SymBfw||{};var e={APPLICATION_NAME:"APPLICATION_NAME",APPLICATION_VERSION:"APPLICATION_VERSION",DATA_SOURCE:"DATA_SOURCE",USER_LANGUAGE:"USER_LANGUAGE",TOKEN:"TOKEN",CLIENT_ID:"CLIENT_ID"};e.defaultParametersList=[e.APPLICATION_NAME,e.APPLICATION_VERSION,e.DATA_SOURCE];e.dataSource={BROWSER_EXTENSION:"web",MOBILE_APP:"app"};e.HIT_TYPE={PAGE_VIEW:"pageview",SCREEN_VIEW:"screenview",EVENT:"event",EXCEPTION:"exception"};e.MESSAGES={SEND_TELEMETRY_TO_V2_BG:"3fd353b0-319d-41f3-b3a3-22e893730e65"};
e.MESSAGES.TYPE={TRACK:"TRACK",SET_PROPERTY:"SET_PROPERTY",INCREMENT:"INCREMENT",APPEND_PROPERTY:"APPEND_PROPERTY",UNION_PROPERTY:"UNION_PROPERTY"};e.parameters={NON_INTERACTION_HIT:"ni",HIT_TYPE:"t",ACTION:"ea",LABEL:"el",DOCUMENT_PATH:"dp",DOCUMENT_TITLE:"dt",CUSTOM_DIMENSION1:"cd1",PRODUCT_IMPRESSION_BRAND1:"il1pi1br",ITEM_CATEGORY:"iv",CAMPAIGN_SOURCE:"cs",CAMPAIGN_MEDIUM:"cm"};e.TELEMETRY_CATEGORY={BROWSER:"Browser",EXTENSION:"Extension"};e.actionType={BROWSER:{LAUNCH:"launch",UPDATE:"update"},
EXTENSION:{INSTALL:"install",UPDATE:"update"}};e.defaultParameters={APPLICATION_NAME:{maxLength:100,key:"app_name"},APPLICATION_VERSION:{maxLength:100,key:"app_version"},DATA_SOURCE:{maxLength:50,key:"data_source",value:e.dataSource.BROWSER_EXTENSION},USER_LANGUAGE:{maxLength:20,key:"user_language"}};e.CONFIG={IGNORE_TELEMETRY_ENABLED_SETTINGS:"IGNORE_TELEMETRY_ENABLED_SETTINGS",DEFAULT_PARAMETERS:"DEFAULT_PARAMETERS",DEFAULT_PROFILE:"DEFAULT_PROFILE",TOKEN:"TOKEN",DISTINCT_ID:"DISTINCT_ID",MIXPANEL_CONFIG:"MIXPANEL_CONFIG"};
f.telemetryV2Constants=e})(window);
(function(f){f.SymBfw.telemetryV2Proxy=function(e){var d=e.utils.isNil,a=e.telemetryV2Constants,b={send:function(c,d){b._sendTelemetryRequest(d,a.MESSAGES.TYPE.TRACK,c)},setProfile:function(c){b._sendTelemetryRequest(c,a.MESSAGES.TYPE.SET_PROPERTY)},incrementProperty:function(c){b._sendTelemetryRequest(c,a.MESSAGES.TYPE.INCREMENT)},appendPropertyList:function(c){b._sendTelemetryRequest(c,a.MESSAGES.TYPE.APPEND_PROPERTY)},unionPropertyList:function(c){b._sendTelemetryRequest(c,a.MESSAGES.TYPE.UNION_PROPERTY)},
_sendTelemetryRequest:function(b,f,k){if(f===a.MESSAGES.TYPE.TRACK&&d(k))throw Error("event cannot be null");e.extensionAdapter.sendMessage({id:a.MESSAGES.SEND_TELEMETRY_TO_V2_BG,type:f,payload:{event:k,parameters:b}})}};return b}(f.SymBfw)})(window);
(function(f){f.SymBfw.telemetryWrapper=function(e){var d=e.utils.isNil,a=e.utils.isString,b={TELEMETRY_CATEGORY:"bfw",TELEMETRY_TYPE:"event",componentType:{LOGGER:"logger",LOCALIZER:"localizer",STORAGE:"storage",SETTINGS:"settings",SECURE_SETTINGS:"secureSettings"},actionType:{WARN:"warn",ERROR:"error"},parameters:{EVENT:"t",CATEGORY:"ec",ACTION:"ea",PAYLOAD:"el"},send:function(c,f,k){if(!a(c))throw Error("componentType should be a string");if(!a(f))throw Error("actionType should be a string");if(d(k))throw Error("payload should not be Nil");
if(!a(k)){if(!(k instanceof Error))throw Error("payload should be an instanceof Error other than a string");k=k.toString()}var g={};g[b.parameters.EVENT]=b.TELEMETRY_TYPE;g[b.parameters.CATEGORY]=b.TELEMETRY_CATEGORY+"-"+c;g[b.parameters.ACTION]=f;g[b.parameters.PAYLOAD]=k;return(e.telemetry||e.telemetryProxy).send(g)}};return b}(f.SymBfw)})(window);
(function(f){f.SymBfw.inProductMessagingIframeAdapter=function(e){var d=e.inProductMessagingConstants,a={messageIframe:null,targetUrl:"",setDestinationIframe:function(b,c){a.messageIframe=document.getElementById(b);a.targetUrl=c},passMessageToIframe:function(b){a.messageIframe.contentWindow.postMessage(b,a.targetUrl)},handleBGMessage:function(b){b.id===d.MESSAGES.SEND_MESSAGE_TO_MESSAGE_PROXY&&a.passMessageToIframe(b)},handleIframeMessage:function(b){b=b.data;if(b.id===d.MESSAGES.SEND_MESSAGE_TO_MESSAGE_BG){switch(b.type){case d.MESSAGES.TYPE.DELIVERED_MINI:a.messageIframe.className=
d.STYLE.SHOW_MINI;break;case d.MESSAGES.TYPE.CLOSE_MESSAGE:a.messageIframe.className=d.STYLE.HIDE;return;case d.MESSAGES.TYPE.DELIVERED_TAKEOVER:a.messageIframe.className=d.STYLE.SHOW_TAKEOVER;break;case d.MESSAGES.TYPE.RENDER_VIDEO:a.messageIframe.className=d.STYLE.SHOW_TAKEOVER;return;default:throw Error("Unexpected payload type");}e.extensionAdapter.sendMessage(b)}}};return a}(f.SymBfw)})(window);
(function(f){f.SymBfw.domElementInjecter=function(){var e={injectElement:function(d,a,b,c){b=void 0===b?!0:b;c=void 0===c?!0:c;return new Promise(function(e,f){var g=document.createElement(d);g.addEventListener("load",function(){e(g)});g.addEventListener("error",function(){f()});switch(d){case "script":g.src=a;g.async=b;break;case "link":g.href=a;g.type="text/css";g.rel="stylesheet";g.async=b;break;case "iframe":g.src=a,g.async=b}c?document.head.appendChild(g):document.body.appendChild(g)})},readFileAsText:function(d){return new Promise(function(a,
b){var c=new XMLHttpRequest;c.onreadystatechange=function(){200===c.status&&c.readyState===XMLHttpRequest.DONE?a(c.responseText):c.readyState==XMLHttpRequest.DONE&&200!==c.status&&b()};c.open("GET",d,!0);c.send()})},injectScriptFromBlob:function(d,a,b){a=void 0===a?!0:a;b=void 0===b?!0:b;d=new Blob(d,{type:"text/javascript"});d=URL.createObjectURL(d);return e.injectElement("script",d,a,b)}};return e}()})(window);
(function(f){var e={},d=SymBfw.utils.isntNil,a=SymBfw.utils.isNil,b=SymBfw.localizerProxy,c=SymBfw.constants.uiConstants;e.direction="ltr";e.updateFrameSizeAndLocation=function(b,c,e,f){b=document.getElementById(b);a(b)||(d(e)&&b.setAttribute("width",e),d(c)&&b.setAttribute("height",c),d(f)&&b.setAttribute("style","left:"+f.left+"px;top:"+f.top+"px;"))};e.createFrame=function(a,c,f,l,n){b.getCurrentLanguageDirection(function(b){e.direction=b;var g=document.createElement("IFRAME");g.setAttribute("id",
a);g.setAttribute("src",c);g.setAttribute("class","symc-notification-hide");g.setAttribute("frameBorder",0);g.setAttribute("dir",b);d(l)&&g.setAttribute("width",l);d(f)&&g.setAttribute("height",f);d(n)&&g.setAttribute("style","left:"+n.left+"px;top:"+n.top+"px;");document.documentElement.appendChild(g);g.addEventListener("load",function(){"symc-in-page-popup"!==g.getAttribute("id")&&g.setAttribute("class","symc-notification-show")})})};e.getDirection=function(){return e.direction};e.injectStyle=function(b){var a=
document.documentElement,e=document.getElementById(c.CONTENT_PAGE_STYLE_ID);d(e)&&a.removeChild(e);e=document.createElement("LINK");e.setAttribute("id",c.CONTENT_PAGE_STYLE_ID);e.setAttribute("rel","stylesheet");e.setAttribute("href",b);a.appendChild(e)};e.isPageRTL=function(a){for(;d(a);){var b=a.getAttribute("dir");if(d(b)&&"rtl"===b)return!0;a=a.parentElement}return!1};e.isTopLevelWindow=function(){return window===window.top?!0:!1};f.SymBfw.uiUtils=e})(window);
(function(f){f.SymBfw.performanceReporterFactoryProxy=function(e){var d=e.utils.isNil,a=e.extensionAdapter,b=e.constants.performanceReporter.MESSAGES,c={AUTOMATION_MODE:!1,reportStart:function(a,d){c.sendMessage(b.REPORT_START,{component:a,type:d})},reportEnd:function(a,d){c.sendMessage(b.REPORT_END,{component:a,type:d})},sendMessage:function(b,f){if(!1!==c.AUTOMATION_MODE){if(d(b))throw Error("messageID cannot be null");if(d(f))throw Error("payload cannot be null");d(this._frameGUID)&&(this._frameGUID=
e.utils.createNewGuid());f.guid=this._frameGUID;f.frameURL=document.URL;a.sendMessage({id:b,payload:f})}}};return c}(f.SymBfw)})(window);
