var CryptoJS=CryptoJS||function(h,u){var f={},v=f.lib={},n=function(){},k=v.Base={extend:function(a){n.prototype=this;var c=new n;a&&c.mixIn(a);c.hasOwnProperty("init")||(c.init=function(){c.$super.init.apply(this,arguments)});c.init.prototype=c;c.$super=this;return c},create:function(){var a=this.extend();a.init.apply(a,arguments);return a},init:function(){},mixIn:function(a){for(var c in a)a.hasOwnProperty(c)&&(this[c]=a[c]);a.hasOwnProperty("toString")&&(this.toString=a.toString)},clone:function(){return this.init.prototype.extend(this)}},
r=v.WordArray=k.extend({init:function(a,c){a=this.words=a||[];this.sigBytes=c!=u?c:4*a.length},toString:function(a){return(a||w).stringify(this)},concat:function(a){var c=this.words,d=a.words,b=this.sigBytes;a=a.sigBytes;this.clamp();if(b%4)for(var e=0;e<a;e++)c[b+e>>>2]|=(d[e>>>2]>>>24-e%4*8&255)<<24-(b+e)%4*8;else if(65535<d.length)for(e=0;e<a;e+=4)c[b+e>>>2]=d[e>>>2];else c.push.apply(c,d);this.sigBytes+=a;return this},clamp:function(){var a=this.words,c=this.sigBytes;a[c>>>2]&=4294967295<<32-
c%4*8;a.length=h.ceil(c/4)},clone:function(){var a=k.clone.call(this);a.words=this.words.slice(0);return a},random:function(a){for(var c=[],d=0;d<a;d+=4)c.push(4294967296*h.random()|0);return new r.init(c,a)}}),x=f.enc={},w=x.Hex={stringify:function(a){var c=a.words;a=a.sigBytes;for(var d=[],b=0;b<a;b++){var e=c[b>>>2]>>>24-b%4*8&255;d.push((e>>>4).toString(16));d.push((e&15).toString(16))}return d.join("")},parse:function(a){for(var c=a.length,d=[],b=0;b<c;b+=2)d[b>>>3]|=parseInt(a.substr(b,2),16)<<
24-b%8*4;return new r.init(d,c/2)}},l=x.Latin1={stringify:function(a){var c=a.words;a=a.sigBytes;for(var d=[],b=0;b<a;b++)d.push(String.fromCharCode(c[b>>>2]>>>24-b%4*8&255));return d.join("")},parse:function(a){for(var c=a.length,d=[],b=0;b<c;b++)d[b>>>2]|=(a.charCodeAt(b)&255)<<24-b%4*8;return new r.init(d,c)}},g=x.Utf8={stringify:function(a){try{return decodeURIComponent(escape(l.stringify(a)))}catch(c){throw Error("Malformed UTF-8 data");}},parse:function(a){return l.parse(unescape(encodeURIComponent(a)))}},
z=v.BufferedBlockAlgorithm=k.extend({reset:function(){this._data=new r.init;this._nDataBytes=0},_append:function(a){"string"==typeof a&&(a=g.parse(a));this._data.concat(a);this._nDataBytes+=a.sigBytes},_process:function(a){var c=this._data,d=c.words,b=c.sigBytes,e=this.blockSize,f=b/(4*e);f=a?h.ceil(f):h.max((f|0)-this._minBufferSize,0);a=f*e;b=h.min(4*a,b);if(a){for(var p=0;p<a;p+=e)this._doProcessBlock(d,p);p=d.splice(0,a);c.sigBytes-=b}return new r.init(p,b)},clone:function(){var a=k.clone.call(this);
a._data=this._data.clone();return a},_minBufferSize:0});v.Hasher=z.extend({cfg:k.extend(),init:function(a){this.cfg=this.cfg.extend(a);this.reset()},reset:function(){z.reset.call(this);this._doReset()},update:function(a){this._append(a);this._process();return this},finalize:function(a){a&&this._append(a);return this._doFinalize()},blockSize:16,_createHelper:function(a){return function(c,d){return(new a.init(d)).finalize(c)}},_createHmacHelper:function(a){return function(c,d){return(new y.HMAC.init(a,
d)).finalize(c)}}});var y=f.algo={};return f}(Math);
(function(h){var u=CryptoJS,f=u.lib,v=f.WordArray,n=f.Hasher;f=u.algo;for(var k=[],r=[],x=function(a){return 4294967296*(a-(a|0))|0},w=2,l=0;64>l;){a:{var g=w;for(var z=h.sqrt(g),y=2;y<=z;y++)if(!(g%y)){g=!1;break a}g=!0}g&&(8>l&&(k[l]=x(h.pow(w,.5))),r[l]=x(h.pow(w,1/3)),l++);w++}var a=[];f=f.SHA256=n.extend({_doReset:function(){this._hash=new v.init(k.slice(0))},_doProcessBlock:function(c,d){for(var b=this._hash.words,e=b[0],f=b[1],p=b[2],h=b[3],q=b[4],k=b[5],l=b[6],n=b[7],m=0;64>m;m++){if(16>m)a[m]=
c[d+m]|0;else{var t=a[m-15],g=a[m-2];a[m]=((t<<25|t>>>7)^(t<<14|t>>>18)^t>>>3)+a[m-7]+((g<<15|g>>>17)^(g<<13|g>>>19)^g>>>10)+a[m-16]}t=n+((q<<26|q>>>6)^(q<<21|q>>>11)^(q<<7|q>>>25))+(q&k^~q&l)+r[m]+a[m];g=((e<<30|e>>>2)^(e<<19|e>>>13)^(e<<10|e>>>22))+(e&f^e&p^f&p);n=l;l=k;k=q;q=h+t|0;h=p;p=f;f=e;e=t+g|0}b[0]=b[0]+e|0;b[1]=b[1]+f|0;b[2]=b[2]+p|0;b[3]=b[3]+h|0;b[4]=b[4]+q|0;b[5]=b[5]+k|0;b[6]=b[6]+l|0;b[7]=b[7]+n|0},_doFinalize:function(){var a=this._data,d=a.words,b=8*this._nDataBytes,e=8*a.sigBytes;
d[e>>>5]|=128<<24-e%32;d[(e+64>>>9<<4)+14]=h.floor(b/4294967296);d[(e+64>>>9<<4)+15]=b;a.sigBytes=4*d.length;this._process();return this._hash},clone:function(){var a=n.clone.call(this);a._hash=this._hash.clone();return a}});u.SHA256=n._createHelper(f);u.HmacSHA256=n._createHmacHelper(f)})(Math);
