var WAXUtils=function(){var h={Unknown:0,Text:1,TextArea:2,Password:3,Submit:4,Image:5,Button:6,Checkbox:7,Radio:8,Reset:9,File:10,Hidden:11,Select:12,EventObject:13},q={Unknown:0,Label:1,TableCell:2,Header:3,Table:4,TableBody:5,TableRow:6,Input:7,TextArea:8,Button:9,Image:10,Select:11,Link:12,Container:13,SelectOption:14,Generic:15,Form:16,Comments:17,FieldSet:18,AjaxLink:19},f={Unknown:0,IE:1,Firefox:3,Chrome:4,Safari:5,Opera:6},k=f.Unknown,l=-1,n=!1,m=null,p=null;return{setInit:function(a){n=a},
getInit:function(){return n},getInputTypeEnum:function(){return h},getElementTypeEnum:function(){return q},getBrowserTypeEnum:function(){return f},getBrowserType:function(){if(f.Unknown!=k)return k;if(window.ActiveXObject)k=f.IE;else{var a=navigator.userAgent;-1!=a.indexOf("Firefox")?k=f.Firefox:-1!=a.indexOf("Chrome/")?k=f.Chrome:-1!=a.indexOf("Safari")?k=f.Safari:-1!=a.indexOf("Opera")&&(k=f.Opera)}return k},getBrowserVersion:function(){if(-1!=l)return l;if(/MSIE (\d+\.\d+);/.test(navigator.userAgent))l=
new Number(RegExp.$1);else if(/Firefox[\/\s](\d+\.\d+)/.test(navigator.userAgent))l=new Number(RegExp.$1);else if(/Chrome[\/\s](\d+\.\d+)/.test(navigator.userAgent))l=new Number(RegExp.$1);else if(-1!=navigator.userAgent.indexOf("Opera")){var a=navigator.userAgent.split("Version/");l=a[1].substring(0,a[1].indexOf("."))}else/Version[\/\s](\d+\.\d+)/.test(navigator.userAgent)&&(l=new Number(RegExp.$1));return l},eventCallback:function(a,b){0==b?waxEntry(a,1==a?document.documentElement:WAXUtils.getLoginForm()):
setTimeout(function(){waxEntry(a,1==a?document.documentElement:WAXUtils.getLoginForm())},b)},addListener:function(a,b,c,e){var g=WAXUtils.getBrowserType();if(f.Unknown==g)return!1;a.addEventListener(b,function(){WAXUtils.eventCallback(c,e)},!1);return!0},removeListener:function(a,b){var c=WAXUtils.getBrowserType();if(f.Unknown==c)return!1;a.removeEventListener(b,WAXUtils.eventCallback,!1);return!0},trim:function(a){if(null==a||"undefined"==typeof a)return"";a=a.replace(/^\s\s*/,"").replace(/\s\s*$/,
"");'"'==a.charAt(0)&&(a=a.substring(1,a.length));'"'==a.charAt(a.length-1)&&(a=a.substring(0,a.length-1));return a},matchesAttributes:function(a,b){if("undefined"==typeof a||"undefined"==typeof b||Array!=a.constructor)return!1;for(var c=!0,e=0;e<a.length;e++){var g=a[e].split(":="),d=WAXUtils.trim(g[0]);g=WAXUtils.trim(g[1]);if("index"!=d)if("tagname"==d){if(b.tagName.toLowerCase()!=g.toLowerCase()){c=!1;break}}else if("innerText"==d){if(d=WAXUtils.getBrowserType()==f.Firefox?b.textContent:b.innerText,
d=WAXUtils.trim(d),d.toLowerCase()!=g.toLowerCase()){c=!1;break}}else if(d=b.getAttribute(d),null==d||g!=d){c=!1;break}}return c},findElement:function(a){if(null==a||"undefined"==typeof a)return null;a=a.replace(/(", ")|(" , ")|(" ,")/g,'","');var b=a.split('","'),c=b[0].split(":="),e=WAXUtils.trim(c[0]);c=WAXUtils.trim(c[1]);var g=null;if("id"==e)g=window.document.getElementById(c);else if("tagname"==e){e=window.document.getElementsByTagName(c);if("undefined"==typeof e||null==e)return null;var d=
[];for(c=0;c<e.length;c++){var f=e[c];WAXUtils.matchesAttributes(b,f)&&d.push(f)}1==d.length?g=d[0]:(b=a.split('","'),c=b[b.length-1].split(":="),e=WAXUtils.trim(c[0]),"index"==e&&(c=WAXUtils.trim(c[1]),c<d.length&&(g=d[c])))}return g},onLoginKeyDown:function(a){if("undefined"!=typeof a&&null!=a){var b=a.keyCode?a.keyCode:event.keyCode,c=!1;WAXUtils.isTextInput(a.srcElement?a.srcElement:a.target)?13==b&&(c=WAXUtils.verifyLoginInputs()):32==b&&(c=WAXUtils.verifyLoginInputs());c&&waxEntry(2,WAXUtils.getLoginForm())}},
onLoginClick:function(a){"undefined"!=typeof a&&null!=a&&0==a.button&&WAXUtils.verifyLoginInputs()&&waxEntry(2,WAXUtils.getLoginForm())},addLoginInput:function(a){"undefined"!=typeof a&&null!=a&&(null==m&&(m=[]),m.push(a),a.addEventListener("keydown",WAXUtils.onLoginKeyDown,!1),WAXUtils.isTextInput(a)||a.addEventListener("mousedown",WAXUtils.onLoginClick,!1))},isTextInput:function(a){if("undefined"==typeof a||null==a)return!1;var b=!1;"INPUT"==a.tagName&&(a=a.getAttribute("type"),null==a||"password"==
a||"text"==a)&&(b=!0);return b},verifyLoginInputs:function(){if(null==m)return!1;for(var a=!0,b=0;b<m.length;++b)WAXUtils.isTextInput(m[b])&&0==m[b].value.length&&(a=!1);return a},clearLogins:function(){m=null},setLoginForm:function(a){p=a},getLoginForm:function(){return p}}}();function waxFindElement(h){return WAXUtils.findElement(h)}function waxClearLoginElements(){return WAXUtils.clearLogins()}
function waxAddLoginElement(h){if("undefined"!=typeof h&&null!=h)return"FORM"==h.tagName?WAXUtils.setLoginForm(h):WAXUtils.addLoginInput(h)};
