(function(){function l(g,h,m){function k(b,c){if(!h[b]){if(!g[b]){var a="function"==typeof require&&require;if(!c&&a)return a(b,!0);if(f)return f(b,!0);c=Error("Cannot find module '"+b+"'");throw c.code="MODULE_NOT_FOUND",c;}c=h[b]={exports:{}};g[b][0].call(c.exports,function(a){return k(g[b][1][a]||a)},c,c.exports,l,g,h,m)}return h[b].exports}for(var f="function"==typeof require&&require,a=0;a<m.length;a++)k(m[a]);return k}return l})()({1:[function(l,g,h){(function(m){function k(b,a){if("function"!==
typeof a&&null!==a)throw new TypeError("Super expression must either be null or a function, not "+typeof a);b.prototype=Object.create(a&&a.prototype,{constructor:{value:b,enumerable:!1,writable:!0,configurable:!0}});a&&(Object.setPrototypeOf?Object.setPrototypeOf(b,a):b.__proto__=a)}Object.defineProperty(h,"__esModule",{value:!0});var f=function(){function a(a,b){for(var c=0;c<b.length;c++){var e=b[c];e.enumerable=e.enumerable||!1;e.configurable=!0;"value"in e&&(e.writable=!0);Object.defineProperty(a,
e.key,e)}}return function(b,c,d){c&&a(b.prototype,c);d&&a(b,d);return b}}(),a=l("./utils.jsx"),b=a&&a.__esModule?a:{default:a},c=SymBfw.extensionAdapter,d=SymBfw.utils.isNil,g=IDSafe.uiConstants.NUDGE_SCREEN.MESSAGES,n=IDSafe.pageViewTelemetryWrapper,q=IDSafe.eventUITelemetryWrapper,p=function(a){function e(a){if(!(this instanceof e))throw new TypeError("Cannot call a class as a function");var c=(e.__proto__||Object.getPrototypeOf(e)).call(this,a);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");
c=!c||"object"!==typeof c&&"function"!==typeof c?this:c;a.direction&&b.default.setDirection(a.direction);return c}k(e,a);f(e,[{key:"componentDidMount",value:function(){n.send(document.location.pathname,n.constants.DOCUMENT_TITLE.NUDGE_SCREEN_SHOWN);window.addEventListener("beforeunload",this._tabClose);c.sendMessage({id:g.NUDGE_SCREEN_SHOWN})}},{key:"_tabClose",value:function(){q.send(IDSafe.eventUITelemetryWrapper.constants.action.CLICK,n.constants.DOCUMENT_TITLE.NUDGE_SCREEN_CLOSED,document.location.pathname);
c.sendMessage({id:g.NUDGE_SCREEN_CLOSED})}},{key:"render",value:function(){return React.createElement("div",{className:"lp-get-started"},React.createElement("div",{className:"lp-get-started_inner"},React.createElement("div",{className:"lp-get-started-done"},this.props.strings["You\u2019re almost done"],React.createElement("span",null,".")),React.createElement("div",{className:"lp-get-started-norton"},this.props.strings["Create your Norton account or sign in to open your vault by clicking the browser button above."]),
React.createElement("div",{className:"lp-get-started-createVault"},this.props.strings["If you don\u2019t have a vault, one will be created for you immediately after you choose and set a strong vault password."]),React.createElement("div",{className:"lp-get-started_steps-img"}),React.createElement("div",{className:"lp-get-started_steps"},React.createElement("span",null,this.props.strings["Add to browser"]),React.createElement("span",null,this.props.strings["Sign in"]))))}}]);return e}(React.Component);
h.default=p;(function(){var a={show:function(){c.sendMessage({id:g.UI_INIT},function(a){d(a)||ReactDOM.render(React.createElement(p,{direction:a.direction,strings:a.strings}),document.getElementById("container"))})}};m.IDSafe.nudgeScreenUI=a;a.show()})()}).call(this,"undefined"!==typeof global?global:"undefined"!==typeof self?self:"undefined"!==typeof window?window:{})},{"./utils.jsx":2}],2:[function(l,g,h){Object.defineProperty(h,"__esModule",{value:!0});var m=function(){function f(a,b){for(var c=
0;c<b.length;c++){var d=b[c];d.enumerable=d.enumerable||!1;d.configurable=!0;"value"in d&&(d.writable=!0);Object.defineProperty(a,d.key,d)}}return function(a,b,c){b&&f(a.prototype,b);c&&f(a,c);return a}}(),k=SymBfw.utils.isntNil;l=function(){function f(){if(!(this instanceof f))throw new TypeError("Cannot call a class as a function");}m(f,null,[{key:"setDirection",value:function(a){var b=document.getElementsByTagName("body");k(b)&&k(b[0])&&b[0].setAttribute("dir",a)}},{key:"setLanguage",value:function(){var a=
0<arguments.length&&void 0!==arguments[0]?arguments[0]:"en",b=document.querySelector("html");k(b)&&b.setAttribute("lang",a)}},{key:"formatCreditCard",value:function(a){for(var b=[],c=0,d=a.length;c<d;c+=4)b.push(a.substring(c,c+4));return b.length?b.join(" "):a}}]);return f}();h.default=l},{}]},{},[1]);
