(function(d){d.NSSS.sb_bing=function(){var a={},m;a.initialize=function(){a.parsePage=function(){if(Utils){-1!==window.location.href.indexOf("livesearch.msn.co.kr")?(Utils.execSearchQuery("//div[@class='iePngFix']//li/dl/dt/a[(@class='a_blue') and (not(child::img))]"),Utils.execRightSponsQuery("//div[@id='news_side']//*[@id='news_side_list']/li/dl//dt/a[(@class='a_blue') and (not(child::img))]"),Utils.execTopBtmSponsQuery("//*[@id='overture_list']/li/dl/dt[@class='txt_inline']/a[@class='a_blue']",
"//*[@id='overture_list']/li/dl/dd[@class='txt_inline']"),gbKoreaSrchPage=!0):-1!==window.location.href.indexOf("bing.search.daum.net")?(Utils.execSearchQuery("//div[contains(@class,'collTot')]//li//span[@class='tit']/a[1][not(@class)]"),Utils.execSearchQuery("//div[contains(@class,'collTot')]//li//span[@class='fl']/a[1]"),Utils.execSearchQuery("//div[contains(@class,'collTot')]//table//td[contains(@class,'l_') or @class='txt']/a[1]"),Utils.execSearchQuery("//div[contains(@class,'collTot')]//dd[contains(@id,'vclip_DD')]//span[@class='tit']/a[1]"),
Utils.execSearchQuery("//div[contains(@class,'collTot')]//dd[@class='c_desc']//li[@class='t']/a[1]"),Utils.execSearchQuery("//div[contains(@class,'collTot')]//li//span[@class='tit']/a[contains(@class,'fL')]"),Utils.execSearchQuery("//div[contains(@class,'collTot')]//li//div[contains(@class,'dicObj')]/a[1]"),Utils.execTopBtmSponsQuery("//div[contains(@class,'collTotAd')]//ul/li/a[1]","//div[contains(@class,'collTotAd')]//ul/li/span[@class='url']/a"),Utils.execSearchQuery("//div[contains(@class,'collTot')]//span/a[not(child::img) and (@class='newsTit fL')]"),
Utils.execSearchQuery("//div[contains(@class,'collTot')]//li[not(@class)]//p[not(child::span)]/a[not(child::img)] ")):-1!==window.location.href.indexOf("www.bing.com/news/search")?(Utils.execSearchQuery("//div[contains(@class,'sn_r')]//div[contains(@class,'newstitle')]/a"),Utils.execSearchQuery("//div[contains(@class,'TextContainer entry-content')]/ul/li/a[not(child::img)]")):(Utils.execSearchQuery("//div[@id='results']//li//div[contains(@class,'lst')]//h3/a[not(child::img)]"),Utils.execSearchQuery("//ol[@id='b_results']//li[contains(@class,'b_algo') or contains(@class,'b_ans')]//h2//a[not(child::img)]"),
Utils.execSearchQuery("//*[@id='b_results']//li[contains(@class,'b_algo') or contains(@class,'b_ans') or contains(@class,'b_ad')]//*[contains(@class, 'b_deep')]//h3/a[not(child::img)]"),Utils.execRightSponsQuery("//div[starts-with(@class,'sb_adsN')]//li/div/h3/a|//div[starts-with(@class,'sb_adsN')]//li/a/h3","//div[starts-with(@class,'sb_adsN')]//li//cite"),Utils.execTopBtmSponsQuery("//div[contains(@class,'sb_adTA')]//h2/a","//div[contains(@class,'sb_adTA')]//div//cite"),Utils.execSearchQuery("//li[starts-with(@class,'b_ans')]//div[starts-with(@class,'b_rich')]//div[starts-with(@class,'mcd')]//h4/a[1]"),
Utils.execSearchQuery("//li[starts-with(@class,'b_ans')]//div[starts-with(@class,'b_rich')]//li//h5/a[1]"),Utils.execSearchQuery("//div[@class='sr_dcard' or @class='ec']//h3/a[not(child::img)]"),Utils.execSearchQuery("//div[starts-with(@class,'ans')]//h2[not(descendant::span)]/div/a[not(child::img)]"),Utils.execSearchQuery("//li[starts-with(@class, 'sb_ans')]//div[starts-with(@class,'ans')]//h2[not(descendant::span)]/a[not(child::img)]"),Utils.execSearchQuery("//div[starts-with(@class,'ans')]//h2[descendant::span]/div/a[not(child::img)]",
"align"),Utils.execSearchQuery("//div[(@class='vsa')or (@class='ans')]//h2/a[not(@class) and not(child::img)]"),Utils.execSearchQuery("//div[@id='sa_bop']//div[@class='ans3']//li[not(parent::div)]/a[not(child::img)]"),Utils.execSearchQuery("//div[starts-with(@class,'ans')or (@id='sa_bop')]//div[@class='sn_rct']//li//span/a[1]"),Utils.execTopBtmSponsQuery("//div[@id='results_container']/div[@class='sx_m']/h3[@class='sx_t']/span[@class='sx_b']/a","//div[@id='results_container']/div[@class='sx_m']/div[@class='sx_su']/cite"));
var a=Utils.getSearchText();0<a.length&&(m=Shasta.getPageDirection().toLowerCase());for(var e=0;e<a.length;e++){var l=Utils.getFormatLink(unescape(a[e]));Shasta.addURL(encodeURI(l))}}return!0};a.createAnnotation=function(){var a=navigator.userAgent.indexOf("Firefox"),e=Utils.getSearchFlags(),l=function(){return!1},d=function(b,d,f){var g=b.parentNode,h=b.nextSibling,k=!1;if(!0!==Utils.isAlreadyAnnotated(g)){h&&!0!==(3===h.nodeType&&!/\S/.test(h.nodeValue))||(k=!0);var c=document.createElement("a");
c.style.textDecoration="none";c.style.cursor="pointer";c.style.padding="0px";d.style.top="0px";c.style.display="inline";c.onclick=l;c.appendChild(d);b.style.display="inline";var n=!0;-1===a&&(n=!1,d.style.position="static",e[f].toLowerCase()===Utils.constants.NORMAL?(b.appendChild(document.createTextNode(" ")),b.appendChild(c)):"ltr"===m&&(c.style.position="relative"));if(e[f].toLowerCase()!==Utils.constants.NORMAL||!0===n)k?(g.appendChild(document.createTextNode(" ")),g.appendChild(c)):(g.insertBefore(document.createTextNode(" "),
h),g.insertBefore(c,h))}},f=[];Shasta.getPageDirection();f=Utils.getSearchNodes();for(var b=0;b<f.length;b++){var k=void 0;k=Utils.createImage(b);d(f[b],k,b)}return!0}};a.initialize();return a}()})(executionContext);
