var isIe=/MSIE [56789]/.test(navigator.userAgent)&&"Win32"==navigator.platform;
if(isIe){var _XPathMsxmlDocumentHelper=function(){function c(){document._propertyChangeDetected=!0}function a(d){if(d.dom)d.documentChangeDetected()&&(b=d.dom,b.load(""),h(b,b,document.body,d),d._currentElementCount=document.all.length,document._propertyChangeDetected=!1);else{var b=new ActiveXObject("Msxml2.DOMDocument");b.setProperty("SelectionLanguage","XPath");b.async=!1;b.resolveExternals=!1;h(b,b,document.body,d);d.dom=b;d._currentElementCount=document.all.length;document._propertyChangeDetected=
!1}}function h(d,b,a,k){var f=a.nodeName;if(!(-1<f.indexOf("/")||""==f||"#document"==f||"#document-fragment"==f||"#cdata-section"==f||"#xml-declaration"==f||"#whitespace"==f||"#significat-whitespace"==f||"#comment"==f||3==a.nodeType||a.getAttribute(lSbId)&&1!=document._SbReParse)){a.setAttribute(lSbId,a.uniqueID);f=a.nodeName.toLowerCase();f=d.createElement(f);b.appendChild(f);var e=a.id,g=a.className,l=a.getAttribute(lSbId);e&&(b=d.createAttribute("id"),b.value=e,f.setAttributeNode(b));g&&(b=d.createAttribute("class"),
b.value=g,f.setAttributeNode(b));l&&(b=d.createAttribute(lSbId),b.value=l,f.setAttributeNode(b));b=a.childNodes;e=0;b&&(e=b.length);for(g=0;g<e;g++)3!=b[g].nodeType&&"b"!=b[g].nodeName.toLowerCase()&&h(d,f,b[g],k);a.attachEvent("onpropertychange",c)}}this.getDom=function(){a(this);return this.dom};this.getXml=function(){a(this);return this.dom.xml};this.getTextResult=function(a){a=a.replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,'"');a='<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:output method="text"/><xsl:template match="*"><xsl:value-of select="'+
a+'"/></xsl:template></xsl:stylesheet>';var b=new ActiveXObject("Msxml2.DOMDocument");b.loadXML(a);try{var c=this.getDom().transformNode(b)}catch(k){}return c};this.reset=function(){this.dom=null};this.documentChangeDetected=function(){return document.ignoreDocumentChanges?!1:this._currentElementCount!=document.all.length||document._propertyChangeDetected}},XPathResult$0=function(c,a,h,d){function b(e){k(e);return e._textResult}function m(e,a){switch(a.nodeType){case 1:if(e=a.attributes.getNamedItem(lSbId))return document.getElementsByName(e.value)[0];
XPathException.Throw("unable to locate element in XML tree");case 2:if(e=a.selectSingleNode("..").attributes.getNamedItem(lSbId))if(e=document.getElementsByName(e.text))return e[0].attributes.getNamedItem(a.nodeName);XPathException.Throw("unable to locate attribute in XML tree");case 3:if(e=a.selectSingleNode("..").attributes.getNamedItem(lSbId))if(e=document.getElementsByName(e.value))for(child in e[0].childNodes)if(3==child.nodeType&&child.nodeValue==a.nodeValue)return child;XPathException.Throw("unable to locate text in XML tree")}XPathException.Throw("unknown node type")}
function k(e){if(!e._domResult)try{var a=e._expression.expressionString;e._contextNode!=document&&0!=a.indexOf("//")&&(a="//*[@id = '"+e._contextNode.id+"']"+(0==a.indexOf("/")?"":"/")+a);e._isNodeSet?e._domResult=document._XPathMsxmlDocumentHelper.getDom().selectNodes(a):(e._domResult=!0,e._textResult=document._XPathMsxmlDocumentHelper.getTextResult(a))}catch(l){XPathException.ThrowInvalidExpression(l.description)}}function f(a,b){k(a);return(b=a._domResult.item(b))?m(a,b):null}this.initialize=function(a,
b,c,d){this._domResult=null;this._expression=a;this._contextNode=b;this._resolver=c;d?(this.resultType=d,this._isIterator=d==XPathResult$0.UNORDERED_NODE_ITERATOR_TYPE||d==XPathResult$0.ORDERED_NODE_ITERATOR_TYPE||d==XPathResult$0.ANY_TYPE,this._isSnapshot=d==XPathResult$0.UNORDERED_SNAPSHOT_TYPE||d==XPathResult$0.ORDERED_SNAPSHOT_TYPE,this._isNodeSet=d>XPathResult$0.BOOLEAN_TYPE):(this.resultType=XPathResult$0.ANY_TYPE,this._isIterator=!0,this._isSnapshot=!1,this._isNodeSet=!0);return this};this.initialize(c,
a,h,d);this.getInvalidIteratorState=function(){return document._XPathMsxmlDocumentHelper.documentChangeDetected()||!this._isIterator};this.getSnapshotLength=function(){this._isSnapshot||XPathException.ThrowType("Snapshot is not an expected result type");k(this);return this._domResult.length};this.iterateNext=function(){this._isIterator||XPathException.ThrowType("Iterator is not an expected result type");k(this);document._XPathMsxmlDocumentHelper.documentChangeDetected()&&DOMException.ThrowInvalidState("iterateNext");
var a;a=(a=this._domResult.nextNode)?m(this,a):this._domResult=null;return a};this.snapshotItem=function(a){this._isSnapshot||XPathException.ThrowType("Snapshot is not an expected result type");return f(this,a)};this.toString=function(){return"[XPathResult]"};this.getStringValue=function(){this.resultType!=XPathResult$0.STRING_TYPE&&XPathException.ThrowType("The expression can not be converted to return String");return b(this)};this.getNumberValue=function(){this.resultType!=XPathResult$0.NUMBER_TYPE&&
XPathException.ThrowType("The expression can not be converted to return Number");var a=parseInt(b(this));isNaN(a)&&XPathException.ThrowType("The result can not be converted to Number");return a};this.getBooleanValue=function(){this.resultType!=XPathResult$0.BOOLEAN_TYPE&&XPathException.ThrowType("The expression can not be converted to return Boolean");var a=b(this);bool=a?a.toLowerCase():null;if("false"==bool||"true"==bool)return bool;XPathException.ThrowType("The result can not be converted to Boolean")};
this.getSingleNodeValue=function(){this.resultType!=XPathResult$0.ANY_UNORDERED_NODE_TYPE&&this.resultType!=XPathResult$0.FIRST_ORDERED_NODE_TYPE&&XPathException.ThrowType("The expression can not be converted to return single Node value");var a=f(this,0);this._domResult=null;return a}},XPathNSResolver=function(c){this.node=c;this.lookupNamespaceURI=function(a){XPathException.ThrowNotImplemented();return null};this.toString=function(){return"[XPathNSResolver]"}},XPathExpression=function(c,a){this.expressionString=
c;this.resolver=a;this.evaluate=function(c,d,b){return b&&b.constructor==XPathResult$0?b.initialize(this,c,a,d):new XPathResult$0(this,c,a,d)};this.toString=function(){return"[XPathExpression]"}},_DOMExceptionHandler=function(){this.ThrowInvalidState=function(c){c=Error(13,"DOM : The state of the object is no longer valid"+(c?', "'+c+'"':""));c.code=13;c.name="DOMException";throw c;}},_XPathExceptionHandler=function(){function c(a,c,d){c=Error(a,"DOM-L3-XPath "+document.DomL3XPathRelease+": "+c+(d?
', "'+d+'"':""));c.code=a;c.name="XPathException";throw c;}this.INVALID_EXPRESSION_ERR=51;this.TYPE_ERR=52;this.NOT_IMPLEMENTED_ERR=-1;this.RUNTIME_ERR=-2;this.ThrowNotImplemented=function(a){c(this.NOT_IMPLEMENTED_ERR,"This functionality is not implemented.",a)};this.ThrowInvalidExpression=function(a){c(this.INVALID_EXPRESSION_ERR,"Invalid expression",a)};this.ThrowType=function(a){c(this.TYPE_ERR,"Type error",a)};this.Throw=function(a){c(this.RUNTIME_ERR,"Run-time error",a)}},lSbId="sb_id";document.DomL3XPathRelease=
"0.0.3.0";document._SbReParse=0;var XPathException=new _XPathExceptionHandler,DOMException=new _DOMExceptionHandler;document.createExpression=function(c,a){return new XPathExpression(c,a)};document.createNSResolver=function(c){return new XPathNSResolver(c)};document.evaluate=function(c,a,h,d,b){return document.createExpression(c,h).evaluate(a,d,b)};XPathResult$0.ANY_TYPE=0;XPathResult$0.NUMBER_TYPE=1;XPathResult$0.STRING_TYPE=2;XPathResult$0.BOOLEAN_TYPE=3;XPathResult$0.UNORDERED_NODE_ITERATOR_TYPE=
4;XPathResult$0.ORDERED_NODE_ITERATOR_TYPE=5;XPathResult$0.UNORDERED_SNAPSHOT_TYPE=6;XPathResult$0.ORDERED_SNAPSHOT_TYPE=7;XPathResult$0.ANY_UNORDERED_NODE_TYPE=8;XPathResult$0.FIRST_ORDERED_NODE_TYPE=9;document.reloadDom=function(){document._XPathMsxmlDocumentHelper.reset()};document.sbReParse=function(){document._SbReParse=1};document._XPathMsxmlDocumentHelper=new _XPathMsxmlDocumentHelper}else document.reloadDom=function(){},document.sbReParse=function(){},XPathResult.prototype.getStringValue=
function(){return this.stringValue},XPathResult.prototype.getNumberValue=function(){return this.numberValue},XPathResult.prototype.getBooleanValue=function(){return this.booleanValue},XPathResult.prototype.getSingleNodeValue=function(){return this.singleNodeValue},XPathResult.prototype.getInvalidIteratorState=function(){return this.invalidIteratorState},XPathResult.prototype.getSnapshotLength=function(){return this.snapshotLength},XPathResult.prototype.getResultType=function(){return this.resultType};
