// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 7);
user_pref("app.normandy.startupRolloutPrefs.services.sync.bookmarks.buffer", true);
user_pref("app.normandy.user_id", "add34bbe-6237-4d17-89cf-993f65684e88");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1573700367);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1573700487);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 4977);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1573700262);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 87);
user_pref("browser.newtabpage.activity-stream.impressionId", "{9d5c64fd-352c-46cc-8916-7d6b60930c86}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1573700377919");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1573702202919");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1573700266004");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1573703866004");
user_pref("browser.search.region", "JP");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20191031085722");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1573700337");
user_pref("browser.slowStartup.averageTime", 1281);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20191031085722");
user_pref("browser.startup.homepage_override.mstone", "70.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1573700337);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1573700264575");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "70.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "a428c582d0c34dc7968563da3f74a5cf");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20191031085722");
user_pref("extensions.lastAppVersion", "70.0.1");
user_pref("extensions.lastPlatformVersion", "70.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"c33ed50c-6748-4821-be8d-705a4e05eafb\",\"screenshots@mozilla.org\":\"f58c3f24-18bb-4c65-93e5-c38f0207e624\",\"webcompat-reporter@mozilla.org\":\"564bb3ed-d85c-43a2-9efe-253ad6de41a6\",\"webcompat@mozilla.org\":\"660bad18-b920-4797-98fe-c78591e8743b\",\"default-theme@mozilla.org\":\"b280c775-aeab-4958-8758-7ffdc7bb5744\",\"google@search.mozilla.org\":\"67151fa8-ce3b-47c0-af13-b47fda0941af\",\"yahoo-jp@search.mozilla.org\":\"26b6a095-7b98-4c9b-aa61-c73f3d15e7fb\",\"bing@search.mozilla.org\":\"fabd7747-140a-4cac-8d3e-8da4a6225a07\",\"amazon@search.mozilla.org\":\"d58c6008-5209-4ded-87b8-6340a80c1816\",\"rakuten@search.mozilla.org\":\"8518604c-fe41-4e0c-b3d0-431928ca219c\",\"yahoo-jp-auctions@search.mozilla.org\":\"4500dfaf-f847-448b-911e-89699ec75bec\",\"oshiete-goo@search.mozilla.org\":\"13420b6b-de9f-4ea6-b9a8-a464648f3f44\",\"twitter@search.mozilla.org\":\"7b5675cb-c9e8-4061-8762-055f235a300f\",\"wikipedia@search.mozilla.org\":\"57549717-adff-4598-87d8-8b67ac0949f6\",\"ddg@search.mozilla.org\":\"df55a259-3730-4f0e-82ae-28d90addcafe\"}");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1573700428);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20191031085722");
user_pref("media.gmp-manager.lastCheck", 1573700426);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "16915bd8-98eb-41d9-8bfc-47c41b0e481e");
user_pref("security.sandbox.plugin.tempDirSuffix", "5b6c1cb1-16d6-4b91-be04-afc79a8c6c54");
user_pref("services.blocklist.pinning.checked", 1573700426);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1573689608411\"");
user_pref("services.settings.last_update_seconds", 1573700426);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1573700426);
user_pref("services.settings.main.cfr-fxa.last_check", 1573700426);
user_pref("services.settings.main.cfr.last_check", 1573700426);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1573700426);
user_pref("services.settings.main.hijack-blocklists.last_check", 1573700426);
user_pref("services.settings.main.language-dictionaries.last_check", 1573700426);
user_pref("services.settings.main.normandy-recipes.last_check", 1573700426);
user_pref("services.settings.main.public-suffix-list.last_check", 1573700426);
user_pref("services.settings.main.sites-classification.last_check", 1573700426);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1573700426);
user_pref("services.settings.main.whats-new-panel.last_check", 1573700426);
user_pref("services.settings.security.onecrl.checked", 1573700426);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1573700336);
user_pref("toolkit.telemetry.cachedClientID", "1f293339-2fa8-444e-9f25-6130c8e31102");
user_pref("toolkit.telemetry.previousBuildID", "20191031085722");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
