(function e$jscomp$0(l,m,h){function n(g,e){if(!m[g]){if(!l[g]){var p="function"==typeof require&&require;if(!e&&p)return p(g,!0);if(b)return b(g,!0);e=Error("Cannot find module '"+g+"'");throw e.code="MODULE_NOT_FOUND",e;}e=m[g]={exports:{}};l[g][0].call(e.exports,function(d){var a=l[g][1][d];return n(a?a:d)},e,e.exports,e$jscomp$0,l,m,h)}return m[g].exports}for(var b="function"==typeof require&&require,k=0;k<h.length;k++)n(h[k]);return n})({1:[function(l,m,h){function q(b,d){if("function"!==typeof d&&
null!==d)throw new TypeError("Super expression must either be null or a function, not "+typeof d);b.prototype=Object.create(d&&d.prototype,{constructor:{value:b,enumerable:!1,writable:!0,configurable:!0}});d&&(Object.setPrototypeOf?Object.setPrototypeOf(b,d):b.__proto__=d)}Object.defineProperty(h,"__esModule",{value:!0});var n=function(){function b(d,a){for(var c=0;c<a.length;c++){var b=a[c];b.enumerable=b.enumerable||!1;b.configurable=!0;"value"in b&&(b.writable=!0);Object.defineProperty(d,b.key,
b)}}return function(d,a,c){a&&b(d.prototype,a);c&&b(d,c);return d}}(),b=SymBfw.constants.uiConstants.NOTIFICATION,k=SymBfw.utils.isntNil,g=SymBfw.extensionAdapter,e=function(e){function d(a){if(!(this instanceof d))throw new TypeError("Cannot call a class as a function");var c=(d.__proto__||Object.getPrototypeOf(d)).call(this,a);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");c=!c||"object"!==typeof c&&"function"!==typeof c?this:c;c.state={notifications:a.notifications};
a.direction&&c.setDirection(a.direction);return c}q(d,e);n(d,[{key:"setDirection",value:function(a){var c=document.getElementsByTagName("body");k(c)&&k(c[0])&&c[0].setAttribute("dir",a)}},{key:"sendMessage",value:function(a,c){g.sendMessage({id:b.MESSAGES.DEFAULT_MESSAGE,payload:{eventID:c,notificationID:a}})}},{key:"onCloseClicked",value:function(a,c){this.sendMessage(a,b.MESSAGES.NOTIFICATION_CLOSED)}},{key:"onDefaultButtonClicked",value:function(a,c){this.sendMessage(a,b.MESSAGES.DEFAULT_BUTTON_PRESSED)}},
{key:"onSecondaryLinkClicked",value:function(a,c){this.sendMessage(a,b.MESSAGES.SECONDARY_LINK_PRESSED)}},{key:"onThirdButtonClicked",value:function(a,c){this.sendMessage(a,b.MESSAGES.THIRD_BUTTON_PRESSED)}},{key:"closeNotification",value:function(a){var c=this.state.notifications;c.splice(a,1);this.setState({notifications:c})}},{key:"getIconStyle",value:function(a){var c={};c.backgroundImage="url(../../"+a+")";return c}},{key:"getNotifications",value:function(){for(var a=[],c=b.STACK_COUNT,d=[],
e=0;(e<c||0===a.length)&&e<this.state.notifications.length;e++){var f=this.state.notifications[e];if(!1!==f.isAllowed){var h=f.notificationID;d.push(h);var k="notify";switch(f.type){case b.TYPE.QUESTION:k+=" actionable"}a.push(React.createElement("div",{key:h},React.createElement("div",{className:k},React.createElement("div",{className:"icon-close",onClick:this.onCloseClicked.bind(this,h,e)}),React.createElement("div",{className:"notification-message-content"},React.createElement("div",{className:"icon good-image",
style:this.getIconStyle(f.imageUrl)}),React.createElement("div",{className:"message-container"},f.title?React.createElement("div",{className:"title"},f.title):null,React.createElement("div",{className:"message"},f.description),React.createElement("div",{className:"extra-message"},React.createElement("div",{className:"line1"},f.line1),React.createElement("div",{className:"line2"},f.line2)))),React.createElement("div",{className:"actions"},f.secondaryLink?React.createElement("div",{className:"dont-ask",
onClick:this.onSecondaryLinkClicked.bind(this,h,e)},f.secondaryLink):null,f.defaultButton?React.createElement("div",{className:"action-button",onClick:this.onDefaultButtonClicked.bind(this,h,e)},f.defaultButton):null,f.thirdButton?React.createElement("div",{className:"third-action-button",onClick:this.onThirdButtonClicked.bind(this,h,e)},f.thirdButton):null)),React.createElement("div",{className:"divider"})))}}g.sendMessage({id:b.MESSAGES.DEFAULT_MESSAGE,payload:{eventID:b.MESSAGES.NOTIFICATIONS_SHOWN,
notificationArray:d}});return a}},{key:"render",value:function(){var a=this.getNotifications();return 0===a.length?(g.sendMessage({id:b.MESSAGES.DEFAULT_MESSAGE,payload:{eventID:b.MESSAGES.HIDE_NOTIFICATIONS}}),null):React.createElement("div",{className:"notify-center"},a)}}]);return d}(React.Component);h.default=e;g.sendMessage({id:b.MESSAGES.UI_INIT},function(b){ReactDOM.render(React.createElement(e,{notifications:b.notifications,direction:b.direction}),document.getElementById("container"))})},
{}]},{},[1]);
