var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var d=0;return function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,c){a!=Array.prototype&&a!=Object.prototype&&(a[d]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,d){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:d})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(c||"")+"_"+d++,c)}var d=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.iteratorFromArray=function(a,d){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,b={next:function(){if(c<a.length){var e=c++;return{value:d(e,a[e]),done:!1}}b.next=function(){return{done:!0,value:void 0}};return b.next()}};b[Symbol.iterator]=function(){return b};return b};
$jscomp.polyfill=function(a,d,c,b){if(d){c=$jscomp.global;a=a.split(".");for(b=0;b<a.length-1;b++){var e=a[b];e in c||(c[e]={});c=c[e]}a=a[a.length-1];b=c[a];d=d(b);d!=b&&null!=d&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:d})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
(function(a){(a.NSSS=a.NSSS||{}).nfmUI=function(a,c){var b={replaceString:{nortonRating:"NORTON_RATING",computerThreats:"COMPUTER_THREATS",identityThreats:"IDENTITY_THREATS",annoyanceThreats:"ANNOYANCE_THREATS",totalThreats:"TOTAL_THREATS",fullReport:"FULL_REPORT",reportSite:"REPORT_SITE",nortonSafeWeb:"NORTON_SAFEWEB"}},d=b.replaceString,h=a.extensionAdapter,f=c.uiHelper,k=f.ratingStyle;b.replaceStrings=function(a){var b=$("div#placeholder").html();if(null!==b&&"undefined"!==typeof b){var g=Object.keys(d),
c;$("#searchbox").attr("placeholder",a.search);for(c=0;c<g.length;c++)a.rating[g[c]]&&(b=b.replace(d[g[c]],a.rating[g[c]]));$("div#placeholder").replaceWith(b)}};b.fillValues=function(a){$("#searchbox").val("");$("#rating").attr("rating",k[a.rating]);$("#ratingtext").text(a.ratingText);$("#compthreats").text(a.computerThreats);$("#idthreats").text(a.identityThreats);$("#annoythreats").text(a.annoyanceThreats);$("#totalthreats").text(a.totalThreats);$("#sitename").text(a.sitename);$("#reportsite").hide();
!0===a.showSafeWebSearchbox?$("div#safesearchbox").show():($("div#safesearchbox").hide(),$("#sitename").css("padding-top","7px"),$("#sitename").css("padding-bottom","5px"));b.browserAdjustments(a.showSafeWebSearchbox)};b.showUILinks=function(a,b){a?$("span#fullreport").show():$("span#fullreport").hide();b?$("span#reportsite").show():$("span#reportsite").hide()};b.showResults=function(){$("#placeholder").show();$("span#fullreport").click(function(a){null!==b.browserCallback&&"undefined"!==typeof b.browserCallback&&
(b.browserCallback(f.FULL_REPORT_EVENTID,null),b.closePopup())});$("span#reportsite").click(function(a){null!==b.browserCallback&&"undefined"!==typeof b.browserCallback&&b.browserCallback(f.REPORTSITE_EVENTID,null);$("span#reportsite").hide()});$("div#settings").click(function(a){null!==b.browserCallback&&"undefined"!==typeof b.browserCallback&&(b.closePopup(),b.browserCallback(f.SETTINGS_CLICKED_EVENTID,null))});$("input#searchbox").click(function(a){a.pageX-$(this).position().left>$(this).width()&&
($(this).val(""),$(this).addClass("hide-bg"))});$("input#searchbox").on("mouseover mousemove",function(a){a.pageX-$(this).position().left>$(this).width()&&$(this).val()?$(this).css("cursor","pointer"):$(this).css("cursor","text")});$("input#searchbox").keyup(function(a){$(this).val()?$(this).removeClass("hide-bg"):$(this).addClass("hide-bg");13===a.keyCode&&$("div#searchbutton").click()});$("div#searchbutton").click(function(a){(a=$("input#searchbox").val())&&null!==b.browserCallback&&"undefined"!==
typeof b.browserCallback&&(b.browserCallback(f.SEARCH_EVENTID,a),b.closePopup())})};b.closePopup=function(){setTimeout(function(){h.hidePopup()},50)};return b}(a.SymBfw,a.NSSS)})(executionContext);
