var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,g){a!=Array.prototype&&a!=Object.prototype&&(a[b]=g.value)};
$jscomp.polyfill=function(a,b,g,c){if(b){g=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var k=a[c];k in g||(g[k]={});g=g[k]}a=a[a.length-1];c=g[a];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(g,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function g(a){return a instanceof k?a:new k(function(b,c){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var c=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){c(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];a[b]=null;try{c()}catch(F){this.asyncThrow_(F)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var k=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(E){b.reject(E)}};k.prototype.createResolveAndReject_=function(){function a(a){return function(g){c||(c=!0,a.call(b,g))}}var b=this,c=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};k.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof k)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};k.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(E){this.reject_(E);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};k.prototype.reject_=function(a){this.settle_(2,a)};k.prototype.fulfill_=function(a){this.settle_(1,a)};k.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};k.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)l.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var l=new b;k.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};k.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(F){c.reject(F)}};k.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{g(a(b))}catch(N){l(N)}}:b}var g,l,v=new k(function(a,b){g=a;l=b});this.callWhenSettled_(c(a,g),c(b,l));return v};
k.prototype.catch=function(a){return this.then(void 0,a)};k.prototype.callWhenSettled_=function(a,b){function c(){switch(g.state_){case 1:a(g.result_);break;case 2:b(g.result_);break;default:throw Error("Unexpected state: "+g.state_);}}var g=this;null==this.onSettledCallbacks_?l.asyncExecute(c):this.onSettledCallbacks_.push(c)};k.resolve=g;k.reject=function(a){return new k(function(b,c){c(a)})};k.race=function(a){return new k(function(b,c){for(var k=$jscomp.makeIterator(a),l=k.next();!l.done;l=k.next())g(l.value).callWhenSettled_(b,
c)})};k.all=function(a){var b=$jscomp.makeIterator(a),c=b.next();return c.done?g([]):new k(function(a,k){function l(b){return function(c){e[b]=c;p--;0==p&&a(e)}}var e=[],p=0;do e.push(void 0),p++,g(c.value).callWhenSettled_(l(e.length-1),k),c=b.next();while(!c.done)})};return k},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(g){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(g||"")+"_"+b++,g)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(g){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var g=a.next();$jscomp.generator.ensureIteratorResultIsObject_(g);if(g.done)this.yieldResult=g.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(g.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,g){g?this.finallyContexts_[g]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,g){try{var c=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(c);if(!c.done)return this.context_.stop_(),c;var k=c.value}catch(l){return this.context_.yieldAllIterator_=null,this.context_.throw_(l),this.nextStep_()}this.context_.yieldAllIterator_=null;g.call(this.context_,k);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(b){return a.next(b)}function g(b){return a.throw(b)}return new Promise(function(c,k){function l(a){a.done?c(a.value):Promise.resolve(a.value).then(b,g).then(l,k)}l(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};$jscomp.assign="function"==typeof Object.assign?Object.assign:function(a,b){for(var g=1;g<arguments.length;g++){var c=arguments[g];if(c)for(var k in c)$jscomp.owns(c,k)&&(a[k]=c[k])}return a};$jscomp.polyfill("Object.assign",function(a){return a||$jscomp.assign},"es6","es3");$jscomp.polyfill("Object.is",function(a){return a?a:function(a,g){return a===g?0!==a||1/a===1/g:a!==a&&g!==g}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,g){var b=this;b instanceof String&&(b=String(b));var k=b.length;g=g||0;for(0>g&&(g=Math.max(g+k,0));g<k;g++){var l=b[g];if(l===a||Object.is(l,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,b,g){if(null==a)throw new TypeError("The 'this' value for String.prototype."+g+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+g+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,g){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,g||0)}},"es6","es3");
(function(a){a.IDSafe.chromeGlobal=function(b,g,c){var k=b.logger,l=b.utils.isNil,v=b.utils.isntNil,da=b.utils.isString,E=b.utils.isFunction,F=c.session,A=c.vaultManager,H=c.uiService,e={},p=c.uiConstants,M=p.LOGIN_UNLOCK.messages,N=p.NO_VAULT.MESSAGES,ea=p.NO_VAULT.STRINGS,I=p.VAULT_UNLOCK.MESSAGES,fa=p.VAULT_UNLOCK.STRINGS,W=p.CREATE_VAULT.messages,ha=p.CREATE_VAULT.STRINGS,ia=p.SETTINGS.strings,O=p.SETTINGS.MESSAGES,X=p.PASSWORD_GENERATOR.MESSAGES,ja=b.utils.isNewVersionUpdated,u=p.MESSAGES,x=
p.POPUP.MESSAGES,D=p.BROWSER_ACTION_POPUP.MESSAGES,z=c.signIn,P=c.loginUnlock,ka=g.authSCD,n=c.constants,J=c.mainUI,K=b.notificationCenter,B=b.utils.baseURL,la=b.utils.urlWithoutQueryParameters,Q=c.settings,y=c.globalSettings,t=b.localizer,h=b.extensionAdapter,R=b.utils.getDomain,Y=c.vaultUnlockSettings,ma=p.SETUP_VAULT.STRINGS,na=p.SETUP_VAULT.MESSAGES,oa=p.DELETE_VAULT.STRINGS,T=p.DELETE_VAULT.MESSAGES,L=p.CHANGE_PASSWORD.MESSAGES,pa=p.CHANGE_PASSWORD.STRINGS,Z=c.constants.VAULT_UNLOCK.RESPONSE_STATUS,
aa=b.telemetryConstants,ba=p.NUDGE_SCREEN,qa=ba.STRINGS,S=ba.MESSAGES,U=0,V=0;e.partialSubmissions={};e.tabID=null;var G=c.fillCaptureHandler,ca=b.utils.createNewGuid();e.signInPopupURLExclusionList=[ka.SSO_OPENID_CONNECT_LOGIN_URL];e.captureExclusionList=[];e.mutationObserverExclusionList=["wellsfargo.com"];e.waxProcessingExclusionList=[n.ONBOARDING_URL_IDENTITY,n.ONBOARDING_URL_SEARCHSAFE,n.ONBOARDING_URL_SEARCH];e.getVaultItemById=function(a,b,e,g){if(l(a))throw Error("managerItem cannot be null");
if(l(b))throw Error("ItemID cannot be null");if(l(e))throw Error("sender (TAB)object cannot be null");if(l(g))throw Error("callback function cannot be null");var f=A.getItemManager(a).getItem(b);a=h.getTabID(e);e=h.getWindowIDForTab(e);Q.getRequireVaultPassword()||f.getSecure()?c.verifyPasswordRequest.beginOrContinueVerifyVaultPasswordFlow(a,e,function(a){var b=null;!0===a&&(b=JSON.parse(f.serializeNode(!1,!1)));g(b)}):g(JSON.parse(f.serializeNode(!1,!1)))};e.updateLoginFavorite=function(a,b){var c=
A.getItemManager(A.constructor.LOGIN_MANAGER);a=c.getItem(a);l(a)||(a.setFavorite(b),a.setLastUpdate((new Date).getTime()/1E3),c.updateItem(a,!0),k.info("Marked login "+B(a.loginURL)+" with favorite = "+b))};e.handleWindowFocusChange=function(a){K.handleActivate()};e.isUrlExcludedForSignInPopup=function(a){for(var b in e.signInPopupURLExclusionList)if(B(a)===B(e.signInPopupURLExclusionList[b]))return!0;return!1};e.canShowSignInPopup=function(a,b,c){if(!da(a))throw Error("The URL should a string");
if(l(b))throw Error("The tabId cannot be Nil");if(!E(c))throw Error("sendResponse should be a function");a=z.isSignInTab(b)&&e.isUrlExcludedForSignInPopup(a)?!0:y.getValue(n.DONT_ASK_SIGN_IN_AGAIN);c({canShow:!a})};e.closeInPagePopup=function(a){h.sendMessageToTab(a,{id:x.POPUP_CLOSE})};e.handleActivate=function(a){K.handleActivate()};e.handlePagePopupMessage=function(a,b,g,k,l){b=a.payload;h.getTabID(g);switch(a.id){case x.POPUP_SIGNIN_CLICKED:c.vaultUnlockManager.automaticMobileUnlockRequest=!1;
z.openLoginFlow();e.closeInPagePopup(g);break;case x.POPUP_DONT_ASK_ME_AGAIN_CLICKED:y.setValue(n.DONT_ASK_SIGN_IN_AGAIN,!0);e.closeInPagePopup(g);break;case x.POPUP_MISC_OPTIONS_EULA_CLICKED:J.openEula();e.closeInPagePopup(g);break;case x.SHOW_INPAGE_POPUP_ON_TOP_FRAME:h.sendMessageToParentFrame(g,{id:x.SHOW_INPAGE_POPUP_ON_TOP_FRAME_BG,payload:b},null,k);break;case x.ITEM_SELECTED_INPAGE_POPUP_ON_TOP_FRAME:h.sendMessageToTab(g,{id:x.ITEM_SELECTED_INPAGE_POPUP_ON_TOP_FRAME_BG,payload:b})}};e.sendVaultStatus=
function(a,f,g){a.state===A.constructor.state.CLIENT_UNAUTHORIZED?(V++,g({status:!1,maxRetryCountExceed:3<=V})):a.state===A.constructor.state.VAULT_SYNCED&&(HeartbeatSDK.hbRecurrentPingManager.start(n.HEARTBEAT.ACTIVE_VAULT_USERS),v(c.vaultUnlockManager.notificationID)&&b.notificationCenter.removeNotification(c.vaultUnlockManager.notificationID),g({status:!0,state:A.constructor.state.VAULT_SYNCED}),G.handleUnlockVaultSuccess().catch(function(a){return k.info(a)}),y.getOpenVaultUI()&&c.vaultUnlockManager.openVaultTabUI?
!0===c.vaultTabUI.controller.isImportDiscontinueFlow?c.vaultTabUI.controller.showImportModal():c.vaultTabUI.controller.openVaultTabUI():(!0===c.vaultTabUI.controller.isImportDiscontinueFlow&&c.vaultTabUI.controller.showImportModal(),v(e.tabID)&&z.changeTabFocus(e.tabID)),!1===y.getOpenVaultUI()&&0<c.vaultUnlockSettings.getUnlockNotificationCount()&&!1===c.vaultUnlockSettings.getIsSplashScreenShown()&&c.vaultUnlockManager.showMobileUnlockNotification(Z.UNLOCK_WELCOME),H.setBrowserActionIcon(!0),h.getAllTabs(function(a){a.forEach(function(a){var b=
h.getTabID(a);h.sendMessageToTab(a,{id:u.VAULT_LOGGEDIN,payload:{tabId:b}})})}))};e.handleMessage=function(m,f,q,C){var r=m.id,d=m.payload,w=h.getTabID(q);e.tabID=w;switch(r){case u.VAULT_ISLOGGEDIN:f(c.vaultKeys.isLocked());break;case I.UNLOCK_VAULT:return c.vaultKeys.setUnlockUsingMobileFlag(!1),d=b.utils.obfuscatePassword(m.payload.password,ca),F.openVault(d,function(a,b){e.sendVaultStatus(a,b,f)}),!0;case I.SIGNOUT_OF_NA:return F.logoutNA(function(a,b){z.removeSignInTab(I.SIGNOUT_OF_NA);h.getAllTabs(function(a){a.forEach(function(a){var b=
h.getTabID(a);a.url===h.getExtensionURL("content/ui/vault-unlock.html")||a.url===h.getExtensionURL("content/ui/settings.html")||a.url===h.getExtensionURL("content/ui/no-vault.html")||a.url===h.getExtensionURL("content/ui/change-vault-password.html")?h.closeTab(b):h.sendMessageToTab(a,{id:u.NA_LOGGEDOUT,payload:{tabId:b}})})});H.setBrowserActionIcon(!1)}),!0;case u.LAUNCH_DELETE_VAULT_FLOW:return F.logoutNA(function(a,b){a?(HeartbeatSDK.hbRecurrentPingManager.stop(n.HEARTBEAT.ACTIVE_VAULT_USERS),e._closeExistingIDSTabs(),
e.isDeleteVaultFlow=!0,H.setBrowserActionIcon(!1),z.resetContainer(),z.openLoginFlow(e.isDeleteVaultFlow)):h.closeTab(w)}),!0;case T.CALL_DELETE_VAULT_API:a.IDSafe.vaultManager.deleteVault(function(a){k.info("extensionAdapter.sendMessage(CALL_DELETE_VAULT_API) - response - State= "+a.state+" - additionalInfo= "+a.additionalInfo);if(c.vaultManager.constructor.state.VAULT_DELETED!==a.state){var f=t.getLocalizedString("Sorry, something went wrong. Please try again."),d=t.getLocalizedString("__LONG_PRODUCT_NAME__");
f=new b.TimedNotification(f,c.notificationIcon.getErrorIcon(),d);b.notificationCenter.addNotification(f);c.telemetryWrapper.deleteVaultFailure(a.state,a.additionalInfo);h.closeTab(w)}else c.telemetryWrapper.deleteVaultSuccess(),v(Y.getRegisteredDevice())&&Y.removeNAGuidSettings(),h.getAllTabs(function(a){a.forEach(function(a){v(a)&&v(a.url)&&a.url===h.getExtensionURL(p.DELETE_VAULT.HTML)&&h.sendMessageToTab(a,{id:T.DELETE_VAULT_API_SUCCESS})})})});break;case L.CALL_CHANGE_VAULT_PASSWORD_API:d=m.payload;
a.IDSafe.vaultManager.changeVaultPassword(d.current_password,d.new_password,d.new_hint,function(a){k.info("extensionAdapter.sendMessage(CALL_CHANGE_VAULT_PASSWORD_API) - response - State= "+a.state+" - additionalInfo= "+a.additionalInfo);if(c.vaultManager.constructor.state.VAULT_PASSWORD_CHANGED===a.state)h.getTab(h.getTabID(q),function(a){h.sendMessageToTab(a,{id:L.CHANGE_VAULT_PASSWORD_API_SUCCESS})}),c.telemetryWrapper.changeVaultPasswordSuccess();else{c.statusReporter.reportVaultState(a.getState());
var b=h.getTabID(q);c.telemetryWrapper.changeVaultPasswordFailure(a.state,a.additionalInfo);h.closeTab(b)}});break;case L.VALIDATE_PREVIOUS_VAULT_PASSWORD:return c.vaultKeys.compareWithVaultPassword(m.payload.password,function(a){f({status:a})}),!0;case L.UPDATE_SETTINGS_URL:c.vaultTabUI.controller.showSettingsModal();break;case L.UI_INIT:d={};d.direction=b.localizer.getCurrentLanguageDirection();d.strings=b.localizer.getLocalizedStrings(pa);d.passwordHint=c.appNode.getPasswordHint();d.email=g.session.getEmail();
if(c.vaultKeys.isLocked())break;f(d);break;case W.CALL_CREATE_VAULT_API:a.IDSafe.vaultManager.createVault(d.password,d.hint,function(a){k.info("extensionAdapter.sendMessage(CALL_CREATE_VAULT_API) - response - State= "+a.state+" - additionalInfo= "+a.additionalInfo);if(c.vaultManager.constructor.state.VAULT_CREATED!==a.state){var f=t.getLocalizedString("Sorry, something went wrong. Please try again."),d=t.getLocalizedString("__LONG_PRODUCT_NAME__");f=new b.TimedNotification(f,c.notificationIcon.getErrorIcon(),
d);b.notificationCenter.addNotification(f);h.closeTab(w);c.telemetryWrapper.createVaultFailure(a.state,a.additionalInfo)}else{HeartbeatSDK.hbRecurrentPingManager.start(n.HEARTBEAT.ACTIVE_VAULT_USERS);a=h.getExtensionURL(c.uiConstants.CREATE_VAULT.SETUP_COMPLETE_PAGE_HTML);var e=h.getTabID(q);h.updateTabUrl(e,a,function(){setTimeout(function(){G.handleUnlockVaultSuccess().then(function(){setTimeout(function(){h.closeTabAndEnsureBrowserIsAlive(e,function(){})},1E3)}).catch(function(a){return k.info(a)})},
5E3)});c.compromisedPasswordHelper.isCompromisedPasswordFlowInProgress()?c.telemetryWrapper.createVaultSuccess({key:b.telemetryConstants.parameters.CUSTOM_DIMENSION4,value:"mot"}):c.telemetryWrapper.createVaultSuccess()}});break;case W.CREATE_VAULT_FLOW_INIT:var x={};x.direction=b.localizer.getCurrentLanguageDirection();x.strings=b.localizer.getLocalizedStrings(ha);x.email=g.session.getEmail();F.doesVaultExist(function(a,b,c){v(c)||(x.isVaultExists=a);f(x)});return!0;case I.UI_INIT:d={};V=0;d.direction=
b.localizer.getCurrentLanguageDirection();d.strings=b.localizer.getLocalizedStrings(fa);d.passwordHint=c.appNode.getPasswordHint();d.email=g.session.getEmail();d.obfuscationKey=ca;d.openVaultUI=y.getOpenVaultUI();f(d);break;case I.SET_OPEN_VAULT_UI:y.setOpenVaultUI(d);break;case u.VAULT_GET_LOGINS_BY_URL:m=d.ignoreHttp;C=R(q.url).toLowerCase();r=null;B(q.url)===n.FG_ISOLATION_URL_DOMAIN?r=d.srcAttribute:(d=R(d.srcAttribute).toLowerCase(),r=C===d?q.url:null);if(l(r)){k.info("Url is null");f(null);
break}G.getLoginsByUrl(r,w,function(a,b){v(b)&&k.error(b);f(a)},m);return!0;case u.VAULT_GET_LOGIN_BY_ID:return e.getVaultItemById(A.constructor.LOGIN_MANAGER,d.id,q,function(a){f(a)}),!0;case u.VAULT_GET_CARD_BY_ID:return e.getVaultItemById(A.constructor.CREDIT_CARD_MANAGER,d.id,q,function(a){f(a)}),!0;case u.VAULT_GET_CARD_ITEMS:return m=d.ignoreHttp,d=G.getCardItems(q.url,m),(l(d)||0===d.length)&&k.error("returned empty card list"),f(d),!0;case u.VAULT_PROCESS_LOGIN_FORM_SUBMISSION:if(l(d)||l(d.loginInfo)||
l(d.senderURL))break;C=R(q.url).toLowerCase();m=d.isIsolationURL;r=null;B(q.url)===n.FG_ISOLATION_URL_DOMAIN?r=d.senderURL:(r=R(d.senderURL).toLowerCase(),r=C===r?q.url:null);if(l(r))break;C=la(r);r=B(r);d.loginInfo.loginURL=C;d.loginInfo.siteName=r;e.isUrlInList(e.captureExclusionList,r)?k.debug("IDSafeWAX: skipping URL: "+d.loginInfo.url):(c.telemetryWrapper.sendWaxFormSubmit(r,c.telemetryWrapper.WAX_FORMSUBMIT_VALUE.MANUAL,m),G.processLoginFormSubmission(d.loginInfo,w).catch(function(a){return k.error(a)}));
break;case u.GET_SANDBOX_INFORMATION:h.sendMessageToParentFrame(q,{id:u.GET_SANDBOX_INFORMATION_CS,payload:d},null,C);break;case u.CAN_SHOW_SIGNIN_POPUP:e.canShowSignInPopup(q.url,w,f);break;case u.IS_URL_EXCLUDED_FROM_WAX:f(e.isUrlExcluded(B(q.url)));break;case u.IS_URL_EXCLUDED_FROM_CAPTURE:f(e.isUrlInList(e.captureExclusionList,B(q.url)));break;case u.IS_URL_EXCLUDED_FROM_ADDING_MUTATION_OBSERVER:f(e.isUrlInList(e.mutationObserverExclusionList,B(q.url)));break;case u.CLOSE_CURRENT_TAB:h.closeTab(w);
b.utils.createCustomHTMLEvent(n.IDSAFE_CLOSED_TAB,{tabId:w});break;case M.UI_INIT:d={};U=0;d.direction=b.localizer.getCurrentLanguageDirection();d.strings=b.localizer.getLocalizedStrings(p.LOGIN_UNLOCK.strings);d.passwordHint=c.appNode.getPasswordHint();d.email=g.session.getEmail();f(d);break;case M.UNLOCK_LOGIN:var E=P.getLoginIdFromLoginUnlockPage(w);if(l(E)){h.closeTab(w);break}var K=P.getParentTabId(w);if(l(K))break;c.vaultKeys.compareWithVaultPassword(m.payload.password,function(a){a?(f({status:a}),
h.closeTab(w),h.getTab(K,function(a){l(a)||h.sendMessageToTab(a,{id:M.LOGIN_UNLOCKED,payload:{loginId:E}})})):(U++,a=3<=U,a)?a&&(h.closeTab(w),c.loginUnlock.showLoginAttemptsExceededNotification()):f({status:!1,maxRetryCountExceed:a})});return!0;case M.SHOW_LOGIN_ATTEMPT_EXCEEDED_NOTIFICATION:h.closeTab(w);c.loginUnlock.showLoginAttemptsExceededNotification();break;case n.idsSettings.MESSAGES.GET_IDS_SETTING:m=Q.getSettings();f(m[d]);break;case n.idsSettings.MESSAGES.GET_ALL_IDS_SETTINGS:d=Q.getSettings();
f(d);break;case N.OPEN_CREATE_VAULT:h.updateTabUrl(h.getTabID(q),h.getExtensionURL(c.uiConstants.NO_VAULT.CREATE_VAULT_URL));break;case N.UI_INIT:d={};d.direction=t.getCurrentLanguageDirection();d.strings=t.getLocalizedStrings(ea);Object.assign(d.strings,t.getLocalizedStringsWithFormat(p.NO_VAULT.formatStrings));d.email=g.session.getEmail();f(d);break;case O.UI_INIT:if(c.vaultKeys.isLocked()||l(c.vaultKeys.isLocked())){f();break}d={};d.direction=b.localizer.getCurrentLanguageDirection();d.strings=
b.localizer.getLocalizedStrings(ia);d.email=g.session.getEmail();d.settings=Q.getSettings();d.registeredDate=c.vaultUnlockSettings.getRegisteredTime();d.autoMobileUnlockRequest=c.vaultUnlockSettings.isAutoMobileUnlockRequestEnabled();m=c.vaultUnlockSettings.getRegisteredDevice();C=null;v(m)&&(m=c.proto.devices.Device.decode64(m),C=m.name);d.deviceName=C;f(d);break;case O.RESTORE_DEFAULT_SETTINGS:c.settings.resetSettings();f(c.settings.getSettings());break;case O.SET_SETTINGS:c.settings.setSettings(d);
break;case O.INITIALIZE_VERIFY_VAULT_PASSWORD:return c.verifyPasswordRequest.beginOrContinueVerifyVaultPasswordFlow(w,h.getWindowIDForTab(q),function(a){f({result:a})}),!0;case X.GENERATE_PASSWORD:d=c.passwordGenerator.createPassword(d.length,d.includeLetters,d.includeMixedCase,d.includeSymbols,d.includeNumbers);m=c.securityDashboard.utils.getPasswordInfo(d);f({password:d,strength:m.strength});break;case X.GENERATE_MULTIPLE_PASSWORD:d=c.passwordGenerator.createMultiplePassword(d.length,d.includeLetters,
d.includeMixedCase,d.includeSymbols,d.includeNumbers,d.count);f({passwordArray:d});break;case D.LOGINS_VIEW_MESSAGES:return J.handleMessage(m.payload);case D.POPUP_SELECTED_LOGIN_VIEW:d=A.getItemManager(A.constructor.LOGIN_MANAGER).getItem(m.payload.loginId);m={};v(d)&&(m.id=d.getPath(),m.loginURL=d.getLoginURL(),m.siteName=d.getSiteName(),m.username=d.getUsername(),m.password=d.getPassword(),m.favorite=d.getFavorite());f(m);break;case D.POPUP_SET_LOGIN_FAVORITE:e.updateLoginFavorite(m.payload.id,
m.payload.isFavorite);break;case D.CLOSE_VAULT_CLICKED:case D.CANCEL_CLICKED:case D.MISC_OPTIONS_CLICKED:J.handleMessage(m.payload);break;case D.OPEN_VAULT_CLICKED:case D.SIGNIN_CLICKED:e.isDeleteVaultFlow=!1;c.vaultUnlockManager.automaticMobileUnlockRequest=!1;z.openLoginFlow();r===D.SIGNIN_CLICKED&&(d=c.extension.getVersion(),c.telemetryWrapper.sendBrowserSignin(d));break;case na.UI_INIT:d={};d.direction=t.getCurrentLanguageDirection();d.strings=t.getLocalizedStrings(ma);Object.assign(d.strings,
t.getLocalizedStringsWithFormat(p.SETUP_VAULT.formatStrings));d.email=g.session.getEmail();f(d);break;case T.UI_INIT:l(a.IDSafe.chromeGlobal.isDeleteVaultFlow)||!1===a.IDSafe.chromeGlobal.isDeleteVaultFlow||h.getTabID(q)!==z._tabID?f(null):(a.IDSafe.chromeGlobal.isDeleteVaultFlow=!1,d={},d.direction=b.localizer.getCurrentLanguageDirection(),d.strings=b.localizer.getLocalizedStrings(oa),d.email=g.session.getEmail(),f(d));break;case S.UI_INIT:d={};d.direction=t.getCurrentLanguageDirection();d.strings=
t.getLocalizedStrings(qa);f(d);break;case S.NUDGE_SCREEN_SHOWN:y.setValue(n.NUDGE_SCREEN_OPEN,!0);break;case S.NUDGE_SCREEN_CLOSED:y.setValue(n.NUDGE_SCREEN_OPEN,!1);break;case S.GET_NUDGE_SCREEN_STATUS:f(y.getValue(n.NUDGE_SCREEN_OPEN));break;default:return H.handleMessage(m,f,q)}};e.handleClose=function(a,b){z.onTabClosed(a,e.isDeleteVaultFlow);P.onTabClosed(a);J.onTabClosed(a);c.exportData.onTabClosed(a);c.vaultTabUI.controller.onTabClosed(a)};e.handleWindowClose=function(a){z.onWindowClosed(a);
P.onWindowClosed(a);J.onWindowClosed(a);c.exportData.onWindowClosed(a);c.vaultTabUI.controller.onWindowClosed(a)};e.handleTabReplace=function(a,b){z.onTabReplaced(a,b);G.onTabReplaced(a,b)};e.initialize=function(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){switch(f.nextAddress){case 1:e._checkForInstallUpdate();e.handleTelemetryOptOut();h.addTabReplacedEventListener(e.handleTabReplace);h.addTabRemovedEventListener(e.handleClose);h.addTabActivatedEventListener(e.handleActivate);
h.addMessageListener(e.handleMessage);h.addMessageListener(c.passwordStrength.handlePasswordMeterRequests);h.addMessageListener(e.handlePagePopupMessage);h.addWindowRemovedEventListener(e.handleWindowClose);h.addWindowFocusedEventListener(e.handleWindowFocusChange);H.setBrowserActionIcon(!1);c.cctWorker.initializeCCTWorker(b.localizer.getNavigatorLanguage());if(!c.vaultUnlockSettings.isAutoMobileUnlockRequestEnabled())return k.info("Auto Unlock Request not sent to mobile since it is disabled"),f.return();
c.vaultKeys.isLocked()&&v(c.vaultUnlockSettings.getRegisteredDevice())&&(c.vaultUnlockManager.automaticMobileUnlockRequest=!0,c.session.doesVaultExist(function(a,b,f){v(f)?k.error(f):!0===a&&(c.vaultUnlockManager.showMobileUnlockNotification(Z.UNLOCK_REQUEST_SENT),c.vaultUnlockManager.unlockVaultWithMobile(c.vaultUnlockManager.unlockVaultNotificationCallback))}));f.setCatchFinallyBlocks(2);return f.yield(e._initializeHeartBeatSDK(),4);case 4:f.leaveTryBlock(3);break;case 2:a=f.enterCatchBlock(),k.error("Error in initializing HeartbeatSDK. Error : "+
a);case 3:if("Safari"!=b.globals.BROWSER)try{e._initializeFGHelperSDK()}catch(q){k.error("Error in initializing FGHelperSDK. Error : "+q)}try{e._initializeActiveVaultUserPingObj()}catch(q){k.error("Error in creating recurrent ping. Error : "+q)}f.jumpToEnd()}})};e._initializeHeartBeatSDK=function(){var a="Norton Identity Safe_"+b.extensionAdapter.getExtensionId(),f=new HeartbeatSDK.HBConfig;f.prodName=a;f.prodVersion=c.extension.getVersion();f.machineId=c.extension.getClientID();f.dataSource=n.HEARTBEAT.BROWSER_EXTENSION;
f.apiKey=c.constants.TELEMETRY_TRACKING_ID;f.userLanguage=navigator.language;f.isInstallPingEnabled=!0;f.isFreshInstall=e.isInstall;f.isHeartBeatPingEnabled=!0;f.heartBeatIntervalInMilliSec=n.HEARTBEAT.HEARTBEAT_PING_INTERVAL_TIME;f.isTelemetryEnabled=b.telemetrySettings.isTelemetryEnabled();return HeartbeatSDK.hbManager.init(f)};e._initializeFGHelperSDK=function(){var a=new fgHelperSDK.FGHelperConfig;a.prodVersion=c.extension.getVersion();fgHelperSDK.fgHelperBG.init(a)};e._initializeActiveVaultUserPingObj=
function(){var a=t.getLocalizedString("__LONG_PRODUCT_NAME__")+"_"+b.extensionAdapter.getExtensionId(),f=new HeartbeatSDK.HBRecurrentPingConfig;f.prodName=a;f.prodVersion=c.extension.getVersion();f.machineId=c.extension.getClientID();f.apiKey=c.constants.TELEMETRY_TRACKING_ID;f.dataSource=n.HEARTBEAT.BROWSER_EXTENSION;f.userLanguage=navigator.language;f.pingIntervalInMillis=n.HEARTBEAT.ACTIVE_VAULT_USERS_PING_INTERVAL;f.pingName=n.HEARTBEAT.ACTIVE_VAULT_USERS;f.pingData=e._getActiveVaultUserPingData();
HeartbeatSDK.hbRecurrentPingManager.createPing(f)};e._getActiveVaultUserPingData=function(){var a={};return a[aa.parameters.ACTION]=n.HEARTBEAT.VAULT_OPEN,a[aa.parameters.CATEGORY]=n.HEARTBEAT.ACTIVE_USERS,a};e.handleTelemetryOptOut=function(){if(!b.telemetrySettings.isTelemetryEnabled()){var a=b.telemetrySettings.getLastOfferDate(),f=!1;l(a)?f=!0:"Firefox"!==b.globals.BROWSER&&new Date-a>c.constants.telemetryOptOut.REOFFER_TIME_WINDOW&&(f=!0);f&&e._showTelemetryNotification(c.constants.telemetryOptOut.NOTIFICATION_LEEWAY+
1E3*Math.random())}};e._showTelemetryNotification=function(a){setTimeout(function(){if(!b.telemetrySettings.isTelemetryEnabled()){var a=t.getLocalizedStringWithFormat("Thank you for using {0}! Share usage and error data anonymously with Norton to help make our products even better.",[t.getLocalizedString("__LONG_PRODUCT_NAME__")]),g=t.getLocalizedString("OK"),h=t.getLocalizedString("Learn More"),m=t.getLocalizedString("No, thanks");a=new b.QuestionNotification(a,{},g,function(a){b.telemetrySettings.setTelemetryEnabled(!0);
b.telemetrySettings.setUserRespondedInOptOutPage(!0)},c.notificationIcon.getInfoIcon());a.addSecondaryLink(h,function(a){b.extensionAdapter.createTab("https://www.symantec.com/privacy/product-privacy-statements/norton-browser-extensions-privacy-notice");e._showTelemetryNotification(50)});a.addThirdButton(m,function(a){b.telemetrySettings.setTelemetryEnabled(!1);b.telemetrySettings.setUserRespondedInOptOutPage(!0)});a.addCloseButtonAction(function(a){b.telemetrySettings.setTelemetryEnabled(!1);b.telemetrySettings.setUserRespondedInOptOutPage(!0)});
b.telemetrySettings.setLastOfferDate(new Date);b.notificationCenter.addNotification(a)}},a)};e.load=function(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){switch(b.nextAddress){case 1:return b.setCatchFinallyBlocks(2),b.yield(c.init.ready(),4);case 4:return b.yield(e.initialize(),5);case 5:b.leaveTryBlock(0);break;case 2:a=b.enterCatchBlock(),k.error(a),b.jumpToEnd()}})};e.isUrlInList=function(a,b){if(l(b))return!1;for(var c in a){var f=a[c],e=f.length;if(b===f||b.substring(b.length-
e-1)==="."+f)return!0}return!1};e.isUrlExcluded=function(a){for(var b in e.waxProcessingExclusionList)if(a===B(e.waxProcessingExclusionList[b]))return!0;return!1};e._reloadOnboardingPageIfAny=function(){"Safari"!==b.globals.BROWSER&&"Edge"!==b.globals.BROWSER||h.getAllTabs(function(a){a.forEach(function(a){var b=a.url;l(b)||(new URI(b)).domain()!==n.ONBOARDING_URL_DOMAIN||(b=h.getTabID(a),h.updateTabUrl(b,a.url,null),h.activateTab(b))})})};e._checkForInstallUpdate=function(){var a=y.getValue(n.STORED_VERSION),
b=n.VERSION;c.welcomeNotification.show();e.isInstall=!1;l(a)?(e.isInstall=!0,c.telemetryWrapper.sendExtensionInstall(),y.setValue(n.STORED_VERSION,b),e._reloadOnboardingPageIfAny(),h.createTab(h.getExtensionURL(c.uiConstants.NUDGE_SCREEN.CONTENT_PAGE_URL))):b!==a&&(ja(a,b)&&y.setValue(n.WELCOME_NOTIFICATION_CLICKED,!0),c.telemetryWrapper.sendExtensionUpdate(),y.setValue(n.STORED_VERSION,b))};e._closeExistingIDSTabs=function(){var a=[h.getExtensionURL("content/ui/no-vault.html"),h.getExtensionURL("content/ui/vault-setup-complete.html"),
h.getExtensionURL("content/ui/vault-unlock.html")];h.getAllTabs(function(c){c.forEach(function(c){for(var e=!1,f=0;f<a.length;f++)if(c.url===a[f]){e=!0;break}f=h.getTabID(c);!0===e?h.closeTabAndEnsureBrowserIsAlive(f):("Safari"!==b.globals.BROWSER||v(c.page))&&h.sendMessageToTab(c,{id:u.NA_LOGGEDOUT,payload:{tabId:f}})})})};e._doExecuteScript=function(a,b){return new Promise(function(c,e){l(a)||l(b)?e():chrome.tabs.executeScript(a,{file:b},function(a){var d=h.getLastError();l(a)||v(d)?(k.error("Failed during execute script : "+
b),e()):c()})})};e._executeScripts=function(a){var c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){switch(f.nextAddress){case 1:return f.setCatchFinallyBlocks(2),f.yield(e._doExecuteScript(a,"content/libs/uri.min.js"),4);case 4:return f.yield(e._doExecuteScript(a,"content/scripts/IDSContextInit.js"),5);case 5:return f.yield(e._doExecuteScript(a,"content/scripts/SymBfwCS.js"),6);case 6:return f.yield(e._doExecuteScript(a,"content/scripts/IDSPortalUtils.js"),7);case 7:return f.yield(e._doExecuteScript(a,
"content/scripts/IDSPortal.js"),8);case 8:if("Chrome"!==b.globals.BROWSER){f.jumpTo(9);break}return f.yield(e._doExecuteScript(a,"content/scripts/portalInstallFlowCS.js"),9);case 9:f.leaveTryBlock(0);break;case 2:c=f.enterCatchBlock(),k.error(c),f.jumpToEnd()}})};e._getAllTabsPromise=function(){return new Promise(function(a,b){try{h.getAllTabs(function(b){a(b)})}catch(q){b(q)}})};e.onInstall=function(){var a,f,g;return $jscomp.asyncExecutePromiseGeneratorProgram(function(h){if(1==h.nextAddress)return h.setCatchFinallyBlocks(2),
h.yield(e._getAllTabsPromise(),4);if(2!=h.nextAddress)return a=h.yieldResult,f=!1,a.forEach(function(a){var d=a.url;if(!l(d)){var g=new URI(d);g.domain()===n.ONBOARDING_PORTAL_DOMAIN&&!1!==n.ONBOARDING_PORTAL_SUBDOMAIN.includes(g.subdomain())&&(a=a&&a.id,("Chrome"===b.globals.BROWSER||"Firefox"===b.globals.BROWSER)&&a&&e._executeScripts(a),f=!0,d=(new URI(d)).query(!0),c.cguid=d[n.CGUID])}}),f&&v(c.cguid)?h.return(Promise.resolve(c.cguid)):h.return(Promise.resolve("Not a portal page"));g=h.enterCatchBlock();
return h.return(Promise.reject(g))})};return e}(SymBfw,SymO2,IDSafe)})(executionContext);window.addEventListener("load",function(a){IDSafe.chromeGlobal.load()});
