var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,f){a!=Array.prototype&&a!=Object.prototype&&(a[b]=f.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(f){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(f||"")+"_"+b++,f)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var f=0,e={next:function(){if(f<a.length){var l=f++;return{value:b(l,a[l]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};
$jscomp.polyfill=function(a,b,f,e){if(b){f=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var l=a[e];l in f||(f[l]={});f=f[l]}a=a[a.length-1];e=f[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(f,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");var apiGateway=apiGateway||{};apiGateway.core=apiGateway.core||{};apiGateway.core.sigV4ClientFactory={};
apiGateway.core.sigV4ClientFactory.newClient=function(a){function b(a,b){return CryptoJS.HmacSHA256(b,a,{asBytes:!0})}function f(a){if(1>Object.keys(a).length)return"";var b=[];for(d in a)a.hasOwnProperty(d)&&b.push(d);b.sort();var d="";for(var c=0;c<b.length;c++)d+=b[c]+"="+e(a[b[c]])+"&";return d.substr(0,d.length-1)}function e(a){return encodeURIComponent(a).replace(/[!'()*]/g,function(a){return"%"+a.charCodeAt(0).toString(16).toUpperCase()})}function l(a){var b=[],c;for(c in a)a.hasOwnProperty(c)&&
b.push(c.toLowerCase());b.sort();return b.join(";")}var c={};if(void 0===a.accessKey||void 0===a.secretKey)return c;c.accessKey=apiGateway.core.utils.assertDefined(a.accessKey,"accessKey");c.secretKey=apiGateway.core.utils.assertDefined(a.secretKey,"secretKey");c.sessionToken=a.sessionToken;c.serviceName=apiGateway.core.utils.assertDefined(a.serviceName,"serviceName");c.region=apiGateway.core.utils.assertDefined(a.region,"region");c.endpoint=apiGateway.core.utils.assertDefined(a.endpoint,"endpoint");
c.makeRequest=function(d){var e=apiGateway.core.utils.assertDefined(d.verb,"verb"),p=apiGateway.core.utils.assertDefined(d.path,"path"),n=apiGateway.core.utils.copy(d.queryParams);void 0===n&&(n={});var g=apiGateway.core.utils.copy(d.headers);void 0===g&&(g={});void 0===g["Content-Type"]&&(g["Content-Type"]=a.defaultContentType);void 0===g.Accept&&(g.Accept=a.defaultAcceptType);d=apiGateway.core.utils.copy(d.body);d=void 0===d||"GET"===e?"":JSON.stringify(d);""!==d&&void 0!==d&&null!==d||delete g["Content-Type"];
var m=(new Date).toISOString().replace(/\.\d{3}Z$/,"Z").replace(/[:\-]|\.\d{3}/g,"");g["x-amz-date"]=m;var k=document.createElement("a");k.href=c.endpoint;g.host=k.hostname;var h,q=n;k=g;var r=d;q=e+"\n"+encodeURI(p)+"\n"+f(q)+"\n";var u="",t=[];for(h in k)k.hasOwnProperty(h)&&t.push(h);t.sort();for(h=0;h<t.length;h++)u+=t[h].toLowerCase()+":"+k[t[h]]+"\n";h=q+u+"\n"+l(k)+"\n"+CryptoJS.SHA256(r).toString(CryptoJS.enc.Hex);k=CryptoJS.SHA256(h).toString(CryptoJS.enc.Hex);h=c.region;r=c.serviceName;
h=m.substr(0,8)+"/"+h+"/"+r+"/aws4_request";k="AWS4-HMAC-SHA256\n"+m+"\n"+h+"\n"+k;r=c.region;q=c.serviceName;m=b(b(b(b("AWS4"+c.secretKey,m.substr(0,8)),r),q),"aws4_request");k=b(m,k).toString(CryptoJS.enc.Hex);m=g;h="AWS4-HMAC-SHA256 Credential="+c.accessKey+"/"+h+", SignedHeaders="+l(g)+", Signature="+k;m.Authorization=h;void 0!==c.sessionToken&&""!==c.sessionToken&&(g["x-amz-security-token"]=c.sessionToken);delete g.host;p=a.endpoint+p;n=f(n);""!=n&&(p+="?"+n);void 0===g["Content-Type"]&&(g["Content-Type"]=
a.defaultContentType);return axios({method:e,url:p,headers:g,data:d})};return c};
